package org.egov.payment.model;

// Generated Mar 10, 2008 12:54:41 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * Billcollector generated by hbm2java
 */
public class Billcollector implements java.io.Serializable
{

	private Integer id;

	private String code;

	private String name;

	private BigDecimal departmentid;

	private BigDecimal cashinhand;

	private BigDecimal chequeinhand;

	private String type;

	private BigDecimal zoneid;

	private BigDecimal regionid;

	private String narration;

	private boolean isactive;

	private Date lastmodified;

	private Date created;

	private BigDecimal modifiedby;
	public Billcollector()
	{
	}

	public Billcollector(Integer id, String code, String name,
			BigDecimal departmentid, String type, boolean isactive, Date created)
	{
		this.id = id;
		this.code = code;
		this.name = name;
		this.departmentid = departmentid;
		this.type = type;
		this.isactive = isactive;
		this.created = created;
	}

	public Billcollector(Integer id, String code, String name,
			BigDecimal departmentid, BigDecimal cashinhand,
			BigDecimal chequeinhand, String type, BigDecimal zoneid,
			BigDecimal regionid, String narration, boolean isactive,
			Date lastmodified, Date created, BigDecimal modifiedby)
	{
		this.id = id;
		this.code = code;
		this.name = name;
		this.departmentid = departmentid;
		this.cashinhand = cashinhand;
		this.chequeinhand = chequeinhand;
		this.type = type;
		this.zoneid = zoneid;
		this.regionid = regionid;
		this.narration = narration;
		this.isactive = isactive;
		this.lastmodified = lastmodified;
		this.created = created;
		this.modifiedby = modifiedby;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public BigDecimal getDepartmentid()
	{
		return this.departmentid;
	}

	public void setDepartmentid(BigDecimal departmentid)
	{
		this.departmentid = departmentid;
	}

	public BigDecimal getCashinhand()
	{
		return this.cashinhand;
	}

	public void setCashinhand(BigDecimal cashinhand)
	{
		this.cashinhand = cashinhand;
	}

	public BigDecimal getChequeinhand()
	{
		return this.chequeinhand;
	}

	public void setChequeinhand(BigDecimal chequeinhand)
	{
		this.chequeinhand = chequeinhand;
	}

	public String getType()
	{
		return this.type;
	}

	public void setType(String type)
	{
		this.type = type;
	}

	public BigDecimal getZoneid()
	{
		return this.zoneid;
	}

	public void setZoneid(BigDecimal zoneid)
	{
		this.zoneid = zoneid;
	}

	public BigDecimal getRegionid()
	{
		return this.regionid;
	}

	public void setRegionid(BigDecimal regionid)
	{
		this.regionid = regionid;
	}

	public String getNarration()
	{
		return this.narration;
	}

	public void setNarration(String narration)
	{
		this.narration = narration;
	}

	public boolean isIsactive()
	{
		return this.isactive;
	}

	public void setIsactive(boolean isactive)
	{
		this.isactive = isactive;
	}

	public Date getLastmodified()
	{
		return this.lastmodified;
	}

	public void setLastmodified(Date lastmodified)
	{
		this.lastmodified = lastmodified;
	}

	public Date getCreated()
	{
		return this.created;
	}

	public void setCreated(Date created)
	{
		this.created = created;
	}

	public BigDecimal getModifiedby()
	{
		return this.modifiedby;
	}

	public void setModifiedby(BigDecimal modifiedby)
	{
		this.modifiedby = modifiedby;
	}
}
