package org.egov.model.bills;

// Generated Jul 30, 2007 12:27:25 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EgBilldetails generated by hbm2java
 */
public class EgBilldetails implements java.io.Serializable {

	private Integer id;

	private EgBillregister egBillregister;

	private BigDecimal functionid;

	private BigDecimal glcodeid;

	private BigDecimal debitamount;

	private BigDecimal creditamount;

	private Date lastupdatedtime;
	
	private String narration;
	
	private Set<EgBillPayeedetails> egBillPaydetailes = new HashSet<EgBillPayeedetails>(0);

	public EgBilldetails() {
	}

	public EgBilldetails(Integer id, EgBillregister egBillregister,
			BigDecimal glcodeid, Date lastupdatedtime) {
		this.id = id;
		this.egBillregister = egBillregister;
		this.glcodeid = glcodeid;
		this.lastupdatedtime = lastupdatedtime;
	}

	public EgBilldetails(Integer id, EgBillregister egBillregister,
			BigDecimal functionid, BigDecimal glcodeid, BigDecimal debitamount,
			BigDecimal creditamount, Date lastupdatedtime , Set<EgBillPayeedetails> egBillPaydetailes,String narration) {
		this.id = id;
		this.egBillregister = egBillregister;
		this.functionid = functionid;
		this.glcodeid = glcodeid;
		this.debitamount = debitamount;
		this.creditamount = creditamount;
		this.lastupdatedtime = lastupdatedtime;
		this.egBillPaydetailes = egBillPaydetailes;
		this.narration=narration;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public EgBillregister getEgBillregister() {
		return this.egBillregister;
	}

	public void setEgBillregister(EgBillregister egBillregister) {
		this.egBillregister = egBillregister;
	}

	public BigDecimal getFunctionid() {
		return this.functionid;
	}

	public void setFunctionid(BigDecimal functionid) {
		this.functionid = functionid;
	}

	public BigDecimal getGlcodeid() {
		return this.glcodeid;
	}

	public void setGlcodeid(BigDecimal glcodeid) {
		this.glcodeid = glcodeid;
	}

	public BigDecimal getDebitamount() {
		return this.debitamount;
	}

	public void setDebitamount(BigDecimal debitamount) {
		this.debitamount = debitamount;
	}

	public BigDecimal getCreditamount() {
		return this.creditamount;
	}

	public void setCreditamount(BigDecimal creditamount) {
		this.creditamount = creditamount;
	}

	public Date getLastupdatedtime() {
		return this.lastupdatedtime;
	}

	public void setLastupdatedtime(Date lastupdatedtime) {
		this.lastupdatedtime = lastupdatedtime;
	}

	public Set<EgBillPayeedetails> getEgBillPaydetailes() {
		return egBillPaydetailes;
	}

	public void setEgBillPaydetailes(Set<EgBillPayeedetails> egBillPaydetailes) {
		this.egBillPaydetailes = egBillPaydetailes;
	}

	public String getNarration() {
		return narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}
	public void addEgBillPayeedetail(EgBillPayeedetails egbillpayee)
	{			
		if(egbillpayee!=null) 
			getEgBillPaydetailes().add(egbillpayee);
	}
	public void removeEgBillPayeedetail(EgBillPayeedetails egbillpayee)
	{			
		if(egbillpayee!=null)
			getEgBillPaydetailes().remove(egbillpayee);
	}
}
