package org.egov.assets.service;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.egov.assets.model.Asset;
import org.egov.assets.model.VoucherInput;

/**
 * This class will have all business logic related to Asset Master.
 * @author Nils
 *
 */
public interface AssetService extends BaseService<Asset,Long> {
	
	public void setAssetNumber(Asset entity);
	
	public boolean isAssetCodeAutoGenerated();
	
	public void capitaliseAsset(Asset asset, List<VoucherInput> voucherInputList, Date dateOfCapitalisation,
			BigDecimal assetIndrctExpns,Integer projectType);
	
	public BigDecimal getDepreciationAmt(Asset asset);
}
