package org.egov.asset.service.impl;

import java.util.Date;

import org.apache.log4j.Logger;
import org.egov.asset.model.Asset;
import org.egov.asset.model.AssetNumberGenrator;
import org.egov.asset.service.AppService;
import org.egov.asset.service.AssetService;
import org.egov.commons.EgwStatus;
import org.egov.infstr.services.PersistenceService;

/**
 * This class will expose all asset master related operations.
 * @author Nils
 *
 */
public class AssetServiceImpl extends BaseServiceImpl<Asset, Long> implements AssetService{

	private static final Logger logger = Logger.getLogger(AssetServiceImpl.class);
	private AppService appService;
	private AssetNumberGenrator assetNumberGenrator;
	public AssetServiceImpl(PersistenceService<Asset, Long> persistenceService) {
		super(persistenceService);
	}
	
	@Override
	public void setAssetNumber(Asset entity){
		String year = getFinancialYear(entity.getDateOfCreation());
		if(entity!=null && (entity.getId()==null || entity.getCode()==null || "".equals(entity.getCode())) && isAssetCodeAutoGenerated()){
			logger.info("---Auto generating Asset code....");
			entity.setCode(assetNumberGenrator.getAssetNumber(entity, year));
		}
	}
	
	@Override
	public boolean isAssetCodeAutoGenerated() {
		String isAutoGenerated = appService.getUniqueAppConfigValue("IS_ASSET_CODE_AUTOGENERATED");
		if("yes".equalsIgnoreCase(isAutoGenerated))
			return true;
		return false;
	}
	
	private void changeAssetToCapitaliseStatus(Asset asset, String statusCode, Date dateOfCapitalisation){
		EgwStatus egwStatus = getAssetStatusByCode(statusCode); 
		asset.setStatus(egwStatus); 		
	}
	
	
	public void setAppService(AppService appService) {
		this.appService = appService;
	}
	
	public void setAssetNumberGenrator(
			AssetNumberGenrator assetNumberGenrator) {
		this.assetNumberGenrator = assetNumberGenrator;
	}
	
}
