package org.egov.asset.service.impl;

import org.apache.log4j.Logger;
import org.egov.asset.model.AssetCategory;
import org.egov.asset.model.AssetCategoryNumberGenrator;
import org.egov.asset.service.AppService;
import org.egov.asset.service.AssetCategoryService;
import org.egov.commons.CFinancialYear;
import org.egov.infstr.services.PersistenceService;

/**
 * This class will expose all asset category related operations.
 * @author Nils
 *
 */
public class AssetCategoryServiceImpl extends BaseServiceImpl<AssetCategory, Long>
										implements AssetCategoryService{

	private static final Logger logger = Logger.getLogger(AssetCategoryServiceImpl.class);
	private AppService appService;
	private AssetCategoryNumberGenrator assetCategoryNumberGenrator;
	
	public AssetCategoryServiceImpl(PersistenceService<AssetCategory, Long> persistenceService) {
		super(persistenceService);
	}
	
	@Override
	public void setAssetCategoryNumber(AssetCategory entity){
		// CFinancialYear financialYear = getCurrentFinancialYear(entity.getCreatedDate());
		CFinancialYear financialYear = new CFinancialYear();
		if(entity!=null && (entity.getId()==null || entity.getCode()==null || "".equals(entity.getCode())) && isAssetCategoryCodeAutoGenerated()){
			logger.info("---Auto generating Asset Category code....");
			entity.setCode(assetCategoryNumberGenrator.getAssetCategoryNumber(entity, financialYear));
		}
	}
	
	@Override
	public boolean isAssetCategoryCodeAutoGenerated() {
		String isAutoGenerated = appService.getUniqueAppConfigValue("IS_ASSET_CATEGORYCODE_AUTOGENERATED");
		if("yes".equalsIgnoreCase(isAutoGenerated))
			return true;
		return false;
	}

	public void setAppService(AppService appService) {
		this.appService = appService;
	}
	
	public void setAssetCategoryNumberGenrator(
			AssetCategoryNumberGenrator assetCategoryNumberGenrator) {
		this.assetCategoryNumberGenrator = assetCategoryNumberGenrator;
	}
	
}
