var tree_data = [
	['Title', 'Files/9.gif', '', 'Topics/IDH_Topic10.htm', null],
	['Legal', 'Files/9.gif', '', 'Topics/IDH_Topic20.htm', null],
	['Preface', 'Files/9.gif', '', 'Topics/IDH_Topic480.htm', null],
	['Introduction to eGov Financials', 'Files/9.gif', '', 'Topics/IDH_Topic960.htm', null],
	['Volume I: Masters', 'Files/1.gif', 'Files/2.gif', '',
		['Chapter 1: Chart of Accounts', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic450.htm', null],
			['Creating/Modifying Source of Financing', 'Files/9.gif', '', 'Topics/IDH_Topic520.htm', null],
			['Creating/Modifying Account Codes', 'Files/9.gif', '', 'Topics/IDH_Topic460.htm', null],
			['Viewing Account Codes', 'Files/9.gif', '', 'Topics/IDH_Topic1120.htm', null],
			['Creating/Modifying Funds', 'Files/9.gif', '', 'Topics/IDH_Topic180.htm', null],
			['Creating/Modifying Functions', 'Files/9.gif', '', 'Topics/IDH_Topic190.htm', null]
		],
		['Chapter 2: Sub-Ledgers', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic730.htm', null],
			['Accounting Entity', 'Files/9.gif', '', 'Topics/IDH_Topic530.htm', null],
			['User-Defined Codes', 'Files/9.gif', '', 'Topics/IDH_Topic510.htm', null]
		],
		['Chapter 3: Banks', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic1000.htm', null],
			['Create a Bank', 'Files/9.gif', '', 'Topics/IDH_Topic490.htm', null],
			['Modify a Bank', 'Files/9.gif', '', 'Topics/IDH_Topic500.htm', null]
		],
		['Chapter 4: Schemes/Sub-Schemes', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic470.htm', null],
			['Create a Scheme', 'Files/9.gif', '', 'Topics/IDH_Topic420.htm', null],
			['View a Scheme', 'Files/9.gif', '', 'Topics/IDH_Topic430.htm', null],
			['Modify a Scheme', 'Files/9.gif', '', 'Topics/IDH_Topic440.htm', null]
		],
		['Chapter 5: Suppliers/Contractors', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic1010.htm', null],
			['Create Supplier or Contractor', 'Files/9.gif', '', 'Topics/IDH_Topic390.htm', null],
			['View Supplier or Contractor', 'Files/9.gif', '', 'Topics/IDH_Topic400.htm', null],
			['Modify Supplier or Contractor', 'Files/9.gif', '', 'Topics/IDH_Topic410.htm', null]
		],
		['Procurement Orders', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic1020.htm', null],
			['Creating Procurement Orders', 'Files/9.gif', '', 'Topics/IDH_Topic360.htm', null],
			['Viewing Procurement Orders', 'Files/9.gif', '', 'Topics/IDH_Topic370.htm', null],
			['Modifying Procurement Orders', 'Files/9.gif', '', 'Topics/IDH_Topic380.htm', null]
		],
		['Chapter 6: Period-End Activities', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic910.htm', null],
			['Creating a Financial Year', 'Files/9.gif', '', 'Topics/IDH_Topic920.htm', null],
			['Creating an Opening Balance', 'Files/9.gif', '', 'Topics/IDH_Topic930.htm', null],
			['Closing a Period', 'Files/9.gif', '', 'Topics/IDH_Topic940.htm', null]
		],
		['Collection/Payment Point', 'Files/9.gif', '', 'Topics/IDH_Topic1030.htm', null],
		['Check In Hand/Cash in Hand', 'Files/9.gif', '', 'Topics/IDH_Topic1470.htm', null]
	],
	['Volume II: Setup', 'Files/1.gif', 'Files/2.gif', '',
		['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic230.htm', null],
		['Chapter 1: Salary Codes', 'Files/1.gif', 'Files/2.gif', '',
			['Create Salary Codes', 'Files/9.gif', '', 'Topics/IDH_Topic760.htm', null],
			['View Salary Codes', 'Files/9.gif', '', 'Topics/IDH_Topic770.htm', null],
			['Modify Salary Codes', 'Files/9.gif', '', 'Topics/IDH_Topic790.htm', null]
		],
		['Chapter 2: Report Scheduling', 'Files/1.gif', 'Files/2.gif', '',
			['Create Report Schedule', 'Files/9.gif', '', 'Topics/IDH_Topic1100.htm', null],
			['View/Modify Report Schedule', 'Files/9.gif', '', 'Topics/IDH_Topic1110.htm', null]
		],
		['Chapter 3: Party Types', 'Files/1.gif', 'Files/2.gif', '',
			['Create Party Types', 'Files/9.gif', '', 'Topics/IDH_Topic780.htm', null],
			['View Party Types', 'Files/9.gif', '', 'Topics/IDH_Topic800.htm', null],
			['Modify Party Types', 'Files/9.gif', '', 'Topics/IDH_Topic810.htm', null]
		],
		['Chapter 4: Contract Types', 'Files/1.gif', 'Files/2.gif', '',
			['Create Contract Types', 'Files/9.gif', '', 'Topics/IDH_Topic820.htm', null],
			['View Contract Types', 'Files/9.gif', '', 'Topics/IDH_Topic830.htm', null],
			['Modify Contract Types', 'Files/9.gif', '', 'Topics/IDH_Topic840.htm', null]
		],
		['Create ULB Details', 'Files/9.gif', '', 'Topics/IDH_Topic900.htm', null]
	],
	['Volume III: Transactions', 'Files/1.gif', 'Files/2.gif', '',
		['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic890.htm', null],
		['Chapter 1: Receipts', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic1130.htm', null],
			['Creating a Receipt', 'Files/9.gif', '', 'Topics/IDH_Topic1140.htm', null],
			['Reversing a Receipt', 'Files/9.gif', '', 'Topics/IDH_Topic1170.htm', null],
			['Modifying a Receipt', 'Files/9.gif', '', 'Topics/IDH_Topic1160.htm', null]
		],
		['Chapter 2: Salary Bills and Salary Bill Vouchers-Internal', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic1040.htm', null],
			['Create Salary Bills', 'Files/9.gif', '', 'Topics/IDH_Topic250.htm', null],
			['View Salary Bills', 'Files/9.gif', '', 'Topics/IDH_Topic260.htm', null],
			['Modify Salary Bills', 'Files/9.gif', '', 'Topics/IDH_Topic270.htm', null],
			['Approve Salary Bills', 'Files/9.gif', '', 'Topics/IDH_Topic280.htm', null],
			['Create a Salary Bill Voucher', 'Files/9.gif', '', 'Topics/IDH_Topic350.htm', null],
			['Modifying a Salary Bill Voucher', 'Files/9.gif', '', 'Topics/IDH_Topic1190.htm', null]
		],
		['Chapter 3: Contractor/Supplier/Expense Bills and Vouchers - Internal', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic950.htm', null],
			['Create Work Bills', 'Files/9.gif', '', 'Topics/IDH_Topic290.htm', null],
			['Create Purchase Bills', 'Files/9.gif', '', 'Topics/IDH_Topic300.htm', null],
			['Create Expense Bills', 'Files/9.gif', '', 'Topics/IDH_Topic310.htm', null],
			['View Bills', 'Files/9.gif', '', 'Topics/IDH_Topic320.htm', null],
			['Modify Bills', 'Files/9.gif', '', 'Topics/IDH_Topic330.htm', null],
			['Cancel Bills', 'Files/9.gif', '', 'Topics/IDH_Topic220.htm', null],
			['Approve Bills and Create Vouchers ', 'Files/9.gif', '', 'Topics/IDH_Topic340.htm', null]
		],
		['Chapter 4: Bills Accounting', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic1150.htm', null],
			['Creating a Bill Voucher', 'Files/9.gif', '', 'Topics/IDH_Topic1050.htm', null],
			['Approving a Bill Voucher', 'Files/9.gif', '', 'Topics/IDH_Topic1060.htm', null]
		],
		['Chapter 5: Payments', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic210.htm', null],
			['Generate a Bank Payment Voucher', 'Files/9.gif', '', 'Topics/IDH_Topic1200.htm', null],
			['Approving a BPV', 'Files/9.gif', '', 'Topics/IDH_Topic1080.htm', null],
			['Reversing a BPV', 'Files/9.gif', '', 'Topics/IDH_Topic1330.htm', null],
			['Direct Bank Payment', 'Files/9.gif', '', 'Topics/IDH_Topic1070.htm', null],
			['Non-Bill Payments', 'Files/9.gif', '', 'Topics/IDH_Topic1480.htm', null],
			['Advance Payment', 'Files/9.gif', '', 'Topics/IDH_Topic1500.htm', null],
			['Assigning a Cheque', 'Files/9.gif', '', 'Topics/IDH_Topic1090.htm', null],
			['Surrendering/Reassigning Cheque', 'Files/9.gif', '', 'Topics/IDH_Topic1180.htm', null],
			['Outstanding Bank Payments', 'Files/9.gif', '', 'Topics/IDH_Topic1360.htm', null],
			['Concurrence Report', 'Files/9.gif', '', 'Topics/IDH_Topic1490.htm', null]
		],
		['Chapter 6: Bank Reconciliation', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic550.htm', null],
			['Reconciling with Bank', 'Files/9.gif', '', 'Topics/IDH_Topic560.htm', null],
			['Reconciliation Summary', 'Files/9.gif', '', 'Topics/IDH_Topic700.htm', null],
			['Dishonored Cheques', 'Files/9.gif', '', 'Topics/IDH_Topic710.htm', null]
		],
		['Chapter 7: Contra Entries', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic620.htm', null],
			['Cash Deposit', 'Files/9.gif', '', 'Topics/IDH_Topic610.htm', null],
			['Cash Withdrawal', 'Files/9.gif', '', 'Topics/IDH_Topic630.htm', null],
			['Bank to Bank Transfer', 'Files/9.gif', '', 'Topics/IDH_Topic640.htm', null],
			['Pay In', 'Files/9.gif', '', 'Topics/IDH_Topic650.htm', null],
			['Modify Contra Entries', 'Files/9.gif', '', 'Topics/IDH_Topic660.htm', null]
		],
		['Chapter 8: Journal Voucher', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic580.htm', null],
			['Creating a Journal Voucher', 'Files/9.gif', '', 'Topics/IDH_Topic570.htm', null],
			['Modifying Journal Vouchers', 'Files/9.gif', '', 'Topics/IDH_Topic590.htm', null]
		],
		['Chapter 9: Processing Bill Vouchers', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic880.htm', null],
			['Viewing Bill Vouchers', 'Files/9.gif', '', 'Topics/IDH_Topic720.htm', null],
			['Canceling Bill Vouchers', 'Files/9.gif', '', 'Topics/IDH_Topic750.htm', null],
			['Confirming Bill Vouchers', 'Files/9.gif', '', 'Topics/IDH_Topic850.htm', null],
			['Reversing a Voucher', 'Files/1.gif', 'Files/2.gif', '',
				['Reversing Contractor/Supplier/Salary/C-Bill Vouchers', 'Files/9.gif', '', 'Topics/IDH_Topic740.htm', null],
				['Reverse Journal Vouchers', 'Files/9.gif', '', 'Topics/IDH_Topic600.htm', null],
				['Reverse Contra Vouchers', 'Files/9.gif', '', 'Topics/IDH_Topic670.htm', null]
			]
		]
	],
	['Volume IV: Deductions', 'Files/1.gif', 'Files/2.gif', '',
		['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic540.htm', null],
		['Creating Remittance Recovery', 'Files/9.gif', '', 'Topics/IDH_Topic970.htm', null],
		['Viewing Remittance Recovery', 'Files/9.gif', '', 'Topics/IDH_Topic980.htm', null],
		['Modifying Remittance Recovery', 'Files/9.gif', '', 'Topics/IDH_Topic990.htm', null]
	],
	['Volume V: Budgeting', 'Files/1.gif', 'Files/2.gif', '',
		['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic30.htm', null],
		['Chapter 1: Budget Definition', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic40.htm', null],
			['Creating a Budget Definition', 'Files/9.gif', '', 'Topics/IDH_Topic50.htm', null],
			['Modifying a Budget Definition', 'Files/9.gif', '', 'Topics/IDH_Topic60.htm', null]
		],
		['Chapter 2: Budget Groups', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic70.htm', null],
			['Creating a Budget Group', 'Files/9.gif', '', 'Topics/IDH_Topic80.htm', null],
			['Modifying a Budget Group', 'Files/9.gif', '', 'Topics/IDH_Topic90.htm', null],
			['Viewing a Budget Group', 'Files/9.gif', '', 'Topics/IDH_Topic100.htm', null]
		],
		['Chapter 3: Budget Details', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic110.htm', null],
			['Adding Budget Details', 'Files/9.gif', '', 'Topics/IDH_Topic120.htm', null],
			['Modifying Budget Details', 'Files/9.gif', '', 'Topics/IDH_Topic130.htm', null]
		],
		['Chapter 4: Budget Reappropriation', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic160.htm', null],
			['Reappropriating a Budget', 'Files/9.gif', '', 'Topics/IDH_Topic170.htm', null],
			['Modifying a Reappropriated Budget', 'Files/9.gif', '', 'Topics/IDH_Topic200.htm', null]
		],
		['Chapter 5: Budget Approval', 'Files/1.gif', 'Files/2.gif', '',
			['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic140.htm', null],
			['Approving a Budget', 'Files/9.gif', '', 'Topics/IDH_Topic150.htm', null]
		]
	],
	['Volume VI: Period-End Activities', 'Files/1.gif', 'Files/2.gif', '',
		['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic910.htm', null],
		['Creating a Financial Year', 'Files/9.gif', '', 'Topics/IDH_Topic920.htm', null],
		['Creating an Opening Balance', 'Files/9.gif', '', 'Topics/IDH_Topic930.htm', null],
		['Closing a Period', 'Files/9.gif', '', 'Topics/IDH_Topic940.htm', null]
	],
	['Volume VII: Reports', 'Files/1.gif', 'Files/2.gif', '',
		['Introduction', 'Files/9.gif', '', 'Topics/IDH_Topic240.htm', null],
		['Financial Statements', 'Files/1.gif', 'Files/2.gif', '',
			['Income/Expenditure Statement', 'Files/9.gif', '', 'Topics/IDH_Topic1210.htm', null],
			['Receipt/Payment', 'Files/9.gif', '', 'Topics/IDH_Topic1220.htm', null],
			['Balance Sheet Report', 'Files/9.gif', '', 'Topics/IDH_Topic1230.htm', null]
		],
		['Accounting Reports', 'Files/1.gif', 'Files/2.gif', '',
			['Trial Balance', 'Files/9.gif', '', 'Topics/IDH_Topic1240.htm', null],
			['Cash Book', 'Files/9.gif', '', 'Topics/IDH_Topic1250.htm', null],
			['Bank Book', 'Files/9.gif', '', 'Topics/IDH_Topic1260.htm', null],
			['Journal Book', 'Files/9.gif', '', 'Topics/IDH_Topic1270.htm', null],
			['General Ledger', 'Files/9.gif', '', 'Topics/IDH_Topic1280.htm', null],
			['Day Book', 'Files/9.gif', '', 'Topics/IDH_Topic1290.htm', null],
			['Sub-Ledger Report', 'Files/9.gif', '', 'Topics/IDH_Topic1300.htm', null],
			['Sub-Ledger Schedule Report', 'Files/9.gif', '', 'Topics/IDH_Topic1310.htm', null],
			['Opening Balance', 'Files/9.gif', '', 'Topics/IDH_Topic1320.htm', null]
		],
		['MIS Reports', 'Files/1.gif', 'Files/2.gif', '',
			['Contractor/Supplier Report', 'Files/9.gif', '', 'Topics/IDH_Topic1340.htm', null],
			['Cheque Issue Register', 'Files/9.gif', '', 'Topics/IDH_Topic1350.htm', null],
			['Bank Transaction', 'Files/9.gif', '', 'Topics/IDH_Topic1380.htm', null],
			['Statement of Outstanding Liability', 'Files/9.gif', '', 'Topics/IDH_Topic1390.htm', null],
			['Functionwise IE Subsidiary Register', 'Files/9.gif', '', 'Topics/IDH_Topic1400.htm', null],
			['Deposit Register Report', 'Files/9.gif', '', 'Topics/IDH_Topic1410.htm', null],
			['Register of Advance', 'Files/9.gif', '', 'Topics/IDH_Topic1420.htm', null],
			['Scheme Utiilzation Report', 'Files/9.gif', '', 'Topics/IDH_Topic1430.htm', null],
			['Dishonored Cheque Report', 'Files/9.gif', '', 'Topics/IDH_Topic1440.htm', null],
			['Summary Statement Report', 'Files/9.gif', '', 'Topics/IDH_Topic1450.htm', null],
			['Audit Trail Report', 'Files/9.gif', '', 'Topics/IDH_Topic1460.htm', null]
		],
		['Budget Reports', 'Files/1.gif', 'Files/2.gif', '',
			['Departwise Budget Summary', 'Files/9.gif', '', 'Topics/IDH_Topic860.htm', null],
			['Functionwise Budget Summary', 'Files/9.gif', '', 'Topics/IDH_Topic870.htm', null],
			['Budget Appropriation Register', 'Files/9.gif', '', 'Topics/IDH_Topic1370.htm', null],
			['Budget Variance Report', 'Files/9.gif', '', 'Topics/IDH_Topic1510.htm', null]
		]
	]
];