//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.20 at 11:49:41 AM IST 
//

package org.egov.infra.events.entity.schema;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * org.egov.infstr.events.domain.entity.schema package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * org.egov.infstr.events.domain.entity.schema
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link EmailType }
	 * 
	 */
	public EmailType createEmailType() {
		return new EmailType();
	}

	/**
	 * Create an instance of {@link SMSType }
	 * 
	 */
	public SMSType createSMSType() {
		return new SMSType();
	}

	/**
	 * Create an instance of {@link Response }
	 * 
	 */
	public Response createResponse() {
		return new Response();
	}

	/**
	 * Create an instance of {@link CallBackType }
	 * 
	 */
	public CallBackType createCallBackType() {
		return new CallBackType();
	}

}
