CREATE SEQUENCE SEQUENCE_EGF_BUDGET_GROUP
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE TABLE EGF_BUDGET_GROUP(
  ID                NUMBER     NOT NULL,
  MAJORCODE      NUMBER,
  MAXCODE          NUMBER,
  MINCODE    		NUMBER     NOT NULL,
  NAME     	VARCHAR2(250 BYTE),
  DESCRIPTION     	VARCHAR2(250 BYTE),
  BUDGETINGTYPE   VARCHAR2(250 BYTE),
  ACCOUNTTYPE     VARCHAR2(250 BYTE),
  ISACTIVE         NUMBER(1),
  UPDATEDTIMESTAMP  DATE  NOT NULL
); 

ALTER TABLE EGF_BUDGET_GROUP ADD CONSTRAINT PK_EGF_BUDGET_GROUP PRIMARY KEY (ID);
ALTER TABLE EGF_BUDGET_GROUP ADD CONSTRAINT FK_EGF_BUDGET_GROUP_MAJORCODE FOREIGN KEY (MAJORCODE) REFERENCES  CHARTOFACCOUNTS(ID);
ALTER TABLE EGF_BUDGET_GROUP ADD CONSTRAINT FK_EGF_BUDGET_GROUP_MAXCODE FOREIGN KEY (MAXCODE) REFERENCES  CHARTOFACCOUNTS(ID);
ALTER TABLE EGF_BUDGET_GROUP ADD CONSTRAINT FK_EGF_BUDGET_GROUP_MINCODE FOREIGN KEY (MINCODE) REFERENCES  CHARTOFACCOUNTS(ID);
  								   

CREATE SEQUENCE SEQUENCE_EGF_BUDGET_DETAIL
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE TABLE EGF_BUDGET_DETAIL(
  ID                NUMBER     NOT NULL,
  USING_DEPARTMENT        NUMBER,
  EXECUTING_DEPARTMENT    NUMBER,
  FUNCTION          NUMBER,
  BUDGET     		NUMBER     NOT NULL,
  BUDGETGROUP     	NUMBER,
  ORIGINALAMOUNT    NUMBER(15,2),
  BUDGETAVAILABLE   NUMBER(15,2),
  SCHEME          	NUMBER,
  SUBSCHEME       	NUMBER,
  FUNCTIONARY   	NUMBER,
  BOUNDARY          NUMBER,
  MODIFIEDDATE DATE,
  MODIFIEDBY NUMBER,
  CREATEDDATE DATE,
  CREATEDBY NUMBER
); 

ALTER TABLE EGF_BUDGET_DETAIL ADD CONSTRAINT PK_EGF_BUDGET_DETAIL PRIMARY KEY (ID);
ALTER TABLE EGF_BUDGET_DETAIL ADD CONSTRAINT FK_EGF_BUDGET_DETAIL_FUNTION FOREIGN KEY (FUNCTION) REFERENCES  FUNCTION(ID);
ALTER TABLE EGF_BUDGET_DETAIL ADD CONSTRAINT FK_EGF_BUDGET_DETAIL_GROUP FOREIGN KEY (BUDGETGROUP) REFERENCES  EGF_BUDGET_GROUP(ID);
ALTER TABLE EGF_BUDGET_DETAIL ADD CONSTRAINT FK_BUDGET_DETAIL_USING_DEPT FOREIGN KEY (USING_DEPARTMENT) REFERENCES EG_DEPARTMENT (ID_DEPT);
ALTER TABLE EGF_BUDGET_DETAIL ADD CONSTRAINT FK_BUDGET_DETAIL_EXE_DEPT FOREIGN KEY (EXECUTING_DEPARTMENT) REFERENCES EG_DEPARTMENT (ID_DEPT);
ALTER TABLE EGF_BUDGET_DETAIL ADD CONSTRAINT FK_EGF_BUDGET_DETAIL_BUDGET FOREIGN KEY (BUDGET) REFERENCES BUDGET (ID);
ALTER TABLE EGF_BUDGET_DETAIL ADD CONSTRAINT FK_EGF_BUDGET_DETAIL_SUBSCHEME FOREIGN KEY (SUBSCHEME) REFERENCES SUB_SCHEME (ID);
ALTER TABLE EGF_BUDGET_DETAIL ADD CONSTRAINT FK_EGF_BUDGET_DETAIL_SCHEME FOREIGN KEY (SCHEME) REFERENCES SCHEME (ID);
ALTER TABLE EGF_BUDGET_DETAIL ADD CONSTRAINT FK_BUDGET_DETAIL_FUNCTIONARY FOREIGN KEY (FUNCTIONARY) REFERENCES FUNCTIONARY (ID);

CREATE SEQUENCE SEQUENCE_BUDGET
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE TABLE BUDGET(
  ID             NUMBER     NOT NULL,
  NAME           VARCHAR2(250 BYTE),
  DESCRIPTION    NUMBER,
  CHARTOFACCOUNT NUMBER,
  PARENT     	 NUMBER,
  FINANCIALYEAR  NUMBER,
  ISPRIMARYBUDGET NUMBER(1),
  ISACTIVEBUDGET  NUMBER(1),
  UPDATEDTIMESTAMP  DATE  NOT NULL
); 

ALTER TABLE BUDGET ADD CONSTRAINT PK_BUDGET PRIMARY KEY (ID);
ALTER TABLE BUDGET ADD CONSTRAINT FK_BUDGET_CHARTOFACCOUNT FOREIGN KEY (CHARTOFACCOUNT) REFERENCES  CHARTOFACCOUNTS(ID);
ALTER TABLE BUDGET ADD CONSTRAINT FK_BUDGET_PARENT FOREIGN KEY (PARENT) REFERENCES  BUDGET(ID);
ALTER TABLE BUDGET ADD CONSTRAINT FK_BUDGET_FINANCIALYEAR FOREIGN KEY (FINANCIALYEAR) REFERENCES FINANCIALYEAR (ID);

INSERT INTO EG_MODULE (ID_MODULE, MODULE_NAME, LASTUPDATEDTIMESTAMP, ISENABLED,  BASEURL, PARENTID, ORDER_NUM, MODULE_DESC)
VALUES (seq_modulemaster.nextVal, 'Budgeting',sysdate,'1','',(select id_module from eg_module where module_name='EGF'),8,'Budgeting');

INSERT INTO EG_MODULE (ID_MODULE, MODULE_NAME, LASTUPDATEDTIMESTAMP, ISENABLED,  BASEURL, PARENTID, ORDER_NUM, MODULE_DESC)
VALUES (seq_modulemaster.nextVal, 'Budget Details',sysdate,'1','',(select id_module from eg_module where module_name='Budgeting'),1,'Budget Details');

INSERT INTO eg_action(ID, NAME, ENTITYID, TASKID, UPDATEDTIME, URL, QUERYPARAMS, URLORDERID, MODULE_ID, ORDER_NUMBER, DISPLAY_NAME, IS_ENABLED, ACTION_HELP_URL)
VALUES(seq_eg_action.nextVal, 'Add Budget Details', NULL,null, sysdate, 
    '/budget/budgetDetail.action', '', NULL, (select id_module from eg_module where module_name='Budget Details'), 1,'Add Budget Details', 1, NULL);
    
insert into eg_roleaction_map select (SELECT ID_ROLE FROM EG_ROLES WHERE ROLE_NAME IN ('SuperUser','Super User','SUPER USER')),id from eg_action where id >=(select id from eg_action where name='Add Budget Details');    

commit;
