------------------START------------------
INSERT INTO eg_appconfig_values(id, key_id, effective_from, value, version) VALUES (nextval('seq_eg_appconfig_values'), (select id from eg_appconfig where key_name='IS_ASSET_CATEGORYCODE_AUTOGENERATED'), now(), 'yes', 0);
INSERT INTO eg_appconfig_values(id, key_id, effective_from, value, version) VALUES (nextval('seq_eg_appconfig_values'), (select id from eg_appconfig where key_name='ASSET_ACCOUNT_CODE_PURPOSEID'), now(), (select id from egf_accountcode_purpose where name='Fixed Assets'), 0);
INSERT INTO eg_appconfig_values(id, key_id, effective_from, value, version) VALUES (nextval('seq_eg_appconfig_values'),  (select id from eg_appconfig where key_name='REVALUATION_RESERVE_ACCOUNT_PURPOSEID'), now(), (select id from egf_accountcode_purpose where name='Revaluation Reserve Account'), 0);
INSERT INTO eg_appconfig_values(id, key_id, effective_from, value, version) VALUES (nextval('seq_eg_appconfig_values'),  (select id from eg_appconfig where key_name='DEPRECIATION_EXPENSE_ACCOUNT_PURPOSEID'), now(), (select id from egf_accountcode_purpose where name='Depreciation Expense Account'), 0);
INSERT INTO eg_appconfig_values(id, key_id, effective_from, value, version) VALUES (nextval('seq_eg_appconfig_values'),  (select id from eg_appconfig where key_name='ACCUMULATED_DEPRECIATION_PURPOSEID'), now(), (select id from egf_accountcode_purpose where name='Accumulated Depreciation'), 0);
INSERT INTO eg_appconfig_values(id, key_id, effective_from, value, version) VALUES (nextval('seq_eg_appconfig_values'), (select id from eg_appconfig where key_name='IS_ASSET_CODE_AUTOGENERATED'), now(), 'yes', 0);
-------------------END-------------------

------------------START------------------
update chartofaccounts set purposeid =
(select id from EGF_ACCOUNTCODE_PURPOSE where name='Fixed Assets') where glcode='410' and purposeid is null;
update chartofaccounts set purposeid =
(select id from EGF_ACCOUNTCODE_PURPOSE where name='Accumulated Depreciation') where glcode='411' and purposeid is null;
update chartofaccounts set purposeid =
(select id from EGF_ACCOUNTCODE_PURPOSE where name='Depreciation Expense Account') where glcode='272' and purposeid is null;
update chartofaccounts set purposeid =
(select id from EGF_ACCOUNTCODE_PURPOSE where name='Revaluation Reserve Account') where glcode='312' and purposeid is null;
-------------------END-------------------

--rollback update chartofaccounts set purposeid = null where glcode='410' and purposeid in(select id from EGF_ACCOUNTCODE_PURPOSE where name='Fixed Assets');
--rollback update chartofaccounts set purposeid = null where glcode='411' and purposeid in (select id from EGF_ACCOUNTCODE_PURPOSE where name='Accumulated Depreciation');
--rollback update chartofaccounts set purposeid = null where glcode='272' and purposeid in (select id from EGF_ACCOUNTCODE_PURPOSE where name='Depreciation Expense Account');
--rollback update chartofaccounts set purposeid = null where glcode='312' and purposeid in (select id from EGF_ACCOUNTCODE_PURPOSE where name='Revaluation Reserve Account');

--rollback delete from eg_appconfig_values where key_id in(select id from eg_appconfig where module='Assets');


