#UP


-- eg_employee
Insert into EG_USER
   (ID_USER, FIRST_NAME, ID_DEPARTMENT, USER_NAME, PWD, PWD_REMINDER, UPDATETIME, IS_SUSPENDED, ID_TOP_BNDRY, ISACTIVE, FROMDATE, TODATE)
 Values
   (SEQ_EG_USER.NEXTVAL, 'Manager', null, 'manager', '72scnc8h75di6', 'test', TO_DATE('03/10/2008 18:20:06', 'MM/DD/YYYY HH24:MI:SS'), 'N',
   (SELECT id_bndry FROM EG_BOUNDARY WHERE name='chennaicmc'), 1, TO_DATE('01/01/1990 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into EG_EMPLOYEE
   (ID, CODE, DATE_OF_BIRTH, GENDER, IS_HANDICAPPED, IS_MED_REPORT_AVAILABLE, DATE_OF_FIRST_APPOINTMENT, MODE_OF_RECRUIMENT_ID, RECRUITMENT_TYPE_ID, ID_USER, ISACTIVE, EMP_FIRSTNAME, NAME,EMPCATMSTR_ID)
 Values
   (EGPIMS_PERSONAL_INFO_SEQ.NEXTVAL, '2', TO_DATE('09/05/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0', '0', '0', TO_DATE('09/05/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), null, null,  (SELECT id_user FROM EG_USER WHERE user_name='manager'), 1, 'Manager', 'Manager',3);


-- eg_designation

Insert into EG_DESIGNATION
   (DESIGNATIONID, DEPTID, OFFICER_LEVEL, DESIGNATION_NAME, DESIGNATION_DESCRIPTION, SANCTIONED_POSTS, OUTSOURCED_POSTS, BASIC_FROM, BASIC_TO, REPORTSTO)
 Values
   (SEQ_DESIGNATION.nextval, (select id_dept from eg_department where dept_name = 'E-Education'), 1, 'Asst. Engineer', 'Engineer Asst.', 10, 7, 4500, 9000, 2);
Insert into EG_DESIGNATION
   (DESIGNATIONID, DEPTID, OFFICER_LEVEL, DESIGNATION_NAME, SANCTIONED_POSTS, OUTSOURCED_POSTS, BASIC_FROM, BASIC_TO, REPORTSTO)
 Values
   (SEQ_DESIGNATION.nextval, (select id_dept from eg_department where dept_name = 'E-Education'), 1, 'Exec Engineer', 2, 2, 9000, 10000, 1);



-- eg position

INSERT INTO EG_POSITION
   (POSITION_NAME, ID, SANCTIONED_POSTS, OUTSOURCED_POSTS, DESIG_ID, EFFECTIVE_DATE)
 VALUES
   ('Engg', SEQ_POS.NEXTVAL, 1, 0, (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='Asst. Engineer' ) , TO_DATE('03/26/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));


INSERT INTO  EG_POSITION
   (POSITION_NAME, ID, SANCTIONED_POSTS, OUTSOURCED_POSTS, DESIG_ID, EFFECTIVE_DATE)
 VALUES
   ('Sr Engg',SEQ_POS.NEXTVAL, 1, 0, (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='Exec Engineer'), TO_DATE('03/26/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));


--EG_POSITION_HIR


 Insert into EG_POSITION_HIR
   (ID, POSITION_FROM, POSITION_TO, OBJECT_TYPE_ID)
 Values
   (SEQ_POSITION_HIR.nextval, (SELECT e.POS_ID  FROM eg_eis_employeeinfo e WHERE e.CODE=100), (select id from eg_position where position_name like 'Sr Engg'), (select id from eg_object_type where type='MaterialIndent'));

Insert into EG_POSITION_HIR
   (ID, POSITION_FROM, POSITION_TO, OBJECT_TYPE_ID)
 Values
   (SEQ_POSITION_HIR.nextval, (SELECT e.POS_ID  FROM eg_eis_employeeinfo e WHERE e.CODE=100), (select id from eg_position where position_name like 'Sr Engg'), (select id from eg_object_type where type='MMRN'));

Insert into EG_POSITION_HIR
   (ID, POSITION_FROM, POSITION_TO, OBJECT_TYPE_ID)
 Values
   (SEQ_POSITION_HIR.nextval, (SELECT e.POS_ID  FROM eg_eis_employeeinfo e WHERE e.CODE=100), (select id from eg_position where position_name like 'Sr Engg'), (select id from eg_object_type where type='MaterialIssue'));
Insert into EG_POSITION_HIR
   (ID, POSITION_FROM, POSITION_TO, OBJECT_TYPE_ID)
 Values
   (SEQ_POSITION_HIR.nextval, (SELECT e.POS_ID  FROM eg_eis_employeeinfo e WHERE e.CODE=100), (select id from eg_position where position_name like 'Sr Engg'), (select id from eg_object_type where type='PJV'));

--EG_EMP_ASSIGNMENT_PRD

INSERT INTO EG_EMP_ASSIGNMENT_PRD
   (ID, FROM_DATE, ID_EMPLOYEE)
 VALUES
   (SEQ_ASS_PRD.NEXTVAL, TO_DATE('01/01/1990 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),  (SELECT id FROM EG_EMPLOYEE  WHERE name='Manager'));


--Emp_ASSignment


INSERT INTO EG_EMP_ASSIGNMENT
   (ID, ID_FUND, ID_FUNCTION, DESIGNATIONID, ID_FUNCTIONARY, ID_EMP_ASSIGN_PRD, MAIN_DEPT, POSITION_ID)
 VALUES
   (SEQ_ASS.NEXTVAL, (SELECT ID FROM FUND WHERE NAME='Municipal Service Fund'),
 (SELECT id FROM FUNCTION WHERE name = 'Public Works' ),
 (SELECT designationid FROM eg_designation WHERE designation_name='Asst. Engineer'),
(SELECT id FROM functionary WHERE name='A.E.-8 PUBLIC WORKS'),

(SELECT id FROM eg_emp_assignment_prd WHERE id_employee = (SELECT id FROM eg_employee WHERE code=2) ),
(SELECT id_dept FROM eg_department WHERE dept_name='G-General'),
(SELECT id FROM eg_position WHERE position_name='Sr Engg'));

--EG_EMPLOYEE_DEPT




INSERT INTO EG_EMPLOYEE_DEPT
   (DEPTID, ID, ASSIGNMENT_ID, HOD)
 VALUES
   ((SELECT id_dept FROM EG_DEPARTMENT WHERE dept_name = 'G-General'),
   SEQ_ASS_DEPT.NEXTVAL,
   (SELECT id FROM EG_EMP_ASSIGNMENT  WHERE ID_EMP_ASSIGN_PRD= (SELECT  id FROM EG_EMP_ASSIGNMENT_PRD  WHERE id_employee=(SELECT id FROM EG_EMPLOYEE WHERE name='Manager'))) ,
   '1');

--EG_USER_JURLEVEL


   INSERT INTO EG_USER_JURLEVEL
      (ID_USER_JURLEVEL, ID_USER, ID_BNDRY_TYPE, UPDATETIME)
    VALUES
      (SEQ_EG_USER_JURLEVEL.NEXTVAL, (SELECT id_user FROM EG_USER WHERE FIRST_NAME='SUPERUSER'),

      (SELECT  ID_BNDRY_TYPE FROM EG_BOUNDARY_TYPE  WHERE name='City' AND  id_HEiRarchy_type=1),
    TO_DATE('03/11/2008 13:47:11', 'MM/DD/YYYY HH24:MI:SS'));





    INSERT INTO EG_USER_JURVALUES
       (ID_USER_JURLEVEL, ID_BNDRY, FROMDATE, ID, IS_HISTORY)
     VALUES
   ((SELECT MIN(id_user_jurlevel) FROM EG_USER_JURLEVEL), (SELECT  ID_BNDRY FROM EG_BOUNDARY  WHERE name='chennaicmc' ), TO_DATE('01/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),SEQ_EG_USER_JURVALUES.NEXTVAL, 'N');


    -- for mysore
      update EG_APPCONFIG_VALUES set value='NO'
      where id in (select id from EG_APPCONFIG where key_name='AUTOGENKEY');
      -- for coc
      update EG_APPCONFIG_VALUES set value='YES' where id in (select id from EG_APPCONFIG where key_name='AUTOGENKEY');

      update EG_APPCONFIG_VALUES set value=1 where value='YES';
      update EG_APPCONFIG_VALUES set value=0 where value='NO';



      insert into EG_ROLEACTION_MAP(ROLEID,ACTIONID)
       (select (select id_role from EG_USERROLE where id_user in (
       	(select id_user  from eg_user where user_name like'manager'))) as userid,id from eg_action
      where id in (select id from eg_action where name in ('DEFAULT')	));

      insert into EG_ROLEACTION_MAP(ROLEID,ACTIONID)
      (select (select id_role from EG_roles where role_name like 'SuperUser') as roleid,id from eg_action
      where id in (select id from eg_action where name like 'Create Inter Bin Transfer'));

      insert into EG_ROLEACTION_MAP(ROLEID,ACTIONID)
       (select (select id_role from EG_USERROLE where id_user in (
       	(select id_user  from eg_user where user_name like'manager'))) as userid,id from eg_action
      where id in (select id from eg_action where url like '%Inbo%'	));


      Insert into EG_POSITION_HIR
         (ID, POSITION_FROM, POSITION_TO, OBJECT_TYPE_ID)
       Values
         (SEQ_POSITION_HIR.nextval,(SELECT e.POS_ID  FROM eg_eis_employeeinfo e WHERE e.CODE=100), (select id from eg_position where position_name like 'Sr Engg'), (select id from EG_OBJECT_TYPE where type='MRN'));




 --Merged form other seed data files

 INSERT INTO ChartOfAccounts (id, glCode, name, description, isActiveForPosting,  parentId,  lastModified, modifiedBy,
 created, purposeid,functionreqd, operation,type,classification,class,budgetCheckReq)
 VALUES(1537, '4702001', 'Inter Unit Transfer', null, '1',  '326',  '18-Jul-2008', '1', '18-Jul-2008',  '22','0',null,'A','4',0,'0');



 update chartofaccounts set purposeid='32' where glcode='2702001';
 update chartofaccounts set purposeid='22' where glcode='4702001';
 update chartofaccounts set purposeid='23' where glcode='1501201';
 update chartofaccounts set purposeid='24' where glcode='3509003';
update chartofaccounts set purposeid='25' where glcode='2704001';
update chartofaccounts set purposeid='37' where glcode='4308000';

 UPDATE FUND SET identifier='F' WHERE name='Municipal Service Fund';





INSERT INTO EG_ROLEACTION_MAP(ROLEID,ACTIONID)
(SELECT (SELECT id_role FROM EG_ROLES WHERE role_name LIKE 'SuperUser') AS roleid,id FROM EG_ACTION
WHERE id IN
(SELECT id FROM EG_ACTION WHERE name IN(
'CREATE Inter Bin Transfer',
'MRTypePurchase',
'MRNTypeSupplier',
'MRNTypeInterSTransfer',
'MRNTypeAdhoc',
'MMRNTypeSuppRecpt',
'CREATE General Issue',
'MMRNTypePhyStkTaking',
'MMRNTypeROM',
'CREATE MaterialIdent Issue',
'INDEX page',
'ApproveMaterialIndentusingJbmp',
'VIEW Material Issue',
'UOM Category',
'Unit OF Measurement',
'Item TYPE',
'Stores Master',
'Report Setup',
'CREATE Item',
'VIEW Item',
'MODIFY Item',
'CREATE Supplier',
'VIEW Supplier',
'MODIFY Supplier',
'CREATE Purchase ORDER',
'MODIFY Purchase ORDER',
'VIEW Purchase ORDER',
'Approve Purchase ORDER',
'Auto CREATE PO',
'CREATE MRN',
'MODIFY MRN',
'VIEW MRN',
'Approve MRN',
'CREATE MRIN',
'MODIFY MRIN',
'VIEW MRIN',
'CREATE Catalogue',
'VIEW Catalogue',
'MODIFY Catalogue',
'CREATE Rate Contract',
'VIEW Rate Contract',
'MODIFY Rate Contract',
'Approve Rate Contract',
'CANCEL Rate Contract',
'CREATE MR',
'VIEW  MR',
'MODIFY MR',
'Approve MR',
'CREATE Supplier Bill',
'MODIFY Supplier Bill',
'Approve Supplier Bill',
'CREATE MMR',
'VIEW MMR',
'MODIFY MMR',
'Stores Ledger',
'Material Receipt Note',
'Vendor Ageing Analysis',
'Inventory INDEX page',
'VIEW Supplier  Bill',
'VIEW Agreement',
'MODIFY Agreement',
'VIEW WORK ORDER',
'CREATE Contractor Bill',
'MODIFY Contractor Bill',
'MODIFY Contractor',
'VIEW Contractor',
'MODIFY Contractor Grades',
'Approve Bill Register',
'MRTypeInternal',
'DEFAULT',
'CHANGE PASSWORD',
'VIEW Inter Bin Transfer'
)));


/* EG_UOMCATEGORY*/

Insert into EG_UOMCATEGORY
   (ID, CATEGORY, NARRATION, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOMCATEGORY.nextval, 'QUNITA', 'quinta11', TO_TIMESTAMP('1/30/2009 8:02:37.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('01/29/2009 18:18:22', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));


Insert into EG_UOMCATEGORY
   (ID, CATEGORY, NARRATION, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOMCATEGORY.nextval, 'Quantity', 'Quantity', TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

/** Moved to assets sample data file 0005
Insert into EG_UOMCATEGORY
   (ID, CATEGORY, NARRATION, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOMCATEGORY.nextval, 'Length', 'Length', TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));
Insert into EG_UOMCATEGORY
   (ID, CATEGORY, NARRATION, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOMCATEGORY.nextval, 'AREA', 'area', TO_TIMESTAMP('3/20/2009 6:29:46.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));**/

Insert into EG_UOMCATEGORY
   (ID, CATEGORY, NARRATION, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOMCATEGORY.nextval, 'DENSITY', 'density', TO_TIMESTAMP('1/23/2009 11:41:49.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/19/2008 11:52:52', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));



/*EG_UOM*/


Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Length'), 'VOLT', 2, 0, TO_TIMESTAMP('1/30/2009 11:04:41.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('01/30/2009 11:04:41', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Length' ) , 'CENTIMETER', 'centimeter', 100, 0, TO_TIMESTAMP('1/30/2009 8:04:46.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('01/30/2009 20:04:46', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Length'), 'AMP', 'AMP', 1, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Quantity' ) , 'BAG', 'BAG', 12, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Quantity' ) , 'BOX', 'BOX1', 12, 0, TO_TIMESTAMP('3/16/2009 3:25:27.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Length' ), 'CUM', 'CUM', 1000, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Quantity' ) , 'DOZ', 'DOZ', 12, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));


Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='AREA' ), 'GRM', 'GRM', 1, 1, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='AREA' ), 'GRS', 'GRS', 1, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='AREA' ), 'KGS', 'KGS', 1000, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Quantity' ) , 'KIT', 'KIT', 1, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='AREA' ), 'LBS', 'LBS', 454.55, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));


Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Length' ), 'LTR', 'LTR', 1, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Length' ), 'LTS', 'LTS', 1, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));
/** Moved to assets sample data file 0005
Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Length' ) , 'MTR', 'MTR', 1, 1, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));
**/
Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Length' ) , 'MTS', 'MTS', 1, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'),(select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Quantity' ) , 'NOS', 'NOS', 1, 1, TO_TIMESTAMP('1/30/2009 3:23:49.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Quantity' ) , 'PCS', 'PCS', 1, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Quantity' ) , 'PKT', 'PKT', 1, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='Length' ) , 'ROL', 'ROL', 100, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'));

Insert into EG_UOM
   (ID, UOMCATEGORYID, UOM, NARRATION, CONV_FACTOR, BASEUOM, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY)
 Values
   (SEQ_EG_UOM.nextval, (SELECT  id FROM   EG_UOMCATEGORY WHERE category='AREA' ), 'TON', 'TON', 1000000, 0, TO_TIMESTAMP('11/8/2008 7:25:11.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 07:25:11', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'),(select id_user from EG_USER where user_name='egovernments'));


/* EG_ITEMTYPE*/
Insert into EG_ITEMTYPE
   (ID, ITEMTYPE, NARRATION, LASTMODIFIED, CREATEDDATE, CREATEDBY, STOCKINHANDCODEID)
 Values
   (SEQ_EG_ITEMTYPE.nextval, 'IRON', 'IRON', TO_TIMESTAMP('1/7/2009 5:42:55.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('01/07/2009 17:42:55', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), ( SELECT id  FROM CHARTOFACCOUNTS WHERE id=946));


Insert into EG_ITEMTYPE
   (ID, ITEMTYPE, NARRATION, LASTMODIFIED, CREATEDDATE, CREATEDBY, STOCKINHANDCODEID)
 Values
   (SEQ_EG_ITEMTYPE.nextval, 'WOOD', 'Different woods for Furniture', TO_TIMESTAMP('1/7/2009 5:44:21.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('01/07/2009 17:44:21', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), ( SELECT id  FROM CHARTOFACCOUNTS WHERE id=946));

Insert into EG_ITEMTYPE
   (ID, ITEMTYPE, LASTMODIFIED, CREATEDDATE, CREATEDBY, STOCKINHANDCODEID)
 Values
   (SEQ_EG_ITEMTYPE.nextval, 'Mechanical Supplies-7', TO_TIMESTAMP('11/8/2008 11:03:26.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 11:03:26', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), ( SELECT id  FROM CHARTOFACCOUNTS WHERE id=946));

Insert into EG_ITEMTYPE
   (ID, ITEMTYPE, LASTMODIFIED, CREATEDDATE, CREATEDBY, STOCKINHANDCODEID)
 Values
   (SEQ_EG_ITEMTYPE.nextval, 'Medical supplies-3', TO_TIMESTAMP('11/8/2008 11:03:26.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 11:03:26', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), ( SELECT id  FROM CHARTOFACCOUNTS WHERE id=946));

Insert into EG_ITEMTYPE
   (ID, ITEMTYPE, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY, STOCKINHANDCODEID)
 Values
   (SEQ_EG_ITEMTYPE.nextval, 'OILS-5', TO_TIMESTAMP('1/16/2009 4:20:45.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 11:03:26', 'MM/DD/YYYY HH24:MI:SS'),(select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'), ( SELECT id  FROM CHARTOFACCOUNTS WHERE id=946));

Insert into EG_ITEMTYPE
   (ID, ITEMTYPE, LASTMODIFIED, CREATEDDATE, CREATEDBY, LASTMODIFIEDBY, STOCKINHANDCODEID)
 Values
   (SEQ_EG_ITEMTYPE.nextval, 'MS RODS-1', TO_TIMESTAMP('1/6/2009 4:08:05.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('11/08/2008 11:03:27', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'), (select id_user from EG_USER where user_name='egovernments'), ( SELECT id  FROM CHARTOFACCOUNTS WHERE id=946));

Insert into EG_ITEMTYPE
   (ID, ITEMTYPE, NARRATION, LASTMODIFIED, CREATEDDATE, CREATEDBY, STOCKINHANDCODEID)
 Values
   (SEQ_EG_ITEMTYPE.nextval, 'HOUSING', 'HOUSING', TO_TIMESTAMP('1/7/2009 6:04:49.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), TO_DATE('01/07/2009 18:04:49', 'MM/DD/YYYY HH24:MI:SS'), (select id_user from EG_USER where user_name='egovernments'),( SELECT id  FROM CHARTOFACCOUNTS WHERE id=946));



/* EG_ITEM*/


Insert into EG_ITEM
   (ID, ITEMNO, ITEMTYPEID, UOMID, NARRATION, LASTMODIFIED, ISINVENTORYASSET, ITEMSTATUSID, CREATEDBY, CREATEDDATE, STOCKINGUOMID, ISLOTCONTROLLED, TAXABLE, CONTRACTREQT, PUCHUOMID, CANPURCHASE, ISSHELFLIFECONTROLLED, ISINDENTREQUIRED, ALLOWNEGETIVEQTY, BINLEVELSTORAGE, ISSCRAP)
 Values
   (SEQ_EG_ITEM.nextval, 'GRANITE', (SELECT id FROM EG_ITEMTYPE WHERE itemtype='HOUSING'), (SELECT id FROM EG_UOM WHERE uom='NOS' ), 'granite', TO_DATE('03/20/2009 18:14:46', 'MM/DD/YYYY HH24:MI:SS'), 1, (SELECT id FROM EGW_STATUS WHERE moduletype='Item'  AND description='Active'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), TO_DATE('03/20/2009 18:14:46', 'MM/DD/YYYY HH24:MI:SS'), (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 1, 0, 'T', (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 0, 1, 1, 0, 1, 0);
Insert into EG_ITEM
   (ID, ITEMNO, ITEMTYPEID, UOMID, NARRATION, LASTMODIFIED, ISINVENTORYASSET, ITEMSTATUSID, LASTMODIFIEDBY, CREATEDBY, CREATEDDATE, STOCKINGUOMID, ISLOTCONTROLLED, CONTRACTREQT, PUCHUOMID, CANPURCHASE, ISSHELFLIFECONTROLLED, ISINDENTREQUIRED, ALLOWNEGETIVEQTY, BINLEVELSTORAGE, ISSCRAP)
 Values
   (SEQ_EG_ITEM.nextval, '93C01', (SELECT id FROM EG_ITEMTYPE WHERE itemtype='OILS-5'), (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 'COUNTER PLATE B0105003', TO_DATE('11/08/2008 11:03:26', 'MM/DD/YYYY HH24:MI:SS'), 0, (SELECT id FROM EGW_STATUS WHERE moduletype='Item'  AND description='Active'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), TO_DATE('11/08/2008 11:03:26', 'MM/DD/YYYY HH24:MI:SS'), (SELECT id FROM EG_UOM WHERE uom='NOS' ), 0, '0', (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 1, 0, 1, 0, 0, 0);
Insert into EG_ITEM
   (ID, ITEMNO, ITEMTYPEID, UOMID, NARRATION, LASTMODIFIED, ISINVENTORYASSET, ITEMSTATUSID, LASTMODIFIEDBY, CREATEDBY, CREATEDDATE, STOCKINGUOMID, ISLOTCONTROLLED, CONTRACTREQT, PUCHUOMID, CANPURCHASE, ISSHELFLIFECONTROLLED, ISINDENTREQUIRED, ALLOWNEGETIVEQTY, BINLEVELSTORAGE, ISSCRAP)
 Values
   (SEQ_EG_ITEM.nextval, '14A05', (SELECT id FROM EG_ITEMTYPE WHERE itemtype='OILS-5'), (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 'REAR WHEEL BUSH [CI] O/S', TO_DATE('11/08/2008 11:03:28', 'MM/DD/YYYY HH24:MI:SS'), 1, (SELECT id FROM EGW_STATUS WHERE moduletype='Item'  AND description='Active'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), TO_DATE('11/08/2008 11:03:28', 'MM/DD/YYYY HH24:MI:SS'), (SELECT id FROM EG_UOM WHERE uom='NOS' ), 0, '0', (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 1, 0, 1, 0, 0, 0);
Insert into EG_ITEM
   (ID, ITEMNO, ITEMTYPEID, UOMID, NARRATION, LASTMODIFIED, ISINVENTORYASSET, ITEMSTATUSID, LASTMODIFIEDBY, CREATEDBY, CREATEDDATE, STOCKINGUOMID, ISLOTCONTROLLED, CONTRACTREQT, PUCHUOMID, CANPURCHASE, ISSHELFLIFECONTROLLED, ISINDENTREQUIRED, ALLOWNEGETIVEQTY, BINLEVELSTORAGE, ISSCRAP)
 Values
   (SEQ_EG_ITEM.nextval, '14A06', (SELECT id FROM EG_ITEMTYPE WHERE itemtype='OILS-5'), (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 'FRONT WHEEL BUSH [C.I] O/S', TO_DATE('11/08/2008 11:03:28', 'MM/DD/YYYY HH24:MI:SS'), 1, (SELECT id FROM EGW_STATUS WHERE moduletype='Item'  AND description='Active'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), TO_DATE('11/08/2008 11:03:28', 'MM/DD/YYYY HH24:MI:SS'),(SELECT id FROM EG_UOM WHERE uom='NOS' ), 0, '0', (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 1, 0, 1, 0, 0, 0);
Insert into EG_ITEM
   (ID, ITEMNO, ITEMTYPEID, UOMID, NARRATION, LASTMODIFIED, ISINVENTORYASSET, ITEMSTATUSID, LASTMODIFIEDBY, CREATEDBY, CREATEDDATE, STOCKINGUOMID, ISLOTCONTROLLED, CONTRACTREQT, PUCHUOMID, CANPURCHASE, ISSHELFLIFECONTROLLED, ISINDENTREQUIRED, ALLOWNEGETIVEQTY, BINLEVELSTORAGE, ISSCRAP)
 Values
   (SEQ_EG_ITEM.nextval, '10G64', (SELECT id FROM EG_ITEMTYPE WHERE itemtype='OILS-5'), (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 'FILTER ELEMENT [P4]', TO_DATE('11/08/2008 11:03:27', 'MM/DD/YYYY HH24:MI:SS'), 1, (SELECT id FROM EGW_STATUS WHERE moduletype='Item'  AND description='Active'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), TO_DATE('11/08/2008 11:03:27', 'MM/DD/YYYY HH24:MI:SS'),(SELECT id FROM EG_UOM WHERE uom='NOS' ), 0, '0', (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 1, 0, 1, 0, 0, 0);
Insert into EG_ITEM
   (ID, ITEMNO, ITEMTYPEID, UOMID, NARRATION, LASTMODIFIED, ISINVENTORYASSET, ITEMSTATUSID, LASTMODIFIEDBY, CREATEDBY, CREATEDDATE, STOCKINGUOMID, ISLOTCONTROLLED, CONTRACTREQT, PUCHUOMID, CANPURCHASE, ISSHELFLIFECONTROLLED, ISINDENTREQUIRED, ALLOWNEGETIVEQTY, BINLEVELSTORAGE, ISSCRAP)
 Values
   (SEQ_EG_ITEM.nextval, '10G65', (SELECT id FROM EG_ITEMTYPE WHERE itemtype='OILS-5'), (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 'L.H.UNION INNER BUSH G.M', TO_DATE('11/08/2008 11:03:27', 'MM/DD/YYYY HH24:MI:SS'), 1, (SELECT id FROM EGW_STATUS WHERE moduletype='Item'  AND description='Active'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), TO_DATE('11/08/2008 11:03:27', 'MM/DD/YYYY HH24:MI:SS'), (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 0, '0', (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 1, 0, 1, 0, 0, 0);
Insert into EG_ITEM
   (ID, ITEMNO, ITEMTYPEID, UOMID, NARRATION, LASTMODIFIED, ISINVENTORYASSET, ITEMSTATUSID, LASTMODIFIEDBY, CREATEDBY, CREATEDDATE, STOCKINGUOMID, ISLOTCONTROLLED, CONTRACTREQT, PUCHUOMID, CANPURCHASE, ISSHELFLIFECONTROLLED, ISINDENTREQUIRED, ALLOWNEGETIVEQTY, BINLEVELSTORAGE, ISSCRAP)
 Values
   (SEQ_EG_ITEM.nextval, '10G66', (SELECT id FROM EG_ITEMTYPE WHERE itemtype='OILS-5'), (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 'KEY FOR FINAL DRIVE PINON', TO_DATE('11/08/2008 11:03:27', 'MM/DD/YYYY HH24:MI:SS'), 1, (SELECT id FROM EGW_STATUS WHERE moduletype='Item'  AND description='Active'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), TO_DATE('11/08/2008 11:03:27', 'MM/DD/YYYY HH24:MI:SS'), (SELECT id FROM EG_UOM WHERE uom='NOS' ), 0, '0', (SELECT id FROM EG_UOM WHERE uom='NOS' ), 1, 0, 1, 0, 0, 0);
Insert into EG_ITEM
   (ID, ITEMNO, ITEMTYPEID, UOMID, NARRATION, LASTMODIFIED, ISINVENTORYASSET, ITEMSTATUSID, LASTMODIFIEDBY, CREATEDBY, CREATEDDATE, STOCKINGUOMID, ISLOTCONTROLLED, CONTRACTREQT, PUCHUOMID, CANPURCHASE, ISSHELFLIFECONTROLLED, ISINDENTREQUIRED, ALLOWNEGETIVEQTY, BINLEVELSTORAGE, ISSCRAP)
 Values
   (SEQ_EG_ITEM.nextval, '10G67', (SELECT id FROM EG_ITEMTYPE WHERE itemtype='OILS-5'), (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 'BEARING HOUSING', TO_DATE('11/08/2008 11:03:27', 'MM/DD/YYYY HH24:MI:SS'), 1, (SELECT id FROM EGW_STATUS WHERE moduletype='Item'  AND description='Active'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), TO_DATE('11/08/2008 11:03:27', 'MM/DD/YYYY HH24:MI:SS'), (SELECT id FROM EG_UOM WHERE uom='NOS' ), 0, '0', (SELECT id FROM EG_UOM WHERE uom='NOS' ), 1, 0, 1, 0, 0, 0);
Insert into EG_ITEM
   (ID, ITEMNO, ITEMTYPEID, UOMID, NARRATION, LASTMODIFIED, ISINVENTORYASSET, ITEMSTATUSID, LASTMODIFIEDBY, CREATEDBY, CREATEDDATE, STOCKINGUOMID, ISLOTCONTROLLED, TAXABLE, MODEL, CONTRACTREQT, PUCHUOMID, CANPURCHASE, ISSHELFLIFECONTROLLED, ISINDENTREQUIRED, ALLOWNEGETIVEQTY, BINLEVELSTORAGE, ISSCRAP)
 Values
   (SEQ_EG_ITEM.nextval, '10G68', (SELECT id FROM EG_ITEMTYPE WHERE itemtype='OILS-5'), (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 'STEERING WORM WHEER', TO_DATE('04/22/2009 11:33:38', 'MM/DD/YYYY HH24:MI:SS'), 1, (SELECT id FROM EGW_STATUS WHERE moduletype='Item'  AND description='Active'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), TO_DATE('11/08/2008 11:03:27', 'MM/DD/YYYY HH24:MI:SS'), (SELECT id FROM EG_UOM WHERE uom='NOS' ), 0, 0, 'AXSD', 'T', (SELECT id FROM EG_UOM WHERE uom='NOS' ), 1, 0, 1, 0, 0, 0);
Insert into EG_ITEM
   (ID, ITEMNO, ITEMTYPEID, UOMID, NARRATION, LASTMODIFIED, ISINVENTORYASSET, ITEMSTATUSID, CREATEDBY, CREATEDDATE, STOCKINGUOMID, ABCCLASS, ISLOTCONTROLLED, TAXABLE, MODEL, CONTRACTREQT, PUCHUOMID, CANPURCHASE, ISSHELFLIFECONTROLLED, ISINDENTREQUIRED, ALLOWNEGETIVEQTY, BINLEVELSTORAGE, ISSCRAP)
 Values
   (SEQ_EG_ITEM.nextval, 'TYRES', (SELECT id FROM EG_ITEMTYPE WHERE itemtype='OILS-5'), (SELECT id FROM EG_UOM WHERE uom='NOS' ) , 'TYRES', TO_DATE('04/22/2009 11:32:45', 'MM/DD/YYYY HH24:MI:SS'), 1, (SELECT id FROM EGW_STATUS WHERE moduletype='Item'  AND description='Active'), (SELECT id_user FROM EG_USER WHERE user_name='egovernments'), TO_DATE('04/22/2009 11:32:45', 'MM/DD/YYYY HH24:MI:SS'), (SELECT id FROM EG_UOM WHERE uom='NOS' ), 'B', 1, 0, 'CBZ-05', 'T', (SELECT id FROM EG_UOM WHERE uom='NOS' ), 0, 1, 1, 0, 1, 0);
COMMIT;

   /* Role Action map for manager*/

INSERT INTO EG_ROLES ( ID_ROLE, ROLE_NAME, ROLE_DESC, ROLE_NAME_LOCAL, ROLE_DESC_LOCAL, UPDATETIME,
UPDATEUSERID ) VALUES (
SEQ_EG_ROLES.NEXTVAL, 'TestUser', NULL, NULL, NULL,  TO_DATE( '06/09/2008 02:24:30 PM', 'MM/DD/YYYY HH:MI:SS AM')
, (SELECT ID_USER FROM EG_USER WHERE USER_NAME LIKE 'manager'));


   INSERT INTO EG_USERROLE ( ID_ROLE, ID_USER, ID, FROMDATE, TODATE,
   IS_HISTORY ) VALUES (
   (SELECT ID_ROLE FROM EG_ROLES WHERE ROLE_NAME LIKE 'TestUser'), (SELECT ID_USER FROM eg_user WHERE USER_NAME LIKE 'manager'), SEQ_EG_USERROLE.NEXTVAL,  TO_DATE( '01/01/2000 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'),  NULL
, 'N');



INSERT INTO EG_ROLEACTION_MAP(ROLEID,ACTIONID)
(SELECT (SELECT id_role FROM EG_USERROLE WHERE id_user IN (
	(SELECT id_user  FROM eg_user WHERE user_name LIKE'manager'))) AS userid,id FROM eg_action
WHERE id IN (SELECT id FROM eg_action WHERE name IN ('Inventory index page','index page','EstimateIndex')	));




INSERT INTO EG_ROLEACTION_MAP(ROLEID,ACTIONID)
SELECT ID_ROLE , ID FROM EG_ACTION , EG_ROLES WHERE ROLE_NAME LIKE 'TestUser' AND id IN (SELECT ea.id FROM eg_action ea WHERE ea.url LIKE '/inbox/Inbox.jsp');


INSERT INTO EG_ROLEACTION_MAP(ROLEID,ACTIONID)
SELECT ID_ROLE , ID FROM EG_ACTION , EG_ROLES WHERE ROLE_NAME LIKE 'TestUser' AND id IN (SELECT ea.id FROM EG_ACTION ea WHERE ea.name= 'DEFAULT');




UPDATE EG_EIS_EMPLOYEEINFO SET POS_ID=(SELECT id FROM EG_POSITION WHERE position_name ='Sr Engg') WHERE user_id=(SELECT id_user FROM EG_USER where USER_NAME='manager');

/* Creating stores  */

INSERT INTO EG_STORES(ID,STORENO,STORENAME,DEPTID,LASTMODIFIED,CREATEDDATE,CREATEDBY,BILLINGADdR)
 VALUES(SEQ_EG_STORES.NEXTVAL,'ACC-02','ACC-02',(SELECT ID_DEPT FROM EG_DEPARTMENT WHERE DEPT_NAME ='E-Education'),SYSDATE,SYSDATE,
 (SELECT ID_USER FROM EG_USER WHERE USER_NAME='egovernments'),'INDIRANAGAR');

 INSERT INTO EG_STORES(ID,STORENO,STORENAME,DEPTID,LASTMODIFIED,CREATEDDATE,CREATEDBY,BILLINGADdR)
 VALUES(SEQ_EG_STORES.NEXTVAL,'EDU-01','EDU-01',(SELECT ID_DEPT FROM EG_DEPARTMENT WHERE DEPT_NAME ='E-Education'),SYSDATE,SYSDATE,
 (SELECT ID_USER FROM EG_USER WHERE USER_NAME='egovernments'),'KORAMANGALA');


  INSERT INTO EG_STORES(ID,STORENO,STORENAME,DEPTID,LASTMODIFIED,CREATEDDATE,CREATEDBY,BILLINGADdR)
 VALUES(SEQ_EG_STORES.NEXTVAL,'EDU-02','EDU-02',(SELECT ID_DEPT FROM EG_DEPARTMENT WHERE DEPT_NAME ='E-Education'),SYSDATE,SYSDATE,
 (SELECT ID_USER FROM EG_USER WHERE USER_NAME='egovernments'),'EJIPURA');


  INSERT INTO EG_STORES(ID,STORENO,STORENAME,DEPTID,LASTMODIFIED,CREATEDDATE,CREATEDBY,BILLINGADdR)
 VALUES(SEQ_EG_STORES.NEXTVAL,'BUILD-01','BUILD-01',(SELECT ID_DEPT FROM EG_DEPARTMENT WHERE DEPT_NAME ='B-Buildings'),SYSDATE,SYSDATE,
 (SELECT ID_USER FROM EG_USER WHERE USER_NAME='egovernments'),'CHROMPET');


   INSERT INTO EG_STORES(ID,STORENO,STORENAME,DEPTID,LASTMODIFIED,CREATEDDATE,CREATEDBY,BILLINGADdR)
 VALUES(SEQ_EG_STORES.NEXTVAL,'BUILD-02','BUILD-02',(SELECT ID_DEPT FROM EG_DEPARTMENT WHERE DEPT_NAME ='B-Buildings'),SYSDATE,SYSDATE,
 (SELECT ID_USER FROM EG_USER WHERE USER_NAME='egovernments'),'Chennai');

/********************  Asset Sample Data has been  moved to 0005_assetSampleData.sql  *******************/


INSERT INTO RELATION ( ID, CODE, NAME, ADDRESS1, ADDRESS2, CITY, PIN, PHONE, FAX, CONTACTPERSON,
MOBILE, EMAIL, NARRATION, ISACTIVE, LASTMODIFIED, CREATED, MODIFIEDBY, RELATIONTYPEID, TDSID,
GLCODEID, PANNO, TINNO, BANKACCOUNT, BANKNAME, PWDAPPROVALCODE, REGNO, CREATEDBY, STATUSID, GRADEID,
INACTIVEON, PARTYTYPEID, SUBTYPEID, MODEOFPAY ) VALUES ( 
SEQ_RELATION.NEXTVAL, 'IOC1', 'Ioc Kondapalli', 'Ioc Kondapalli', NULL, NULL, '0', NULL, NULL, NULL
, NULL, NULL, 'Towrds supply of HSD oil', 0,  TO_DATE( '06/15/2007 04:04:03 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_DATE( '04/07/2007 04:43:23 PM', 'MM/DD/YYYY HH:MI:SS AM'), (SELECT id_user FROM EG_USER WHERE user_name LIKE 'egovernments'),
 (SELECT  id  FROM RELATIONTYPE WHERE name LIKE 'Contractor'), NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, (SELECT id_user FROM EG_USER WHERE user_name LIKE 'egovernments'), NULL, NULL, NULL, NULL, NULL, NULL); 



  INSERT INTO WORKSDETAIL ( ID, RELATIONID, CODE, ORDERDATE, TOTALVALUE, PAIDAMOUNT, ADVANCEPAYABLE,
ADVANCEAMOUNT, ISACTIVE, CREATED, LASTMODIFIED, MODIFIEDBY, NAME, AUTHORIZEDBY, LEVELOFWORK, WARDID,
SCHEMEID, TDSID, SECURITYDEPOSIT, RETENTION, BANKGUARANTEE, GLCODEID, PASSEDAMOUNT, TYPE,
ADVANCEADJ, FUNDID, FUNDSOURCEID, SANCTIONNO, WORKSTDS, REMARKS, SANCTIONDATE, ACT_COMM_DATE,
ACT_COMP_DATE, COMM_DATE, STATUSID, CREATEDBY, SHIPTO, BILLTO, COMP_DATE, WORKLOCATION,
WORKCATEGORY, SUBCATEGORY, USERDEPTID, EXECDEPTID, PARENTID ) VALUES ( 
SEQ_WORKSDETAIL.NEXTVAL, (  SELECT id FROM RELATION WHERE code='IOC1'), '2008-09/WO1',  
SYSDATE, 26000, NULL, NULL, NULL, 1,  SYSDATE, SYSDATE,  (SELECT id_user FROM EG_USER WHERE user_name LIKE 'egovernments')
, 'test', NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19120, NULL, NULL, NULL, NULL, NULL, NULL
, 'remark', NULL,  TO_DATE( '11/26/2008 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_DATE( '05/12/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_DATE( '11/28/2008 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
(SELECT id  FROM EGW_STATUS WHERE moduletype LIKE 'WO' AND description LIKE 'Admin Approval Done '),
 (SELECT id_user FROM EG_USER WHERE user_name LIKE 'egovernments'), NULL, NULL
,  TO_DATE( '12/10/2021 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL
, NULL, NULL, NULL);


 insert into EG_ROLEACTION_MAP(ROLEID,ACTIONID)
       (select (select id_role from EG_USERROLE where id_user in (
       	(select id_user  from eg_user where user_name like'manager'))) as userid,id from eg_action
      where id in ( select id from eg_action where name in ('loadcombo','loadmenutree','menutree')));

 insert into EG_ROLEACTION_MAP(ROLEID,ACTIONID)
       (select (select id_role from EG_USERROLE where id_user in (
       	(select id_user  from eg_user where user_name like'egovernments'))) as userid,id from eg_action
      where id in ( select id from eg_action where name in ('loadcombo')));
	  

UPDATE EG_EMPLOYEE SET lastmodified_date = sysdate 
where lastmodified_date is null;

commit;	  
	  

#DOWN
