#UP

----- Type of Work master data for Roads and Bridges---

INSERT INTO EGW_TYPEOFWORK ( ID, CODE, PARENTID, DESCRIPTION, CREATEDBY, CREATEDDATE,LASTMODIFIEDBY, LASTMODIFIEDDATE, PARTYTYPEID ) 
VALUES (SEQ_EGW_TYPEOFWORK.NEXTVAL, 'RoadesAndBridges', NULL, 'Roades And Bridges', 1,  TO_DATE( '07/09/2008 09:24:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, (SELECT ID FROM EG_PARTYTYPE WHERE CODE='Contractor')); 
INSERT INTO EGW_TYPEOFWORK ( ID, CODE, PARENTID, DESCRIPTION, CREATEDBY, CREATEDDATE,LASTMODIFIEDBY, LASTMODIFIEDDATE, PARTYTYPEID ) 
VALUES (SEQ_EGW_TYPEOFWORK.NEXTVAL, 'RoadsAndPvmntBlkTop', (SELECT ID FROM EGW_TYPEOFWORK WHERE CODE='RoadesAndBridges'), 'Roads and Pavement-Black Top', 1,  TO_DATE( '07/09/2008 09:25:45 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, (SELECT ID FROM EG_PARTYTYPE WHERE CODE='Contractor')); 
INSERT INTO EGW_TYPEOFWORK ( ID, CODE, PARENTID, DESCRIPTION, CREATEDBY, CREATEDDATE,LASTMODIFIEDBY, LASTMODIFIEDDATE, PARTYTYPEID ) 
VALUES (SEQ_EGW_TYPEOFWORK.NEXTVAL, 'RoadsAndPvmntOthers', (SELECT ID FROM EGW_TYPEOFWORK WHERE CODE='RoadesAndBridges'), 'Roads and Pavement-Others', 1,  TO_DATE( '07/09/2008 09:26:17 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, (SELECT ID FROM EG_PARTYTYPE WHERE CODE='Contractor')); 
INSERT INTO EGW_TYPEOFWORK ( ID, CODE, PARENTID, DESCRIPTION, CREATEDBY, CREATEDDATE,LASTMODIFIEDBY, LASTMODIFIEDDATE, PARTYTYPEID ) 
VALUES (SEQ_EGW_TYPEOFWORK.NEXTVAL, 'RoadsideDrains', (SELECT ID FROM EGW_TYPEOFWORK WHERE CODE='RoadesAndBridges'), 'Roadside Drains', 1,  TO_DATE( '07/09/2008 09:27:41 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, (SELECT ID FROM EG_PARTYTYPE WHERE CODE='Contractor')); 
INSERT INTO EGW_TYPEOFWORK ( ID, CODE, PARENTID, DESCRIPTION, CREATEDBY, CREATEDDATE,LASTMODIFIEDBY, LASTMODIFIEDDATE, PARTYTYPEID ) 
VALUES (SEQ_EGW_TYPEOFWORK.NEXTVAL, 'FlyOvrAndBridge', (SELECT ID FROM EGW_TYPEOFWORK WHERE CODE='RoadesAndBridges'), 'Flyovers, Bridges and Subways', 1,  TO_DATE( '07/09/2008 09:29:15 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, (SELECT ID FROM EG_PARTYTYPE WHERE CODE='Contractor'));
COMMIT;
#DOWN
