#UP

----- Over Heads Master Data---

INSERT INTO EGW_OVERHEAD ( ID, CREATED_BY, CREATED_DATE, DESCRIPTION, EXPENDITURE_TYPE, ACCOUNT, MODIFIED_BY, MODIFIED_DATE, NAME) VALUES (EGW_OVERHEAD_SEQ.nextval, 1, sysdate, 'Contingencies', 'REVENUE', (SELECT ID FROM CHARTOFACCOUNTS 
WHERE NAME='Bridges'), 1, TO_DATE('02-23-2009','MM-DD-YYYY'), 'Contingencies');

INSERT INTO EGW_OVERHEAD_RATE(ID, OVERHEAD_ID, LUMPSUM_AMOUNT, PERCENTAGE, STARTDATE, ENDDATE, MY_OHR_INDEX) VALUES (EGW_WORKS_OVERHEADRATE_SEQ.nextval, EGW_OVERHEAD_SEQ.currval, NULL, 2.5, TO_DATE('04-01-2007','MM-DD-YYYY'), TO_DATE('03-31-2010','MM-DD-YYYY'),0);

INSERT INTO EGW_OVERHEAD_RATE(ID, OVERHEAD_ID, LUMPSUM_AMOUNT, PERCENTAGE, STARTDATE, ENDDATE, MY_OHR_INDEX) VALUES (EGW_WORKS_OVERHEADRATE_SEQ.nextval, EGW_OVERHEAD_SEQ.currval, NULL, 3, TO_DATE('04-01-2010','MM-DD-YYYY'), null,1);

INSERT INTO EGW_OVERHEAD ( ID, CREATED_BY, CREATED_DATE, DESCRIPTION, EXPENDITURE_TYPE, ACCOUNT, MODIFIED_BY, MODIFIED_DATE, NAME) VALUES (EGW_OVERHEAD_SEQ.nextval, 1, sysdate,  'Supervision charges', 'REVENUE', (SELECT ID FROM CHARTOFACCOUNTS 
WHERE NAME='Bridges'), 1, TO_DATE('02-23-2009','MM-DD-YYYY'), 'Supervision charges');

INSERT INTO EGW_OVERHEAD_RATE(ID, OVERHEAD_ID, LUMPSUM_AMOUNT, PERCENTAGE, STARTDATE, ENDDATE, MY_OHR_INDEX) VALUES (EGW_WORKS_OVERHEADRATE_SEQ.nextval, EGW_OVERHEAD_SEQ.currval, NULL, 10, TO_DATE('04-01-2007','MM-DD-YYYY'), TO_DATE('03-31-2010','MM-DD-YYYY'),0);

INSERT INTO EGW_OVERHEAD_RATE(ID, OVERHEAD_ID, LUMPSUM_AMOUNT, PERCENTAGE, STARTDATE, ENDDATE, MY_OHR_INDEX) VALUES (EGW_WORKS_OVERHEADRATE_SEQ.nextval, EGW_OVERHEAD_SEQ.currval, NULL, 10.5, TO_DATE('04-01-2010','MM-DD-YYYY'), null,1);


INSERT INTO EGW_OVERHEAD ( ID, CREATED_BY, CREATED_DATE, DESCRIPTION, EXPENDITURE_TYPE, ACCOUNT, MODIFIED_BY, MODIFIED_DATE, NAME) VALUES (EGW_OVERHEAD_SEQ.nextval, 1, sysdate,  'Petty supervision charges', 'REVENUE', (SELECT ID FROM CHARTOFACCOUNTS 
WHERE NAME='Bridges'), 1, TO_DATE('02-23-2009','MM-DD-YYYY'), 'Petty supervision charges');

INSERT INTO EGW_OVERHEAD_RATE(ID, OVERHEAD_ID, LUMPSUM_AMOUNT, PERCENTAGE, STARTDATE, ENDDATE, MY_OHR_INDEX) VALUES (EGW_WORKS_OVERHEADRATE_SEQ.nextval, EGW_OVERHEAD_SEQ.currval, NULL, 2.5, TO_DATE('04-01-2007','MM-DD-YYYY'), TO_DATE('03-31-2010','MM-DD-YYYY'),0);

INSERT INTO EGW_OVERHEAD_RATE(ID, OVERHEAD_ID, LUMPSUM_AMOUNT, PERCENTAGE, STARTDATE, ENDDATE, MY_OHR_INDEX) VALUES (EGW_WORKS_OVERHEADRATE_SEQ.nextval, EGW_OVERHEAD_SEQ.currval, NULL, 3, TO_DATE('04-01-2010','MM-DD-YYYY'),null,1);

INSERT INTO EGW_OVERHEAD ( ID, CREATED_BY, CREATED_DATE, DESCRIPTION, EXPENDITURE_TYPE, ACCOUNT, MODIFIED_BY, MODIFIED_DATE, NAME) VALUES (EGW_OVERHEAD_SEQ.nextval, 1, sysdate, 'Tools and Plants', 'CAPITAL', (SELECT ID FROM CHARTOFACCOUNTS 
WHERE NAME='Bridges'), 1, TO_DATE('02-23-2009','MM-DD-YYYY'), 'Tools and Plants');

INSERT INTO EGW_OVERHEAD_RATE(ID, OVERHEAD_ID, LUMPSUM_AMOUNT, PERCENTAGE, STARTDATE, ENDDATE, MY_OHR_INDEX) VALUES (EGW_WORKS_OVERHEADRATE_SEQ.nextval, EGW_OVERHEAD_SEQ.currval, NULL, 1, TO_DATE('04-01-2007','MM-DD-YYYY'), TO_DATE('03-31-2010','MM-DD-YYYY'),0);

INSERT INTO EGW_OVERHEAD_RATE(ID, OVERHEAD_ID, LUMPSUM_AMOUNT, PERCENTAGE, STARTDATE, ENDDATE, MY_OHR_INDEX) VALUES (EGW_WORKS_OVERHEADRATE_SEQ.nextval, EGW_OVERHEAD_SEQ.currval, NULL, 1.5, TO_DATE('04-01-2010','MM-DD-YYYY'), null,1);


#DOWN
