#UP

----New Case Types 

INSERT INTO EGLC_CASETYPE_MASTER ( ID, CASE_TYPE, NOTES, ORDERNUMBER, CODE,
CREATEDDATE, LASTMODIFIEDDATE, CREATEDBY, LASTMODIFIEDBY ) VALUES ( 
SEQ_EGLC_CASETYPE_MASTER.NEXTVAL, 'Bunk Shop', NULL, NULL, NULL,  TO_Date( '06/16/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '06/16/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 1, 1); 
INSERT INTO EGLC_CASETYPE_MASTER ( ID, CASE_TYPE, NOTES, ORDERNUMBER, CODE,
CREATEDDATE, LASTMODIFIEDDATE, CREATEDBY, LASTMODIFIEDBY ) VALUES ( 
SEQ_EGLC_CASETYPE_MASTER.NEXTVAL, 'Motor Accident', NULL, NULL, NULL,  TO_Date( '06/16/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '06/16/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 1, 1);
COMMIT;

#DOWN
