#UP

----New Case Types 

INSERT INTO EGLC_CASETYPE_MASTER ( ID, CASE_TYPE, NOTES, ORDERNUMBER, CODE,
CREATEDDATE, LASTMODIFIEDDATE, CREATEDBY, LASTMODIFIEDBY ) VALUES ( 
SEQ_EGLC_CASETYPE_MASTER.NEXTVAL, 'Birth & Death Date Alteration', NULL, NULL, NULL,  TO_Date( '06/24/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '06/24/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 1, 1); 
COMMIT;


#DOWN
