#UP

-- This is for  Financials Budget junits  it uses the budget group inserted in 33_budgetSampledata and 09_pgrSampledata

--designation and position creation
INSERT INTO EG_DESIGNATION
   (DESIGNATIONID, DEPTID, DESIGNATION_NAME, DESIGNATION_LOCAL, OFFICER_LEVEL, DESIGNATION_DESCRIPTION, SANCTIONED_POSTS, OUTSOURCED_POSTS, BASIC_FROM, BASIC_TO, ANN_INCREMENT, REPORTSTO)
 VALUES
   (SEQ_DESIGNATION.NEXTVAL, 1, 'HOD', NULL, 
    1, 'HOD.', 10, 7, 4500, 
    9000, NULL, 2);
    INSERT INTO EG_DESIGNATION
   (DESIGNATIONID, DEPTID, DESIGNATION_NAME, DESIGNATION_LOCAL, OFFICER_LEVEL, DESIGNATION_DESCRIPTION, SANCTIONED_POSTS, OUTSOURCED_POSTS, BASIC_FROM, BASIC_TO, ANN_INCREMENT, REPORTSTO)
 VALUES
   (SEQ_DESIGNATION.NEXTVAL, 1, 'CHIEF ACCOUNTS OFFICER', NULL, 
    1, 'FMU.', 10, 7, 4500, 
    9000, NULL, 2);
      INSERT INTO EG_DESIGNATION
   (DESIGNATIONID, DEPTID, DESIGNATION_NAME, DESIGNATION_LOCAL, OFFICER_LEVEL, DESIGNATION_DESCRIPTION, SANCTIONED_POSTS, OUTSOURCED_POSTS, BASIC_FROM, BASIC_TO, ANN_INCREMENT, REPORTSTO)
 VALUES
   (SEQ_DESIGNATION.NEXTVAL, 1, 'DEPUTY COMMISSIONER', NULL, 
    1, 'DC.', 10, 7, 4500, 
    9000, NULL, 2);
       INSERT INTO EG_DESIGNATION
   (DESIGNATIONID, DEPTID, DESIGNATION_NAME, DESIGNATION_LOCAL, OFFICER_LEVEL, DESIGNATION_DESCRIPTION, SANCTIONED_POSTS, OUTSOURCED_POSTS, BASIC_FROM, BASIC_TO, ANN_INCREMENT, REPORTSTO)
 VALUES
   (SEQ_DESIGNATION.NEXTVAL, 1, 'FINANCIAL ADVISOR', NULL, 
    1, 'FA.', 10, 7, 4500, 
    9000, NULL, 2);
 






INSERT INTO EG_POSITION
   (POSITION_NAME, ID, SANCTIONED_POSTS, OUTSOURCED_POSTS, DESIG_ID, EFFECTIVE_DATE)
 VALUES
   ('EnggHOD', seq_pos.NEXTVAL, 10, 7, 
    (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='HOD' ), TO_DATE('03/26/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
INSERT INTO EG_POSITION
   (POSITION_NAME, ID, SANCTIONED_POSTS, OUTSOURCED_POSTS, DESIG_ID, EFFECTIVE_DATE)
 VALUES
   ('CHIEF ACCOUNTS OFFICER', seq_pos.NEXTVAL, 5, 2, 
       (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='CHIEF ACCOUNTS OFFICER' ), TO_DATE('03/26/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
 

INSERT INTO EG_POSITION
   (POSITION_NAME, ID, SANCTIONED_POSTS, OUTSOURCED_POSTS, DESIG_ID, EFFECTIVE_DATE)
 VALUES
   ('FINANCIAL ADVISOR', seq_pos.NEXTVAL, 5, 2, 
       (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='FINANCIAL ADVISOR' ), TO_DATE('03/26/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
 
INSERT INTO EG_POSITION
   (POSITION_NAME, ID, SANCTIONED_POSTS, OUTSOURCED_POSTS, DESIG_ID, EFFECTIVE_DATE)
 VALUES
   ('DEPUTY COMMISSIONER', seq_pos.NEXTVAL, 5, 2, 
       (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='DEPUTY COMMISSIONER' ), TO_DATE('03/26/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
 
INSERT INTO EG_POSITION
   (POSITION_NAME, ID, SANCTIONED_POSTS, OUTSOURCED_POSTS, DESIG_ID, EFFECTIVE_DATE)
 VALUES
   ('EGFCOMMISSIONER', seq_pos.NEXTVAL, 5, 2, 
       (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='Commissioner' ), TO_DATE('03/26/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
 



---------------------------------user
INSERT INTO EG_USER
   (ID_USER, FIRST_NAME, USER_NAME, PWD, PWD_REMINDER, UPDATETIME, IS_SUSPENDED, ISACTIVE, FROMDATE, TODATE)
 VALUES
   (seq_eg_user.NEXTVAL, 'EnggHOD', 'EnggHOD', 't27o223b7q3k0mtic20k1u32n', 'egovfinancials', TO_DATE('03/17/2008 11:59:39', 'MM/DD/YYYY HH24:MI:SS'), 'N', 1, TO_DATE('01/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
INSERT INTO EG_USER
   (ID_USER, FIRST_NAME, USER_NAME, PWD, PWD_REMINDER, UPDATETIME, IS_SUSPENDED, ISACTIVE, FROMDATE, TODATE)
 VALUES
   (seq_eg_user.NEXTVAL, 'FMU1', 'FMU1', 't27o223b7q3k0mtic20k1u32n', 'egovfinancials', TO_DATE('03/17/2008 11:59:39', 'MM/DD/YYYY HH24:MI:SS'), 'N', 1, TO_DATE('01/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO EG_USER
   (ID_USER, FIRST_NAME, USER_NAME, PWD, PWD_REMINDER, UPDATETIME, IS_SUSPENDED, ISACTIVE, FROMDATE, TODATE)
 VALUES
   (seq_eg_user.NEXTVAL, 'FA', 'FA', 't27o223b7q3k0mtic20k1u32n', 'egovfinancials', TO_DATE('03/17/2008 11:59:39', 'MM/DD/YYYY HH24:MI:SS'), 'N', 1, TO_DATE('01/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
INSERT INTO EG_USER
   (ID_USER, FIRST_NAME, USER_NAME, PWD, PWD_REMINDER, UPDATETIME, IS_SUSPENDED, ISACTIVE, FROMDATE, TODATE)
 VALUES
   (seq_eg_user.NEXTVAL, 'DC', 'DC', 't27o223b7q3k0mtic20k1u32n', 'egovfinancials', TO_DATE('03/17/2008 11:59:39', 'MM/DD/YYYY HH24:MI:SS'), 'N', 1, TO_DATE('01/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO EG_USER
   (ID_USER, FIRST_NAME, USER_NAME, PWD, PWD_REMINDER, UPDATETIME, IS_SUSPENDED, ISACTIVE, FROMDATE, TODATE)
 VALUES
   (seq_eg_user.NEXTVAL, 'Comm', 'Comm', 't27o223b7q3k0mtic20k1u32n', 'egovfinancials', TO_DATE('03/17/2008 11:59:39', 'MM/DD/YYYY HH24:MI:SS'), 'N', 1, TO_DATE('01/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));




INSERT INTO EG_EMPLOYEE
   (ID, CODE, DATE_OF_BIRTH, BLOOD_GROUP, MOTHER_TONUGE, RELIGION_ID, COMMUNITY_ID, GENDER, IS_HANDICAPPED, IS_MED_REPORT_AVAILABLE, DATE_OF_FIRST_APPOINTMENT, IDENTIFICATION_MARKS1, LANGUAGES_KNOWN_ID, MODE_OF_RECRUIMENT_ID, RECRUITMENT_TYPE_ID, CATEGORY_ID, QULIFIED_ID, SALARY_BANK, BANK,  PAY_FIXED_IN_ID, GRADE_ID, PRESENT_DESIGNATION, SCALE_OF_PAY, BASIC_PAY, SPL_PAY, PP_SGPP_PAY, ANNUAL_INCREMENT_ID, GPF_AC_NUMBER, RETIREMENT_AGE, PRESENT_DEPARTMENT, IF_ON_DUTY_ARRANGMENT_DUTY_DEP, LOCATION, COST_CENTER, ID_DEPT, ID_USER, ISACTIVE, EMPFATHER_FIRSTNAME, EMPFATHER_LASTNAME, EMPFATHER_MIDDLENAME, EMP_FIRSTNAME, EMP_LASTNAME, EMP_MIDDLENAME, IDENTIFICATION_MARKS2, PAN_NUMBER, NAME, MATURITY_DATE,EMPCATMSTR_ID)
 VALUES
   (EGPIMS_PERSONAL_INFO_SEQ.NEXTVAL, 130, TO_DATE('11/11/1982 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL, '0', '0', '0', 
    TO_DATE('11/11/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 1, 1, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL,  NULL, 
    NULL, NULL, NULL,  '452454', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, (SELECT id_user FROM EG_USER WHERE user_name ='EnggHOD'), 1, NULL, NULL, 
    NULL, 'EnggHOD', NULL, NULL, NULL, 
    NULL, 'EnggHOD', NULL,3);
INSERT INTO EG_EMPLOYEE
   (ID, CODE, DATE_OF_BIRTH, BLOOD_GROUP, MOTHER_TONUGE, RELIGION_ID, COMMUNITY_ID, GENDER, IS_HANDICAPPED, IS_MED_REPORT_AVAILABLE, DATE_OF_FIRST_APPOINTMENT, IDENTIFICATION_MARKS1, LANGUAGES_KNOWN_ID, MODE_OF_RECRUIMENT_ID, RECRUITMENT_TYPE_ID, CATEGORY_ID, QULIFIED_ID, SALARY_BANK, BANK,  PAY_FIXED_IN_ID, GRADE_ID, PRESENT_DESIGNATION, SCALE_OF_PAY, BASIC_PAY, SPL_PAY, PP_SGPP_PAY, ANNUAL_INCREMENT_ID, GPF_AC_NUMBER, RETIREMENT_AGE, PRESENT_DEPARTMENT, IF_ON_DUTY_ARRANGMENT_DUTY_DEP, LOCATION, COST_CENTER, ID_DEPT, ID_USER, ISACTIVE, EMPFATHER_FIRSTNAME, EMPFATHER_LASTNAME, EMPFATHER_MIDDLENAME, EMP_FIRSTNAME, EMP_LASTNAME, EMP_MIDDLENAME, IDENTIFICATION_MARKS2, PAN_NUMBER, NAME, MATURITY_DATE,EMPCATMSTR_ID)
 VALUES
   (EGPIMS_PERSONAL_INFO_SEQ.NEXTVAL, '135', TO_DATE('11/11/1982 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL, '0', '0', '0', 
    TO_DATE('11/11/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 1, 1, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL,  '452454', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, (SELECT id_user FROM EG_USER WHERE user_name ='FMU1'), 1, NULL, NULL, 
    NULL, 'FMU1', NULL, NULL, NULL, 
    NULL, 'FMU1', NULL,3);
 

INSERT INTO EG_EMPLOYEE
   (ID, CODE, DATE_OF_BIRTH, BLOOD_GROUP, MOTHER_TONUGE, RELIGION_ID, COMMUNITY_ID, GENDER, IS_HANDICAPPED, IS_MED_REPORT_AVAILABLE, DATE_OF_FIRST_APPOINTMENT, IDENTIFICATION_MARKS1, LANGUAGES_KNOWN_ID, MODE_OF_RECRUIMENT_ID, RECRUITMENT_TYPE_ID, CATEGORY_ID, QULIFIED_ID, SALARY_BANK, BANK, PAY_FIXED_IN_ID, GRADE_ID, PRESENT_DESIGNATION, SCALE_OF_PAY, BASIC_PAY, SPL_PAY, PP_SGPP_PAY, ANNUAL_INCREMENT_ID, GPF_AC_NUMBER, RETIREMENT_AGE, PRESENT_DEPARTMENT, IF_ON_DUTY_ARRANGMENT_DUTY_DEP, LOCATION, COST_CENTER, ID_DEPT, ID_USER, ISACTIVE, EMPFATHER_FIRSTNAME, EMPFATHER_LASTNAME, EMPFATHER_MIDDLENAME, EMP_FIRSTNAME, EMP_LASTNAME, EMP_MIDDLENAME, IDENTIFICATION_MARKS2, PAN_NUMBER, NAME, MATURITY_DATE,EMPCATMSTR_ID)
 VALUES
   (EGPIMS_PERSONAL_INFO_SEQ.NEXTVAL, '150', TO_DATE('11/11/1982 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL, '0', '0', '0', 
    TO_DATE('11/11/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 1, 1, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL,  '452454', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, (SELECT id_user FROM EG_USER WHERE user_name ='FA'), 1, NULL, NULL, 
    NULL, 'FA', NULL, NULL, NULL, 
    NULL, 'FA', NULL,3);
 
INSERT INTO EG_EMPLOYEE
   (ID, CODE, DATE_OF_BIRTH, BLOOD_GROUP, MOTHER_TONUGE, RELIGION_ID, COMMUNITY_ID, GENDER, IS_HANDICAPPED, IS_MED_REPORT_AVAILABLE, DATE_OF_FIRST_APPOINTMENT, IDENTIFICATION_MARKS1, LANGUAGES_KNOWN_ID, MODE_OF_RECRUIMENT_ID, RECRUITMENT_TYPE_ID,  CATEGORY_ID, QULIFIED_ID, SALARY_BANK, BANK,  PAY_FIXED_IN_ID, GRADE_ID, PRESENT_DESIGNATION, SCALE_OF_PAY, BASIC_PAY, SPL_PAY, PP_SGPP_PAY, ANNUAL_INCREMENT_ID, GPF_AC_NUMBER, RETIREMENT_AGE, PRESENT_DEPARTMENT, IF_ON_DUTY_ARRANGMENT_DUTY_DEP, LOCATION, COST_CENTER, ID_DEPT, ID_USER, ISACTIVE, EMPFATHER_FIRSTNAME, EMPFATHER_LASTNAME, EMPFATHER_MIDDLENAME, EMP_FIRSTNAME, EMP_LASTNAME, EMP_MIDDLENAME, IDENTIFICATION_MARKS2, PAN_NUMBER, NAME, MATURITY_DATE,EMPCATMSTR_ID)
 VALUES
   (EGPIMS_PERSONAL_INFO_SEQ.NEXTVAL, '136', TO_DATE('11/11/1982 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL, '0', '0', '0', 
    TO_DATE('11/11/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 1, 1, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL,  '452454', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, (SELECT id_user FROM EG_USER WHERE user_name ='DC'), 1, NULL, NULL, 
    NULL, 'DC', NULL, NULL, NULL, 
    NULL, 'DC', NULL,3);

INSERT INTO EG_EMPLOYEE
   (ID, CODE, DATE_OF_BIRTH, BLOOD_GROUP, MOTHER_TONUGE, RELIGION_ID, COMMUNITY_ID, GENDER, IS_HANDICAPPED, IS_MED_REPORT_AVAILABLE, DATE_OF_FIRST_APPOINTMENT, IDENTIFICATION_MARKS1, LANGUAGES_KNOWN_ID, MODE_OF_RECRUIMENT_ID, RECRUITMENT_TYPE_ID,  CATEGORY_ID, QULIFIED_ID, SALARY_BANK, BANK,  PAY_FIXED_IN_ID, GRADE_ID, PRESENT_DESIGNATION, SCALE_OF_PAY, BASIC_PAY, SPL_PAY, PP_SGPP_PAY, ANNUAL_INCREMENT_ID, GPF_AC_NUMBER, RETIREMENT_AGE, PRESENT_DEPARTMENT, IF_ON_DUTY_ARRANGMENT_DUTY_DEP, LOCATION, COST_CENTER, ID_DEPT, ID_USER, ISACTIVE, EMPFATHER_FIRSTNAME, EMPFATHER_LASTNAME, EMPFATHER_MIDDLENAME, EMP_FIRSTNAME, EMP_LASTNAME, EMP_MIDDLENAME, IDENTIFICATION_MARKS2, PAN_NUMBER, NAME, MATURITY_DATE,EMPCATMSTR_ID)
 VALUES
   (EGPIMS_PERSONAL_INFO_SEQ.NEXTVAL, '137', TO_DATE('11/11/1982 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL, '0', '0', '0', 
    TO_DATE('11/11/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 1, 1, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL,  '452454', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, (SELECT id_user FROM EG_USER WHERE user_name ='Comm'), 1, NULL, NULL, 
    NULL, 'Comm', NULL, NULL, NULL, 
    NULL, 'Comm', NULL,3);
 


INSERT INTO EG_EMP_ASSIGNMENT_PRD
   (ID, FROM_DATE, TO_DATE, ID_EMPLOYEE)
 VALUES
   (seq_ass_prd.NEXTVAL, TO_DATE('01/01/1990 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, (SELECT id FROM EG_EMPLOYEE WHERE name='EnggHOD'));
INSERT INTO EG_EMP_ASSIGNMENT_PRD
   (ID, FROM_DATE, TO_DATE, ID_EMPLOYEE)
 VALUES
   (seq_ass_prd.NEXTVAL, TO_DATE('01/01/1990 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, (SELECT id FROM EG_EMPLOYEE WHERE name='FMU1'));

   INSERT INTO EG_EMP_ASSIGNMENT_PRD
   (ID, FROM_DATE, TO_DATE, ID_EMPLOYEE)
 VALUES
   (seq_ass_prd.NEXTVAL, TO_DATE('01/01/1990 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, (SELECT id FROM EG_EMPLOYEE WHERE name='FA'));

INSERT INTO EG_EMP_ASSIGNMENT_PRD
   (ID, FROM_DATE, TO_DATE, ID_EMPLOYEE)
 VALUES
   (seq_ass_prd.NEXTVAL, TO_DATE('01/01/1990 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, (SELECT id FROM EG_EMPLOYEE WHERE name='DC'));

INSERT INTO EG_EMP_ASSIGNMENT_PRD
   (ID, FROM_DATE, TO_DATE, ID_EMPLOYEE)
 VALUES
   (seq_ass_prd.NEXTVAL, TO_DATE('01/01/1990 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, (SELECT id FROM EG_EMPLOYEE WHERE name='Comm'));


  
 INSERT INTO EG_EMP_ASSIGNMENT
   (ID, ID_FUND, ID_FUNCTION, DESIGNATIONID, ID_FUNCTIONARY, PCT_ALLOCATION, REPORTS_TO, ID_EMP_ASSIGN_PRD, FIELD, MAIN_DEPT, POSITION_ID,GOVT_ORDER_NO, GRADE_ID)
 VALUES
   (seq_ass.NEXTVAL, 12, 1, (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='HOD' ), 
    NULL, NULL, (SELECT id FROM EG_EMPLOYEE WHERE name='FMU1'),(SELECT id FROM EG_EMP_ASSIGNMENT_PRD WHERE id_employee =(SELECT id FROM EG_EMPLOYEE WHERE name='EnggHOD')), NULL, 
    (select id_dept from eg_department where dept_name ='A-Accounts Central Cell'), (SELECT id FROM EG_POSITION WHERE position_name='EnggHOD'),NULL,NULL);



 INSERT INTO EG_EMP_ASSIGNMENT
   (ID, ID_FUND, ID_FUNCTION, DESIGNATIONID, ID_FUNCTIONARY, PCT_ALLOCATION, REPORTS_TO, ID_EMP_ASSIGN_PRD, FIELD, MAIN_DEPT, POSITION_ID,GOVT_ORDER_NO, GRADE_ID)
 VALUES
   (seq_ass.NEXTVAL, 12, 1, (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='CHIEF ACCOUNTS OFFICER' ), 
    NULL, NULL, (SELECT id FROM EG_EMPLOYEE WHERE name='FA'),(SELECT id FROM EG_EMP_ASSIGNMENT_PRD WHERE id_employee =(SELECT id FROM EG_EMPLOYEE WHERE name='FMU1')), NULL, 
   (select id_dept from eg_department where dept_name ='A-Accounts Central Cell'),( SELECT id FROM EG_POSITION WHERE position_name='CHIEF ACCOUNTS OFFICER'),NULL,NULL);

 INSERT INTO EG_EMP_ASSIGNMENT 
   (ID, ID_FUND, ID_FUNCTION, DESIGNATIONID, ID_FUNCTIONARY, PCT_ALLOCATION, REPORTS_TO, ID_EMP_ASSIGN_PRD, FIELD, MAIN_DEPT, POSITION_ID,GOVT_ORDER_NO, GRADE_ID)
 VALUES
   (seq_ass.NEXTVAL, 12, 1, (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='FINANCIAL ADVISOR' ), 
    NULL, NULL, (SELECT id FROM EG_EMPLOYEE WHERE name='DC'),(SELECT id FROM EG_EMP_ASSIGNMENT_PRD WHERE id_employee =(SELECT id FROM EG_EMPLOYEE WHERE name='FA')), NULL, 
   (select id_dept from eg_department where dept_name ='A-Accounts Central Cell'),( SELECT id FROM EG_POSITION WHERE position_name='FINANCIAL ADVISOR'),NULL,NULL);

INSERT INTO EG_EMP_ASSIGNMENT
   (ID, ID_FUND, ID_FUNCTION, DESIGNATIONID, ID_FUNCTIONARY, PCT_ALLOCATION, REPORTS_TO, ID_EMP_ASSIGN_PRD, FIELD, MAIN_DEPT, POSITION_ID,GOVT_ORDER_NO, GRADE_ID)
 VALUES
   (seq_ass.NEXTVAL, 12, 1, (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='DEPUTY COMMISSIONER' ), 
    NULL, NULL, (SELECT id FROM EG_EMPLOYEE WHERE name='Commissioner'),(SELECT id FROM EG_EMP_ASSIGNMENT_PRD WHERE id_employee =(SELECT id FROM EG_EMPLOYEE WHERE name='DC')), NULL, 
    (select id_dept from eg_department where dept_name ='G-General'), (SELECT id FROM EG_POSITION WHERE position_name='DEPUTY COMMISSIONER'),NULL,NULL);

    
  --this depends on the designation Commissioner created in 09_pgrSampledata
    INSERT INTO EG_EMP_ASSIGNMENT
   (ID, ID_FUND, ID_FUNCTION, DESIGNATIONID, ID_FUNCTIONARY, PCT_ALLOCATION, REPORTS_TO, ID_EMP_ASSIGN_PRD, FIELD, MAIN_DEPT, POSITION_ID,GOVT_ORDER_NO, GRADE_ID)
 VALUES
   (seq_ass.NEXTVAL, 12, 1, (SELECT designationid FROM EG_DESIGNATION WHERE designation_name='Commissioner' ), 
    NULL, NULL, (SELECT id FROM EG_EMPLOYEE WHERE name='Comm'),(SELECT id FROM EG_EMP_ASSIGNMENT_PRD WHERE id_employee =(SELECT id FROM EG_EMPLOYEE WHERE name='Comm')), NULL, 
    (select id_dept from eg_department where dept_name ='G-General'), (SELECT id FROM EG_POSITION WHERE position_name='EGFCOMMISSIONER'),NULL,NULL);

  
    Insert into eg_user_jurlevel
   (ID_USER_JURLEVEL, ID_USER, ID_BNDRY_TYPE, UPDATETIME)
 Values
   (SEQ_EG_USER_JURLEVEL.nextVal, (select id_user from eg_user where first_name='EnggHOD'), 1, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into eg_user_jurvalues
   (ID_USER_JURLEVEL, ID_BNDRY, ID, FROMDATE, TODATE, IS_HISTORY)
 Values
   ((select id_user_jurlevel from eg_user_jurlevel where id_user=(select id_user from eg_user where first_name='EnggHOD')), 1, SEQ_EG_USER_JURVALUES.nextVal, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('08/11/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');

  
						  
						  
INSERT INTO EG_USER_JURLEVEL
   (ID_USER_JURLEVEL, ID_USER, ID_BNDRY_TYPE, UPDATETIME)
 VALUES
   (SEQ_EG_USER_JURLEVEL.NEXTVAL, (SELECT id_user FROM EG_USER WHERE first_name='FMU1'), 1, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO EG_USER_JURVALUES
   (ID_USER_JURLEVEL, ID_BNDRY, ID, FROMDATE, TODATE, IS_HISTORY)
 VALUES
   ((SELECT id_user_jurlevel FROM EG_USER_JURLEVEL WHERE id_user=(SELECT id_user FROM EG_USER WHERE first_name='FMU1')), 1, SEQ_EG_USER_JURVALUES.NEXTVAL, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('08/11/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');

  INSERT INTO EG_USER_JURLEVEL
   (ID_USER_JURLEVEL, ID_USER, ID_BNDRY_TYPE, UPDATETIME)
 VALUES
   (SEQ_EG_USER_JURLEVEL.NEXTVAL, (SELECT id_user FROM EG_USER WHERE first_name='FA'), 1, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO EG_USER_JURVALUES
   (ID_USER_JURLEVEL, ID_BNDRY, ID, FROMDATE, TODATE, IS_HISTORY)
 VALUES
   ((SELECT id_user_jurlevel FROM EG_USER_JURLEVEL WHERE id_user=(SELECT id_user FROM EG_USER WHERE first_name='FA')), 1, SEQ_EG_USER_JURVALUES.NEXTVAL, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('08/11/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');

 INSERT INTO EG_USER_JURLEVEL
   (ID_USER_JURLEVEL, ID_USER, ID_BNDRY_TYPE, UPDATETIME)
 VALUES
   (SEQ_EG_USER_JURLEVEL.NEXTVAL, (SELECT id_user FROM EG_USER WHERE first_name='DC'), 1, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO EG_USER_JURVALUES
   (ID_USER_JURLEVEL, ID_BNDRY, ID, FROMDATE, TODATE, IS_HISTORY)
 VALUES
   ((SELECT id_user_jurlevel FROM EG_USER_JURLEVEL WHERE id_user=(SELECT id_user FROM EG_USER WHERE first_name='DC')), 1, SEQ_EG_USER_JURVALUES.NEXTVAL, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('08/11/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');


 INSERT INTO EG_USER_JURLEVEL
   (ID_USER_JURLEVEL, ID_USER, ID_BNDRY_TYPE, UPDATETIME)
 VALUES
   (SEQ_EG_USER_JURLEVEL.NEXTVAL, (SELECT id_user FROM EG_USER WHERE first_name='Comm'), 1, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

INSERT INTO EG_USER_JURVALUES
   (ID_USER_JURLEVEL, ID_BNDRY, ID, FROMDATE, TODATE, IS_HISTORY)
 VALUES
   ((SELECT id_user_jurlevel FROM EG_USER_JURLEVEL WHERE id_user=(SELECT id_user FROM EG_USER WHERE first_name='Comm') and ID_BNDRY_TYPE=1), 1, SEQ_EG_USER_JURVALUES.NEXTVAL, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('08/11/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');


 

INSERT INTO eg_userrole
            (id_role, id_user, ID,
             fromdate, todate, is_history
            )
     VALUES ((SELECT id_role FROM eg_roles WHERE ROLE_NAME='SuperUser'), (SELECT id_user
                   FROM eg_user
                  WHERE user_name = 'EnggHOD'), seq_eg_userrole.NEXTVAL,
             TO_DATE('01-01-2000','mm-dd-yyyy'), '', 'N'
            )   ;
	    INSERT INTO eg_userrole
            (id_role, id_user, ID,
             fromdate, todate, is_history
            )
     VALUES ((SELECT id_role FROM eg_roles WHERE ROLE_NAME='SuperUser'), (SELECT id_user
                   FROM eg_user
                  WHERE user_name = 'FMU1'), seq_eg_userrole.NEXTVAL,
             TO_DATE('01-01-2000','mm-dd-yyyy'), '', 'N'
            )   ;

	    INSERT INTO eg_userrole
            (id_role, id_user, ID,
             fromdate, todate, is_history
            )
     VALUES ((SELECT id_role FROM eg_roles WHERE ROLE_NAME='SuperUser'), (SELECT id_user
                   FROM eg_user
                  WHERE user_name = 'FA'), seq_eg_userrole.NEXTVAL,
             TO_DATE('01-01-2000','mm-dd-yyyy'), '', 'N'
            )   ;

	    INSERT INTO eg_userrole
            (id_role, id_user, ID,
             fromdate, todate, is_history
            )
     VALUES ((SELECT id_role FROM eg_roles WHERE ROLE_NAME='SuperUser'), (SELECT id_user
                   FROM eg_user
                  WHERE user_name = 'DC'), seq_eg_userrole.NEXTVAL,
             TO_DATE('01-01-2000','mm-dd-yyyy'), '', 'N'
            )   ;

	    INSERT INTO eg_userrole
            (id_role, id_user, ID,
             fromdate, todate, is_history
            )
     VALUES ((SELECT id_role FROM eg_roles WHERE ROLE_NAME='SuperUser'), (SELECT id_user
                   FROM eg_user
                  WHERE user_name = 'Comm'), seq_eg_userrole.NEXTVAL,
             TO_DATE('01-01-2000','mm-dd-yyyy'), '', 'N'
            )   ;

	

INSERT INTO EG_EMPLOYEE_DEPT(deptid,ID,assignment_id,hod)VALUES ((SELECT id_dept FROM EG_DEPARTMENT WHERE dept_NAME = 'A-Accounts Central Cell'),
SEQ_ASS_DEPT.NEXTVAL, (SELECT ID FROM EG_EMP_ASSIGNMENT WHERE position_id = (SELECT ID FROM EG_POSITION WHERE position_name = 'EnggHOD')),
(SELECT id_dept FROM EG_DEPARTMENT WHERE dept_NAME = 'A-Accounts Central Cell') );


update egf_budgetdetail set modifieddate=sysdate,modifiedby=1,createddate=sysdate,createdby=1;
update egf_budget set updatedtimestamp=sysdate,lastmodifiedby=1,createdby=1;
update eg_wf_states set modified_by=1,created_by=1,created_date=sysdate,modified_date=sysdate,owner=(SELECT ID FROM EG_POSITION WHERE position_name = 'EnggHOD') where type like 'Budget%';

commit;
#DOWN
