#UP

Insert into EGPT_MUTATION_MASTER(ID_MUTATION, MUTATION_NAME, MUTATION_DESC, TYPE, CODE,ORDER_ID) Values (SEQ_PROP_MUTATION_MSTR.nextval, 'Clerical Error', 'Clerical Error', 'MUTATION', 'CLERICAL_ERR',6);

#DOWN