#UP

Insert into EGPT_MUTATION_MASTER(ID_MUTATION, MUTATION_NAME, MUTATION_DESC, TYPE, CODE, ORDER_ID)
 Values(SEQ_PROP_MUTATION_MSTR.nextval, 'Court Order', 'Court Order', 'MUTATION', 'COURT_ORDER', 7);
 
Insert into EGPT_MUTATION_MASTER(ID_MUTATION, MUTATION_NAME, MUTATION_DESC, TYPE, CODE, ORDER_ID)
 Values(SEQ_PROP_MUTATION_MSTR.nextval, 'Family Arrangement', 'Family Arrangement', 'MUTATION', 'FMLY_ARRGMNT', 8);
 
Insert into EGPT_MUTATION_MASTER(ID_MUTATION, MUTATION_NAME, MUTATION_DESC, TYPE, CODE, ORDER_ID)
 Values(SEQ_PROP_MUTATION_MSTR.nextval, 'Partition Deed', 'Partition Deed', 'MUTATION', 'PARTITION_DEED', 9);
 
Insert into EGPT_MUTATION_MASTER(ID_MUTATION, MUTATION_NAME, MUTATION_DESC, TYPE, CODE, ORDER_ID)
 Values(SEQ_PROP_MUTATION_MSTR.nextval, 'Allotment', 'Allotment', 'MUTATION', 'ALLOTMENT', 10);
 
Insert into EGPT_MUTATION_MASTER(ID_MUTATION, MUTATION_NAME, MUTATION_DESC, TYPE, CODE, ORDER_ID)
 Values(SEQ_PROP_MUTATION_MSTR.nextval, 'Hibba', 'Hibba', 'MUTATION', 'HIBBA', 11);
 
Insert into EGPT_MUTATION_MASTER(ID_MUTATION, MUTATION_NAME, MUTATION_DESC, TYPE, CODE, ORDER_ID)
 Values(SEQ_PROP_MUTATION_MSTR.nextval, 'Release Deed', 'Release Deed', 'MUTATION', 'RELEASE_DEED', 12);
 
Insert into EGPT_MUTATION_MASTER(ID_MUTATION, MUTATION_NAME, MUTATION_DESC, TYPE, CODE, ORDER_ID)
 Values(SEQ_PROP_MUTATION_MSTR.nextval, 'Gazette Notification', 'Gazette Notification', 'MUTATION', 'GAZT_NOTFICATN', 13);
 
Insert into EGPT_MUTATION_MASTER(ID_MUTATION, MUTATION_NAME, MUTATION_DESC, TYPE, CODE, ORDER_ID)
 Values(SEQ_PROP_MUTATION_MSTR.nextval, 'Amalgamation of Companies', 'Amalgamation of Companies', 'MUTATION', 'AMALG_OF_CMPNY', 14);


commit;

#DOWN