#UP

UPDATE EG_ASSETCATEGORY SET UOM_ID=(SELECT ID FROM EG_UOM WHERE UOM='sq.m') WHERE CODE='BUILD';

UPDATE EG_ASSETCATEGORY SET UOM_ID=(SELECT ID FROM EG_UOM WHERE UOM='m') WHERE CODE='ROADS';


#DOWN

UPDATE EG_ASSETCATEGORY SET UOM_ID=NULL WHERE CODE='BUILD';

UPDATE EG_ASSETCATEGORY SET UOM_ID=NULL WHERE CODE='ROADS';
