#UP
INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE key_name='ASSET_ACCOUNT_CODE_PURPOSEID'),  
TO_DATE( '10/14/2009 01:21:15 PM', 'MM/DD/YYYY HH:MI:SS AM'), '19'); 

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE key_name='REVALUATION_RESERVE_ACCOUNT_PURPOSEID'),  
TO_DATE( '10/14/2009 01:21:15 PM', 'MM/DD/YYYY HH:MI:SS AM'), '18'); 

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE key_name='DEPRECIATION_EXPENSE_ACCOUNT_PURPOSEID'),  
TO_DATE( '10/14/2009 01:21:15 PM', 'MM/DD/YYYY HH:MI:SS AM'), '17'); 

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE key_name='CWIP_ACCOUNT_CODE_PURPOSEID'),  
TO_DATE( '10/14/2009 01:21:15 PM', 'MM/DD/YYYY HH:MI:SS AM'), '16'); 

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE key_name='ACCUMULATED_DEPRECIATION_PURPOSEID'),  
TO_DATE( '10/14/2009 01:21:15 PM', 'MM/DD/YYYY HH:MI:SS AM'), '15'); 

#DOWN

DELETE FROM EG_APPCONFIG_VALUES WHERE KEY_ID IN (SELECT id FROM EG_APPCONFIG WHERE key_name='ACCUMULATED_DEPRECIATION_PURPOSEID')
AND VALUE = '15';

DELETE FROM EG_APPCONFIG_VALUES WHERE KEY_ID IN (SELECT id FROM EG_APPCONFIG WHERE key_name='CWIP_ACCOUNT_CODE_PURPOSEID')
AND VALUE = '16';

DELETE FROM EG_APPCONFIG_VALUES WHERE KEY_ID IN (SELECT id FROM EG_APPCONFIG WHERE key_name='DEPRECIATION_EXPENSE_ACCOUNT_PURPOSEID')
AND VALUE = '17';


DELETE FROM EG_APPCONFIG_VALUES WHERE KEY_ID IN (SELECT id FROM EG_APPCONFIG WHERE key_name='REVALUATION_RESERVE_ACCOUNT_PURPOSEID')
AND VALUE = '18';


DELETE FROM EG_APPCONFIG_VALUES WHERE KEY_ID IN (SELECT id FROM EG_APPCONFIG WHERE key_name='ASSET_ACCOUNT_CODE_PURPOSEID')
AND VALUE = '19';