#UP

/** Sample data for PFSetup  master and PF Interest calculation service **/

INSERT INTO EGPAY_PFDETAILS(ID,PFHEADERID,FROMDATE,TODATE,ANNUALRATEOFINTEREST) VALUES (SEQ_PFDETAILS.nextval,
  (SELECT distinct id from EGPAY_PFHEADER WHERE PF_TYPE='GPF'),TO_DATE('04/01/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),TO_DATE('03/31/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),10);


INSERT INTO VOUCHERHEADER
   (ID, CGN, CGDATE, NAME, TYPE, DESCRIPTION, EFFECTIVEDATE, VOUCHERNUMBER, VOUCHERDATE, FUNDID, FISCALPERIODID, STATUS, ISCONFIRMED, CREATEDBY, CGVN)
 VALUES
   (SEQ_VOUCHERHEADER.NEXTVAL, 'SAL1', TO_DATE('05/20/2009 11:10:57', 'MM/DD/YYYY HH24:MI:SS'), 'Salary Journal', 'Journal Voucher', ' ',TO_DATE('05/20/2009 11:10:57', 'MM/DD/YYYY HH24:MI:SS'), 'MJSAL16/12/0910', TO_DATE('05/20/2009 11:10:57', 'MM/DD/YYYY HH24:MI:SS'), 11, 6, 0, 0, 1, 'MJ00001');

INSERT INTO VOUCHERDETAIL
   (ID, LINEID, VOUCHERHEADERID, GLCODE, ACCOUNTNAME, DEBITAMOUNT, CREDITAMOUNT)
 VALUES
   (SEQ_VOUCHERDETAIL.NEXTVAL, 1, (select id from voucherheader where cgn='SAL1' and vouchernumber='MJSAL16/12/0910' and cgvn='MJ00001' ), '3502001', 'General Provident fund', 0, 780);


 INSERT INTO GENERALLEDGER
    (ID, VOUCHERLINEID, EFFECTIVEDATE, GLCODEID, GLCODE, DEBITAMOUNT, CREDITAMOUNT, DESCRIPTION, VOUCHERHEADERID)
  VALUES
    (SEQ_GENERALLEDGER.NEXTVAL, 1, TO_DATE('05/20/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), (select id from chartofaccounts where glcode='3502001' and isactiveforposting='1'), '3502001', 0, 780, ' ', (select id from voucherheader where cgn='SAL1' and vouchernumber='MJSAL16/12/0910' and cgvn='MJ00001' ));
    

INSERT INTO TRANSACTIONSUMMARY ( ID, GLCODEID, OPENINGDEBITBALANCE, OPENINGCREDITBALANCE,
DEBITAMOUNT, CREDITAMOUNT, ACCOUNTDETAILTYPEID, ACCOUNTDETAILKEY, FINANCIALYEARID, FUNDID,
FUNDSOURCEID, NARRATION, LASTMODIFIEDBY, LASTMODIFIEDDATE, DEPARTMENTID, FUNCTIONARYID, FUNCTIONID,
DIVISIONID ) VALUES ( 
SEQ_TRANSACTIONSUMMARY.nextval, (select id from chartofaccounts where glcode='3502001' and isactiveforposting='1'), 0, 780, 0, 0, 1, 1, 6, 11, NULL, NULL, NULL, NULL, 10, 76, 111, NULL); 


COMMIT;

#DOWN





