#UP

--Create Chart of Account for credit/debit card transaction and map it to card instrument type

--INSERT INTO EGF_ACCOUNTCODE_PURPOSE VALUES (58,'Credit Card Payment',NULL,NULL,NULL,NULL);

INSERT INTO CHARTOFACCOUNTS ( ID, GLCODE, NAME, DESCRIPTION, ISACTIVEFORPOSTING, PARENTID,
LASTMODIFIED, MODIFIEDBY, CREATED, PURPOSEID, OPERATION, TYPE, CLASS, CLASSIFICATION, FUNCTIONREQD,
BUDGETCHECKREQ, SCHEDULEID, RECEIPTSCHEDULEID, RECEIPTOPERATION, PAYMENTSCHEDULEID,
PAYMENTOPERATION, MAJORCODE, CREATEDBY ) VALUES ( 
SEQ_CHARTOFACCOUNTS.NEXTVAL, '4501003', 'Credit Card Payment', NULL, 1, 302,  TO_Date( '12/08/2009 10:45:12 AM', 
'MM/DD/YYYY HH:MI:SS AM'), 1,  TO_Date( '12/08/2009 10:45:12 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, 
NULL, 'A', NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '450', NULL); 

INSERT INTO EGF_INSTRUMENTACCOUNTCODES VALUES (SEQ_EGF_INSTRUMENTACCOUNTCODES.NEXTVAL,(SELECT ID FROM 
EGF_INSTRUMENTTYPE WHERE TYPE='card'),
(SELECT ID FROM CHARTOFACCOUNTS WHERE GLCODE='4501003'),1,1,SYSDATE,SYSDATE);


#DOWN
