#UP
Insert into EG_UOM Values (SEQ_EG_UOM.NEXTVAL, (select id from eg_uomcategory where category='Length'), '30 MTR', '30 METER', 30, 0, sysdate,sysdate, 1,1);
Insert into EG_UOM Values (SEQ_EG_UOM.NEXTVAL, (select id from eg_uomcategory where category='AREA'), '10 SQM', '10 SQM', 10, 0, sysdate,sysdate, 1,1);

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES
(SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='EXCEPTIONALSOR'),  SYSDATE, '10 SQM,10');
INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES
(SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='EXCEPTIONALSOR'),  SYSDATE, '30 MTR,30'); 

#DOWN
delete from EG_APPCONFIG_VALUES where  KEY_ID in (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='EXCEPTIONALSOR')
