#UP
INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE key_name='CONTRACTOR_ADVANCE_CODE'),  
TO_DATE( '02/22/2010 01:21:15 PM', 'MM/DD/YYYY HH:MI:SS AM'), '4604002'); 
#DOWN
DELETE FROM EG_APPCONFIG_VALUES WHERE KEY_ID IN (SELECT id FROM EG_APPCONFIG WHERE key_name='CONTRACTOR_ADVANCE_CODE')
AND VALUE = '4604002';



