#UP
INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE key_name='contingencyBillPurposeIds'),  
TO_DATE( '03/03/2010', 'MM/DD/YYYY'), 26); 

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE key_name='contingencyBillPurposeIds'),  
TO_DATE( '03/03/2010', 'MM/DD/YYYY'), 27);

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE key_name='contingencyBillPurposeIds'),  
TO_DATE( '03/03/2010', 'MM/DD/YYYY'), 28);

#DOWN
DELETE FROM EG_APPCONFIG_VALUES where key_id = (select id from EG_APPCONFIG where KEY_NAME = 'contingencyBillPurposeIds');

