#UP
INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES 
(SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='salaryBillDefaultPurposeId'),  SYSDATE, '31');
#DOWN