#UP
INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES
(SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='STATUS_FOR_WORKORDER_CREATION'),  SYSDATE, '0'); 
#DOWN
delete from EG_APPCONFIG_VALUES where key_id (select id from EG_APPCONFIG where key_name='STATUS_FOR_WORKORDER_CREATION');

