#UP
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-Revenue'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO R1');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-110'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO R2');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-120'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO R3');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-130'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO R4');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-140'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO R5');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-150'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO R6');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-160'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO R7');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-170'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO R8');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-171'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO R9');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-180'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO R10');

insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-Expense'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO F1');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-210'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO F2');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-220'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO F3');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-230'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO F4');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-240'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO F5');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-250'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO F6');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-260'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO F7');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-270'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO F8');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-271'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO F9');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-280'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO F10');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'functionWiseBudgetReport-290'),to_date('01/04/2009','dd/MM/yyyy'),'FORM NO F11');

insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-110'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D1');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-110'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D2');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-110'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D3');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-120'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D4');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-130'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D5');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-140'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D6');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-150'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D7');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-160'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D8');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-170'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D9');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-171'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D10');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-180'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D11');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-210'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D12');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-220'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D13');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-230'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D14');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-240'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D15');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-250'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D16');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-260'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D17');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-270'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D18');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-280'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D19');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'departmentWiseBudgetReport-290'),to_date('01/04/2009','dd/MM/yyyy'),'FORM No D20');

#DOWN

