#UP
update eg_module set isenabled=1 where module_name='AssetReports';
update eg_action set is_enabled=0 where name in ('Register of Land','Register of Immovable Properties'
,'Register of Movable Properties');

Insert into eg_action
   (ID, NAME, ENTITYID, TASKID, UPDATEDTIME, URL, QUERYPARAMS, URLORDERID, MODULE_ID, ORDER_NUMBER, DISPLAY_NAME, IS_ENABLED, ACTION_HELP_URL, CONTEXT_ROOT)
 Values
   (seq_eg_action.nextVal, 'Asset Register Report', NULL,NULL, sysdate, 
    '/assetreport/assetRegisterReport!newform.action', 'xmlconfigname=assets_config.xml&categoryname=AssetCategoryName', NULL, (select id_module from eg_module where module_name='AssetReports'), 4, 
    'Asset Register Report', 1, null, 'egassets');
    
INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='SuperUser'),
(SELECT id FROM EG_ACTION WHERE name='Asset Register Report'));

INSERT INTO EG_USER(ID_USER, FIRST_NAME, USER_NAME, PWD, PWD_REMINDER, UPDATETIME, IS_SUSPENDED, ISACTIVE, FROMDATE, TODATE)
 VALUES (seq_eg_user.NEXTVAL, 'ASSETADMIN', 'ASSETADMIN', 't27o223b7q3k0mtic20k1u32n', 'egovfinancials', TO_DATE('03/17/2008 11:59:39', 'MM/DD/YYYY HH24:MI:SS'), 'N', 1, TO_DATE('01/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));


INSERT INTO EG_EMPLOYEE (ID, CODE, DATE_OF_BIRTH, BLOOD_GROUP, MOTHER_TONUGE, RELIGION_ID, COMMUNITY_ID, GENDER, IS_HANDICAPPED, IS_MED_REPORT_AVAILABLE, DATE_OF_FIRST_APPOINTMENT, IDENTIFICATION_MARKS1, LANGUAGES_KNOWN_ID, MODE_OF_RECRUIMENT_ID, RECRUITMENT_TYPE_ID, CATEGORY_ID, QULIFIED_ID, SALARY_BANK, BANK,  PAY_FIXED_IN_ID, GRADE_ID, PRESENT_DESIGNATION, SCALE_OF_PAY, BASIC_PAY, SPL_PAY, PP_SGPP_PAY, ANNUAL_INCREMENT_ID, GPF_AC_NUMBER, RETIREMENT_AGE, PRESENT_DEPARTMENT, IF_ON_DUTY_ARRANGMENT_DUTY_DEP, LOCATION, COST_CENTER, ID_DEPT, ID_USER, ISACTIVE, EMPFATHER_FIRSTNAME, EMPFATHER_LASTNAME, EMPFATHER_MIDDLENAME, EMP_FIRSTNAME, EMP_LASTNAME, EMP_MIDDLENAME, IDENTIFICATION_MARKS2, PAN_NUMBER, NAME, MATURITY_DATE,EMPCATMSTR_ID)
 VALUES (EGPIMS_PERSONAL_INFO_SEQ.NEXTVAL, '9999', TO_DATE('11/11/1982 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL, '0', '0', '0', 
    TO_DATE('11/11/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 1, 1, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL,  NULL, 
    NULL, NULL, NULL,  '9252', 
    NULL, NULL, NULL, NULL, NULL, 
    (select id_dept from eg_department where dept_code='A'), (SELECT id_user FROM EG_USER WHERE user_name ='ASSETADMIN'), 1, NULL, NULL, 
    NULL, 'ASSETADMIN', NULL, NULL, NULL, 
    NULL, 'ASSETADMIN', NULL,3);

INSERT INTO EG_EMP_ASSIGNMENT_PRD (ID, FROM_DATE, TO_DATE, ID_EMPLOYEE)
 VALUES (seq_ass_prd.NEXTVAL, TO_DATE('01/01/1990 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, (SELECT id FROM EG_EMPLOYEE WHERE name='ASSETADMIN'));


INSERT INTO EG_USER_JURLEVEL(ID_USER_JURLEVEL, ID_USER, ID_BNDRY_TYPE, UPDATETIME)
 VALUES (SEQ_EG_USER_JURLEVEL.NEXTVAL, (SELECT id_user FROM EG_USER WHERE first_name='ASSETADMIN'), 1, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
 
 INSERT INTO EG_USER_JURVALUES (ID_USER_JURLEVEL, ID_BNDRY, ID, FROMDATE, TODATE, IS_HISTORY)
 VALUES ((SELECT id_user_jurlevel FROM EG_USER_JURLEVEL WHERE id_user=(SELECT id_user FROM EG_USER WHERE first_name='ASSETADMIN')), 1, SEQ_EG_USER_JURVALUES.NEXTVAL, TO_DATE('08/11/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('08/11/2099 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'N');
 
 INSERT INTO EG_ROLES (ID_ROLE, ROLE_NAME, ROLE_DESC, ROLE_NAME_LOCAL, ROLE_DESC_LOCAL, UPDATETIME,UPDATEUSERID) 
VALUES (SEQ_EG_ROLES.nextval, 'ASSET ADMIN', 'ASSET ADMIN', NULL, NULL,  SYSDATE, NULL); 

INSERT INTO EG_USERROLE (id_role, id_user, ID, fromdate, todate, is_history)
VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'), 
(SELECT id_user FROM EG_USER WHERE FIRST_NAME = 'ASSETADMIN'), 
seq_eg_userrole.NEXTVAL,TO_DATE('01-01-2000','mm-dd-yyyy'), '', 'N' );


INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='Asset Register Report'));

INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='LOGIN'));

INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='DEFAULT'));

INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='WorkflowInbox'));

INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='EgiIndex'));

INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='ASSETS HOME'));

INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='Create Asset Category'));

INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='View Asset Category'));

INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='Modify Asset Category'));



INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='Create Asset'));

INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='View Asset'));

INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='Modify Asset'));

INSERT INTO EG_ROLEACTION_MAP (roleid,actionid) VALUES ((SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN'),
(SELECT id FROM EG_ACTION WHERE name='Create Asset Revaluation'));
#DOWN
update eg_module set isenabled=0 where module_name='AssetReports';
delete from EG_ROLEACTION_MAP where roleid = (SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN');
delete from  EG_USERROLE where id_role =(SELECT id_role FROM EG_ROLES WHERE ROLE_NAME='ASSET ADMIN');
delete from EG_ROLES where ROLE_NAME='ASSET ADMIN';
delete from eg_action where name='Asset Register Report';

