#UP


/******************** TRADE NATURE SAMPLE DATA *****************
REMOVING  SCRIPTS AS THIS TABLE IS NOT USED ANYMORE.

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'SuperMarket',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Jewellery',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select id_user from   EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Readymade Garment',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Automobile Spares',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select id_user 	from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Automobile Showroom',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select 		id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Bakery',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select 		id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Grocery',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select 		id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Electronics',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select 		id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Electricals',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select 		id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Gymnasium',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select 		id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Health Club',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select 		id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Medical Shop',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select 		id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Fastfood Hotel',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select 		id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Restaurants',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select 		id_user from EG_USER where user_name='egovernments'));

INSERT INTO EGTL_MSTR_TRADE_NATURE
   (ID,TRADE_NATURE,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY)
VALUES(SEQ_EGTL_MSTR_TRADENATURE.NEXTVAL,'Petty Shop',SYSDATE,SYSDATE,(select id_user from EG_USER where user_name='egovernments'),(select 		id_user from EG_USER where user_name='egovernments'));
**/

#DOWN
/**
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='SuperMarket';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Jewellery';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Readymade Garment';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Automobile Spares';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Automobile Showroom';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Bakery';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Grocery';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Electronics';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Health Club';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Electricals';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Gymnasium';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Medical Shop';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Fastfood Hotel';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Restaurants';
DELETE FROM EGTL_MSTR_TRADE_NATURE WHERE TRADE_NATURE='Petty Shop';

**/

