#UP

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','NEW',null,null,'Garden Inspector,JUNIOR ENGINEER','budgetApp','CREATED','Pending Approval for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','CREATED','Forward,Cancel',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','TECH_SANCTIONED',null,'Pending Budgetary Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','budgetApp','BUDGETARY_APPR_CHECKED','Pending Budgetary Appropriation Approval','Chief Accounts and Finance Officer','BUDGETARY_APPR_CHECKED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','BUDGETARY_APPR_CHECKED',null,'Pending Budgetary Appropriation Approval','Chief Accounts and Finance Officer','budgetApp','BUDGETARY_APPROPRIATION_DONE','Pending Admin Sanction','Municipal Commissioner','BUDGETARY_APPROPRIATION_DONE','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','BUDGETARY_APPROPRIATION_DONE',null,'Pending Admin Sanction','Municipal Commissioner','budgetApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','REJECTED',null,null,'Garden Inspector,JUNIOR ENGINEER','budgetApp','RESUBMITTED','Pending Approval for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','NEW',null,null,'Garden Inspector,JUNIOR ENGINEER','budgetApp','CREATED','Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','CREATED','Forward,Cancel',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','TECH_SANCTIONED',null,'Pending Budgetary Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','budgetApp','BUDGETARY_APPR_CHECKED','Pending Budgetary Appropriation Approval','Chief Accounts and Finance Officer','BUDGETARY_APPR_CHECKED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','BUDGETARY_APPR_CHECKED',null,'Pending Budgetary Appropriation Approval','Chief Accounts and Finance Officer','budgetApp','BUDGETARY_APPROPRIATION_DONE','Pending Admin Sanction','Municipal Commissioner','BUDGETARY_APPROPRIATION_DONE','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','BUDGETARY_APPROPRIATION_DONE',null,'Pending Admin Sanction','Municipal Commissioner','budgetApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','REJECTED',null,null,'Garden Inspector,JUNIOR ENGINEER','budgetApp','RESUBMITTED','Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','NEW',null,null,'Garden Inspector,JUNIOR ENGINEER','budgetApp','CREATED','Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','CREATED','Forward,Cancel',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','TECH_SANCTIONED',null,'Pending Budgetary Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','budgetApp','BUDGETARY_APPR_CHECKED','Pending Budgetary Appropriation Approval','Chief Accounts and Finance Officer','BUDGETARY_APPR_CHECKED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','BUDGETARY_APPR_CHECKED',null,'Pending Budgetary Appropriation Approval','Chief Accounts and Finance Officer','budgetApp','BUDGETARY_APPROPRIATION_DONE','Pending Admin Check','Municipal Commissioner','BUDGETARY_APPROPRIATION_DONE','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','BUDGETARY_APPROPRIATION_DONE',null,'Pending Admin Check','Municipal Commissioner','budgetApp','ADMIN_CHECKED','Pending Admin Sanction','Municipal Commissioner','ADMIN_CHECKED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','ADMIN_CHECKED',null,'Pending Admin Sanction','Municipal Commissioner','budgetApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','REJECTED',null,null,'Garden Inspector,JUNIOR ENGINEER','budgetApp','RESUBMITTED','Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','MBHeader','NEW',null,null,'Garden Inspector,JUNIOR ENGINEER',null,'CREATED','Pending for check','Garden Superintendent,DEPUTY ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','MBHeader','CREATED',null,'Pending for check','Garden Superintendent,DEPUTY ENGINEER',null,'CHECKED','Pending for Approval','Garden Superintendent,EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','MBHeader','CHECKED',null,'Pending for Approval','Garden Superintendent,EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','MBHeader','REJECTED',null,null,'Garden Inspector,JUNIOR ENGINEER',null,'RESUBMITTED','Pending for check','Garden Superintendent,DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','MBHeader','RESUBMITTED',null,'Pending for check','Garden Superintendent,DEPUTY ENGINEER',null,'CHECKED','Pending for Approval','Garden Superintendent,EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','ContractorBillRegister','NEW',null,null,'Garden Inspector,JUNIOR ENGINEER',null,'CREATED','Pending for Check','Garden Superintendent,DEPUTY ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','ContractorBillRegister','CREATED',null,'Pending for Check','Garden Superintendent,DEPUTY ENGINEER',null,'CHECKED','Pending for Approval','Garden Superintendent,EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','ContractorBillRegister','CHECKED',null,'Pending for Approval','Garden Superintendent,EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','ContractorBillRegister','REJECTED',null,null,'Garden Inspector,JUNIOR ENGINEER',null,'RESUBMITTED','Pending for Check','Garden Superintendent,DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','ContractorBillRegister','RESUBMITTED',null,'Pending for Check','Garden Superintendent,DEPUTY ENGINEER',null,'CHECKED','Pending for Approval','Garden Superintendent,EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','Indent','NEW',null,null,'Garden Superintendent',null,'CREATED','Pending for Approval','Garden Superintendent','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','Indent','CREATED',null,'Pending for Approval','Garden Superintendent',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','Indent','REJECTED',null,null,'Garden Superintendent',null,'RESUBMITTED','Pending for Approval','Garden Superintendent','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','Indent','RESUBMITTED',null,'Pending for Approval','Garden Superintendent',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','NEW',null,null,'Garden Inspector,JUNIOR ENGINEER','depositCodeApp','CREATED','Pending Approval for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','CREATED','Forward,Cancel',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Deposit Code Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','TECH_SANCTIONED',null,'Pending Deposit Code Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','depositCodeApp','DEPOSIT_CODE_APPR_CHECKED','Pending Deposit Code Appropriation Approval','Chief Accounts and Finance Officer','DEPOSIT_CODE_APPR_CHECKED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','DEPOSIT_CODE_APPR_CHECKED',null,'Pending Deposit Code Appropriation Approval','Chief Accounts and Finance Officer','depositCodeApp','DEPOSIT_CODE_APPR_DONE','Pending Admin Sanction','Municipal Commissioner','DEPOSIT_CODE_APPR_DONE','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','DEPOSIT_CODE_APPR_DONE',null,'Pending Admin Sanction','Municipal Commissioner','depositCodeApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','REJECTED',null,null,'Garden Inspector,JUNIOR ENGINEER','depositCodeApp','RESUBMITTED','Pending Approval for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Deposit Code Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','NEW',null,null,'Garden Inspector,JUNIOR ENGINEER','depositCodeApp','CREATED','Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','CREATED','Forward,Cancel',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Deposit Code Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','TECH_SANCTIONED',null,'Pending Deposit Code Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','depositCodeApp','DEPOSIT_CODE_APPR_CHECKED','Pending Deposit Code Appropriation Approval','Chief Accounts and Finance Officer','DEPOSIT_CODE_APPR_CHECKED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','DEPOSIT_CODE_APPR_CHECKED',null,'Pending Deposit Code Appropriation Approval','Chief Accounts and Finance Officer','depositCodeApp','DEPOSIT_CODE_APPR_DONE','Pending Admin Sanction','Municipal Commissioner','DEPOSIT_CODE_APPR_DONE','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','DEPOSIT_CODE_APPR_DONE',null,'Pending Admin Sanction','Municipal Commissioner','depositCodeApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','REJECTED',null,null,'Garden Inspector,JUNIOR ENGINEER','depositCodeApp','RESUBMITTED','Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Deposit Code Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','NEW',null,null,'Garden Inspector,JUNIOR ENGINEER','depositCodeApp','CREATED','Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','CREATED','Forward,Cancel',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Deposit Code Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','TECH_SANCTIONED',null,'Pending Deposit Code Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','depositCodeApp','DEPOSIT_CODE_APPR_CHECKED','Pending Deposit Code Appropriation Approval','Chief Accounts and Finance Officer','DEPOSIT_CODE_APPR_CHECKED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','DEPOSIT_CODE_APPR_CHECKED',null,'Pending Deposit Code Appropriation Approval','Chief Accounts and Finance Officer','depositCodeApp','DEPOSIT_CODE_APPR_DONE','Pending Admin Check','Municipal Commissioner','DEPOSIT_CODE_APPR_DONE','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','DEPOSIT_CODE_APPR_DONE',null,'Pending Admin Check','Municipal Commissioner','depositCodeApp','ADMIN_CHECKED','Pending Admin Sanction','Municipal Commissioner','ADMIN_CHECKED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','ADMIN_CHECKED',null,'Pending Admin Sanction','Municipal Commissioner','depositCodeApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','REJECTED',null,null,'Garden Inspector,JUNIOR ENGINEER','depositCodeApp','RESUBMITTED','Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','Garden Superintendent,EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Budgetary Appropriation Check','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','TenderFile','NEW',null,null,'Garden Superintendent',null,'CREATED','Pending for Approval','Garden Superintendent,EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','TenderFile','CREATED',null,'Pending for Approval','Garden Superintendent,EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','TenderFile','REJECTED',null,null,'Garden Superintendent',null,'RESUBMITTED','Pending for Approval','Garden Superintendent,EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Garden','TenderFile','RESUBMITTED',null,'Pending for Approval','Garden Superintendent,EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);


#DOWN

Delete from eg_wf_matrix where objectType in ('TenderFile','AbstractEstimate','Indent','MBHeader','ContractorBillRegister') and department='Garden';
