#UP

   
-- This is for Budget 11-12

 INSERT INTO EG_WF_STATES ( ID, TYPE, VALUE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE,
OWNER, DATE1, DATE2, TEXT1, TEXT2, PREVIOUS, NEXT ) VALUES (
EG_WF_STATES_SEQ.NEXTVAL, 'Budget',
(SELECT value FROM EG_APPCONFIG_VALUES WHERE key_id IN(SELECT id FROM EG_APPCONFIG WHERE key_name='budget_final_approval_status')),
NULL, TO_DATE( '08/27/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, TO_DATE( '08/27/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), (select id from eg_position where position_name='EnggHOD'), NULL, NULL, 'workflow.start', NULL, NULL, NULL);



INSERT INTO EGF_BUDGET
   (ID, NAME, DESCRIPTION, FINANCIALYEARID, STATE_ID, ISACTIVEBUDGET, UPDATEDTIMESTAMP, ISPRIMARYBUDGET,ISBERE)
 VALUES
   (seq_egf_budget.NEXTVAL, '2011-2012-BE', '2011-2012-BE', 
   (SELECT id FROM FINANCIALYEAR WHERE FINANCIALYEAR='2011-12')
   , (select max(id) from eg_wf_states), 1, TO_DATE('05/19/2008 14:36:55', 'MM/DD/YYYY HH24:MI:SS'), 1,'BE' );
   
   
---- This is for Budget detail

INSERT INTO EGF_BUDGETDETAIL
   (ID, BUDGETGROUP, BUDGET, ORIGINALAMOUNT, APPROVEDAMOUNT, BUDGETAVAILABLE, FUNCTION, STATE_ID, MODIFIEDDATE, SCHEME, SUBSCHEME,EXECUTING_DEPARTMENT,BOUNDARY, FUND)
 VALUES
   (seq_egf_budgetdetail.NEXTVAL,(SELECT id FROM EGF_BUDGETGROUP WHERE name='41120-BUILDING WORKS'),
   (SELECT id FROM EGF_BUDGET WHERE name='2011-2012-BE'), 20000000, 0, 20000000, (SELECT id FROM FUNCTION WHERE code='0201')
   , NULL, TO_DATE('11/16/2008 22:15:19', 'MM/DD/YYYY HH24:MI:SS'),NULL, NULL,(SELECT id_dept FROM EG_DEPARTMENT WHERE dept_name='L-Electrical'),(SELECT id_bndry FROM EG_BOUNDARY WHERE name='014'), (SELECT id FROM FUND WHERE code='0102'));
   

INSERT INTO EGF_BUDGETDETAIL
   (ID, BUDGETGROUP, BUDGET, ORIGINALAMOUNT, APPROVEDAMOUNT, BUDGETAVAILABLE, FUNCTION, STATE_ID, MODIFIEDDATE, SCHEME, SUBSCHEME,EXECUTING_DEPARTMENT,BOUNDARY, FUND)
 VALUES
   (seq_egf_budgetdetail.NEXTVAL,(SELECT id FROM EGF_BUDGETGROUP WHERE name='41120-BUILDING WORKS'),
   (SELECT id FROM EGF_BUDGET WHERE name='2011-2012-BE'), 10000000, 0, 10000000, (SELECT id FROM FUNCTION WHERE code='0101')
   , NULL, TO_DATE('11/16/2008 22:15:19', 'MM/DD/YYYY HH24:MI:SS'),NULL, NULL,(SELECT id_dept FROM EG_DEPARTMENT WHERE dept_name='L-Electrical'),(SELECT id_bndry FROM EG_BOUNDARY WHERE name='014'), (SELECT id FROM FUND WHERE code='0102'));


#DOWN

delete from egf_budgetdetail where budget in (SELECT id FROM EGF_BUDGET WHERE name='2011-2012-BE');
delete from EGF_BUDGET WHERE name='2011-2012-BE';