#UP

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,
NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','MBHeader','NEW',null,null,'JUNIOR ENGINEER',null,'CREATED','Pending for check',
'ASSISTANT ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,
NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','MBHeader','CREATED',null,'Pending for check','ASSISTANT ENGINEER',null,'CHECKED','Pending for Approval',
'EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,
NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','MBHeader','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER',null,'APPROVED','END',
null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,
NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','MBHeader','REJECTED',null,null,'JUNIOR ENGINEER',null,'RESUBMITTED','Pending for check',
'ASSISTANT ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,
NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','MBHeader','RESUBMITTED',null,'Pending for check','ASSISTANT ENGINEER',null,'CHECKED','Pending for Approval',
'EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

#DOWN

delete from EG_WF_MATRIX where DEPARTMENT='Electrical' and OBJECTTYPE='MBHeader';


