#UP

Insert into EG_WF_MATRIX
   (ID, DEPARTMENT, OBJECTTYPE, CURRENTSTATE,PENDINGACTIONS,CURRENTDESIGNATION, NEXTSTATE, NEXTACTION, NEXTDESIGNATION, NEXTSTATUS, VALIDACTIONS)
 Values
   (EG_WF_MATRIX_SEQ.nextVal, 'Electrical', 'Indent', 'NEW',null, 'JUNIOR ENGINEER', 'Created', 'Pending for Check', 'ASSISTANT ENGINEER', 'CREATED', 'Forward,Cancel');

Insert into EG_WF_MATRIX
   (ID, DEPARTMENT, OBJECTTYPE, CURRENTSTATE,PENDINGACTIONS,CURRENTDESIGNATION, NEXTSTATE, NEXTACTION, NEXTDESIGNATION, NEXTSTATUS, VALIDACTIONS)
 Values
   (EG_WF_MATRIX_SEQ.nextVal, 'Electrical', 'Indent', 'Created','Pending for Check', 'ASSISTANT ENGINEER', 'Checked', 'Pending for Approval', 'EXECUTIVE ENGINEER', 'CHECKED', 'Forward,Reject');

Insert into EG_WF_MATRIX
   (ID, DEPARTMENT, OBJECTTYPE, CURRENTSTATE,PENDINGACTIONS,CURRENTDESIGNATION, NEXTSTATE, NEXTACTION, NEXTDESIGNATION, NEXTSTATUS, VALIDACTIONS)
 Values
   (EG_WF_MATRIX_SEQ.nextVal, 'Electrical', 'Indent', 'Checked', 'Pending for Approval', 'EXECUTIVE ENGINEER', 'Approved', 'END', null, 'APPROVED', 'Approve,Reject');

Insert into EG_WF_MATRIX
   (ID, DEPARTMENT, OBJECTTYPE, CURRENTSTATE,PENDINGACTIONS,CURRENTDESIGNATION, NEXTSTATE, NEXTACTION, NEXTDESIGNATION, NEXTSTATUS, VALIDACTIONS)
 Values
   (EG_WF_MATRIX_SEQ.nextVal, 'Electrical', 'Indent', 'Rejected',null, 'JUNIOR ENGINEER', 'Created', 'Pending for Check', 'ASSISTANT ENGINEER', 'RESUBMITTED', 'Forward,Cancel');



#DOWN

DELETE FROM EG_WF_MATRIX WHERE OBJECTTYPE='Indent' AND DEPARTMENT='Electrical';
