#UP

UPDATE EG_WF_MATRIX SET NEXTSTATE='CREATED' 
WHERE DEPARTMENT='Electrical' and OBJECTTYPE='TenderFile' and CURRENTSTATE='NEW' and CURRENTDESIGNATION='JUNIOR ENGINEER,ASSISTANT ENGINEER';

UPDATE EG_WF_MATRIX SET CURRENTSTATE='CREATED',NEXTSTATE='APPROVED'
WHERE DEPARTMENT='Electrical' and OBJECTTYPE='TenderFile' and CURRENTSTATE='Created' and CURRENTDESIGNATION='EXECUTIVE ENGINEER';

UPDATE EG_WF_MATRIX SET CURRENTSTATE='REJECTED',NEXTSTATE='RESUBMITTED'
WHERE DEPARTMENT='Electrical' and OBJECTTYPE='TenderFile' and CURRENTSTATE='Rejected' and CURRENTDESIGNATION='JUNIOR ENGINEER,ASSISTANT ENGINEER';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,
NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) 
values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','TenderFile','RESUBMITTED',null,'Pending for Approval','EXECUTIVE ENGINEER',null,'APPROVED','END',null,
'APPROVED','Approve,Reject',null,null);

#DOWN

UPDATE EG_WF_MATRIX SET NEXTSTATE='Created' 
WHERE DEPARTMENT='Electrical' and OBJECTTYPE='TenderFile' and CURRENTSTATE='NEW' and CURRENTDESIGNATION='JUNIOR ENGINEER,ASSISTANT ENGINEER';

UPDATE EG_WF_MATRIX SET CURRENTSTATE='Created',NEXTSTATE='Approved'
WHERE DEPARTMENT='Electrical' and OBJECTTYPE='TenderFile' and CURRENTSTATE='CREATED' and CURRENTDESIGNATION='EXECUTIVE ENGINEER';

UPDATE EG_WF_MATRIX SET CURRENTSTATE='Rejected',NEXTSTATE='Create'
WHERE DEPARTMENT='Electrical' and OBJECTTYPE='TenderFile' and CURRENTSTATE='REJECTED' and CURRENTDESIGNATION='JUNIOR ENGINEER,ASSISTANT ENGINEER';

delete from EG_WF_MATRIX 
where DEPARTMENT='Electrical' and OBJECTTYPE='TenderFile' and CURRENTSTATE='RESUBMITTED' and CURRENTDESIGNATION='EXECUTIVE ENGINEER';







