#UP
--- TENDER FILE - PUBLIC WORK DEPARTMENT

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='TenderFile';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','NEW',null,null,'DEPUTY ENGINEER','','CREATED','Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CREATED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','REJECTED',null,null,'DEPUTY ENGINEER','','RESUBMITTED','Pending Checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','RESUBMITTED','Forward,Cancel',null,null);


Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','RESUBMITTED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null); 

--- WORK ORDER - PUBLIC WORK DEPARTMENT

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='WorkOrder';

-- WO: PWD-Workflow-Zones

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','NEW',null,null,'DEPUTY ENGINEER','ZonalPublicWork','CREATED','Pending for Approval','ASST. COMMISSIONER / WARD OFFICER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending for Approval','ASST. COMMISSIONER / WARD OFFICER','ZonalPublicWork','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','REJECTED',null,null,'DEPUTY ENGINEER','ZonalPublicWork','RESUBMITTED','Pending for Approval','ASST. COMMISSIONER / WARD OFFICER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending for Approval','ASST. COMMISSIONER / WARD OFFICER','ZonalPublicWork','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);


-- WO: PWD-Workflow-HQ 

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','NEW',null,null,'JUNIOR ENGINEER','HQPublicWork','CREATED','Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','HQPublicWork','CREATED','Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','CREATED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','HQPublicWork','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','HQPublicWork','APPROVED','END','null','APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','REJECTED',null,null,'JUNIOR ENGINEER','HQPublicWork','RESUBMITTED','Pending Checking by DEPUTY ENGINEER','DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','HQPublicWork','RESUBMITTED','Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','RESUBMITTED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','HQPublicWork','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);


--- MBHEADER - PUBLIC WORK DEPARTMENT

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='MBHeader';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','NEW',null,null,'DEPUTY ENGINEER','','CREATED','Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','CREATED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','REJECTED',null,null,'DEPUTY ENGINEER','','RESUBMITTED','Pending Checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','RESUBMITTED','Forward,Cancel',null,null);


Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','RESUBMITTED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null); 

--- CONTRACTOR BILL - PUBLIC WORK DEPARTMENT

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='ContractorBillRegister';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','NEW',null,null,'DEPUTY ENGINEER','','CREATED','Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','CREATED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','REJECTED',null,null,'DEPUTY ENGINEER','','RESUBMITTED','Pending Checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','RESUBMITTED','Forward,Cancel',null,null);


Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','RESUBMITTED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null); 


#DOWN


--- TENDER FILE 

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='TenderFile';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CHECKED',null,'Pending for Approval','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','quotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CREATED',null,'Pending for Approval','EXECUTIVE ENGINEER','noQuotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CREATED',null,'Pending for Check','EXECUTIVE ENGINEER','quotation','CHECKED','Pending for Approval','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','NEW',null,null,'EXECUTIVE ENGINEER','noQuotation','CREATED','Pending for Approval','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','NEW',null,null,'JUNIOR ENGINEER','quotation','CREATED','Pending for Check','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','REJECTED',null,null,'EXECUTIVE ENGINEER','noQuotation','RESUBMITTED','Pending for Approval','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','REJECTED',null,null,'JUNIOR ENGINEER','quotation','RESUBMITTED','Pending for Check','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','RESUBMITTED',null,'Pending for Approval','EXECUTIVE ENGINEER','noQuotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','RESUBMITTED',null,'Pending for Check','EXECUTIVE ENGINEER','quotation','CHECKED','Pending for Approval','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','CHECKED','Forward,Reject',null,null);


--- WORK ORDER 

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='WorkOrder';

-- WO - NoQuotation

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','NEW',null,null,'EXECUTIVE ENGINEER','noQuotation','CREATED','Pending for Approval','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending for Approval','EXECUTIVE ENGINEER','noQuotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending for Approval','EXECUTIVE ENGINEER','noQuotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','REJECTED',null,null,'EXECUTIVE ENGINEER','noQuotation','RESUBMITTED','Pending for Approval','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);


-- WO - Quotation

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','NEW',null,null,'EXECUTIVE ENGINEER','quotation','CREATED','Pending for Approval','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending for Approval','EXECUTIVE ENGINEER','quotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending for Approval','EXECUTIVE ENGINEER','quotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','REJECTED',null,null,'EXECUTIVE ENGINEER','quotation','RESUBMITTED','Pending for Approval','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);


-- WO - RateContract

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','NEW',null,null,'EXECUTIVE ENGINEER','rateContract','CREATED','Pending for Approval','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending for Approval','EXECUTIVE ENGINEER','rateContract','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending for Approval','EXECUTIVE ENGINEER','rateContract','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','REJECTED',null,null,'EXECUTIVE ENGINEER','rateContract','RESUBMITTED','Pending for Approval','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

--- MBHEADER

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='MBHeader';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','CREATED',null,'Pending for check','EXECUTIVE ENGINEER',null,'CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','NEW',null,null,'JUNIOR ENGINEER',null,'CREATED','Pending for check','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','REJECTED',null,null,'JUNIOR ENGINEER',null,'RESUBMITTED','Pending for check','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','RESUBMITTED',null,'Pending for check','EXECUTIVE ENGINEER',null,'CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

--- CONTRACTORBILLREGISTER

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='ContractorBillRegister';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','CREATED',null,'Pending for Check','EXECUTIVE ENGINEER',null,'CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','NEW',null,null,'JUNIOR ENGINEER',null,'CREATED','Pending for Check','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','REJECTED',null,null,'JUNIOR ENGINEER',null,'RESUBMITTED','Pending for Check','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','RESUBMITTED',null,'Pending for Check','EXECUTIVE ENGINEER',null,'CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);






