#UP

--- TENDER FILE - PUBLIC WORK DEPARTMENT

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='TenderFile';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','NEW',null,null,'JUNIOR ENGINEER','','CREATED','Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CREATED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','REJECTED',null,null,'JUNIOR ENGINEER','','RESUBMITTED','Pending Checking by DEPUTY ENGINEER','DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','RESUBMITTED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

--- WORK ORDER - PUBLIC WORK DEPARTMENT - HQ

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='WorkOrder' and ADDITIONALRULE='HQPublicWork';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','NEW',null,null,'JUNIOR ENGINEER','HQPublicWork','CREATED','Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','HQPublicWork','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','HQPublicWork','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','REJECTED',null,null,'JUNIOR ENGINEER','HQPublicWork','RESUBMITTED','Pending Checking by DEPUTY ENGINEER','DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','HQPublicWork','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);  
 


--- MBHEADER - PUBLIC WORK DEPARTMENT

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='MBHeader';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','NEW',null,null,'JUNIOR ENGINEER','','CREATED','Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','CREATED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','REJECTED',null,null,'JUNIOR ENGINEER','','RESUBMITTED','Pending Checking by DEPUTY ENGINEER','DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','RESUBMITTED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null); 

--- CONTRACTOR BILL - PUBLIC WORK DEPARTMENT

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='ContractorBillRegister';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','NEW',null,null,'JUNIOR ENGINEER','','CREATED','Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','CREATED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','REJECTED',null,null,'JUNIOR ENGINEER','','RESUBMITTED','Pending Checking by DEPUTY ENGINEER','DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','RESUBMITTED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null); 
 

#DOWN

--- TENDER FILE - PUBLIC WORK DEPARTMENT

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='TenderFile';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','NEW',null,null,'DEPUTY ENGINEER','','CREATED','Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CREATED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','REJECTED',null,null,'DEPUTY ENGINEER','','RESUBMITTED','Pending Checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','RESUBMITTED','Forward,Cancel',null,null);


Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','RESUBMITTED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null); 

--- WORK ORDER - PUBLIC WORK DEPARTMENT - HQ

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='WorkOrder' and ADDITIONALRULE='HQPublicWork';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','NEW',null,null,'JUNIOR ENGINEER','HQPublicWork','CREATED','Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','HQPublicWork','CREATED','Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','CREATED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','HQPublicWork','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','HQPublicWork','APPROVED','END','null','APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','REJECTED',null,null,'JUNIOR ENGINEER','HQPublicWork','RESUBMITTED','Pending Checking by DEPUTY ENGINEER','DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending checking by DEPUTY ENGINEER','DEPUTY ENGINEER','HQPublicWork','RESUBMITTED','Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','RESUBMITTED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','HQPublicWork','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

--- MBHEADER - PUBLIC WORK DEPARTMENT

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='MBHeader';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','NEW',null,null,'DEPUTY ENGINEER','','CREATED','Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','CREATED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','REJECTED',null,null,'DEPUTY ENGINEER','','RESUBMITTED','Pending Checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','RESUBMITTED','Forward,Cancel',null,null);


Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','RESUBMITTED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null); 

--- CONTRACTOR BILL - PUBLIC WORK DEPARTMENT

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='ContractorBillRegister';

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','NEW',null,null,'DEPUTY ENGINEER','','CREATED','Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','CREATED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER','','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','REJECTED',null,null,'DEPUTY ENGINEER','','RESUBMITTED','Pending Checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','RESUBMITTED','Forward,Cancel',null,null);


Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','RESUBMITTED',null,'Pending checking by ASST. COMMISSIONER / WARD OFFICER','ASST. COMMISSIONER / WARD OFFICER','','CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null); 


