#UP

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES
(SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='ESTIMATE_DRAFTRESOLUTION_RULES'),  SYSDATE, 'Public Work,5000000');

#DOWN

delete from EG_APPCONFIG_VALUES where  KEY_ID in (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='ESTIMATE_DRAFTRESOLUTION_RULES') and value='Public Work,5000000';
 
