#UP
UPDATE CHARTOFACCOUNTS
SET PURPOSEID = (SELECT ID FROM EGF_ACCOUNTCODE_PURPOSE WHERE NAME = 'Pension Payable Code')
WHERE GLCODE = '3501102';

#DOWN

UPDATE CHARTOFACCOUNTS
SET PURPOSEID = (SELECT ID FROM EGF_ACCOUNTCODE_PURPOSE WHERE NAME = 'Commutation Payable Code')
WHERE GLCODE = '3501102';
