package org.egov.pims.model;

import org.egov.infra.persistence.validator.annotation.Required;
import org.egov.infra.persistence.validator.annotation.Unique;

// Generated Aug 8, 2008 9:23:49 AM by Hibernate Tools 3.2.0.b9




/**
 * EgeisNomineeType generated by hbm2java
 */
@Unique(fields={"nomineeType"},id="id",tableName="EGEIS_RELATION_TYPE",columnName={"RELATION_TYPE"},message="Relation Type is unique")
public class EisRelationType implements java.io.Serializable
{

	private Long id;
	@Required(message="Relation Type should not be empty")
	private String nomineeType;

	private boolean fullBenefitEligible;

	private String gender;

	private Long eligibleAge;
	
	private String eligStatusIfMarried;
	
	private String eligStatusIfEmployed;
	
	private String narration;
	
	public EisRelationType() {}
	public String getEligStatusIfMarried() {
		return eligStatusIfMarried;
	}
	public void setEligStatusIfMarried(String eligStatusIfMarried) {
		this.eligStatusIfMarried = eligStatusIfMarried;
	}
	public String getEligStatusIfEmployed() {
		return eligStatusIfEmployed;
	}
	public void setEligStatusIfEmployed(String eligStatusIfEmployed) {
		this.eligStatusIfEmployed = eligStatusIfEmployed;
	}
	
	public EisRelationType(boolean fullBenefitElegible, String gender)
	{
		this.fullBenefitEligible = fullBenefitElegible;
		this.gender = gender;
	}

	

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public String getNomineeType()
	{
		return this.nomineeType;
	}

	public void setNomineeType(String nomineeType)
	{
		this.nomineeType = nomineeType;
	}

	public boolean isFullBenefitEligible()
	{
		return this.fullBenefitEligible;
	}

	public void setFullBenefitEligible(boolean fullBenefitElegible)
	{
		this.fullBenefitEligible = fullBenefitElegible;
	}

	public String getGender()
	{
		return this.gender;
	}

	public void setGender(String gender)
	{
		this.gender = gender;
	}

	public Long getEligibleAge() {
		return eligibleAge;
	}
	public void setEligibleAge(Long eligibleAge) {
		this.eligibleAge = eligibleAge;
	}
	public String getNarration() {
		return narration;
	}
	public void setNarration(String narration) {
		this.narration = narration;
	}
	
}
