insert into eg_action (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'AjaxFindDesignationsByDepartment','/ajaxWorkFlow-findDesignationsByObjectType',null,(select id from eg_module where name='EIS-COMMON'),1,'Find Designations by Department',false,'eis',0,(select id from eg_user where username = 'egovernments'),now(),(select id from eg_user where username = 'egovernments'),now(),(select id from eg_module where name = 'EIS'));
insert into eg_roleaction(roleid,actionid) select r.id, (select id from eg_action where name='AjaxFindDesignationsByDepartment') from eg_roleaction ra, eg_action a, eg_role r  where ra.actionid = a.id and ra.roleid = r.id and a.url = '/ajaxWorkFlow-getDesignationsByObjectType';

insert into eg_action (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'FindDesignationsForActiveAssignmentsByDepartment','/ajaxWorkFlow-findDesignationsForActiveAssignmentsByObjectType',null,(select id from eg_module where name='EIS-COMMON'),1,'Find Designations by Department',false,'eis',0,(select id from eg_user where username = 'egovernments'),now(),(select id from eg_user where username = 'egovernments'),now(),(select id from eg_module where name = 'EIS'));
insert into eg_roleaction(roleid,actionid) select r.id, (select id from eg_action where name='FindDesignationsForActiveAssignmentsByDepartment') from eg_roleaction ra, eg_action a, eg_role r  where ra.actionid = a.id and ra.roleid = r.id and a.url = '/ajaxWorkFlow-getDesignationsForActiveAssignmentsByObjectType';

insert into eg_action (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'FindDesignationsByDepartmentWithDesignation',
'/ajaxWorkFlow-findDesignationsByObjectTypeAndDesignation',null,(select id from eg_module where name='EIS-COMMON'),1,'FindDesignationsByDepartmentWithDesignation',false,'eis',0,(select id from eg_user where username = 'egovernments'),now(),(select id from eg_user where username = 'egovernments'),now(),(select id from eg_module where name='EIS'));
insert into eg_roleaction(roleid,actionid) select r.id, (select id from eg_action where name='FindDesignationsByDepartmentWithDesignation') from eg_roleaction ra, eg_action a, eg_role r  where ra.actionid = a.id and ra.roleid = r.id and a.url = '/ajaxWorkFlow-getDesignationsByObjectTypeAndDesignation';

insert into eg_action (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'FindDesignationsByDepartmentWithDesignationAndDate',
'/ajaxWorkFlow-findDesignationsByObjectTypeAndDesignationAndDate',null,(select id from eg_module where name='EIS-COMMON'),1,'FindDesignationsByDepartmentWithDesignationAndDate',false,'eis',0,(select id from eg_user where username = 'egovernments'),now(),(select id from eg_user where username = 'egovernments'),now(),(select id from eg_module where name='EIS'));
insert into eg_roleaction(roleid,actionid) select r.id, (select id from eg_action where name='FindDesignationsByDepartmentWithDesignationAndDate') from eg_roleaction ra, eg_action a, eg_role r  where ra.actionid = a.id and ra.roleid = r.id and a.url = '/ajaxWorkFlow-getDesignationsByObjectTypeAndDesignationAndDate';
