Insert into chartofaccounts
   (ID, GLCODE, NAME, ISACTIVEFORPOSTING, PARENTID, ISACTIVE, LASTMODIFIED, MODIFIEDBY, CREATED, GROUPID, OPERATION, TYPE, CLASSIFICATION, SCHEDULEID, PAYMENTSCHEDULEID, PAYMENTOPERATION)
 Values
   (seq_chartofaccounts.nextval, '1100200', 'Water Tax', 1, 50, 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, null, 'I', 4,null, null, null);


Insert into chartofaccounts
   (ID, GLCODE, NAME, ISACTIVEFORPOSTING, PARENTID, ISACTIVE, LASTMODIFIED, MODIFIEDBY, CREATED, GROUPID, OPERATION, TYPE, CLASSIFICATION, SCHEDULEID, PAYMENTSCHEDULEID, PAYMENTOPERATION)
 Values
   (seq_chartofaccounts.nextval, '1100300', 'Sewarage Tax', 1, 51, 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, null, 'I', 4,null, null, null);
   
   

Insert into chartofaccounts
   (ID, GLCODE, NAME, ISACTIVEFORPOSTING, PARENTID, ISACTIVE, LASTMODIFIED, MODIFIEDBY, CREATED, GROUPID, OPERATION, TYPE, CLASSIFICATION, SCHEDULEID, PAYMENTSCHEDULEID, PAYMENTOPERATION)
 Values
   (seq_chartofaccounts.nextval, '1100400', 'Conservancy Tax', 1, 52, 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, null, 'I', 4,null, null, null);
   
   
   Insert into chartofaccounts
      (ID, GLCODE, NAME, ISACTIVEFORPOSTING, PARENTID, ISACTIVE, LASTMODIFIED, MODIFIEDBY, CREATED, GROUPID, OPERATION, TYPE, CLASSIFICATION, SCHEDULEID, PAYMENTSCHEDULEID, PAYMENTOPERATION)
    Values
      (seq_chartofaccounts.nextval, '1100500', 'Lighting Tax', 1, 53, 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, null, 'I', 4,null, null, null);


Insert into chartofaccounts
   (ID, GLCODE, NAME, ISACTIVEFORPOSTING, PARENTID, ISACTIVE, LASTMODIFIED, MODIFIEDBY, CREATED, GROUPID, OPERATION, TYPE, CLASSIFICATION, SCHEDULEID, PAYMENTSCHEDULEID, PAYMENTOPERATION)
 Values
   (seq_chartofaccounts.nextval, '1100600', 'Education Tax', 1, 54, 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, null, 'I', 4,null, null, null);



Insert into chartofaccounts
   (ID, GLCODE, NAME, ISACTIVEFORPOSTING, PARENTID, ISACTIVE, LASTMODIFIED, MODIFIEDBY, CREATED, GROUPID, OPERATION, TYPE, CLASSIFICATION, SCHEDULEID, PAYMENTSCHEDULEID, PAYMENTOPERATION)
 Values
   (seq_chartofaccounts.nextval, '11010', 'Trade and Proffessional Tax', 1, 5, 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, null, 'I', 2,null, null, null);


   
   Insert into chartofaccounts
      (ID, GLCODE, NAME, ISACTIVEFORPOSTING, PARENTID, ISACTIVE, LASTMODIFIED, MODIFIEDBY, CREATED, GROUPID, OPERATION, TYPE, CLASSIFICATION, SCHEDULEID, PAYMENTSCHEDULEID, PAYMENTOPERATION)
    Values
      (seq_chartofaccounts.nextval, '1101000', 'Trade and Proffessional Tax', 1, seq_chartofaccounts.nextval-1, 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, null, 'I', 4,null, null, null);
   

Insert into chartofaccounts
   (ID, GLCODE, NAME, ISACTIVEFORPOSTING, PARENTID, ISACTIVE, LASTMODIFIED, MODIFIEDBY, CREATED, GROUPID, OPERATION, TYPE, CLASSIFICATION, SCHEDULEID, PAYMENTSCHEDULEID, PAYMENTOPERATION)
 Values
   (seq_chartofaccounts.nextval, '1108000', 'Other Taxes', 1, 61, 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, TO_DATE('02/13/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, null, 'I', 4,null, null, null);
   
   


