package org.egov.payroll.model;

import org.egov.commons.CChartOfAccounts;
import org.egov.infstr.models.BaseModel;
import org.egov.infstr.models.validator.Unique;
import org.egov.infstr.workflow.Action;

/**
 * nomination header generated by hbm2java
 */

@Unique(fields={"code"},id="id",tableName="EGPAY_NOMINATION_HEADER",columnName={"CODE"},message="Nomination.Code.isunique")
public class NominationHeader extends BaseModel {
	
	private String code;
	
	private String description;
	
	private SalaryCodes salaryCodes;

	private CChartOfAccounts coa;
	
	private Action ruleScript;

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public SalaryCodes getSalaryCodes() {
		return salaryCodes;
	}

	public void setSalaryCodes(SalaryCodes salaryCodes) {
		this.salaryCodes = salaryCodes;
	}

	public CChartOfAccounts getCoa() {
		return coa;
	}

	public void setCoa(CChartOfAccounts coa) {
		this.coa = coa;
	}

	public Action getRuleScript() {
		return ruleScript;
	}

	public void setRuleScript(Action ruleScript) {
		this.ruleScript = ruleScript;
	}
	
}
