package org.egov.payroll.model;

// Generated Aug 28, 2007 7:45:39 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Comparator;

/**
 * PayScaleDetails generated by hbm2java
 */
public class PayScaleDetails implements java.io.Serializable {

	private Integer id;

	private PayScaleHeader payHeader;

	private SalaryCodes salaryCodes;

	private BigDecimal pct;

	private BigDecimal amount;

	public PayScaleDetails() {
	}

	public PayScaleDetails(Integer id, PayScaleHeader payHeader,
			SalaryCodes salaryCodes, BigDecimal pct, BigDecimal amount) {
		this.id = id;
		this.payHeader = payHeader;
		this.salaryCodes = salaryCodes;
		this.pct = pct;
		this.amount = amount;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PayScaleHeader getPayHeader() {
		return this.payHeader;
	}

	public void setPayHeader(PayScaleHeader payHeader) {
		this.payHeader = payHeader;
	}

	public SalaryCodes getSalaryCodes() {
		return this.salaryCodes;
	}

	public void setSalaryCodes(SalaryCodes salaryCodes) {
		this.salaryCodes = salaryCodes;
	}

	public BigDecimal getPct() {
		return this.pct;
	}

	public void setPct(BigDecimal pct) {
		this.pct = pct;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	public static Comparator SalarycodeOrderIdComparator = new Comparator() {
	    public int compare(Object payScaleDetails, Object anotherPayScaleDetails) {	    	
	    	Integer	order1 = ((PayScaleDetails) payScaleDetails).getSalaryCodes().getOrderId().intValue();	
	    	Integer	order2 = ((PayScaleDetails) anotherPayScaleDetails).getSalaryCodes().getOrderId().intValue();	      
	    	return order1.compareTo(order2);	      
	    }
	 };

}
