package org.egov.payroll.model;

// Generated Aug 31, 2007 11:23:00 AM by Hibernate Tools 3.2.0.b9


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EgpayCategoryMaster generated by hbm2java
 */
public class SalaryCategoryMaster implements java.io.Serializable {

	private Integer id;

	private String name;

	private String description;

	private String catType;

	private long createdby;

	private Date createdtimestamp;

	private Set salaryCodeses = new HashSet(0);

	public SalaryCategoryMaster() {
	}

	public SalaryCategoryMaster(Integer id, String name, String catType,
			long createdby, Date createdtimestamp) {
		this.id = id;
		this.name = name;
		this.catType = catType;
		this.createdby = createdby;
		this.createdtimestamp = createdtimestamp;
	}

	public SalaryCategoryMaster(Integer id, String name, String description,
			String catType, long createdby, Date createdtimestamp,
			Set salaryCodeses) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.catType = catType;
		this.createdby = createdby;
		this.createdtimestamp = createdtimestamp;
		this.salaryCodeses = salaryCodeses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCatType() {
		return this.catType;
	}

	public void setCatType(String catType) {
		this.catType = catType;
	}

	public long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(long createdby) {
		this.createdby = createdby;
	}

	public Date getCreatedtimestamp() {
		return this.createdtimestamp;
	}

	public void setCreatedtimestamp(Date createdtimestamp) {
		this.createdtimestamp = createdtimestamp;
	}

	public Set getSalaryCodeses() {
		return this.salaryCodeses;
	}

	public void setSalaryCodeses(Set salaryCodeses) {
		this.salaryCodeses = salaryCodeses;
	}

}
