package org.egov.payroll.model;

import org.egov.model.advance.EgAdvanceRequisition;

/**
 * EgpaySaladvances generated by hbm2java
 */
public class SalaryARF extends EgAdvanceRequisition implements java.io.Serializable {

	private Advance advance;

	public Advance getAdvance() {
		return advance;
	}

	public void setAdvance(Advance advance) {
		this.advance = advance;
	}
	
	@Override
	public String getStateDetails() {
		return advance.getSalaryCodes().getDescription()+" : "+advance.getEmployee().getEmployeeCode()+"-"+this.advance.getEmployee().getEmployeeName()+"-"+this.advance.getAdvanceAmt();
	}

}
