ALTER TABLE EG_EMPLOYEE DROP COLUMN BANK; 
ALTER TABLE EG_EMPLOYEE DROP COLUMN SB_ACCOUNT_NUMBER; 
COMMIT;

ALTER TABLE EG_EMPLOYEE
  ADD CREATEDTIME DATE;
  
  ALTER TABLE EG_EMPLOYEE
  ADD CREATED_BY NUMBER(12);
  COMMIT;


  ALTER TABLE EGEIS_LEAVE_APPLICATION
  ADD IS_LEAVE_ENCASHMENT NUMBER(1)
  
  /***********insert into leave_status table Encashed status***********\
  
  insert into egeis_leave_status values('Encashed',4)
