delete from eg_wf_matrix where objecttype  = 'AbstractEstimate';

--0 to 200000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Technical Sanction', 'Deputy Executive Engineer', 'Created', 'Save,Forward', 0, 200000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Created', NULL, 'Pending Technical Sanction', 'Deputy Executive Engineer', NULL, 'Technical Sanctioned', 'END', 'NULL', 'NULL', 'Approve,Reject', 0, 200000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Rejected', NULL, 'Pending Technical Sanction', 'Assistant Engineer', NULL, 'Resubmitted', 'Pending Technical Sanction', 'Deputy Executive Engineer', NULL, 'Forward,Cancel', 0, 200000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Resubmitted', NULL, 'Pending Technical Sanction', 'Deputy Executive Engineer', NULL, 'Technical Sanctioned', 'END', 'NULL', 'NULL', 'Approve,Reject', 0, 200000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'NEW', NULL, 'Pending Submission', 'Assistant Engineer', NULL, 'Created', 'Pending Technical Sanction', 'Deputy Executive Engineer', 'Created', 'Save,Forward,Cancel', 0, 200000, now(), now());

--200000 to 1000000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Save,Forward', 200000.1, 1000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Technical Sanction', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 200000.1, 1000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Checked', NULL, 'Pending Technical Sanction', 'Executive Engineer', NULL, 'Technical Sanctioned', 'END', 'NULL', 'NULL', 'Approve,Reject', 200000.1, 1000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'NEW', NULL, 'Pending Submission', 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Save,Forward,Cancel', 200000.1, 1000000, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Rejected', NULL, NULL, 'Assistant Engineer', NULL, 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Forward,Cancel', 200000.1, 1000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Technical Sanction', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 200000.1, 1000000, now(), now());

--1000000 to 5000000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Save,Forward', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Checked', NULL, 'Pending Check By Executive Engineer', 'Executive Engineer', NULL, 'Checked', 'Pending Technical Sanction', 'Superintending Engineer', 'Pending Technical Sanction', 'Submit,Reject', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Checked', NULL, 'Pending Technical Sanction', 'Superintending Engineer', NULL, 'Technical Sanctioned', 'END', 'NULL', 'NULL', 'Approve,Reject', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'NEW', NULL, 'Pending Submission', 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Save,Forward,Cancel', 1000000.1, 5000000, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Rejected', NULL, NULL, 'Assistant Engineer', NULL, 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Forward,Cancel', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 1000000.1, 5000000, now(), now());

-- >5000000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Save,Forward', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Checked', NULL, 'Pending Check By Executive Engineer', 'Executive Engineer', NULL, 'Checked', 'Pending Check By Superintending Engineer', 'Superintending Engineer', 'Pending Check By Superintending Engineer', 'Submit,Reject', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Checked', NULL, 'Pending Check By Superintending Engineer', 'Superintending Engineer', NULL, 'Checked', 'Pending Technical Sanction', 'Chief Engineer', 'Pending Technical Sanction', 'Submit,Reject', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Checked', NULL, 'Pending Technical Sanction', 'Chief Engineer', NULL, 'Technical Sanctioned', 'END', 'NULL', 'NULL', 'Approve,Reject', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'NEW', NULL, 'Pending Submission', 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Save,Forward,Cancel', 5000000.1, NULL, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Rejected', NULL, NULL, 'Assistant Engineer', NULL, 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Forward,Cancel', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 5000000.1, NULL, now(), now());


--rollback INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Technical Sanction', 'Superintending Engineer', 'Created', 'Save,Forward', NULL, NULL, now(), now());
--rollback INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Created', NULL, NULL, 'Superintending Engineer', NULL, 'Technical Sanctioned', 'Pending Admin sanction', 'Commissioner', 'Technical Sanctioned', 'Submit,Reject', NULL, NULL, now(), now());
--rollback INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Technical Sanctioned', NULL, NULL, 'Commissioner', NULL, 'Admin Sanctioned', 'END', NULL, NULL, 'Approve,Reject', NULL, NULL, now(), now());
--rollback INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Rejected', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Technical Sanction', 'Superintending Engineer', NULL, 'Forward,Cancel', NULL, NULL, now(), now());
--rollback INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'AbstractEstimate', 'Resubmitted', NULL, NULL, 'Superintending Engineer', NULL, 'Technical Sanctioned', 'Pending Admin sanction', 'Commissioner', 'Technical Sanctioned', 'Submit,Reject', NULL, NULL, now(), now());
--rollback UPDATE EG_WF_MATRIX SET nextstate = 'Resubmitted' where objecttype = 'AbstractEstimate' and currentstate = 'Rejected';

