UPDATE EGW_STATUS SET ORDER_ID = 10 where MODULETYPE = 'AbstractEstimate' and CODE = 'NOTICEINVITINGTENDERRELEASED';
UPDATE EGW_STATUS SET ORDER_ID = 11 where MODULETYPE = 'AbstractEstimate' and CODE = 'TENDER_DOCUMENT_RELEASED';
UPDATE EGW_STATUS SET ORDER_ID = 12 where MODULETYPE = 'AbstractEstimate' and CODE = 'TENDER_OPENED';
UPDATE EGW_STATUS SET ORDER_ID = 13 where MODULETYPE = 'AbstractEstimate' and CODE = 'TECHNICAL_EVALUATION_DONE';
UPDATE EGW_STATUS SET ORDER_ID = 14 where MODULETYPE = 'AbstractEstimate' and CODE = 'COMMERCIAL_EVALUATION_DONE';
UPDATE EGW_STATUS SET ORDER_ID = 15 where MODULETYPE = 'AbstractEstimate' and CODE = 'L1_TENDER_FINALIZED';

UPDATE EGW_STATUS SET CODE = 'APPROVED' , DESCRIPTION='Approved' where MODULETYPE = 'AbstractEstimate' and CODE = 'ADMIN_SANCTIONED';
delete from EGW_STATUS where MODULETYPE = 'AbstractEstimate' and CODE = 'TECH_SANCTIONED';

--rollback delete from EGW_STATUS where MODULETYPE='AbstractEstimate' and CODE='CHECKED';

--rollback UPDATE EGW_STATUS SET ORDER_ID = 9 where MODULETYPE = 'AbstractEstimate' and CODE = 'NOTICEINVITINGTENDERRELEASED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 10 where MODULETYPE = 'AbstractEstimate' and CODE = 'TENDER_DOCUMENT_RELEASED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 11 where MODULETYPE = 'AbstractEstimate' and CODE = 'TENDER_OPENED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 12 where MODULETYPE = 'AbstractEstimate' and CODE = 'TECHNICAL_EVALUATION_DONE';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 13 where MODULETYPE = 'AbstractEstimate' and CODE = 'COMMERCIAL_EVALUATION_DONE';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 14 where MODULETYPE = 'AbstractEstimate' and CODE = 'L1_TENDER_FINALIZED';

--rollback UPDATE EGW_STATUS SET CODE = 'ADMIN_SANCTIONED' and DESCRIPTION='ADMIN_SANCTIONED' where MODULETYPE = 'AbstractEstimate' and CODE = 'APPROVED';
--rollback Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (NEXTVAL('SEQ_EGW_STATUS'),'AbstractEstimate','Technical Sanctioned',now(),'TECH_SANCTIONED',2);