ALTER TABLE EGW_CONTRACTOR_MB_DETAILS ALTER COLUMN WO_ACTIVITY_ID DROP NOT NULL;
ALTER TABLE EGW_CONTRACTOR_MB_DETAILS ADD COLUMN uom bigint;
ALTER TABLE EGW_CONTRACTOR_MB_DETAILS ADD CONSTRAINT FK_CONTRACTOR_MB_DETAILS_UOM FOREIGN KEY (uom) REFERENCES eg_uom (id);
ALTER TABLE EGW_CONTRACTOR_MB_DETAILS ADD COLUMN description character varying(1024);

ALTER TABLE EGW_CONTRACTOR_MB_MEASUREMENTSHEET ALTER COLUMN WOMSHEETID DROP NOT NULL;
ALTER TABLE EGW_CONTRACTOR_MB_MEASUREMENTSHEET ADD COLUMN identifier character(1);

--rollback ALTER TABLE EGW_CONTRACTOR_MB_MEASUREMENTSHEET DROP COLUMN identifier;

--rollback ALTER TABLE EGW_CONTRACTOR_MB_DETAILS DROP COLUMN description;
--rollback ALTER TABLE EGW_CONTRACTOR_MB_DETAILS DROP COLUMN uom;
