
ALTER TABLE EGW_ESTIMATE_ASSETS ADD COLUMN version bigint DEFAULT 0;
ALTER TABLE EGW_ESTIMATE_ASSETS DROP COLUMN estimate_asset_index;

ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN ABSTRACTESTIMATE_ID TO ABSTRACTESTIMATE;
ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN ASSET_ID TO ASSET;

ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN CREATED_BY TO CREATEDBY;
ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN CREATED_DATE TO CREATEDDATE;
ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN modified_by TO lastmodifiedby;
ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN modified_date TO lastmodifieddate;


--rollback ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN lastmodifieddate TO modifieddate;
--rollback ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN lastmodifiedby TO modifiedby;
--rollback ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN CREATEDDATE TO CREATED_DATE;
--rollback ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN CREATEDBY TO CREATED_BY;

--rollback ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN ASSET TO ASSET_ID;
--rollback ALTER TABLE EGW_ESTIMATE_ASSETS RENAME COLUMN ABSTRACTESTIMATE TO ABSTRACTESTIMATE_ID;
--rollback ALTER TABLE EGW_ESTIMATE_ASSETS ADD COLUMN estimate_asset_index bigint;
--rollback ALTER TABLE EGW_ESTIMATE_ASSETS DROP COLUMN version;