------------------START------------------
ALTER TABLE EGW_WORKORDER DROP COLUMN PREPAREDBY;
ALTER TABLE EGW_WORKORDER DROP COLUMN engineer_incharge2;
ALTER TABLE EGW_WORKORDER RENAME COLUMN engineer_incharge1 TO engineerincharge;
ALTER TABLE EGW_WORKORDER DROP COLUMN document_number;

ALTER TABLE EGW_WORKORDER ADD COLUMN TENDERFINALIZEDPERCENTAGE double precision; 
ALTER TABLE EGW_WORKORDER ADD COLUMN BANKGUARANTEE character varying(1024);
ALTER TABLE EGW_WORKORDER ADD COLUMN FILENUMBER character varying(100); 
ALTER TABLE EGW_WORKORDER ADD COLUMN FILEDATE timestamp without time zone; 
ALTER TABLE EGW_WORKORDER ADD COLUMN ESTIMATENUMBER character varying(100); 
-------------------END-------------------

--rollback ALTER TABLE EGW_WORKORDER DROP COLUMN ESTIMATENUMBER;
--rollback ALTER TABLE EGW_WORKORDER DROP COLUMN FILEDATE;
--rollback ALTER TABLE EGW_WORKORDER DROP COLUMN FILENUMBER;
--rollback ALTER TABLE EGW_WORKORDER DROP COLUMN BANKGUARANTEE;
--rollback ALTER TABLE EGW_WORKORDER DROP COLUMN TENDERFINALIZEDPERCENTAGE;

--rollback ALTER TABLE EGW_WORKORDER ADD COLUMN document_number bigint; 

--rollback ALTER TABLE EGW_WORKORDER RENAME COLUMN engineerincharge TO engineer_incharge1;

--rollback ALTER TABLE EGW_WORKORDER ADD COLUMN engineer_incharge2 bigint; 
--rollback ALTER TABLE EGW_WORKORDER ADD CONSTRAINT fk_wo_eng_incharge2 FOREIGN KEY (engineer_incharge2) REFERENCES egeis_employee (id);
--rollback CREATE INDEX idx_wo_engineer_incharge2 ON EGW_WORKORDER USING btree (engineer_incharge2);

--rollback ALTER TABLE EGW_WORKORDER ADD COLUMN preparedby bigint NOT NULL;
--rollback ALTER TABLE EGW_WORKORDER ADD CONSTRAINT fk_wo_preparedby FOREIGN KEY (preparedby) REFERENCES egeis_employee (id);
--rollback CREATE INDEX idx_wo_preparedby ON EGW_WORKORDER USING btree (preparedby);