DROP SEQUENCE SEQ_ACCOUNTDETAILTYPE;
CREATE SEQUENCE SEQ_ACCOUNTDETAILTYPE START WITH 5;

Insert into ACCOUNTDETAILTYPE (ID,NAME,DESCRIPTION,TABLENAME,COLUMNNAME,ATTRIBUTENAME,NBROFLEVELS,ISACTIVE,CREATED,LASTMODIFIED,MODIFIEDBY,FULL_QUALIFIED_NAME) values (nextval('SEQ_ACCOUNTDETAILTYPE'),'PROJECTCODE','PROJECTCODE','egw_projectcode','id','projectcode_id',1,1,now(),null,null,'org.egov.works.models.estimate.ProjectCode');

--rollback delete from ACCOUNTDETAILTYPE where NAME='PROJECTCODE';