------------------------ Create Table egw_mv_work_progress_register --------------------
CREATE TABLE egw_mv_work_progress_register
(
  id bigint,
  ward bigint,
  location bigint,
  workcategory character varying(100),
  typeofslum character varying(100),
  beneficiary character varying(100),
  nameofwork character varying(1024),
  wincode character varying(256),
  fund bigint,
  function bigint,
  budgethead bigint,
  typeofwork bigint,
  subtypeofwork bigint,
  adminsanctionby bigint,
  adminsanctiondate timestamp without time zone,
  adminsanctionamount double precision,
  technicalsanctionby bigint,
  technicalsanctiondate timestamp without time zone,
  estimateamount double precision,
  modeofallotment character varying(100),
  agreementnumber character varying(256),
  agreementdate timestamp without time zone,
  contractor bigint,
  agreementamount double precision,
  latestmbnumber character varying(50),
  latestmbdate timestamp without time zone,
  latestbillnumber character varying(50),
  latestbilldate timestamp without time zone,
  billtype character varying(50),
  billamount double precision,
  totalbillpaidsofar double precision,
  balancevalueofworktobill double precision,
  spilloverflag boolean,
  department bigint,
  createdby bigint NOT NULL,
  createddate timestamp without time zone,
  lastmodifiedby bigint,
  lastmodifieddate timestamp without time zone,
  version bigint DEFAULT 0
);
create sequence seq_egw_mv_work_progress_register;
