------------------START------------------
DROP TABLE EGW_ESTIMATE_APPROPRIATION;
DROP SEQUENCE SEQ_EGW_ESTIMATE_APPROPRIATION;
ALTER TABLE EGW_LINEESTIMATE_APPROPRIATION RENAME TO EGW_ESTIMATE_APPROPRIATION;
ALTER SEQUENCE SEQ_EGW_LINEESTIMATE_APPROPRIATION RENAME TO SEQ_EGW_ESTIMATE_APPROPRIATION;

ALTER TABLE EGW_ESTIMATE_APPROPRIATION ALTER COLUMN lineestimatedetails DROP NOT NULL;
ALTER TABLE EGW_ESTIMATE_APPROPRIATION ADD COLUMN abstractestimate bigint;
ALTER TABLE EGW_ESTIMATE_APPROPRIATION ADD CONSTRAINT fk_estimate_appropriation_abstractestimate FOREIGN KEY (abstractestimate)
      REFERENCES egw_abstractestimate (id);

-----------------END------------------------------
--rollback ALTER TABLE EGW_ESTIMATE_APPROPRIATION DROP COLUMN abstractestimate bigint;
--rollback ALTER TABLE EGW_ESTIMATE_APPROPRIATION RENAME TO EGW_LINEESTIMATE_APPROPRIATION;