------------------START------------------
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN CANCELLATIONREASON varchar(50);
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN CANCELLATIONREMARKS varchar(126);
-------------------END-------------------
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN CANCELLATIONREMARKS;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN CANCELLATIONREASON; 
