--0 to 200000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Save,Forward', 0, 200000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Junior Accountant/Senior Accountant/Accounts Officer', 'Junior Accountant,Senior Accountant,Accounts Officer', 'Pending Check By Junior Accountant/Senior Accountant/Accounts Officer', 'Submit,Reject', 0, 200000, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Rejected', NULL, NULL,'Assistant engineer', null, 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', null, 'Forward,Cancel', 0, 200000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Junior Accountant/Senior Accountant/Accounts Officer', 'Junior Accountant,Senior Accountant,Accounts Officer', 'Pending Check By Junior Accountant/Senior Accountant/Accounts Officer', 'Submit,Reject', 0, 200000, now(), now());

--200000 to 1000000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Save,Forward', 200000.1, 1000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 200000.1, 1000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Checked', NULL, 'Pending Check By Executive Engineer', 'Executive Engineer', NULL, 'Checked', 'Pending Check By Junior Accountant/Senior Accountant/Accounts Officer', 'Junior Accountant,Senior Accountant,Accounts Officer', 'Pending Check By Junior Accountant/Senior Accountant/Accounts Officer', 'Submit,Reject', 200000.1, 1000000, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Rejected', NULL, NULL,'Assistant engineer', null, 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', null, 'Forward,Cancel', 200000.1, 1000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Checked', 'Submit,Reject', 200000.1, 1000000, now(), now());

--1000000 to 5000000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Save,Forward', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Checked', NULL, 'Pending Check By Executive Engineer', 'Executive Engineer', NULL, 'Checked', 'Pending Check By Superintending Engineer', 'Superintending Engineer', 'Pending Check By Superintending Engineer', 'Submit,Reject', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Checked', NULL, 'Pending Check By Superintending Engineer', 'Superintending Engineer', NULL, 'Checked', 'Pending Check By Junior Accountant/Senior Accountant/Accounts Officer', 'Junior Accountant,Senior Accountant,Accounts Officer', 'Pending Check By Junior Accountant/Senior Accountant/Accounts Officer', 'Submit,Reject', 1000000.1, 5000000, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Rejected', NULL, NULL,'Assistant engineer', null, 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', null, 'Forward,Cancel', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Checked', 'Submit,Reject', 1000000.1, 5000000, now(), now());

-- >5000000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Save,Forward', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Checked', NULL, 'Pending Check By Executive Engineer', 'Executive Engineer', NULL, 'Checked', 'Pending Check By Superintending Engineer', 'Superintending Engineer', 'Pending Check By Superintending Engineer', 'Submit,Reject', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Checked', NULL, 'Pending Check By Superintending Engineer', 'Superintending Engineer', NULL, 'Checked', 'Pending Check By Chief Engineer', 'Chief Engineer', 'Pending Check By Chief Engineer', 'Submit,Reject', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Checked', NULL, 'Pending Check By Chief Engineer', 'Chief Engineer', NULL, 'Checked', 'Pending Check By Junior Accountant/Senior Accountant/Accounts Officer', 'Junior Accountant,Senior Accountant,Accounts Officer', 'Pending Check By Junior Accountant/Senior Accountant/Accounts Officer', 'Submit,Reject', 5000000.1, NULL, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Rejected', NULL, NULL,'Assistant engineer', null, 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', null, 'Forward,Cancel', 5000000.1, null, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Checked', 'Submit,Reject', 5000000.1, null, now(), now());

--common financial approval
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Checked', NULL, 'Pending Check By Junior Accountant/Senior Accountant/Accounts Officer', 'Junior Accountant,Senior Accountant,Accounts Officer', NULL, 'Checked','Pending Check By Examiner Of Accounts', 'Examiner Of Accounts', 'Pending Check By Examiner Of Accounts', 'Submit,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Checked', NULL, 'Pending Check By Examiner Of Accounts','Examiner Of Accounts', null, 'Checked', 'Pending Approval', 'Commissioner', 'Pending Approval', 'Submit,Reject', 0, null, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'ContractorAdvanceRequisition', 'Checked', NULL, 'Pending Approval', 'Commissioner', NULL, 'Approved', 'END', 'NULL', 'NULL', 'Approve,Reject', 0, NULL, now(), now());

------ START : Application types for workflow ---
INSERT INTO EG_WF_TYPES (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, enabled, grouped, typefqn, displayname, version) VALUES (nextval('seq_eg_wf_types'), (select id from eg_module where name = 'Works Management'), 'ContractorAdvanceRequisition', '/egworks/contractoradvance/update/:ID', 1, now(), 1, now(), TRUE, FALSE, 'org.egov.works.ContractorAdvanceRequisition.entity.ContractorAdvanceRequisitionRequisition', 'Contractor Advance Requisition', 0);
------ END : Application types for workflow ---

--rollback delete from EG_WF_TYPES where type = 'ContractorAdvanceRequisition' and link = '/egworks/contractoradvance/update/:ID';
--rollback delete from EG_WF_MATRIX where objecttype = 'ContractorAdvanceRequisition';