------------------START------------------
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN BENEFICIARY character varying(100);
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN LOCALITY BIGINT;
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN MODEOFALLOTMENT character varying(100);
ALTER TABLE EGW_ABSTRACTESTIMATE ADD CONSTRAINT fk_abstractestimate_locality FOREIGN KEY (locality)
      REFERENCES eg_boundary (id);
-------------------END-------------------
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN MODEOFALLOTMENT;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN LOCALITY;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN BENEFICIARY;
