ALTER TABLE EGW_CONTRACTOR_ADVANCE ADD COLUMN approveddate timestamp without time zone;
ALTER TABLE EGW_CONTRACTOR_ADVANCE ADD COLUMN approvedby bigint;
ALTER TABLE EGW_CONTRACTOR_ADVANCE ALTER COLUMN drawing_officer DROP NOT NULL;

--rollback ALTER TABLE EGW_CONTRACTOR_ADVANCE ALTER COLUMN drawing_officer SET NOT NULL;
--rollback ALTER TABLE EGW_CONTRACTOR_ADVANCE DROP COLUMN approveddate;
--rollback ALTER TABLE EGW_CONTRACTOR_ADVANCE DROP COLUMN approvedby;