
UPDATE EGW_STATUS SET ORDER_ID = 3 where MODULETYPE = 'WorkOrder' and CODE = 'REJECTED';
UPDATE EGW_STATUS SET ORDER_ID = 4 where MODULETYPE = 'WorkOrder' and CODE = 'APPROVED';
UPDATE EGW_STATUS SET ORDER_ID = 5 where MODULETYPE = 'WorkOrder' and CODE = 'DEPOSIT_CODE_APPR_DONE';
UPDATE EGW_STATUS SET ORDER_ID = 6 where MODULETYPE = 'WorkOrder' and CODE = 'CANCELLED';
UPDATE EGW_STATUS SET ORDER_ID = 7 where MODULETYPE = 'WorkOrder' and CODE = 'ACCEPTANCE_LETTER_ISSUED';
UPDATE EGW_STATUS SET ORDER_ID = 8 where MODULETYPE = 'WorkOrder' and CODE = 'ACCEPTANCE_LETTER_ACKNOWLEDGED';
UPDATE EGW_STATUS SET ORDER_ID = 9 where MODULETYPE = 'WorkOrder' and CODE = 'RESUBMITTED';
UPDATE EGW_STATUS SET ORDER_ID = 7 where MODULETYPE = 'WorkOrder' and CODE = 'AGREEMENT_ORDER_SIGNED';
UPDATE EGW_STATUS SET ORDER_ID = 8 where MODULETYPE = 'WorkOrder' and CODE = 'WORK_ORDER_ACKNOWLEDGED';
UPDATE EGW_STATUS SET ORDER_ID = 9 where MODULETYPE = 'WorkOrder' and CODE = 'SITE_HANDED_OVER';
UPDATE EGW_STATUS SET ORDER_ID = 9 where MODULETYPE = 'WorkOrder' and CODE = 'WORK_COMMENCED';
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (NEXTVAL('SEQ_EGW_STATUS'),'WorkOrder','Checked',now(),'CHECKED',2);

--rollback delete from EGW_STATUS where MODULETYPE='WorkOrder' and CODE='CHECKED';

--rollback UPDATE EGW_STATUS SET ORDER_ID = 2 where MODULETYPE = 'WorkOrder' and CODE = 'REJECTED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 3 where MODULETYPE = 'WorkOrder' and CODE = 'APPROVED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 4 where MODULETYPE = 'WorkOrder' and CODE = 'DEPOSIT_CODE_APPR_DONE';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 5 where MODULETYPE = 'WorkOrder' and CODE = 'CANCELLED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 6 where MODULETYPE = 'WorkOrder' and CODE = 'ACCEPTANCE_LETTER_ISSUED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 7 where MODULETYPE = 'WorkOrder' and CODE = 'ACCEPTANCE_LETTER_ACKNOWLEDGED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 8 where MODULETYPE = 'WorkOrder' and CODE = 'RESUBMITTED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 9 where MODULETYPE = 'WorkOrder' and CODE = 'AGREEMENT_ORDER_SIGNED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 10 where MODULETYPE = 'WorkOrder' and CODE = 'WORK_ORDER_ACKNOWLEDGED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 11 where MODULETYPE = 'WorkOrder' and CODE = 'SITE_HANDED_OVER';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 12 where MODULETYPE = 'WorkOrder' and CODE = 'WORK_COMMENCED';