-----------------Role action mappings to search work id numbers----------------------
Insert into eg_action (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values(nextval('SEQ_EG_ACTION'),'Ajax Search Work Identification Numbers For Loa','/lineestimate/workIdNumbersForLoa',null,(select id from eg_module where name='WorksLineEstimate'),1,'Ajax Search Work Identification Numbers For Loa','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Ajax Search Work Identification Numbers For Loa'));
Insert into eg_roleaction values((select id from eg_role where name='Works Creator'),(select id from eg_action where name='Ajax Search Work Identification Numbers For Loa'));
Insert into eg_roleaction values((select id from eg_role where name='Works Approver'),(select id from eg_action where name='Ajax Search Work Identification Numbers For Loa'));

--rollback delete from EG_ROLEACTION where roleid = (select id from eg_role where name = 'Works Approver') and actionid = (select id from eg_action where name ='Ajax Search Work Identification Numbers For Loa' and contextroot = 'egworks');
--rollback delete from EG_ROLEACTION where roleid = (select id from eg_role where name = 'Works Creator') and actionid = (select id from eg_action where name ='Ajax Search Work Identification Numbers For Loa' and contextroot = 'egworks');
--rollback delete from EG_ROLEACTION where roleid = (select id from eg_role where name = 'Super User') and actionid = (select id from eg_action where name ='Ajax Search Work Identification Numbers For Loa' and contextroot = 'egworks');
--rollback delete from EG_ACTION where name = 'Ajax Search Work Identification Numbers For Loa' and contextroot = 'egworks';