UPDATE EGW_STATUS SET ORDER_ID = 10 where MODULETYPE = 'WorkOrder' and CODE = 'AGREEMENT_ORDER_SIGNED';
UPDATE EGW_STATUS SET ORDER_ID = 11 where MODULETYPE = 'WorkOrder' and CODE = 'WORK_ORDER_ACKNOWLEDGED';
UPDATE EGW_STATUS SET ORDER_ID = 12 where MODULETYPE = 'WorkOrder' and CODE = 'SITE_HANDED_OVER';
UPDATE EGW_STATUS SET ORDER_ID = 13 where MODULETYPE = 'WorkOrder' and CODE = 'WORK_COMMENCED';

--rollback UPDATE EGW_STATUS SET ORDER_ID = 9 where MODULETYPE = 'WorkOrder' and CODE = 'AGREEMENT_ORDER_SIGNED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 10 where MODULETYPE = 'WorkOrder' and CODE = 'WORK_ORDER_ACKNOWLEDGED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 11 where MODULETYPE = 'WorkOrder' and CODE = 'SITE_HANDED_OVER';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 12 where MODULETYPE = 'WorkOrder' and CODE = 'WORK_COMMENCED';