Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksAddEstimateTemplateToEstimate','/estimate/estimateTemplate-search.action','sourcePage=searchForEstimate',(select id from EG_MODULE where name = 'WorksAbstractEstimate'),null,'WorksAddEstimateTemplateToEstimate','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksAddEstimateTemplateToEstimate' and contextroot = 'egworks'));

Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksEstimateTemplateSearchResult','/estimate/estimateTemplate-searchDetails.action',null,(select id from EG_MODULE where name = 'WorksEstimateTemplateMaster'),null,'WorksEstimateTemplateSearchResult','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksEstimateTemplateSearchResult' and contextroot = 'egworks'));

Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksEstimateTemplateSearchAjax','/estimate/ajaxEstimateTemplate-searchAjax.action',null,(select id from EG_MODULE where name = 'WorksAbstractEstimate'),null,'WorksEstimateTemplateSearchAjax','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksEstimateTemplateSearchAjax' and contextroot = 'egworks'));

Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksEstimateTemplateFindCodeAjax','/estimate/ajaxEstimateTemplate-findCodeAjax.action',null,(select id from EG_MODULE where name = 'WorksAbstractEstimate'),null,'WorksEstimateTemplateFindCodeAjax','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksEstimateTemplateFindCodeAjax' and contextroot = 'egworks'));


--rollback delete from eg_roleaction where actionid in (select id from eg_action where name in ('WorksAddEstimateTemplateToEstimate','WorksEstimateTemplateSearchResult','WorksEstimateTemplateSearchAjax','WorksEstimateTemplateFindCodeAjax') and contextroot = 'egworks') and roleid in(select id from eg_role where name = 'Super User');
--rollback delete from eg_action where name in ('WorksAddEstimateTemplateToEstimate','WorksEstimateTemplateSearchResult','WorksEstimateTemplateSearchAjax','WorksEstimateTemplateFindCodeAjax') and contextroot = 'egworks';