------------------START------------------
ALTER TABLE EGW_CONTRACTORBILL ALTER COLUMN CANCELLATIONREMARKS TYPE varchar(256);
-------------------END-------------------
--rollback ALTER TABLE EGW_CONTRACTORBILL DROP COLUMN CANCELLATIONREMARKS;
