
ALTER TABLE EGW_DEPOSITWORKS_USAGE ADD COLUMN version bigint DEFAULT 0;

ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN ABSTRACTESTIMATE_ID TO ABSTRACTESTIMATE;
ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN DEPOSITCODE_ID TO DEPOSITCODE;
ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN COA_ID TO COA;
ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN FINANCIALYEAR_ID TO FINANCIALYEAR;
ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN TOTAL_DEPOSIT_AMOUNT TO TOTALDEPOSITAMOUNT;
ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN CONSUMED_AMT TO CONSUMEDAMOUNT;
ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN RELEASED_AMT TO RELEASEDAMOUNT;
ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN APPROPRIATION_NUMBER TO APPROPRIATIONNUMBER;
ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN APPROPRIATION_DATE TO APPROPRIATIONDATE;

ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN CREATED_BY TO CREATEDBY;
ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN CREATED_DATE TO CREATEDDATE;
ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN modified_by TO lastmodifiedby;
ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN modified_date TO lastmodifieddate;


--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN lastmodifieddate TO modifieddate;
--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN lastmodifiedby TO modifiedby;
--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN CREATEDDATE TO CREATED_DATE;
--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN CREATEDBY TO CREATED_BY;

--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN APPROPRIATIONDATE TO APPROPRIATION_DATE;
--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN APPROPRIATIONNUMBER TO APPROPRIATION_NUMBER;
--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN RELEASEDAMOUNT TO RELEASED_AMT;
--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN CONSUMEDAMOUNT TO CONSUMED_AMT;
--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN TOTALDEPOSITAMOUNT TO TOTAL_DEPOSIT_AMOUNT;
--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN FINANCIALYEAR TO FINANCIALYEAR_ID;
--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN COA TO COA_ID;
--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN DEPOSITCODE TO DEPOSITCODE_ID;
--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE RENAME COLUMN ABSTRACTESTIMATE TO ABSTRACTESTIMATE_ID;

--rollback ALTER TABLE EGW_DEPOSITWORKS_USAGE DROP COLUMN version;