
ALTER TABLE EGW_ESTIMATE_ACTIVITY ADD COLUMN version bigint DEFAULT 0;
ALTER TABLE EGW_ESTIMATE_ACTIVITY DROP COLUMN estimate_activity_index;

ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN ABSTRACTESTIMATE_ID TO ABSTRACTESTIMATE;
ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN SCHEDULEOFRATE_ID TO SCHEDULEOFRATE;
ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN NONSOR_ID TO NONSOR;
ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN UOM_ID TO UOM;
ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN UNIT_RATE TO UNITRATE;
ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN SOR_RATE TO SORRATE;
ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN REVISION_TYPE TO REVISIONTYPE;
ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN PARENTID TO PARENT;

ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN CREATED_BY TO CREATEDBY;
ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN CREATED_DATE TO CREATEDDATE;
ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN modified_by TO lastmodifiedby;
ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN modified_date TO lastmodifieddate;

ALTER TABLE EGW_NONSOR ADD COLUMN version bigint DEFAULT 0;
ALTER TABLE EGW_NONSOR RENAME COLUMN UOM_ID TO UOM;
ALTER TABLE EGW_NONSOR RENAME COLUMN CREATED_BY TO CREATEDBY;
ALTER TABLE EGW_NONSOR RENAME COLUMN CREATED_DATE TO CREATEDDATE;
ALTER TABLE EGW_NONSOR RENAME COLUMN modified_by TO lastmodifiedby;
ALTER TABLE EGW_NONSOR RENAME COLUMN modified_date TO lastmodifieddate;

--rollback ALTER TABLE EGW_NONSOR RENAME COLUMN lastmodifieddate TO modified_date;
--rollback ALTER TABLE EGW_NONSOR RENAME COLUMN lastmodifiedby TO modified_by;
--rollback ALTER TABLE EGW_NONSOR RENAME COLUMN CREATEDDATE TO CREATED_DATE;
--rollback ALTER TABLE EGW_NONSOR RENAME COLUMN CREATEDBY TO CREATED_BY;

--rollback ALTER TABLE EGW_NONSOR RENAME COLUMN UOM TO UOM_ID;
--rollback ALTER TABLE EGW_NONSOR DROP COLUMN version;

--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN lastmodifieddate TO modified_date;
--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN lastmodifiedby TO modified_by;
--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN CREATEDDATE TO CREATED_DATE;
--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN CREATEDBY TO CREATED_BY;

--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN PARENT TO PARENTID;
--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN REVISIONTYPE TO REVISION_TYPE;
--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN SORRATE TO SOR_RATE;
--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN UNITRATE TO UNIT_RATE;
--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN UOM TO UOM_ID;
--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN NONSOR TO NONSOR_ID;
--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN SCHEDULEOFRATE TO SCHEDULEOFRATE_ID;
--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY RENAME COLUMN ABSTRACTESTIMATE TO ABSTRACTESTIMATE_ID;

--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY ADD COLUMN estimate_activity_index bigint NOT NULL;
--rollback ALTER TABLE EGW_ESTIMATE_ACTIVITY DROP COLUMN version;