
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN version bigint DEFAULT 0;

ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN estimate_number TO estimatenumber;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN estimate_date TO estimatedate;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN user_department TO userdepartment;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN executing_department TO executingdepartment;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN work_value TO workvalue;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN estimate_value TO estimatevalue;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN work_type TO typeofwork;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN work_subtype TO subtypeofwork;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN fundsource_id TO fundsource;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN status_id TO status;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN despositcode_id TO despositcode;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN projectcode_id TO projectcode;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN parentid TO parent;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN approved_date TO approveddate;

ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN IF EXISTS is_copied_est;
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN copiedestimate boolean DEFAULT 'false';

ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN modifiedby TO lastmodifiedby;
ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN modifieddate TO lastmodifieddate;

ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN IF EXISTS budgetapprno;
ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN IF EXISTS budget_apprn_date;
ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN IF EXISTS budgetavailable;
ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN IF EXISTS budgetrejectionno;

--rollback ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN budgetrejectionno character varying(256);
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN budgetavailable double precision;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN budget_apprn_date timestamp without time zone;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN budgetapprno character varying(256);

--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN lastmodifieddate TO modifieddate;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN lastmodifiedby TO modifiedby;

--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN IF EXISTS copiedestimate;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN is_copied_est character varying(1) DEFAULT 'N'::character varying;

--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN approveddate TO approved_date;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN parent TO parentid;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN projectcode TO projectcode_id;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN despositcode TO despositcode_id;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN status TO status_id;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN fundsource TO fundsource_id;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN subtypeofwork TO work_subtype;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN typeofwork TO work_type;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN estimatevalue TO estimate_value;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN workvalue TO work_value;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN executingdepartment TO executing_department;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN userdepartment TO user_department;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN estimatedate TO estimate_date;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE RENAME COLUMN estimatenumber TO estimate_number;

--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN version;