UPDATE EGW_STATUS SET ORDER_ID = 3 where MODULETYPE = 'AbstractEstimate' and CODE = 'TECH_SANCTIONED';
UPDATE EGW_STATUS SET ORDER_ID = 4 where MODULETYPE = 'AbstractEstimate' and CODE = 'BUDGETARY_APPROPRIATION_DONE';
UPDATE EGW_STATUS SET ORDER_ID = 5 where MODULETYPE = 'AbstractEstimate' and CODE = 'DEPOSIT_CODE_APPR_DONE';
UPDATE EGW_STATUS SET ORDER_ID = 6 where MODULETYPE = 'AbstractEstimate' and CODE = 'ADMIN_SANCTIONED';
UPDATE EGW_STATUS SET ORDER_ID = 7 where MODULETYPE = 'AbstractEstimate' and CODE = 'REJECTED';
UPDATE EGW_STATUS SET ORDER_ID = 8 where MODULETYPE = 'AbstractEstimate' and CODE = 'RESUBMITTED';
UPDATE EGW_STATUS SET ORDER_ID = 9 where MODULETYPE = 'AbstractEstimate' and CODE = 'CANCELLED';

Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (NEXTVAL('SEQ_EGW_STATUS'),'AbstractEstimate','Checked',now(),'CHECKED',2);

--rollback delete from EGW_STATUS where MODULETYPE='AbstractEstimate' and CODE='CHECKED';

--rollback UPDATE EGW_STATUS SET ORDER_ID = 2 where MODULETYPE = 'AbstractEstimate' and CODE = 'TECH_SANCTIONED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 3 where MODULETYPE = 'AbstractEstimate' and CODE = 'BUDGETARY_APPROPRIATION_DONE';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 4 where MODULETYPE = 'AbstractEstimate' and CODE = 'DEPOSIT_CODE_APPR_DONE';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 5 where MODULETYPE = 'AbstractEstimate' and CODE = 'ADMIN_SANCTIONED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 6 where MODULETYPE = 'AbstractEstimate' and CODE = 'REJECTED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 7 where MODULETYPE = 'AbstractEstimate' and CODE = 'RESUBMITTED';
--rollback UPDATE EGW_STATUS SET ORDER_ID = 8 where MODULETYPE = 'AbstractEstimate' and CODE = 'CANCELLED';