ALTER TABLE EGW_WO_MEASUREMENTSHEET ADD COLUMN PARENT BIGINT;
ALTER TABLE EGW_WO_MEASUREMENTSHEET ADD CONSTRAINT FK_WO_MEASUREMENTSHEET_PARENT FOREIGN KEY (PARENT) REFERENCES EGW_WO_MEASUREMENTSHEET (ID);

--rollback ALTER TABLE EGW_WO_MEASUREMENTSHEET DROP COLUMN PARENT;