delete from eg_wf_matrix where objecttype  = 'WorkOrder';

--0 to 200000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Approval', 'Deputy Executive Engineer', 'Created', 'Forward', 0, 200000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Created', NULL, 'Pending Approval', 'Deputy Executive Engineer', NULL, 'Approved', 'END', 'NULL', 'NULL', 'Approve,Reject', 0, 200000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, 'Pending Approval', 'Assistant Engineer', NULL, 'Resubmitted', 'Pending Approval', 'Deputy Executive Engineer', NULL, 'Forward,Cancel', 0, 200000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, 'Pending Approval', 'Deputy Executive Engineer', NULL, 'Approved', 'END', 'NULL', 'NULL', 'Approve,Reject', 0, 200000, now(), now());

--200000 to 1000000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Forward', 200000.1, 1000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Approval', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 200000.1, 1000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Approval', 'Executive Engineer', NULL, 'Approved', 'END', 'NULL', 'NULL', 'Approve,Reject', 200000.1, 1000000, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, NULL, 'Assistant Engineer', NULL, 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Forward,Cancel', 200000.1, 1000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Approval', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 200000.1, 1000000, now(), now());

--1000000 to 5000000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Forward', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Check By Executive Engineer', 'Executive Engineer', NULL, 'Checked', 'Pending Approval', 'Superintending Engineer', 'Pending Approval', 'Submit,Reject', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Approval', 'Superintending Engineer', NULL, 'Approved', 'END', 'NULL', 'NULL', 'Approve,Reject', 1000000.1, 5000000, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, NULL, 'Assistant Engineer', NULL, 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Forward,Cancel', 1000000.1, 5000000, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 1000000.1, 5000000, now(), now());

-- >5000000
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Assistant Engineer', NULL, 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Forward', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Check By Executive Engineer', 'Executive Engineer', NULL, 'Checked', 'Pending Check By Superintending Engineer', 'Superintending Engineer', 'Pending Check By Superintending Engineer', 'Submit,Reject', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Check By Superintending Engineer', 'Superintending Engineer', NULL, 'Checked', 'Pending Approval', 'Chief Engineer', 'Pending Approval', 'Submit,Reject', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Approval', 'Chief Engineer', NULL, 'Approved', 'END', 'NULL', 'NULL', 'Approve,Reject', 5000000.1, NULL, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, NULL, 'Assistant Engineer', NULL, 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Forward,Cancel', 5000000.1, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES 
(nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', NULL, 'Checked', 'Pending Check By Executive Engineer', 'Executive Engineer', 'Pending Check By Executive Engineer', 'Submit,Reject', 5000000.1, NULL, now(), now());

--rollback delete from EGW_STATUS where MODULETYPE='WorkOrder' and CODE='CHECKED';
--rollback INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Assistant engineer', NULL, 'Approve', 'Pending Approval', 'Assistant Executive Engineer', 'Approve', 'Forward', NULL, NULL, now(), now());
--rollback INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Approve', NULL, NULL, 'Assistant Executive Engineer', NULL, 'Approved', 'END', NULL, NULL, 'Approve,Reject', NULL, NULL, now(), now());
--rollback INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, NULL, 'Assistant engineer', NULL, 'Approve', 'Pending Approval', 'Assistant Executive Engineer', NULL, 'Forward,Cancel', NULL, NULL, now(), now());
--rollback INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, NULL, 'Assistant Executive Engineer', NULL, 'Approved', 'END', NULL, NULL, 'Approve,Reject', NULL, NULL, now(), now());
--rollback UPDATE EG_WF_MATRIX SET nextstate = 'Resubmitted' where objecttype = 'WorkOrder' and currentstate = 'Rejected';

