------------------START------------------
ALTER TABLE EGW_CONTRACTORBILL ADD COLUMN CANCELLATIONREASON varchar(50);
ALTER TABLE EGW_CONTRACTORBILL ADD COLUMN CANCELLATIONREMARKS varchar(126);
-------------------END-------------------
--rollback ALTER TABLE EGW_CONTRACTORBILL DROP COLUMN CANCELLATIONREMARKS;
--rollback ALTER TABLE EGW_CONTRACTORBILL DROP COLUMN CANCELLATIONREASON; 
