
ALTER TABLE EGW_MULTIYEAR_ESTIMATE ADD COLUMN version bigint DEFAULT 0;
ALTER TABLE EGW_MULTIYEAR_ESTIMATE DROP COLUMN multiyear_estimate_index;

ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN ABSTRACTESTIMATE_ID TO ABSTRACTESTIMATE;
ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN FINANCIALYEAR_ID TO FINANCIALYEAR;

ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN CREATED_BY TO CREATEDBY;
ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN CREATED_DATE TO CREATEDDATE;
ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN modified_by TO lastmodifiedby;
ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN modified_date TO lastmodifieddate;

ALTER TABLE EGW_ESTIMATE_OVERHEADS ADD COLUMN version bigint DEFAULT 0;
ALTER TABLE EGW_ESTIMATE_OVERHEADS DROP COLUMN estimate_overhead_index;

ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN ABSTRACTESTIMATE_ID TO ABSTRACTESTIMATE;
ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN OVERHEAD_ID TO OVERHEAD;

ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN CREATED_BY TO CREATEDBY;
ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN CREATED_DATE TO CREATEDDATE;
ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN modified_by TO lastmodifiedby;
ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN modified_date TO lastmodifieddate;

--rollback ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN lastmodifieddate TO modifieddate;
--rollback ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN lastmodifiedby TO modifiedby;
--rollback ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN CREATEDDATE TO CREATED_DATE;
--rollback ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN CREATEDBY TO CREATED_BY;

--rollback ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN OVERHEAD TO OVERHEAD_ID;
--rollback ALTER TABLE EGW_ESTIMATE_OVERHEADS RENAME COLUMN ABSTRACTESTIMATE TO ABSTRACTESTIMATE_ID;
--rollback ALTER TABLE EGW_ESTIMATE_OVERHEADS ADD COLUMN estimate_overhead_index bigint NOT NULL;
--rollback ALTER TABLE EGW_ESTIMATE_OVERHEADS DROP COLUMN version;


--rollback ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN lastmodifieddate TO modifieddate;
--rollback ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN lastmodifiedby TO modifiedby;
--rollback ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN CREATEDDATE TO CREATED_DATE;
--rollback ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN CREATEDBY TO CREATED_BY;

--rollback ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN FINANCIALYEAR TO FINANCIALYEAR_ID;
--rollback ALTER TABLE EGW_MULTIYEAR_ESTIMATE RENAME COLUMN ABSTRACTESTIMATE TO ABSTRACTESTIMATE_ID;
--rollback ALTER TABLE EGW_MULTIYEAR_ESTIMATE ADD COLUMN multiyear_estimate_index bigint NOT NULL;
--rollback ALTER TABLE EGW_MULTIYEAR_ESTIMATE DROP COLUMN version;