
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksPackageSave','/tender/worksPackage-save.action',null,(select id from EG_MODULE where name = 'WorksPackage'),0,'WorksPackageSave','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksPackageSave' and contextroot = 'egworks'));

Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksTenderFileNoUniqueCheckAjax','/tender/ajaxWorksPackage-tenderFileNumberUniqueCheck.action',null,(select id from EG_MODULE where name = 'WorksPackage'),0,'WorksTenderFileNoUniqueCheckAjax','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksTenderFileNoUniqueCheckAjax' and contextroot = 'egworks'));

Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksPackagePDF','/tender/worksPackage-viewWorksPackagePdf.action',null,(select id from EG_MODULE where name = 'WorksPackage'),0,'WorksPackagePDF','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksPackagePDF' and contextroot = 'egworks'));

Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksPackageEdit','/tender/worksPackage-edit.action',null,(select id from EG_MODULE where name = 'WorksPackage'),0,'WorksPackageEdit','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksPackageEdit' and contextroot = 'egworks'));

update eg_action set url='/tender/searchWorksPackage.action' where name='SearchWorksPackage' and contextroot = 'egworks';

Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksPackageSearch','/tender/searchWorksPackage-search.action',null,(select id from EG_MODULE where name = 'WorksPackage'),0,'WorksPackageSearch','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksPackageSearch' and contextroot = 'egworks'));

Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'AjaxSearchWorksPackageNumber','/tender/ajaxWorksPackage-searchWorksPackageNumber.action',null,(select id from EG_MODULE where name = 'WorksPackage'),0,'AjaxSearchWorksPackageNumber','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='AjaxSearchWorksPackageNumber' and contextroot = 'egworks'));

Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'AjaxTRPresentForWPCheck','/tender/ajaxWorksPackage-isTRPresentForWPCheck.action',null,(select id from EG_MODULE where name = 'WorksPackage'),0,'AjaxTRPresentForWPCheck','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='AjaxTRPresentForWPCheck' and contextroot = 'egworks'));

Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'AjaxWPSearchTenderFileNumber','/tender/ajaxWorksPackage-searchTenderFileNumber.action',null,(select id from EG_MODULE where name = 'WorksPackage'),0,'AjaxWPSearchTenderFileNumber','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='AjaxWPSearchTenderFileNumber' and contextroot = 'egworks'));

Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'AjaxWPSearchEstimateNumber','/tender/ajaxWorksPackage-searchEstimateNumber.action',null,(select id from EG_MODULE where name = 'WorksPackage'),0,'AjaxWPSearchEstimateNumber','false','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='AjaxWPSearchEstimateNumber' and contextroot = 'egworks'));

 
--rollback delete from eg_roleaction where actionid in (select id from eg_action where name in ('WorksPackageSave', 'WorksTenderFileNoUniqueCheckAjax','WorksPackagePDF','WorksPackageEdit','WorksPackageSearch','AjaxSearchWorksPackageNumber','AjaxTRPresentForWPCheck','AjaxWPSearchTenderFileNumber','AjaxWPSearchEstimateNumber') and contextroot = 'egworks') and roleid in(select id from eg_role where name = 'Super User');
--rollback delete from eg_action where name in ('WorksPackageSave','WorksTenderFileNoUniqueCheckAjax','WorksPackagePDF','WorksPackageEdit','WorksPackageSearch','AjaxSearchWorksPackageNumber','AjaxTRPresentForWPCheck','AjaxWPSearchTenderFileNumber','AjaxWPSearchEstimateNumber') and contextroot = 'egworks';