delete from eg_wf_matrix  where objecttype  = 'WorkOrder';
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Technical Officer', 'I', 'Created', 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Created', 'Forward', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Created', NULL, 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'I', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Approval', 'Commissioner', 'I', 'Approved', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, NULL, 'Technical Officer', 'I', 'Resubmitted', 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Resubmitted', 'Forward,Cancel', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'I', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Assistant engineer', 'II', 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Forward', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'II', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Approval', 'Commissioner', 'II', 'Approved', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, NULL, 'Assistant engineer', 'II', 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Resubmitted', 'Forward,Cancel', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'II', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Assistant engineer', 'III', 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Forward', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'III', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Approval', 'Commissioner', 'III', 'Approved', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, NULL, 'Assistant engineer', 'III', 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Resubmitted', 'Forward,Cancel', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'III', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Assistant engineer', 'NP', 'Created', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Created', 'Forward', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Created', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'NP', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Approval', 'Commissioner', 'NP', 'Approved', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, NULL, 'Assistant engineer', 'NP', 'Resubmitted', 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'Resubmitted', 'Forward,Cancel', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, 'Pending Check By Deputy Executive Engineer', 'Deputy Executive Engineer', 'NP', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Technical Officer', 'Special', 'Created', 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Created', 'Forward', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Created', NULL, 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Special', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Approval', 'Commissioner', 'Special', 'Approved', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, NULL, 'Technical Officer', 'Special', 'Resubmitted', 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Resubmitted', 'Forward,Cancel', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Special', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Technical Officer', 'Selection', 'Created', 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Created', 'Forward', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Created', NULL, 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Selection', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Approval', 'Commissioner', 'Selection', 'Approved', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, NULL, 'Technical Officer', 'Selection', 'Resubmitted', 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Resubmitted', 'Forward,Cancel', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Selection', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());

INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'NEW', NULL, NULL, 'Technical Officer', 'Corp', 'Created', 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Created', 'Forward', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Created', NULL, 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Corp', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Checked', NULL, 'Pending Approval', 'Commissioner', 'Corp', 'Approved', 'END', NULL, NULL, 'Approve,Reject', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Rejected', NULL, NULL, 'Technical Officer', 'Corp', 'Resubmitted', 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Resubmitted', 'Forward,Cancel', 0, NULL, now(), now());
INSERT INTO EG_WF_MATRIX (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction,nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('seq_eg_wf_matrix'), 'ANY', 'WorkOrder', 'Resubmitted', NULL, 'Pending Check By Executive Engineer / Superintending Engineer / Chief engineer', 'Executive Engineer,Superintending Engineer,Chief Engineer', 'Corp', 'Checked', 'Pending Approval', 'Commissioner', 'Checked', 'Submit,Reject', 0, NULL, now(), now());