------------------START------------------
ALTER TABLE EGW_CONTRACTORBILL DROP COLUMN DOCUMENT_NUMBER;

ALTER TABLE EGW_CONTRACTORBILL ADD COLUMN WORKORDER bigint not null; 
ALTER TABLE EGW_CONTRACTORBILL ADD CONSTRAINT fk_contractorbill_workorder FOREIGN KEY (workorder) REFERENCES egw_workorder (id);
CREATE INDEX idx_contractorbill_workorder ON EGW_CONTRACTORBILL USING btree (workorder);       
ALTER TABLE EGW_CONTRACTORBILL DROP COLUMN PART_BILLNUMBER;
ALTER TABLE EGW_CONTRACTORBILL ADD COLUMN BILLSEQUENCENUMBER integer;

ALTER TABLE EGW_CONTRACTORBILL RENAME COLUMN APPROVED_DATE to APPROVEDDATE;
-------------------END-------------------

--rollback ALTER TABLE EGW_CONTRACTORBILL RENAME COLUMN APPROVEDDATE to APPROVED_DATE;
--rollback ALTER TABLE EGW_CONTRACTORBILL DROP COLUMN BILLSEQUENCENUMBER;
--rollback ALTER TABLE EGW_CONTRACTORBILL ADD COLUMN PART_BILLNUMBER bigint; 

--rollback ALTER TABLE EGW_CONTRACTORBILL DROP COLUMN WORKORDER;

--rollback ALTER TABLE EGW_CONTRACTORBILL ADD COLUMN DOCUMENT_NUMBER bigint; 
