ALTER TABLE EGW_ESTIMATE_FINANCINGSOURCE ADD COLUMN createdby bigint;
ALTER TABLE EGW_ESTIMATE_FINANCINGSOURCE ADD COLUMN lastmodifiedby bigint;
ALTER TABLE EGW_ESTIMATE_FINANCINGSOURCE ADD COLUMN createddate timestamp without time zone;