------------------START------------------
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN ADMINSANCTIONNUMBER character varying(50);
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN ADMINSANCTIONDATE timestamp without time zone;
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN ADMINSANCTIONBY character varying(100);
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN COUNCILRESOLUTIONNUMBER character varying(100);
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN COUNCILRESOLUTIONDATE timestamp without time zone;
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN SPILLOVERFLAG boolean DEFAULT false;
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN grossamountbilled double precision;
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN workordercreated boolean DEFAULT false;
ALTER TABLE EGW_ABSTRACTESTIMATE ADD COLUMN billscreated boolean DEFAULT false;

-----------------END------------------------------
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN billscreated;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN workordercreated;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN grossamountbilled;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN SPILLOVERFLAG;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN ADMINSANCTIONNUMBER;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN ADMINSANCTIONDATE;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN ADMINSANCTIONBY;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN COUNCILRESOLUTIONNUMBER;
--rollback ALTER TABLE EGW_ABSTRACTESTIMATE DROP COLUMN COUNCILRESOLUTIONDATE;
