CREATE TABLE TEMP_EG_ROLE_ACTION(
ACTIONID bigint,
ROLEID bigint
);

INSERT INTO TEMP_EG_ROLE_ACTION (ACTIONID, ROLEID)
SELECT ACTIONID, ROLEID FROM EG_ROLEACTION GROUP BY ACTIONID, ROLEID;

DELETE FROM EG_ROLEACTION;

INSERT INTO EG_ROLEACTION (ACTIONID, ROLEID)
SELECT ACTIONID, ROLEID FROM TEMP_EG_ROLE_ACTION;

DROP TABLE TEMP_EG_ROLE_ACTION;

ALTER TABLE EG_ROLEACTION ADD CONSTRAINT unq_roleaction UNIQUE(actionid,roleid);


INSERT INTO EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) VALUES 
(NEXTVAL('SEQ_EG_ACTION'),'ListFeaturesByModule','/feature/access-control/list-by-module', null,(select id from EG_MODULE where name = 'EGI-FeatureAccessControl'),1,
'ListFeaturesByModule',false,'egi',0,1,now(),1,now(),(select id from eg_module  where name = 'Administration'));

INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) 
VALUES 
((select id from eg_role where name = 'Super User') ,(select id FROM eg_action  WHERE name = 'ListFeaturesByModule'));
