ALTER TABLE EG_FAVOURITES ALTER COLUMN userid SET NOT NULL;
ALTER TABLE EG_FAVOURITES ALTER COLUMN actionid SET NOT NULL;
ALTER TABLE EG_FAVOURITES ALTER COLUMN name SET NOT NULL;
ALTER TABLE EG_FAVOURITES ALTER COLUMN contextroot SET NOT NULL;

ALTER TABLE EG_MESSAGETEMPLATE ALTER COLUMN locale SET NOT NULL;

ALTER TABLE EG_IDENTITYRECOVERY ALTER COLUMN token SET NOT NULL;
ALTER TABLE EG_IDENTITYRECOVERY ALTER COLUMN userid SET NOT NULL;
ALTER TABLE EG_IDENTITYRECOVERY ALTER COLUMN expiry SET NOT NULL;

ALTER TABLE EG_ACTION ALTER COLUMN url SET NOT NULL;
ALTER TABLE EG_ACTION ALTER COLUMN contextRoot SET NOT NULL;
UPDATE EG_ACTION SET enabled=false where enabled is null;
ALTER TABLE EG_ACTION ALTER COLUMN enabled SET NOT NULL;

DROP INDEX indx_eram_actionid,indx_eram_roleid;

ALTER TABLE eg_appconfig RENAME COLUMN key_name to keyname;

ALTER TABLE eg_appconfig_values RENAME COLUMN key_id to config;
ALTER TABLE eg_appconfig_values RENAME COLUMN effective_from to effectivefrom;

ALTER TABLE eg_boundary ALTER COLUMN boundarynum SET NOT NULL;
ALTER TABLE eg_boundary ALTER COLUMN code SET NOT NULL;
ALTER TABLE eg_boundary ALTER COLUMN fromdate SET NOT NULL;

ALTER TABLE eg_boundary_type RENAME TO eg_boundarytype;
ALTER TABLE eg_boundarytype ALTER COLUMN code SET NOT NULL;

ALTER TABLE eg_department ALTER COLUMN code TYPE varchar(64);
ALTER TABLE eg_department ALTER COLUMN code SET NOT NULL;

ALTER TABLE eg_feature ALTER COLUMN name SET NOT NULL;

ALTER TABLE eg_hierarchy_type ALTER COLUMN code SET NOT NULL;

CREATE UNIQUE INDEX idx_eg_location_name ON eg_location(name);

ALTER TABLE eg_filestoremap ALTER COLUMN filename TYPE varchar(255);

ALTER TABLE EG_APPLICATIONINDEX ALTER COLUMN cityname TYPE varchar(50);
ALTER TABLE EG_APPLICATIONINDEX ALTER COLUMN districtname TYPE varchar(50);
ALTER TABLE EG_APPLICATIONINDEX ALTER COLUMN mobilenumber TYPE varchar(12);
ALTER TABLE EG_APPLICATIONINDEX ALTER COLUMN aadharnumber TYPE varchar(12);
ALTER TABLE EG_APPLICATIONINDEX ALTER COLUMN closed TYPE varchar(5);
ALTER TABLE EG_APPLICATIONINDEX ALTER COLUMN approved TYPE varchar(20);

