update eg_wf_matrix set validactions='Forward,Preview,Sign' where objecttype='TradeLicense' and currentstate like'Chief Medical Officer of Health Approved' and currentdesignation='Chief Medical Officer of Health' and additionalrule in ('NEWLICENSE','RENEWLICENSE');

Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','Digital Signature Pending','Assistant Medical Officer of Health','NEWLICENSE','Assistant Medical Officer of Health Approved','','Municipal Health Officer,Assistant Medical Officer of Health,Commissioner','','Forward,Preview,Sign',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','Second Level Collection Pending','Assistant Medical Officer of Health','NEWLICENSECOLLECTION','Second Level Collection Paid','Digital Signature Pending','Assistant Medical Officer of Health','','Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','Digital Signature Pending','Assistant Medical Officer of Health','RENEWLICENSE','Assistant Medical Officer of Health Approved','','Municipal Health Officer,Assistant Medical Officer of Health,Commissioner','','Forward,Preview,Sign',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','Second Level Collection Pending','Assistant Medical Officer of Health','RENEWLICENSECOLLECTION','Second Level Collection Paid','Digital Signature Pending','Assistant Medical Officer of Health','','Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);

delete from eg_wf_matrix where objecttype='TradeLicense' and additionalrule='RENEWLICENSE' and currentstate='Sanitary Inspector Approved' and pendingactions='Municipal Health Officer Approval Pending';
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Municipal Health Officer Approval Pending','Municipal Health Officer','RENEWLICENSE','Municipal Health Officer Approved','','Chief Medical Officer of Health,Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);

