alter table egtl_license add column newworkflow boolean, add column collectionpending boolean;

--workflow matrix script

Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','New','','License Creation Pending','Senior Assistant,Junior Assistant','NEWLICENSE','License Created','First level Collection pending','Senior Assistant,Junior Assistant','CREATED','Save',null,null,'2015-04-01','2099-04-01',0,'all',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'PUBLIC HEALTH AND SANITATION','TradeLicense','New','','License Creation Pending','','CSCOPERATORNEWLICENSE','License Created','First level Collection pending','Senior Assistant,Junior Assistant','CREATED','Save',null,null,'2015-04-01','2099-04-01',0,'all',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','License Created','','First level Collection pending','Senior Assistant,Junior Assistant','NEWLICENSE','First Level Fee Collected','Assistant Approval Pending','Senior Assistant,Junior Assistant','','Cancel',null,null,'2015-04-01','2099-04-01',0,'all',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','First Level Fee Collected','','Assistant Approval Pending','Senior Assistant,Junior Assistant','NEWLICENSE','Assistant Approved','SI Approval Pending','Sanitary Inspector','','Forward,Cancel',null,null,'2015-04-01','2099-04-01',0,'all',true,false,null,true);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Approved','','SI Approval Pending','Sanitary Inspector','NEWLICENSE','Sanitary Inspector Approved','','Sanitary Supervisor,Assistant Medical Officer of Health,Municipal Health Officer,Chief Medical Officer of Health,Commissioner','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,true);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','SS Verification Pending','Sanitary Supervisor','NEWLICENSE','Sanitary Supervisor Verified','','Assistant Medical Officer of Health,Municipal Health Officer,Chief Medical Officer of Health,Commissioner','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,true);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Municipal Health Officer Approval Pending','Municipal Health Officer','NEWLICENSE','Municipal Health Officer Approved','','Chief Medical Officer of Health,Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Commissioner Approval Pending','Commissioner','NEWLICENSE','Commissioner Approved','Digital Signature Pending','Commissioner','','Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Municipal Health Officer Approval Pending','Municipal Health Officer','NEWLICENSE','Municipal Health Officer Approved','Digital Signature Pending','Chief Medical Officer of Health,Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Commissioner Approval Pending','Commissioner','NEWLICENSE','Commissioner Approved','Digital Signature Pending','Commissioner','','Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Municipal Health Officer Approved','','Digital Signature Pending','Municipal Health Officer','NEWLICENSE','Municipal Health Officer Approved',null,'Chief Medical Officer of Health,Commissioner','','Forward,Preview,Sign',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Municipal Health Officer Approved','','Commissioner Approval Pending','Commissioner','NEWLICENSE','Commissioner Approved','Digital Signature Pending','Commissioner','','Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Commissioner Approved','','Digital Signature Pending','Commissioner','NEWLICENSE','Digitally Signed','','','','Preview,Sign',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Municipal Health Officer Approval Pending','Municipal Health Officer','NEWLICENSECOLLECTION','Municipal Health Officer Approved','Second Level Collection Pending','Municipal Health Officer','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Municipal Health Officer Approved','','Second Level Collection Pending','Municipal Health Officer','NEWLICENSECOLLECTION','Second Level Collection Paid','Digital Signature Pending','Municipal Health Officer','','Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Commissioner Approval Pending','Commissioner','NEWLICENSECOLLECTION','Commissioner Approved','Second Level Collection Pending','Commissioner','','Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Commissioner Approved','','Second Level Collection Pending','Commissioner','NEWLICENSECOLLECTION','Second Level Collection Paid','Digital Signature Pending','Commissioner','','Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Municipal Health Officer Approval Pending','Municipal Health Officer','NEWLICENSECOLLECTION','Municipal Health Officer Approved','Second Level Collection Pending','Chief Medical Officer of Health,Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Commissioner Approval Pending','Commissioner','NEWLICENSECOLLECTION','Commissioner Approved','Second Level Collection Pending','Commissioner','','Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Municipal Health Officer Approved','','Commissioner Approval Pending','Commissioner','NEWLICENSECOLLECTION','Commissioner Approved','Second Level Collection Pending','Commissioner','','Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Second Level Collection Paid','','Digital Signature Pending','Municipal Health Officer','NEWLICENSE','Second Level Collection Paid','','Chief Medical Officer of Health,Commissioner','','Forward,Preview,Sign',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Second Level Collection Paid','','Digital Signature Pending','Commissioner','NEWLICENSE','Digitally Signed','END','','','Preview,Sign',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','SS Verification Pending','Sanitary Supervisor','NEWLICENSECOLLECTION','Sanitary Supervisor Verified','','Assistant Medical Officer of Health,Municipal Health Officer,Chief Medical Officer of Health,Commissioner','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Approved','','SI Approval Pending','Sanitary Inspector','NEWLICENSEREJECT','Sanitary Inspector Rejected','Assistant Approval Pending','Senior Assistant,Junior Assistant','','Forward,Cancel',null,null,'2015-04-01','2099-04-01',0,'all',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Rejected','','Assistant Approval Pending','Senior Assistant,Junior Assistant','NEWLICENSE','Assistant Approved','SI Approval Pending','Senior Assistant,Junior Assistant','','Forward,Cancel',null,null,'2015-04-01','2099-04-01',0,'all',true,false,null,true);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','SS Verification Pending','Sanitary Supervisor','NEWLICENSEREJECT','Sanitary Supervisor Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Rejected','','SI Approval Pending','Sanitary Inspector','NEWLICENSE','Sanitary Inspector Approved','','Sanitary Supervisor,Assistant Medical Officer of Health,Municipal Health Officer,Chief Medical Officer of Health,Commissioner,','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'all',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Municipal Health Officer Approval Pending','Municipal Health Officer','NEWLICENSEREJECT','Municipal Health Officer Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Municipal Health Officer Rejected','','SI Approval Pending','Sanitary Inspector','NEWLICENSE','Sanitary Inspector Approved','','Sanitary Supervisor,Assistant Medical Officer of Health,Municipal Health Officer,Chief Medical Officer of Health,Commissioner','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'all',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Commissioner Approval Pending','Commissioner','NEWLICENSEREJECT','Commissioner Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Commissioner Rejected','','SI Approval Pending','Sanitary Inspector','NEWLICENSE','Sanitary Inspector Approved','','Sanitary Supervisor,Assistant Medical Officer of Health,Municipal Health Officer,Chief Medical Officer of Health,Commissioner','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'all',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Municipal Health Officer Approved','','','Commissioner','NEWLICENSEREJECT','Commissioner Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Commissioner Approved','','Second Level Collection Pending','Commissioner','NEWLICENSEREJECT','Commissioner Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Municipal Health Officer Approved','','Second Level Collection Pending','Municipal Health Officer','NEWLICENSEREJECT','Municipal Health Officer Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Assistant Medical Officer of Health Approval Pending','Assistant Medical Officer of Health','NEWLICENSE','Assistant Medical Officer of Health Approved','','Municipal Health Officer,Chief Medical Officer of Health,Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Assistant Medical Officer of Health Approval Pending','Assistant Medical Officer of Health','NEWLICENSECOLLECTION','Assistant Medical Officer of Health Approved','','Municipal Health Officer,Chief Medical Officer of Health,Commissioner','Second Level Collection Pending','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Chief Medical Officer of Health Approval Pending','Chief Medical Officer of Health','NEWLICENSE','Chief Medical Officer of Health Approved','','Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Chief Medical Officer of Health Approval Pending','Chief Medical Officer of Health','NEWLICENSECOLLECTION','Chief Medical Officer of Health Approved','','Commissioner','Second Level Collection Pending','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Assistant Medical Officer of Health Approval Pending','Assistant Medical Officer of Health','NEWLICENSE','Assistant Medical Officer of Health Approved','','Municipal Health Officer,Chief Medical Officer of Health,Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Assistant Medical Officer of Health Approval Pending','Assistant Medical Officer of Health','NEWLICENSECOLLECTION','Assistant Medical Officer of Health Approved','','Municipal Health Officer,Chief Medical Officer of Health,Commissioner','Second Level Collection Pending','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Chief Medical Officer of Health Approval Pending','Chief Medical Officer of Health','NEWLICENSE','Chief Medical Officer of Health Approved','','Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Chief Medical Officer of Health Approval Pending','Chief Medical Officer of Health','NEWLICENSE','Chief Medical Officer of Health Approved','','Commissioner','Second Level Collection Pending','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','Chief Medical Officer of Health Approval Pending','Chief Medical Officer of Health','NEWLICENSE','Chief Medical Officer of Health Approved','','Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','Chief Medical Officer of Health Approval Pending','Chief Medical Officer of Health','NEWLICENSECOLLECTION','Chief Medical Officer of Health Approved','','Commissioner','Second Level Collection Pending','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','Municipal Health Officer Approval Pending','Municipal Health Officer','NEWLICENSE','Municipal Health Officer Approved','','Chief Medical Officer of Health,Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','Municipal Health Officer Approval Pending','Municipal Health Officer','NEWLICENSECOLLECTION','Municipal Health Officer Approved','Second Level Collection Pending','Chief Medical Officer of Health,Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','Commissioner Approval Pending','Commissioner','NEWLICENSE','Commissioner Approved','','Commissioner','','Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','Commissioner Approval Pending','Commissioner','NEWLICENSECOLLECTION','Commissioner Approved','Second Level Collection Pending','Commissioner','','Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Municipal Health Officer Approved','','Chief Medical Officer of Health Approval Pending','Chief Medical Officer of Health','NEWLICENSE','Chief Medical Officer of Health Approved','','Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Municipal Health Officer Approved','','Chief Medical Officer of Health Approval Pending','Chief Medical Officer of Health','NEWLICENSECOLLECTION','Chief Medical Officer of Health Approved','','Commissioner','Second Level Collection Pending','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Chief Medical Officer of Health Approved','','Digital Signature Pending','Chief Medical Officer of Health','NEWLICENSE','Chief Medical Officer of Health Approved','','Commissioner','','Forward,Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',true,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Chief Medical Officer of Health Approved','','Commissioner Approval Pending','Commissioner','NEWLICENSE','Commissioner Approved','','Commissioner','','Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Chief Medical Officer of Health Approved','','Second Level Collection Pending','Chief Medical Officer of Health','NEWLICENSECOLLECTION','Second Level Collection Paid','Digital Signature Pending','Chief Medical Officer of Health','','Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,true,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Chief Medical Officer of Health Approved','','Commissioner Approval Pending','Commissioner','NEWLICENSECOLLECTION','Commissioner Approved','Second Level Collection Pending','Commissioner','','Approve,Reject',null,null,'2015-04-01','2099-04-01',0,'parentBoundary,boundary',false,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Assistant Medical Officer of Health Approval Pending','Assistant Medical Officer of Health','NEWLICENSEREJECT','Assistant Medical Officer of Health Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Rejected','','SI Approval Pending','Sanitary Inspector','NEWLICENSE','Sanitary Inspector Approved','','Sanitary Supervisor,Assistant Medical Officer of Health,Municipal Health Officer,Chief Medical Officer of Health,Commissioner','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'all',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Inspector Approved','','Chief Medical Officer of Health Approval Pending','Chief Medical Officer of Health','NEWLICENSEREJECT','Chief Medical Officer of Health Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Chief Medical Officer of Health Rejected','','SI Approval Pending','Sanitary Inspector','NEWLICENSE','Sanitary Inspector Approved','','Sanitary Supervisor,Assistant Medical Officer of Health,Municipal Health Officer,Chief Medical Officer of Health,Commissioner','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'all',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','','Municipal Health Officer','NEWLICENSEREJECT','Municipal Health Officer Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','','Chief Medical Officer of Health','NEWLICENSEREJECT','Chief Medical Officer of Health Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','','Commissioner','NEWLICENSEREJECT','Commissioner Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Municipal Health Officer Approved','','','Chief Medical Officer of Health','NEWLICENSEREJECT','Chief Medical Officer of Health Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Chief Medical Officer of Health Approved','','','Commissioner','NEWLICENSEREJECT','Commissioner Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Assistant Medical Officer of Health Approved','','Second Level Collection Pending','Assistant Medical Officer of Health','NEWLICENSEREJECT','Assistant Medical Officer of Health Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Chief Medical Officer of Health Approved','','Second Level Collection Pending','Chief Medical Officer of Health','NEWLICENSEREJECT','Chief Medical Officer of Health Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,null);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Municipal Health Officer Approval Pending','Municipal Health Officer','NEWLICENSEREJECT','Municipal Health Officer Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,true);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Assistant Medical Officer of Health Approval Pending','Assistant Medical Officer of Health','NEWLICENSEREJECT','Assistant Medical Officer of Health Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,true);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Chief Medical Officer of Health Approval Pending','Chief Medical Officer of Health','NEWLICENSEREJECT','Chief Medical Officer of Health Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,true);
Insert into eg_wf_matrix values(nextval('seq_eg_wf_matrix'),'ANY','TradeLicense','Sanitary Supervisor Verified','','Commissioner Approval Pending','Commissioner','NEWLICENSEREJECT','Commissioner Rejected','SI Approval Pending','Sanitary Inspector','','Forward,Reject',null,null,'2015-04-01','2099-04-01',0,'tradeArea_weight,parentBoundary,boundary',true,false,null,true);

-------save license action and roleaction

INSERT INTO EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) 
values (NEXTVAL('SEQ_EG_ACTION'),'savetradelicense','/newtradelicense/newTradeLicense-save',null,(select id from EG_MODULE where name = 'Trade License Transactions'),1,'savetradelicense',FALSE, 'tl',0,1,now(),1,now(),(SELECT id FROM eg_module WHERE name = 'Trade License' AND parentmodule IS NULL));

INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) VALUES ((SELECT id FROM eg_role WHERE name LIKE 'TLCreator'), (SELECT id FROM eg_action WHERE name ='savetradelicense'));

INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) VALUES ((SELECT id FROM eg_role WHERE name LIKE 'TLApprover'), (SELECT id FROM eg_action WHERE name ='savetradelicense'));
