ALTER TABLE EGTL_LICENSE DROP COLUMN DOC_IMAGE_NUMBER, DROP COLUMN POWER_OF_ATTORNEY, DROP COLUMN COMPANY_PAN_NUMBER;
ALTER TABLE EGTL_LICENSE DROP COLUMN VAT_NUMBER, DROP COLUMN MIN_SOLVENCY, DROP COLUMN AVG_ANNUAL_TURNOVER;
ALTER TABLE EGTL_LICENSE DROP COLUMN BANK_IFSC_CODE, DROP COLUMN FEE_EXEMPTION;
ALTER TABLE EGTL_LICENSE DROP COLUMN OFFICE_EMAILID, DROP COLUMN PROPERTY_NO, DROP COLUMN filestoreid;
ALTER TABLE EGTL_LICENSE DROP COLUMN SERVICE_TAX_NUM,DROP COLUMN TIN_NUM,DROP COLUMN NOOFROOMS;
ALTER TABLE EGTL_LICENSE DROP COLUMN PHONENUMBER,DROP COLUMN COMPANY_DETAIL,DROP COLUMN rentalAgreement;
ALTER TABLE EGTL_LICENSE DROP COLUMN RENT_PAID,DROP COLUMN FEETYPETEXT,DROP COLUMN CHECKLIST;
DROP  TABLE EGTL_STATUS_VALUES CASCADE;
DROP SEQUENCE seq_egtl_status_values;
ALTER TABLE EGTL_LICENSE_AUD DROP COLUMN PHONENUMBER;
ALTER TABLE EGTL_TRADE_LICENSE DROP COLUMN SAND_BUCKETS,DROP COLUMN WATER_BUCKETS,DROP COLUMN DCP_EXTINGUISHER;
ALTER TABLE EGTL_TRADE_LICENSE DROP COLUMN NOC_NUMBER,DROP COLUMN ISCERTIFICATEGENERATED,DROP COLUMN total_hp;
ALTER TABLE EGTL_TRADE_LICENSE DROP COLUMN ismotorinstalled;
ALTER TABLE EGTL_LICENSEE DROP COLUMN NATIONALITY,DROP COLUMN QUALIFICATION,DROP COLUMN AGE,DROP COLUMN GENDER;
ALTER TABLE EGTL_LICENSEE DROP COLUMN PAN_NUM,DROP COLUMN ID_ADM_BNDRY,DROP COLUMN PHONENUMBER;
DROP TABLE EGTL_LICENSEOBJECTION_DOCS CASCADE;
DROP TABLE EGTL_LICENSETRANSFER_DOCS CASCADE;
ALTER TABLE EGTL_MSTR_SUB_CATEGORY DROP COLUMN id_tl_dept, DROP COLUMN id_schedule, DROP COLUMN section_applicable;
ALTER TABLE EGTL_MSTR_SUB_CATEGORY DROP COLUMN pfa_applicable,DROP COLUMN fee_based_on, DROP COLUMN approval_required,DROP COLUMN noc_applicable;
DROP TABLE egtl_mstr_department CASCADE;
DROP SEQUENCE seq_egtl_mstr_department;
ALTER TABLE EGTL_LICENSE ADD COLUMN DigiSignedCertFileStoreId varchar(40);



