DROP TABLE EGTL_ACTIVITY CASCADE;
DROP SEQUENCE SEQ_EGTL_ACTIVITY;
DROP TABLE EGTL_OBJECTION CASCADE;
DROP SEQUENCE SEQ_EGTL_OBJECTION;
ALTER TABLE EGTL_TRADE_LICENSE DROP COLUMN HOTEL_GRADE;
DROP TABLE EGTL_LICENSETRANSFER CASCADE;
DROP SEQUENCE SEQ_EGTL_LICENSETRANSFER;
DROP TABLE EGTL_MAJOR_WORKS CASCADE;
DROP SEQUENCE SEQ_EGTL_MAJOR_WORKS;
DROP TABLE EGTL_MOTOR_DETAILS CASCADE;
DROP SEQUENCE SEQ_EGTL_MOTOR_DETAILS;
DROP TABLE EGTL_MSTR_MOTOR_FEE_RANGE;
DROP SEQUENCE SEQ_EGTL_MSTR_MOTOR_FEE_RANGE;
DROP TABLE EGTL_NOTICE CASCADE;
DROP SEQUENCE SEQ_EGTL_NOTICE;
DROP TABLE EGTL_MSTR_SCHEDULE CASCADE;
DROP SEQUENCE SEQ_EGTL_MSTR_SCHEDULE;



