--Installment master 2020-21
INSERT INTO eg_installment_master (ID,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP, DESCRIPTION,INSTALLMENT_TYPE) SELECT nextval('SEQ_EG_INSTALLMENT_MASTER'), 202004, to_date('01-04-20','DD-MM-YY'),to_date('01-04-20','DD-MM-YY'),to_date('31-03-21','DD-MM-YY'), (select id from eg_module where name = 'Trade License' and parentmodule is null), current_timestamp,'TL/20-21','Yearly' WHERE NOT EXISTS (SELECT 1 FROM eg_installment_master WHERE INSTALLMENT_NUM=202004 and description='TL/20-21');

--Demand reason for 2020-21
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='License Fee'and module=(select id from eg_module where name='Trade License')), (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Trade License') and start_date = to_date('01/04/2020 00:00:00','dd/MM/yyyy HH24:MI:SS')), null, null, current_timestamp, current_timestamp, (select id from chartofaccounts  where glcode='1401101') WHERE NOT EXISTS (SELECT 1 FROM EG_DEMAND_REASON WHERE id_demand_reason_master=(select id from eg_demand_reason_master where reasonmaster='License Fee') and id_installment=(select id from eg_installment_master where id_module=(select id from eg_module where name ='Trade License' and parentmodule is null) and installment_num='202004' and description='TL/20-21'));

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Penalty' and module=(select id from eg_module where name='Trade License')), (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Trade License') and start_date = to_date('01/04/2020 00:00:00','dd/MM/yyyy HH24:MI:SS')), null, null, current_timestamp, current_timestamp, (select id from chartofaccounts  where glcode='1402015') WHERE NOT EXISTS (SELECT 1 FROM EG_DEMAND_REASON WHERE id_demand_reason_master=(select id from eg_demand_reason_master where reasonmaster='Penalty' and module=(select id from eg_module where name='Trade License' and parentmodule is null)) and id_installment=(select id from eg_installment_master where id_module=(select id from eg_module where name ='Trade License' and parentmodule is null) and installment_num='202004' and description='TL/20-21'));


--Installment master for 2021-22
INSERT INTO eg_installment_master (ID,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP, DESCRIPTION,INSTALLMENT_TYPE) SELECT nextval('SEQ_EG_INSTALLMENT_MASTER'), 202104, to_date('01-04-21','DD-MM-YY'),to_date('01-04-21','DD-MM-YY'),to_date('31-03-22','DD-MM-YY'), (select id from eg_module where name = 'Trade License' and parentmodule is null), current_timestamp,'TL/21-22','Yearly' WHERE NOT EXISTS (SELECT 1 FROM eg_installment_master WHERE INSTALLMENT_NUM=202104 and description='TL/21-22');

--Demand reason for 2021-22
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='License Fee'and module=(select id from eg_module where name='Trade License')), (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Trade License') and start_date = to_date('01/04/2021 00:00:00','dd/MM/yyyy HH24:MI:SS')), null, null, current_timestamp, current_timestamp, (select id from chartofaccounts  where glcode='1401101') WHERE NOT EXISTS (SELECT 1 FROM EG_DEMAND_REASON WHERE id_demand_reason_master=(select id from eg_demand_reason_master where reasonmaster='License Fee') and id_installment=(select id from eg_installment_master where id_module=(select id from eg_module where name ='Trade License' and parentmodule is null) and installment_num='202104' and description='TL/21-22'));

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Penalty' and module=(select id from eg_module where name='Trade License')), (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Trade License') and start_date = to_date('01/04/2021 00:00:00','dd/MM/yyyy HH24:MI:SS')), null, null, current_timestamp, current_timestamp, (select id from chartofaccounts  where glcode='1402015') WHERE NOT EXISTS (SELECT 1 FROM EG_DEMAND_REASON WHERE id_demand_reason_master=(select id from eg_demand_reason_master where reasonmaster='Penalty' and module=(select id from eg_module where name='Trade License' and parentmodule is null)) and id_installment=(select id from eg_installment_master where id_module=(select id from eg_module where name ='Trade License' and parentmodule is null) and installment_num='202104' and description='TL/21-22'));