CREATE TABLE EGTL_DEMAND_VOUCHER
(
  ID BIGINT NOT NULL,
  LICENSEDETAIL BIGINT NOT NULL,
  VOUCHERHEADER BIGINT NOT NULL,
  VERSION NUMERIC DEFAULT 0,
  CREATEDBY BIGINT NOT NULL,
  LASTMODIFIEDBY BIGINT NOT NULL,
  CREATEDDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT PK_EGTL_DEMAND_VOUCHER_ID PRIMARY KEY (ID),
  CONSTRAINT FK_EGTL_DEMAND_VOUCHER_CREATEDBY FOREIGN KEY (CREATEDBY) REFERENCES EG_USER (ID),
  CONSTRAINT FK_EGTL_DEMAND_VOUCHER_LASTMODIFIEDBY FOREIGN KEY (LASTMODIFIEDBY) REFERENCES EG_USER (ID),
  CONSTRAINT FK_EGTL_DEMAND_VOUCHER_LICDETAIL FOREIGN KEY (licensedetail) REFERENCES EGTL_LICENSE (ID)
);

CREATE INDEX idx_tl_demandvoucher_license ON EGTL_DEMAND_VOUCHER(licensedetail);
CREATE INDEX idx_tl_demandvoucher_voucherheader ON EGTL_DEMAND_VOUCHER(voucherheader);

COMMENT ON COLUMN EGTL_DEMAND_VOUCHER.licensedetail IS 'primary key of egtl_license';
COMMENT ON COLUMN EGTL_DEMAND_VOUCHER.voucherheader IS 'primary key of voucherheader';
COMMENT ON TABLE EGTL_DEMAND_VOUCHER IS 'This table stores link between Trade License details and voucherheader';

CREATE SEQUENCE SEQ_EGTL_DEMAND_VOUCHER;

