CREATE TABLE EGCL_SERVICEMODULE_MAPPING
(
	ID			BIGINT NOT NULL,
	ID_SERVICE_DETAILS	BIGINT NOT NULL,
	ID_MODULE		BIGINT NOT NULL,
	CREATED_BY		BIGINT NOT NULL,
	CREATED_DATE     	TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	MODIFIED_BY		BIGINT NOT NULL,
	MODIFIED_DATE		TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	CONSTRAINT FK_EGCL_SERVICEMODULE_MAP_SRVCDET FOREIGN KEY (ID_SERVICE_DETAILS) REFERENCES EGCL_SERVICEDETAILS (ID),
	CONSTRAINT FK_EGCL_SERVICEMODULE_MAP_MODULE FOREIGN KEY (ID_MODULE) REFERENCES EG_MODULE (ID),
	CONSTRAINT FK_EGCL_SERVICEMODULE_MAP_CREATEDBY FOREIGN KEY (CREATED_BY) REFERENCES EG_USER (ID),
	CONSTRAINT FK_EGCL_SERVICEMODULE_MAP_MODIFIEDBY FOREIGN KEY (MODIFIED_BY) REFERENCES EG_USER (ID)
);


CREATE SEQUENCE SEQ_EGCL_SERVICEMODULE_MAPPING;


