ALTER TABLE EG_COLLECTIONINDEX RENAME COLUMN payeename TO consumername;
ALTER TABLE EG_COLLECTIONINDEX RENAME COLUMN ulbname TO cityname;
ALTER TABLE EG_COLLECTIONINDEX ADD COLUMN citygrade character varying(50);
ALTER TABLE EG_COLLECTIONINDEX ADD COLUMN citycode character varying(10);
ALTER TABLE EG_COLLECTIONINDEX ADD COLUMN receiptcreator character varying(100);
