INSERT INTO eg_module(id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (nextval('SEQ_EG_MODULE'),'Bank Branch User Mapping',true,null,(select id from eg_module where name='Collection Master'),'Bank Branch User Mapping',1);

INSERT into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'BeforeCreateBankCollOpMap','/service/branchUserMap-newform.action',null,(select id from eg_module where name='Bank Branch User Mapping'),1,'Create Bank Branch To User Map',true,'collection',0,1,now(),1,now(),(select id from eg_module where name='Collection'));
INSERT into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'BankBranchUserAjaxBranch','/service/branchUserMap-bankBranchsByBankForReceiptPayments.action',null,(select id from eg_module where name='Bank Branch User Mapping'),1,'BankBranchUserAjaxBranch',false,'collection',0,1,now(),1,now(),(select id from eg_module where name='Collection'));
INSERT into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'BankBranchUserAction','/service/branchUserMap.action',null,(select id from eg_module where name='Bank Branch User Mapping'),1,'BankBranchUserAction',false,'collection',0,1,now(),1,now(),(select id from eg_module where name='Collection'));
INSERT into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'CreateBankCollOpMap','/service/branchUserMap-create.action',null,(select id from eg_module where name='Bank Branch User Mapping'),1,'CreateBankCollOpMap',false,'collection',0,1,now(),1,now(),(select id from eg_module where name='Collection'));

INSERT into eg_roleaction (roleid,actionid) values ((select id from eg_role where name='SYSTEM'),(select id from eg_action where name='BeforeCreateBankCollOpMap'));
INSERT into eg_roleaction (roleid,actionid) values ((select id from eg_role where name='SYSTEM'),(select id from eg_action where name='BankBranchUserAjaxBranch'));
INSERT into eg_roleaction (roleid,actionid) values ((select id from eg_role where name='SYSTEM'),(select id from eg_action where name='BankBranchUserAction'));
INSERT into eg_roleaction (roleid,actionid) values ((select id from eg_role where name='SYSTEM'),(select id from eg_action where name='CreateBankCollOpMap'));