INSERT INTO eg_role(id,name,description,createddate,createdby,lastmodifiedby,lastmodifieddate,version,internal) VALUES (nextval('seq_eg_role'),'COLLECTION_APPROVER','Approver role for counter collection workflow', now(), (SELECT id FROM eg_user WHERE lower(username)='system'), (SELECT id FROM eg_user WHERE lower(username)='system'), now(), 0, FALSE );

INSERT INTO eg_module (id,name,enabled,contextroot,parentmodule,displayname,ordernumber,rootmodule) VALUES (nextval('seq_eg_module'), 'ApproverToRemitterMapping', true, null, (SELECT id FROM eg_module WHERE name = 'Collection Master'), 'Approver to Remitter Mapping', 2, null);
INSERT INTO eg_action (id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) VALUES ( nextval('seq_eg_action'), 'ApproverRemitterCreate', '/receipts/approverRemitterMapping/create', (SELECT id FROM eg_module WHERE name = 'ApproverToRemitterMapping'), 1, 'Create Approver Remitter Mapping', TRUE, 'collection', 0, (SELECT id FROM eg_user WHERE lower(username)='system'), now(), (SELECT id FROM eg_user WHERE lower(username)='system'), now(), (SELECT id FROM eg_module WHERE name = 'Collection'));
INSERT INTO eg_action (id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) VALUES ( nextval('seq_eg_action'), 'ApproverRemitterView', '/receipts/approverRemitterMapping/view', (SELECT id FROM eg_module WHERE name = 'ApproverToRemitterMapping'), 3,'View Approver Remitter Mapping', TRUE,'collection', 0, (SELECT id FROM eg_user WHERE lower(username)='system'), now(), (SELECT id FROM eg_user WHERE lower(username)='system'), now(), (SELECT id FROM eg_module WHERE name = 'Collection'));
INSERT INTO eg_action (id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) VALUES ( nextval('seq_eg_action'), 'ApproverRemitterModify', '/receipts/approverRemitterMapping/modify', (SELECT id FROM eg_module WHERE name = 'ApproverToRemitterMapping'), 2,'Modify Approver Remitter Mapping', TRUE,'collection', 0, (SELECT id FROM eg_user WHERE lower(username)='system'), now(), (SELECT id FROM eg_user WHERE lower(username)='system'), now(), (SELECT id FROM eg_module WHERE name = 'Collection'));
INSERT INTO eg_action (id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) VALUES ( nextval('seq_eg_action'), 'ApproverRemitterEdit', '/receipts/approverRemitterMapping/edit', (SELECT id FROM eg_module WHERE name = 'ApproverToRemitterMapping'), 3,'Edit Approver Remitter Mapping', FALSE,'collection', 0, (SELECT id FROM eg_user WHERE lower(username)='system'), now(), (SELECT id FROM eg_user WHERE lower(username)='system'), now(), (SELECT id FROM eg_module WHERE name = 'Collection') );
INSERT INTO eg_action (id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) VALUES ( nextval('seq_eg_action'), 'ReceiptWorkflowAjax', '/receipts/workflowApproverAjax.action', (SELECT id FROM eg_module WHERE name = 'Receipt Services'), 0,'ReceiptWorkflowAjax', FALSE,'collection', 0, (SELECT id FROM eg_user WHERE lower(username)='system'), now(), (SELECT id FROM eg_user WHERE lower(username)='system'), now(), (SELECT id FROM eg_module WHERE name = 'Collection'));

INSERT INTO eg_roleaction (roleid, actionid) SELECT r.id AS roleid, a.id AS actionid FROM eg_action a, eg_role r WHERE a.name IN ('ApproverRemitterCreate', 'ApproverRemitterView', 'ApproverRemitterModify', 'ApproverRemitterEdit') AND (r.name = 'SYSTEM');
INSERT INTO eg_roleaction (roleid, actionid) SELECT r.id AS roleid, a.id AS actionid FROM eg_action a, eg_role r WHERE a.name IN ('ApproverRemitterCreate', 'ApproverRemitterView', 'ApproverRemitterModify', 'ApproverRemitterEdit') AND (r.name = 'Coll_Master Access');
INSERT INTO eg_roleaction (roleid, actionid) SELECT r.id AS roleid, a.id AS actionid FROM eg_action a, eg_role r WHERE a.name IN ('ApproverRemitterView' ) AND (r.name = 'Coll_View Access');
INSERT INTO eg_roleaction (roleid, actionid) SELECT r.id AS roleid, a.id AS actionid FROM eg_action a, eg_role r WHERE a.name IN ('ListReceiptWorkFlowAction', 'GenerateCashReport', 'ListDetailAction', 'RejectReceiptCollection', 'GenerateChequeReport', 'CollectionsWorkflowReject', 'SubmitReceiptWorkFlowAction', 'ApproveReceiptCollection', 'CollectionsWorkflowApprove', 'CollectionsWorkflowApproveAll') AND r.name = 'COLLECTION_APPROVER';
INSERT INTO eg_roleaction (roleid, actionid) SELECT r.id AS roleid, a.id AS actionid FROM eg_action a, eg_role r WHERE a.name IN ('ReceiptWorkflowAjax') AND r.name <> 'Remitter' AND ( r.id IN (SELECT ra.roleid FROM eg_roleaction ra JOIN eg_action a ON ra.actionid = a.id  AND a.name = 'ListReceiptWorkFlowAction' ));

DELETE FROM eg_roleaction WHERE roleid = (SELECT id FROM eg_role WHERE name ='Remitter') AND actionid in (SELECT id FROM eg_action WHERE name in ('ListReceiptWorkFlowAction', 'GenerateCashReport', 'ListDetailAction', 'SubmitAllReceiptCollection', 'RejectReceiptCollection', 'SubmitReceiptCollection', 'GenerateChequeReport', 'CollectionsWorkflowReject', 'SubmitReceiptWorkFlowAction', 'ApproveReceiptCollection', 'CollectionsWorkflowApprove', 'CollectionsWorkflowApproveAll'));

INSERT INTO eg_appconfig (id,key_name,description,version,createdby,lastmodifiedby,createddate,lastmodifieddate, module) VALUES (nextval('seq_eg_appconfig'), 'COLLECTION_REMITTER_ROLE', 'Remitter role in cash/cheque collection workflow', 0, (select id from eg_user where UPPER(username)='SYSTEM'), (select id from eg_user where UPPER(username)='SYSTEM'), current_date, null, (select id from eg_module where UPPER(name) = 'COLLECTION' and enabled = true) );
INSERT INTO eg_appconfig_values (id, key_id,effective_from, value, createddate, createdby, version) VALUES (nextval('seq_eg_appconfig_values'), (select id from eg_appconfig where key_name = 'COLLECTION_REMITTER_ROLE'),current_timestamp, 'Remitter', current_date,(select id from eg_user where UPPER(username)='SYSTEM'),0);