CREATE TABLE EGCL_BRANCHUSER_MAP
(id bigint NOT NULL,
bankbranch bigint NOT NULL,
bankuser bigint NOT NULL,
isactive boolean default true,
CREATEDBY bigint NOT NULL,
CREATED_DATE timestamp without time zone NOT NULL,
MODIFIEDBY bigint,
MODIFIED_DATE timestamp without time zone,
version numeric DEFAULT 0,
CONSTRAINT PK_EGCL_BRANCHUSER_MAP_ID PRIMARY KEY(id),
CONSTRAINT FK_EGCL_BRANCHUSER_MAP_MFDBY FOREIGN KEY (MODIFIEDBY)
         REFERENCES EG_USER (ID),
CONSTRAINT FK_EGCL_BRANCHUSER_MAP_CRTBY FOREIGN KEY (CREATEDBY)
         REFERENCES EG_USER (ID),
CONSTRAINT FK_EGCL_BRANCHUSER_MAP_BANKBRANCH FOREIGN KEY (bankbranch)
         REFERENCES BANKBRANCH (ID),  
CONSTRAINT FK_EGCL_BRANCHUSER_MAP_BANKUSER FOREIGN KEY (bankuser)
         REFERENCES EG_USER (ID)         
);

create SEQUENCE SEQ_EGCL_BRANCHUSER_MAP;


ALTER table EGCL_COLLECTIONMIS drop column depositedInBank;
ALTER table EGCL_COLLECTIONMIS add column depositedBranch bigint;
ALTER table EGCL_COLLECTIONMIS add CONSTRAINT fk_collmis_bankbranch FOREIGN KEY (depositedBranch) REFERENCES Bankbranch (id);