-----------------START--------------------
INSERT INTO eg_module(id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (nextval('SEQ_EG_MODULE'), 'Water Tax Management', true, 'wtms', null, 'Water Tax Management', (select max(ordernumber)+1 from eg_module where parentmodule is null));
INSERT INTO eg_module(id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (nextval('SEQ_EG_MODULE'), 'WaterTaxMasters', false, null, (select id from eg_module where name='Water Tax Management'), 'Masters', 1);
INSERT INTO eg_module(id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (nextval('SEQ_EG_MODULE'), 'WaterTaxTransactions', true, null, (select id from eg_module where name='Water Tax Management'), 'Transactions', 2);
INSERT INTO eg_module(id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (nextval('SEQ_EG_MODULE'), 'WaterTaxReports', false, null, (select id from eg_module where name='Water Tax Management'), 'Reports', 3);
------------------END---------------------
-----------------START--------------------
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxCreateNewConnectionNewForm','/application/newConnection-newform',null,(select id from eg_module where name='WaterTaxTransactions'),1,'New Water Tap Connection','true','wtms',0,1,to_timestamp('2015-08-15 11:02:43.968604','null'),1,to_timestamp('2015-08-15 11:02:43.968604','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxCreateNewConnection','/application/newConnection-create',null,(select id from eg_module where name='WaterTaxTransactions'),1,'WaterTaxCreateNewConnection','false','wtms',0,1,to_timestamp('2015-08-15 11:02:46.030564','null'),1,to_timestamp('2015-08-15 11:02:46.030564','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'View Water Connection','/application/view/',null,(select id from eg_module where name='WaterTaxTransactions'),null,'View Water Connection','false','wtms',0,1,to_timestamp('2015-08-15 11:02:48.457381','null'),1,to_timestamp('2015-08-15 11:02:48.457381','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'ElasiticapplicationSearch','/elastic/appSearch/',null,(select id from eg_module where name='WaterTaxTransactions'),null,'Search Application','true','wtms',0,1,to_timestamp('2015-08-15 11:02:49.518827','null'),1,to_timestamp('2015-08-15 11:02:49.518827','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'AjaxDesignationsByDepartment','/ajaxWorkFlow-getDesignationsByObjectType',null,(select id from eg_module where name='WaterTaxTransactions'),1,'Approver Designations by Department','false','wtms',0,1,to_timestamp('2015-08-15 11:04:03.817729','null'),1,to_timestamp('2015-08-15 11:04:03.817729','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'AjaxApproverByDesignationAndDepartment','/ajaxWorkFlow-positionsByDepartmentAndDesignation',null,(select id from eg_module where name='WaterTaxTransactions'),1,'Approver By Designation and Department','false','wtms',0,1,to_timestamp('2015-08-15 11:04:03.817729','null'),1,to_timestamp('2015-08-15 11:04:03.817729','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'UpdateWaterConnectionApplication','/application/update/',null,(select id from eg_module where name='WaterTaxTransactions'),null,'Update Water Connection Application','false','wtms',0,1,to_timestamp('2015-08-15 11:04:04.11703','null'),1,to_timestamp('2015-08-15 11:04:04.11703','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'watertaxappsearch','/search/waterSearch/',null,(select id from eg_module where name='WaterTaxTransactions'),null,'Search Connection','true','wtms',0,1,to_timestamp('2015-08-15 11:04:14.873066','null'),1,to_timestamp('2015-08-15 11:04:14.873066','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'Addtional Water Connection','/application/addconnection/',null,(select id from eg_module where name='WaterTaxTransactions'),null,'Addtional Water Connection','false','wtms',0,1,to_timestamp('2015-08-15 11:04:19.854078','null'),1,to_timestamp('2015-08-15 11:04:19.854078','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxAddConnection','/application/addConnection-create',null,(select id from eg_module where name='WaterTaxTransactions'),null,'WaterTaxAddConnection','false','wtms',0,1,to_timestamp('2015-08-15 11:04:19.854078','null'),1,to_timestamp('2015-08-15 11:04:19.854078','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxChangeOfUseApplication','/application/changeOfUse/',null,(select id from eg_module where name='WaterTaxTransactions'),1,'Change Of Use','false','wtms',0,1,to_timestamp('2015-08-15 11:04:22.551016','null'),1,to_timestamp('2015-08-15 11:04:22.551016','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxCreateChangeOfUseApplication','/application/changeOfUse-create',null,(select id from eg_module where name='WaterTaxTransactions'),1,'Create Change Of Use','false','wtms',0,1,to_timestamp('2015-08-15 11:04:22.551016','null'),1,to_timestamp('2015-08-15 11:04:22.551016','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxCollectionView','/application/generatebill',null,(select id from eg_module where name='WaterTaxTransactions'),null,'WaterTaxCollectionView','false','wtms',0,1,to_timestamp('2015-08-15 11:04:22.606759','null'),1,to_timestamp('2015-08-15 11:04:22.606759','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxAjaxCheckPrimaryConnection','/ajaxconnection/check-primaryconnection-exists',null,(select id from eg_module where name='WaterTaxTransactions'),1,'WaterTaxAjaxCheckPrimaryConnection','false','wtms',0,1,to_timestamp('2015-08-15 11:04:24.597(select id from eg_module where name='WaterTaxMasters')','null'),1,to_timestamp('2015-08-15 11:04:24.597(select id from eg_module where name='WaterTaxMasters')','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'connectiontypesajax','/ajax-connectionTypes',null,(select id from eg_module where name='Water Tax Management'),null,'connectiontypesajax','false','wtms',0,1,to_timestamp('2015-08-15 11:04:25.548004','null'),1,to_timestamp('2015-08-15 11:04:25.548004','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'workorderreportview','/application/workorder/view',null,(select id from eg_module where name='WaterTaxTransactions'),null,'workorderreportview','false','wtms',0,1,to_timestamp('2015-08-15 11:04:27.524838','null'),1,to_timestamp('2015-08-15 11:04:27.524838','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'workorderreport','/application/workorder',null,(select id from eg_module where name='WaterTaxTransactions'),null,'workorderreport','false','wtms',0,1,to_timestamp('2015-08-15 11:04:27.524838','null'),1,to_timestamp('2015-08-15 11:04:27.524838','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxConnectionDataEntry','/application/newConnection-dataEntryForm.action',null,(select id from eg_module where name='WaterTaxTransactions'),2,'Data Entry Screen','true','wtms',0,1,to_timestamp('2015-08-15 11:04:27.770298','null'),1,to_timestamp('2015-08-15 11:04:27.770298','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'categorytypebypropertytypeajax','/ajax-CategoryTypeByPropertyType',null,(select id from eg_module where name='Water Tax Management'),null,'populatingcategorytypebasingonpropertytype','false','wtms',0,1,to_timestamp('2015-08-15 11:04:28.831251','null'),1,to_timestamp('2015-08-15 11:04:28.831251','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'usagetypebypropertytypeajax','/ajax-UsageTypeByPropertyType',null,(select id from eg_module where name='Water Tax Management'),null,'populatingusagetypebasingonpropertytype','false','wtms',0,1,to_timestamp('2015-08-15 11:04:28.831251','null'),1,to_timestamp('2015-08-15 11:04:28.831251','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'pipesizesbypropertytypeajax','/ajax-PipeSizesByPropertyType',null,(select id from eg_module where name='Water Tax Management'),null,'populatingpipesizesbasingonpropertytype','false','wtms',0,1,to_timestamp('2015-08-15 11:04:28.831251','null'),1,to_timestamp('2015-08-15 11:04:28.831251','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'meter Entry screen','/application/meterentry/',null,(select id from eg_module where name='Water Tax Management'),null,'meter Entry screen','false','wtms',0,1,to_timestamp('2015-08-19 10:45:49.032969','null'),1,to_timestamp('2015-08-19 10:45:49.032969','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxConnectionDataEntry-message','/application/newConnection-existingMessage',null,(select id from eg_module where name='WaterTaxTransactions'),2,'WaterTaxConnectionDataEntry-message','false','wtms',0,1,to_timestamp('2015-08-19 10:45:49.578055','null'),1,to_timestamp('2015-08-19 10:45:49.578055','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'watertaxestimationnotice','/application/estimationNotice',null,(select id from eg_module where name='WaterTaxTransactions'),null,'watertaxestimationnotice','false','wtms',0,1,to_timestamp('2015-08-19 10:45:50.991631','null'),1,to_timestamp('2015-08-19 10:45:50.991631','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'watertaxestimationnoticeview','/application/estimationNotice/view/',null,(select id from eg_module where name='WaterTaxTransactions'),null,'watertaxestimationnoticeview','false','wtms',0,1,to_timestamp('2015-08-19 10:45:50.991631','null'),1,to_timestamp('2015-08-19 10:45:50.991631','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxConnectionDataEntry-edit','/application/newConnection-editExisting',null,(select id from eg_module where name='WaterTaxTransactions'),2,'WaterTaxConnectionDataEntry-edit','false','wtms',0,1,to_timestamp('2015-08-19 10:45:51.224841','null'),1,to_timestamp('2015-08-19 10:45:51.224841','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxDCBReportZoneWise','/reports/dCBReport/zoneWise',null,(select id from eg_module where name='WaterTaxReports'),1,'DCB Report Zone Wise','true','wtms',0,1,to_timestamp('2015-08-19 17:14:12.454451','null'),1,to_timestamp('2015-08-19 17:14:12.454451','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'DCBReportList','/reports/dCBReportList',null,(select id from eg_module where name='WaterTaxReports'),null,'DCB Report List','false','wtms',0,1,to_timestamp('2015-08-19 17:14:12.454451','null'),1,to_timestamp('2015-08-19 17:14:12.454451','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'meter Demand Notice generate screen','/application/meterdemandnotice',null,(select id from eg_module where name='Water Tax Management'),null,'meter Demand Notice generate screen','false','wtms',0,1,to_timestamp('2015-08-22 15:02:28.978373','null'),1,to_timestamp('2015-08-22 15:02:28.978373','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'autopopulateApplicationType','/elastic/appSearch/ajax-moduleTypepopulate',null,(select id from eg_module where name='Water Tax Management'),null,'autopopulateApplicationType','false','wtms',0,1,to_timestamp('2015-08-22 15:02:30.581478','null'),1,to_timestamp('2015-08-22 15:02:30.581478','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxDCBReportWardWise','/reports/dCBReport/wardWise',null,(select id from eg_module where name='WaterTaxReports'),2,'DCB Report Ward Wise','true','wtms',0,1,to_timestamp('2015-08-22 15:02:30.793522','null'),1,to_timestamp('2015-08-22 15:02:30.793522','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxDCBReportBlockWise','/reports/dCBReport/blockWise',null,(select id from eg_module where name='WaterTaxReports'),3,'DCB Report Block Wise','true','wtms',0,1,to_timestamp('2015-08-22 15:02:30.793522','null'),1,to_timestamp('2015-08-22 15:02:30.793522','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'WaterTaxDCBReportLocalityWise','/reports/dCBReport/localityWise',null,(select id from eg_module where name='WaterTaxReports'),4,'DCB Report Locality Wise','true','wtms',0,1,to_timestamp('2015-08-24 11:11:30.249443','null'),1,to_timestamp('2015-08-24 11:11:30.249443','null'),(select id from eg_module where name='Water Tax Management'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'ChairPersonDetailsScreen','/application/chairPersonDetails.action',null,(select id from eg_module where name='WaterTaxMasters'),1,'Create Chair Person','true','wtms',0,1,to_timestamp('2015-08-31 13:33:48.231263','null'),1,to_timestamp('2015-08-31 13:33:48.231263','null'),(select id from eg_module where name='WaterTaxMasters'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'getchairpersonname-ajax','/application/ajax-chairPersonName',null,(select id from eg_module where name='WaterTaxMasters'),null,'getchairpersonname','false','wtms',0,1,to_timestamp('2015-08-31 13:33:48.231263','null'),1,to_timestamp('2015-08-31 13:33:48.231263','null'),(select id from eg_module where name='WaterTaxMasters'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'getchairpersontableajax','/application/ajax-chairpersontable',null,(select id from eg_module where name='WaterTaxMasters'),null,'getchairpersontable','false','wtms',0,1,to_timestamp('2015-08-31 13:33:48.231263','null'),1,to_timestamp('2015-08-31 13:33:48.231263','null'),(select id from eg_module where name='WaterTaxMasters'));
Insert into EG_ACTION (id,name,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate,lastmodifiedby,lastmodifieddate,application) values (nextval('SEQ_EG_ACTION'),'ajaxForExistredMeterReading','/ajax-meterReadingEntryExist',null,(select id from eg_module where name='WaterTaxTransactions'),4,'ajaxForExistredMeterReading','false','wtms',0,1,to_timestamp('2015-09-15 10:44:14.929994','null'),1,to_timestamp('2015-09-15 10:44:14.929994','null'),(select id from eg_module where name='Water Tax Management'));
------------------END---------------------
-----------------START--------------------
INSERT INTO eg_role(id, name, description, createddate, createdby, lastmodifiedby, lastmodifieddate, version) VALUES (nextval('seq_eg_role'), 'Water Tax Approver', 'Water Tax Approver', now(), 1, 1, now(), 0);
INSERT INTO eg_role(id, name, description, createddate, createdby, lastmodifiedby, lastmodifieddate, version) VALUES (nextval('seq_eg_role'), 'Water Tax Report Viewer', 'Report Viewer for Water Tax', now(), 1, 1, now(), 0);
------------------END---------------------
-----------------START--------------------
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxCreateNewConnectionNewForm'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='WaterTaxCreateNewConnectionNewForm'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='WaterTaxCreateNewConnectionNewForm'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='WaterTaxCreateNewConnection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='WaterTaxCreateNewConnection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxCreateNewConnection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Approver'),(select id from eg_action where name='View Water Connection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='View Water Connection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='View Water Connection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='View Water Connection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='ElasiticapplicationSearch'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='ElasiticapplicationSearch'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='ElasiticapplicationSearch'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='AjaxDesignationsByDepartment'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='AjaxDesignationsByDepartment'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Approver'),(select id from eg_action where name='AjaxDesignationsByDepartment'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='AjaxApproverByDesignationAndDepartment'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='AjaxApproverByDesignationAndDepartment'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Approver'),(select id from eg_action where name='AjaxApproverByDesignationAndDepartment'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Approver'),(select id from eg_action where name='UpdateWaterConnectionApplication'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='UpdateWaterConnectionApplication'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Property Administrator'),(select id from eg_action where name='UpdateWaterConnectionApplication'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='UpdateWaterConnectionApplication'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='watertaxappsearch'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='watertaxappsearch'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='watertaxappsearch'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='watertaxappsearch'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Approver'),(select id from eg_action where name='watertaxappsearch'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='Addtional Water Connection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='Addtional Water Connection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='Addtional Water Connection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxAddConnection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='WaterTaxAddConnection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='WaterTaxChangeOfUseApplication'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxChangeOfUseApplication'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='WaterTaxChangeOfUseApplication'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='WaterTaxCreateChangeOfUseApplication'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxCreateChangeOfUseApplication'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='WaterTaxCreateChangeOfUseApplication'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='WaterTaxCollectionView'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Approver'),(select id from eg_action where name='WaterTaxCollectionView'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxCollectionView'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='WaterTaxCollectionView'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='WaterTaxAjaxCheckPrimaryConnection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxAjaxCheckPrimaryConnection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='WaterTaxAjaxCheckPrimaryConnection'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='connectiontypesajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='connectiontypesajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='connectiontypesajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='connectiontypesajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='workorderreportview'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='workorderreportview'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='workorderreportview'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='workorderreport'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='workorderreport'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Approver'),(select id from eg_action where name='workorderreport'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='WaterTaxConnectionDataEntry'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxConnectionDataEntry'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='categorytypebypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Approver'),(select id from eg_action where name='categorytypebypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='categorytypebypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='categorytypebypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='usagetypebypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='usagetypebypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='usagetypebypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Approver'),(select id from eg_action where name='usagetypebypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Approver'),(select id from eg_action where name='pipesizesbypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='pipesizesbypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='pipesizesbypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='pipesizesbypropertytypeajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='meter Entry screen'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='meter Entry screen'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='meter Entry screen'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='WaterTaxConnectionDataEntry-message'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxConnectionDataEntry-message'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='watertaxestimationnotice'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='watertaxestimationnotice'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='watertaxestimationnoticeview'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='watertaxestimationnoticeview'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Approver'),(select id from eg_action where name='watertaxestimationnoticeview'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='watertaxestimationnoticeview'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxConnectionDataEntry-edit'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='WaterTaxConnectionDataEntry-edit'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Report Viewer'),(select id from eg_action where name='WaterTaxDCBReportZoneWise'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxDCBReportZoneWise'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Report Viewer'),(select id from eg_action where name='DCBReportList'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='DCBReportList'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='meter Demand Notice generate screen'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='meter Demand Notice generate screen'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='meter Demand Notice generate screen'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='autopopulateApplicationType'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='CSC Operator'),(select id from eg_action where name='autopopulateApplicationType'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='autopopulateApplicationType'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxDCBReportWardWise'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Report Viewer'),(select id from eg_action where name='WaterTaxDCBReportWardWise'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxDCBReportBlockWise'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Report Viewer'),(select id from eg_action where name='WaterTaxDCBReportBlockWise'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='WaterTaxDCBReportLocalityWise'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Water Tax Report Viewer'),(select id from eg_action where name='WaterTaxDCBReportLocalityWise'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Property Administrator'),(select id from eg_action where name='ChairPersonDetailsScreen'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Property Administrator'),(select id from eg_action where name='getchairpersonname-ajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Property Administrator'),(select id from eg_action where name='getchairpersontableajax'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='Super User'),(select id from eg_action where name='ajaxForExistredMeterReading'));
Insert into EXPORT_TABLE (roleid,actionid) values ((select id from eg_role where name='ULB Operator'),(select id from eg_action where name='ajaxForExistredMeterReading'));
------------------END---------------------
-----------------START--------------------
Insert into eg_appconfig (id,key_name,description,version,createdby,lastmodifiedby,createddate,lastmodifieddate,module) values (nextval('SEQ_EG_APPCONFIG_VALUES'),'SENDSMSFORWATERTAX','SMS Notification for Water Tax module is enabled or not',0,null,null,null,null,(select id from eg_module where name='Water Tax Management'));
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='SENDSMSFORWATERTAX'), current_date, 'YES',0);
Insert into eg_appconfig (id,key_name,description,version,createdby,lastmodifiedby,createddate,lastmodifieddate,module) values (nextval('SEQ_EG_APPCONFIG_VALUES'),'SENDEMAILFORWATERTAX','Email Notification for Water Tax module is enabled or not',0,null,null,null,null,(select id from eg_module where name='Water Tax Management'));
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='SENDEMAILFORWATERTAX'), current_date, 'YES',0);
Insert into eg_appconfig (id,key_name,description,version,createdby,lastmodifiedby,createddate,lastmodifieddate,module) values (nextval('SEQ_EG_APPCONFIG_VALUES'),'MULTIPLENEWCONNECTIONFORPID','To restrict whether multiple new water tap connection allowed for single Property ID',0,null,null,null,null,(select id from eg_module where name='Water Tax Management'));
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='MULTIPLENEWCONNECTIONFORPID'), current_date, 'NO',0);
Insert into eg_appconfig (id,key_name,description,version,createdby,lastmodifiedby,createddate,lastmodifieddate,module) values (nextval('SEQ_EG_APPCONFIG_VALUES'),'NEWCONNECTIONALLOWEDIFPTDUE','To check whether New water tap connection application allowed if PT Tax due present',0,null,null,null,null,(select id from eg_module where name='Water Tax Management'));
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='NEWCONNECTIONALLOWEDIFPTDUE'), current_date, 'NO',0);
Insert into eg_appconfig (id,key_name,description,version,createdby,lastmodifiedby,createddate,lastmodifieddate,module) values (nextval('SEQ_EG_APPCONFIG_VALUES'),'DOCUMENTREQUIREDFORBPL','The document which is mandatory to get water tap connection for BPL category',0,null,null,null,null,(select id from eg_module where name='Water Tax Management'));
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='DOCUMENTREQUIREDFORBPL'), current_date, 'Ration Card',0);
Insert into eg_appconfig (id,key_name,description,version,createdby,lastmodifiedby,createddate,lastmodifieddate,module) values (nextval('SEQ_EG_APPCONFIG_VALUES'),'CLERKDESIGNATIONFORCSCOPERATOR','Department for Workflow',0,null,null,null,null,(select id from eg_module where name='Water Tax Management'));
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='CLERKDESIGNATIONFORCSCOPERATOR'), current_date, 'Revenue Clerk',0);
Insert into eg_appconfig (id,key_name,description,version,createdby,lastmodifiedby,createddate,lastmodifieddate,module) values (nextval('SEQ_EG_APPCONFIG_VALUES'),'DEPARTMENTFORWORKFLOW','Department for Workflow',0,null,null,null,null,(select id from eg_module where name='Water Tax Management'));
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='DEPARTMENTFORWORKFLOW'), current_date, 'Revenue',0);
Insert into eg_appconfig (id,key_name,description,version,createdby,lastmodifiedby,createddate,lastmodifieddate,module) values (nextval('SEQ_EG_APPCONFIG_VALUES'),'ROLEFORNONEMPLOYEEINWATERTAX','roles to create waterTax application ',0,null,null,null,null,(select id from eg_module where name='Water Tax Management'));
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='SENDEMAILFORWATERTAX'), current_date, 'CSC Operator',0);
Insert into eg_appconfig (id,key_name,description,version,createdby,lastmodifiedby,createddate,lastmodifieddate,module) values (nextval('SEQ_EG_APPCONFIG_VALUES'),'ADDCONNECTIONALLOWEDIFWTDUE','To restrict whether multiple additional water tap connection allowed for single Property ID',0,null,null,null,null,(select id from eg_module where name='Water Tax Management'));
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='ADDCONNECTIONALLOWEDIFWTDUE'), current_date, 'NO',0);
Insert into eg_appconfig (id,key_name,description,version,createdby,lastmodifiedby,createddate,lastmodifieddate,module) values (310,'RolesForSearchWAterTaxConnection','Roles To Show Action dropdown In search connection',0,null,null,null,null,(select id from eg_module where name='Water Tax Management'));
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='RolesForSearchWAterTaxConnection'), current_date, 'Operator',0);
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='RolesForSearchWAterTaxConnection'), current_date, 'Water Tax Approver',0);
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='RolesForSearchWAterTaxConnection'), current_date, 'Super User',0);
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='RolesForSearchWAterTaxConnection'), current_date, 'CSC Operator',0);
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='RolesForSearchWAterTaxConnection'), current_date, 'ULB Operator',0);
------------------END---------------------
-----------------START--------------------
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 2015, '2015-04-01 00:00:00', '2015-04-01 00:00:00', '2016-03-31 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:44:03.289636', '2015-16', 'Yearly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 42015, '2015-04-01 00:00:00', '2015-04-01 00:00:00', '2015-04-30 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-I/15-16', 'Monthly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 52015, '2015-05-01 00:00:00', '2015-05-01 00:00:00', '2015-05-31 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-II/15-16', 'Monthly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 62015, '2015-06-01 00:00:00', '2015-06-01 00:00:00', '2015-06-30 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-III/15-16', 'Monthly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 72015, '2015-07-01 00:00:00', '2015-07-01 00:00:00', '2015-07-31 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-IV/15-16', 'Monthly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 82015, '2015-08-01 00:00:00', '2015-08-01 00:00:00', '2015-08-31 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-V/15-16', 'Monthly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 92015, '2015-09-01 00:00:00', '2015-09-01 00:00:00', '2015-09-30 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-VI/15-16', 'Monthly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 102015, '2015-10-01 00:00:00', '2015-10-01 00:00:00', '2015-10-31 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-VII/15-16', 'Monthly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 112015, '2015-11-01 00:00:00', '2015-11-01 00:00:00', '2015-11-30 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-VIII/15-16', 'Monthly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 122015, '2015-12-01 00:00:00', '2015-12-01 00:00:00', '2015-12-31 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-IX/15-16', 'Monthly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 12015, '2016-01-01 00:00:00', '2016-01-01 00:00:00', '2016-01-31 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-X/15-16', 'Monthly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 22015, '2016-02-01 00:00:00', '2016-02-01 00:00:00', '2016-02-28 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-XI/15-16', 'Monthly');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 32015, '2016-03-01 00:00:00', '2016-03-01 00:00:00', '2016-03-31 00:00:00', (select id from eg_module where name='Water Tax Management'), '2015-08-28 10:45:34.63278', 'WT_MC-XII/15-16', 'Monthly');
------------------END---------------------
-----------------START-------------------
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Rejected', NULL, NULL, 'Revenue Clerk', 'NEWCONNECTION', 'Clerk approved', 'Asst.engineer approval pending', 'Assistant engineer', NULL, 'Forward,Reject', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'NEW', NULL, NULL, 'Revenue Clerk', 'NEWCONNECTION', 'Clerk approved', 'Asst.engineer approval pending', 'Assistant engineer', 'Clerk Approved', 'Forward', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Clerk approved', NULL, NULL, 'Assistant engineer', 'NEWCONNECTION', 'Asst engg approved', 'Estimation Notice print pending', 'Revenue Clerk', 'Assistant Engineer approved', 'Submit,Reject', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Payment done against Estimation', NULL, NULL, 'Commissioner', 'NEWCONNECTION', 'Commissioner Approved', 'Work order print pending', 'Revenue Clerk', 'workorder pending', 'Approve', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Work order generated', NULL, NULL, 'Assistant engineer', 'NEWCONNECTION', 'END', 'END', NULL, NULL, 'Tap Execution Date', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Commissioner Approved', NULL, NULL, 'Revenue Clerk', 'NEWCONNECTION', 'Work order generated', 'Tap execution pending', 'Assistant engineer', 'Metered connection entry', 'Generate WorkOrder', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Asst engg approved', NULL, NULL, 'Revenue Clerk', 'NEWCONNECTION', 'Estmate Notice Generated', 'Ready For Payment', 'Revenue Clerk', 'Ready for Payment', 'Generate Estimation Notice', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Created', NULL, NULL, NULL, 'NEWCONNECTION', 'NEW', 'Revenue Clerk approval pending', 'Revenue Clerk', 'Clerk Approved Pending', 'Forward', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'NEW', NULL, NULL, 'Revenue Clerk', 'ADDNLCONNECTION', 'Clerk approved', 'Asst.engineer approval pending', 'Assistant engineer', 'Clerk Approved', 'Forward', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Clerk approved', NULL, NULL, 'Assistant engineer', 'ADDNLCONNECTION', 'Asst engg approved', 'Estimation Notice print pending', 'Revenue Clerk', 'Assistant Engineer approved', 'Submit,Reject', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Payment done against Estimation', NULL, NULL, 'Commissioner', 'ADDNLCONNECTION', 'Commissioner Approved', 'Work order print pending', 'Revenue Clerk', 'workorder pending', 'Approve', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Commissioner Approved', NULL, NULL, 'Revenue Clerk', 'ADDNLCONNECTION', 'Work order generated', 'Tap execution pending', 'Assistant engineer', 'Metered connection entry', 'WorkOrder Generate', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Work order generated', NULL, NULL, 'Assistant engineer', 'ADDNLCONNECTION', 'END', 'END', NULL, NULL, 'Tap Execution Date', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'NEW', NULL, NULL, 'Revenue Clerk', 'CHANGEOFUSE', 'Clerk approved', 'Asst.engineer approval pending', 'Assistant engineer', 'Clerk Approved', 'Forward', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Clerk approved', NULL, NULL, 'Assistant engineer', 'CHANGEOFUSE', 'Asst engg approved', 'Estimation Notice print pending', 'Revenue Clerk', 'Assistant Engineer approved', 'Submit,Reject', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Payment done against Estimation', NULL, NULL, 'Commissioner', 'CHANGEOFUSE', 'Commissioner Approved', 'Work order print pending', 'Revenue Clerk', 'workorder pending', 'Approve', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Commissioner Approved', NULL, NULL, 'Revenue Clerk', 'CHANGEOFUSE', 'Work order generated', 'Tap execution pending', 'Assistant engineer', 'Metered connection entry', 'WorkOrder Generate', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Work order generated', NULL, NULL, 'Assistant engineer', 'CHANGEOFUSE', 'END', 'END', NULL, NULL, 'Tap Execution Date', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Asst engg approved', NULL, NULL, 'Revenue Clerk', 'ADDNLCONNECTION', 'Estmate Notice Generated', 'Ready For Payment', 'Revenue Clerk', 'Ready for Payment', 'Generate Estimation Notice', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Asst engg approved', NULL, NULL, 'Revenue Clerk', 'CHANGEOFUSE', 'Estmate Notice Generated', 'Ready For Payment', 'Revenue Clerk', 'Ready for Payment', 'Generate Estimation Notice', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Estmate Notice Generated', NULL, NULL, 'Revenue Clerk', 'NEWCONNECTION', 'Payment done against Estimation', 'Commissioner Approval pending', 'Commissioner', 'Payment against Estimation', 'Submit,Reject', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Estmate Notice Generated', NULL, NULL, 'Revenue Clerk', 'ADDNLCONNECTION', 'Payment done against Estimation', 'Commissioner Approval pending', 'Commissioner', 'Payment against Estimation', 'Submit,Reject', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Estmate Notice Generated', NULL, NULL, 'Revenue Clerk', 'CHANGEOFUSE', 'Payment done against Estimation', 'Commissioner Approval pending', 'Commissioner', 'Payment against Estimation', 'Submit,Reject', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Rejected', NULL, NULL, 'Revenue Clerk', 'ADDNLCONNECTION', 'Clerk approved', 'Asst.engineer approval pending', 'Assistant engineer', NULL, 'Forward,Reject', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Created', NULL, NULL, NULL, 'ADDNLCONNECTION', 'NEW', 'Revenue Clerk approval pending', 'Revenue Clerk', 'Clerk Approved Pending', 'Forward', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Rejected', NULL, NULL, 'Revenue Clerk', 'CHANGEOFUSE', 'Clerk approved', 'Asst.engineer approval pending', 'Assistant engineer', NULL, 'Forward,Reject', NULL, NULL, '2015-08-01', '2099-04-01');
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (nextval('eg_wf_matrix_seq'), 'ANY', 'WaterConnectionDetails', 'Created', NULL, NULL, NULL, 'CHANGEOFUSE', 'NEW', 'Revenue Clerk approval pending', 'Revenue Clerk', 'Clerk Approved Pending', 'Forward', NULL, NULL, '2015-08-01', '2099-04-01');
------------------END---------------------
-----------------START-------------------
INSERT INTO eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, renderyn, groupyn, typefqn, displayname, version) VALUES (nextval('seq_eg_wf_types'), 2, 'WaterConnectionDetails', '/wtms/application/update/:ID', 1, '2015-08-28 10:45:18.201078', 1, '2015-08-28 10:45:18.201078', 'Y', 'N', 'org.egov.wtms.application.entity.WaterConnectionDetails', 'Water Tap Connection', 0);
------------------END---------------------

