package org.egov.pims.empLeave.model;

// Generated Jul 9, 2007 3:21:09 PM by Hibernate Tools 3.2.0.b9


/**
 * LeavetypeDetails generated by hbm2java
 */
public class LeaveMaster implements java.io.Serializable
{

	private Integer id;
	private TypeOfLeaveMaster typeOfLeaveMstr;
	private org.egov.pims.commons.DesignationMaster desigId;
	private Integer noOfDays;

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public TypeOfLeaveMaster getTypeOfLeaveMstr()
	{
		return this.typeOfLeaveMstr;
	}
	public void setTypeOfLeaveMstr(
			TypeOfLeaveMaster typeOfLeaveMstr)
	{
		this.typeOfLeaveMstr = typeOfLeaveMstr;
	}
	public org.egov.pims.commons.DesignationMaster getDesigId() {
		return desigId;
	}
	public void setDesigId(org.egov.pims.commons.DesignationMaster desigId) {
		this.desigId = desigId;
	}
	public Integer getNoOfDays() {
		return noOfDays;
	}
	public void setNoOfDays(Integer noOfDays) {
		this.noOfDays = noOfDays;
	}

}
