package org.egov.pims.empLeave.model;

// Generated Jul 9, 2007 3:21:09 PM by Hibernate Tools 3.2.0.b9

import org.egov.commons.CFinancialYear;
import org.egov.pims.model.PersonalInformation;

/**
 * LeavetypeDetails generated by hbm2java
 */
public class LeaveOpeningBalance implements java.io.Serializable
{

	private Integer id;
	private TypeOfLeaveMaster typeOfLeaveMstr;
	private Float noOfLeavesAvai;
	private PersonalInformation employeeId;
	
	
	private CFinancialYear financialId;
	private CalendarYear calendarId;
	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public TypeOfLeaveMaster getTypeOfLeaveMstr()
	{
		return this.typeOfLeaveMstr;
	}
	public void setTypeOfLeaveMstr(
			TypeOfLeaveMaster typeOfLeaveMstr)
	{
		this.typeOfLeaveMstr = typeOfLeaveMstr;
	}
	
	
	public Float getNoOfLeavesAvai() {
		return noOfLeavesAvai;
	}
	public void setNoOfLeavesAvai(Float noOfLeavesAvai) {
		this.noOfLeavesAvai = noOfLeavesAvai;
	}
	
	public CFinancialYear getFinancialId() {
		return financialId;
	}
	public void setFinancialId(CFinancialYear financialId) {
		this.financialId = financialId;
	}
	public PersonalInformation getEmployeeId() {
		return employeeId;
	}
	public void setEmployeeId(PersonalInformation employeeId) {
		this.employeeId = employeeId;
	}
	public CalendarYear getCalendarId() {
		return calendarId;
	}
	public void setCalendarId(CalendarYear calendarId) {
		this.calendarId = calendarId;
	}
	
	
	
}
