CREATE SEQUENCE SEQ_EGPT_VACANCY_REMISSION_APPROVAL;

CREATE TABLE EGPT_VACANCY_REMISSION_APPROVAL
(
	ID			BIGINT NOT NULL,
	VACANCYREMISSION	BIGINT NOT NULL,
	CHECKINDATE		TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	COMMENTS		VARCHAR(1000) NOT NULL,
	STATE_ID		BIGINT,
	STATUS			VARCHAR(50),
	APPROVALDATE		TIMESTAMP WITHOUT TIME ZONE,
	ISAPPROVED 		boolean DEFAULT false,
	CREATEDBY		BIGINT NOT NULL,
	CREATEDDATE     	TIMESTAMP WITHOUT TIME ZONE       NOT NULL,
	LASTMODIFIEDDATE	TIMESTAMP WITHOUT TIME ZONE       NOT NULL,
	LASTMODIFIEDBY		BIGINT NOT NULL,
	VERSION 		BIGINT,
	CONSTRAINT PK_EGPT_VR_APPROVAL_ID PRIMARY KEY (ID ),
	CONSTRAINT FK_EGPT_VR_APPROVAL_VACANCYREMISSION_ID FOREIGN KEY (VACANCYREMISSION) REFERENCES EGPT_VACANCY_REMISSION (ID),
	CONSTRAINT FK_EGPT_VR_APPROVAL_STATE FOREIGN KEY (STATE_ID) REFERENCES EG_WF_STATES (ID),
	CONSTRAINT FK_EGPT_VR_APPROVAL_CREATEDBY FOREIGN KEY (CREATEDBY) REFERENCES EG_USER (ID),
	CONSTRAINT FK_EGPT_VR_APPROVAL_LASTMODIFIEDBY FOREIGN KEY (LASTMODIFIEDBY) REFERENCES EG_USER (ID)
);


