CREATE SEQUENCE SEQ_EGPT_GIS_DETAILS;

CREATE TABLE EGPT_GIS_DETAILS
(
	ID BIGINT NOT NULL, -- PRIMARY KEY
	GIS_PROPERTY BIGINT NOT NULL, -- GIS PROPERTY ID
	APPL_PROPERTY BIGINT NOT NULL, -- APPLICATION PROPERTY ID
	GIS_ZONE BIGINT, -- GIS ZONE ID
	APPL_ZONE BIGINT, -- APPLICATION ZONE ID
	GIS_TAX double precision,
	APPLICATION_TAX double precision,
	APPROVED_TAX double precision,
	SYSTEM_TAX double precision,
	CREATEDBY BIGINT NOT NULL,
	LASTMODIFIEDBY BIGINT NOT NULL,
	CREATEDDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	VERSION BIGINT,
	CONSTRAINT PK_EGPT_GIS_DETAILS_ID PRIMARY KEY (ID),
	CONSTRAINT FK_EGPT_GIS_DETAILS_CREATEDBY FOREIGN KEY (CREATEDBY) REFERENCES EG_USER (ID),
	CONSTRAINT FK_EGPT_GIS_DETAILS_LASTMODBY FOREIGN KEY (LASTMODIFIEDBY) REFERENCES EG_USER (ID),
	CONSTRAINT FK_EGPT_GIS_DETAILS_GISPROP FOREIGN KEY (GIS_PROPERTY) REFERENCES EGPT_PROPERTY (ID),
	CONSTRAINT FK_EGPT_GIS_DETAILS_APPLPROP FOREIGN KEY (APPL_PROPERTY) REFERENCES EGPT_PROPERTY (ID)
);



CREATE SEQUENCE SEQ_EGPT_GIS_AUD_DETAILS;

CREATE TABLE EGPT_GIS_AUD_DETAILS
(
	ID BIGINT NOT NULL, -- PRIMARY KEY
	GISDETAILS BIGINT NOT NULL, -- GISDETAILS ID
	APPL_ZONE BIGINT, -- APPLICATION ZONE ID
	APPLICATION_TAX double precision,
	CREATEDBY BIGINT NOT NULL,
	LASTMODIFIEDBY BIGINT NOT NULL,
	CREATEDDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	VERSION BIGINT,
	CONSTRAINT PK_EGPT_GIS_AUD_DET_ID PRIMARY KEY (ID),
	CONSTRAINT FK_EGPT_GIS_AUD_DET_CREATEDBY FOREIGN KEY (CREATEDBY) REFERENCES EG_USER (ID),
	CONSTRAINT FK_EGPT_GIS_AUD_DET_LASTMODBY FOREIGN KEY (LASTMODIFIEDBY) REFERENCES EG_USER (ID),
	CONSTRAINT FK_EGPT_GIS_AUD_DET_GISDET FOREIGN KEY (GISDETAILS) REFERENCES EGPT_GIS_DETAILS (ID)
);

