-----------------START-------------------
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (359, 'Property Tax', true, 'ptis', NULL, 'Property Tax', 6);
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (360, 'New Property', true, NULL, 359, 'New Property', NULL);
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (361, 'Existing property', true, NULL, 359, 'Existing property', NULL);
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (362, 'PTIS-Reports', true, NULL, 359, 'Reports', NULL);
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (363, 'GIS', true, NULL, 359, 'GIS', NULL);
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (364, 'PTIS-Administration', true, NULL, 359, 'Administration', NULL);
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (396, 'Ptis Revision Petition', false, NULL, 359, 'Ptis Revision Petition', 1);
INSERT INTO eg_module (id, name, enabled, contextroot, parentmodule, displayname, ordernumber) VALUES (400, 'PTIS-COMMON', false, 'ptis', 359, 'PTIS-COMMON', NULL);
------------------END---------------------

-----------------START-------------------
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (839,'CollectionPTIS','/search/searchProperty-searchForm.action','callbackurl=/collection/receipts/receipt-newform?collectXML=',400,1,'Property Tax','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (840,'Search by GIS','/search/gisSearchProperty-gisFormRedirect.action',null,363,1,'Search by GIS','true','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (842,'Search GIS Property','/search/gisSearchProperty-gisSearchForm.action',null,363,1,'Search GIS Module','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (843,'Search GIS Property Default','/search/gisSearchProperty.action',null,363,1,'Search GIS Module','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (844,'PTIS Index','/eGov.jsp',null,400,1,'PTIS Index','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (845,'Create Property','/create/createProperty-newForm.action',null,360,1,'Create New Property','true','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (846,'Create Property Submit','/create/createProperty-create.action',null,360,1,'Create New Property','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (847,'Search Property','/search/searchProperty-searchForm.action',null,361,1,'Search Property','true','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (848,'Search Property By Index','/search/searchProperty-srchByIndex.action',null,361,1,'Search Property By Index','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (849,'Search Property By Bndry','/search/searchProperty-srchByBndry.action',null,361,1,'Search Property By Bndry','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (850,'Search Property By Area','/search/searchProperty-srchByArea.action',null,361,1,'Search Property','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (852,'Search Notice','/reports/searchNotices-index.action',null,362,1,'Search Notice','true','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (853,'Search GIS Property by Boundary','/search/gisSearchProperty-gisSearchForm.action','mode=bndry',363,1,'Search GIS Property by Boundary','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (854,'Search GIS Property by Property Type','/search/gisSearchProperty-gisSearchForm.action','mode=propType',363,1,'Search GIS Property by Property Type','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (855,'Search GIS Property by Demand','/search/gisSearchProperty-gisSearchForm.action','mode=demand',363,1,'Search GIS Property by Demand','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (856,'Search GIS Property by Defaulter','/search/gisSearchProperty-gisSearchForm.action','mode=defaulter',363,1,'Search GIS Property by Defaulter','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (857,'Change Location Rate','/admin/changeStreetRate-searchForm.action',null,364,1,'Change Location Rate','true','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (859,'PTISVIEWDOC','/view/viewProperty-viewDoc.action',null,400,1,'PTISVIEWDOC','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (865,'Edit Demand Form','/edit/editDemand-newEditForm.action',null,400,0,'Edit Demand Form','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (866,'Edit Demand Update','/edit/editDemand',null,400,0,'Edit Demand Update','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (874,'Edit Owner','/modify/modifyProperty-ownerForm.action',null,400,null,'Edit Owner Form','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (875,'Edit Owner submit','/modify/modifyProperty-updateOwner.action',null,400,null,'Edit Owner submit','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (876,'Generate bills for ward New','/bills/bulkBillGeneration-newForm.action',null,364,1,'Generate bills for ward','true','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (877,'Generate bills for ward Ack','/bills/bulkBillGeneration-generateBills.action',null,364,1,'Generate bills for ward Ack','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (996,'Populate LocationFactors','/common/ajaxCommon-locationFactorsByWard.action',null,361,0,'Populate LocationFactors','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (997,'Populate Structural Classifications','/common/ajaxCommon-populateStructuralClassifications.action',null,361,0,'Populate Structural Classifications','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (998,'Populate Wards','/common/ajaxCommon-wardByZone.action',null,361,0,'Populate Wards','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (999,'Populate Streets','/common/ajaxCommon-streetByWard.action',null,361,0,'Populate Streets','false','ptis',0,1,'2015-07-15 19:14:54.980736',1,'2015-07-15 19:14:54.980736',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1050,'View Property','/view/viewProperty-viewForm.action',null,361,null,'View Property','false','ptis',0,1,'2015-07-15 19:14:57.181755',1,'2015-07-15 19:14:57.181755',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1051,'Load Admin Boundaries','/common/ajaxCommon-blockByLocality.action',null,360,null,'View Property','false','ptis',0,1,'2015-07-15 19:14:57.181755',1,'2015-07-15 19:14:57.181755',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1062,'Modify Property Form','/modify/modifyProperty-modifyForm.action',null,361,null,'Modify Property Form','false','ptis',null,1,'2015-07-15 19:15:09.902655',1,'2015-07-15 19:15:09.902655',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1064,'Rebate Master','/rebatePeriod/create',null,364,3,'Rebate Master','true','ptis',0,1,'2015-07-15 19:15:12.506533',1,'2015-07-15 19:15:12.506533',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1065,'Transfer Property Form','/property/transfer/new.action',null,361,null,'Transfer Property Form','false','ptis',null,1,'2015-07-15 19:15:12.523258',1,'2015-07-15 19:15:12.523258',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1066,'Transfer Property Save','/property/transfer/save.action',null,361,null,'Transfer Property Save','false','ptis',null,1,'2015-07-15 19:15:12.523258',1,'2015-07-15 19:15:12.523258',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1067,'Populate Designation','/common/ajaxCommon-populateDesignationsByDept.action',null,360,null,'Populate Designation','false','ptis',0,1,'2015-07-15 19:15:12.824107',1,'2015-07-15 19:15:12.824107',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1068,'Populate Approver','/common/ajaxCommon-populateUsersByDeptAndDesignation.action',null,360,null,'Populate Approver','false','ptis',0,1,'2015-07-15 19:15:12.824107',1,'2015-07-15 19:15:12.824107',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1074,'Property Tax Rev Petition New','/revPetition/revPetition-newForm.action',null,396,1,'Property Tax Rev Petition New','false','ptis',0,1,'2015-07-15 19:15:12.932985',1,'2015-07-15 19:15:12.932985',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1075,'Property Tax Rev Petition View','/revPetition/revPetition-view.action',null,396,2,'Property Tax Rev Petition View','false','ptis',0,1,'2015-07-15 19:15:12.932985',1,'2015-07-15 19:15:12.932985',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1076,'Property Tax Rev Petition Action','/revPetition/revPetition.action',null,396,3,'Property Tax Rev Petition Action','false','ptis',0,1,'2015-07-15 19:15:12.932985',1,'2015-07-15 19:15:12.932985',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1078,'Open inbox','/create/createProperty-view.action',null,360,null,'Open inbox','false','ptis',0,1,'2015-07-15 19:15:13.650394',1,'2015-07-15 19:15:13.650394',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1079,'Approve Property','/create/createProperty-approve.action',null,360,null,'Approve Property','false','ptis',0,1,'2015-07-15 19:15:13.650394',1,'2015-07-15 19:15:13.650394',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1080,'Forward Property','/create/createProperty-forward.action',null,360,null,'Forward Property','false','ptis',0,1,'2015-07-15 19:15:13.650394',1,'2015-07-15 19:15:13.650394',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1081,'Reject Property','/create/createProperty-reject.action',null,360,null,'Reject Property','false','ptis',0,1,'2015-07-15 19:15:13.650394',1,'2015-07-15 19:15:13.650394',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1082,'Modify Property Action','/modify/modifyProperty-save.action',null,361,null,'Modify Property Action','false','ptis',null,1,'2015-07-15 19:15:13.734131',1,'2015-07-15 19:15:13.734131',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1088,'Transfer Property View','/property/transfer/view.action',null,361,null,'Transfer Property View','false','ptis',null,1,'2015-07-15 19:15:13.850645',1,'2015-07-15 19:15:13.850645',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1089,'Transfer Property Approve','/property/transfer/approve.action',null,361,null,'Transfer Property Approve','false','ptis',null,1,'2015-07-15 19:15:13.850645',1,'2015-07-15 19:15:13.850645',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1090,'Transfer Property Forward','/property/transfer/forward.action',null,361,null,'Transfer Property Forward','false','ptis',null,1,'2015-07-15 19:15:13.850645',1,'2015-07-15 19:15:13.850645',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1091,'Transfer Property Reject','/property/transfer/reject.action',null,361,null,'Transfer Property Reject','false','ptis',null,1,'2015-07-15 19:15:13.850645',1,'2015-07-15 19:15:13.850645',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1094,'Forward Modify Property','/modify/modifyProperty-forward.action',null,361,null,'Forward Modify Property','false','ptis',null,1,'2015-07-15 19:15:14.370376',1,'2015-07-15 19:15:14.370376',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1095,'View Modify Property','/modify/modifyProperty-view.action',null,361,null,'View Modify Property','false','ptis',null,1,'2015-07-15 19:15:14.370376',1,'2015-07-15 19:15:14.370376',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1096,'Forward View Modify Property','/modify/modifyProperty-forwardView.action',null,361,null,'Forward View Modify Property','false','ptis',null,1,'2015-07-15 19:15:14.370376',1,'2015-07-15 19:15:14.370376',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1097,'Approve Modify Property','/modify/modifyProperty-approve.action',null,361,null,'Approve Modify Property','false','ptis',null,1,'2015-07-15 19:15:14.370376',1,'2015-07-15 19:15:14.370376',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1098,'Reject Modify Property','/modify/modifyProperty-reject.action',null,361,null,'Reject Modify Property','false','ptis',null,1,'2015-07-15 19:15:14.370376',1,'2015-07-15 19:15:14.370376',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1099,'Search Property By Location','/search/searchProperty-srchByLocation.action',null,361,1,'Search Property By Location','false','ptis',0,1,'2015-07-15 19:15:14.403683',1,'2015-07-15 19:15:14.403683',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1100,'Search Property By Demand','/search/searchProperty-searchByDemand.action',null,361,1,'Search Property By Demand','false','ptis',0,1,'2015-07-15 19:15:14.403683',1,'2015-07-15 19:15:14.403683',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1101,'Search Property By Assessment','/search/searchProperty-srchByAssessment.action',null,361,1,'Search Property By Demand','false','ptis',0,1,'2015-07-15 19:15:14.403683',1,'2015-07-15 19:15:14.403683',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1106,'Unit Rate Master','/admin/unitRate-newForm.action',null,364,2,'Unit Rate','true','ptis',0,1,'2015-07-15 19:15:14.757074',1,'2015-07-15 19:15:14.757074',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1107,'Unit Rate Create','/admin/unitRate-create.action',null,364,3,'Unit Rate Create','false','ptis',0,1,'2015-07-15 19:15:14.757074',1,'2015-07-15 19:15:14.757074',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1108,'Generate Collection Bill','/collection/collectPropertyTax-generateBill.action',null,361,0,'Generate Collection Bill','false','ptis',0,1,'2015-07-15 19:15:14.882475',1,'2015-07-15 19:15:14.882475',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1113,'Populate Designation For Revision Petition','/common/ajaxCommon-populateDesignationsByDeptForRevisionPetition.action',null,396,null,'Populate Designation For Revision Petition','false','ptis',0,1,'2015-07-15 19:17:52.4041',1,'2015-07-15 19:17:52.4041',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1114,'PropTax Rev Petition Add hearing','/revPetition/revPetition-addHearingDate.action',null,396,1,'PropTax Rev Petition Add hearing','false','ptis',0,1,'2015-07-15 19:17:52.4041',1,'2015-07-15 19:17:52.4041',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1115,'PropTax Rev Petition generate hearingnotice','/revPetition/revPetition-generateHearingNotice',null,400,1,'PropTax Rev Petition Add hearing','false','ptis',0,1,'2015-07-15 19:17:52.4041',1,'2015-07-15 19:17:52.4041',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1116,'PropTax Rev Petition record hearing','/revPetition/revPetition-recordHearingDetails',null,400,1,'PropTax Rev Petition record hearing','false','ptis',0,1,'2015-07-15 19:17:52.4041',1,'2015-07-15 19:17:52.4041',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1117,'PropTax Rev Petition record inspection','/revPetition/revPetition-recordInspectionDetails',null,400,1,'PropTax Rev Petition record inspection','false','ptis',0,1,'2015-07-15 19:17:52.4041',1,'2015-07-15 19:17:52.4041',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1118,'PropTax Rev Petition Outcome','/revPetition/revPetition-recordObjectionOutcome',null,400,1,'PropTax Rev Petition Outcome','false','ptis',0,1,'2015-07-15 19:17:52.4041',1,'2015-07-15 19:17:52.4041',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1119,'PropTax Rev Petition endoresement notice','/revPetition/revPetition-generateEnodresementNotice',null,400,1,'PropTax Rev Petition endoresement notice','false','ptis',0,1,'2015-07-15 19:17:52.4041',1,'2015-07-15 19:17:52.4041',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1129,'createPropertyAckPrint','/create/createProperty-printAck.action',null,360,4,'createPropertyAckPrint','false','ptis',0,1,'2015-07-15 19:17:52.955373',1,'2015-07-15 19:17:52.955373',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1130,'Acknowledgement Transfer Property','/property/transfer/printAck.action',null,361,null,'Acknowledgement Transfer Property','false','ptis',0,1,'2015-07-15 19:17:52.971998',1,'2015-07-15 19:17:52.971998',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1131,'Notice Transfer Property','/property/transfer/printNotice.action',null,361,null,'Acknowledgement Transfer Property','false','ptis',0,1,'2015-07-15 19:17:53.005346',1,'2015-07-15 19:17:53.005346',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1144,'PropTax generateBill','/bills/billGeneration-generateBill.action',null,400,0,null,'false','ptis',0,1,'2015-07-15 19:17:57.915012',1,'2015-07-15 19:17:57.915012',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1145,'Transferee Delete','/property/transfer/delete-transferee.action',null,361,null,'Transferee Delete','false','ptis',null,1,'2015-07-15 19:17:57.948467',1,'2015-07-15 19:17:57.948467',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1146,'Calculate Mutation Fee','/property/transfer/calculate-mutationfee.action',null,361,null,'Calculate Mutation Fee','false','ptis',null,1,'2015-07-15 19:17:57.965094',1,'2015-07-15 19:17:57.965094',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1148,'generateSpecialNotice','/notice/propertyTaxNotice-generateNotice',null,360,3,'generateSpecialNotice','false','ptis',0,1,'2015-07-15 19:18:00.649018',1,'2015-07-15 19:18:00.649018',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1149,'PropTax report viewer','/reportViewer',null,400,1,'PropTax report viewer','false','ptis',0,1,'2015-07-15 19:18:00.666015',1,'2015-07-15 19:18:00.666015',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1154,'Populate Categories by Property Type','/common/ajaxCommon-propTypeCategoryByPropType.action',null,396,null,'Populate Categories by Property Type','false','ptis',0,1,'2015-07-15 19:18:00.817023',1,'2015-07-15 19:18:00.817023',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1157,'PropTax Rev Petition print hearingnotice','/revPetition/revPetition-printHearingNotice.action',null,396,1,'PropTax Rev Petition print hearingnotice','false','ptis',0,1,'2015-07-15 19:18:01.552952',1,'2015-07-15 19:18:01.552952',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1158,'PropTax Rev Petition print Endoresement','/revPetition/revPetition-printEnodresementNotice.action',null,396,1,'PropTax Rev Petition print Endoresement','false','ptis',0,1,'2015-07-15 19:18:01.552952',1,'2015-07-15 19:18:01.552952',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1159,'Property Transfer Success Redirect','/property/transfer/redirect-success.action',null,361,null,'Property Transfer Success Redirect','false','ptis',null,1,'2015-07-15 19:18:01.661772',1,'2015-07-15 19:18:01.661772',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1160,'modifyPropertyAckPrint','/modify/modifyProperty-printAck',null,360,null,'modifyPropertyAckPrint','false','ptis',null,1,'2015-07-15 19:18:01.678499',1,'2015-07-15 19:18:01.678499',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1161,'Mutation Fee Payment Generate','/property/transfer/collect-fee.action',null,361,null,'Mutation Fee Payment Generate','false','ptis',0,1,'2015-07-15 19:18:01.82576',1,'2015-07-15 19:18:01.82576',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1163,'Mutation Fee Payment Search','/property/transfer/search.action',null,361,null,'Property Mutation Fee Search','false','ptis',null,1,'2015-07-15 19:18:01.82576',1,'2015-07-15 19:18:01.82576',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1164,'View DCB Property','/view/viewDCBProperty-viewForm.action',null,361,null,'View DCB Property','false','ptis',0,1,'2015-07-15 19:18:01.859083',1,'2015-07-15 19:18:01.859083',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1165,'View DCB Property Display','/view/viewDCBProperty-displayPropInfo.action',null,361,null,'View DCB Property','false','ptis',0,1,'2015-07-15 19:18:01.875647',1,'2015-07-15 19:18:01.875647',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1214,'Zone Wise Collection Report','/reports/collectionSummaryReport-zoneWise.action',null,362,0,'Revenue Zone Wise Collection Report','true','ptis',0,1,'2015-07-30 11:12:49.516393',1,'2015-07-30 11:12:49.516393',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1215,'Ward Wise Collection Report','/reports/collectionSummaryReport-wardWise.action',null,362,0,'Revenue Ward Wise Collection Report','true','ptis',0,1,'2015-07-30 11:12:49.516393',1,'2015-07-30 11:12:49.516393',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1216,'Block Wise Collection Report','/reports/collectionSummaryReport-blockWise.action',null,362,0,'Revenue Block Wise Collection Report','true','ptis',0,1,'2015-07-30 11:12:49.516393',1,'2015-07-30 11:12:49.516393',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1217,'Locality Wise Collection Report','/reports/collectionSummaryReport-localityWise.action',null,362,0,'Revenue Locality Wise Collection Report','true','ptis',0,1,'2015-07-30 11:12:49.516393',1,'2015-07-30 11:12:49.516393',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1218,'PropTax Rev Petition verify inspection','/revPetition/revPetition-validateInspectionDetails',null,396,null,'PropTax Rev Petition verify inspection','false','ptis',0,1,'2015-07-30 11:12:50.117705',1,'2015-07-30 11:12:50.117705',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1220,'PropTax Rev Petition reject inspection','/revPetition/revPetition-rejectInspectionDetails',null,396,null,'PropTax Rev Petition reject inspection','false','ptis',0,1,'2015-08-03 11:20:15.939085',1,'2015-08-03 11:20:15.939085',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1221,'SearchNoticeSearchResult','/reports/searchNotices-search',null,362,null,'SearchNoticeSearchResult','false','ptis',null,1,'2015-08-05 10:16:51.990117',1,'2015-08-05 10:16:51.990117',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1225,'SearchNoticeMergeAndDownload','/reports/searchNotices-mergeAndDownload',null,362,null,'SearchNoticeMergeAndDownload','false','ptis',null,1,'2015-08-05 10:16:51.990117',1,'2015-08-05 10:16:51.990117',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1226,'SearchNoticeZipAndDownload','/reports/searchNotices-zipAndDownload',null,362,null,'SearchNoticeZipAndDownload','false','ptis',null,1,'2015-08-05 10:16:51.990117',1,'2015-08-05 10:16:51.990117',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1227,'SearchNoticeReset','/reports/searchNotices-reset',null,362,null,'SearchNoticeReset','false','ptis',null,1,'2015-08-05 10:16:51.990117',1,'2015-08-05 10:16:51.990117',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1238,'SearchNoticeShowNotice','/reports/searchNotices-showNotice',null,362,null,'SearchNoticeShowNotice','false','ptis',null,1,'2015-08-05 17:55:34.329387',1,'2015-08-05 17:55:34.329387',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1240,'Collection Summary Report Result','/reports/collectionSummaryReport-list.action',null,362,1,'Collection Summary Report Result','false','ptis',0,1,'2015-08-10 14:31:59.145439',1,'2015-08-10 14:31:59.145439',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1241,'DCBReport','/reports/dCBReport-search.action',null,362,3,'DCB Report','true','ptis',0,1,'2015-08-12 17:22:47.518842',1,'2015-08-12 17:22:47.518842',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1242,'SearchDCBReport','/reports/ajaxDCBReport-getBoundaryWiseDCBList.action',null,362,3,'SearchDCBReport','false','ptis',0,1,'2015-08-12 17:22:47.518842',1,'2015-08-12 17:22:47.518842',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1243,'PropTax Rev Petition rejection','/revPetition/revPetition-reject.action',null,396,1,'PropTax Rev Petition rejection','false','ptis',0,1,'2015-08-12 18:23:10.175228',1,'2015-08-12 18:23:10.175228',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1244,'PropTax Rev Petition Special notice','/revPetition/revPetition-generateSpecialNotice.action',null,396,1,'PropTax Rev Petition Special notice','false','ptis',0,1,'2015-08-12 18:23:10.175228',1,'2015-08-12 18:23:10.175228',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1258,'Arrears Register Report','/reports/arrearRegisterReport-index.action',null,362,0,'Arrears Register Report','true','ptis',0,1,'2015-08-18 14:32:53.476811',1,'2015-08-18 14:32:53.476811',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1259,'GenerateArrearRegisterReport','/reports/arrearRegisterReport-generateArrearReport.action',null,362,0,'GenerateArrearRegisterReport','false','ptis',0,1,'2015-08-18 14:32:53.476811',1,'2015-08-18 14:32:53.476811',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1260,'ajaxLoadBoundaryWard','/common/ajaxCommon-wardByZone.action',null,362,0,'ajaxLoadBoundary','false','ptis',0,1,'2015-08-18 14:32:53.476811',1,'2015-08-18 14:32:53.476811',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1261,'ajaxLoadBoundaryBlock','/common/ajaxCommon-areaByWard.action',null,362,0,'ajaxLoadBoundaryBlock','false','ptis',0,1,'2015-08-18 14:32:53.476811',1,'2015-08-18 14:32:53.476811',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1264,'User By Mobile number','/common/ajaxCommon-getUserByMobileNo.action',null,360,0,'User By Mobile number','false','ptis',0,1,'2015-08-19 02:14:08.103201',1,'2015-08-19 02:14:08.103201',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1269,'Title Transfer Register Report','/reports/titleTransferRegister-search.action',null,362,0,'Title Transfer Register Report','true','ptis',0,1,'2015-08-19 17:21:44.72557',1,'2015-08-19 17:21:44.72557',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1270,'TitleTransferRegReportResult','/reports/titleTransferRegister-getPropertyList.action',null,362,0,'Title Transfer Register Report','false','ptis',0,1,'2015-08-19 17:21:44.72557',1,'2015-08-19 17:21:44.72557',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1275,'PTIS-Data Entry Screen','/create/createProperty-dataEntry.action',null,361,1,'Data Entry Screen','true','ptis',0,1,'2015-08-22 09:59:36.851093',1,'2015-08-22 09:59:36.851093',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1276,'PTIS-Create Data Entry Screen','/create/createProperty-createDataEntry.action',null,361,1,'Create Data Entry Screen','false','ptis',0,1,'2015-08-22 09:59:36.851093',1,'2015-08-22 09:59:36.851093',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1293,'Usage Wise Collection Summary Report','/reports/collectionSummaryReport-usageWise.action',null,362,0,'Usage Wise Collection Summary Report','true','ptis',0,1,'2015-09-03 13:24:04.773853',1,'2015-09-03 13:24:04.773853',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1341,'Edit Demand submit','/edit/editDemand.action',null,361,1,'Edit Demand submit','false','ptis',0,1,'2015-09-14 11:53:22.606753',1,'2015-09-14 11:53:22.606753',359);
Insert into EG_ACTION (id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate, application) values (1342,'Edit Demand Update Form','/edit/editDemand-update',null,361,1,'Edit Demand Update Form','false','ptis',0,1,'2015-09-14 11:53:25.182135',1,'2015-09-14 11:53:25.182135',359);
INSERT INTO eg_action(id, name, url, queryparams, parentmodule, ordernumber, displayname, enabled, contextroot, version, createdby, createddate, lastmodifiedby, lastmodifieddate,application) VALUES (nextval('seq_eg_action'), 'Property Usage by type', '/common/ajaxCommon-usageByPropType.action', null,(select id from eg_module where name='New Property'), 0, 'Property Usage by type', false, 'ptis', 0, 1, now(), 1, now(),(select id from eg_module where name='Property Tax' and parentmodule is null));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'AlterAssessment-Form','/search/searchProperty-commonForm.action', 'applicationType=Alter_Assessment',(select id from EG_MODULE where name = 'Existing property'),null,'Addition/Alteration of Assessment','t','ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'BifurcateAssessment-Form','/search/searchProperty-commonForm.action', 'applicationType=Bifuracate_Assessment',(select id from EG_MODULE where name = 'Existing property'),null,'Bifurcation of Assessment','t','ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'TransferOwnership-Form','/search/searchProperty-commonForm.action', 'applicationType=Transfer_of_Ownership',(select id from EG_MODULE where name = 'Existing property'),null,'Transfer Ownership','t','ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'RevisionPetition-Form','/search/searchProperty-commonForm.action', 'applicationType=Revision Petition',(select id from EG_MODULE where name = 'Existing property'),null,'Create Revision Petition','t','ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'CollectTax-Form','/search/searchProperty-commonForm.action', 'applicationType=Collect_Tax',(select id from EG_MODULE where name = 'Existing property'),null,'Collect Tax','t','ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'GenerateDemandBill-Form','/search/searchProperty-commonForm.action', 'applicationType=Generate_demand_bill',(select id from EG_MODULE where name = 'Existing property'),null,'Generate Demand Bill','t','ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Assessment-commonSearch','/search/searchProperty-commonSearch.action', null,(select id from EG_MODULE where name = 'Existing property'),null,null,'f','ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'ajaxLoadBolockByWard','/common/ajaxCommon-blockByWard.action', null,(select id from EG_MODULE where name = 'New Property'),null,null,'f','ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
Insert into eg_action (ID,NAME,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate, lastmodifiedby, lastmodifieddate, application) values (nextval('seq_eg_action'),'PTIS-Edit Data Entry Screen','/modify/modifyProperty-modifyDataEntry.action', null, (select ID from eg_module where NAME ='Existing property'), null, 'Edit Data Entry Screen', false, 'ptis', null, 1, current_timestamp,1,current_timestamp, (select ID from eg_module where NAME ='Property Tax'));
Insert into eg_action (ID,NAME,url,queryparams,parentmodule,ordernumber,displayname,enabled,contextroot,version,createdby,createddate, lastmodifiedby, lastmodifieddate, application) values (nextval('seq_eg_action'),'PTIS-Save Edit Data Entry Screen','/modify/modifyProperty-saveDataEntry.action', null, (select ID from eg_module where NAME ='Existing property'), null, 'Save Edit Data Entry Screen', false, 'ptis', null, 1, current_timestamp,1,current_timestamp, (select ID from eg_module where NAME ='Property Tax'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'checkExistingCategory','/common/ajaxCommon-checkIfCategoryExists.action',null,(select id from EG_MODULE where name = 'PTIS-Administration'),0,'checkExistingCategory',false,'ptis',0,1,now(),1,now(),(select id from eg_module where name='Property Tax' and parentmodule is null));
INSERT INTO EG_ACTION (ID, NAME, URL, QUERYPARAMS, PARENTMODULE, ORDERNUMBER, DISPLAYNAME, ENABLED, CONTEXTROOT, VERSION, CREATEDBY, CREATEDDATE, LASTMODIFIEDBY, LASTMODIFIEDDATE, APPLICATION) VALUES (nextval('SEQ_EG_ACTION'), 'Usage Master', '/usage/create', NULL, (SELECT ID FROM EG_MODULE WHERE NAME = 'PTIS-Administration'), 3, 'Usage Master', true, 'ptis', 0, 1, now(), 1, now(), (SELECT id FROM eg_module WHERE name='Property Tax' AND parentmodule IS NULL));
INSERT INTO EG_ACTION (ID, NAME, URL, QUERYPARAMS, PARENTMODULE, ORDERNUMBER,DISPLAYNAME, ENABLED, CONTEXTROOT, VERSION, CREATEDBY, CREATEDDATE, LASTMODIFIEDBY, LASTMODIFIEDDATE, APPLICATION) VALUES (nextval('SEQ_EG_ACTION'), 'Usage Master List', '/usage/list', NULL, (SELECT ID FROM EG_MODULE WHERE NAME = 'PTIS-Administration'), 3, 'Usage Master List', false, 'ptis', 0, 1, now(), 1, now(), (SELECT id FROM eg_module WHERE name='Property Tax' AND parentmodule IS NULL));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Base Register Report','/report/baseRegister', null,(select id from EG_MODULE where name = 'PTIS-Reports'),null, 'Base Register','t','ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Base Register Report result','/report/baseRegister/result', null,(select id from EG_MODULE where name = 'PTIS-Reports'),null,'Base Register Report result',false,'ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'NatureOfUsageReport-form','/reports/natureOfUsageReport-form', null,(select id from EG_MODULE where name = 'PTIS-Reports'),1,'Nature of usage report','t','ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'NatureOfUsageReport-result','/reports/natureOfUsageReportList', null,(select id from EG_MODULE where name = 'PTIS-Reports'),null,null,'f','ptis',0,1,now(),1,now(),(select id from eg_module  where name = 'Property Tax'));
------------------END---------------------

-----------------START-------------------
INSERT INTO eg_role (id, name, description, createddate, createdby, lastmodifiedby, lastmodifieddate, version) VALUES (14, 'Property Administrator', 'Administrator for Property Tax', '2015-08-28 10:43:58.851212', 1, 1, '2015-08-28 10:43:58.851212', 0);
INSERT INTO eg_role (id, name, description, createddate, createdby, lastmodifiedby, lastmodifieddate, version) VALUES (11, 'Property Verifier', 'Muncipal Commissioner, final approval authority', '2015-08-28 10:43:45.850138', 1, 1, '2015-08-28 10:43:45.850138', NULL);
INSERT INTO eg_role (id, name, description, createddate, createdby, lastmodifiedby, lastmodifieddate, version) VALUES (12, 'Property Approver', 'Muncipal Commissioner, final approval authority', '2015-08-28 10:43:45.850138', 1, 1, '2015-08-28 10:43:45.850138', NULL);
------------------END---------------------

-----------------START-------------------
Insert into EG_ROLEACTION (roleid, actionid) values (16,839);
Insert into EG_ROLEACTION (roleid, actionid) values (16,842);
Insert into EG_ROLEACTION (roleid, actionid) values (16,843);
Insert into EG_ROLEACTION (roleid, actionid) values (16,844);
Insert into EG_ROLEACTION (roleid, actionid) values (16,845);
Insert into EG_ROLEACTION (roleid, actionid) values (5,845);
Insert into EG_ROLEACTION (roleid, actionid) values (16,846);
Insert into EG_ROLEACTION (roleid, actionid) values (5,846);
Insert into EG_ROLEACTION (roleid, actionid) values (5,847);
Insert into EG_ROLEACTION (roleid, actionid) values (14,847);
Insert into EG_ROLEACTION (roleid, actionid) values (12,847);
Insert into EG_ROLEACTION (roleid, actionid) values (11,847);
Insert into EG_ROLEACTION (roleid, actionid) values (16,847);
Insert into EG_ROLEACTION (roleid, actionid) values (4,847);
Insert into EG_ROLEACTION (roleid, actionid) values (14,848);
Insert into EG_ROLEACTION (roleid, actionid) values (12,848);
Insert into EG_ROLEACTION (roleid, actionid) values (11,848);
Insert into EG_ROLEACTION (roleid, actionid) values (16,848);
Insert into EG_ROLEACTION (roleid, actionid) values (14,849);
Insert into EG_ROLEACTION (roleid, actionid) values (4,849);
Insert into EG_ROLEACTION (roleid, actionid) values (12,849);
Insert into EG_ROLEACTION (roleid, actionid) values (11,849);
Insert into EG_ROLEACTION (roleid, actionid) values (16,849);
Insert into EG_ROLEACTION (roleid, actionid) values (16,850);
Insert into EG_ROLEACTION (roleid, actionid) values (11,850);
Insert into EG_ROLEACTION (roleid, actionid) values (12,850);
Insert into EG_ROLEACTION (roleid, actionid) values (14,850);
Insert into EG_ROLEACTION (roleid, actionid) values (14,852);
Insert into EG_ROLEACTION (roleid, actionid) values (12,852);
Insert into EG_ROLEACTION (roleid, actionid) values (16,852);
Insert into EG_ROLEACTION (roleid, actionid) values (11,852);
Insert into EG_ROLEACTION (roleid, actionid) values (16,853);
Insert into EG_ROLEACTION (roleid, actionid) values (16,854);
Insert into EG_ROLEACTION (roleid, actionid) values (16,855);
Insert into EG_ROLEACTION (roleid, actionid) values (16,856);
Insert into EG_ROLEACTION (roleid, actionid) values (16,857);
Insert into EG_ROLEACTION (roleid, actionid) values (16,859);
Insert into EG_ROLEACTION (roleid, actionid) values (16,865);
Insert into EG_ROLEACTION (roleid, actionid) values (5,865);
Insert into EG_ROLEACTION (roleid, actionid) values (16,866);
Insert into EG_ROLEACTION (roleid, actionid) values (16,874);
Insert into EG_ROLEACTION (roleid, actionid) values (16,875);
Insert into EG_ROLEACTION (roleid, actionid) values (16,876);
Insert into EG_ROLEACTION (roleid, actionid) values (16,877);
Insert into EG_ROLEACTION (roleid, actionid) values (16,996);
Insert into EG_ROLEACTION (roleid, actionid) values (16,997);
Insert into EG_ROLEACTION (roleid, actionid) values (16,998);
Insert into EG_ROLEACTION (roleid, actionid) values (11,998);
Insert into EG_ROLEACTION (roleid, actionid) values (12,998);
Insert into EG_ROLEACTION (roleid, actionid) values (4,998);
Insert into EG_ROLEACTION (roleid, actionid) values (14,998);
Insert into EG_ROLEACTION (roleid, actionid) values (16,999);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1050);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1050);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1050);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1050);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1050);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1050);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1051);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1051);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1051);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1062);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1062);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1064);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1065);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1065);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1065);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1066);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1066);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1066);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1067);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1067);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1068);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1068);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1074);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1074);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1075);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1075);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1075);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1076);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1076);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1076);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1078);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1078);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1078);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1079);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1079);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1080);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1080);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1080);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1081);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1081);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1081);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1082);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1088);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1088);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1088);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1089);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1089);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1089);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1090);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1090);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1090);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1091);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1091);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1091);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1091);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1094);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1094);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1094);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1095);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1095);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1095);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1096);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1096);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1096);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1097);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1097);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1098);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1098);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1098);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1099);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1099);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1099);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1099);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1100);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1100);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1100);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1100);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1101);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1101);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1101);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1101);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1101);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1106);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1107);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1108);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1108);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1113);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1113);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1113);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1113);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1114);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1115);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1116);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1117);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1118);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1119);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1129);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1129);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1130);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1130);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1131);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1131);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1144);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1144);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1144);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1145);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1145);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1145);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1145);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1146);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1146);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1146);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1146);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1148);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1148);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1148);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1149);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1149);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1154);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1154);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1154);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1157);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1158);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1159);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1159);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1159);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1159);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1160);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1160);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1160);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1161);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1163);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1164);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1165);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1165);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1165);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1165);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1165);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1214);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1214);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1214);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1214);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1214);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1214);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1215);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1215);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1215);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1215);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1215);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1215);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1216);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1216);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1216);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1216);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1216);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1216);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1217);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1217);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1217);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1217);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1217);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1217);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1218);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1218);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1220);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1220);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1221);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1221);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1221);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1221);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1225);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1225);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1225);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1225);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1226);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1226);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1226);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1226);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1227);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1227);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1227);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1227);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1238);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1238);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1238);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1238);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1240);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1240);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1240);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1241);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1241);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1241);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1242);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1242);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1242);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1243);
Insert into EG_ROLEACTION (roleid, actionid) values (14,1243);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1243);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1243);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1244);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1258);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1258);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1258);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1259);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1259);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1259);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1260);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1260);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1260);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1261);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1261);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1261);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1261);
Insert into EG_ROLEACTION (roleid, actionid) values (12,1264);
Insert into EG_ROLEACTION (roleid, actionid) values (11,1264);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1264);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1264);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1269);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1269);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1269);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1270);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1270);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1270);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1275);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1275);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1276);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1276);
Insert into EG_ROLEACTION (roleid, actionid) values (16,1293);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1293);
Insert into EG_ROLEACTION (roleid, actionid) values (4,1293);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1341);
Insert into EG_ROLEACTION (roleid, actionid) values (5,1342);
Insert into EG_ROLEACTION (roleid, actionid) values (4,56);
Insert into EG_ROLEACTION (roleid, actionid) values (5,56);
Insert into EG_ROLEACTION (roleid, actionid) values (15,56);
Insert into EG_ROLEACTION (roleid, actionid) values (16,56);
Insert into EG_ROLEACTION (roleid, actionid) values (11,56);
Insert into EG_ROLEACTION (roleid, actionid) values (12,56);
Insert into EG_ROLEACTION (roleid, actionid) values (5,41);
Insert into EG_ROLEACTION (roleid, actionid) values (5,42);
Insert into EG_ROLEACTION (roleid, actionid) values (5,43);
insert into eg_roleaction(Select id,(select id from eg_action where name='AjaxDesignationDropdown') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='AjaxApproverDropdown') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='AjaxDesignationDropdown') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='AjaxApproverDropdown') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='AjaxDesignationDropdown') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='AjaxApproverDropdown') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='OfficialsProfileEdit') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='OfficialSentFeedBack') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='OfficialChangePassword') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='AddFavourite') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='RemoveFavourite') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='Official Home Page') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='CitizenInboxForm') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='OfficialsProfileEdit') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='OfficialSentFeedBack') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='OfficialChangePassword') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='AddFavourite') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='RemoveFavourite') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='Official Home Page') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='CitizenInboxForm') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='OfficialsProfileEdit') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='OfficialSentFeedBack') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='OfficialChangePassword') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='AddFavourite') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='RemoveFavourite') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='Official Home Page') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='CitizenInboxForm') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='Inbox') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='InboxDraft') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='InboxHistory') from eg_role where name='ULB Operator');
insert into eg_roleaction(Select id,(select id from eg_action where name='Inbox') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='InboxDraft') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='InboxHistory') from eg_role where name='Property Approver');
insert into eg_roleaction(Select id,(select id from eg_action where name='Inbox') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='InboxDraft') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='InboxHistory') from eg_role where name='Property Verifier');
insert into eg_roleaction(Select id,(select id from eg_action where name='Inbox') from eg_role where name='Employee');
insert into eg_roleaction(Select id,(select id from eg_action where name='InboxDraft') from eg_role where name='Employee');
insert into eg_roleaction(Select id,(select id from eg_action where name='InboxHistory') from eg_role where name='Employee');
insert into eg_roleaction(Select id,(select id from eg_action where name='Open inbox') from eg_role where name='Employee');
insert into eg_roleaction(Select id,(select id from eg_action where name='Forward Property') from eg_role where name='Employee');
INSERT INTO eg_roleaction (actionid,roleid) VALUES ((SELECT id FROM eg_action WHERE name='AadhaarInfo' and contextroot='egi'),(SELECT id FROM eg_role WHERE name ='ULB Operator'));
INSERT INTO eg_roleaction (actionid,roleid) VALUES ((SELECT id FROM eg_action WHERE name='AadhaarInfo' and contextroot='egi'),(SELECT id FROM eg_role WHERE name ='CSC Operator'));
INSERT INTO eg_roleaction (actionid,roleid) VALUES ((SELECT id FROM eg_action WHERE name='AadhaarInfo' and contextroot='egi'),(SELECT id FROM eg_role WHERE name ='Property Verifier'));
INSERT INTO eg_roleaction (actionid,roleid) VALUES ((SELECT id FROM eg_action WHERE name='AadhaarInfo' and contextroot='egi'),(SELECT id FROM eg_role WHERE name ='Property Approver'));
INSERT INTO eg_roleaction  (actionid,roleid) VALUES ((SELECT id FROM eg_action WHERE name='Property Usage by type' and contextroot='ptis'),(SELECT id FROM eg_role WHERE name ='ULB Operator'));
INSERT INTO eg_roleaction  (actionid,roleid) VALUES ((SELECT id FROM eg_action WHERE name='Property Usage by type' and contextroot='ptis'),(SELECT id FROM eg_role WHERE name ='CSC Operator'));
INSERT INTO eg_roleaction  (actionid,roleid) VALUES ((SELECT id FROM eg_action WHERE name='Property Usage by type' and contextroot='ptis'),(SELECT id FROM eg_role WHERE name ='Property Verifier'));
INSERT INTO eg_roleaction  (actionid,roleid) VALUES ((SELECT id FROM eg_action WHERE name='Property Usage by type' and contextroot='ptis'),(SELECT id FROM eg_role WHERE name ='Property Approver'));
insert into eg_roleaction (roleid, actionid) select (select id from eg_role where name = 'ULB Operator'), id from eg_action where name = 'AlterAssessment-Form';
insert into eg_roleaction (roleid, actionid) select (select id from eg_role where name = 'ULB Operator'), id from eg_action where name = 'Assessment-commonSearch';
insert into eg_roleaction (roleid, actionid) select (select id from eg_role where name = 'ULB Operator'), id from eg_action where name = 'BifurcateAssessment-Form';
insert into eg_roleaction (roleid, actionid) select (select id from eg_role where name = 'ULB Operator'), id from eg_action where name = 'TransferOwnership-Form';
insert into eg_roleaction (roleid, actionid) select (select id from eg_role where name = 'ULB Operator'), id from eg_action where name = 'RevisionPetition-Form';
insert into eg_roleaction (roleid, actionid) select (select id from eg_role where name = 'ULB Operator'), id from eg_action where name = 'GenerateDemandBill-Form';
insert into eg_roleaction (roleid, actionid) select (select id from eg_role where name = 'CSC Operator'), id from eg_action where name = 'CollectTax-Form';
insert into eg_roleaction (roleid, actionid) select (select id from eg_role where name = 'CSC Operator'), id from eg_action where name = 'Assessment-commonSearch';
INSERT INTO eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Property Verifier'), (select id from eg_action  where name = 'ajaxLoadBoundaryBlock'));
insert into eg_roleaction (roleid, actionid) select (select id from eg_role where name = 'ULB Operator'), id from eg_action where name = 'ajaxLoadBolockByWard';
insert into eg_roleaction (roleid, actionid) select (select id from eg_role where name = 'Property Verifier'), id from eg_action where name = 'ajaxLoadBolockByWard';
INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) values ((select id from eg_role where name = 'CSC Operator') ,(select id FROM eg_action  WHERE name = 'PTIS-Edit Data Entry Screen' and contextroot='ptis'));
INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) values ((select id from eg_role where name = 'CSC Operator') ,(select id FROM eg_action  WHERE name = 'PTIS-Save Edit Data Entry Screen' and contextroot='ptis'));
INSERT INTO eg_roleaction (actionid,roleid) VALUES ((SELECT id FROM eg_action WHERE name='checkExistingCategory' and contextroot='ptis'),(SELECT id FROM eg_role WHERE name ='Property Administrator'));
INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) VALUES ((SELECT id FROM eg_role WHERE name LIKE 'Property Administrator'), (SELECT id FROM eg_action WHERE NAME = 'Usage Master' AND CONTEXTROOT = 'ptis'));
INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) VALUES ((SELECT id FROM eg_role WHERE name LIKE 'Property Administrator'),(SELECT id FROM eg_action WHERE NAME = 'Usage Master List' AND CONTEXTROOT = 'ptis'));
insert into eg_roleaction (actionid, roleid) select (select id from eg_action where name = 'Base Register Report'), id from eg_role where name in ('Super User','ULB Operator','Property Administrator','Property Approver','Property Verifier');
insert into eg_roleaction (actionid, roleid) select (select id from eg_action where name = 'Base Register Report result'), id from eg_role where name in ('Super User','ULB Operator','Property Administrator','Property Approver','Property Verifier');
insert into eg_roleaction (actionid, roleid) select (select id from eg_action where name = 'NatureOfUsageReport-form'), id from eg_role where name in ('Super User','ULB Operator','Property Administrator','Property Approver','Property Verifier');
insert into eg_roleaction (actionid, roleid) select (select id from eg_action where name = 'NatureOfUsageReport-result'), id from eg_role where name in ('Super User','ULB Operator','Property Administrator','Property Approver','Property Verifier');

--Mapping all the actions to Super user role
INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) select (select id from eg_role where name = 'Super User'), id FROM eg_action  WHERE contextroot='ptis' and application=(select id from eg_module where name='Property Tax');------------------END---------------------

-----------------START-------------------
Insert into EGPT_SRC_OF_INFO (ID,SOURCE_NAME,LASTUPDATEDTIMESTAMP,SOURCE_NAME_LOCAL,SRC_SHT_NAME) values (nextval('SEQ_EGPT_SRC_OF_INFO'),'Municipal Records',CURRENT_TIMESTAMP,null,'MNCPL-RECORDS');
------------------END---------------------

-----------------START-------------------
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'OBJECTED',CURRENT_TIMESTAMP,'Y','OBJECTED');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'NOTICE155ISSUED',CURRENT_TIMESTAMP,'Y','NOTICE155ISSUED');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'WARRANT APPLICATION PREPARED',CURRENT_TIMESTAMP,'Y','WARRANT APPLICATION PREPARED');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Warrant application approved',CURRENT_TIMESTAMP,'Y','WARRANT APPLICATION APPROVED');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'WARRANT NOTICE CREATED',CURRENT_TIMESTAMP,'Y','WARRANT NOTICE CREATED');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'WARRANT NOTICE ISSUED',CURRENT_TIMESTAMP,'Y','WARRANT NOTICE ISSUED');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'CEASE NOTICE CREATED',CURRENT_TIMESTAMP,'Y','CEASE NOTICE CREATED');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'CEASE NOTICE ISSUED',CURRENT_TIMESTAMP,'Y','CEASE NOTICE ISSUED');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Inactive',CURRENT_TIMESTAMP,'Y','INACTIVE');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Self Assessed and Unverified',CURRENT_TIMESTAMP,'Y',null);
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Assessed',CURRENT_TIMESTAMP,'Y','ASSESSED');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Unassessed',CURRENT_TIMESTAMP,'Y',null);
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Create',CURRENT_TIMESTAMP,'Y','CREATE');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Change',CURRENT_TIMESTAMP,'Y','CHANGE');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Alter',CURRENT_TIMESTAMP,'Y','ADD_OR_ALTER');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Active',CURRENT_TIMESTAMP,'Y','ACTIVE');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Marked For Deactivation',CURRENT_TIMESTAMP,'Y','MARK_DEACTIVE');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Bifurcation',CURRENT_TIMESTAMP,'Y','BIFURCATE');
Insert into egpt_status (ID,STATUS_NAME,created_date,IS_ACTIVE,CODE) values (nextval('SEQ_EGPT_STATUS'),'Amalgamation',CURRENT_TIMESTAMP,'Y','AMALG');
INSERT INTO egpt_status (id,status_name,created_date,is_active,code) values (nextval('SEQ_EGPT_STATUS'),'WORKFLOW',CURRENT_TIMESTAMP,'Y','WORKFLOW');
INSERT INTO egpt_status (id,status_name,created_date,is_active,code) values (nextval('SEQ_EGPT_STATUS'),'APPROVED',CURRENT_TIMESTAMP,'Y','APPROVED');
------------------END---------------------

-----------------START-------------------
Insert into egpt_mutation_master (ID,MUTATION_NAME,MUTATION_DESC,TYPE,CODE,ORDER_ID) values (nextval('SEQ_EGPT_MUTATION_MASTER'),'NEW PROPERTY','new property','CREATE','NEW',1);
Insert into egpt_mutation_master (ID,MUTATION_NAME,MUTATION_DESC,TYPE,CODE,ORDER_ID) values (nextval('SEQ_EGPT_MUTATION_MASTER'),'BIFURCATION','Bifurcation','CREATE','BIFUR',2);
Insert into egpt_mutation_master (ID,MUTATION_NAME,MUTATION_DESC,TYPE,CODE,ORDER_ID) values (nextval('SEQ_EGPT_MUTATION_MASTER'),'AMALGAMATION ','Amalgamation ','MODIFY','AMALG',3);
Insert into egpt_mutation_master (ID,MUTATION_NAME,MUTATION_DESC,TYPE,CODE,ORDER_ID) values (nextval('SEQ_EGPT_MUTATION_MASTER'),'COURT ORDER','By Court order','DEACTIVATE','COURTORDER',1);
Insert into egpt_mutation_master (ID,MUTATION_NAME,MUTATION_DESC,TYPE,CODE,ORDER_ID) values (nextval('SEQ_EGPT_MUTATION_MASTER'),'WRONG ENTRY IN SYSTEM','Because of wrong entry in the system','DEACTIVATE','WRONGENTRY',4);
Insert into egpt_mutation_master (ID,MUTATION_NAME,MUTATION_DESC,TYPE,CODE,ORDER_ID) values (nextval('SEQ_EGPT_MUTATION_MASTER'),'CHANGE PROPERTY DETAILS','Change Property Details','MODIFY','MODIFY',1);
Insert into egpt_mutation_master (ID,MUTATION_NAME,MUTATION_DESC,TYPE,CODE,ORDER_ID) values (nextval('SEQ_EGPT_MUTATION_MASTER'),'BIFURCATION','Bifurcation','MODIFY','BIFURCATE',2);
Insert into egpt_mutation_master (ID,MUTATION_NAME,MUTATION_DESC,TYPE,CODE,ORDER_ID) values (nextval('SEQ_EGPT_MUTATION_MASTER'),'COURT RULING','Court Ruling','MODIFY','COURT_RULE',4);
Insert into egpt_mutation_master (ID,MUTATION_NAME,MUTATION_DESC,TYPE,CODE,ORDER_ID) values (nextval('SEQ_EGPT_MUTATION_MASTER'),'OBJECTION','Objection','MODIFY','OBJ',5);
insert into egpt_mutation_master (id, mutation_name, mutation_desc, type, code, order_id) values (nextval('seq_egpt_mutation_master'), 'ADDITION OR ALTERATION', 'Addition or Alteration', 'MODIFY', 'ADD_OR_ALTER', (SELECT MAX(ORDER_ID) + 1 FROM EGPT_MUTATION_MASTER WHERE TYPE = 'MODIFY'));
insert into egpt_mutation_master (id, mutation_name, mutation_desc, type, code, order_id) values (nextval('seq_egpt_mutation_master'), 'PART DEMOLITION', 'Part Demolition', 'MODIFY', 'PART DEMOLITION', (SELECT MAX(ORDER_ID) + 1 FROM EGPT_MUTATION_MASTER WHERE TYPE = 'MODIFY'));
Insert into egpt_mutation_master (ID,MUTATION_NAME,MUTATION_DESC,TYPE,CODE,ORDER_ID) values (nextval('SEQ_EGPT_MUTATION_MASTER'),'DATA ENTRY','DataEntry','MODIFY','DATA_ENTRY',6);
------------------END---------------------

-----------------START-------------------
INSERT INTO eg_wf_types (id,module,type,link,createdby,createddate,lastmodifiedby,lastmodifieddate,renderyn,groupyn,typefqn,displayname) VALUES (nextval('seq_eg_wf_types'),(SELECT id FROM eg_module WHERE name='Property Tax'),'PropertyImpl',':ID',1,now(),1,now(), 'Y', 'N','org.egov.ptis.domain.entity.property.PropertyImpl', 'Property');
INSERT INTO eg_wf_types (id,module,type,link,createdby,createddate,lastmodifiedby,lastmodifieddate,renderyn,groupyn,typefqn,displayname) VALUES (nextval('seq_eg_wf_types'),(SELECT id FROM eg_module WHERE name='Property Tax'),'PropertyMutation','/ptis/property/transfer/view.action?mutationId=:ID',1,now(),1,now(),'Y','N','org.egov.ptis.domain.entity.property.PropertyMutation','Property Owner Transfer');
INSERT INTO eg_wf_types (id,module,type,link,createdby,createddate,lastmodifiedby,lastmodifieddate,renderyn,groupyn,typefqn,displayname) VALUES (nextval('seq_eg_wf_types'),(SELECT id FROM eg_module WHERE name='Property Tax'),'RevisionPetition','/ptis/revPetition/revPetition-view.action?objectionId=:ID',1,now(),1,now(), 'Y', 'N','org.egov.ptis.domain.entity.objection.RevisionPetition', 'Revision Petition');
------------------END---------------------

-----------------START-------------------
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, VERSION, MODULE ) VALUES (nextval('SEQ_EG_APPCONFIG'), 'IS_CORPORATION', 'To know the ULB is Corporation or not',0, (select id from eg_module where name='Property Tax')); 
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE, VERSION ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='IS_CORPORATION'), current_date, '0',0);
------------------END---------------------

-----------------START-------------------
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'PTObejction','CREATED',now(),'CREATED',1);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'PTObejction','HEARING DATE FIXED',now(),'HEARING DATE FIXED',2);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'PTObejction','HEARING COMPLETED',now(),'HEARING COMPLETED',3);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'PTObejction','INSPECTION COMPLETED',now(),'INSPECTION COMPLETED',4);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'PTObejction','OBJECTION ACCEPTED',now(),'OBJECTION ACCEPTED',5);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'PTObejction','OBJECTION REJECTED',now(),'OBJECTION REJECTED',6);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'PTObejction','GENERATE HEARING NOTICE',now(),'GENERATE HEARING NOTICE',7);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'PTObejction','GENERATE ENDORSEMENT NOTICE',now(),'GENERATE ENDORSEMENT NOTICE',8);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'PTObejction','INSPECTION VERIFY',now(),'INSPECTION VERIFY',7);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'PTObejction','Rejected',now(),'Rejected',1);
------------------END---------------------