---Alter Assessment

delete from eg_wf_matrix where objecttype = 'PropertyImpl' and additionalrule='ALTER ASSESSMENT';

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:NEW', NULL,'Assistant approval pending','Senior Assistant,Junior Assistant', 'ALTER ASSESSMENT', 'Alter:Assistant Approved', 'Bill Collector Approval Pending', 'Bill Collector', 'Assistant Approved', 'Create', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Assistant Approved', NULL, 'Bill Collector Approval Pending', 'Bill Collector', 'ALTER ASSESSMENT', 'Alter:Bill Collector Approved', 'UD Revenue Inspector Approval Pending', 'UD Revenue Inspector', 'Bill Collector Approved', 'Forward,Reject', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Bill Collector Approved', NULL, 'UD Revenue Inspector Approval Pending', 'UD Revenue Inspector', 'ALTER ASSESSMENT', 'Alter:UD Revenue Inspector Approved', 'Revenue Officer Approval Pending', 'Revenue officer', 'UD Revenue Inspector Approved', 'Forward,Reject', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:UD Revenue Inspector Approved', NULL, 'Revenue Officer Approval Pending', 'Revenue officer', 'ALTER ASSESSMENT', 'Alter:Revenue Officer Approved', NULL, 'Assistant Commissioner,Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner','Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2015-04-01', '2099-04-01');


--Revenue Officer
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Revenue Officer Approved', NULL, 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'ALTER ASSESSMENT', 'Alter:Assistant Commissioner Approved', 'Digital Signature Pending', 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner','Assistant Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Revenue Officer Approved', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'ALTER ASSESSMENT', 'Alter:Zonal Commissioner Approved', 'Digital Signature Pending', 'Deputy Commissioner,Additional Commissioner,Commissioner','Assistant Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Revenue Officer Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'ALTER ASSESSMENT', 'Alter:Deputy Commissioner Approved', 'Digital Signature Pending', 'Additional Commissioner,Commissioner','Deputy Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Revenue Officer Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'ALTER ASSESSMENT', 'Alter:Additional Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Additional Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Revenue Officer Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'ALTER ASSESSMENT', 'Alter:Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Commissioner Approved', 'Approve,Reject', NULL, NULL, '2015-04-01', '2099-04-01');


--Assistant Commissioner
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Assistant Commissioner Approved', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'ALTER ASSESSMENT', 'Alter:Zonal Commissioner Approved', 'Digital Signature Pending', 'Deputy Commissioner,Additional Commissioner,Commissioner','Assistant Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Assistant Commissioner Approved', NULL, 'Digital Signature Pending', 'Zonal Commissioner', 'ALTER ASSESSMENT', 'Alter:Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Assistant Commissioner Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'ALTER ASSESSMENT', 'Alter:Deputy Commissioner Approved', 'Digital Signature Pending', 'Additional Commissioner,Commissioner','Deputy Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Assistant Commissioner Approved', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'ALTER ASSESSMENT', 'Alter:Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Assistant Commissioner Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'ALTER ASSESSMENT', 'Alter:Additional Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Additional Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Assistant Commissioner Approved', NULL, 'Digital Signature Pending', 'Assistant Commissioner', 'ALTER ASSESSMENT', 'Alter:Assistant Commissioner Approved', NULL, 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Assistant Commissioner Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'ALTER ASSESSMENT', 'Alter:Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Assistant Commissioner Approved', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'ALTER ASSESSMENT', 'Alter:Additional Commissioner Approved', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


----Zonal Commissioner
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Zonal Commissioner Approved', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'ALTER ASSESSMENT', 'Alter:Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Zonal Commissioner Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'ALTER ASSESSMENT', 'Alter:Deputy Commissioner Approved', 'Digital Signature Pending', 'Additional Commissioner,Commissioner',NULL, 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Zonal Commissioner Approved', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'ALTER ASSESSMENT', 'Alter:Additional Commissioner Approved', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Zonal Commissioner Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'ALTER ASSESSMENT', 'Alter:Additional Commissioner Approved', 'Digital Signature Pending', 'Commissioner',NULL, 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Zonal Commissioner Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'ALTER ASSESSMENT', 'Alter:Commissioner Approved', 'Digital Signature Pending', 'Commissioner',NULL, 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Zonal Commissioner Approved', NULL, 'Digital Signature Pending', 'Commissioner', 'ALTER ASSESSMENT', 'Alter:Commissioner Approved', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Zonal Commissioner Approved', NULL, 'Digital Signature Pending', 'Zonal Commissioner', 'ALTER ASSESSMENT', 'Alter:Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


----Deputy Commissioner
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Deputy Commissioner Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'ALTER ASSESSMENT', 'Alter:Additional Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Additional Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Deputy Commissioner Approved', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'ALTER ASSESSMENT', 'Alter:Additional Commissioner Approved', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Deputy Commissioner Approved', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'ALTER ASSESSMENT', 'Alter:Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Deputy Commissioner Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'ALTER ASSESSMENT', 'Alter:Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Commissioner Approved', 'Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');



--Additional Commissioner

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Additional Commissioner Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'ALTER ASSESSMENT', 'Alter:Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Commissioner Approved', 'Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Additional Commissioner Approved', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'ALTER ASSESSMENT', 'Alter:Additional Commissioner Approved', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


--Commissioner
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Commissioner Approved', NULL, 'Digital Signature Pending', 'Commissioner', 'ALTER ASSESSMENT', 'Alter:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Digitally Signed', NULL, 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'ALTER ASSESSMENT', 'Alter:END', 'END', NULL, NULL, 'Generate Notice', NULL, NULL, '2015-04-01', '2099-04-01');


----Rejection and common
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected', NULL, 'Assistant Approval Pending', 'Senior Assistant,Junior Assistant', 'ALTER ASSESSMENT', 'Alter:Assistant Approved', 'Bill Collector Approval Pending', 'Bill Collector', NULL, 'Forward,Reject', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Created', NULL, NULL, 'NULL', 'ALTER ASSESSMENT', 'Alter:NEW', 'Assistant approval pending', 'Senior Assistant,Junior Assistant', 'Assistant Approved', 'Forward', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected', NULL, 'UD Revenue Inspector Approval Pending', 'UD Revenue Inspector', 'ALTER ASSESSMENT', 'Alter:UD Revenue Inspector Approved', 'Revenue Officer Approval Pending', 'Revenue officer', NULL, 'Forward,Reject', NULL, NULL, '2015-04-01', '2099-04-01');

-----Rejection to cancel


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Assistant Commissioner', 'ALTER ASSESSMENT', 'Alter:Rejected to Cancel', NULL, 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Zonal Commissioner', 'ALTER ASSESSMENT', 'Alter:Rejected to Cancel', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'ALTER ASSESSMENT', 'Alter:Rejected to Cancel', NULL, 'Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'ALTER ASSESSMENT', 'Alter:Rejected to Cancel', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Commissioner', 'ALTER ASSESSMENT', 'Alter:Rejected to Cancel', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'ALTER ASSESSMENT', 'Alter:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'ALTER ASSESSMENT', 'Alter:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'ALTER ASSESSMENT', 'Alter:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'ALTER ASSESSMENT', 'Alter:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Alter:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Commissioner', 'ALTER ASSESSMENT', 'Alter:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');




---BIFURCATE ASSESSMENT

delete from eg_wf_matrix where objecttype = 'PropertyImpl' and additionalrule='BIFURCATE ASSESSMENT';

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:NEW', NULL, 'Assistant approval pending', 'Senior Assistant,Junior Assistant', 'BIFURCATE ASSESSMENT', 'Bifurcate:Assistant Approved', 'Bill Collector Approval Pending', 'Bill Collector', 'Assistant Approved', 'Create', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Assistant Approved', NULL, 'Bill Collector Approval Pending', 'Bill Collector', 'BIFURCATE ASSESSMENT', 'Bifurcate:Bill Collector Approved', 'UD Revenue Inspector Approval Pending', 'UD Revenue Inspector', 'Bill Collector Approved', 'Forward,Reject', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Bill Collector Approved', NULL, 'UD Revenue Inspector Approval Pending', 'UD Revenue Inspector', 'BIFURCATE ASSESSMENT', 'Bifurcate:UD Revenue Inspector Approved', 'Revenue Officer Approval Pending', 'Revenue officer', 'UD Revenue Inspector Approved', 'Forward,Reject', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:UD Revenue Inspector Approved', NULL, 'Revenue Officer Approval Pending', 'Revenue officer', 'BIFURCATE ASSESSMENT', 'Bifurcate:Revenue Officer Approved', NULL, 'Assistant Commissioner,Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner','Revenue Officer Approved', 'Forward,Reject', NULL, NULL, '2015-04-01', '2099-04-01');


--Revenue Officer
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Revenue Officer Approved', NULL, 'Assistant Commissioner Approval Pending', 'Assistant Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Assistant Commissioner Approved', 'Digital Signature Pending', 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner','Assistant Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Revenue Officer Approved', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Zonal Commissioner Approved', 'Digital Signature Pending', 'Deputy Commissioner,Additional Commissioner,Commissioner','Assistant Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Revenue Officer Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Deputy Commissioner Approved', 'Digital Signature Pending', 'Additional Commissioner,Commissioner','Deputy Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Revenue Officer Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Additional Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Additional Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Revenue Officer Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Commissioner Approved', 'Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');



--Assistant Commissioner

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Assistant Commissioner Approved', NULL, 'Zonal Commissioner Approval Pending', 'Zonal Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Zonal Commissioner Approved', 'Digital Signature Pending', 'Deputy Commissioner,Additional Commissioner,Commissioner','Assistant Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Assistant Commissioner Approved', NULL, 'Digital Signature Pending', 'Zonal Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Assistant Commissioner Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Deputy Commissioner Approved', 'Digital Signature Pending', 'Additional Commissioner,Commissioner','Deputy Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Assistant Commissioner Approved', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Assistant Commissioner Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Additional Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Additional Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Assistant Commissioner Approved', NULL, 'Digital Signature Pending', 'Assistant Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Assistant Commissioner Approved', NULL, 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Assistant Commissioner Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Assistant Commissioner Approved', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Additional Commissioner Approved', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


----Zonal Commissioner

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Zonal Commissioner Approved', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Zonal Commissioner Approved', NULL, 'Deputy Commissioner Approval Pending', 'Deputy Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Deputy Commissioner Approved', 'Digital Signature Pending', 'Additional Commissioner,Commissioner',NULL, 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Zonal Commissioner Approved', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Additional Commissioner Approved', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Zonal Commissioner Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Additional Commissioner Approved', 'Digital Signature Pending', 'Commissioner',NULL, 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Zonal Commissioner Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Commissioner Approved', 'Digital Signature Pending', 'Commissioner',NULL, 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Zonal Commissioner Approved', NULL, 'Digital Signature Pending', 'Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Commissioner Approved', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Zonal Commissioner Approved', NULL, 'Digital Signature Pending', 'Zonal Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Zonal Commissioner Approved', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


----Deputy Commissioner
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Deputy Commissioner Approved', NULL, 'Additional Commissioner Approval Pending', 'Additional Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Additional Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Additional Commissioner Approved', 'Forward,Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Deputy Commissioner Approved', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Additional Commissioner Approved', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Deputy Commissioner Approved', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Deputy Commissioner Approved', NULL, 'Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Deputy Commissioner Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Commissioner Approved', 'Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');



--Additional Commissioner
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Additional Commissioner Approved', NULL, 'Commissioner Approval Pending', 'Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Commissioner Approved', 'Digital Signature Pending', 'Commissioner','Commissioner Approved', 'Approve,Reject,Reject To Cancel', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Additional Commissioner Approved', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Additional Commissioner Approved', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


--Commissioner
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Commissioner Approved', NULL, 'Digital Signature Pending', 'Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Digitally Signed', NULL, 'Notice Print Pending', 'Senior Assistant,Junior Assistant', 'BIFURCATE ASSESSMENT', 'Bifurcate:END', 'END', NULL, NULL, 'Generate Notice', NULL, NULL, '2015-04-01', '2099-04-01');


----Rejection and common
INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected', NULL, 'Assistant Approval Pending', 'Senior Assistant,Junior Assistant', 'BIFURCATE ASSESSMENT', 'Bifurcate:Assistant Approved', 'Bill Collector Approval Pending', 'Bill Collector', NULL, 'Forward,Reject', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Created', NULL, NULL, 'NULL', 'BIFURCATE ASSESSMENT', 'Bifurcate:NEW', 'Assistant approval pending', 'Senior Assistant,Junior Assistant', 'Assistant Approved', 'Forward', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected', NULL, 'UD Revenue Inspector Approval Pending', 'UD Revenue Inspector', 'BIFURCATE ASSESSMENT', 'Bifurcate:UD Revenue Inspector Approved', 'Revenue Officer Approval Pending', 'Revenue officer', NULL, 'Forward,Reject', NULL, NULL, '2015-04-01', '2099-04-01');


-----Rejection to cancel


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Assistant Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Rejected to Cancel', NULL, 'Zonal Commissioner,Deputy Commissioner,Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Zonal Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Rejected to Cancel', NULL, 'Deputy Commissioner,Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Rejected to Cancel', NULL, 'Additional Commissioner,Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Rejected to Cancel', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');

INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Rejected to Cancel', NULL, 'Commissioner',NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Deputy Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Additional Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Forward,Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');


INSERT INTO eg_wf_matrix (id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate) VALUES (NEXTVAL('seq_eg_wf_matrix'), 'ANY', 'PropertyImpl', 'Bifurcate:Rejected to Cancel', NULL, 'Digital Signature Pending', 'Commissioner', 'BIFURCATE ASSESSMENT', 'Bifurcate:Digitally Signed', 'Notice Print Pending', NULL, NULL, 'Preview,Sign', NULL, NULL, '2015-04-01', '2099-04-01');




