
update eg_wf_matrix set currentstate='Approver Rejected Application' ,nextaction='Approver Approval Pending',nextdesignation='Commissioner' where currentstate='Assistant Engineer Rejected' and objecttype='MarriageRegistration';
update eg_wf_matrix set currentstate='Application Approved',currentdesignation='Commissioner'  where currentstate='Assistant Engineer Approved' and objecttype='MarriageRegistration';
update eg_wf_matrix set nextstate='Application Approved',nextstatus='APPROVED' where currentstate='Revenue Clerk Approved' and objecttype='MarriageRegistration';
update eg_wf_matrix set nextaction='Approver Approval Pending',nextstatus='CREATED',nextdesignation='Commissioner' where currentstate='NEW' and objecttype='MarriageRegistration';

update eg_wf_matrix set currentstate='Approver Rejected Application', nextaction='Approver Approval Pending',nextdesignation='Commissioner' where currentstate='Assistant Engineer Rejected' and objecttype='ReIssue';
update eg_wf_matrix set currentstate='Application Approved',currentdesignation='Commissioner'  where currentstate='Assistant Engineer Approved' and objecttype='ReIssue';
update eg_wf_matrix set nextstate='Application Approved',nextstatus='APPROVED' where currentstate='Revenue Clerk Approved' and objecttype='ReIssue';
update eg_wf_matrix set nextaction='Approver Approval Pending',nextstatus='CREATED',nextdesignation='Commissioner' where currentstate='NEW' and objecttype='ReIssue';


--INSERT INTO eg_wf_matrix( id, department, objecttype, currentstate, currentstatus, pendingactions,currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, version) VALUES (nextval('eg_wf_matrix_seq'),'ANY','MarriageRegistration','Assistant Engineer Rejected','','','Revenue Clerk','MARRIAGE REGISTRATION','Revenue Clerk Approved','Asst. engineer Approval Pending','Assistant engineer','','Forward,Cancel Registration','','','2016-04-01','2099-04-01',0);
--INSERT INTO eg_wf_matrix( id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, version)   VALUES (nextval('eg_wf_matrix_seq'),'ANY','MarriageRegistration','Assistant Engineer Approved','','Certificate Print Pending','Revenue Clerk','MARRIAGE REGISTRATION','END','END','','','Print Certificate','','','2016-04-01','2099-04-01',0);
--INSERT INTO eg_wf_matrix( id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, version)  VALUES (nextval('eg_wf_matrix_seq'),'ANY','MarriageRegistration','Revenue Clerk Approved','','','Assistant Engineer','MARRIAGE REGISTRATION','Assistant Engineer Approved','Certificate Print Pending','Revenue Clerk','Assistant Engineer Approved','Approve,Reject','','','2016-04-01','2099-04-01',0);
--INSERT INTO eg_wf_matrix( id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, version)  VALUES (nextval('eg_wf_matrix_seq'),'ANY','MarriageRegistration','NEW','','','Revenue Clerk','MARRIAGE REGISTRATION','Revenue Clerk Approved','Asst. engineer Approval Pending','Assistant engineer','Revenue Clerk Approved','Forward','','','2016-04-01','2099-04-01',0);

--INSERT INTO eg_wf_matrix( id, department, objecttype, currentstate, currentstatus, pendingactions,currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, version) VALUES (nextval('eg_wf_matrix_seq'),'ANY','ReIssue','Assistant Engineer Rejected','','','Revenue Clerk','MARRIAGE REGISTRATION','Revenue Clerk Approved','Asst. engineer Approval Pending','Assistant engineer','','Forward,Cancel Registration','','','2016-04-01','2099-04-01',0);
--INSERT INTO eg_wf_matrix( id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, version)   VALUES (nextval('eg_wf_matrix_seq'),'ANY','ReIssue','Assistant Engineer Approved','','Certificate Print Pending','Revenue Clerk','MARRIAGE REGISTRATION','END','END','','','Print Certificate','','','2016-04-01','2099-04-01',0);
--INSERT INTO eg_wf_matrix( id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, version)  VALUES (nextval('eg_wf_matrix_seq'),'ANY','ReIssue','Revenue Clerk Approved','','','Assistant Engineer','MARRIAGE REGISTRATION','Assistant Engineer Approved','Certificate Print Pending','Revenue Clerk','Assistant Engineer Approved','Approve,Reject','','','2016-04-01','2099-04-01',0);
--INSERT INTO eg_wf_matrix( id, department, objecttype, currentstate, currentstatus, pendingactions, currentdesignation, additionalrule, nextstate, nextaction, nextdesignation, nextstatus, validactions, fromqty, toqty, fromdate, todate, version)  VALUES (nextval('eg_wf_matrix_seq'),'ANY','ReIssue','NEW','','','Revenue Clerk','MARRIAGE REGISTRATION','Revenue Clerk Approved','Asst. engineer Approval Pending','Assistant engineer','Revenue Clerk Approved','Forward','','','2016-04-01','2099-04-01',0);
