------------------------START-----------------------------
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Surrendered',to_date('23-01-10','DD-MM-RR'),'Surrendered',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','New',to_date('22-11-09','DD-MM-RR'),'New',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Deposited',to_date('22-11-09','DD-MM-RR'),'Deposited',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Reconciled',to_date('22-11-09','DD-MM-RR'),'Reconciled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Cancelled',to_date('22-11-09','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Dishonored',to_date('22-11-09','DD-MM-RR'),'Dishonored',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Planning',to_date('01-06-07','DD-MM-RR'),'Planning',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Approved',to_date('01-06-07','DD-MM-RR'),'Approved',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Closed',to_date('01-06-07','DD-MM-RR'),'Closed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Created',to_date('01-06-07','DD-MM-RR'),'Created',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Verified',to_date('01-06-07','DD-MM-RR'),'Verified',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Confirmed',to_date('01-06-07','DD-MM-RR'),'Confirmed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Checked',to_date('01-06-07','DD-MM-RR'),'Checked',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Mark For Checking',to_date('01-06-07','DD-MM-RR'),'Mark For Checking',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Concurrence',to_date('01-06-07','DD-MM-RR'),'Concurrence',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Created',to_date('26-05-10','DD-MM-RR'),'Created',1);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Approved',to_date('26-05-10','DD-MM-RR'),'Approved',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Cancelled',to_date('26-05-10','DD-MM-RR'),'Cancelled',3);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','APPROVED',to_date('28-03-10','DD-MM-RR'),'APPROVED',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Created By DO',to_date('17-06-13','DD-MM-RR'),'Created By DO',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Created By SM',to_date('17-06-13','DD-MM-RR'),'Created By SM',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','CREATED',to_date('28-03-10','DD-MM-RR'),'CREATED',1);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','Approved',to_date('28-03-10','DD-MM-RR'),'Approved',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','Voucher Created',to_date('28-03-10','DD-MM-RR'),'Voucher Created',3);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','Cancelled',to_date('28-03-10','DD-MM-RR'),'Cancelled',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Surrender_For_Reassign',to_date('16-09-10','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BudgetReAppropriation','New',to_date('25-01-11','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BudgetReAppropriation','Approved',to_date('25-01-11','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BudgetReAppropriation','Cancelled',to_date('25-01-11','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','CREATED',to_date('01-06-07','DD-MM-RR'),'CREATED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','VERIFIED',to_date('01-06-07','DD-MM-RR'),'VERIFIED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','ACCOUNTS APPROVAL',to_date('01-06-07','DD-MM-RR'),'ACCOUNTS APPROVAL',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','Voucher Created',to_date('01-06-07','DD-MM-RR'),'Voucher Created',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','PAYMENT APPROVED',to_date('27-06-07','DD-MM-RR'),'PAYMENT APPROVED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','PAYMENT CONFIRMED',to_date('27-06-07','DD-MM-RR'),'PAYMENT CONFIRMED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Created',to_date('10-07-07','DD-MM-RR'),'Created',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Approved',to_date('10-07-07','DD-MM-RR'),'Approved',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Passed',to_date('10-07-07','DD-MM-RR'),'Passed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Paid',to_date('10-07-07','DD-MM-RR'),'Paid',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Cancelled',to_date('01-02-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Pending',to_date('01-02-08','DD-MM-RR'),'Pending',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Passed',to_date('01-02-08','DD-MM-RR'),'Passed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Cancelled',to_date('01-02-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Paid',to_date('01-02-08','DD-MM-RR'),'Paid',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Pending',to_date('01-02-08','DD-MM-RR'),'Pending',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Passed',to_date('01-02-08','DD-MM-RR'),'Passed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Cancelled',to_date('01-02-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Paid',to_date('01-02-08','DD-MM-RR'),'Paid',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','Cancelled',to_date('17-03-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Rejected',to_date('22-09-13','DD-MM-RR'),'Rejected',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','dishonour cheque in workflow',to_date('02-01-14','DD-MM-RR'),'InWorkflow',null);
---------------------------------END------------------------------
------------------------START-----------------------------
Insert into eg_wf_types (id,module,type,link,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,RENDERYN,GROUPYN,TYPEFQN,DISPLAYNAME) values (nextval('seq_eg_wf_types'),(select ID_MODULE from eg_module where MODULE_NAME = 'Budgeting'),'BudgetDetail','/EGF/budget/budgetProposal!modifyDetailList.action?budgetDetail.id=:ID&mode=approve',1,null,null,null,'Y','N','org.egov.model.budget.BudgetDetail','BudgetDetail');
Insert into eg_wf_types (id,module,type,link,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,RENDERYN,GROUPYN,TYPEFQN,DISPLAYNAME) values (nextval('seq_eg_wf_types'),(select ID_MODULE from eg_module where MODULE_NAME = 'Budgeting'),'BudgetReAppropriationMisc','/EGF/budget/budgetReAppropriationModify!approvalList.action?budgetReAppropriation.reAppropriationMisc.id=:ID',1,null,null,null,'Y','N','org.egov.model.budget.BudgetReAppropriationMisc','Budget ReAppropriation');
Insert into eg_wf_types (id,module,type,link,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,RENDERYN,GROUPYN,TYPEFQN,DISPLAYNAME) values (nextval('seq_eg_wf_types'),(select ID_MODULE from eg_module where MODULE_NAME = 'EGF'),'Paymentheader','/EGF/payment/basePayment!viewInboxItems.action?paymentid=:ID',null,null,null,null,'Y','N','org.egov.model.payment.Paymentheader','Payment');
Insert into eg_wf_types (id,module,type,link,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,RENDERYN,GROUPYN,TYPEFQN,DISPLAYNAME) values (nextval('seq_eg_wf_types'),(select ID_MODULE from eg_module where MODULE_NAME = 'Budgeting'),'Budget','/EGF/budget/budgetProposal!modifyBudgetDetailList.action?budgetDetail.budget.id=:ID&mode=approve',1,null,null,null,'Y','N','org.egov.model.budget.Budget','Budget');
Insert into eg_wf_types (id,module,type,link,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,RENDERYN,GROUPYN,TYPEFQN,DISPLAYNAME) values (nextval('seq_eg_wf_types'),(select ID_MODULE from eg_module where MODULE_NAME = 'EGF'),'CVoucherHeader','/EGF/voucher/preApprovedVoucher!loadvoucher.action?vhid=:ID\&from=Journal Voucher',null,null,null,null,'Y','N','org.egov.commons.CVoucherHeader','Voucher');
Insert into eg_wf_types (id,module,type,link,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,RENDERYN,GROUPYN,TYPEFQN,DISPLAYNAME) values (nextval('seq_eg_wf_types'),(select ID_MODULE from eg_module where MODULE_NAME = 'EGF'),'ContraJournalVoucher','/EGF/voucher/preApprovedVoucher!loadvoucherview.action?vhid=:ID\&from=Contra',null,null,null,null,'Y','N','org.egov.model.contra.ContraJournalVoucher','Contra Voucher');
Insert into eg_wf_types (id,module,type,link,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,RENDERYN,GROUPYN,TYPEFQN,DISPLAYNAME) values (nextval('seq_eg_wf_types'),(select ID_MODULE from eg_module where MODULE_NAME = 'Bill Registers'),'Cbill','/EGF/bill/contingentBill!beforeView.action?billRegisterId=:ID&mode=approve',1,null,null,null,'Y','N','org.egov.egf.bills.model.Cbill','ExpenseBill');
Insert into eg_wf_types (id,module,type,link,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,RENDERYN,GROUPYN,TYPEFQN,DISPLAYNAME) values (nextval('seq_eg_wf_types'),(select ID_MODULE from eg_module where MODULE_NAME = 'EGF'),'ReceiptVoucher','/EGF/voucher/preApprovedVoucher!loadvoucherview.action?vhid=:ID\&from=Receipt',null,null,null,null,'Y','N','org.egov.model.receipt.ReceiptVoucher','Receipt Voucher');
Insert into eg_wf_types (id,module,type,link,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,RENDERYN,GROUPYN,TYPEFQN,DISPLAYNAME) values (nextval('seq_eg_wf_types'),(select ID_MODULE from eg_module where MODULE_NAME = 'BRS'),'DishonorCheque','/EGF/payment/dishonorChequeWorkflow!view.action?dishonourChqId=:ID',1,to_date('20-01-14','DD-MM-RR'),null,null,'Y','N','org.egov.model.instrument.DishonorCheque','Dishonor Cheque');
---------------------------------END------------------------------

-----------------------------------START-------------------------
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'exclude_status_forbudget_actual','exclude voucher status for budget','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetaryCheck_budgettype_cashbased','budgetaryCheck budgettype','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_final_approval_status','Final Approval status for budget','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'pjv_saveasworkingcopy_enabled','pjv_saveasworkingcopy_enabled','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Bill_Number_Geneartion_Auto','bill number genration auto or manual ','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'cancelledstatus','Cancelled status for voucher','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'contingencyBillPurposeIds','Contingent Bill PurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'VOUCHER_STATUS_TO_CHECK_BANK_BALANCE','VOUCHER_STATUS_TO_CHECK_BANK_BALANCE','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'salaryBillPurposeIds','Salary Bill PurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'salaryBillDefaultPurposeId','Salary Bill Default PurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'bank_balance_mandatory','bank_balance_mandatory','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PurchaseBillApprovalStatus','Purchase bill Status for approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'WorksBillApprovalStatus','Works bill Status for approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'ExpenseBillApprovalStatus','Contingency bill Status for approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'SalaryBillApprovalStatus','Salary bill Status for approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Balance Check Based on Fund Flow Report','Check Balance  Based on Fund Flow Report Or Not','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'add_less_codes_for_ie_report','add and less codes for ie report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'planning_budget_multiplication_factor','planning budget multiplication factor','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'CONSIDER_RE_REAPPROPRIATION_AS_SEPARATE','Whether or not to consider re_reappropriation as seperate in budget reports','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'pensionBillPurposeIds','Pension Bill PurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PensionBillApprovalStatus','Pension bill Status for approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_SMlevel_approver_designation','budget_SMlevel_approver_designation','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'USE BILLDATE IN CREATE VOUCHER FROM BILL','USE BILLDATE IN CREATE VOUCHER FROM BILL','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'WORKS VOUCHERS RESTRICTION DATE FROM JV SCREEN','WORKS VOUCHERS RESTRICTION DATE FROM JV SCREEN','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'GJV_FOR_RCPT_CHQ_DISHON','Generate Journal Voucher on dishonoring receipt cheque','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'loangrant.default.fundid','if fund id is present it is defaulted else selection made mandatory','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'BANKBALANCE_CHECK_DATE','Fund Flow BANKBALANCE_CHECK_DATE','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-272','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'CONTRACTOR_ADVANCE_CODE','Contractor Advance Payable','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'contingencyBillDefaultPurposeId',' default Purpose ids for Contingency','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Communication Expenses','ContingentBill-Telephone-CheckList','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Electricity Charges','ContingentBill-Electricity-CheckList','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Others','ContingentBill-Others-CheckList','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PAYMENT_WF_STATUS_FOR_BANK_BALANCE_CHECK','PAYMENT_WF_STATUS_FOR_BANK_BALANCE_CHECK','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DEFAULT_SEARCH_MISATTRRIBUTES','default search mis attributes','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_toplevel_approver_designation','budget_toplevel_approver_designation','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_secondlevel_approver_designation','Functionary contains colon','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Reason For Cheque Surrendaring',' Reasons for cheque surrendering','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PREAPPROVEDVOUCHERSTATUS','voucher status before approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'APPROVEDVOUCHERSTATUS','next state of approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DEFAULTVOUCHERCREATIONSTATUS','DEFAULTVOUCHERCREATIONSTATUS','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_detailcode_length','detailcode length length','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetgroup_range_minor_or_detailed','budgetgroup_range_minor_or_detailed','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_minorcode_length','minorcode length','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_majorcode_length','majorcode length','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetaryCheck_groupby_values','budgetarycheck group by values','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_subminorcode_length','subminorcode length','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'purchaseBillPurposeIds','purchaseBillPurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'worksBillPurposeIds','worksBillPurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'parent_for_detailcode','parent length for detailed code','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Cheque_no_generation_auto','Cheque_nogeneration','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'cheque.assignment.infavourof','cheque.assignment.infavourof','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'boundaryforaccounts','This is the boundary at which books of accounts are maintained','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DEFAULTTXNMISATTRRIBUTES','default transaction mis attributes','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'JournalVoucher_ConfirmonCreate','journal voucher create isconfirmed value','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'bs_report_half_yearly','balance sheet report half yearly date (dd/mm)','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'REPORT_SEARCH_MISATTRRIBUTES','default search mis attributes','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetDetail_mandatory_fields','Budget Detail mandatroy fields','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetCheckRequired','budgetCheckRequired','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'RTGSNO_GENERATION_AUTO','RTGSNO_GENERATION_AUTO','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DATE_RESTRICTION_FOR_CJV_PAYMENT_MODE_AS_RTGS','Whether RTGS should be the only mode of payment for CJVs for the bill date','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Remove Entrys With Zero Amount','Value to deside Remove Entrys With Zero Amount in Reports','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'ifRestrictedToOneFunctionCenter','ifRestrictedToOneFunctionCenter','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'VOUCHERDATE_FROM_UI','GET VOUCHERDATE FROM UI','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'CJV_PAYMENT_MODE_AS_RTGS','Whether RTGS should be the only mode of payment for CJVs','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Remove Entries With Zero Amount in Report','Value to deside Remove Entries With Zero Amount in Reports','EGF');
--------------------------------END---------------------------------------------------------
------------------------START-------------------------
update eg_module set enabled=false where name='Assigned Revenue Reports';
update eg_module set enabled=false where name='TNEB';

update eg_action set enabled=false where name='Reverse Bills-Search';
update eg_action set enabled=false where name='Modify Payments-Search';
update eg_action set enabled=false where name='Modify Fund Flow Analysis Report';
update eg_action set enabled=false where name='Fund Flow Analysis Report';
update eg_action set enabled=false where name='Outstanding Payment';
update eg_action set enabled=false where name='Concurrence Report';
update eg_action set enabled=false where name='ManualEntryReport';
update eg_action set enabled=false where name='Reverse Journal Vouchers-Search';
update eg_action set enabled=false where name='Cash Withdrawal';
update eg_action set enabled=false where name='Reverse Contra Entries-Search';

update eg_action set enabled=false where name='AutoReconcile';
update eg_action set enabled=false where name='AutoReconcile-Upload';
update eg_action set enabled=false where name='Confirm Vouchers';
update eg_action set enabled=false where name='ScheduleRemittanceManual';
update eg_action set enabled=false where name='RTGSAssignmentforPayment';
update eg_action set enabled=false where name='Creditors Recoveries';
update eg_action set enabled=false where name='Setup Cheque in Hand/Cash in Hand';
update eg_action set enabled=false where name='Add Bank';
update eg_action set enabled=false where name='AutoRemittanceReport';
update eg_action set enabled=false where name='AutoRemittanceSchedulerReport';
update eg_action set enabled = false where displayname ='Add/Modify Branch-Modify Bank';
------------------------END-------------------
------------------------START-------------------------
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (4,'Cash In Hand',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (5,'Cheque In Hand',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (7,'ExcessIE',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (8,' Payable to Other Funds',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (10,'Contractor Deductions',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (16,'CWIP Account code',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (21,'Fixed Assets Written off',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (22,'Inter-Unit Transfer Account',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (26,'Creditors-Contractor Payable',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (27,'Creditors-Supplier Payable',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (28,'Contigency Bill Code',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (29,'Security Deposit',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (30,'Bank Charges',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (31,'Salary Payable',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (35,'Supplier Advance Account',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (37,'Material Clearing Account',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (38,'Scrap Suspense Account',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (60,'Overhead_account codes',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (61,'DEPOSIT:OTHER WORKS',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (62,'REPAIRS AND MAINTENANCE',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (95,'RETENTION_MONEY',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (96,'LandEstate_Rent_purpose',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (103,'Pension Payable Code',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (105,'CONTRACTOR_ADVANCE_ACCOUNTCODE',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (120,'BPA Deposit CWIP Account Code',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (34,'Pension Payable',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (36,'Wages Payable',current_date,1,current_date,1);
update egf_accountcode_purpose set id = 11 where name = 'Fixed Assets';
update egf_accountcode_purpose set id = 15 where name = 'Accumulated Depreciation';
update egf_accountcode_purpose set id = 17 where name = 'Depreciation Expense Account';
update egf_accountcode_purpose set id = 18 where name = 'Revaluation Reserve Account';
------------------------END-------------------