ALTER TABLE EG_ADVANCEREQUISITIONMIS ADD COLUMN BILLREGISTER bigint;
ALTER TABLE EG_ADVANCEREQUISITIONMIS add constraint FK_EG_ADVANCEREQUISITIONMIS_BILLREGISTER  FOREIGN KEY (BILLREGISTER) REFERENCES EG_BILLREGISTER(id);

--rollback ALTER TABLE EG_ADVANCEREQUISITIONMIS DROP COLUMN BILLREGISTER;