insert into EG_APPCONFIG (ID,KEY_NAME,DESCRIPTION,VERSION,MODULE) values (nextval('seq_eg_appconfig'),'auto_bankaccount_glcode',
'GlCode to be autogenerated',0,(select id from eg_module where name='EGF'));

insert into EG_APPCONFIG_VALUES (ID,KEY_ID,EFFECTIVE_FROM,VALUE,VERSION) values (nextval('seq_eg_appconfig_values'),
(select id from EG_APPCONFIG where KEY_NAME ='auto_bankaccount_glcode'),current_date,'Yes',0);