ALTER TABLE EG_ADVANCEREQPAYEEDETAILS DROP COLUMN LASTUPDATEDTIME;
ALTER TABLE EG_ADVANCEREQPAYEEDETAILS ADD COLUMN version bigint DEFAULT 0;
ALTER TABLE EG_ADVANCEREQPAYEEDETAILS ADD COLUMN createdby bigint;
ALTER TABLE EG_ADVANCEREQPAYEEDETAILS ADD COLUMN lastmodifiedby bigint;
ALTER TABLE EG_ADVANCEREQPAYEEDETAILS ADD COLUMN createddate timestamp without time zone;
ALTER TABLE EG_ADVANCEREQPAYEEDETAILS ADD COLUMN lastModifieddate timestamp without time zone;

ALTER TABLE EG_ADVANCEREQUISITIONDETAILS DROP COLUMN LASTUPDATEDTIME;
ALTER TABLE EG_ADVANCEREQUISITIONDETAILS ADD COLUMN version bigint DEFAULT 0;
ALTER TABLE EG_ADVANCEREQUISITIONDETAILS ADD COLUMN createdby bigint;
ALTER TABLE EG_ADVANCEREQUISITIONDETAILS ADD COLUMN lastmodifiedby bigint;
ALTER TABLE EG_ADVANCEREQUISITIONDETAILS ADD COLUMN createddate timestamp without time zone;
ALTER TABLE EG_ADVANCEREQUISITIONDETAILS ADD COLUMN lastModifieddate timestamp without time zone;

ALTER TABLE EG_ADVANCEREQUISITIONMIS DROP COLUMN LASTUPDATEDTIME;
ALTER TABLE EG_ADVANCEREQUISITIONMIS ADD COLUMN version bigint DEFAULT 0;
ALTER TABLE EG_ADVANCEREQUISITIONMIS ADD COLUMN createdby bigint;
ALTER TABLE EG_ADVANCEREQUISITIONMIS ADD COLUMN lastmodifiedby bigint;
ALTER TABLE EG_ADVANCEREQUISITIONMIS ADD COLUMN createddate timestamp without time zone;
ALTER TABLE EG_ADVANCEREQUISITIONMIS ADD COLUMN lastModifieddate timestamp without time zone;

--rollback ALTER TABLE EG_ADVANCEREQUISITIONMIS DROP COLUMN version;
--rollback ALTER TABLE EG_ADVANCEREQUISITIONMIS DROP COLUMN createdby;
--rollback ALTER TABLE EG_ADVANCEREQUISITIONMIS DROP COLUMN lastmodifiedby;
--rollback ALTER TABLE EG_ADVANCEREQUISITIONMIS DROP COLUMN createddate;
--rollback ALTER TABLE EG_ADVANCEREQUISITIONMIS DROP COLUMN lastModifieddate;
--rollback ALTER TABLE EG_ADVANCEREQUISITIONMIS ADD COLUMN LASTUPDATEDTIME timestamp without time zone;

--rollback ALTER TABLE EG_ADVANCEREQUISITIONDETAILS DROP COLUMN version;
--rollback ALTER TABLE EG_ADVANCEREQUISITIONDETAILS DROP COLUMN createdby;
--rollback ALTER TABLE EG_ADVANCEREQUISITIONDETAILS DROP COLUMN lastmodifiedby;
--rollback ALTER TABLE EG_ADVANCEREQUISITIONDETAILS DROP COLUMN createddate;
--rollback ALTER TABLE EG_ADVANCEREQUISITIONDETAILS DROP COLUMN lastModifieddate;
--rollback ALTER TABLE EG_ADVANCEREQUISITIONDETAILS ADD COLUMN LASTUPDATEDTIME timestamp without time zone;

--rollback ALTER TABLE EG_ADVANCEREQPAYEEDETAILS DROP COLUMN version;
--rollback ALTER TABLE EG_ADVANCEREQPAYEEDETAILS DROP COLUMN createdby;
--rollback ALTER TABLE EG_ADVANCEREQPAYEEDETAILS DROP COLUMN lastmodifiedby;
--rollback ALTER TABLE EG_ADVANCEREQPAYEEDETAILS DROP COLUMN createddate;
--rollback ALTER TABLE EG_ADVANCEREQPAYEEDETAILS DROP COLUMN lastModifieddate;
--rollback ALTER TABLE EG_ADVANCEREQPAYEEDETAILS ADD COLUMN LASTUPDATEDTIME timestamp without time zone;