ALTER TABLE EG_ADVANCEREQUISITION ADD COLUMN version bigint DEFAULT 0;
ALTER TABLE EG_ADVANCEREQUISITION ALTER COLUMN arftype DROP NOT NULL;

--rollback ALTER TABLE EG_ADVANCEREQUISITION ALTER COLUMN arftype SET NOT NULL;
--rollback ALTER TABLE EG_ADVANCEREQUISITION DROP COLUMN version;