------------------------START-----------------------------
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Surrendered',to_date('23-01-10','DD-MM-RR'),'Surrendered',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','New',to_date('22-11-09','DD-MM-RR'),'New',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Deposited',to_date('22-11-09','DD-MM-RR'),'Deposited',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Reconciled',to_date('22-11-09','DD-MM-RR'),'Reconciled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Cancelled',to_date('22-11-09','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Dishonored',to_date('22-11-09','DD-MM-RR'),'Dishonored',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Planning',to_date('01-06-07','DD-MM-RR'),'Planning',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Approved',to_date('01-06-07','DD-MM-RR'),'Approved',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Closed',to_date('01-06-07','DD-MM-RR'),'Closed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Created',to_date('01-06-07','DD-MM-RR'),'Created',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Verified',to_date('01-06-07','DD-MM-RR'),'Verified',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Confirmed',to_date('01-06-07','DD-MM-RR'),'Confirmed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Checked',to_date('01-06-07','DD-MM-RR'),'Checked',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Mark For Checking',to_date('01-06-07','DD-MM-RR'),'Mark For Checking',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Concurrence',to_date('01-06-07','DD-MM-RR'),'Concurrence',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Created',to_date('26-05-10','DD-MM-RR'),'Created',1);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Approved',to_date('26-05-10','DD-MM-RR'),'Approved',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Cancelled',to_date('26-05-10','DD-MM-RR'),'Cancelled',3);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','APPROVED',to_date('28-03-10','DD-MM-RR'),'APPROVED',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Created By DO',to_date('17-06-13','DD-MM-RR'),'Created By DO',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Created By SM',to_date('17-06-13','DD-MM-RR'),'Created By SM',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','CREATED',to_date('28-03-10','DD-MM-RR'),'CREATED',1);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','Approved',to_date('28-03-10','DD-MM-RR'),'Approved',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','Voucher Created',to_date('28-03-10','DD-MM-RR'),'Voucher Created',3);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','Cancelled',to_date('28-03-10','DD-MM-RR'),'Cancelled',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Surrender_For_Reassign',to_date('16-09-10','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BudgetReAppropriation','New',to_date('25-01-11','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BudgetReAppropriation','Approved',to_date('25-01-11','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BudgetReAppropriation','Cancelled',to_date('25-01-11','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','CREATED',to_date('01-06-07','DD-MM-RR'),'CREATED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','VERIFIED',to_date('01-06-07','DD-MM-RR'),'VERIFIED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','ACCOUNTS APPROVAL',to_date('01-06-07','DD-MM-RR'),'ACCOUNTS APPROVAL',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','Voucher Created',to_date('01-06-07','DD-MM-RR'),'Voucher Created',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','PAYMENT APPROVED',to_date('27-06-07','DD-MM-RR'),'PAYMENT APPROVED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','PAYMENT CONFIRMED',to_date('27-06-07','DD-MM-RR'),'PAYMENT CONFIRMED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Created',to_date('10-07-07','DD-MM-RR'),'Created',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Approved',to_date('10-07-07','DD-MM-RR'),'Approved',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Passed',to_date('10-07-07','DD-MM-RR'),'Passed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Paid',to_date('10-07-07','DD-MM-RR'),'Paid',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Cancelled',to_date('01-02-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Pending',to_date('01-02-08','DD-MM-RR'),'Pending',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Passed',to_date('01-02-08','DD-MM-RR'),'Passed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Cancelled',to_date('01-02-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Paid',to_date('01-02-08','DD-MM-RR'),'Paid',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Pending',to_date('01-02-08','DD-MM-RR'),'Pending',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Passed',to_date('01-02-08','DD-MM-RR'),'Passed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Cancelled',to_date('01-02-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Paid',to_date('01-02-08','DD-MM-RR'),'Paid',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','Cancelled',to_date('17-03-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Rejected',to_date('22-09-13','DD-MM-RR'),'Rejected',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','dishonour cheque in workflow',to_date('02-01-14','DD-MM-RR'),'InWorkflow',null);
---------------------------------END------------------------------
------------------------START-----------------------------
INSERT INTO eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, renderyn, groupyn, typefqn, displayname, version) VALUES (2, 303, 'BudgetDetail', '/EGF/budget/budgetProposal!modifyDetailList.action?budgetDetail.id=:ID&mode=approve', 1, NULL, NULL, NULL, 'Y', 'N', 'org.egov.model.budget.BudgetDetail', 'BudgetDetail', NULL);
INSERT INTO eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, renderyn, groupyn, typefqn, displayname, version) VALUES (3, 303, 'BudgetReAppropriationMisc', '/EGF/budget/budgetReAppropriationModify!approvalList.action?budgetReAppropriation.reAppropriationMisc.id=:ID', 1, NULL, NULL, NULL, 'Y', 'N', 'org.egov.model.budget.BudgetReAppropriationMisc', 'Budget ReAppropriation', NULL);
INSERT INTO eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, renderyn, groupyn, typefqn, displayname, version) VALUES (4, 302, 'Paymentheader', '/EGF/payment/basePayment!viewInboxItems.action?paymentid=:ID', NULL, NULL, NULL, NULL, 'Y', 'N', 'org.egov.model.payment.Paymentheader', 'Payment', NULL);
INSERT INTO eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, renderyn, groupyn, typefqn, displayname, version) VALUES (5, 303, 'Budget', '/EGF/budget/budgetProposal!modifyBudgetDetailList.action?budgetDetail.budget.id=:ID&mode=approve', 1, NULL, NULL, NULL, 'Y', 'N', 'org.egov.model.budget.Budget', 'Budget', NULL);
INSERT INTO eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, renderyn, groupyn, typefqn, displayname, version) VALUES (6, 302, 'CVoucherHeader', '/EGF/voucher/preApprovedVoucher!loadvoucher.action?vhid=:ID\&from=Journal Voucher', NULL, NULL, NULL, NULL, 'Y', 'N', 'org.egov.commons.CVoucherHeader', 'Voucher', NULL);
INSERT INTO eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, renderyn, groupyn, typefqn, displayname, version) VALUES (7, 302, 'ContraJournalVoucher', '/EGF/voucher/preApprovedVoucher!loadvoucherview.action?vhid=:ID\&from=Contra', NULL, NULL, NULL, NULL, 'Y', 'N', 'org.egov.model.contra.ContraJournalVoucher', 'Contra Voucher', NULL);
INSERT INTO eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, renderyn, groupyn, typefqn, displayname, version) VALUES (8, 347, 'Cbill', '/EGF/bill/contingentBill!beforeView.action?billRegisterId=:ID&mode=approve', 1, NULL, NULL, NULL, 'Y', 'N', 'org.egov.egf.bills.model.Cbill', 'ExpenseBill', NULL);
INSERT INTO eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, renderyn, groupyn, typefqn, displayname, version) VALUES (9, 302, 'ReceiptVoucher', '/EGF/voucher/preApprovedVoucher!loadvoucherview.action?vhid=:ID\&from=Receipt', NULL, NULL, NULL, NULL, 'Y', 'N', 'org.egov.model.receipt.ReceiptVoucher', 'Receipt Voucher', NULL);
INSERT INTO eg_wf_types (id, module, type, link, createdby, createddate, lastmodifiedby, lastmodifieddate, renderyn, groupyn, typefqn, displayname, version) VALUES (10, 328, 'DishonorCheque', '/EGF/payment/dishonorChequeWorkflow!view.action?dishonourChqId=:ID', 1, '0001-01-20 00:00:00 BC', NULL, NULL, 'Y', 'N', 'org.egov.model.instrument.DishonorCheque', 'Dishonor Cheque', NULL);
---------------------------------END------------------------------

-----------------------------------START-------------------------
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'exclude_status_forbudget_actual','exclude voucher status for budget',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetaryCheck_budgettype_cashbased','budgetaryCheck budgettype',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_final_approval_status','Final Approval status for budget',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'pjv_saveasworkingcopy_enabled','pjv_saveasworkingcopy_enabled',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Bill_Number_Geneartion_Auto','bill number genration auto or manual ',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'cancelledstatus','Cancelled status for voucher',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'contingencyBillPurposeIds','Contingent Bill PurposeIds',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'VOUCHER_STATUS_TO_CHECK_BANK_BALANCE','VOUCHER_STATUS_TO_CHECK_BANK_BALANCE',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'salaryBillPurposeIds','Salary Bill PurposeIds',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'salaryBillDefaultPurposeId','Salary Bill Default PurposeIds',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'bank_balance_mandatory','bank_balance_mandatory',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PurchaseBillApprovalStatus','Purchase bill Status for approval',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'WorksBillApprovalStatus','Works bill Status for approval',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'ExpenseBillApprovalStatus','Contingency bill Status for approval',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'SalaryBillApprovalStatus','Salary bill Status for approval',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Balance Check Based on Fund Flow Report','Check Balance  Based on Fund Flow Report Or Not',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'add_less_codes_for_ie_report','add and less codes for ie report',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'planning_budget_multiplication_factor','planning budget multiplication factor',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'CONSIDER_RE_REAPPROPRIATION_AS_SEPARATE','Whether or not to consider re_reappropriation as seperate in budget reports',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'pensionBillPurposeIds','Pension Bill PurposeIds',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PensionBillApprovalStatus','Pension bill Status for approval',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_SMlevel_approver_designation','budget_SMlevel_approver_designation',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'USE BILLDATE IN CREATE VOUCHER FROM BILL','USE BILLDATE IN CREATE VOUCHER FROM BILL',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'WORKS VOUCHERS RESTRICTION DATE FROM JV SCREEN','WORKS VOUCHERS RESTRICTION DATE FROM JV SCREEN',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'GJV_FOR_RCPT_CHQ_DISHON','Generate Journal Voucher on dishonoring receipt cheque',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'loangrant.default.fundid','if fund id is present it is defaulted else selection made mandatory',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'BANKBALANCE_CHECK_DATE','Fund Flow BANKBALANCE_CHECK_DATE',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-272','Function Wise Budget Report',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'CONTRACTOR_ADVANCE_CODE','Contractor Advance Payable',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'contingencyBillDefaultPurposeId',' default Purpose ids for Contingency',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Communication Expenses','ContingentBill-Telephone-CheckList',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Electricity Charges','ContingentBill-Electricity-CheckList',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Others','ContingentBill-Others-CheckList',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PAYMENT_WF_STATUS_FOR_BANK_BALANCE_CHECK','PAYMENT_WF_STATUS_FOR_BANK_BALANCE_CHECK',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DEFAULT_SEARCH_MISATTRRIBUTES','default search mis attributes',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_toplevel_approver_designation','budget_toplevel_approver_designation',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_secondlevel_approver_designation','Functionary contains colon',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Reason For Cheque Surrendaring',' Reasons for cheque surrendering',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PREAPPROVEDVOUCHERSTATUS','voucher status before approval',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'APPROVEDVOUCHERSTATUS','next state of approval',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DEFAULTVOUCHERCREATIONSTATUS','DEFAULTVOUCHERCREATIONSTATUS',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_detailcode_length','detailcode length length',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetgroup_range_minor_or_detailed','budgetgroup_range_minor_or_detailed',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_minorcode_length','minorcode length',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_majorcode_length','majorcode length',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetaryCheck_groupby_values','budgetarycheck group by values',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_subminorcode_length','subminorcode length',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'purchaseBillPurposeIds','purchaseBillPurposeIds',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'worksBillPurposeIds','worksBillPurposeIds',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'parent_for_detailcode','parent length for detailed code',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Cheque_no_generation_auto','Cheque_nogeneration',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'cheque.assignment.infavourof','cheque.assignment.infavourof',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'boundaryforaccounts','This is the boundary at which books of accounts are maintained',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DEFAULTTXNMISATTRRIBUTES','default transaction mis attributes',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'JournalVoucher_ConfirmonCreate','journal voucher create isconfirmed value',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'bs_report_half_yearly','balance sheet report half yearly date (dd/mm)',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'REPORT_SEARCH_MISATTRRIBUTES','default search mis attributes',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetDetail_mandatory_fields','Budget Detail mandatroy fields',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetCheckRequired','budgetCheckRequired',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'RTGSNO_GENERATION_AUTO','RTGSNO_GENERATION_AUTO',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DATE_RESTRICTION_FOR_CJV_PAYMENT_MODE_AS_RTGS','Whether RTGS should be the only mode of payment for CJVs for the bill date',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Remove Entrys With Zero Amount','Value to deside Remove Entrys With Zero Amount in Reports',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'ifRestrictedToOneFunctionCenter','ifRestrictedToOneFunctionCenter',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'VOUCHERDATE_FROM_UI','GET VOUCHERDATE FROM UI',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'CJV_PAYMENT_MODE_AS_RTGS','Whether RTGS should be the only mode of payment for CJVs',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Remove Entries With Zero Amount in Report','Value to deside Remove Entries With Zero Amount in Reports',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_major_capital_exp_fie_report','coa_major_capital_exp_fie_report',(select id from eg_module where name='EGF'));
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'AuoRemittance_Account_Number_For_GJV','Bank Account number GJV remittance Payment',(select id from eg_module where name='EGF'));

--------------------------------END---------------------------------------------------------
------------------------START-------------------------
update eg_module set enabled=false where name='Assigned Revenue Reports';
update eg_module set enabled=false where name='TNEB';

update eg_action set enabled=false where name='Reverse Bills-Search';
update eg_action set enabled=false where name='Modify Payments-Search';
update eg_action set enabled=false where name='Modify Fund Flow Analysis Report';
update eg_action set enabled=false where name='Fund Flow Analysis Report';
update eg_action set enabled=false where name='Outstanding Payment';
update eg_action set enabled=false where name='Concurrence Report';
update eg_action set enabled=false where name='ManualEntryReport';
update eg_action set enabled=false where name='Reverse Journal Vouchers-Search';
update eg_action set enabled=false where name='Cash Withdrawal';
update eg_action set enabled=false where name='Reverse Contra Entries-Search';

update eg_action set enabled=false where name='AutoReconcile';
update eg_action set enabled=false where name='AutoReconcile-Upload';
update eg_action set enabled=false where name='Confirm Vouchers';
update eg_action set enabled=false where name='ScheduleRemittanceManual';
update eg_action set enabled=false where name='RTGSAssignmentforPayment';
update eg_action set enabled=false where name='Creditors Recoveries';
update eg_action set enabled=false where name='Setup Cheque in Hand/Cash in Hand';
update eg_action set enabled=false where name='Add Bank';
update eg_action set enabled=false where name='AutoRemittanceReport';
update eg_action set enabled=false where name='AutoRemittanceSchedulerReport';
update eg_action set enabled = false where displayname ='Add/Modify Branch-Modify Bank';
------------------------END-------------------
------------------------START-------------------------
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (4,'Cash In Hand',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (5,'Cheque In Hand',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (7,'ExcessIE',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (8,' Payable to Other Funds',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (10,'Contractor Deductions',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (16,'CWIP Account code',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (21,'Fixed Assets Written off',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (22,'Inter-Unit Transfer Account',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (26,'Creditors-Contractor Payable',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (27,'Creditors-Supplier Payable',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (28,'Contigency Bill Code',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (29,'Security Deposit',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (30,'Bank Charges',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (31,'Salary Payable',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (35,'Supplier Advance Account',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (37,'Material Clearing Account',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (38,'Scrap Suspense Account',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (60,'Overhead_account codes',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (61,'DEPOSIT:OTHER WORKS',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (62,'REPAIRS AND MAINTENANCE',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (95,'RETENTION_MONEY',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (96,'LandEstate_Rent_purpose',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (103,'Pension Payable Code',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (105,'CONTRACTOR_ADVANCE_ACCOUNTCODE',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (120,'BPA Deposit CWIP Account Code',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (34,'Pension Payable',current_date,1,current_date,1);
Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values (36,'Wages Payable',current_date,1,current_date,1);

Insert into egf_accountcode_purpose (ID,NAME,MODIFIEDDATE,MODIFIEDBY,CREATEDDATE,CREATEDBY) values 
(121,'Cash In Transit',current_date,1,current_date,1);
------------------------END-------------------
-----------------START-----------------------------------
INSERT INTO EGF_INSTRUMENTTYPE (ID,TYPE,ISACTIVE,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE) values (nextval('SEQ_EGF_INSTRUMENTTYPE'),'cash','1',1,1, current_timestamp, current_timestamp);
INSERT INTO EGF_INSTRUMENTTYPE (ID,TYPE,ISACTIVE,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE) values (nextval('SEQ_EGF_INSTRUMENTTYPE'),'cheque','1',1,1, current_timestamp, current_timestamp);
INSERT INTO EGF_INSTRUMENTTYPE (ID,TYPE,ISACTIVE,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE) values (nextval('SEQ_EGF_INSTRUMENTTYPE'),'dd','1',1,1, current_timestamp, current_timestamp);
INSERT INTO EGF_INSTRUMENTTYPE (ID,TYPE,ISACTIVE,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE) values (nextval('SEQ_EGF_INSTRUMENTTYPE'),'online','1',1,1, current_timestamp, current_timestamp);
-------------------------END-----------------------------
---------------------------START-------------------------------------------
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='PREAPPROVEDVOUCHERSTATUS'),to_date('23-09-09','DD-MM-RR'),'5');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='APPROVEDVOUCHERSTATUS'),to_date('23-09-09','DD-MM-RR'),'0');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='DEFAULTVOUCHERCREATIONSTATUS'),to_date('23-09-09','DD-MM-RR'),'0');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='exclude_status_forbudget_actual'),to_date('23-09-09','DD-MM-RR'),'4');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='budgetaryCheck_budgettype_cashbased'),to_date('23-09-09','DD-MM-RR'),'N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='budget_final_approval_status'),to_date('23-09-09','DD-MM-RR'),'END');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='coa_majorcode_length'),to_date('23-09-09','DD-MM-RR'),'3');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='coa_minorcode_length'),to_date('23-09-09','DD-MM-RR'),'5');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='budgetaryCheck_groupby_values'),to_date('23-09-09','DD-MM-RR'),'department,function,fund');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='budgetaryCheck_groupby_values'),to_date('24-03-10','DD-MM-RR'),'department,function,fund');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='coa_detailcode_length'),to_date('23-09-09','DD-MM-RR'),'9');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='budgetgroup_range_minor_or_detailed'),to_date('23-09-09','DD-MM-RR'),'detailed');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='pjv_saveasworkingcopy_enabled'),to_date('23-09-09','DD-MM-RR'),'N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='DEFAULTTXNMISATTRRIBUTES'),to_date('28-03-10','DD-MM-RR'),'department|M');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='DEFAULTTXNMISATTRRIBUTES'),to_date('28-03-10','DD-MM-RR'),'function|N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='DEFAULTTXNMISATTRRIBUTES'),to_date('28-03-10','DD-MM-RR'),'fundsource|N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='DEFAULTTXNMISATTRRIBUTES'),to_date('28-03-10','DD-MM-RR'),'fund|M');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='DEFAULTTXNMISATTRRIBUTES'),to_date('13-08-10','DD-MM-RR'),'scheme|N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='DEFAULTTXNMISATTRRIBUTES'),to_date('13-08-10','DD-MM-RR'),'subscheme|N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='JournalVoucher_ConfirmonCreate'),to_date('28-03-10','DD-MM-RR'),'0');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='bs_report_half_yearly'),to_date('22-11-09','DD-MM-RR'),'30/09');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='REPORT_SEARCH_MISATTRRIBUTES'),to_date('07-10-09','DD-MM-RR'),'department|N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='REPORT_SEARCH_MISATTRRIBUTES'),to_date('07-10-09','DD-MM-RR'),'fund|M');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='REPORT_SEARCH_MISATTRRIBUTES'),to_date('22-10-09','DD-MM-RR'),'function|N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='budgetDetail_mandatory_fields'),to_date('28-03-10','DD-MM-RR'),'executingDepartment,function,fund');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='budgetCheckRequired'),to_date('11-11-09','DD-MM-RR'),'Y');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='coa_subminorcode_length'),to_date('28-03-10','DD-MM-RR'),'7');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='purchaseBillPurposeIds'),to_date('28-03-10','DD-MM-RR'),'27');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='worksBillPurposeIds'),to_date('28-03-10','DD-MM-RR'),'26');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='parent_for_detailcode'),to_date('28-03-10','DD-MM-RR'),'3');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Cheque_no_generation_auto'),to_date('17-12-09','DD-MM-RR'),'N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='cheque.assignment.infavourof'),to_date('17-12-09','DD-MM-RR'),'Chairperson');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='boundaryforaccounts'),to_date('17-12-09','DD-MM-RR'),'City');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='boundaryforaccounts'),to_date('01-01-10','DD-MM-RR'),'City');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='cancelledstatus'),to_date('17-12-09','DD-MM-RR'),'4');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='bank_balance_mandatory'),to_date('28-03-10','DD-MM-RR'),'Y');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='CONTRACTOR_ADVANCE_CODE'),to_date('22-02-10','DD-MM-RR'),'4604002');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='PurchaseBillApprovalStatus'),to_date('01-04-09','DD-MM-RR'),'SBILL|Approved');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='WorksBillApprovalStatus'),to_date('01-04-09','DD-MM-RR'),'CONTRACTORBILL|APPROVED');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='ExpenseBillApprovalStatus'),to_date('01-04-09','DD-MM-RR'),'CBILL|APPROVED');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='ExpenseBillApprovalStatus'),to_date('01-04-09','DD-MM-RR'),'EXPENSEBILL|Approved');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='SalaryBillApprovalStatus'),to_date('01-04-09','DD-MM-RR'),'SALBILL|Approved');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='contingencyBillPurposeIds'),to_date('03-03-10','DD-MM-RR'),'28');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='contingencyBillPurposeIds'),to_date('01-04-10','DD-MM-RR'),'26');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='contingencyBillPurposeIds'),to_date('18-06-10','DD-MM-RR'),'31');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='contingencyBillPurposeIds'),to_date('18-06-10','DD-MM-RR'),'34');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='contingencyBillPurposeIds'),to_date('22-06-10','DD-MM-RR'),'36');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='contingencyBillPurposeIds'),to_date('28-02-11','DD-MM-RR'),'27');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='contingencyBillPurposeIds'),to_date('10-07-12','DD-MM-RR'),'103');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='contingencyBillDefaultPurposeId'),to_date('28-03-10','DD-MM-RR'),'0');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Communication Expenses'),to_date('28-03-10','DD-MM-RR'),'1. Whether the monthly rental charges claimed is correct.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Communication Expenses'),to_date('28-03-10','DD-MM-RR'),'10. Whether the original bill is enclosed.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Communication Expenses'),to_date('28-03-10','DD-MM-RR'),'2. Whether the call charges claimed is correct.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Communication Expenses'),to_date('28-03-10','DD-MM-RR'),'3. Whether the OB has been compared with CB of the previous bill.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Communication Expenses'),to_date('28-03-10','DD-MM-RR'),'4. Whether the call charges does not exceed the permitted calls.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Communication Expenses'),to_date('28-03-10','DD-MM-RR'),'5. Whether the sanction of the competent authority has been obtained if the permitted calls exceeds.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Communication Expenses'),to_date('28-03-10','DD-MM-RR'),'6. Whether the charges for the excess calls have been remitted in the Treasury and the challan produced in respect of residential phone.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Communication Expenses'),to_date('28-03-10','DD-MM-RR'),'7. Whether necessary entry has been made in the Standard Register.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Communication Expenses'),to_date('28-03-10','DD-MM-RR'),'8. Whether the budget provision is available.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Communication Expenses'),to_date('28-03-10','DD-MM-RR'),'9. Whether the bill has been approved by the competent authority.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Electricity Charges'),to_date('28-03-10','DD-MM-RR'),'1. Whether the claim is in order.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Electricity Charges'),to_date('28-03-10','DD-MM-RR'),'2. Whether the OB has been compared with CB of the previous bill. ');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Electricity Charges'),to_date('28-03-10','DD-MM-RR'),'3. Whether necessary entry has been made in the Standard Register.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Electricity Charges'),to_date('28-03-10','DD-MM-RR'),'4. Whether the budget provision is available.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Electricity Charges'),to_date('28-03-10','DD-MM-RR'),'5. Whether the bill has been approved by the competent authority.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Electricity Charges'),to_date('28-03-10','DD-MM-RR'),'6. Whether an extract of the electricity meter reader is enclosed.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Others'),to_date('28-03-10','DD-MM-RR'),'1. Whether the claim is in order.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Others'),to_date('28-03-10','DD-MM-RR'),'2. Whether the budget provision is available.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Others'),to_date('28-03-10','DD-MM-RR'),'3. Whether the bill has been approved by the competent authority. ');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Others'),to_date('28-03-10','DD-MM-RR'),'4. Whether original bill has been enclosed');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='PAYMENT_WF_STATUS_FOR_BANK_BALANCE_CHECK'),to_date('28-03-10','DD-MM-RR'),'Checked by FMU SECTION MANAGER');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='PAYMENT_WF_STATUS_FOR_BANK_BALANCE_CHECK'),to_date('28-03-10','DD-MM-RR'),'Prepared by FMU ASSISTANT');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Bill_Number_Geneartion_Auto'),to_date('28-03-10','DD-MM-RR'),'N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='DEFAULT_SEARCH_MISATTRRIBUTES'),to_date('07-10-09','DD-MM-RR'),'department|N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='DEFAULT_SEARCH_MISATTRRIBUTES'),to_date('07-10-09','DD-MM-RR'),'fund|M');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='VOUCHER_STATUS_TO_CHECK_BANK_BALANCE'),to_date('01-04-09','DD-MM-RR'),'Approved by %(UAC - ACCOUNTS OFFICER');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='VOUCHER_STATUS_TO_CHECK_BANK_BALANCE'),to_date('06-06-12','DD-MM-RR'),'ASSISTANT,FMU');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='salaryBillPurposeIds'),to_date('04-04-10','DD-MM-RR'),'31,34,36,103');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='add_less_codes_for_ie_report'),to_date('18-06-10','DD-MM-RR'),'280-Add,290-Less');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='planning_budget_multiplication_factor'),to_date('03-06-10','DD-MM-RR'),'2');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='budget_toplevel_approver_designation'),to_date('01-04-00','DD-MM-RR'),'Commissioner');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='budget_secondlevel_approver_designation'),to_date('01-04-00','DD-MM-RR'),'FMU:');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Reason For Cheque Surrendaring'),to_date('16-09-10','DD-MM-RR'),'Cheque to be scrapped.');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Reason For Cheque Surrendaring'),to_date('16-09-10','DD-MM-RR'),'Damaged cheque');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Reason For Cheque Surrendaring'),to_date('16-09-10','DD-MM-RR'),'Surrender: cheque leaf to be re-used.|Y');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Balance Check Based on Fund Flow Report'),to_date('17-11-10','DD-MM-RR'),'Y');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='CONSIDER_RE_REAPPROPRIATION_AS_SEPARATE'),to_date('25-04-11','DD-MM-RR'),'N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='GJV_FOR_RCPT_CHQ_DISHON'),to_date('27-07-11','DD-MM-RR'),'Y');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='loangrant.default.fundid'),to_date('01-04-11','DD-MM-RR'),'23');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='coa_major_capital_exp_fie_report'),to_date('30-03-12','DD-MM-RR'),'410,412');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='BANKBALANCE_CHECK_DATE'),to_date('17-04-12','DD-MM-RR'),'01-Apr-2012');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='pensionBillPurposeIds'),to_date('11-09-12','DD-MM-RR'),'103');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='PensionBillApprovalStatus'),to_date('01-04-09','DD-MM-RR'),'PENSIONBILL|Approved');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='budget_SMlevel_approver_designation'),to_date('01-04-00','DD-MM-RR'),'SECTION MANAGER');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='USE BILLDATE IN CREATE VOUCHER FROM BILL'),to_date('02-04-13','DD-MM-RR'),'N');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='WORKS VOUCHERS RESTRICTION DATE FROM JV SCREEN'),to_date('03-05-13','DD-MM-RR'),'Works,01/04/2013');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='ifRestrictedToOneFunctionCenter'),to_date('04-09-13','DD-MM-RR'),'No');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='CJV_PAYMENT_MODE_AS_RTGS'),to_date('01-04-09','DD-MM-RR'),'Y');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='DATE_RESTRICTION_FOR_CJV_PAYMENT_MODE_AS_RTGS'),to_date('01-04-09','DD-MM-RR'),'01/10/2013');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='RTGSNO_GENERATION_AUTO'),to_date('26-03-14','DD-MM-RR'),'Y');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='AuoRemittance_Account_Number_For_GJV'),to_date('15-04-14','DD-MM-RR'),'01-171102000000700');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='VOUCHERDATE_FROM_UI'),to_date('29-05-14','DD-MM-RR'),'Y');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Remove Entrys With Zero Amount'),to_date('20-08-14','DD-MM-RR'),'true');
Insert into eg_appconfig_values (ID,KEY_ID,EFFECTIVE_FROM,VALUE) values (nextval('seq_eg_appconfig_values'),(select id from eg_appconfig where KEY_NAME ='Remove Entries With Zero Amount in Report'),to_date('17-10-14','DD-MM-RR'),'Yes');
update eg_appconfig_values set value = 7 where KEY_ID in (select id from eg_appconfig where key_name = 'coa_detailcode_length');
update eg_appconfig_values set value = 5 where KEY_ID in (select id from eg_appconfig where key_name = 'coa_subminorcode_length');
update eg_appconfig_values set value = 2 where KEY_ID in (select id from eg_appconfig where key_name = 'parent_for_detailcode');

----------------------------------END-------------------------------------------------    
