#created on: 5 Oct, 2008
package works_routing

#list any import classes here.

import org.egov.payroll.model.SalaryCodes
import org.egov.payroll.services.payhead.PayheadManagerBean


rule "isRecurring"
	salience 10
	when
		$payheadName:String()
		$payheadManagerBean:PayheadManagerBean()
		$salarycodes:SalaryCodes() from $payheadManagerBean.getSalaryCodeByHead($payheadName)
		SalaryCodes(isRecurring=="N",head=="test") from $salarycodes
	then
		System.out.println("Rule is fired in isRecurring");
		System.out.println("salarycodeId-->"+$salarycodes.getId());		
end



/*rule "isRecurringTestY"
	salience 10
	when		
		$salarycodes:SalaryCodes()
		SalaryCodes(isRecurring=="Y") from $salarycodes
	then
		System.out.println("Rule is fired in isRecurring");
		System.out.println("salarycodeId-->"+$salarycodes.getId());	
		$salarycodes.setHead("testY");	
end

rule "isRecurringTestN"
	salience 10
	when		
		$salarycodes:SalaryCodes()
		SalaryCodes(isRecurring=="Y") from $salarycodes
	then
		System.out.println("Rule is fired in isRecurring");
		System.out.println("salarycodeId-->"+$salarycodes.getId());	
		$salarycodes.setHead("testN");	
end*/
 