#created on: 5 Oct, 2008
package works_routing

#list any import classes here.

import org.egov.payroll.model.SalaryCodes
import org.egov.payroll.services.payhead.PayheadManagerBean
import org.egov.payroll.model.EmpPayroll
import org.egov.payroll.model.Earnings
import org.egov.payroll.model.SalaryCodes
import org.egov.payroll.rules.PayheadRuleUtil
import org.egov.payroll.services.payslip.PayRollManagerBean
import java.util.HashSet
import java.math.*


rule "isRullBased"
	salience 10
	when
		$currPayslip : EmpPayroll($earningsSet : earningses)		  
		$currEarning : Earnings()		
		$ruleUtill : PayheadRuleUtil()
		SalaryCodes(head=="pctOfBasicRule") from $currEarning.getSalaryCodes()			
		#Getting Basic earnings from current payslip		
		$basicEarning : Earnings() from $ruleUtill.getEarningByNameFormPayslip($currPayslip,"Basic")		
		
	then
		BigDecimal basicPct = new BigDecimal(10);		
		System.out.println("Basic amount pctOfBasic------"+$basicEarning.getAmount());		
		BigDecimal basic = $basicEarning.getAmount();	
		BigDecimal basicCal = basic.multiply(basicPct).divide(new BigDecimal(100));			
		$currEarning.setAmount(basicCal);		
end
