INSERT INTO eg_module(
            id, name, enabled, contextroot, parentmodule, displayname, ordernumber)
    VALUES (nextval('SEQ_EG_MODULE'), 'Council Management', true, 'council', null, 'Council Management', (select max(ordernumber)+1 from eg_module where parentmodule is null));

INSERT INTO eg_module(
            id, name, enabled, contextroot, parentmodule, displayname, ordernumber)
    VALUES (nextval('SEQ_EG_MODULE'), 'Council Management Master', true, null, (select id from eg_module where name='Council Management'), 'Masters', 1);

    
Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'New-CouncilCaste','/councilcaste/new',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'New-CouncilCaste',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='New-CouncilCaste'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Create-CouncilCaste','/councilcaste/create',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Create-CouncilCaste',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Create-CouncilCaste'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Update-CouncilCaste','/councilcaste/update',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Update-CouncilCaste',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Update-CouncilCaste'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'View-CouncilCaste','/councilcaste/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'View-CouncilCaste',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='View-CouncilCaste'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Edit-CouncilCaste','/councilcaste/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Edit-CouncilCaste',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Edit-CouncilCaste'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Result-CouncilCaste','/councilcaste/result',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Result-CouncilCaste',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Result-CouncilCaste'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and View-CouncilCaste','/councilcaste/search/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),2,'Search and View-CouncilCaste',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and View-CouncilCaste'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and Edit-CouncilCaste','/councilcaste/search/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),3,'Search and Edit-CouncilCaste',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and Edit-CouncilCaste'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and View Result-CouncilCaste','/councilcaste/ajaxsearch/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Search and View Result-CouncilCaste',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and View Result-CouncilCaste'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and Edit Result-CouncilCaste','/councilcaste/ajaxsearch/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Search and Edit Result-CouncilCaste',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and Edit Result-CouncilCaste'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'New-CouncilDesignation','/councildesignation/new',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'New-CouncilDesignation',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='New-CouncilDesignation'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Create-CouncilDesignation','/councildesignation/create',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Create-CouncilDesignation',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Create-CouncilDesignation'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Update-CouncilDesignation','/councildesignation/update',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Update-CouncilDesignation',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Update-CouncilDesignation'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'View-CouncilDesignation','/councildesignation/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'View-CouncilDesignation',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='View-CouncilDesignation'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Edit-CouncilDesignation','/councildesignation/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Edit-CouncilDesignation',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Edit-CouncilDesignation'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Result-CouncilDesignation','/councildesignation/result',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Result-CouncilDesignation',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Result-CouncilDesignation'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and View-CouncilDesignation','/councildesignation/search/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),2,'Search and View-CouncilDesignation',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and View-CouncilDesignation'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and Edit-CouncilDesignation','/councildesignation/search/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),3,'Search and Edit-CouncilDesignation',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and Edit-CouncilDesignation'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and View Result-CouncilDesignation','/councildesignation/ajaxsearch/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Search and View Result-CouncilDesignation',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and View Result-CouncilDesignation'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and Edit Result-CouncilDesignation','/councildesignation/ajaxsearch/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Search and Edit Result-CouncilDesignation',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and Edit Result-CouncilDesignation'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'New-CouncilMember','/councilmember/new',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'New-CouncilMember',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='New-CouncilMember'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Create-CouncilMember','/councilmember/create',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Create-CouncilMember',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Create-CouncilMember'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Update-CouncilMember','/councilmember/update',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Update-CouncilMember',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Update-CouncilMember'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'View-CouncilMember','/councilmember/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'View-CouncilMember',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='View-CouncilMember'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Edit-CouncilMember','/councilmember/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Edit-CouncilMember',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Edit-CouncilMember'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Result-CouncilMember','/councilmember/result',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Result-CouncilMember',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Result-CouncilMember'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and View-CouncilMember','/councilmember/search/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),2,'Search and View-CouncilMember',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and View-CouncilMember'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and Edit-CouncilMember','/councilmember/search/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),3,'Search and Edit-CouncilMember',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and Edit-CouncilMember'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and View Result-CouncilMember','/councilmember/ajaxsearch/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Search and View Result-CouncilMember',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and View Result-CouncilMember'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and Edit Result-CouncilMember','/councilmember/ajaxsearch/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Search and Edit Result-CouncilMember',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and Edit Result-CouncilMember'));


Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'New-CouncilParty','/councilparty/new',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'New-CouncilParty',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='New-CouncilParty'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Create-CouncilParty','/councilparty/create',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Create-CouncilParty',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Create-CouncilParty'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Update-CouncilParty','/councilparty/update',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Update-CouncilParty',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Update-CouncilParty'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'View-CouncilParty','/councilparty/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'View-CouncilParty',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='View-CouncilParty'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Edit-CouncilParty','/councilparty/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Edit-CouncilParty',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Edit-CouncilParty'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Result-CouncilParty','/councilparty/result',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Result-CouncilParty',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Result-CouncilParty'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and View-CouncilParty','/councilparty/search/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),2,'Search and View-CouncilParty',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and View-CouncilParty'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and Edit-CouncilParty','/councilparty/search/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),3,'Search and Edit-CouncilParty',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and Edit-CouncilParty'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and View Result-CouncilParty','/councilparty/ajaxsearch/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Search and View Result-CouncilParty',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and View Result-CouncilParty'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and Edit Result-CouncilParty','/councilparty/ajaxsearch/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Search and Edit Result-CouncilParty',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and Edit Result-CouncilParty'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'New-CouncilQualification','/councilqualification/new',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'New-CouncilQualification',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='New-CouncilQualification'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Create-CouncilQualification','/councilqualification/create',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Create-CouncilQualification',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Create-CouncilQualification'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Update-CouncilQualification','/councilqualification/update',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Update-CouncilQualification',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Update-CouncilQualification'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'View-CouncilQualification','/councilqualification/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'View-CouncilQualification',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='View-CouncilQualification'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Edit-CouncilQualification','/councilqualification/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Edit-CouncilQualification',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Edit-CouncilQualification'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Result-CouncilQualification','/councilqualification/result',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Result-CouncilQualification',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Result-CouncilQualification'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and View-CouncilQualification','/councilqualification/search/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),2,'Search and View-CouncilQualification',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and View-CouncilQualification'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and Edit-CouncilQualification','/councilqualification/search/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),3,'Search and Edit-CouncilQualification',true,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and Edit-CouncilQualification'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and View Result-CouncilQualification','/councilqualification/ajaxsearch/view',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Search and View Result-CouncilQualification',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and View Result-CouncilQualification'));

Insert into eg_action(id,name,url,parentmodule,ordernumber,displayname,enabled,contextroot,application) values(nextval('SEQ_EG_ACTION'),'Search and Edit Result-CouncilQualification','/councilqualification/ajaxsearch/edit',(select id from eg_module where name='Council Management Master' and parentmodule=(select id from eg_module where name='Council Management' and parentmodule is null)),1,'Search and Edit Result-CouncilQualification',false,'council',(select id from eg_module where name='Council Management' and parentmodule is null));
Insert into eg_roleaction values((select id from eg_role where name='Super User'),(select id from eg_action where name='Search and Edit Result-CouncilQualification'));



