
INSERT INTO eg_role(id, name, description, createddate, createdby, lastmodifiedby, lastmodifieddate, version) 
VALUES (nextval('seq_eg_role'), 'Council Management Admin', 'Council Management Admin', now(), 1, 1, now(), 0);


INSERT into EG_ROLEACTION(ROLEID,ACTIONID) 
select (select id from eg_role where name='Council Management Admin'), id from eg_action where name in ('Create-CouncilCaste','Update-CouncilCaste','View-CouncilCaste','Edit-CouncilCaste','Result-CouncilCaste','Search and View Result-CouncilCaste','Search and Edit Result-CouncilCaste','Create-CouncilQualification','Update-CouncilQualification','View-CouncilQualification','Edit-CouncilQualification','Result-CouncilQualification','Search and View Result-CouncilQualification','Search and Edit Result-CouncilQualification','Create-CouncilParty','Search and View-CouncilCaste','Search and Edit-CouncilCaste','New-CouncilCaste','Search and View-CouncilQualification',
'Search and Edit-CouncilQualification','New-CouncilQualification','New-CouncilParty','Update-CouncilParty','View-CouncilParty','Edit-CouncilParty','Result-CouncilParty','Search and View Result-CouncilParty','Search and Edit Result-CouncilParty','Create-CouncilMember','Update-CouncilMember','View-CouncilMember','Edit-CouncilMember','Result-CouncilMember','Search and Edit Result-CouncilMember','Create-CouncilDesignation','Update-CouncilDesignation','View-CouncilDesignation','Edit-CouncilDesignation','Result-CouncilDesignation,''Search and View Result-CouncilDesignation',
'Search and Edit Result-CouncilDesignation','Download-Photo','Search and View Result-CouncilMember','Search and View-CouncilDesignation','Search and Edit-CouncilDesignation','New-CouncilDesignation','New-CouncilMember','Search and View-CouncilParty','Search and Edit-CouncilParty','Search and Edit-CouncilMember','Search and View-CouncilMember');


--delete from eg_role where name='Council Management Admin';

--delete from  EG_ROLEACTION where actionid in (select id from eg_action where name in ('Create-CouncilCaste','Update-CouncilCaste','View-CouncilCaste','Edit-CouncilCaste','Result-CouncilCaste','Search and View Result-CouncilCaste','Search and Edit Result-CouncilCaste','Create-CouncilQualification','Update-CouncilQualification','View-CouncilQualification','Edit-CouncilQualification','Result-CouncilQualification','Search and View Result-CouncilQualification','Search and Edit Result-CouncilQualification','Create-CouncilParty','Search and View-CouncilCaste','Search and Edit-CouncilCaste','New-CouncilCaste','Search and View-CouncilQualification','Search and Edit-CouncilQualification','New-CouncilQualification','New-CouncilParty','Update-CouncilParty','View-CouncilParty','Edit-CouncilParty','Result-CouncilParty','Search and View Result-CouncilParty','Search and Edit Result-CouncilParty','Create-CouncilMember','Update-CouncilMember','View-CouncilMember','Edit-CouncilMember','Result-CouncilMember','Search and Edit Result-CouncilMember','Create-CouncilDesignation','Update-CouncilDesignation','View-CouncilDesignation','Edit-CouncilDesignation','Result-CouncilDesignation,''Search and View Result-CouncilDesignation','Search and Edit Result-CouncilDesignation','Download-Photo','Search and View Result-CouncilMember','Search and View-CouncilDesignation','Search and Edit-CouncilDesignation','New-CouncilDesignation','New-CouncilMember','Search and View-CouncilParty','Search and Edit-CouncilParty','Search and Edit-CouncilMember','Search and View-CouncilMember')) and roleid in  (select id from eg_role where name='Council Management Admin');