---Insert RECORDED and SANCTIONED for resolution status
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'COUNCILRESOLUTION','RECORDED',now(),'RECORDED',4);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'COUNCILRESOLUTION','SANCTIONED',now(),'SANCTIONED',5);
