CREATE SEQUENCE SEQ_EIS_POST_CREATION;

CREATE TABLE EGEIS_POST_CREATION
(
	ID			integer NOT NULL,
	POST_NAME		character varying(512) NOT NULL,
	DESIG_ID		integer NOT NULL,
	DEPT_ID			integer NOT NULL,
	STATUS         	 	integer NOT NULL,
	STATE_ID		integer,
	QUALIFY_DETAILS		character varying(1024),
	POSITION_ID		integer ,
	REMARKS			character varying(1024),
	CREATEDBY		integer NOT NULL,
	CREATEDDATE     	DATE       NOT NULL,
	LASTMODIFIEDDATE	DATE       NOT NULL,
	LASTMODIFIEDBY		integer NOT NULL
);

ALTER TABLE EGEIS_POST_CREATION ADD CONSTRAINT PK_EIS_POST_ID PRIMARY KEY (ID);
  
ALTER TABLE EGEIS_POST_CREATION ADD CONSTRAINT FK_EIS_POST_DESIG_ID FOREIGN KEY (DESIG_ID) 
    REFERENCES EG_DESIGNATION (DESIGNATIONID); 
 
ALTER TABLE EGEIS_POST_CREATION ADD CONSTRAINT FK_EIS_POST_DEPT_ID FOREIGN KEY (DEPT_ID) 
    REFERENCES EG_DEPARTMENT (ID_DEPT);    
    	
ALTER TABLE EGEIS_POST_CREATION ADD CONSTRAINT FK_EIS_POST_STATUS FOREIGN KEY (STATUS) 
    REFERENCES EGW_STATUS (ID) ;
    
ALTER TABLE EGEIS_POST_CREATION ADD CONSTRAINT FK_EIS_POST_STATE_ID FOREIGN KEY (STATE_ID) 
    REFERENCES EG_WF_STATES (ID);    
    
ALTER TABLE EGEIS_POST_CREATION ADD CONSTRAINT FK_EIS_POST_LASTMODIFIEDBY FOREIGN KEY (LASTMODIFIEDBY)
    REFERENCES EG_USER (ID_USER);
  
ALTER TABLE EGEIS_POST_CREATION ADD CONSTRAINT FK_EIS_POST_CREATEDBY FOREIGN KEY (CREATEDBY)
    REFERENCES EG_USER (ID_USER);
      
ALTER TABLE EGEIS_POST_CREATION ADD CONSTRAINT FK_EIS_POST_POSITION_ID FOREIGN KEY (POSITION_ID)
    REFERENCES EG_POSITION (ID);

--rollback DROP TABLE EGEIS_POST_CREATION;
--rollback DROP SEQUENCE SEQ_EIS_POST_CREATION;
