ALTER TABLE EG_DEPARTMENT RENAME COLUMN ID_DEPT TO ID;

ALTER TABLE EG_DEPARTMENT RENAME COLUMN DEPT_NAME TO NAME;

ALTER TABLE EG_DEPARTMENT RENAME COLUMN DEPT_CODE TO CODE;

ALTER TABLE EG_DEPARTMENT RENAME COLUMN UPDATETIME TO CREATEDDATE;

ALTER TABLE EG_DEPARTMENT ADD CREATEDBY BIGINT;

ALTER TABLE EG_DEPARTMENT ADD LASTMODIFIEDBY BIGINT;

ALTER TABLE EG_DEPARTMENT ADD LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE EG_DEPARTMENT ADD VERSION BIGINT;

DROP SEQUENCE SEQ_EG_DEPT;

DELETE FROM EG_ROLEACTION_MAP WHERE ACTIONID = (SELECT id FROM EG_ACTION WHERE NAME = 'Create Department');

DELETE FROM EG_ACTION WHERE NAME = 'Create Department';

INSERT INTO EG_ACTION(ID, NAME, ENTITYID, TASKID, UPDATEDTIME, URL, QUERYPARAMS, URLORDERID, MODULE_ID, ORDER_NUMBER, DISPLAY_NAME, IS_ENABLED, ACTION_HELP_URL, CONTEXT_ROOT)
Values (nextval('SEQ_EG_ACTION'), 'CreateDepartmentForm', NULL, NULL, now(), '/controller/create-department', NULL, NULL, (SELECT ID_MODULE FROM EG_MODULE WHERE MODULE_DESC = 'Department'),
0, 'Create Department', 1, NULL, 'egi');

INSERT INTO EG_ROLEACTION_MAP (ROLEID, ACTIONID) values ((select id from eg_role where UPPER(name) LIKE 'SUPERUSER') ,(select id FROM eg_action  WHERE name = 'CreateDepartmentForm'));
