CREATE OR REPLACE VIEW EG_EIS_EMPLOYEEINFO("ASS_ID","ID", "CODE", "NAME", "DESIGNATIONID",
 "FROM_DATE", "TO_DATE", "DATE_OF_FA", "ISACTIVE", "DEPT_ID", "FUNCTIONARY_ID", "POS_ID", "USER_ID", "STATUS", "EMPLOYEE_TYPE",
 "IS_PRIMARY","ASS_ID_UNIQUE","FUNCTION_ID","USER_ACTIVE","USER_NAME") AS 
  SELECT EEA.ID,EE.ID,EE.CODE,EE.EMP_FIRSTNAME||' '||EE.EMP_MIDDLENAME||' '||EE.EMP_LASTNAME,     
 EEA.DESIGNATIONID,EEA.FROM_DATE,EEA.TO_DATE,EE.DATE_OF_FIRST_APPOINTMENT,EE.ISACTIVE,      
 EEA.MAIN_DEPT,EEA.ID_FUNCTIONARY,EEA.POSITION_ID,ee.ID_USER,ee.STATUS ,ee.EMPLOYMENT_STATUS ,EEA.IS_PRIMARY,EEA.ID,EEA.ID_FUNCTION,
 EU.ISACTIVE,EU.USERNAME 
FROM EG_EMP_ASSIGNMENT EEA, EG_EMPLOYEE EE,EG_USER EU  WHERE EE.ID = EEA.ID_EMPLOYEE AND EU.ID = EE.ID_USER;

--rollback DROP VIEW EG_EIS_EMPLOYEEINFO;
