/*
 * eGov suite of products aim to improve the internal efficiency,transparency,
 *    accountability and the service delivery of the government  organizations.
 *
 *     Copyright (C) <2015>  eGovernments Foundation
 *
 *     The updated version of eGov suite of products as by eGovernments Foundation
 *     is available at http://www.egovernments.org
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program. If not, see http://www.gnu.org/licenses/ or
 *     http://www.gnu.org/licenses/gpl.html .
 *
 *     In addition to the terms of the GPL license to be adhered to in using this
 *     program, the following additional terms are to be complied with:
 *
 *         1) All versions of this program, verbatim or modified must carry this
 *            Legal Notice.
 *
 *         2) Any misrepresentation of the origin of the material is prohibited. It
 *            is required that all modified versions of this material be marked in
 *            reasonable ways as different from the original version.
 *
 *         3) This license does not grant any rights to any user of the program
 *            with regards to rights under trademark law for use of the trade names
 *            or trademarks of eGovernments Foundation.
 *
 *   In case of any queries, you can reach eGovernments Foundation at contact@egovernments.org.
 */
var d =document.getElementById('TreeDiv');
alert (d);
var t = new NamTree(d);
alert (t);
t.createNode( "main", "1" ,"Revenue"  ,"1000" );
t.createNode( "sub", "1000" ,"Chart of Accounts" );
t.createNode( "accounthead", "2", "Expense"  ,"1000");
t.createNode( "account", "3", "Asset", "1000");
t.createNode( "", "4"  ,"Liability", "1000");
t.createNode( "", "5"  ,"Tax Revenue", "1");
t.createNode( "", "6"  ,"Assigned Revenues and Compensations"  ,"1");
t.createNode( "", "7"  ,"Rental Income from Muncipal Properies"  ,"1");
t.createNode( "", "8"  ,"Fees and User Charges"  ,"1");
t.createNode( "", "9"  ,"Sales and Hire Charges"  ,"1");
t.createNode( "", "10"  ,"Revenue Grants, Contributions and Subsidies"  ,"1");
t.createNode( "", "11"  ,"Income from Investments - General Fund"  ,"1");
t.createNode( "", "12"  ,"Income from Investments - Othern Funds"  ,"1");
t.createNode( "", "13"  ,"Interest Earned"  ,"1");
t.createNode( "", "14"  ,"Other Income"  ,"1");
t.createNode( "", "15"  ,"Property Tax"  ,"5");
t.createNode( "", "16"  ,"Octroi and Toll"  ,"5");
t.createNode( "", "17"  ,"Cess"  ,"5");
t.createNode( "", "18"  ,"Professional Tax"  ,"5");
t.createNode( "", "19"  ,"Water Tax"  ,"5");
t.createNode( "", "20"  ,"Conservancy Tax"  ,"5");
t.createNode( "", "21"  ,"Lighting Tax"  ,"5");
t.createNode( "", "22"  ,"Education Tax"  ,"5");
t.createNode( "", "23"  ,"Vehicle Tax"  ,"5");
t.createNode( "", "24"  ,"Tax on Carriage and Carts"  ,"5");
t.createNode( "", "25"  ,"Tax on Animals"  ,"5");
t.createNode( "", "26"  ,"Advertisement Tax"  ,"5");
t.createNode( "", "27"  ,"Electricity Tax"  ,"5");
t.createNode( "", "28"  ,"Building Tax"  ,"5");
t.createNode( "", "29"  ,"Drainage Tax"  ,"5");
t.createNode( "", "30"  ,"Speciall Sanitary; Tax"  ,"5");
t.createNode( "", "31"  ,"Others Taxes"  ,"5");
t.createNode( "", "32"  ,"Property Tax from Residential Properties"  ,"15");
t.createNode( "", "33"  ,"Property Tax from Commercial Properties"  ,"15");
t.createNode( "", "34"  ,"Service Charges in lieu of Property Tax."  ,"15");
t.createNode( "", "35"  ,"Property Tax from others (Specify)"  ,"15");
t.createNode( "", "36"  ,"Octoroi"  ,"16");
t.createNode( "", "37"  ,"Toll Tax"  ,"16");
t.createNode( "", "38"  ,"Education Cess"  ,"17");
t.createNode( "", "39"  ,"Beggar Cess"  ,"17");
t.createNode( "", "40"  ,"Cess in lieu of Octroi"  ,"17");
t.createNode( "", "41"  ,"Any other Cess"  ,"17");
t.createNode( "", "42"  ,"Land Hoarding"  ,"26");
t.createNode( "", "43"  ,"Bus Shelter"  ,"26");
t.createNode( "", "44"  ,"Neon Signs and Shops"  ,"26");
t.createNode( "", "45"  ,"On Pvt. Land Hoarding"  ,"26");
t.createNode( "", "46"  ,"On Toilets"  ,"26");
t.createNode( "", "47"  ,"On Traffic Signals, Police Booths, Umbrellas etc."  ,"26");
t.createNode( "", "48"  ,"On Footpath, Railing Poles etc."  ,"26");
t.createNode( "", "49"  ,"On Tree Guards"  ,"26");
t.createNode( "", "50"  ,"Other Advertisement Taxes"  ,"26");
t.createNode( "", "51"  ,"Duty on transfer of Properties"  ,"6");
t.createNode( "", "52"  ,"Entertainment Tax"  ,"6");
t.createNode( "", "53"  ,"Compensation in lieu of Octroi"  ,"6");
t.createNode( "", "54"  ,"Other assigned revenues"  ,"6");
t.createNode( "", "55"  ,"Rent from Markets/Shopping Complexes"  ,"7");
t.createNode( "", "56"  ,"Rent from Office Buildings"  ,"7");
t.createNode( "", "57"  ,"Rent from Guest Houses"  ,"7");
t.createNode( "", "58"  ,"Rent from Lease of Lands"  ,"7");
t.createNode( "", "59"  ,"Other Rents"  ,"7");
t.createNode( "", "60"  ,"General Administration"  ,"8");
t.createNode( "", "61"  ,"General Administration"  ,"8");
t.createNode( "", "62"  ,"Public Works - Lands and Buildings"  ,"8");
t.createNode( "", "63"  ,"Water Supply"  ,"8");
t.createNode( "", "64"  ,"Public Health and Medical Services"  ,"8");
t.createNode( "", "65"  ,"Sanitation Conservancy and Sewerage"  ,"8");
t.createNode( "", "66"  ,"Solid Waste Management"  ,"8");
t.createNode( "", "67"  ,"Urban Forestry, Ecology and Environment"  ,"8");
t.createNode( "", "68"  ,"Urban Amenities and Facilities - Parks, Gardens and Playgrounds"  ,"8");
t.createNode( "", "69"  ,"Arts and Culture"  ,"8");
t.createNode( "", "70"  ,"Education"  ,"8");
t.createNode( "", "71"  ,"Burial and Cremations"  ,"8");
t.createNode( "", "72"  ,"Veterinary Services and Amimal Health"  ,"8");
t.createNode( "", "73"  ,"Vital Statistics - Birth and Death Registration"  ,"8");
t.createNode( "", "74"  ,"Public Amenities - Street Lighting, Parking Lots, Bus Stops and Public Convenience"  ,"8");
t.createNode( "", "75"  ,"Slaughter Houses and Tranneries"  ,"8");
t.createNode( "", "76"  ,"Electricty Supply"  ,"8");
t.createNode( "", "77"  ,"Housing"  ,"8");
t.createNode( "", "79"  ,"Conversion charges of Lease Hold Property to Free hold"  ,"61");
t.createNode( "", "80"  ,"Mutation Fee"  ,"61");
t.createNode( "", "81"  ,"DandO Trade License Fee"  ,"61");
t.createNode( "", "82"  ,"License Fee"  ,"61");
t.createNode( "", "83"  ,"Hawking License Fee"  ,"61");
t.createNode( "", "84"  ,"Dhobi Ghat License Fee"  ,"61");
t.createNode( "", "85"  ,"Shop License Fee"  ,"61");
t.createNode( "", "86"  ,"Copying Fee"  ,"61");
t.createNode( "", "87"  ,"Registration Fee of Professionals"  ,"61");
t.createNode( "", "88"  ,"License Fee on The Bazzar"  ,"61");
t.createNode( "", "89"  ,"Registration Fee of Carts etc."  ,"61");
t.createNode( "", "90"  ,"Transit Fee"  ,"61");
t.createNode( "", "91"  ,"Escort Fee"  ,"61");
t.createNode( "", "92"  ,"Layout/Sub-division Fee"  ,"61");
t.createNode( "", "93"  ,"Building Plan Fee"  ,"61");
t.createNode( "", "94"  ,"Plan Preparation Fee"  ,"61");
t.createNode( "", "95"  ,"Development Charges"  ,"61");
t.createNode( "", "96"  ,"Betterment Charges"  ,"61");
t.createNode( "", "97"  ,"Demolition Charges"  ,"61");
t.createNode( "", "98"  ,"Encoarchment Fees/Charges"  ,"61");
t.createNode( "", "99"  ,"Compounding Fee"  ,"61");
t.createNode( "", "100"  ,"Composition Fee"  ,"61");
t.createNode( "", "101"  ,"Building Construction Regularization Fee"  ,"61");
t.createNode( "", "102"  ,"Revalidation Fee"  ,"61");
t.createNode( "", "103"  ,"Service Charges "  ,"61");
t.createNode( "", "104"  ,"License Fees (Staff Quarter)"  ,"61");
t.createNode( "", "105"  ,"Road Cutting Charges"  ,"61");
t.createNode( "", "106"  ,"Stacking Charges"  ,"61");
t.createNode( "", "107"  ,"Percent Charges on Deposit Works"  ,"61");
t.createNode( "", "108"  ,"Registration Charges of PW Contractors"  ,"61");
t.createNode( "", "109"  ,"Connection Charges for Water Supply"  ,"61");
t.createNode( "", "110"  ,"Meter Rent for ater Supply"  ,"61");
t.createNode( "", "111"  ,"Plumbing License Fee"  ,"61");
t.createNode( "", "112"  ,"Registration Frees from Pati"  ,"61");
t.createNode( "", "113"  ,"Cost of Medicines"  ,"61");
t.createNode( "", "114"  ,"Examination Charges(Tests, X-ray,Ultra-Sound etc.)"  ,"61");
t.createNode( "", "115"  ,"Ambulance Charges"  ,"61");
t.createNode( "", "116"  ,"Funeral Van Services"  ,"61");
t.createNode( "", "117"  ,"Sewerage Connection Fee"  ,"61");
t.createNode( "", "118"  ,"Bulk Garbage Collectin Charges"  ,"61");
t.createNode( "", "119"  ,"Littering and debris Collection Charges"  ,"61");
t.createNode( "", "120"  ,"Septic Tank Clearance Charges"  ,"61");
t.createNode( "", "121"  ,"Sewerage blockage and sewer inspection fee"  ,"61");
t.createNode( "", "122"  ,"Park Entrance Fees"  ,"61");
t.createNode( "", "123"  ,"Fees for film shooting and other uses, etc."  ,"61");
t.createNode( "", "124"  ,"Play Ground Membership Fees"  ,"61");
t.createNode( "", "125"  ,"Lease of Jetties/Boats"  ,"61");
t.createNode( "", "126"  ,"Swimming Pools Using charges"  ,"61");
t.createNode( "", "127"  ,"Registration Charges - Education"  ,"61");
t.createNode( "", "128"  ,"Admission Fee - Education"  ,"61");
t.createNode( "", "129"  ,"Tution Fee"  ,"61");
t.createNode( "", "130"  ,"Sports Fee"  ,"61");
t.createNode( "", "131"  ,"Building/Development Fund"  ,"61");
t.createNode( "", "132"  ,"Crematiorium Charges"  ,"61");
t.createNode( "", "133"  ,"Burial Ground Charges"  ,"61");
t.createNode( "", "134"  ,"Cattle Pond Fees"  ,"61");
t.createNode( "", "135"  ,"Birth and Death Fee"  ,"61");
t.createNode( "", "136"  ,"Parking Fees"  ,"61");
t.createNode( "", "137"  ,"Fees for Pay and Use Toilets"  ,"61");
t.createNode( "", "138"  ,"Slaughtering Fees"  ,"61");
t.createNode( "", "139"  ,"License Fees fro Butchers and Traders of Meat"  ,"61");
t.createNode( "", "140"  ,"Meat and Poultry Trade Licensing Fees"  ,"61");
t.createNode( "", "141"  ,"Connection Charges - Electricity"  ,"61");
t.createNode( "", "142"  ,"Meter Rent - Electricity"  ,"61");
t.createNode( "", "143"  ,"Sale of Electricity"  ,"61");
t.createNode( "", "144"  ,"Other Fees and Charges"  ,"61");
t.createNode( "", "145"  ,"General Administration"  ,"9");
t.createNode( "", "146"  ,"Urban Planning - Town Planning"  ,"9");
t.createNode( "", "147"  ,"Public Works - Lands and Buildings"  ,"9");
t.createNode( "", "148"  ,"Water Supply"  ,"9");
t.createNode( "", "149"  ,"Public Health and Medical Services"  ,"9");
t.createNode( "", "150"  ,"Sanitation Conservancy and Sewerage"  ,"9");
t.createNode( "", "151"  ,"Solid Waste Management"  ,"9");
t.createNode( "", "152"  ,"Urban Forestry, Ecology and Environment"  ,"9");
t.createNode( "", "153"  ,"Urban Amenities and Facilities - Parks, Gardens and Playgrounds"  ,"9");
t.createNode( "", "154"  ,"Education"  ,"9");
t.createNode( "", "155"  ,"Housing"  ,"9");
t.createNode( "", "156"  ,"Sale of Products"  ,"145");
t.createNode( "", "157"  ,"Sale of Scrap"  ,"145");
t.createNode( "", "158"  ,"Sale of Forms and Documents etc."  ,"145");
t.createNode( "", "159"  ,"Sale of Tender Forms"  ,"145");
t.createNode( "", "160"  ,"Hire Charges of Road Rollers"  ,"145");
t.createNode( "", "161"  ,"Hire Charges of Other Tools and Equipment"  ,"145");
t.createNode( "", "162"  ,"Sale of Water"  ,"145");
t.createNode( "", "163"  ,"Sale of Garbage/manure"  ,"145");
t.createNode( "", "164"  ,"Sale of Trees"  ,"145");
t.createNode( "", "165"  ,"Sale of Fruits"  ,"145");
t.createNode( "", "166"  ,"Sale of Grass"  ,"145");
t.createNode( "", "167"  ,"Sale of Nursery Plants"  ,"145");
t.createNode( "", "168"  ,"Sale of Flowers"  ,"145");
t.createNode( "", "169"  ,"Central Government"  ,"10");
t.createNode( "", "170"  ,"State Government"  ,"10");
t.createNode( "", "171"  ,"Other Governent Agencies"  ,"10");
t.createNode( "", "172"  ,"Financial Institutions"  ,"10");
t.createNode( "", "173"  ,"Welfare Bodies"  ,"10");
t.createNode( "", "174"  ,"International Organisations"  ,"10");
t.createNode( "", "175"  ,"Others"  ,"10");
t.createNode( "", "176"  ,"Interest from General Fund Investment"  ,"11");
t.createNode( "", "177"  ,"Interest from GPF Investments"  ,"12");
t.createNode( "", "178"  ,"Interest from Pension Fund Investments"  ,"12");
t.createNode( "", "179"  ,"Interest from any other Investement"  ,"12");
t.createNode( "", "180"  ,"Interest from Bank Accounts"  ,"13");
t.createNode( "", "181"  ,"Interest from HBA"  ,"13");
t.createNode( "", "182"  ,"Interest from Conveyance Advances"  ,"13");
t.createNode( "", "183"  ,"Interest from Computer Advances"  ,"13");
t.createNode( "", "184"  ,"Interest from Other Interest Bearing Advances"  ,"13");
t.createNode( "", "185"  ,"Interest on Loans given to others"  ,"13");
t.createNode( "", "186"  ,"Interest on debtors and other receivables"  ,"13");
t.createNode( "", "187"  ,"Income from TV Operators"  ,"14");
t.createNode( "", "188"  ,"Lapsed deposits"  ,"14");
t.createNode( "", "189"  ,"Realisation under Municipal Act"  ,"14");
t.createNode( "", "190"  ,"Realisation under Other Acts"  ,"14");
t.createNode( "", "191"  ,"Fines"  ,"14");
t.createNode( "", "192"  ,"Penalities"  ,"14");
t.createNode( "", "193"  ,"Miscellaneous Income"  ,"14");
t.createNode( "", "194"  ,"Establishment Expenses"  ,"2");
t.createNode( "", "195"  ,"Administrative Expenses"  ,"2");
t.createNode( "", "196"  ,"Repairs and Maintenance"  ,"2");
t.createNode( "", "197"  ,"Interest and Finance Charges"  ,"2");
t.createNode( "", "198"  ,"Programme Expenses"  ,"2");
t.createNode( "", "199"  ,"Revenue Grants, Contributions and Subsidies"  ,"2");
t.createNode( "", "200"  ,"Provisions and Write off"  ,"2");
t.createNode( "", "201"  ,"Miscellaneous Expenses"  ,"2");
t.createNode( "", "202"  ,"Depreciation"  ,"2");
t.createNode( "", "203"  ,"Transfer to Reserve Funds"  ,"2");
t.createNode( "", "204"  ,"Municipal Council"  ,"194");
t.createNode( "", "205"  ,"General Administration"  ,"194");
t.createNode( "", "206"  ,"Finance and Audit Department"  ,"194");
t.createNode( "", "207"  ,"Law Department"  ,"194");
t.createNode( "", "208"  ,"Public Relations Department"  ,"194");
t.createNode( "", "209"  ,"Vigliance Department"  ,"194");
t.createNode( "", "210"  ,"Election Department"  ,"194");
t.createNode( "", "211"  ,"Collection of Taxes/Revenue Department"  ,"194");
t.createNode( "", "212"  ,"Information Technology"  ,"194");
t.createNode( "", "213"  ,"Urban Planning - Town Planning"  ,"194");
t.createNode( "", "214"  ,"Public Works - Lands and Buildings"  ,"194");
t.createNode( "", "215"  ,"Housing"  ,"194");
t.createNode( "", "216"  ,"Water Supply"  ,"194");
t.createNode( "", "217"  ,"Public Health and Medical Services"  ,"194");
t.createNode( "", "218"  ,"Sanitation Conservancy and Sewerage"  ,"194");
t.createNode( "", "219"  ,"Solid Waste Managemnet"  ,"194");
t.createNode( "", "220"  ,"Urban Forestry, Ecology and Environment"  ,"194");
t.createNode( "", "221"  ,"Urban Amenities and Facilities - Parks, Gardens and Playgrounds"  ,"194");
t.createNode( "", "222"  ,"Arts and Culture"  ,"194");
t.createNode( "", "223"  ,"Education"  ,"194");
t.createNode( "", "224"  ,"Burial and Cremations"  ,"194");
t.createNode( "", "225"  ,"Vital Statistics - Birth and Death Registration"  ,"194");
t.createNode( "", "226"  ,"Public Amenities - Street Lighting, Parking Lots, Bus Stops and Public Convenience"  ,"194");
t.createNode( "", "227"  ,"Staughter Houses and Tanneries"  ,"194");
t.createNode( "", "228"  ,"Electricity Supply"  ,"194");
t.createNode( "", "229"  ,"Fire Fighting Services"  ,"194");
t.createNode( "", "230"  ,"Family Welfare"  ,"194");
t.createNode( "", "231"  ,"Veterinary Services and Animal Health"  ,"194");
t.createNode( "", "232"  ,"Social Services"  ,"194");
t.createNode( "", "233"  ,"Welfare of weaker sections of society"  ,"194");
t.createNode( "", "234"  ,"Salaries and Allowances - Officers"  ,"204");
t.createNode( "", "235"  ,"Salaries and Allowances - Staff"  ,"204");
t.createNode( "", "236"  ,"Wages"  ,"204");
t.createNode( "", "237"  ,"Bonus/Ex-gratia"  ,"204");
t.createNode( "", "238"  ,"Honorarium/Fees to Chairman/Mayor/Councillors"  ,"204");
t.createNode( "", "239"  ,"Honoraium/Fees to Officers and Staff"  ,"204");
t.createNode( "", "240"  ,"Overtime Allowance"  ,"204");
t.createNode( "", "241"  ,"Leave Travel Concession"  ,"204");
t.createNode( "", "242"  ,"Medical Reimbursement"  ,"204");
t.createNode( "", "243"  ,"Tution Fees"  ,"204");
t.createNode( "", "244"  ,"Children Education Allowance"  ,"204");
t.createNode( "", "245"  ,"Uniform to Staff"  ,"204");
t.createNode( "", "246"  ,"Compensation to Staff"  ,"204");
t.createNode( "", "247"  ,"Pension/Family Pension - (Including commuted Value Pension)"  ,"204");
t.createNode( "", "248"  ,"Leave Encashment"  ,"204");
t.createNode( "", "249"  ,"Death cum Retirement Gratutity"  ,"204");
t.createNode( "", "250"  ,"Leave Salary Contribution for Deputationist"  ,"204");
t.createNode( "", "251"  ,"Pension Contribution for Deparmtne"  ,"204");
t.createNode( "", "252"  ,"Contribution to Provident Fund"  ,"204");
t.createNode( "", "253"  ,"Contribution to Other Fund (Specify)"  ,"204");
t.createNode( "", "254"  ,"Municipal Council"  ,"195");
t.createNode( "", "255"  ,"General Administration"  ,"195");
t.createNode( "", "256"  ,"Finance and Audit Department"  ,"195");
t.createNode( "", "257"  ,"Law Department"  ,"195");
t.createNode( "", "258"  ,"Public Relations Department"  ,"195");
t.createNode( "", "259"  ,"Vigilance Department"  ,"195");
t.createNode( "", "260"  ,"Election Department"  ,"195");
t.createNode( "", "261"  ,"Collection of Taxes/Revenue Department"  ,"195");
t.createNode( "", "262"  ,"Information Technology"  ,"195");
t.createNode( "", "263"  ,"Urban Planning - Town Planning"  ,"195");
t.createNode( "", "264"  ,"Public Works - Lands and Buildings"  ,"195");
t.createNode( "", "265"  ,"Housing"  ,"195");
t.createNode( "", "266"  ,"Water Supply"  ,"195");
t.createNode( "", "267"  ,"Public Health and Medical Services"  ,"195");
t.createNode( "", "268"  ,"Sanitation Conservancy and  Sewerage"  ,"195");
t.createNode( "", "269"  ,"Solid Waste Management"  ,"195");
t.createNode( "", "270"  ,"Urban Forestry, Ecology and Environment"  ,"195");
t.createNode( "", "271"  ,"Urban Amenities and Facilities - Parks, Gardens and Playgrounds"  ,"195");
t.createNode( "", "272"  ,"Arts and Culture"  ,"195");
t.createNode( "", "273"  ,"Education"  ,"195");
t.createNode( "", "274"  ,"Burial and Cremations"  ,"195");
t.createNode( "", "275"  ,"Vital Statistics - Birth and Death Registration"  ,"195");
t.createNode( "", "276"  ,"Public Amenities - Street Lighting, Parking Lots, Bus Stops and Public Convenience"  ,"195");
t.createNode( "", "277"  ,"Slaughter Houses and Tanneries"  ,"195");
t.createNode( "", "278"  ,"Electricity Supply"  ,"195");
t.createNode( "", "279"  ,"Fire Fighting Services"  ,"195");
t.createNode( "", "280"  ,"Family Welfare"  ,"195");
t.createNode( "", "281"  ,"Veterinary Services and Animal Health"  ,"195");
t.createNode( "", "282"  ,"Social Services"  ,"195");
t.createNode( "", "283"  ,"Welfare of weaker sections of Society"  ,"195");
t.createNode( "", "284"  ,"Rents, Rates and Taxes"  ,"254");
t.createNode( "", "285"  ,"Telephone and Communication Expenses"  ,"254");
t.createNode( "", "286"  ,"Printing"  ,"254");
t.createNode( "", "287"  ,"Stationery"  ,"254");
t.createNode( "", "288"  ,"Travelling and Conveyance Expenses"  ,"254");
t.createNode( "", "289"  ,"Insurance Charges"  ,"254");
t.createNode( "", "290"  ,"Audit Fee"  ,"254");
t.createNode( "", "291"  ,"Professional and Other Fees/Charges"  ,"254");
t.createNode( "", "292"  ,"Training  Expenses"  ,"254");
t.createNode( "", "293"  ,"Advertisement and Publicity"  ,"254");
t.createNode( "", "294"  ,"Cartage and Carriage Charges"  ,"254");
t.createNode( "", "295"  ,"Electricity and Power"  ,"254");
t.createNode( "", "296"  ,"Fuel"  ,"254");
t.createNode( "", "297"  ,"Bulk Purchase of Electricity"  ,"254");
t.createNode( "", "298"  ,"Bulk Purchase of Water (Where water supply is a function of the ULB)"  ,"254");
t.createNode( "", "299"  ,"Water Charges for Internal Use"  ,"254");
t.createNode( "", "300"  ,"Service Postage/Stamps"  ,"254");
t.createNode( "", "301"  ,"Legal Expenses"  ,"254");
t.createNode( "", "302"  ,"Computer related Expenses"  ,"254");
t.createNode( "", "303"  ,"Books and Periodicals, News Papers"  ,"254");
t.createNode( "", "304"  ,"Hospitality Expenses"  ,"254");
t.createNode( "", "305"  ,"Other Contingent Expenses"  ,"254");
t.createNode( "", "306"  ,"Municipal Council"  ,"196");
t.createNode( "", "307"  ,"General Administration"  ,"196");
t.createNode( "", "308"  ,"Finance and Audit Department"  ,"196");
t.createNode( "", "309"  ,"Law Department"  ,"196");
t.createNode( "", "310"  ,"Public Relations Department"  ,"196");
t.createNode( "", "311"  ,"Vigilance Department"  ,"196");
t.createNode( "", "312"  ,"Election Department"  ,"196");
t.createNode( "", "313"  ,"Collection of Taxes/Revenue Department"  ,"196");
t.createNode( "", "314"  ,"Information Technology"  ,"196");
t.createNode( "", "315"  ,"Urban Planning - Town Planning"  ,"196");
t.createNode( "", "316"  ,"Public Works - Lands and Buildings"  ,"196");
t.createNode( "", "317"  ,"Housing"  ,"196");
t.createNode( "", "318"  ,"Water Supply"  ,"196");
t.createNode( "", "319"  ,"Public Health and Medical Services"  ,"196");
t.createNode( "", "320"  ,"Sanitation Conservancy and  Sewerage"  ,"196");
t.createNode( "", "321"  ,"Solid Waste Management"  ,"196");
t.createNode( "", "322"  ,"Urban Forestry, Ecology and Environment"  ,"196");
t.createNode( "", "323"  ,"Urban Amenities and Facilities - Parks, Gardens and Playgrounds"  ,"196");
t.createNode( "", "324"  ,"Arts and Culture"  ,"196");
t.createNode( "", "325"  ,"Education"  ,"196");
t.createNode( "", "326"  ,"Burial and Cremations"  ,"196");
t.createNode( "", "327"  ,"Vital Statistics - Birth and Death Registration"  ,"196");
t.createNode( "", "328"  ,"Public Amenities - Street Lighting, Parking Lots, Bus Stops and Public Convenience"  ,"196");
t.createNode( "", "329"  ,"Slaughter Houses and Tanneries"  ,"196");
t.createNode( "", "330"  ,"Electricity Supply"  ,"196");
t.createNode( "", "331"  ,"Fire Fighting Services"  ,"196");
t.createNode( "", "332"  ,"Family Welfare"  ,"196");
t.createNode( "", "333"  ,"Veterinary Services and Animal Health"  ,"196");
t.createNode( "", "334"  ,"Social Services"  ,"196");
t.createNode( "", "335"  ,"Welfare of weaker sections of Society"  ,"196");
t.createNode( "", "336"  ,"Repairs and Maintenance - Buildings"  ,"306");
t.createNode( "", "337"  ,"Repair and Maintenance - Roads and Bridges"  ,"306");
t.createNode( "", "338"  ,"Repairs and Maintenance - Fly-overs"  ,"306");
t.createNode( "", "339"  ,"Repairs and Maintenance - Swimming Pools"  ,"306");
t.createNode( "", "340"  ,"Repairs and Maintenance - Stadium"  ,"306");
t.createNode( "", "341"  ,"Repairs and Maintenance - Plants and Machinery"  ,"306");
t.createNode( "", "342"  ,"Repairs and Maintenance - Vehicles"  ,"306");
t.createNode( "", "343"  ,"Repairs and Maintenance - Furniture, Fixtures and Electrical Appliances"  ,"306");
t.createNode( "", "344"  ,"Repairs and Maintenance - Office and Other Equipment Instruments"  ,"306");
t.createNode( "", "345"  ,"Repairs and Maintenance - Other Fixed Assets"  ,"306");
t.createNode( "", "346"  ,"Repairs and Maintenance - Survey and Drawing Instruments"  ,"306");
t.createNode( "", "347"  ,"Repairs and Maintenance - Sewerage Drainage"  ,"306");
t.createNode( "", "348"  ,"Maintenance of Gardens/Parks"  ,"306");
t.createNode( "", "349"  ,"Maintenance of Nursery"  ,"306");
t.createNode( "", "350"  ,"Maintenance of Play Grounds"  ,"306");
t.createNode( "", "351"  ,"Maintenance of Play Materials"  ,"306");
t.createNode( "", "352"  ,"Repairs and Maintenance - Street Light"  ,"306");
t.createNode( "", "353"  ,"Repairs and Maintenance - Traffic Safety Devices"  ,"306");
t.createNode( "", "354"  ,"Interest on Loans from Central Government"  ,"197");
t.createNode( "", "355"  ,"Interest on Loans from State Government"  ,"197");
t.createNode( "", "356"  ,"Interest on Loans from Other Financial Institutions"  ,"197");
t.createNode( "", "357"  ,"Interest on Provident Funds"  ,"197");
t.createNode( "", "358"  ,"Interest on Debentures and Bonds"  ,"197");
t.createNode( "", "359"  ,"Bank Charges"  ,"197");
t.createNode( "", "360"  ,"Other Finance Charges"  ,"197");
t.createNode( "", "361"  ,"Election Expenses"  ,"198");
t.createNode( "", "362"  ,"Own Programmes"  ,"198");
t.createNode( "", "363"  ,"Share in Programmes of Others"  ,"198");
t.createNode( "", "364"  ,"Grants (give details)"  ,"199");
t.createNode( "", "365"  ,"Contributions (give details)"  ,"199");
t.createNode( "", "366"  ,"Subsidies (give detials)"  ,"199");
t.createNode( "", "367"  ,"Provision for doubtful receivables"  ,"200");
t.createNode( "", "368"  ,"Discount/remission"  ,"200");
t.createNode( "", "369"  ,"Revenues written off"  ,"200");
t.createNode( "", "370"  ,"Miscellaneous Expenses written off"  ,"200");
t.createNode( "", "371"  ,"Loss on account of Sale of tools and Plants and other items"  ,"201");
t.createNode( "", "372"  ,"Miscellaneous contingent expenses"  ,"201");
t.createNode( "", "373"  ,"Builidings"  ,"202");
t.createNode( "", "374"  ,"Roads and Bridges"  ,"202");
t.createNode( "", "375"  ,"Flyovers"  ,"202");
t.createNode( "", "376"  ,"Sewerage and Drainage"  ,"202");
t.createNode( "", "377"  ,"Water Ways"  ,"202");
t.createNode( "", "378"  ,"Plants and Machinery"  ,"202");
t.createNode( "", "379"  ,"Vehicles"  ,"202");
t.createNode( "", "380"  ,"Office and Other Equipment"  ,"202");
t.createNode( "", "381"  ,"Furniture, Fixtures, Fittings and Electrical Appliances"  ,"202");
t.createNode( "", "382"  ,"Other Fixed Assets (Specify)"  ,"202");
t.createNode( "", "383"  ,"Municipal (General) Fund"  ,"3");
t.createNode( "", "384"  ,"Earmarked Funds"  ,"3");
t.createNode( "", "385"  ,"Reserve Funds"  ,"3");
t.createNode( "", "386"  ,"Loans"  ,"3");
t.createNode( "", "387"  ,"Deposits Received"  ,"3");
t.createNode( "", "388"  ,"Grants and Contributions for specific purposes"  ,"3");
t.createNode( "", "389"  ,"Sale Proceeds from Assets"  ,"3");
t.createNode( "", "390"  ,"Deposit Wroks"  ,"3");
t.createNode( "", "391"  ,"Realisation of Investments - General Fund"  ,"3");
t.createNode( "", "392"  ,"Realisation of Investments - Other Funds"  ,"3");
t.createNode( "", "393"  ,"Recoveries of Loans and Advances from Staff"  ,"3");
t.createNode( "", "394"  ,"General Provident Fund/Contributory Provident Fund"  ,"3");
t.createNode( "", "395"  ,"Income Tax deducted from Contracotrs/Suppliers"  ,"3");
t.createNode( "", "396"  ,"Income Tax deducted from Staff"  ,"3");
t.createNode( "", "397"  ,"Sales Tax deducted from Contractors/Suppliers"  ,"3");
t.createNode( "", "398"  ,"Sale Proceeds from Stores (inventories)"  ,"3");
t.createNode( "", "399"  ,"Pension Fund"  ,"385");
t.createNode( "", "400"  ,"General Provident Fund/Contributory Provident Fund"  ,"385");
t.createNode( "", "401"  ,"Capital Reserve"  ,"385");
t.createNode( "", "402"  ,"Any other reserve fund (specify)"  ,"385");
t.createNode( "", "403"  ,"Loans from Central Government (give details)"  ,"386");
t.createNode( "", "404"  ,"Loans from State Government (give details)"  ,"386");
t.createNode( "", "405"  ,"Loans from Govt. Bodies and Associations"  ,"386");
t.createNode( "", "406"  ,"Loans from financial institutions (give details)"  ,"386");
t.createNode( "", "407"  ,"Loans from Banks"  ,"386");
t.createNode( "", "408"  ,"Loans from International Agencies"  ,"386");
t.createNode( "", "409"  ,"Other Term Loans (give details)"  ,"386");
t.createNode( "", "410"  ,"Bonds and Debentures"  ,"386");
t.createNode( "", "411"  ,"From Contractors - Suppliers"  ,"387");
t.createNode( "", "412"  ,"From Staff"  ,"387");
t.createNode( "", "413"  ,"From Others"  ,"387");
t.createNode( "", "414"  ,"Public Works Deposits. - Earnest Money - Security Deposit"  ,"387");
t.createNode( "", "415"  ,"Any other (specify)"  ,"387");
t.createNode( "", "416"  ,"Grants from Centrall Govt. (give details)"  ,"388");
t.createNode( "", "417"  ,"Gransts from State Govt. (give details)"  ,"388");
t.createNode( "", "418"  ,"Grants from Others (give details)"  ,"388");
t.createNode( "", "419"  ,"Land"  ,"389");
t.createNode( "", "420"  ,"Buildings"  ,"389");
t.createNode( "", "421"  ,"Plants and Machinery"  ,"389");
t.createNode( "", "422"  ,"Vehicles"  ,"389");
t.createNode( "", "423"  ,"Office and Other Equipment"  ,"389");
t.createNode( "", "424"  ,"Furniture, Fixtures, Fittings and Electrical Appliances"  ,"389");
t.createNode( "", "425"  ,"Other Fixed Asets (Specify)"  ,"389");
t.createNode( "", "426"  ,"Civil Works"  ,"390");
t.createNode( "", "427"  ,"Electrical Works"  ,"390");
t.createNode( "", "428"  ,"Others"  ,"390");
t.createNode( "", "429"  ,"General Fund Investment"  ,"391");
t.createNode( "", "430"  ,"GPF Investment"  ,"392");
t.createNode( "", "431"  ,"Pension Fund Investment"  ,"392");
t.createNode( "", "432"  ,"Any other Investment (Specify)"  ,"392");
t.createNode( "", "433"  ,"House Building Advance"  ,"393");
t.createNode( "", "434"  ,"Conveyance Advance"  ,"393");
t.createNode( "", "435"  ,"Computer Advance"  ,"393");
t.createNode( "", "436"  ,"Festival Advance"  ,"393");
t.createNode( "", "437"  ,"Other Advance"  ,"393");
t.createNode( "", "438"  ,"Central Store"  ,"398");
t.createNode( "", "439"  ,"Engineering Store"  ,"398");
t.createNode( "", "440"  ,"Auto Store"  ,"398");
t.createNode( "", "441"  ,"Medical Store"  ,"398");
t.createNode( "", "442"  ,"Health Store"  ,"398");
t.createNode( "", "443"  ,"Stationery Store"  ,"398");
t.createNode( "", "444"  ,"Storm Water Store"  ,"398");
t.createNode( "", "445"  ,"Drainage Store"  ,"398");
t.createNode( "", "446"  ,"Sewerage Store"  ,"398");
t.createNode( "", "447"  ,"Sanitary and Conservancy Store"  ,"398");
t.createNode( "", "448"  ,"Water Supply Store"  ,"398");
t.createNode( "", "449"  ,"Electricty Store"  ,"398");
t.createNode( "", "450"  ,"Machinery Spares"  ,"398");
t.createNode( "", "451"  ,"Linen and Furnishings"  ,"398");
t.createNode( "", "452"  ,"Education Store"  ,"398");
t.createNode( "", "453"  ,"Survey and Drawing Instruments"  ,"398");
t.createNode( "", "454"  ,"Loose Tools"  ,"398");
t.createNode( "", "455"  ,"Others (Specify)"  ,"398");
t.createNode( "", "456"  ,"Reserve Funds"  ,"4");
t.createNode( "", "457"  ,"Repayment of Loans"  ,"4");
t.createNode( "", "458"  ,"Refund of Deposits"  ,"4");
t.createNode( "", "459"  ,"Acquisition/Purchase of Fixed Assets"  ,"4");
t.createNode( "", "460"  ,"Capital Work-in Progress"  ,"4");
t.createNode( "", "461"  ,"Deposits Works"  ,"4");
t.createNode( "", "462"  ,"Investments - General Fund"  ,"4");
t.createNode( "", "463"  ,"Investments - Other Funds"  ,"4");
t.createNode( "", "464"  ,"Loans and Advances to Employees"  ,"4");
t.createNode( "", "465"  ,"General Provident Fund/Contributory Provident Fund - Advances/Withdrawals"  ,"4");
t.createNode( "", "466"  ,"Remittance of Income Tax Recovered from Contractors/Suppliers etc."  ,"4");
t.createNode( "", "467"  ,"Remittance of Income Tax Recovered from Staff"  ,"4");
t.createNode( "", "468"  ,"Remittance of Sales Tax Recovered from Contractors / Suppliers etc."  ,"4");
t.createNode( "", "469"  ,"Other Remittances"  ,"4");
t.createNode( "", "470"  ,"Purchase of Stores (Inventories)"  ,"4");
t.createNode( "", "471"  ,"Prepaid Expenses"  ,"4");
t.createNode( "", "472"  ,"Cash Balance"  ,"4");
t.createNode( "", "473"  ,"Capital Reserve"  ,"456");
t.createNode( "", "474"  ,"Any other Reserve Fund (specify)"  ,"456");
t.createNode( "", "475"  ,"Loans from Central Government (give details)"  ,"457");
t.createNode( "", "476"  ,"Loans from State Government (give details)"  ,"457");
t.createNode( "", "477"  ,"Loans from Govt. Bodies and Associations"  ,"457");
t.createNode( "", "478"  ,"Loans from Financial Institutions (give details)"  ,"457");
t.createNode( "", "479"  ,"Loans from Banks"  ,"457");
t.createNode( "", "480"  ,"Loans from International Agencies"  ,"457");
t.createNode( "", "481"  ,"Other Term Loans (give details)"  ,"457");
t.createNode( "", "482"  ,"Bonds and Debentures"  ,"457");
t.createNode( "", "483"  ,"Reund of Deposits to Contractors - Suppliers"  ,"458");
t.createNode( "", "484"  ,"Refund of Deposits to Staff"  ,"458");
t.createNode( "", "485"  ,"Refund of Deposits to Others"  ,"458");
t.createNode( "", "486"  ,"Refund of Earnest Money - Security Deposits - PW Deposits"  ,"458");
t.createNode( "", "498"  ,"Civil Works"  ,"460");
t.createNode( "", "499"  ,"Electrical Works"  ,"460");
t.createNode( "", "500"  ,"Others"  ,"460");
t.createNode( "", "501"  ,"Civil Works"  ,"461");
t.createNode( "", "502"  ,"Electrical Works"  ,"461");
t.createNode( "", "503"  ,"Others"  ,"461");
t.createNode( "", "504"  ,"General Fund Investment"  ,"462");
t.createNode( "", "505"  ,"GPF Investment"  ,"463");
t.createNode( "", "506"  ,"Pension Fund Investment"  ,"463");
t.createNode( "", "507"  ,"Any other Investment (Specify)"  ,"463");
t.createNode( "", "508"  ,"House Building Advance"  ,"464");
t.createNode( "", "509"  ,"Conveyance Advance"  ,"464");
t.createNode( "", "510"  ,"Computer Advance"  ,"464");
t.createNode( "", "511"  ,"Festival Advance"  ,"464");
t.createNode( "", "512"  ,"Any Other Advances"  ,"464");
t.createNode( "", "513"  ,"Central Store"  ,"470");
t.createNode( "", "514"  ,"Engineering Store"  ,"470");
t.createNode( "", "515"  ,"Auto Store"  ,"470");
t.createNode( "", "516"  ,"Medical Store"  ,"470");
t.createNode( "", "517"  ,"Health Store"  ,"470");
t.createNode( "", "518"  ,"Stationery Store"  ,"470");
t.createNode( "", "519"  ,"Storm Water Store"  ,"470");
t.createNode( "", "520"  ,"Drainage Store"  ,"470");
t.createNode( "", "521"  ,"Sewerage Store"  ,"470");
t.createNode( "", "522"  ,"Sanitary and Conservancy Store"  ,"470");
t.createNode( "", "523"  ,"Water Supply Store"  ,"470");
t.createNode( "", "524"  ,"Electricty Store"  ,"470");
t.createNode( "", "525"  ,"Machinery Spares"  ,"470");
t.createNode( "", "526"  ,"Linen and Furnishings"  ,"470");
t.createNode( "", "527"  ,"Education Store"  ,"470");
t.createNode( "", "528"  ,"Survey and Drawing Instruments"  ,"470");
t.createNode( "", "529"  ,"Loose Tools"  ,"470");
t.createNode( "", "530"  ,"Others (Specify)"  ,"470");


t.normalBackgroundColor="white" ;
t.highlightedbackgroundColor="blue";
t.normalColor="navy";
t.highlightedColor="white";
t.fontFamily="tahoma";
t.fontSize="8pt";
t.indent="20";
t.searchIsRequired="true";

t.addImg("main" , "/egi/resources/erp2/images/main.gif");
t.addImg("sub" , "/egi/resources/erp2/images/sub.gif");
t.addImg("accounthead","/egi/resources/erp2/images/head.gif");
t.addImg("account","/egi/resources/erp2/images/account.gif");
alert ('completed');
t.display();
window.status = 'completed';
	
