INSERT INTO EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) 
values (NEXTVAL('SEQ_EG_ACTION'),'GRIEVANCE_REGISTER_OFFICIAL_TYPE_BY_CATEGORY_DROPDOWN','/complaint/officials/complainttypes-by-category',null,(select id from EG_MODULE where name = 'PGR_MAIN'),1,'List Complaint Type By Category Off',false,'pgr',0,1,now(),1,now(),(select id from eg_module  where name = 'PGR'));


INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) VALUES ((SELECT id FROM eg_role WHERE name='PGR VIEW ACCESS'),
 (select id from eg_action where name='GRIEVANCE_REGISTER_OFFICIAL_TYPE_BY_CATEGORY_DROPDOWN'));