update egpgr_complainttype set slahours= 72 where name= 'Absenteesim of door to door garbage collector';
update egpgr_complainttype set slahours= 72 where name= 'Absenteesim of sweepers';
update egpgr_complainttype set slahours= 72 where name= 'Bio Medical waste/Health hazard waste removal';
update egpgr_complainttype set slahours= 72 where name= 'Burning of garbage';
update egpgr_complainttype set slahours= 72 where name= 'Complaints regarding burial ground';
update egpgr_complainttype set slahours= 72 where name= 'Complaints regarding Dispensary';
update egpgr_complainttype set slahours= 72 where name= 'Complaints regarding public toilets';
update egpgr_complainttype set slahours= 72 where name= 'Complaints regarding restaurants / Function halls';
update egpgr_complainttype set slahours= 168 where name= 'Complaints regarding Schools';
update egpgr_complainttype set slahours= 168 where name= 'Complaints regarding Voter list';
update egpgr_complainttype set slahours= 72 where name= 'Desilting of Drain';
update egpgr_complainttype set slahours= 72 where name= 'Disposal of removed silt on the Road';
update egpgr_complainttype set slahours= 72 where name= 'Dog menace';
update egpgr_complainttype set slahours= 168 where name= 'Illegal draining of sewage to SWD/Open site';
update egpgr_complainttype set slahours= 168 where name= 'Inclusion, delection of correction in the Voter list';
update egpgr_complainttype set slahours= 720 where name= 'Maintenance of Parks';
update egpgr_complainttype set slahours= 720 where name= 'Maintenance of Playground';
update egpgr_complainttype set slahours= 72 where name= 'Mosquito menace';
update egpgr_complainttype set slahours= 72 where name= 'Obstruction of road by Trees branches';
update egpgr_complainttype set slahours= 72 where name= 'Obstruction of water flow';
update egpgr_complainttype set slahours= 72 where name= 'Over flowing of garbage bins';
update egpgr_complainttype set slahours= 72 where name= 'Poor quality of work';
update egpgr_complainttype set slahours= 720 where name= 'Pot hole fill up/Repairs to the damage surface';
update egpgr_complainttype set slahours= 168 where name= 'Provision of garbage bin';
update egpgr_complainttype set slahours= 72 where name= 'Removal of fallen trees';
update egpgr_complainttype set slahours= 72 where name= 'Removal of garbage';
update egpgr_complainttype set slahours= 720 where name= 'Repairs to Centre Median';
update egpgr_complainttype set slahours= 720 where name= 'Repairs to existing footpath';
update egpgr_complainttype set slahours= 720 where name= 'Repairs to Flyovers/ bridges/ Culverts';
update egpgr_complainttype set slahours= 720 where name= 'Repairs to the SWD';
update egpgr_complainttype set slahours= 720 where name= 'Repairs to Traffic Island';
update egpgr_complainttype set slahours= 72 where name= 'Request for Anti Larval operations - to prevent  Dengue /Malaria etc';
update egpgr_complainttype set slahours= 168 where name= 'Shifting of garbage bin';
update egpgr_complainttype set slahours= 72 where name= 'Stagnation of water';
update egpgr_complainttype set slahours= 72 where name= 'Stoppage of Civil Works';
update egpgr_complainttype set slahours= 72 where name= 'UGD Over Flow';
update egpgr_complainttype set slahours= 168 where name= 'Unauthorised Road cutting';
update egpgr_complainttype set slahours= 72 where name= 'Unauthorised tree Cutting';
update egpgr_complainttype set slahours= 168 where name= 'Unhygeinic conditions because of Slaughter House';
update egpgr_complainttype set slahours= 72 where name= 'Unsanitary conditions on the road';

