                     
----------- installment from 1998-2004 ----------------


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 042004, '2004-04-01 00:00:00','2004-04-01 00:00:00','2004-09-30 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2004-2005-1', NULL,'2004-05');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 102004, '2004-10-01 00:00:00','2004-10-01 00:00:00','2005-03-31 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2004-2005-2', NULL,'2004-05');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 042003, '2003-04-01 00:00:00','2003-04-01 00:00:00','2003-09-30 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2003-2004-1', NULL,'2003-04');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 102003, '2003-10-01 00:00:00','2003-10-01 00:00:00','2004-03-31 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2003-2004-2', NULL,'2003-04');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 042002, '2002-04-01 00:00:00','2002-04-01 00:00:00','2002-09-30 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2002-2003-1', NULL,'2002-03');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 102002, '2002-10-01 00:00:00','2002-10-01 00:00:00','2003-03-31 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2002-2003-2', NULL,'2002-03');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 042001, '2001-04-01 00:00:00','2001-04-01 00:00:00','2001-09-30 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2001-2002-1', NULL,'2001-02');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 102001, '2001-10-01 00:00:00','2001-10-01 00:00:00','2002-03-31 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2001-2002-2', NULL,'2001-02');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 042000, '2000-04-01 00:00:00','2000-04-01 00:00:00','2000-09-30 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2000-2001-1', NULL,'2000-01');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 102000, '2000-10-01 00:00:00','2000-10-01 00:00:00','2001-03-31 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2000-2001-2', NULL,'2000-01');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 041999, '1999-04-01 00:00:00','1999-04-01 00:00:00','1999-09-30 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '1999-2000-1', NULL,'1999-00');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 101999, '1999-10-01 00:00:00','1999-10-01 00:00:00','2000-03-31 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '1999-2000-2', NULL,'1999-00');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 041998, '1998-04-01 00:00:00','1998-04-01 00:00:00','1998-09-30 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '1998-1999-1', NULL,'1998-99');


INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 101998, '1998-10-01 00:00:00','1998-10-01 00:00:00','1999-03-31 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '1998-1999-2', NULL,'1998-99');



---------------- DEMAND_REASON from 1998 -----------------




Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Sewerage Tax' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2004-05');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Sewerage Tax' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2003-04');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Sewerage Tax' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2002-03');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Sewerage Tax' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2001-02');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Sewerage Tax' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2000-01');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Sewerage Tax' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp,(select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='1999-00');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Sewerage Tax' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp,(select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='1998-99');



----------------------------------------------------------------------------------------------------------------------------------------

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Donation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1603006') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2004-05');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Donation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1603006') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2003-04');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Donation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1603006') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2002-03');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Donation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1603006') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2001-02');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Donation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1603006') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2000-01');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Donation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1603006') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='1999-00');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Donation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1603006') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='1998-99');


--------------------------------------------------------------------------------------------------------------------------------------------


Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Inspection Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2004-05');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Inspection Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2003-04');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Inspection Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2002-03');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Inspection Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2001-02');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Inspection Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2000-01');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Inspection Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='1999-00');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Inspection Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='1998-99');

-------------------------------------------------------------------------------------------------------------------------------------------

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Estimation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2004-05'); 
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Estimation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2003-04'); 
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Estimation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2002-03'); 
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Estimation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2001-02'); 
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Estimation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2000-01'); 
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Estimation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='1999-00');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Estimation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='1998-99');  


----------------------------------------------------------------------------------------------------------------------------------------

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='SEWERAGEADVANCE' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='3504199') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2004-05'); 
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='SEWERAGEADVANCE' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='3504199') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2003-04'); 
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='SEWERAGEADVANCE' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='3504199') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2002-03'); 
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='SEWERAGEADVANCE' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='3504199') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2001-02'); 
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='SEWERAGEADVANCE' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='3504199') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2000-01'); 
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='SEWERAGEADVANCE' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='3504199') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='1999-00'); 
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='SEWERAGEADVANCE' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='3504199') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='1998-99'); 






