INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 042019, '2019-04-01 00:00:00','2019-04-01 00:00:00','2019-09-30 23:59:59', (select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2019-2020-1', NULL,'2019-20');

INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type,financial_year) VALUES (nextval('SEQ_EG_INSTALLMENT_MASTER'), 102019, '2019-10-01 00:00:00','2019-10-01 00:00:00','2020-03-31 23:59:59',(select id from eg_module  where name = 'Sewerage Tax Management'and parentmodule is null), current_timestamp, '2019-2020-2', NULL,'2019-20');

INSERT INTO EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='SEWERAGEADVANCE' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='3504199') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2019-20');

INSERT INTO EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Sewerage Tax' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2019-20');

INSERT INTO EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Donation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1603006') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2019-20');

INSERT INTO EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Inspection Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2019-20');

INSERT INTO EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) (select (nextval('seq_eg_demand_reason')), (select id from eg_demand_reason_master where reasonmaster='Estimation Charge' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404019') from eg_installment_master inst  where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.financial_year='2019-20');
