CREATE TABLE EGSWTAX_DEMAND_VOUCHER
(
  ID BIGINT NOT NULL,
  APPLICATIONDETAIL BIGINT NOT NULL,
  VOUCHERHEADER BIGINT NOT NULL,
  CREATEDBY BIGINT NOT NULL,
  LASTMODIFIEDBY BIGINT NOT NULL,
  CREATEDDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  VERSION NUMERIC DEFAULT 0,
  CONSTRAINT PK_EGSWTAX_DEMAND_VOUCHER_ID PRIMARY KEY (ID),
  CONSTRAINT FK_EGSWTAX_DEMAND_VOUCHER_CREATEDBY FOREIGN KEY (CREATEDBY) REFERENCES EG_USER (ID),
  CONSTRAINT FK_EGSWTAX_DEMAND_VOUCHER_LASTMODIFIEDBY FOREIGN KEY (LASTMODIFIEDBY) REFERENCES EG_USER (ID),
  CONSTRAINT FK_EGSWTAX_DEMAND_VOUCHER_APPDET FOREIGN KEY (APPLICATIONDETAIL) REFERENCES EGSWTAX_APPLICATIONDETAILS (ID)
);

CREATE INDEX idx_stax_demandvoucher_appdetail ON EGSWTAX_DEMAND_VOUCHER(APPLICATIONDETAIL);
CREATE INDEX idx_stax_demandvoucher_voucherheader ON EGSWTAX_DEMAND_VOUCHER(VOUCHERHEADER);

COMMENT ON COLUMN EGSWTAX_DEMAND_VOUCHER.applicationdetail IS 'primary key of EGSWTAX_APPLICATIONDETAILS';
COMMENT ON COLUMN EGSWTAX_DEMAND_VOUCHER.voucherheader IS 'primary key of voucherheader';
COMMENT ON TABLE EGSWTAX_DEMAND_VOUCHER IS 'This table stores link between sewerage application details and voucherheader';

CREATE SEQUENCE SEQ_EGSWTAX_DEMAND_VOUCHER;
