package org.egov.pims.model;

// Generated Jul 9, 2007 3:21:09 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * DeptTests generated by hbm2java
 */
public class DeptTests implements java.io.Serializable
{

	private Integer deptTestsId;

	private TestNameMaster nameOfTestMstr;

	private PersonalInformation employeeId;

	private Date dateOfPass;

	public DeptTests()
	{
	}

	public DeptTests(Integer deptTestsId
			 )
	{
		this.deptTestsId = deptTestsId;

	}

	public DeptTests(Integer deptTestsId,
			TestNameMaster egpimsNameOfTestMstr,
			 Date dateOfPass)
	{
		this.deptTestsId = deptTestsId;
		this.nameOfTestMstr = egpimsNameOfTestMstr;

		this.dateOfPass = dateOfPass;
	}

	public Integer getDeptTestsId()
	{
		return this.deptTestsId;
	}

	public void setDeptTestsId(Integer deptTestsId)
	{
		this.deptTestsId = deptTestsId;
	}

	public TestNameMaster getNameOfTestMstr()
	{
		return this.nameOfTestMstr;
	}

	public void setNameOfTestMstr(
			TestNameMaster nameOfTestMstr)
	{
		this.nameOfTestMstr = nameOfTestMstr;
	}


	public Date getDateOfPass()
	{
		return this.dateOfPass;
	}

	public void setDateOfPass(Date dateOfPass)
	{
		this.dateOfPass = dateOfPass;
	}

	public PersonalInformation getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(PersonalInformation employeeId) {
		this.employeeId = employeeId;
	}

}
