package org.egov.pims.model;

// Generated Jul 9, 2007 3:21:09 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * EduDetails generated by hbm2java
 */
public class EduDetails implements java.io.Serializable
{

	private Integer educationDetailsId;


	private PersonalInformation employeeId;
	private String uniBoard;

	private String qulificationMaster;

	private String majorSubject;

	private Date monthYearPass;
	
	private Long docNo;

	public EduDetails()
	{
	}

	public EduDetails(Integer educationDetailsId,String eduDocNo)
	{
		this.educationDetailsId = educationDetailsId;
		this.docNo=docNo.equals("")? this.docNo : Long.valueOf(eduDocNo);

	}

	

	public Integer getEducationDetailsId()
	{
		return this.educationDetailsId;
	}

	public void setEducationDetailsId(Integer educationDetailsId)
	{
		this.educationDetailsId = educationDetailsId;
	}



	public String getUniBoard()
	{
		return this.uniBoard;
	}

	public void setUniBoard(String uniBoard)
	{
		this.uniBoard = uniBoard;
	}



	public String getMajorSubject()
	{
		return this.majorSubject;
	}

	public void setMajorSubject(String majorSubject)
	{
		this.majorSubject = majorSubject;
	}

	public Date getMonthYearPass()
	{
		return this.monthYearPass;
	}

	public void setMonthYearPass(Date monthYearPass)
	{
		this.monthYearPass = monthYearPass;
	}

	/**
	 * @return Returns the qulificationMaster.
	 */
	public String getQulificationMaster() {
		return qulificationMaster;
	}
	/**
	 * @param qulificationMaster The qulificationMaster to set.
	 */
	public void setQulificationMaster(String qulificationMaster) {
		this.qulificationMaster = qulificationMaster;
	}

	public PersonalInformation getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(PersonalInformation employeeId) {
		this.employeeId = employeeId;
	}

	public Long getDocNo() {
		return docNo;
	}

	public void setDocNo(Long docNo) {
		this.docNo = docNo;
	}
	
	
}
