package org.egov.pims.model;

// Generated Jul 9, 2007 3:21:09 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

/**
 * ImmovablePropDetails generated by hbm2java
 */
public class ImmovablePropDetails implements java.io.Serializable
{

	private Integer immPropertyDetailsId;

	private PersonalInformation employeeId;

	private HowAcquiredMaster howAcquiredMstr;

	private String propertyDescription;

	private String place;

	private BigDecimal presentValue;

	private Character permissionObtained= new Character('0');

	private String orderNo;

	private Date orderDate;

	public ImmovablePropDetails()
	{
	}

	public ImmovablePropDetails(Integer immPropertyDetailsId)
	{
		this.immPropertyDetailsId = immPropertyDetailsId;
	}

	public ImmovablePropDetails(Integer immPropertyDetailsId,

			HowAcquiredMaster egpimsHowAcquiredMstr,
			String propertyDescription, String place, BigDecimal presentValue,
			Character permissionObtained, String orderNo, Date orderDate)
	{
		this.immPropertyDetailsId = immPropertyDetailsId;

		this.howAcquiredMstr = howAcquiredMstr;
		this.propertyDescription = propertyDescription;
		this.place = place;
		this.presentValue = presentValue;
		this.permissionObtained = permissionObtained;
		this.orderNo = orderNo;
		this.orderDate = orderDate;
	}

	public Integer getImmPropertyDetailsId()
	{
		return this.immPropertyDetailsId;
	}

	public void setImmPropertyDetailsId(Integer immPropertyDetailsId)
	{
		this.immPropertyDetailsId = immPropertyDetailsId;
	}



	public HowAcquiredMaster getHowAcquiredMstr()
	{
		return this.howAcquiredMstr;
	}

	public void setHowAcquiredMstr(
			HowAcquiredMaster howAcquiredMstr)
	{
		this.howAcquiredMstr = howAcquiredMstr;
	}

	public String getPropertyDescription()
	{
		return this.propertyDescription;
	}

	public void setPropertyDescription(String propertyDescription)
	{
		this.propertyDescription = propertyDescription;
	}

	public String getPlace()
	{
		return this.place;
	}

	public void setPlace(String place)
	{
		this.place = place;
	}

	public BigDecimal getPresentValue()
	{
		return this.presentValue;
	}

	public void setPresentValue(BigDecimal presentValue)
	{
		this.presentValue = presentValue;
	}

	public Character getPermissionObtained()
	{
		return this.permissionObtained;
	}
	public void setPermissionObtained(Character permissionObtained)
	{
		this.permissionObtained = permissionObtained;
	}
	public String getOrderNo()
	{
		return this.orderNo;
	}
	public void setOrderNo(String orderNo)
	{
		this.orderNo = orderNo;
	}

	public Date getOrderDate()
	{
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate)
	{
		this.orderDate = orderDate;
	}

	public PersonalInformation getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(PersonalInformation employeeId) {
		this.employeeId = employeeId;
	}

}
