package org.egov.pims.model;

// Generated Jul 9, 2007 3:21:09 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * LtcPirticulars generated by hbm2java
 */
public class LtcPirticulars implements java.io.Serializable
{

	private Integer ltcDetailsId;
	private String blockYear;

	private String claimedWayFare;
	private PersonalInformation employeeId;

	private String orderNo;

	private Date orderDate;

	private String leaveType;

	public LtcPirticulars()
	{
	}

	public LtcPirticulars(Integer ltcDetailsId)
	{
		this.ltcDetailsId = ltcDetailsId;
	}

	public LtcPirticulars(Integer ltcDetailsId,
			String blockYear, String claimedWayFare, String orderNo,
			Date orderDate, String leaveType)
	{
		this.ltcDetailsId = ltcDetailsId;

		this.blockYear = blockYear;
		this.claimedWayFare = claimedWayFare;
		this.orderNo = orderNo;
		this.orderDate = orderDate;
		this.leaveType = leaveType;
	}

	public Integer getLtcDetailsId()
	{
		return this.ltcDetailsId;
	}

	public void setLtcDetailsId(Integer ltcDetailsId)
	{
		this.ltcDetailsId = ltcDetailsId;
	}



	public String getBlockYear()
	{
		return this.blockYear;
	}

	public void setBlockYear(String blockYear)
	{
		this.blockYear = blockYear;
	}

	public String getClaimedWayFare()
	{
		return this.claimedWayFare;
	}

	public void setClaimedWayFare(String claimedWayFare)
	{
		this.claimedWayFare = claimedWayFare;
	}

	public String getOrderNo()
	{
		return this.orderNo;
	}

	public void setOrderNo(String orderNo)
	{
		this.orderNo = orderNo;
	}

	public Date getOrderDate()
	{
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate)
	{
		this.orderDate = orderDate;
	}

	public String getLeaveType()
	{
		return this.leaveType;
	}

	public void setLeaveType(String leaveType)
	{
		this.leaveType = leaveType;
	}

	public PersonalInformation getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(PersonalInformation employeeId) {
		this.employeeId = employeeId;
	}

}
