package org.egov.pims.model;

// Generated Jul 9, 2007 3:21:09 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

import org.egov.pims.commons.DesignationMaster;

/**
 * Probation generated by hbm2java
 */
public class Probation implements java.io.Serializable,Comparable<Probation>
{

	private Integer idProbation;
	

	PersonalInformation employeeId;

	private DesignationMaster postMstr;

	private Date probationFromDate;

	private Date probationToDate; 

	private String orderNo;

	private Date orderDate;

	public Probation()
	{
	}

	public Probation(Integer idProbation)
	{
		this.idProbation = idProbation;

	}

	public Probation(Integer idProbation,

			DesignationMaster egpimsPostMstr, Date probationFromDate,
			String orderNo, Date orderDate)
	{
		this.idProbation = idProbation;

		this.postMstr = egpimsPostMstr;
		this.probationFromDate = probationFromDate;
		this.orderNo = orderNo;
		this.orderDate = orderDate;
	}

	public Integer getIdProbation()
	{
		return this.idProbation;
	}

	public void setIdProbation(Integer idProbation)
	{
		this.idProbation = idProbation;
	}

	public Date getProbationFromDate() {
		return probationFromDate;
	}

	public void setProbationFromDate(Date probationFromDate) {
		this.probationFromDate = probationFromDate;
	}

	public Date getProbationToDate() {
		return probationToDate;
	}

	public void setProbationToDate(Date probationToDate) {
		this.probationToDate = probationToDate;
	}

	public DesignationMaster getPostMstr()
	{
		return this.postMstr;
	}

	public void setPostMstr(DesignationMaster egpimsPostMstr)
	{
		this.postMstr = egpimsPostMstr;
	}

	public String getOrderNo()
	{
		return this.orderNo;
	}

	public void setOrderNo(String orderNo)
	{
		this.orderNo = orderNo;
	}

	public Date getOrderDate()
	{
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate)
	{
		this.orderDate = orderDate;
	}

	public PersonalInformation getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(PersonalInformation employeeId) {
		this.employeeId = employeeId;
	}

	@Override
	public int compareTo(Probation probation) {
		if(!(probation instanceof Probation))
		{
			throw new ClassCastException("A Probation object expected.");
		}
		return this.probationFromDate.compareTo(probation.probationFromDate);
	}

}