package org.egov.pims.model;

// Generated Jul 9, 2007 3:21:09 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * TecnicalQualification generated by hbm2java
 */
public class TecnicalQualification implements java.io.Serializable
{

	private Integer tecnicalQulificationId;
	private Date passedDate;
	private String remarks;
	TechnicalGradesMaster technicalGradesMaster;
	SkillMaster SkillMaster;
	PersonalInformation employeeId ;
	private Long docNo;
	public TecnicalQualification()
	{
	}
	public TecnicalQualification(Integer tecnicalQulificationId,String techDocNo)
	{
		this.tecnicalQulificationId = tecnicalQulificationId;
		this.docNo=techDocNo.equals("")? this.docNo : Long.valueOf(techDocNo);
	}

	public TecnicalQualification(Integer tecnicalQulificationId,


			 Date passedDate)
	{
		this.tecnicalQulificationId = tecnicalQulificationId;


		
		this.passedDate = passedDate;

	}

	public Integer getTecnicalQulificationId()
	{
		return this.tecnicalQulificationId;
	}

	public void setTecnicalQulificationId(Integer tecnicalQulificationId)
	{
		this.tecnicalQulificationId = tecnicalQulificationId;
	}




	public Date getPassedDate()
	{
		return this.passedDate;
	}

	public void setPassedDate(Date passedDate)
	{
		this.passedDate = passedDate;
	}
	/**
	 * @return Returns the technicalGradesMaster.
	 */
	public TechnicalGradesMaster getTechnicalGradesMaster() {
		return technicalGradesMaster;
	}
	/**
	 * @param technicalGradesMaster The technicalGradesMaster to set.
	 */
	public void setTechnicalGradesMaster(
			TechnicalGradesMaster technicalGradesMaster) {
		this.technicalGradesMaster = technicalGradesMaster;
	}
	/**
	 * @return Returns the skillMaster.
	 */
	public SkillMaster getSkillMaster() {
		return SkillMaster;
	}
	/**
	 * @param skillMaster The skillMaster to set.
	 */
	public void setSkillMaster(SkillMaster skillMaster) {
		SkillMaster = skillMaster;
	}
	public String getRemarks() {
		return remarks;
	}
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	public PersonalInformation getEmployeeId() {
		return employeeId;
	}
	public void setEmployeeId(PersonalInformation employeeId) {
		this.employeeId = employeeId;
	}
	public Long getDocNo() {
		return docNo;
	}

	public void setDocNo(Long docNo) {
		this.docNo = docNo;
	}
}
