insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Absenteesim of door to door garbage collector',(select id_dept from eg_department where dept_code='H'),24,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Absenteesim of sweepers',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Bio Medical waste/Health hazard waste removal',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Broken Bin',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Building plan sanction',null,168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Burning of garbage',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Change of address in Electoral Roll',(select id_dept from eg_department where dept_code='G'),336,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding  Cleanliness of Toilets in Shopping complex',(select id_dept from eg_department where dept_code='H'),72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding  Dispensary ',(select id_dept from eg_department where dept_code='H'),72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding Bridges/Flyovers/Subways',(select id_dept from eg_department where dept_code='J'),168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding Park',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding Play grounds',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding Schools',(select id_dept from eg_department where dept_code='E'),72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding Voter list',(select id_dept from eg_department where dept_code='R'),72,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding burial ground',(select id_dept from eg_department where dept_code='H'),24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding community hall',(select id_dept from eg_department where dept_code='R'),24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding public toilets',(select id_dept from eg_department where dept_code='H'),72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding quality of food in Hotels',(select id_dept from eg_department where dept_code='H'),24,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints regarding unauthorised restaurants',(select id_dept from eg_department where dept_code='H'),72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints related to issue of all types of license ',(select id_dept from eg_department where dept_code='H'),72,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Complaints related to property tax ',(select id_dept from eg_department where dept_code='R'),168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Covering of Man holes of SWD',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Damage to the  Electric Pole',(select id_dept from eg_department where dept_code='L'),72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Death of Stray Animals',(select id_dept from eg_department where dept_code='H'),24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Desilting of Canal',null,168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Desilting of Drain',null,168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Disposal of removed silt on the Road',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Dog menace ',(select id_dept from eg_department where dept_code='H'),120,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Electric Shock due to street light',(select id_dept from eg_department where dept_code='L'),24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Encroachment on the public property',null,168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Formation of New Road',null,168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Garbage lorry with out Net',null,24,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Illegal draining of sewage to SWD/Open site',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Illegal slaughtering',(select id_dept from eg_department where dept_code='H'),24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Improper Sweeping',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Issue of Birth and Death Certificate',(select id_dept from eg_department where dept_code='H'),72,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Mosquito menace ',(select id_dept from eg_department where dept_code='H'),72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Name Error (Spelling Related)',(select id_dept from eg_department where dept_code='G'),336,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Name not found in Electoral Roll',(select id_dept from eg_department where dept_code='G'),336,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'New Drain Construction',(select id_dept from eg_department where dept_code='D'),168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'New Street light',(select id_dept from eg_department where dept_code='L'),168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Non Burning of Street Lights',(select id_dept from eg_department where dept_code='L'),72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Nuisance by garbage tractors or trucks',null,24,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Obstruction of Trees',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Obstruction of water flow',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Over flowing of garbage bins ',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Over head cable Wires running in Hapazard manner',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Parking Issue',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Poor quality of work',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Pot hole fill up/Repairs to the damage surface',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Provision of garbage bin',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Public Health/Dengue/Malaria/Gastro-enteritis',(select id_dept from eg_department where dept_code='H'),24,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Removal of Debris',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Removal of fallen trees',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Removal of garbage',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Removal of shops in the footpath',null,168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Repairs to existing footpath',null,168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Repairs to the SWD',null,168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Request to provide footpath',null,168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Request to relay the Road',null,168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Road Side Eateries',(select id_dept from eg_department where dept_code='H'),24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Shifting of Street light Pole',(select id_dept from eg_department where dept_code='L'),168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Shifting of garbage bin',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Slaughter House',(select id_dept from eg_department where dept_code='H'),72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Slow progress of work',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Spilling of Garbage from lorry',null,24,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Stagnation of water',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Stray Pigs',(select id_dept from eg_department where dept_code='H'),24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Stray cattle',(select id_dept from eg_department where dept_code='H'),24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Transfer Station Smell',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Unauthorised / Illegal construction',null,168,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Unauthorised Advt. Boards',null,72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Unauthorised sale of meat and meat product',(select id_dept from eg_department where dept_code='H'),24,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Unauthorised tree Cutting',null,24,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Unhygienic and improper transport of meat and livestock',(select id_dept from eg_department where dept_code='H'),72,'FALSE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Unsanitary conditions on the road',(select id_dept from eg_department where dept_code='H'),72,'TRUE');
insert into pgr_complainttype (id,name,dept_id,days_to_resolve,location_required) values(nextval('seq_pgr_complainttype'),'Violation of DCR/Building bye laws',null,168,'TRUE');

