Insert into EG_HEIRARCHY_TYPE (ID_HEIRARCHY_TYPE,TYPE_NAME,UPDATEDTIME,TYPE_CODE)
values (1,'ADMINISTRATION',current_date,'ADMIN');
Insert into EG_HEIRARCHY_TYPE (ID_HEIRARCHY_TYPE,TYPE_NAME,UPDATEDTIME,TYPE_CODE) 
values (2,'LOCATION',current_date,'LOCATION');


