insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Junior enigineer','Junior enigineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Section managar','Section managar');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Zonal medical officer','Zonal medical officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Medical store officer','Medical store officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Sanitary worker','Sanitary worker');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Health inspector grade ii','Health inspector grade ii');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Veternary assistant surgeon','Veternary assistant surgeon');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Plumber','Plumber');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Additional revenue officer','Additional revenue officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'License inspector','License inspector');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistant law officer','Assistant law officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistant divisional electrical engineer','Assistant divisional electrical engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Additional health officer','Additional health officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Superintending  engineer','Superintending  engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistan executive engineer','Assistan executive engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Junior enigneer','Junior enigneer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Gardener','Gardener');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Zonal health officer','Zonal health officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Sweeper','Sweeper');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistant accounts officer','Assistant accounts officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Joint commissioner','Joint commissioner');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Li','Li');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Accounts officer','Accounts officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assessor','Assessor');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistant','Assistant');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistant cashier','Assistant cashier');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistant commissioner','Assistant commissioner');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistant divisional engineer','Assistant divisional engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistant engineer','Assistant engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistant executive engineer','Assistant executive engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistant health officer','Assistant health officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Supervisor','Supervisor');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Chief accounts officer','Chief accounts officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Chief engineer','Chief engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'City engineer','City engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Computer operator','Computer operator');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Conservancy inspector','Conservancy inspector');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Conservancy supervisor','Conservancy supervisor');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Divisional electrical engineer','Divisional electrical engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Driver','Driver');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Electrician','Electrician');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Executive engineer','Executive engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Financial adviser','Financial adviser');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Head cashier','Head cashier');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Health officer','Health officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Junior engineer','Junior engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Law officer','Law officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Licence inspector','Licence inspector');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Operator','Operator');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Public relation officer','Public relation officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Sanitary inspector','Sanitary inspector');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Sanitary officer','Sanitary officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Section manager','Section manager');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Statistical assistant','Statistical assistant');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Store keeper','Store keeper');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Superintending engineer','Superintending engineer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Tax collector','Tax collector');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Commissioner','Commissioner');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Zonal officer','Zonal officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Education officer','Education officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Financial advisor','Financial advisor');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Deputy commissioner','Deputy commissioner');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Assistant revenue officer','Assistant revenue officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Superintendent','Superintendent');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Vigilance inspector','Vigilance inspector');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Superintendent of park','Superintendent of park');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Vigilance officer','Vigilance officer');
insert into eg_designation (designationid,designation_name,designation_description) values (nextval('SEQ_DESIGNATION'),'Data entry operator','Data entry operator');

