Insert into EG_BOUNDARY_TYPE (ID_BNDRY_TYPE,HIERARCHY,PARENT,NAME,UPDATEDTIME,ID_HEIRARCHY_TYPE,BNDRYNAME_LOCAL) values (1,1,null,'City',to_date('01-08-05','DD-MM-RR'),1,null);
Insert into EG_BOUNDARY_TYPE (ID_BNDRY_TYPE,HIERARCHY,PARENT,NAME,UPDATEDTIME,ID_HEIRARCHY_TYPE,BNDRYNAME_LOCAL) values (4,1,null,'City',to_date('30-10-08','DD-MM-RR'),2,null);
Insert into EG_BOUNDARY_TYPE (ID_BNDRY_TYPE,HIERARCHY,PARENT,NAME,UPDATEDTIME,ID_HEIRARCHY_TYPE,BNDRYNAME_LOCAL) values (5,2,4,'Area',to_date('30-10-08','DD-MM-RR'),2,null);
Insert into EG_BOUNDARY_TYPE (ID_BNDRY_TYPE,HIERARCHY,PARENT,NAME,UPDATEDTIME,ID_HEIRARCHY_TYPE,BNDRYNAME_LOCAL) values (6,3,5,'Locality',to_date('30-10-08','DD-MM-RR'),2,null);
Insert into EG_BOUNDARY_TYPE (ID_BNDRY_TYPE,HIERARCHY,PARENT,NAME,UPDATEDTIME,ID_HEIRARCHY_TYPE,BNDRYNAME_LOCAL) values (7,4,6,'Street',to_date('30-10-08','DD-MM-RR'),2,null);
Insert into EG_BOUNDARY_TYPE (ID_BNDRY_TYPE,HIERARCHY,PARENT,NAME,UPDATEDTIME,ID_HEIRARCHY_TYPE,BNDRYNAME_LOCAL) values (8,2,1,'Region',to_date('19-03-14','DD-MM-RR'),1,null);
Insert into EG_BOUNDARY_TYPE (ID_BNDRY_TYPE,HIERARCHY,PARENT,NAME,UPDATEDTIME,ID_HEIRARCHY_TYPE,BNDRYNAME_LOCAL) values (2,3,8,'Zone',to_date('27-12-05','DD-MM-RR'),1,null);
Insert into EG_BOUNDARY_TYPE (ID_BNDRY_TYPE,HIERARCHY,PARENT,NAME,UPDATEDTIME,ID_HEIRARCHY_TYPE,BNDRYNAME_LOCAL) values (3,4,2,'Ward',to_date('12-07-10','DD-MM-RR'),1,'014');
