insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1981-01-10 00:00:00', null, 'M','Krishna','Rupanagunta','KrishnaRupanagunta','E007',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1964-10-03 00:00:00', null, 'F','Elzan','Mathew','ElzanMathew','E008',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1974-07-03 00:00:00', 'Tamil', 'F','Iffath','Fatima','IffathFatima','E018',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1980-11-11 00:00:00', 'Tamil', 'M','Nirbhay','Singh','NirbhaySingh','E019',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1973-11-06 00:00:00', 'Tamil', 'M','P R','Krishnamoorthy','P RKrishnamoorthy','E020',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1987-04-05 00:00:00', null, 'F','Rajashree','G','RajashreeG','E022',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1977-06-04 00:00:00', null, 'M','Ramakrishna','Ippilli','RamakrishnaIppilli','E023',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1976-03-03 00:00:00', null, 'M','Manikanta',' null','Manikanta null','E024',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1981-11-10 00:00:00', null, 'M','Rishi','Katara','RishiKatara','E025',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1986-08-03 00:00:00', null, 'M','Sathish','P','SathishP','E026',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1965-06-06 00:00:00', null, 'M','Satish','N','SatishN','E027',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '2008-09-05 00:00:00', null, 'M','Shahid','Ali.S','ShahidAli.S','E029',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1982-03-07 00:00:00', null, 'M','Sathyandra','Singh','SathyandraSingh','E031',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1983-10-11 00:00:00', null, 'M','Arun','Dev','ArunDev','E032',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1962-1-11 00:00:00', null, 'M','Mohanraj','K','MohanrajK','E033',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1975-04-06 00:00:00', null, 'M','P','Sankar','PSankar','E034',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1977-03-11 00:00:00', null, 'M','Vaibhav','K','VaibhavK','E035',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1975-06-09 00:00:00', null, 'M','Rajkumar','R','RajkumarR','E036',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1979-04-05 00:00:00', null, 'F','Jayashree','Reddy','JayashreeReddy','E037',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1985-1-10 00:00:00', null, 'F','Deepa','Mulimani','DeepaMulimani','E002',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1965-05-10 00:00:00', null, 'M','Suresh','N','SureshN','E003',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1969-10-06 00:00:00', null, 'F','Malathi','R','MalathiR','E004',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1974-11-07 00:00:00', null, 'M','Syed','Muzakkir','SyedMuzakkir','E009',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1973-10-11 00:00:00', null, 'F','Seema','Nayak','SeemaNayak','E010',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1969-10-11 00:00:00', null, 'F','Manasa','Niranjan','ManasaNiranjan','E013',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1977-10-01 00:00:00', null, 'M','Makaraju','Sakethram','MakarajuSakethram','E014',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Venkataramana','Baratam','VenkataramanaBaratam','E015',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Mahesh','Maiya','MaheshMaiya','E039',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Chandrashekar','N.A','ChandrashekarN.A','E040',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Gireesh','Mulage','GireeshMulage','E042',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'F','Jitha','Jothinadh','JithaJothinadh','E043',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Vijay','Ingole','VijayIngole','E044',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'F','Evlyn','George','EvlynGeorge','E045',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Pramod','R','PramodR','E046',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Vasanth','','Vasanth','E047',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Julian','Prabhakar','JulianPrabhakar','E048',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'F','Gauthami','G','GauthamiG','E049',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Chetan','','Chetan','E050',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Vikas','','Vikas','E051',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Akash','','Akash','E052',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'F','Shamili','Gupta','ShamiliGupta','E053',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Mussavir','Hussain','MussavirHussain','E054',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Phanindra','Choda','PhanindraChoda','E055',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'F','Neetu','Kumar','NeetuKumar','E056',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Tilak','Kumar','TilakKumar','E057',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Prabhu','','Prabhu','E058',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Suhail','Mohammed','SuhailMohammed','E059',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Venkatesh','SNV','VenkateshSNV','E060',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Sumit','Jha','SumitJha','E062',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Ravi','Shankar','RaviShankar','E063',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Dharmendra','Singh','DharmendraSingh','E064',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'F','Gayathri','PJ','GayathriPJ','E065',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Manas','Mohapatra','ManasMohapatra','E066',current_date,current_date);


insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,emp_middlename,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1964-10-03 00:00:00', null, 'M','Girish','BV','Kumar','GirishKumarBV','E017',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,emp_middlename,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1983-03-03 00:00:00', 'Tamil', 'M','Pradeep','CM','Kumar','PradeepKumarCM','E021',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,emp_middlename,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1964-10-01 00:00:00', null, 'M','Satyam','Ashish','Kumar','SatyamKumarAshish','E028',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,emp_middlename,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1982-11-11 00:00:00', null, 'M','Sreekanth','Nair','S','SreekanthSNair','E030',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,emp_middlename,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1981-11-11 00:00:00', null, 'M','Subhash','Bose','Chandra','SubhashChandraBose','E001',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,emp_middlename,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1979-01-06 00:00:00', null, 'M','Nayeemalla','Pathan','T','NayeemallaTPathan','E005',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,emp_middlename,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1978-05-06 00:00:00', null,'F','Roopa','Bagi','H','RoopaHBagi','E011',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,emp_middlename,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1972-10-09 00:00:00', null,'F','Parvati','Hiremath','S','ParvatiSHiremath','E012',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,emp_middlename,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Surya ','Bera','Narayan','Surya NarayanBera','E041',current_date,current_date);
insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,emp_middlename,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1967-08-03 00:00:00', null, 'M','Ramandeep ','Bakshi','Singh','Ramandeep SinghBakshi','E061',current_date,current_date);

insert into eg_employee (id, date_of_birth,mother_tonuge,gender,emp_firstname,emp_lastname,name,code,lastmodified_date,createdtime) values(nextval('EGPIMS_PERSONAL_INFO_SEQ'), '1964-10-01 00:00:00', null, 'M','Narasappa','Shelar','NarasappaShelar','E006',current_date,current_date);



update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Narasappa'))  where code='E006';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Krishna'))  where code='E007';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Elzan'))  where code='E008';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Girish'))  where code='E017';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Iffath'))  where code='E018';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Nirbhay'))  where code='E019';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('prk'))  where code='E020';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Pradeep'))  where code='E021';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Rajashree'))  where code='E022';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Ramakrishna'))  where code='E023';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Manikanta'))  where code='E024';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Rishi'))  where code='E025';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Sathish'))  where code='E026';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Satish'))  where code='E027';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Satyam'))  where code='E028';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Shahid'))  where code='E029';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Sreekanth'))  where code='E030';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Sathyandra'))  where code='E031';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Arun'))  where code='E032';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Mohanraj'))  where code='E033';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('sankar'))  where code='E034';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Vaibhav'))  where code='E035';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Rajkumar'))  where code='E036';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Jayashree'))  where code='E037';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Subhash'))  where code='E001';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Nayeemalla'))  where code='E005';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Deepa'))  where code='E002';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Suresh'))  where code='E003';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Malathi'))  where code='E004';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Syed'))  where code='E009';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Seema'))  where code='E010';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Roopa'))  where code='E011';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Parvati'))  where code='E012';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Manasa'))  where code='E013';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Makaraju'))  where code='E014';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Venkataramana'))  where code='E015';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Mahesh'))  where code='E039';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Chandrashekar'))  where code='E040';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Surya '))  where code='E041';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Gireesh'))  where code='E042';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Jitha'))  where code='E043';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Vijay'))  where code='E044';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Evlyn'))  where code='E045';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Pramod'))  where code='E046';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Vasanth'))  where code='E047';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Julian'))  where code='E048';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Gauthami'))  where code='E049';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Chetan'))  where code='E050';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Vikas'))  where code='E051';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Akash'))  where code='E052';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Shamili'))  where code='E053';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Mussavir'))  where code='E054';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Phanindra'))  where code='E055';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Neetu'))  where code='E056';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Tilak'))  where code='E057';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Prabhu'))  where code='E058';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Suhail'))  where code='E059';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Venkatesh'))  where code='E060';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Ramandeep '))  where code='E061';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Sumit'))  where code='E062';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Ravi'))  where code='E063';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Dharmendra'))  where code='E064';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Gayathri'))  where code='E065';
update eg_employee set id_user=(select id_user from eg_user where user_name=lower('Manas'))  where code='E066';




