INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Accounts', 'A', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Buildings', 'B', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Roads', 'BR', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Storm Water Drains', 'D', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Education', 'E', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Zone 1', 'FA', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Zone 2', 'FB', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Zone 3', 'FC', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Zone 4', 'FD', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Zone 5', 'FE', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Zone 6', 'FF', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Zone 7', 'FG', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Zone 8', 'FH', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Zone 9', 'FJ', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Zone 10', 'FK', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'General', 'G', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Family Welfare', 'HD', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Health', 'H', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Bridges', 'J', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Electrical', 'L', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Mechanical', 'M', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Parks and Playfields', 'P', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Solid Waste Management', 'Q', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Revenue', 'R', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Town Planning', 'TP', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Land and Estate', 'V', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Works', 'W', '2015-02-10');
INSERT INTO eg_department (id_dept, dept_name, dept_code, updatetime) VALUES (nextval('seq_eg_dept'), 'Legal Cell', 'Y', '2015-02-10');
