INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( 
nextval('SEQ_EG_APPCONFIG'), 'SENDEMAILFORESCALATION', 'Send email for for escalation', 'PGR'); 

INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='SENDEMAILFORESCALATION'),CURRENT_DATE, 'YES');

--rollback DELETE FROM eg_appconfig_values WHERE key_id in(SELECT id FROM eg_appconfig WHERE key_name='SENDEMAILFORESCALATION');
--rollback DELETE FROM eg_appconfig WHERE key_name='SENDEMAILFORESCALATION';


