DROP TABLE eggr_communication CASCADE;
DROP TABLE eggr_comp_receiving_modes CASCADE;
DROP TABLE eggr_complaintdetails CASCADE;
DROP TABLE eggr_complaintgroup CASCADE;
DROP TABLE eggr_complaintreceivingcenter CASCADE;
DROP TABLE eggr_complaintstatus CASCADE;
DROP TABLE eggr_complainttypes CASCADE;
DROP TABLE eggr_forward_tracker CASCADE;
DROP TABLE eggr_imagevideo_upload CASCADE;
DROP TABLE eggr_priority CASCADE;
DROP TABLE eggr_qams_store CASCADE;
DROP TABLE eggr_redressaldetails CASCADE;
DROP TABLE eggr_region_dept_mapping CASCADE;
DROP TABLE eggr_roles_department CASCADE;
DROP TABLE eggr_status_roles CASCADE;
DROP TABLE eggr_status_tracker CASCADE;

DROP SEQUENCE seq_eggr_statustracker;
DROP SEQUENCE seq_eggr_router;
DROP SEQUENCE seq_eggr_reminder;
DROP SEQUENCE seq_eggr_region_dept;
DROP SEQUENCE seq_eggr_redressaldetail;
DROP SEQUENCE seq_eggr_qams_store;
DROP SEQUENCE seq_eggr_imagevideo_upload;
DROP SEQUENCE seq_eggr_forwardtracker;
DROP SEQUENCE seq_eggr_escalation;
DROP SEQUENCE seq_eggr_complainttypes;
DROP SEQUENCE seq_eggr_complaintreceivingcen;
DROP SEQUENCE seq_eggr_complaintgroup;
DROP SEQUENCE seq_eggr_complaintdetail;
DROP SEQUENCE seq_eggr_communication;
