create sequence seq_eg_boundary_type;

ALTER TABLE EG_BOUNDARY_TYPE RENAME COLUMN ID_BNDRY_TYPE TO ID;
ALTER TABLE EG_BOUNDARY_TYPE RENAME COLUMN ID_HEIRARCHY_TYPE TO hierarchytype_id;
ALTER TABLE EG_BOUNDARY_TYPE RENAME COLUMN parent TO parent_id;

ALTER TABLE EG_BOUNDARY_TYPE DROP column updatedtime;

ALTER TABLE EG_BOUNDARY_TYPE ADD COLUMN createddate TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE EG_BOUNDARY_TYPE ADD COLUMN lastmodifieddate TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE EG_BOUNDARY_TYPE ADD COLUMN createdby BIGINT;
ALTER TABLE EG_BOUNDARY_TYPE ADD COLUMN lastmodifiedby BIGINT;
ALTER TABLE EG_BOUNDARY_TYPE ADD COLUMN version bigint;



-- ROLLBACK DROP SEQUENCE seq_eg_boundary_type;

-- ROLLBACK ALTER TABLE EG_BOUNDARY_TYPE RENAME column id to ID_BNDRY_TYPE;
-- ROLLBACK ALTER TABLE EG_BOUNDARY_TYPE RENAME column hierarchytype_id to ID_HEIRARCHY_TYPE;
-- ROLLBACK ALTER TABLE EG_BOUNDARY_TYPE RENAME column parent_id to parent;

-- ROLLBACK ALTER TABLE EG_BOUNDARY_TYPE DROP COLUMN createddate;
-- ROLLBACK ALTER TABLE EG_BOUNDARY_TYPE DROP COLUMN lastmodifieddate;
-- ROLLBACK ALTER TABLE EG_BOUNDARY_TYPE DROP COLUMN createdby;
-- ROLLBACK ALTER TABLE EG_BOUNDARY_TYPE DROP COLUMN lastmodifiedby;
-- ROLLBACK ALTER TABLE EG_BOUNDARY_TYPE DROP COLUMN version;
