DELETE FROM EG_ROLEACTION_MAP WHERE ACTIONID = (SELECT ID FROM EG_ACTION WHERE DISPLAY_NAME = 'Create Boundary');
DELETE FROM EG_ACTION WHERE DISPLAY_NAME = 'Create Boundary';

DELETE FROM EG_ROLEACTION_MAP WHERE ACTIONID = (SELECT ID FROM EG_ACTION WHERE DISPLAY_NAME = 'Move Boundary');
DELETE FROM EG_ACTION WHERE DISPLAY_NAME = 'Move Boundary';


INSERT INTO EG_ACTION(ID, NAME, ENTITYID, TASKID, UPDATEDTIME, URL, QUERYPARAMS, URLORDERID, MODULE_ID, ORDER_NUMBER, DISPLAY_NAME, IS_ENABLED, ACTION_HELP_URL, CONTEXT_ROOT)
Values (nextval('SEQ_EG_ACTION'), 'SearchBoundaryForm', NULL, NULL, now(), '/controller/search-boundary', NULL, NULL, (SELECT ID_MODULE FROM EG_MODULE WHERE MODULE_DESC = 'Jurisdiction'),
0, 'Search Boundary', 1, NULL, 'egi');

INSERT INTO EG_ACTION(ID, NAME, ENTITYID, TASKID, UPDATEDTIME, URL, QUERYPARAMS, URLORDERID, MODULE_ID, ORDER_NUMBER, DISPLAY_NAME, IS_ENABLED, ACTION_HELP_URL, CONTEXT_ROOT)
Values (nextval('SEQ_EG_ACTION'), 'ViewBoundaryForm', NULL, NULL, now(), '/controller/list-boundaries', NULL, NULL, (SELECT ID_MODULE FROM EG_MODULE WHERE MODULE_DESC = 'Jurisdiction'),
0, 'View Boundaries', 0, NULL, 'egi');

INSERT INTO EG_ACTION(ID, NAME, ENTITYID, TASKID, UPDATEDTIME, URL, QUERYPARAMS, URLORDERID, MODULE_ID, ORDER_NUMBER, DISPLAY_NAME, IS_ENABLED, ACTION_HELP_URL, CONTEXT_ROOT)
Values (nextval('SEQ_EG_ACTION'), 'CreateBoundary', NULL, NULL, now(), '/controller/boundary/create', NULL, NULL, (SELECT ID_MODULE FROM EG_MODULE WHERE MODULE_DESC = 'Jurisdiction'),
0, 'Create Boundary', 0, NULL, 'egi');

INSERT INTO EG_ROLEACTION_MAP (ROLEID, ACTIONID) 
values ((select id from eg_role where UPPER(name) = 'SUPER USER'),(select id FROM eg_action  WHERE name = 'SearchBoundaryForm'));

INSERT INTO EG_ROLEACTION_MAP (ROLEID, ACTIONID) 
values ((select id from eg_role where UPPER(name) = 'SUPER USER') ,(select id FROM eg_action  WHERE name = 'ViewBoundaryForm'));

INSERT INTO EG_ROLEACTION_MAP (ROLEID, ACTIONID) 
values ((select id from eg_role where UPPER(name) = 'SUPER USER') ,(select id FROM eg_action  WHERE name = 'CreateBoundary'));
