ALTER TABLE egcl_servicecategory ADD CONSTRAINT pk_egcl_servicecategory PRIMARY KEY (id);
ALTER TABLE egcl_servicedetails ADD CONSTRAINT pk_egcl_servicedetails PRIMARY KEY (id);
ALTER TABLE egcl_servicedetails ADD CONSTRAINT fk_serdtls_fund FOREIGN KEY (fund) REFERENCES FUND (id);
ALTER TABLE egcl_servicedetails ADD CONSTRAINT fk_serdtls_fsource FOREIGN KEY (fundsource) REFERENCES FUNDSOURCE (id);
ALTER TABLE egcl_servicedetails ADD CONSTRAINT fk_serdtls_functionary FOREIGN KEY (functionary) REFERENCES functionary (id);
ALTER TABLE egcl_servicedetails ADD CONSTRAINT fk_serdtls_scheme FOREIGN KEY (scheme) REFERENCES scheme (id);
ALTER TABLE egcl_servicedetails ADD CONSTRAINT fk_serdtls_servicecat FOREIGN KEY (servicecategory) REFERENCES egcl_servicecategory (id);
ALTER TABLE egcl_servicedetails ADD CONSTRAINT fk_serdtls_subscheme FOREIGN KEY (subscheme) REFERENCES sub_scheme (id);
ALTER TABLE egcl_service_dept_mapping ADD CONSTRAINT egcl_ser_dept_map_srvcdtls_fk FOREIGN KEY (servicedetails) REFERENCES egcl_servicedetails (id);
ALTER TABLE egcl_service_dept_mapping ADD CONSTRAINT egcl_service_deptmapping_dept_fk FOREIGN KEY (department) REFERENCES eg_department (id);
ALTER TABLE egcl_service_accountdetails ADD CONSTRAINT pk_egcl_service_accountdetails PRIMARY KEY (id);
ALTER TABLE egcl_service_accountdetails ADD CONSTRAINT fk_egcl_srvcacc_srvdtils FOREIGN KEY (servicedetails) REFERENCES egcl_servicedetails (id);
ALTER TABLE egcl_service_accountdetails ADD CONSTRAINT fk_egcl_srvcaccdtls_coa FOREIGN KEY (chartofaccount) REFERENCES chartofaccounts (id);
ALTER TABLE egcl_service_accountdetails ADD CONSTRAINT fk_serviceaccdtls_function FOREIGN KEY (functionid) REFERENCES function (id);
ALTER TABLE egcl_service_subledgerinfo ADD CONSTRAINT pk_egcl_service_subledgerinfo PRIMARY KEY (id);
ALTER TABLE egcl_service_subledgerinfo ADD CONSTRAINT fk_egcl_subdtls_accdtltyp FOREIGN KEY (accountdetailtype) REFERENCES accountdetailtype (id);
ALTER TABLE egcl_service_subledgerinfo ADD CONSTRAINT fk_egcl_subledgerdetails_srvcacc FOREIGN KEY (serviceaccountdetail) REFERENCES egcl_service_accountdetails (id);
ALTER TABLE egcl_collectionheader ADD CONSTRAINT pk_egcl_collectionheader PRIMARY KEY (id);
ALTER TABLE egcl_collectionheader ADD CONSTRAINT fk_collhead_location FOREIGN KEY (location) REFERENCES eg_location (id);
ALTER TABLE egcl_collectionheader ADD CONSTRAINT fk_collhead_status FOREIGN KEY (status) REFERENCES egw_status (id);
ALTER TABLE egcl_collectionheader ADD CONSTRAINT fk_collhead_chid FOREIGN KEY (reference_ch_id) REFERENCES egcl_collectionheader (id);
ALTER TABLE egcl_collectionheader ADD CONSTRAINT fk_collhead_service FOREIGN KEY (servicedetails) REFERENCES egcl_servicedetails (id);
ALTER TABLE egcl_collectionheader ADD CONSTRAINT fk_collhead_state FOREIGN KEY (STATE_ID) REFERENCES eg_wf_states (id);
ALTER TABLE egcl_collectionheader ADD CONSTRAINT unq_ch_receiptnumber UNIQUE (receiptnumber);
CREATE INDEX indx_collhd_locid ON egcl_collectionheader(location);
CREATE INDEX indx_collhd_refchid ON egcl_collectionheader(reference_ch_id);
CREATE INDEX indx_collhd_state ON egcl_collectionheader(STATE_ID);
ALTER TABLE egcl_collectionmis ADD CONSTRAINT pk_egcl_collectionmis PRIMARY KEY (id);
ALTER TABLE egcl_collectionmis ADD CONSTRAINT fk_collmis_collhead FOREIGN KEY (collectionheader) REFERENCES egcl_collectionheader (id);
ALTER TABLE egcl_collectionmis ADD CONSTRAINT fk_collmis_boundary FOREIGN KEY (boundary) REFERENCES eg_boundary (id);
ALTER TABLE egcl_collectionmis ADD CONSTRAINT fk_collmis_department FOREIGN KEY (department) REFERENCES eg_department (id);
ALTER TABLE egcl_collectionmis ADD CONSTRAINT fk_collmis_funtionary FOREIGN KEY (functionary) REFERENCES functionary (id);
ALTER TABLE egcl_collectionmis ADD CONSTRAINT fk_collmis_fund FOREIGN KEY (fund) REFERENCES fund (id);
ALTER TABLE egcl_collectionmis ADD CONSTRAINT fk_collmis_fundsource FOREIGN KEY (fundsource) REFERENCES fundsource (id);
ALTER TABLE egcl_collectionmis ADD CONSTRAINT fk_collmis_scheme FOREIGN KEY (scheme) REFERENCES scheme (id);
ALTER TABLE egcl_collectionmis ADD CONSTRAINT fk_collmis_subscheme FOREIGN KEY (subscheme) REFERENCES sub_scheme (id);
ALTER TABLE egcl_collectionmis ADD CONSTRAINT fk_collmis_bank FOREIGN KEY (depositedinbank) REFERENCES bank (id);
CREATE INDEX indx_collmis_depositedinbank ON egcl_collectionmis(depositedinbank);
CREATE INDEX indx_collmis_deptid ON egcl_collectionmis(department);
ALTER TABLE egcl_collectiondetails ADD CONSTRAINT pk_egcl_collectiondetails PRIMARY KEY (id);
ALTER TABLE egcl_collectiondetails ADD CONSTRAINT fk_colldtls_collhead FOREIGN KEY (collectionheader) REFERENCES egcl_collectionheader (id);
ALTER TABLE egcl_collectiondetails ADD CONSTRAINT fk_colldtls_coa FOREIGN KEY (chartofaccount) REFERENCES chartofaccounts (id);
ALTER TABLE egcl_collectiondetails ADD CONSTRAINT fk_colldtls_function FOREIGN KEY (functionid) REFERENCES function (id);
ALTER TABLE egcl_collectiondetails ADD CONSTRAINT fk_colldtls_finyear FOREIGN KEY (financialyear) REFERENCES financialyear (id);
CREATE INDEX indx_colldet_acchead ON egcl_collectiondetails(chartofaccount);
ALTER TABLE egcl_accountpayeedetails ADD CONSTRAINT pk_egcl_accountpayeedetails PRIMARY KEY (id);
ALTER TABLE egcl_accountpayeedetails ADD CONSTRAINT fk_apd_accdtlkey FOREIGN KEY (accountdetailskey) REFERENCES accountdetailkey (id);
ALTER TABLE egcl_accountpayeedetails ADD CONSTRAINT fk_apd_accdtltype FOREIGN KEY (accountdetailstype) REFERENCES accountdetailtype (id);
ALTER TABLE egcl_accountpayeedetails ADD CONSTRAINT fk_apd_colldtl FOREIGN KEY (collectiondetails) REFERENCES egcl_collectiondetails (id);
ALTER TABLE egcl_challanheader ADD CONSTRAINT pk_egcl_challanheader PRIMARY KEY (id);
ALTER TABLE egcl_challanheader ADD CONSTRAINT fk_chlnhead_collhead FOREIGN KEY (collectionheader) REFERENCES egcl_collectionheader (id);
ALTER TABLE egcl_challanheader ADD CONSTRAINT fk_chlnhead_status FOREIGN KEY (status) REFERENCES egw_status (id);
ALTER TABLE egcl_challanheader ADD CONSTRAINT fk_chlnhead_voucher FOREIGN KEY (voucherheader) REFERENCES voucherheader (id);
ALTER TABLE egcl_challanheader ADD CONSTRAINT fk_chlnhead_state FOREIGN KEY (STATE_ID) REFERENCES eg_wf_states (id);
ALTER TABLE egcl_challanheader ADD CONSTRAINT fk_chlnhead_service FOREIGN KEY (servicedetails) REFERENCES egcl_servicedetails (id);
ALTER TABLE egcl_challanheader ADD CONSTRAINT unq_challanheader_challannumber UNIQUE (challannumber);
CREATE INDEX indx_challan_collheaderid ON egcl_challanheader(collectionheader);
CREATE INDEX indx_challan_state ON egcl_challanheader(STATE_ID);
CREATE INDEX indx_challan_status ON egcl_challanheader(status);
ALTER TABLE egcl_collectioninstrument ADD CONSTRAINT fk_collinst_collhead FOREIGN KEY (collectionheader) REFERENCES egcl_collectionheader (id);
--ALTER TABLE egcl_collectioninstrument ADD CONSTRAINT fk_collinst_instrument FOREIGN KEY (instrumentheader) REFERENCES egf_instrumentheader (id);
ALTER TABLE egcl_collectionvoucher ADD CONSTRAINT pk_egcl_collectionvoucher PRIMARY KEY (id);
ALTER TABLE egcl_collectionvoucher ADD CONSTRAINT fk_collvouch_collhead FOREIGN KEY (collectionheader) REFERENCES egcl_collectionheader (id);
ALTER TABLE egcl_collectionvoucher ADD CONSTRAINT fk_collvouch_voucher FOREIGN KEY (voucherheader) REFERENCES voucherheader (id);
ALTER TABLE egcl_onlinepayments ADD CONSTRAINT pk_egcl_onlinepayments PRIMARY KEY (id);
ALTER TABLE egcl_onlinepayments ADD CONSTRAINT fk_onpay_collhead FOREIGN KEY (collectionheader) REFERENCES egcl_collectionheader (id);
ALTER TABLE egcl_onlinepayments ADD CONSTRAINT fk_onpay_service FOREIGN KEY (servicedetails) REFERENCES egcl_servicedetails (id);
ALTER TABLE egcl_onlinepayments ADD CONSTRAINT fk_onpay_status FOREIGN KEY (status) REFERENCES egw_status (id);
CREATE INDEX indx_online_service ON egcl_onlinepayments(servicedetails);
CREATE INDEX indx_online_status ON egcl_onlinepayments(status);
CREATE INDEX indx_op_collheaderid ON egcl_onlinepayments(collectionheader);
ALTER TABLE egcl_bank_remittance ADD CONSTRAINT pk_egcl_bank_remittance PRIMARY KEY (id);
ALTER TABLE egcl_bank_remittance ADD CONSTRAINT fk_bankrmtnc_bank FOREIGN KEY (depositedinbank) REFERENCES bank (id);
ALTER TABLE egcl_bank_remittance ADD CONSTRAINT fk_bankrmtnc_bankaccount FOREIGN KEY (bankaccounttoremit) REFERENCES bankaccount (id);
ALTER TABLE egcl_bank_remittance ADD CONSTRAINT fk_bankrmtnc_service FOREIGN KEY (servicedetails) REFERENCES egcl_servicedetails (id);
ALTER TABLE egcl_bankaccountservicemapping ADD CONSTRAINT pk_egcl_bankaccountservicemapping PRIMARY KEY (id);
ALTER TABLE egcl_bankaccountservicemapping ADD CONSTRAINT fk_basm_bankaccount FOREIGN KEY (bankaccount) REFERENCES bankaccount (id);
ALTER TABLE egcl_bankaccountservicemapping ADD CONSTRAINT fk_basm_department FOREIGN KEY (department) REFERENCES eg_department (id);
ALTER TABLE egcl_bankaccountservicemapping ADD CONSTRAINT fk_basm_service FOREIGN KEY (servicedetails) REFERENCES egcl_servicedetails (id);
--ALTER TABLE egcl_bankaccountservicemapping ADD CONSTRAINT fk_basm_ecstype FOREIGN KEY (ecstype) REFERENCES egf_ecstype (id);


