Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Surrendered',to_date('23-01-10','DD-MM-RR'),'Surrendered',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','New',to_date('22-11-09','DD-MM-RR'),'New',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Deposited',to_date('22-11-09','DD-MM-RR'),'Deposited',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Reconciled',to_date('22-11-09','DD-MM-RR'),'Reconciled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Cancelled',to_date('22-11-09','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Dishonored',to_date('22-11-09','DD-MM-RR'),'Dishonored',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Planning',to_date('01-06-07','DD-MM-RR'),'Planning',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Approved',to_date('01-06-07','DD-MM-RR'),'Approved',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Closed',to_date('01-06-07','DD-MM-RR'),'Closed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Created',to_date('01-06-07','DD-MM-RR'),'Created',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Verified',to_date('01-06-07','DD-MM-RR'),'Verified',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Confirmed',to_date('01-06-07','DD-MM-RR'),'Confirmed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Checked',to_date('01-06-07','DD-MM-RR'),'Checked',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Mark For Checking',to_date('01-06-07','DD-MM-RR'),'Mark For Checking',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BUDGET','Concurrence',to_date('01-06-07','DD-MM-RR'),'Concurrence',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Created',to_date('26-05-10','DD-MM-RR'),'Created',1);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Approved',to_date('26-05-10','DD-MM-RR'),'Approved',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Cancelled',to_date('26-05-10','DD-MM-RR'),'Cancelled',3);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','APPROVED',to_date('28-03-10','DD-MM-RR'),'APPROVED',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Created By DO',to_date('17-06-13','DD-MM-RR'),'Created By DO',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'ARF','Created By SM',to_date('17-06-13','DD-MM-RR'),'Created By SM',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','CREATED',to_date('28-03-10','DD-MM-RR'),'CREATED',1);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','Approved',to_date('28-03-10','DD-MM-RR'),'Approved',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','Voucher Created',to_date('28-03-10','DD-MM-RR'),'Voucher Created',3);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'EXPENSEBILL','Cancelled',to_date('28-03-10','DD-MM-RR'),'Cancelled',2);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','Surrender_For_Reassign',to_date('16-09-10','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BudgetReAppropriation','New',to_date('25-01-11','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BudgetReAppropriation','Approved',to_date('25-01-11','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'BudgetReAppropriation','Cancelled',to_date('25-01-11','DD-MM-RR'),null,null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','CREATED',to_date('01-06-07','DD-MM-RR'),'CREATED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','VERIFIED',to_date('01-06-07','DD-MM-RR'),'VERIFIED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','ACCOUNTS APPROVAL',to_date('01-06-07','DD-MM-RR'),'ACCOUNTS APPROVAL',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','Voucher Created',to_date('01-06-07','DD-MM-RR'),'Voucher Created',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','PAYMENT APPROVED',to_date('27-06-07','DD-MM-RR'),'PAYMENT APPROVED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','PAYMENT CONFIRMED',to_date('27-06-07','DD-MM-RR'),'PAYMENT CONFIRMED',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Created',to_date('10-07-07','DD-MM-RR'),'Created',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Approved',to_date('10-07-07','DD-MM-RR'),'Approved',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Passed',to_date('10-07-07','DD-MM-RR'),'Passed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Paid',to_date('10-07-07','DD-MM-RR'),'Paid',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Cancelled',to_date('01-02-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Pending',to_date('01-02-08','DD-MM-RR'),'Pending',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Passed',to_date('01-02-08','DD-MM-RR'),'Passed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Cancelled',to_date('01-02-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'WORKSBILL','Paid',to_date('01-02-08','DD-MM-RR'),'Paid',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Pending',to_date('01-02-08','DD-MM-RR'),'Pending',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Passed',to_date('01-02-08','DD-MM-RR'),'Passed',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Cancelled',to_date('01-02-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'PURCHBILL','Paid',to_date('01-02-08','DD-MM-RR'),'Paid',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'CBILL','Cancelled',to_date('17-03-08','DD-MM-RR'),'Cancelled',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'SALBILL','Rejected',to_date('22-09-13','DD-MM-RR'),'Rejected',null);
Insert into egw_status (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('seq_egw_status'),'Instrument','dishonour cheque in workflow',to_date('02-01-14','DD-MM-RR'),'InWorkflow',null);

