Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'exclude_status_forbudget_actual','exclude voucher status for budget','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetaryCheck_budgettype_cashbased','budgetaryCheck budgettype','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_final_approval_status','Final Approval status for budget','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'pjv_saveasworkingcopy_enabled','pjv_saveasworkingcopy_enabled','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Bill_Number_Geneartion_Auto','bill number genration auto or manual ','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'cancelledstatus','Cancelled status for voucher','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'contingencyBillPurposeIds','Contingent Bill PurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'VOUCHER_STATUS_TO_CHECK_BANK_BALANCE','VOUCHER_STATUS_TO_CHECK_BANK_BALANCE','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'salaryBillPurposeIds','Salary Bill PurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'salaryBillDefaultPurposeId','Salary Bill Default PurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-Revenue','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-110','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-120','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-130','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-140','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-150','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-160','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-170','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-171','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-180','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-Expense','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-210','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-220','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-230','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-240','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-250','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-260','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-270','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-271','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-280','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-290','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-Revenue','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-Expense','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-110','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-120','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-130','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-140','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-150','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-160','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-170','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-171','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-180','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-210','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-220','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-230','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-240','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-250','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-260','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-270','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-280','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'departmentWiseBudgetReport-290','Department Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'bank_balance_mandatory','bank_balance_mandatory','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PurchaseBillApprovalStatus','Purchase bill Status for approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'WorksBillApprovalStatus','Works bill Status for approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'ExpenseBillApprovalStatus','Contingency bill Status for approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'SalaryBillApprovalStatus','Salary bill Status for approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Balance Check Based on Fund Flow Report','Check Balance  Based on Fund Flow Report Or Not','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'add_less_codes_for_ie_report','add and less codes for ie report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'planning_budget_multiplication_factor','planning budget multiplication factor','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'CONSIDER_RE_REAPPROPRIATION_AS_SEPARATE','Whether or not to consider re_reappropriation as seperate in budget reports','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_major_capital_exp_fie_report','coa_major_capital_exp_fie_report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'pensionBillPurposeIds','Pension Bill PurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PensionBillApprovalStatus','Pension bill Status for approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_SMlevel_approver_designation','budget_SMlevel_approver_designation','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'USE BILLDATE IN CREATE VOUCHER FROM BILL','USE BILLDATE IN CREATE VOUCHER FROM BILL','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'WORKS VOUCHERS RESTRICTION DATE FROM JV SCREEN','WORKS VOUCHERS RESTRICTION DATE FROM JV SCREEN','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'GJV_FOR_RCPT_CHQ_DISHON','Generate Journal Voucher on dishonoring receipt cheque','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'loangrant.default.fundid','if fund id is present it is defaulted else selection made mandatory','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'BANKBALANCE_CHECK_DATE','Fund Flow BANKBALANCE_CHECK_DATE','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'functionWiseBudgetReport-272','Function Wise Budget Report','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'CONTRACTOR_ADVANCE_CODE','Contractor Advance Payable','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'contingencyBillDefaultPurposeId',' default Purpose ids for Contingency','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Communication Expenses','ContingentBill-Telephone-CheckList','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Electricity Charges','ContingentBill-Electricity-CheckList','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Others','ContingentBill-Others-CheckList','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PAYMENT_WF_STATUS_FOR_BANK_BALANCE_CHECK','PAYMENT_WF_STATUS_FOR_BANK_BALANCE_CHECK','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DEFAULT_SEARCH_MISATTRRIBUTES','default search mis attributes','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_toplevel_approver_designation','budget_toplevel_approver_designation','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budget_secondlevel_approver_designation','Functionary contains colon','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Reason For Cheque Surrendaring',' Reasons for cheque surrendering','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'PREAPPROVEDVOUCHERSTATUS','voucher status before approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'APPROVEDVOUCHERSTATUS','next state of approval','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DEFAULTVOUCHERCREATIONSTATUS','DEFAULTVOUCHERCREATIONSTATUS','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_detailcode_length','detailcode length length','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetgroup_range_minor_or_detailed','budgetgroup_range_minor_or_detailed','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_minorcode_length','minorcode length','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_majorcode_length','majorcode length','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetaryCheck_groupby_values','budgetarycheck group by values','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'coa_subminorcode_length','subminorcode length','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'purchaseBillPurposeIds','purchaseBillPurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'worksBillPurposeIds','worksBillPurposeIds','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'parent_for_detailcode','parent length for detailed code','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Cheque_no_generation_auto','Cheque_nogeneration','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'cheque.assignment.infavourof','cheque.assignment.infavourof','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'boundaryforaccounts','This is the boundary at which books of accounts are maintained','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DEFAULTTXNMISATTRRIBUTES','default transaction mis attributes','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'JournalVoucher_ConfirmonCreate','journal voucher create isconfirmed value','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'bs_report_half_yearly','balance sheet report half yearly date (dd/mm)','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'REPORT_SEARCH_MISATTRRIBUTES','default search mis attributes','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetDetail_mandatory_fields','Budget Detail mandatroy fields','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'budgetCheckRequired','budgetCheckRequired','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'EB Voucher Property-Fund','Fund Code Used For EB Bill Voucher Creation','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'EB Voucher Property-Function','Function Code Used For EB Bill Voucher Creation','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'EB Voucher Property-Department','Department Code Used For EB Bill Voucher Creation','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'EB Voucher Property-Bank','Bank Code Used For EB Bill Voucher Creation','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'EB Voucher Property-BankBranch','BankBranch Number Used For EB Bill Voucher Creation','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'EB Voucher Property-BankAccount','BankAccount Number Used For EB Bill Voucher Creation','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'RTGSNO_GENERATION_AUTO','RTGSNO_GENERATION_AUTO','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'DATE_RESTRICTION_FOR_CJV_PAYMENT_MODE_AS_RTGS','Whether RTGS should be the only mode of payment for CJVs for the bill date','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Remove Entrys With Zero Amount','Value to deside Remove Entrys With Zero Amount in Reports','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'ifRestrictedToOneFunctionCenter','ifRestrictedToOneFunctionCenter','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'VOUCHERDATE_FROM_UI','GET VOUCHERDATE FROM UI','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'CJV_PAYMENT_MODE_AS_RTGS','Whether RTGS should be the only mode of payment for CJVs','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'TNEB Bill Pay to','Name of the bank to which bill will be paid','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'AutoRemittance_Start_Date','Starting date of date to be considered for  RTGS Payment','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'AuoRemittance_Account_Number_For_Receipts','Bank Account number Receipt remittance Payment','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'AuoRemittance_Account_Number_For_GJV','Bank Account number GJV remittance Payment','EGF');
Insert into eg_appconfig (ID,KEY_NAME,DESCRIPTION,MODULE) values (nextval('seq_eg_appconfig'),'Remove Entries With Zero Amount in Report','Value to deside Remove Entries With Zero Amount in Reports','EGF');

