INSERT INTO eg_appconfig_values(id, key_id, effective_from, value) VALUES (nextval('seq_eg_appconfig_values'), (select id from eg_appconfig where key_name='IS_ASSET_CATEGORYCODE_AUTOGENERATED'), now(), 'yes');
INSERT INTO eg_appconfig_values(id, key_id, effective_from, value) VALUES (nextval('seq_eg_appconfig_values'), (select id from eg_appconfig where key_name='ASSET_ACCOUNT_CODE_PURPOSEID'), now(), (select id from egf_accountcode_purpose where name='Fixed Assets'));
INSERT INTO eg_appconfig_values(id, key_id, effective_from, value) VALUES (nextval('seq_eg_appconfig_values'),  (select id from eg_appconfig where key_name='REVALUATION_RESERVE_ACCOUNT_PURPOSEID'), now(), (select id from egf_accountcode_purpose where name='Revaluation Reserve Account'));
INSERT INTO eg_appconfig_values(id, key_id, effective_from, value) VALUES (nextval('seq_eg_appconfig_values'),  (select id from eg_appconfig where key_name='DEPRECIATION_EXPENSE_ACCOUNT_PURPOSEID'), now(), (select id from egf_accountcode_purpose where name='Depreciation Expense Account'));
INSERT INTO eg_appconfig_values(id, key_id, effective_from, value) VALUES (nextval('seq_eg_appconfig_values'),  (select id from eg_appconfig where key_name='ACCUMULATED_DEPRECIATION_PURPOSEID'), now(), (select id from egf_accountcode_purpose where name='Accumulated Depreciation'));


--rollback delete from eg_appconfig_values where key_id in(select id from eg_appconfig where module='Assets');
