INSERT INTO eg_appconfig(id, key_name, description, module) VALUES (nextval('seq_eg_appconfig'), 'IS_ASSET_CATEGORYCODE_AUTOGENERATED', 'Auto/User Generated Asset Category Code ', 'Assets');
INSERT INTO eg_appconfig(id, key_name, description, module) VALUES (nextval('seq_eg_appconfig'), 'ASSET_ACCOUNT_CODE_PURPOSEID', 'Asset Account Code Purpose ID', 'Assets');
INSERT INTO eg_appconfig(id, key_name, description, module) VALUES (nextval('seq_eg_appconfig'), 'REVALUATION_RESERVE_ACCOUNT_PURPOSEID', 'Revaluation Reserve Account Purpose ID', 'Assets');
INSERT INTO eg_appconfig(id, key_name, description, module) VALUES (nextval('seq_eg_appconfig'), 'DEPRECIATION_EXPENSE_ACCOUNT_PURPOSEID', 'Depreciation Expense Account Purpose ID', 'Assets');
INSERT INTO eg_appconfig(id, key_name, description, module) VALUES (nextval('seq_eg_appconfig'), 'ACCUMULATED_DEPRECIATION_PURPOSEID', 'Accumulated Depreciation Purpose ID', 'Assets');

--rollback delete from eg_appconfig where module='Assets';
