--------Changes compatiable to Postgres START -----------------------------------------------------
CREATE TABLE EGPT_ADDRESS 
( 
     ID BIGINT,
     SUBNUMBER CHARACTER VARYING(32), 
     DOORNUMOLD CHARACTER VARYING(64) , 
     EMAILADDRESS CHARACTER VARYING(64) , 
     MOBILENO CHARACTER VARYING(10) , 
     EXTRAFIELD1 CHARACTER VARYING(128) , 
     EXTRAFIELD2 CHARACTER VARYING(128) , 
     EXTRAFIELD3 CHARACTER VARYING(128) , 
     EXTRAFIELD4 CHARACTER VARYING(128) 
);

COMMENT ON TABLE EGPT_ADDRESS IS 'Link table between PTIS and EG_ADDRESS';

COMMENT ON COLUMN EGPT_ADDRESS.SUBNUMBER IS 'Alternate NUMBER';

COMMENT ON COLUMN EGPT_ADDRESS.DOORNUMOLD IS 'Old door NUMBER';

COMMENT ON COLUMN EGPT_ADDRESS.EMAILADDRESS IS 'Email address';

COMMENT ON COLUMN EGPT_ADDRESS.MOBILENO IS 'Mobile NUMBER';

COMMENT ON COLUMN EGPT_ADDRESS.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_ADDRESS.EXTRAFIELD1 IS 'Extra address information';

COMMENT ON COLUMN EGPT_ADDRESS.EXTRAFIELD2 IS 'Extra address information';

COMMENT ON COLUMN EGPT_ADDRESS.EXTRAFIELD3 IS 'Extra address information';

COMMENT ON COLUMN EGPT_ADDRESS.EXTRAFIELD4 IS 'Extra address information';


CREATE TABLE EGPT_BASIC_PROPERTY 
( 
     ID BIGINT NOT NULL , 
     CREATEDBY BIGINT NOT NULL , 
     PROPERTYID CHARACTER VARYING(64) , 
     ISACTIVE BOOLEAN DEFAULT 'Y' NOT NULL , 
     ADDRESSID BIGINT NOT NULL , 
     CREATEDDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL , 
     LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL , 
     ID_PROPERTYID BIGINT NOT NULL , 
     MUNICIAPL_NO_OLD CHARACTER VARYING(64) , 
     ID_ADM_BNDRY BIGINT , 
     EXTRA_FIELD1 CHARACTER VARYING(30) , 
     EXTRA_FIELD2 CHARACTER VARYING(1024) , 
     EXTRA_FIELD3 CHARACTER VARYING(30) , 
     ID_PROP_CREATE_REASON BIGINT , 
     PROP_CREATE_DATE TIMESTAMP WITHOUT TIME ZONE , 
     STATUS BIGINT , 
     MODIFIEDBY BIGINT , 
     GIS_REF_NO CHARACTER VARYING(4000) , 
     ISMIGRATED BOOLEAN DEFAULT 'N' , 
     PARTNO CHARACTER VARYING(12) , 
     ALL_CHANGES_COMPLETED CHARACTER VARYING(30) , 
     IS_BILL_CREATED BOOLEAN DEFAULT 'N' , 
     BILL_CRT_ERROR CHARACTER VARYING(4000) , 
     IS_TAXXML_MIGRATED BOOLEAN DEFAULT 'N' 
);


COMMENT ON TABLE EGPT_BASIC_PROPERTY IS 'This is the main table of PTIS, which contains the top-level property information.';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.CREATEDBY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.PROPERTYID IS 'The property business identifier e.g. 072000008';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.ISACTIVE IS 'Y or N';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.ADDRESSID IS 'FK to EG_ADDRESS';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.CREATEDDATE IS 'Created date';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.LASTMODIFIEDDATE IS 'Modified date';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.ID_PROPERTYID IS 'FK to EGPT_PROPERTYID';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.MUNICIAPL_NO_OLD IS 'Not used';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.ID_ADM_BNDRY IS 'The ward boundary ID. FK to eg_boundary.';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.EXTRA_FIELD1 IS 'Not used';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.EXTRA_FIELD2 IS 'Not used';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.EXTRA_FIELD3 IS 'Not used';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.ID_PROP_CREATE_REASON IS 'FK to EGPT_MUTATION_MASTER, reason for creation';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.PROP_CREATE_DATE IS 'Date of occupation';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.STATUS IS 'FK to EGPT_STATUS';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.MODIFIEDBY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.GIS_REF_NO IS 'GIS parcel ID';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.ISMIGRATED IS 'Y or N';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.PARTNO IS 'Part NUMBER';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.IS_BILL_CREATED IS 'bill creation status for a Tax period and value set to N starting of new Tax period';

COMMENT ON COLUMN EGPT_BASIC_PROPERTY.BILL_CRT_ERROR IS 'error log while creating bill if any';

create sequence SEQ_EGPT_BASIC_PROPERTY;


CREATE TABLE EGPT_CITIZEN_ADDRESS 
( 
     ID_ADDRESS BIGINT NOT NULL, 
     ID_CITIZEN BIGINT NOT NULL 
);

COMMENT ON TABLE EGPT_CITIZEN_ADDRESS IS 'Intermediate table used to map citizen and addresses';

COMMENT ON COLUMN EGPT_CITIZEN_ADDRESS.ID_ADDRESS IS 'FK to EG_ADDRESS';

COMMENT ON COLUMN EGPT_CITIZEN_ADDRESS.ID_CITIZEN IS 'FK to EG_CITIZEN';


CREATE TABLE EGPT_DEMANDCALCULATIONS 
( 
     ID BIGINT NOT NULL , 
     ID_DEMAND BIGINT NOT NULL , 
     PROPERTYTAX DOUBLE PRECISION , 
     RATE_OF_TAX DOUBLE PRECISION , 
     CURRENT_INTEREST DOUBLE PRECISION , 
     ARREAR_INTEREST DOUBLE PRECISION , 
     MODIFIED_DATE TIMESTAMP without time zone NOT NULL , 
     CREATED_DATE TIMESTAMP without time zone , 
     CREATED_BY BIGINT , 
     MODIFIED_BY BIGINT , 
     TAXINFO BYTEA , 
     ALV DOUBLE PRECISION 
);

COMMENT ON TABLE EGPT_DEMANDCALCULATIONS IS 'Tax calculation information';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.ID_DEMAND IS 'FK to EG_DEMAND';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.PROPERTYTAX IS 'Total Property Tax for a installment';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.RATE_OF_TAX IS 'Not used';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.CURRENT_INTEREST IS 'Not used';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.ARREAR_INTEREST IS 'Not used';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.MODIFIED_DATE IS 'Modified date';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.CREATED_DATE IS 'Created date';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.CREATED_BY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.MODIFIED_BY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.TAXINFO IS 'Tax calculation XML';

COMMENT ON COLUMN EGPT_DEMANDCALCULATIONS.ALV IS 'Not Used';

create sequence SEQ_EGPT_DEMANDCALCULATIONS;


CREATE TABLE EGPT_FLOORDEMANDCALC 
( 
     ID BIGINT NOT NULL , 
     ID_FLOORDET BIGINT , 
     ID_DMDCALC BIGINT , 
     CATEGORYAMT DOUBLE PRECISION , 
     OCCUPANCYREBATE DOUBLE PRECISION , 
     CONSTRUCTIONREBATE DOUBLE PRECISION , 
     DEPRECIATION_VALUE DOUBLE PRECISION , 
     USAGEREBATE DOUBLE PRECISION , 
     CREATETIMESTAMP TIMESTAMP without time zone, 
     LASTUPDATEDTIMESTAMP TIMESTAMP without time zone, 
     TAX1 DOUBLE PRECISION , 
     TAX2 DOUBLE PRECISION , 
     TAX3 DOUBLE PRECISION , 
     TAX4 DOUBLE PRECISION , 
     TAX5 DOUBLE PRECISION , 
     TAX6 DOUBLE PRECISION , 
     TAX7 DOUBLE PRECISION , 
     TAX8 DOUBLE PRECISION , 
     TAX9 DOUBLE PRECISION , 
     TAX10 DOUBLE PRECISION , 
     ALV DOUBLE PRECISION 
);


COMMENT ON TABLE EGPT_FLOORDEMANDCALC IS 'Unitwise tax calculation link table';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.ID_FLOORDET IS 'FK to EGPT_FLOORDEMANDCALC';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.ID_DMDCALC IS 'FK to EGPT_DEMANDCALCULATIONS';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.CATEGORYAMT IS 'Guidance Value';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.OCCUPANCYREBATE IS 'Rebate against occupancy';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.CONSTRUCTIONREBATE IS 'Rebate against Construction type';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.DEPRECIATION_VALUE IS 'Rebate against Depriciation';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.USAGEREBATE IS 'Rebate against Usage';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.TAX1 IS 'Tax amount for tax head 1 for a floor, ULB t ULB the tax heads are different';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.TAX2 IS 'Tax amount for tax head 2 for a floor';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.TAX3 IS 'Tax amount for tax head 3 for a floor';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.TAX4 IS 'Tax amount for tax head 4 for a floor';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.TAX5 IS 'Tax amount for tax head 5 for a floor';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.TAX6 IS 'Tax amount for tax head 6 for a floor';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.TAX7 IS 'Tax amount for tax head 7 for a floor';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.TAX8 IS 'Tax amount for tax head 8 for a floor';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.TAX9 IS 'Tax amount for tax head 9 for a floor';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.TAX10 IS 'Tax amount for tax head 10 for a floor';

COMMENT ON COLUMN EGPT_FLOORDEMANDCALC.ALV IS 'Manual ALV value for floor';

create sequence SEQ_EGPT_FLOORDEMANDCALC;


CREATE TABLE EGPT_FLOOR_DETAIL 
( 
     ID BIGINT NOT NULL ,
     ID_PROPERTY_DETAIL BIGINT NOT NULL , 
     EXTRA_FIELD1 character varying(256) , 
     FLOOR_NO BIGINT NOT NULL , 
     CRT_TIMESTAMP TIMESTAMP without time zone NOT NULL , 
     FLOOR_AREA DOUBLE PRECISION , 
     BUILTUP_AREA DOUBLE PRECISION , 
     ID_FEATURELIST BIGINT , 
     ID_STRUC_CL BIGINT , 
     ID_OCCPN_MSTR BIGINT , 
     ID_USG_MSTR BIGINT , 
     WATER_METER_NUM character varying(32), 
     ELEC_METER_NUM character varying(32), 
     LASTUPDATEDTIMESTAMP TIMESTAMP without time zone NOT NULL , 
     RENTPER_MONTH character varying(256), 
     EXTRA_FIELD2 character varying(256), 
     EXTRA_FIELD3 character varying(256), 
     EXTRA_FIELD4 character varying(256), 
     EXTRA_FIELD5 character varying(256), 
     EXTRA_FIELD6 character varying(256), 
     CREATED_BY BIGINT , 
     MODIFIED_BY BIGINT , 
     ID_DEPRECIATIONMASTER BIGINT , 
     EXTRA_FIELD7 character varying(256), 
     MANUAL_ALV character varying(256), 
     UNIT_TYPE BIGINT , 
     UNIT_TYPE_CATEGORY character varying (256), 
     WATER_RATE character varying (256), 
     ALV character varying (256), 
     MIG_STATUS character varying (1), 
     TAX_EXEMPTED_REASON character varying (60) 
);

COMMENT ON TABLE EGPT_FLOOR_DETAIL IS 'Details of a unit';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.ID_PROPERTY_DETAIL IS 'FK to EGPT_FLOOR_DETAIL';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.EXTRA_FIELD1 IS 'Unit No';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.FLOOR_NO IS 'Floor Number - 0, 1, 2 etc.';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.CRT_TIMESTAMP IS 'Created date';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.FLOOR_AREA IS 'Not used';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.BUILTUP_AREA IS 'Built up area';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.ID_FEATURELIST IS 'Not used';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.ID_STRUC_CL IS 'FK to EGPT_STRUC_CL';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.ID_OCCPN_MSTR IS 'FK to EGPT_OCCUPATION_TYPE_MASTER';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.ID_USG_MSTR IS 'FK to EGPT_PROPERTY_USAGE_MASTER';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.WATER_METER_NUM IS 'Water meter number';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.ELEC_METER_NUM IS 'Electirc meter number';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.RENTPER_MONTH IS 'Rent for the unit';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.EXTRA_FIELD2 IS 'Extra info specifit client';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.EXTRA_FIELD3 IS 'Extra info specifit client';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.EXTRA_FIELD4 IS 'Extra info specifit client';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.EXTRA_FIELD5 IS 'Extra info specifit client';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.EXTRA_FIELD6 IS 'Extra info specifit client';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.CREATED_BY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.MODIFIED_BY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.ID_DEPRECIATIONMASTER IS 'FK to EGDCB_DEPRECIATIONMASTER';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.EXTRA_FIELD7 IS 'Type of floor';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.MANUAL_ALV IS 'Manually entered ALV';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.UNIT_TYPE IS 'Type of Unit';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.UNIT_TYPE_CATEGORY IS 'Category for Unit';

COMMENT ON COLUMN EGPT_FLOOR_DETAIL.WATER_RATE IS 'Water rate';

create sequence SEQ_EGPT_FLOOR_DETAIL;


CREATE TABLE EGPT_HEARING 
( 
     ID BIGINT NOT NULL , 
     ID_OBJECTION BIGINT NOT NULL , 
     PLANNED_HEARING_DATE TIMESTAMP without time zone, 
     ACTUAL_HEARING_DATE TIMESTAMP without time zone, 
     HEARING_DETAILS CHARACTER VARYING(1024), 
     CREATED_BY BIGINT , 
     MODIFIED_BY BIGINT , 
     CREATED_DATE TIMESTAMP without time zone, 
     MODIFIED_DATE TIMESTAMP without time zone, 
     OBJECTION_IDX BIGINT NOT NULL , 
     DOCUMENT_NUMBER CHARACTER VARYING(50), 
     HEARINGNUMBER CHARACTER VARYING(50), 
     INSPECTIONREQUIRED BIGINT 
);

COMMENT ON TABLE EGPT_HEARING IS 'Objection hearings';

COMMENT ON COLUMN EGPT_HEARING.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_HEARING.ID_OBJECTION IS 'FK to EGPT_OBJECTION';

COMMENT ON COLUMN EGPT_HEARING.PLANNED_HEARING_DATE IS 'Planned hearing date';

COMMENT ON COLUMN EGPT_HEARING.ACTUAL_HEARING_DATE IS 'Actual hearing date';

COMMENT ON COLUMN EGPT_HEARING.HEARING_DETAILS IS 'hearing deatils';

COMMENT ON COLUMN EGPT_HEARING.CREATED_BY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_HEARING.MODIFIED_BY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_HEARING.OBJECTION_IDX IS 'Hearing List index';

COMMENT ON COLUMN EGPT_HEARING.DOCUMENT_NUMBER IS 'hearing document no';

COMMENT ON COLUMN EGPT_HEARING.HEARINGNUMBER IS 'hearing no';

COMMENT ON COLUMN EGPT_HEARING.INSPECTIONREQUIRED IS 'Inspection required, 0 or 1';

create sequence SEQ_EGPT_HEARING;


CREATE TABLE EGPT_INSPECTION 
( 
     ID BIGINT NOT NULL , 
     ID_OBJECTION BIGINT NOT NULL , 
     INSPECTION_REMARKS CHARACTER VARYING(1024), 
     CREATED_BY BIGINT , 
     MODIFIED_BY BIGINT , 
     CREATED_DATE TIMESTAMP without time zone, 
     MODIFIED_DATE TIMESTAMP without time zone, 
     OBJECTION_IDX BIGINT NOT NULL , 
     DOCUMENT_NUMBER CHARACTER VARYING(50) 
);

COMMENT ON TABLE EGPT_INSPECTION IS 'Inspections during Objection process';

COMMENT ON COLUMN EGPT_INSPECTION.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_INSPECTION.ID_OBJECTION IS 'FK to EGPT_OBJECTION';

COMMENT ON COLUMN EGPT_INSPECTION.INSPECTION_REMARKS IS 'Inspection remarks';

COMMENT ON COLUMN EGPT_INSPECTION.CREATED_BY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_INSPECTION.MODIFIED_BY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_INSPECTION.OBJECTION_IDX IS 'Inspection list index';

COMMENT ON COLUMN EGPT_INSPECTION.DOCUMENT_NUMBER IS 'Inspection document no';

create sequence SEQ_EGPT_INSPECTION;


CREATE TABLE EGPT_MSTR_BNDRY_CATEGORY 
( 
     ID BIGINT NOT NULL , 
     ID_BNDRY BIGINT NOT NULL , 
     ID_CATEGORY BIGINT NOT NULL , 
     MODIFIED_DATE DATE NOT NULL , 
     FROM_DATE TIMESTAMP without time zone, 
     TO_DATE TIMESTAMP without time zone, 
     CREATED_BY BIGINT , 
     MODIFIED_BY BIGINT , 
     CREATED_DATE DATE 
);

COMMENT ON TABLE EGPT_MSTR_BNDRY_CATEGORY IS 'Maps boundaries to usage + structural classification combinations, time-wise.';

COMMENT ON COLUMN EGPT_MSTR_BNDRY_CATEGORY.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_MSTR_BNDRY_CATEGORY.ID_BNDRY IS 'FK to EG_BOUNDARY';

COMMENT ON COLUMN EGPT_MSTR_BNDRY_CATEGORY.ID_CATEGORY IS 'FK to EGPT_MSTR_CATEGORY';

COMMENT ON COLUMN EGPT_MSTR_BNDRY_CATEGORY.FROM_DATE IS 'Starting date of the period where this value is active';

COMMENT ON COLUMN EGPT_MSTR_BNDRY_CATEGORY.TO_DATE IS 'End date of the period where this value is active';

COMMENT ON COLUMN EGPT_MSTR_BNDRY_CATEGORY.CREATED_BY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_MSTR_BNDRY_CATEGORY.MODIFIED_BY IS 'FK to eg_user';

create sequence SEQ_EGPT_MSTR_BNDRY_CATEGORY;


CREATE TABLE EGPT_MSTR_CATEGORY 
( 
     ID BIGINT NOT NULL , 
     CATEGORY_NAME CHARACTER VARYING(32) NOT NULL , 
     CATEGORY_AMNT DOUBLE PRECISION NOT NULL , 
     ID_INSTALLMENT BIGINT , 
     IS_HISTORY character(1), 
     CREATED_BY BIGINT , 
     ID_USAGE BIGINT , 
     FROM_DATE TIMESTAMP without time zone, 
     TO_DATE TIMESTAMP without time zone, 
     MODIFIED_BY BIGINT , 
     CREATED_DATE TIMESTAMP without time zone, 
     MODIFIED_DATE TIMESTAMP without time zone, 
     ID_STRUCT_CL BIGINT 
);

COMMENT ON TABLE EGPT_MSTR_CATEGORY IS 'Stores tax rates for usage + structural classification combinations, time-wise.';

COMMENT ON COLUMN EGPT_MSTR_CATEGORY.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_MSTR_CATEGORY.CATEGORY_NAME IS 'For internal use only';

COMMENT ON COLUMN EGPT_MSTR_CATEGORY.CATEGORY_AMNT IS 'Tax amount';

COMMENT ON COLUMN EGPT_MSTR_CATEGORY.ID_INSTALLMENT IS 'Not used';

COMMENT ON COLUMN EGPT_MSTR_CATEGORY.IS_HISTORY IS 'N';

COMMENT ON COLUMN EGPT_MSTR_CATEGORY.CREATED_BY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_MSTR_CATEGORY.ID_USAGE IS 'FK to EGPT_PROPERTY_USAGE_MASTER';

COMMENT ON COLUMN EGPT_MSTR_CATEGORY.FROM_DATE IS 'Start date of period';

COMMENT ON COLUMN EGPT_MSTR_CATEGORY.TO_DATE IS 'End date of period';

COMMENT ON COLUMN EGPT_MSTR_CATEGORY.MODIFIED_BY IS 'FK to eg_user';

COMMENT ON COLUMN EGPT_MSTR_CATEGORY.ID_STRUCT_CL IS 'FK to EGPT_STRUC_CL';

create sequence SEQ_EGPT_MSTR_CATEGORY;


CREATE TABLE EGPT_MUTATION_MASTER
( 
     ID BIGINT NOT NULL , 
     MUTATION_NAME CHARACTER VARYING(256), 
     MUTATION_DESC CHARACTER VARYING(256), 
     TYPE CHARACTER VARYING(16), 
     CODE CHARACTER VARYING(16), 
     ORDER_ID BIGINT 
);

COMMENT ON TABLE EGPT_MUTATION_MASTER IS 'Master table that stores types of mutations';

COMMENT ON COLUMN EGPT_MUTATION_MASTER.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_MUTATION_MASTER.MUTATION_NAME IS 'Name of mutation type';

COMMENT ON COLUMN EGPT_MUTATION_MASTER.MUTATION_DESC IS 'Description for mutation type';

COMMENT ON COLUMN EGPT_MUTATION_MASTER.TYPE IS 'CREATE, MODIFY, DEACTIVATE, TRANSFER';

COMMENT ON COLUMN EGPT_MUTATION_MASTER.CODE IS 'Code for internal use';

COMMENT ON COLUMN EGPT_MUTATION_MASTER.ORDER_ID IS 'Dropdown ordering';

CREATE SEQUENCE SEQ_EGPT_MUTATION_MASTER;


CREATE TABLE EGPT_MUTATION_OWNER 
( 
     ID BIGINT NOT NULL , 
     ID_PROP_MUTATION BIGINT NOT NULL , 
     OWNERID BIGINT NOT NULL 
);

COMMENT ON TABLE EGPT_MUTATION_OWNER IS 'Link table between EGPT_PROPERTY_MUTATION and EG_CITIZEN';

COMMENT ON COLUMN EGPT_MUTATION_OWNER.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_MUTATION_OWNER.ID_PROP_MUTATION IS 'FK to EGPT_PROPERTY_MUTATION';

COMMENT ON COLUMN EGPT_MUTATION_OWNER.OWNERID IS 'FK to EG_CITIZEN';

create sequence SEQ_EGPT_MUTATION_OWNER;


CREATE TABLE EGPT_NEG_ARREARS 
( 
     ID BIGINT NOT NULL , 
     INDEX_NO CHARACTER VARYING(24), 
     ID_DEMAND_DETAIL BIGINT , 
     ID_DEMAND_REASON BIGINT , 
     AMOUNT BIGINT , 
     ID_INSTALLMENT BIGINT 
);

COMMENT ON TABLE EGPT_NEG_ARREARS IS 'Data pushed to this table for -ve arrears adjustment';

COMMENT ON COLUMN EGPT_NEG_ARREARS.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_NEG_ARREARS.INDEX_NO IS 'Index BIGINT';

COMMENT ON COLUMN EGPT_NEG_ARREARS.ID_DEMAND_DETAIL IS 'PK of eg_demand_detail';

COMMENT ON COLUMN EGPT_NEG_ARREARS.ID_DEMAND_REASON IS 'PK of ed_demand_reson';

COMMENT ON COLUMN EGPT_NEG_ARREARS.AMOUNT IS 'Tax amount';

COMMENT ON COLUMN EGPT_NEG_ARREARS.ID_INSTALLMENT IS 'pk of eg_installment_master';

create sequence seq_EGPT_NEG_ARREARS;


CREATE TABLE EGPT_NOTICE 
( 
     ID BIGINT NOT NULL , 
     ID_BASICPROPERTY BIGINT , 
     ID_MODULE BIGINT , 
     NOTICETYPE CHARACTER VARYING(32), 
     NOTICENO CHARACTER VARYING(64), 
     NOTICEDATE TIMESTAMP without time zone, 
     ID_USER BIGINT , 
     NOTICE_FILE bytea , 
     IS_BLOB character(1)
);

COMMENT ON TABLE EGPT_NOTICE IS 'Contains notice information for properties';

COMMENT ON COLUMN EGPT_NOTICE.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_NOTICE.ID_BASICPROPERTY IS 'FK to EGPT_BASIC_PROPERTY';

COMMENT ON COLUMN EGPT_NOTICE.ID_MODULE IS 'FK to EG_MODULE';

COMMENT ON COLUMN EGPT_NOTICE.NOTICETYPE IS 'Type of notice';

COMMENT ON COLUMN EGPT_NOTICE.NOTICENO IS 'Notice Number, it is also the document ID in the document service';

COMMENT ON COLUMN EGPT_NOTICE.NOTICEDATE IS 'notice generation date';

COMMENT ON COLUMN EGPT_NOTICE.ID_USER IS 'FK to EG_USER';

create sequence SEQ_EGPT_NOTICE;


CREATE TABLE EGPT_OBJECTION 
( 
     ID BIGINT NOT NULL , 
     OBJECTION_NUMBER CHARACTER VARYING(50) NOT NULL , 
     RECIEVED_ON TIMESTAMP without time zone, 
     RECIEVED_BY CHARACTER VARYING(256), 
     DETAILS CHARACTER VARYING(1024), 
     ID_STATUS BIGINT NOT NULL , 
     ID_STATE BIGINT , 
     CREATED_BY BIGINT , 
     MODIFIED_BY BIGINT , 
     CREATED_DATE TIMESTAMP without time zone, 
     MODIFIED_DATE TIMESTAMP without time zone, 
     REMARKS CHARACTER VARYING(1024), 
     OBJECTION_REJECTED BIGINT , 
     DATE_OF_OUTCOME TIMESTAMP without time zone, 
     ID_BASICPROPERTY BIGINT NOT NULL , 
     DOCUMENT_NUMBER_OBJECTION CHARACTER VARYING(50), 
     DOCUMENT_NUMBER_OUTCOME CHARACTER VARYING(50) 
);

COMMENT ON TABLE EGPT_OBJECTION IS 'Main objection table';

COMMENT ON COLUMN EGPT_OBJECTION.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_OBJECTION.OBJECTION_NUMBER IS 'Autogenerated';

COMMENT ON COLUMN EGPT_OBJECTION.RECIEVED_ON IS 'Received on date';

COMMENT ON COLUMN EGPT_OBJECTION.RECIEVED_BY IS 'objection received by';

COMMENT ON COLUMN EGPT_OBJECTION.DETAILS IS 'Objection details';

COMMENT ON COLUMN EGPT_OBJECTION.ID_STATUS IS 'FK to EGW_STATUS';

COMMENT ON COLUMN EGPT_OBJECTION.ID_STATE IS 'FK to EG_WF_STATES';

COMMENT ON COLUMN EGPT_OBJECTION.OBJECTION_REJECTED IS '0 or 1';

COMMENT ON COLUMN EGPT_OBJECTION.DATE_OF_OUTCOME IS 'Objection outcome date';

COMMENT ON COLUMN EGPT_OBJECTION.ID_BASICPROPERTY IS 'FK to EGPT_BASIC_PROPERTY';

COMMENT ON COLUMN EGPT_OBJECTION.DOCUMENT_NUMBER_OBJECTION IS 'Objection document no';

COMMENT ON COLUMN EGPT_OBJECTION.DOCUMENT_NUMBER_OUTCOME IS 'outcome document no';

create sequence SEQ_EGPT_OBJECTION;


CREATE TABLE EGPT_OCCUPATION_TYPE_MASTER 
( 
     ID BIGINT NOT NULL , 
     OCCUPATION CHARACTER VARYING(256) NOT NULL , 
     MODIFIED_DATE DATE NOT NULL , 
     OCCUPANY_FACTOR DOUBLE PRECISION , 
     OCCUPATION_LOCAL CHARACTER VARYING(512) , 
     CODE CHARACTER VARYING(16), 
     FROM_DATE TIMESTAMP without time zone, 
     TO_DATE TIMESTAMP without time zone, 
     ID_USG_MSTR BIGINT , 
     CREATED_BY BIGINT , 
     MODIFIED_BY BIGINT , 
     CREATED_DATE DATE 
);

COMMENT ON TABLE EGPT_OCCUPATION_TYPE_MASTER IS 'Master table for occupation type';

COMMENT ON COLUMN EGPT_OCCUPATION_TYPE_MASTER.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_OCCUPATION_TYPE_MASTER.OCCUPATION IS 'Owner, Tenanted, Vacant';

COMMENT ON COLUMN EGPT_OCCUPATION_TYPE_MASTER.OCCUPANY_FACTOR IS '1, 2, 3 - used in tax calc';

COMMENT ON COLUMN EGPT_OCCUPATION_TYPE_MASTER.OCCUPATION_LOCAL IS 'Not used';

COMMENT ON COLUMN EGPT_OCCUPATION_TYPE_MASTER.CODE IS 'Internal use';

COMMENT ON COLUMN EGPT_OCCUPATION_TYPE_MASTER.FROM_DATE IS 'From date for occupancy factor validity';

COMMENT ON COLUMN EGPT_OCCUPATION_TYPE_MASTER.TO_DATE IS 'To date for occupancy factor validity';

COMMENT ON COLUMN EGPT_OCCUPATION_TYPE_MASTER.ID_USG_MSTR IS 'Not used';

COMMENT ON COLUMN EGPT_OCCUPATION_TYPE_MASTER.CREATED_DATE IS 'From date for occupancy factor validity';

create sequence SEQ_EGPT_OCCUPATION_TYPE_MASTER;


CREATE TABLE EGPT_PROPERTY 
( 
     ID BIGINT NOT NULL , 
     CREATED_DATE DATE NOT NULL , 
     MODIFIED_DATE DATE NOT NULL , 
     CREATED_BY BIGINT NOT NULL , 
     ID_SOURCE BIGINT NOT NULL , 
     ID_BASIC_PROPERTY BIGINT NOT NULL , 
     IS_DEFAULT_PROPERTY CHARACTER(1) DEFAULT 'N'::bpchar NOT NULL , 
     STATUS CHARACTER(1) DEFAULT 'N'::bpchar , 
     LATEST_NODE BIGINT , 
     EFFECTIVE_DATE DATE NOT NULL , 
     ISCHECKED CHARACTER(1) DEFAULT 'N'::bpchar , 
     REMARKS CHARACTER VARYING(1048), 
     ID_MODIFY_REASON BIGINT , 
     ID_INSTALLMENT BIGINT , 
     MODIFIED_BY BIGINT , 
     STATE_ID BIGINT , 
     ISEXEMPTEDFROMTAX character(1), 
     TAXEXEMPTREASON CHARACTER VARYING(256), 
     DOC_NUMBER CHARACTER VARYING(256), 
     AREA_BNDRY BIGINT , 
     EXTRA_FIELD1 CHARACTER VARYING(256), 
     EXTRA_FIELD2 CHARACTER VARYING(256), 
     EXTRA_FIELD3 CHARACTER VARYING(256), 
     EXTRA_FIELD4 CHARACTER VARYING(256), 
     EXTRA_FIELD5 CHARACTER VARYING(256), 
     EXTRA_FIELD6 CHARACTER VARYING(256) 
);

COMMENT ON TABLE EGPT_PROPERTY IS 'Contains one row for each property per operation like mutation, transfer';

COMMENT ON COLUMN EGPT_PROPERTY.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_PROPERTY.ID_SOURCE IS 'FK to EGPT_SRC_OF_INFO';

COMMENT ON COLUMN EGPT_PROPERTY.EXTRA_FIELD1 IS 'Not Used';

COMMENT ON COLUMN EGPT_PROPERTY.EXTRA_FIELD2 IS 'to know which notice to be generated Notice 127 or Notice 134';

COMMENT ON COLUMN EGPT_PROPERTY.EXTRA_FIELD3 IS 'Status of Notice (Notices created across the system in different stages of property) generated or not. values are Yes or blank';

COMMENT ON COLUMN EGPT_PROPERTY.ID_BASIC_PROPERTY IS 'FK to EGPT_BASIC_PROPERTY';

COMMENT ON COLUMN EGPT_PROPERTY.IS_DEFAULT_PROPERTY IS 'wheather default property of not, values Y or N';

COMMENT ON COLUMN EGPT_PROPERTY.STATUS IS 'State of property. values if property in Workflow -W in History- H in Approved - A';

COMMENT ON COLUMN EGPT_PROPERTY.LATEST_NODE IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY.EFFECTIVE_DATE IS 'Date of Occupancy';

COMMENT ON COLUMN EGPT_PROPERTY.ISCHECKED IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY.REMARKS IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY.ID_MODIFY_REASON IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY.ID_INSTALLMENT IS 'FK to EG_INSTALLMENT_MASTER';

COMMENT ON COLUMN EGPT_PROPERTY.STATE_ID IS 'FK to EG_WF_STATES';

COMMENT ON COLUMN EGPT_PROPERTY.EXTRA_FIELD4 IS 'Status of Prathivrutta generated or not. values are Yes or blank';

COMMENT ON COLUMN EGPT_PROPERTY.EXTRA_FIELD5 IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY.ISEXEMPTEDFROMTAX IS 'Is property exempted from tax';

COMMENT ON COLUMN EGPT_PROPERTY.TAXEXEMPTREASON IS 'Tax exemption reason';

COMMENT ON COLUMN EGPT_PROPERTY.DOC_NUMBER IS 'Uploaded document Number';

COMMENT ON COLUMN EGPT_PROPERTY.EXTRA_FIELD6 IS 'Property Address for Modify WF address|HNo|HNoOld|Pin|MNo|eMail|Khasra|Mauza|CitySurveyNo|SheetNo|PID';

create sequence SEQ_EGPT_PROPERTY;


CREATE TABLE EGPT_PROPERTYID 
( 
     ID BIGINT NOT NULL , 
     ZONE_NUM BIGINT , 
     WARD_ADM_ID BIGINT , 
     ADM1 BIGINT , 
     ADM2 BIGINT , 
     ADM3 BIGINT , 
     CREATED_DATE timestamp without time zone NOT NULL , 
     MODIFIED_DATE timestamp without time zone NOT NULL , 
     FRONT_BNDRY_STREET BIGINT , 
     BACK_BNDRY_STREET BIGINT , 
     LEFT_BNDRY_STREET BIGINT , 
     RIGHT_BNDRY_STREET BIGINT , 
     BNDRY_STREET_DMDCALC BIGINT , 
     NORTH_BOUNDED CHARACTER VARYING(256), 
     SOUTH_BOUNDED CHARACTER VARYING(256), 
     EAST_BOUNDED CHARACTER VARYING(256), 
     WEST_BOUNDED CHARACTER VARYING(256), 
     CREATED_BY BIGINT , 
     MODIFIED_BY BIGINT 
);

COMMENT ON TABLE EGPT_PROPERTYID IS 'Contains Property boundary and bounded by information';

COMMENT ON COLUMN EGPT_PROPERTYID.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_PROPERTYID.ZONE_NUM IS 'zone boundary (FK to eg_boundary)';

COMMENT ON COLUMN EGPT_PROPERTYID.WARD_ADM_ID IS 'Ward boundry FK to EG_BOUNDRY';

COMMENT ON COLUMN EGPT_PROPERTYID.ADM1 IS 'FK to EG_BOUNDRY';

COMMENT ON COLUMN EGPT_PROPERTYID.ADM2 IS 'FK to EG_BOUNDRY';

COMMENT ON COLUMN EGPT_PROPERTYID.ADM3 IS 'FK to EG_BOUNDRY';

COMMENT ON COLUMN EGPT_PROPERTYID.FRONT_BNDRY_STREET IS 'Front bounded boundary';

COMMENT ON COLUMN EGPT_PROPERTYID.BACK_BNDRY_STREET IS 'Back bounded boundary';

COMMENT ON COLUMN EGPT_PROPERTYID.LEFT_BNDRY_STREET IS 'Left bounded boundary';

COMMENT ON COLUMN EGPT_PROPERTYID.RIGHT_BNDRY_STREET IS 'Right bounded boundary';

COMMENT ON COLUMN EGPT_PROPERTYID.BNDRY_STREET_DMDCALC IS 'Boundary for tax calculation in case boundary is diff from actual boundary';

COMMENT ON COLUMN EGPT_PROPERTYID.NORTH_BOUNDED IS 'Property North Bounded by';

COMMENT ON COLUMN EGPT_PROPERTYID.SOUTH_BOUNDED IS 'Property South Bounded by';

COMMENT ON COLUMN EGPT_PROPERTYID.EAST_BOUNDED IS 'Property East Bounded by';

COMMENT ON COLUMN EGPT_PROPERTYID.WEST_BOUNDED IS 'Property West Bounded by';

create sequence SEQ_EGPT_PROPERTYID;


CREATE TABLE EGPT_PROPERTY_ARREARS 
( 
     ID BIGINT NOT NULL , 
     ID_BASIC_PROPERTY BIGINT , 
     FROM_DATE BIGINT , 
     TO_DATE BIGINT , 
     GENERAL_TAX DOUBLE PRECISION , 
     SEWERAGE_TAX DOUBLE PRECISION , 
     FIRESERVICE_TAX DOUBLE PRECISION , 
     LIGHTING_TAX DOUBLE PRECISION , 
     GENERALWATER_TAX DOUBLE PRECISION , 
     EDU_CESS DOUBLE PRECISION , 
     EGCESS DOUBLE PRECISION , 
     BIG_RESID_TAX DOUBLE PRECISION , 
     PENALTY_TAX DOUBLE PRECISION 
);

COMMENT ON TABLE EGPT_PROPERTY_ARREARS IS 'Contains tax from legacy database';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.ID_BASIC_PROPERTY IS 'FK to EGPT_BASIC_PROPERTY';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.FROM_DATE IS 'Tax effective from date';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.TO_DATE IS 'Tax effective to date';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.GENERAL_TAX IS 'General tax';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.SEWERAGE_TAX IS 'sewerage tax';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.FIRESERVICE_TAX IS 'Fire service tax';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.LIGHTING_TAX IS 'light tax';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.GENERALWATER_TAX IS 'Water tax';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.EDU_CESS IS 'EDU Cess';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.EGCESS IS 'EGS Cess';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.BIG_RESID_TAX IS 'Big Residential Building Tax';

COMMENT ON COLUMN EGPT_PROPERTY_ARREARS.PENALTY_TAX IS 'penalty tax';

create sequence SEQ_EGPT_PROPERTY_ARREARS;


CREATE TABLE EGPT_PROPERTY_DETAIL 
( 
     ID BIGINT NOT NULL , 
     ID_PROPERTY BIGINT NOT NULL , 
     PROPERTY_LENGTH DOUBLE PRECISION , 
     PROPERTY_BREADTH DOUBLE PRECISION , 
     SITAL_AREA DOUBLE PRECISION , 
     IS_IRREGULAR character(1) DEFAULT 'N'::bpchar , 
     PLINTH_AREA DOUBLE PRECISION , 
     TOTAL_BUILTUP_AREA DOUBLE PRECISION , 
     COMMN_BUILTUP_AREA DOUBLE PRECISION , 
     COMMN_VCNT_LAND DOUBLE PRECISION , 
     NUM_FLOORS BIGINT , 
     ID_USG_MSTR BIGINT , 
     WATER_METER_NUM CHARACTER VARYING(32), 
     ELEC_METER_NUM CHARACTER VARYING(32), 
     SURVEY_NUM CHARACTER VARYING(64), 
     IS_FIELD_VERIFIED character(1) DEFAULT 'N' NOT NULL , 
     FIELD_VERIF_DATE TIMESTAMP without time zone, 
     PROPERTY_TYPE CHARACTER VARYING(64) NOT NULL , 
     ID_INSTALLMENT BIGINT , 
     COMPLETION_YEAR TIMESTAMP without time zone, 
     EFFECTIVE_DATE TIMESTAMP without time zone, 
     ID_PROPERTYTYPEMASTER BIGINT , 
     ID_MUTATION BIGINT NOT NULL , 
     UPDT_TIMESTAMP DATE NOT NULL , 
     REFNUM CHARACTER VARYING(16), 
     REFDATE TIMESTAMP without time zone, 
     REMARKS CHARACTER VARYING(32), 
     IS_COMZONE character(1), 
     IS_CORNERPLOT character(1),
     EXTRA_FIELD1 CHARACTER VARYING(256), 
     EXTRA_FIELD2 CHARACTER VARYING(256), 
     EXTRA_FIELD3 CHARACTER VARYING(256),  
     EXTRA_FIELD4 CHARACTER VARYING(4000), 
     EXTRA_FIELD5 CHARACTER VARYING(256), 
     EXTRA_FIELD6 CHARACTER VARYING(256), 
     DATEOFCOMPLETION TIMESTAMP without time zone, 
     ID_OCCPN_MSTR BIGINT , 
     NONRES_PLOTAREA DOUBLE PRECISION , 
     MANUAL_ALV CHARACTER VARYING(256), 
     OCCUPIER_NAME CHARACTER VARYING(256), 
     ALV CHARACTER VARYING(256) 
);

COMMENT ON TABLE EGPT_PROPERTY_DETAIL IS 'Contains Property details like type, usage of property';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.ID_PROPERTY IS 'FK to EGPT_PROPERTY';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.PROPERTY_LENGTH IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.PROPERTY_BREADTH IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.SITAL_AREA IS 'Area of Plot';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.IS_IRREGULAR IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.PLINTH_AREA IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.TOTAL_BUILTUP_AREA IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.COMMN_BUILTUP_AREA IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.COMMN_VCNT_LAND IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.NUM_FLOORS IS 'No.of floors';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.ID_USG_MSTR IS 'FK to egpt_property_usage_master';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.WATER_METER_NUM IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.ELEC_METER_NUM IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.SURVEY_NUM IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.IS_FIELD_VERIFIED IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.FIELD_VERIF_DATE IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.PROPERTY_TYPE IS 'FK to egpt_property_type_master';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.ID_INSTALLMENT IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.COMPLETION_YEAR IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.EFFECTIVE_DATE IS 'Property Occupancy date';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.ID_PROPERTYTYPEMASTER IS 'FK to egpt_property_type_master';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.ID IS 'FK to EGPT_MUTATION_MASTER, reason for modification';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.UPDT_TIMESTAMP IS 'Modified Date';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.REFNUM IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.REFDATE IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.EXTRA_FIELD1 IS 'General Water meter Rate';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.EXTRA_FIELD2 IS 'Rent if property is Open Plot';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.EXTRA_FIELD3 IS 'Building cost for Govt Properties';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.IS_COMZONE IS 'Amenities for Govt Properties';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.IS_CORNERPLOT IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.EXTRA_FIELD4 IS 'Amenities for Govt Properties';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.EXTRA_FIELD5 IS 'Property Category. Residential house, residential flat etc.';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.EXTRA_FIELD6 IS 'Location Factor';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.DATEOFCOMPLETION IS 'Date of Property Completion/occupancy';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.ID_OCCPN_MSTR IS 'FK to egpt_occupation_type_master';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.NONRES_PLOTAREA IS 'Non-Residential area for Plot Area';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.MANUAL_ALV IS 'Manual ALV value for Open Plot';

COMMENT ON COLUMN EGPT_PROPERTY_DETAIL.OCCUPIER_NAME IS 'Occupier Name for Open Plot';

create sequence SEQ_EGPT_PROPERTY_DETAIL;


CREATE TABLE EGPT_PROPERTY_DOCS 
( 
     ID BIGINT NOT NULL , 
     MODIFIED_DATE TIMESTAMP without time zone, 
     DOC_NUMBER CHARACTER VARYING(128) NOT NULL , 
     REASON CHARACTER VARYING(128) NOT NULL , 
     ID_BASIC_PROPERTY BIGINT NOT NULL , 
     CREATED_DATE TIMESTAMP without time zone 
);

COMMENT ON TABLE EGPT_PROPERTY_DOCS IS 'Contains all the documents attached in life of property for different transactions on a property';

COMMENT ON COLUMN EGPT_PROPERTY_DOCS.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_PROPERTY_DOCS.DOC_NUMBER IS 'Not Used';

COMMENT ON COLUMN EGPT_PROPERTY_DOCS.REASON IS 'Reason for Docs uploaded';

COMMENT ON COLUMN EGPT_PROPERTY_DOCS.ID_BASIC_PROPERTY IS 'FK to egpt_basic_property';

create sequence SEQ_EGPT_PROPERTY_DOCS;


CREATE TABLE EGPT_PROPERTY_MUTATION 
( 
     ID BIGINT NOT NULL , 
     MUTATION_NO CHARACTER VARYING(60), 
     MUTATION_DATE TIMESTAMP without time zone, 
     REF_PID CHARACTER VARYING(64), 
     ID_BASIC_PROPERTY BIGINT NOT NULL , 
     CREATED_DATE TIMESTAMP without time zone, 
     MODIFIED_DATE TIMESTAMP without time zone, 
     CREATED_BY BIGINT , 
     CONSFORTRANSFEE BIGINT , 
     IS_TFPAYABLE character(1), 
     NOTICE_DATE TIMESTAMP without time zone, 
     APPLICATION_NO CHARACTER VARYING(60), 
     ID_APPLN_STATUS BIGINT , 
     DEED_NO CHARACTER VARYING(64), 
     DEED_DATE TIMESTAMP without time zone, 
     MODIFIED_BY BIGINT , 
     DOCUMENT_NUMBER CHARACTER VARYING(50), 
     MUTATION_FEE BIGINT , 
     RECEIPT_NUMBER CHARACTER VARYING(60), 
     OLD_OWNER_NAME CHARACTER VARYING(512) ,
     EXTRA_FIELD1 CHARACTER VARYING(256), 
     EXTRA_FIELD2 CHARACTER VARYING(256), 
     EXTRA_FIELD3 CHARACTER VARYING(256),
     EXTRA_FIELD4 CHARACTER VARYING(256)
);

COMMENT ON TABLE EGPT_PROPERTY_MUTATION IS 'Contains Name Transfer information';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.ID IS 'FK to egpt_mutation_master';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.MUTATION_NO IS 'Order no for Name Transfer';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.MUTATION_DATE IS 'Order date for Name Transfer';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.REF_PID IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.ID_BASIC_PROPERTY IS 'FK to egpt_basic_property';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.EXTRA_FIELD1 IS 'Remarks';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.EXTRA_FIELD2 IS 'Subregistrar Name';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.CONSFORTRANSFEE IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.IS_TFPAYABLE IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.NOTICE_DATE IS 'Application Date';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.EXTRA_FIELD3 IS 'Sale Details';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.APPLICATION_NO IS 'Application no';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.ID_APPLN_STATUS IS 'Name Transfer Application Status, FK to EGW_STATUS';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.DEED_NO IS 'Document Number';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.DEED_DATE IS 'Document Date';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.EXTRA_FIELD4 IS 'Other Mutation Reason, if not chosed from given drop down list';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.DOCUMENT_NUMBER IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.MUTATION_FEE IS 'Name Transfer Free';

COMMENT ON COLUMN EGPT_PROPERTY_MUTATION.RECEIPT_NUMBER IS 'Name Transfer Free receipt no';

create sequence SEQ_EGPT_PROPERTY_MUTATION;


CREATE TABLE EGPT_PROPERTY_OWNER 
( 
     OWNERID BIGINT NOT NULL , 
     ID_PROPERTY BIGINT NOT NULL , 
     ID_SOURCE BIGINT , 
     ORDERNO BIGINT 
);

COMMENT ON TABLE EGPT_PROPERTY_OWNER IS 'Mapping table for egpt_propery and eg_citizen, contains property owner';

COMMENT ON COLUMN EGPT_PROPERTY_OWNER.OWNERID IS 'FK to EG_CITIZEN';

COMMENT ON COLUMN EGPT_PROPERTY_OWNER.ID_PROPERTY IS 'FK to EGPT_PROPERTY';

COMMENT ON COLUMN EGPT_PROPERTY_OWNER.ID_SOURCE IS 'Not used';


CREATE TABLE EGPT_PROPERTY_RECEIPTS 
( 
     ID BIGINT NOT NULL , 
     ID_BASIC_PROPERTY BIGINT , 
     BOOKNUMBER CHARACTER VARYING(64), 
     RCPT_NUMBER CHARACTER VARYING(64), 
     RCPT_DATE TIMESTAMP without time zone, 
     FROM_DATE TIMESTAMP without time zone, 
     TO_DATE TIMESTAMP without time zone, 
     RCPT_AMOUNT DOUBLE PRECISION 
);

COMMENT ON TABLE EGPT_PROPERTY_RECEIPTS IS 'Contains receipt information from legacy database';

COMMENT ON COLUMN EGPT_PROPERTY_RECEIPTS.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_PROPERTY_RECEIPTS.ID_BASIC_PROPERTY IS 'FK to EGPT_BASIC_PROPERTY';

COMMENT ON COLUMN EGPT_PROPERTY_RECEIPTS.BOOKNUMBER IS 'Book no';

COMMENT ON COLUMN EGPT_PROPERTY_RECEIPTS.RCPT_NUMBER IS 'receipt no';

COMMENT ON COLUMN EGPT_PROPERTY_RECEIPTS.RCPT_DATE IS 'receipt date';

COMMENT ON COLUMN EGPT_PROPERTY_RECEIPTS.FROM_DATE IS 'receipt from date';

COMMENT ON COLUMN EGPT_PROPERTY_RECEIPTS.TO_DATE IS 'receipt to date';

COMMENT ON COLUMN EGPT_PROPERTY_RECEIPTS.RCPT_AMOUNT IS 'receipt amount';

create sequence SEQ_EGPT_PROPERTY_RECEIPTS;


CREATE TABLE EGPT_PROPERTY_STATUS_VALUES 
( 
     ID BIGINT NOT NULL , 
     ID_STATUS BIGINT NOT NULL , 
     ID_BASIC_PROPERTY BIGINT NOT NULL , 
     REF_DATE TIMESTAMP without time zone, 
     REF_NUM CHARACTER VARYING(64), 
     REMARKS CHARACTER VARYING(1024), 
     IS_ACTIVE character(1), 
     MODIFIED_DATE TIMESTAMP without time zone, 
     CREATED_DATE TIMESTAMP without time zone, 
     CREATED_BY BIGINT NOT NULL , 
     REF_ID_BASIC BIGINT , 
     MODIFIED_BY BIGINT,
     EXTRA_FIELD1 CHARACTER VARYING(64), 
     EXTRA_FIELD2 CHARACTER VARYING(64), 
     EXTRA_FIELD3 CHARACTER VARYING(64)
);

COMMENT ON TABLE EGPT_PROPERTY_STATUS_VALUES IS 'Contains states of the property, holds top level transactions for property';

COMMENT ON COLUMN EGPT_PROPERTY_STATUS_VALUES.ID_STATUS IS 'FK to egw_status';

COMMENT ON COLUMN EGPT_PROPERTY_STATUS_VALUES.ID_BASIC_PROPERTY IS 'FK to egpt_basic_property';

COMMENT ON COLUMN EGPT_PROPERTY_STATUS_VALUES.REF_DATE IS 'Order Date';

COMMENT ON COLUMN EGPT_PROPERTY_STATUS_VALUES.REF_NUM IS 'Order No';

COMMENT ON COLUMN EGPT_PROPERTY_STATUS_VALUES.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_PROPERTY_STATUS_VALUES.EXTRA_FIELD1 IS 'Extra info specific to client';

COMMENT ON COLUMN EGPT_PROPERTY_STATUS_VALUES.EXTRA_FIELD2 IS 'Extra info specific to client';

COMMENT ON COLUMN EGPT_PROPERTY_STATUS_VALUES.EXTRA_FIELD3 IS 'Extra info specific to client';

COMMENT ON COLUMN EGPT_PROPERTY_STATUS_VALUES.REF_ID_BASIC IS 'FK to egpt_basic_property, used only for Bifurcation and Amalgation';

create sequence SEQ_EGPT_PROPERTY_STATUS_VALUES;


CREATE TABLE EGPT_PROPERTY_TYPE_MASTER 
( 
     ID BIGINT NOT NULL , 
     PROPERTY_TYPE CHARACTER VARYING(256) NOT NULL , 
     MODIFIED_DATE DATE NOT NULL , 
     TYPE_FACTOR BIGINT NOT NULL , 
     PROPERTY_TYPE_LOCAL CHARACTER VARYING(512) , 
     CODE CHARACTER VARYING(32), 
     CREATED_BY BIGINT , 
     MODIFIED_BY BIGINT , 
     CREATED_DATE TIMESTAMP without time zone, 
     ORDERNO BIGINT 
);

COMMENT ON TABLE EGPT_PROPERTY_TYPE_MASTER IS 'Master table for property type';

COMMENT ON COLUMN EGPT_PROPERTY_TYPE_MASTER.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_PROPERTY_TYPE_MASTER.PROPERTY_TYPE IS 'type of property';

COMMENT ON COLUMN EGPT_PROPERTY_TYPE_MASTER.TYPE_FACTOR IS 'Factor value for Property type';

COMMENT ON COLUMN EGPT_PROPERTY_TYPE_MASTER.PROPERTY_TYPE_LOCAL IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_TYPE_MASTER.CODE IS 'Code for proeprty type (internal use)';

COMMENT ON COLUMN EGPT_PROPERTY_TYPE_MASTER.ORDERNO IS 'Order no to display list';

create sequence SEQ_EGPT_PROPERTY_TYPE_MASTER;


CREATE TABLE EGPT_PROPERTY_USAGE_MASTER 
( 
     ID BIGINT NOT NULL , 
     USG_NAME CHARACTER VARYING(256) NOT NULL , 
     MODIFIED_DATE DATE NOT NULL , 
     USAGE_FACTOR DOUBLE PRECISION NOT NULL , 
     USG_NAME_LOCAL CHARACTER VARYING(512) , 
     CODE CHARACTER VARYING(16) NOT NULL , 
     ORDER_ID BIGINT , 
     FROM_DATE DATE NOT NULL , 
     TO_DATE TIMESTAMP without time zone, 
     IS_ENABLED BIGINT DEFAULT 1 NOT NULL , 
     CREATED_BY BIGINT , 
     MODIFIED_BY BIGINT , 
     CREATED_DATE DATE 
);

COMMENT ON TABLE EGPT_PROPERTY_USAGE_MASTER IS 'Master table for property usages';

COMMENT ON COLUMN EGPT_PROPERTY_USAGE_MASTER.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_PROPERTY_USAGE_MASTER.USG_NAME IS 'name of prpperty usage';

COMMENT ON COLUMN EGPT_PROPERTY_USAGE_MASTER.USAGE_FACTOR IS 'Usage Factor Value';

COMMENT ON COLUMN EGPT_PROPERTY_USAGE_MASTER.USG_NAME_LOCAL IS 'Not used';

COMMENT ON COLUMN EGPT_PROPERTY_USAGE_MASTER.CODE IS 'code for property usage (internal use)';

COMMENT ON COLUMN EGPT_PROPERTY_USAGE_MASTER.ORDER_ID IS 'Order no to display list';

COMMENT ON COLUMN EGPT_PROPERTY_USAGE_MASTER.FROM_DATE IS 'from date for usage factor validity';

COMMENT ON COLUMN EGPT_PROPERTY_USAGE_MASTER.TO_DATE IS 'To date for usage factor validity';

COMMENT ON COLUMN EGPT_PROPERTY_USAGE_MASTER.IS_ENABLED IS 'is this usage is enabled on system. 0 or 1';

create sequence SEQ_EGPT_PROPERTY_USAGE_MASTER;


CREATE TABLE EGPT_PTDEMAND 
( 
     ID_DEMAND BIGINT NOT NULL , 
     ID_PROPERTY BIGINT NOT NULL 
);

COMMENT ON TABLE EGPT_PTDEMAND IS 'Mappig table b/n egpt_property and eg_demand';

COMMENT ON COLUMN EGPT_PTDEMAND.ID_DEMAND IS 'FK to eg_demand';

COMMENT ON COLUMN EGPT_PTDEMAND.ID_PROPERTY IS 'FK to egpt_property';


CREATE TABLE EGPT_RECOVERY 
( 
     ID BIGINT NOT NULL , 
     ID_BILL BIGINT NOT NULL , 
     ID_BASIC_PROPERTY BIGINT NOT NULL , 
     ID_STATUS BIGINT NOT NULL , 
     ID_STATE BIGINT , 
     CREATED_BY BIGINT NOT NULL , 
     MODIFIED_BY BIGINT NOT NULL , 
     CREATED_DATE DATE NOT NULL , 
     MODIFIED_DATE DATE NOT NULL 
);

COMMENT ON TABLE EGPT_RECOVERY IS 'Main table for Recovery';

COMMENT ON COLUMN EGPT_RECOVERY.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_RECOVERY.ID_BILL IS 'FK to eg_bill';

COMMENT ON COLUMN EGPT_RECOVERY.ID_BASIC_PROPERTY IS 'FK to egpt_basic_property';

COMMENT ON COLUMN EGPT_RECOVERY.ID_STATUS IS 'FK to egw_status';

COMMENT ON COLUMN EGPT_RECOVERY.ID_STATE IS 'FK to eg_wf_states';

create sequence SEQ_EGPT_RECOVERY;


CREATE TABLE EGPT_RECOVERY_CEASE_NOTICE 
( 
     ID BIGINT NOT NULL , 
     ID_RECOVERY BIGINT NOT NULL , 
     ID_NOTICE BIGINT , 
     EXECUTION_DATE DATE NOT NULL , 
     CREATED_BY BIGINT NOT NULL , 
     MODIFIED_BY BIGINT NOT NULL , 
     CREATED_DATE DATE NOT NULL , 
     MODIFIED_DATE DATE NOT NULL , 
     REMARKS CHARACTER VARYING(1024) 
);

COMMENT ON TABLE EGPT_RECOVERY_CEASE_NOTICE IS 'Contains recovery cease details';

COMMENT ON COLUMN EGPT_RECOVERY_CEASE_NOTICE.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_RECOVERY_CEASE_NOTICE.ID_RECOVERY IS 'FK to egpt_recovery';

COMMENT ON COLUMN EGPT_RECOVERY_CEASE_NOTICE.ID_NOTICE IS 'FK to egpt_notice';

create sequence SEQ_EGPT_RECOVERY_CES_NOTICE;


CREATE TABLE EGPT_RECOVERY_INTMATION 
( 
     ID BIGINT NOT NULL , 
     ID_RECOVERY BIGINT NOT NULL , 
     ID_NOTICE BIGINT , 
     REMARKS CHARACTER VARYING(1024), 
     PAYMENT_DUE_DATE DATE NOT NULL , 
     CREATED_BY BIGINT NOT NULL , 
     MODIFIED_BY BIGINT NOT NULL , 
     CREATED_DATE DATE NOT NULL , 
     MODIFIED_DATE DATE NOT NULL 
);

COMMENT ON TABLE EGPT_RECOVERY_INTMATION IS 'contains recover intimation details';

COMMENT ON COLUMN EGPT_RECOVERY_INTMATION.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_RECOVERY_INTMATION.ID_RECOVERY IS 'FK to egpt_recovery';

COMMENT ON COLUMN EGPT_RECOVERY_INTMATION.ID_NOTICE IS 'FK to egpt_notice';

create sequence SEQ_EGPT_RECOVERY_INTMATION;


CREATE TABLE EGPT_RECOVERY_WARRANT 
( 
     ID BIGINT NOT NULL , 
     ID_RECOVERY BIGINT NOT NULL , 
     ID_NOTICE BIGINT , 
     REMARKS CHARACTER VARYING(1024), 
     CREATED_BY BIGINT NOT NULL , 
     MODIFIED_BY BIGINT NOT NULL , 
     CREATED_DATE DATE NOT NULL , 
     MODIFIED_DATE DATE NOT NULL 
);


COMMENT ON TABLE EGPT_RECOVERY_WARRANT IS 'Contains recovery warrant details';

COMMENT ON COLUMN EGPT_RECOVERY_WARRANT.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_RECOVERY_WARRANT.ID_RECOVERY IS 'FK to egpt_recovery';

COMMENT ON COLUMN EGPT_RECOVERY_WARRANT.ID_NOTICE IS 'FK to egpt_notice';

create sequence SEQ_EGPT_RECOVERY_WARRANT;


CREATE TABLE EGPT_RECOVERY_WARRANTFEE 
( 
     ID BIGINT NOT NULL , 
     ID_WARRANT BIGINT NOT NULL , 
     ID_DEMAND_REASON BIGINT NOT NULL , 
     AMOUNT DOUBLE PRECISION NOT NULL , 
     CREATED_BY BIGINT NOT NULL , 
     MODIFIED_BY BIGINT NOT NULL , 
     CREATED_DATE DATE NOT NULL , 
     MODIFIED_DATE DATE NOT NULL , 
     WARRANT_IDX BIGINT NOT NULL 
);

COMMENT ON TABLE EGPT_RECOVERY_WARRANTFEE IS 'Contains recovery warrant fee details';

COMMENT ON COLUMN EGPT_RECOVERY_WARRANTFEE.ID_WARRANT IS 'FK to EGPT_RECOVERY_WARRANT';

COMMENT ON COLUMN EGPT_RECOVERY_WARRANTFEE.ID_DEMAND_REASON IS 'FK to eg_demand_reason';

COMMENT ON COLUMN EGPT_RECOVERY_WARRANTFEE.WARRANT_IDX IS 'Warrant Fee List index';

create sequence SEQ_EGPT_RECOVERY_WARRANTFEE;


CREATE TABLE EGPT_RECOVERY_WARRANT_NOTICE 
( 
     ID BIGINT NOT NULL , 
     ID_RECOVERY BIGINT NOT NULL , 
     ID_NOTICE BIGINT , 
     REMARKS CHARACTER VARYING(1024), 
     WARRANT_RETURNBY_DATE DATE NOT NULL , 
     WARRANT_CC_LIST CHARACTER VARYING(1024), 
     CREATED_BY BIGINT NOT NULL , 
     MODIFIED_BY BIGINT NOT NULL , 
     CREATED_DATE DATE NOT NULL , 
     MODIFIED_DATE DATE NOT NULL 
);

COMMENT ON TABLE EGPT_RECOVERY_WARRANT_NOTICE IS 'Contains recovery warrant notice details';

COMMENT ON COLUMN EGPT_RECOVERY_WARRANT_NOTICE.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_RECOVERY_WARRANT_NOTICE.ID_RECOVERY IS 'FK to egpt_recovery';

COMMENT ON COLUMN EGPT_RECOVERY_WARRANT_NOTICE.ID_NOTICE IS 'FK to egpt_notice';

COMMENT ON COLUMN EGPT_RECOVERY_WARRANT_NOTICE.WARRANT_RETURNBY_DATE IS 'Warrant Return Date';

create sequence SEQ_EGPT_RECOVERY_WARRANT_NOTICE;


CREATE TABLE EGPT_SRC_OF_INFO 
( 
     ID BIGINT NOT NULL , 
     SOURCE_NAME CHARACTER VARYING(256) NOT NULL , 
     LASTUPDATEDTIMESTAMP DATE NOT NULL , 
     SOURCE_NAME_LOCAL CHARACTER VARYING(768) , 
     SRC_SHT_NAME CHARACTER VARYING(32) 
);

COMMENT ON TABLE EGPT_SRC_OF_INFO IS 'Master table for property source of info';

COMMENT ON COLUMN EGPT_SRC_OF_INFO.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_SRC_OF_INFO.SOURCE_NAME IS 'source of property name';

COMMENT ON COLUMN EGPT_SRC_OF_INFO.SOURCE_NAME_LOCAL IS 'Name locale';

COMMENT ON COLUMN EGPT_SRC_OF_INFO.SRC_SHT_NAME IS 'Code for Source of Info';

create sequence SEQ_EGPT_SRC_OF_INFO;


CREATE TABLE EGPT_STATUS 
( 
     ID BIGINT NOT NULL , 
     STATUS_NAME CHARACTER VARYING(256) NOT NULL , 
     created_date DATE NOT NULL , 
     IS_ACTIVE character(1), 
     CODE CHARACTER VARYING(32) 
);

COMMENT ON TABLE EGPT_STATUS IS 'Master table for property status';

COMMENT ON COLUMN EGPT_STATUS.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_STATUS.STATUS_NAME IS 'Property status name';

COMMENT ON COLUMN EGPT_STATUS.IS_ACTIVE IS 'is this status acitve. 0 or 1';

COMMENT ON COLUMN EGPT_STATUS.CODE IS 'property status code (internal use)';

create sequence SEQ_EGPT_STATUS;


CREATE TABLE EGPT_STRUC_CL 
( 
     ID BIGINT NOT NULL , 
     CONSTR_NUM BIGINT NOT NULL , 
     CONSTR_TYPE CHARACTER VARYING(128) NOT NULL , 
     CONSTR_DESCR CHARACTER VARYING(512), 
     CONSTR_FACTOR DOUBLE PRECISION , 
     MODIFIED_DATE DATE NOT NULL , 
     ID_INSTALLMENT BIGINT NOT NULL , 
     IS_HISTORY CHARACTER (1) DEFAULT 'N' , 
     CREATED_BY BIGINT , 
     FLOOR_NUM BIGINT , 
     CODE CHARACTER VARYING(16) NOT NULL , 
     ORDER_ID BIGINT , 
     FROM_DATE DATE NOT NULL , 
     TO_DATE TIMESTAMP without time zone, 
     CREATED_DATE TIMESTAMP without time zone, 
     MODIFIED_BY BIGINT 
);

COMMENT ON TABLE EGPT_STRUC_CL IS 'Master table for Structual classification';

COMMENT ON COLUMN EGPT_STRUC_CL.ID IS 'Primary Key';

COMMENT ON COLUMN EGPT_STRUC_CL.CONSTR_NUM IS 'Not used';

COMMENT ON COLUMN EGPT_STRUC_CL.CONSTR_TYPE IS 'Type construction';

COMMENT ON COLUMN EGPT_STRUC_CL.CONSTR_DESCR IS 'Construction type description';

COMMENT ON COLUMN EGPT_STRUC_CL.CONSTR_FACTOR IS 'Factor value for construction type';

COMMENT ON COLUMN EGPT_STRUC_CL.ID_INSTALLMENT IS 'Not used';

COMMENT ON COLUMN EGPT_STRUC_CL.FLOOR_NUM IS 'Not used';

COMMENT ON COLUMN EGPT_STRUC_CL.ORDER_ID IS 'Order no to display master';

COMMENT ON COLUMN EGPT_STRUC_CL.FROM_DATE IS 'From date of effective';

COMMENT ON COLUMN EGPT_STRUC_CL.TO_DATE IS 'To date of effective';

create sequence SEQ_EGPT_STRUC_CL;


CREATE TABLE EGPT_UNITAREACALC_DETAIL 
( 
     ID BIGINT NOT NULL , 
     ID_UNITTAX BIGINT NOT NULL , 
     TAXABLE_AREA BIGINT DEFAULT 0 NOT NULL , 
     MONTHLY_BASERENT BIGINT DEFAULT 0 NOT NULL , 
     MRV BIGINT DEFAULT 0 NOT NULL , 
     UNIT_OCCUPATION CHARACTER VARYING(200), 
     UNIT_USAGE CHARACTER VARYING(2), 
     BASE_RENT_SQRMTR DOUBLE PRECISION DEFAULT 0 NOT NULL , 
     MANUAL_ALV BIGINT DEFAULT 0 NOT NULL , 
     TENANT_RENT BIGINT DEFAULT 0 NOT NULL , 
     UNIT_IDENTIFIER CHARACTER VARYING(50), 
     FLOOR_NUMBER CHARACTER VARYING(15) 
);

create sequence SEQ_EGPT_UNITAREACALC_DETAIL;


CREATE TABLE EGPT_UNITCALC_DETAIL 
( 
     ID BIGINT NOT NULL , 
     ID_PROPERTY BIGINT NOT NULL , 
     UNIT_NUMBER BIGINT NOT NULL , 
     UNIT_AREA BIGINT NOT NULL , 
     OCCUPANCY_DATE DATE NOT NULL , 
     GUIDANCE_VALUE BIGINT DEFAULT 0 NOT NULL , 
     GUIDANCE_VAL_EFECTIVEDATE DATE NOT NULL , 
     INST_FROMDATE DATE NOT NULL , 
     UNIT_OCCUPATION CHARACTER VARYING(255) NOT NULL , 
     MONTHLY_RENT BIGINT DEFAULT 0 NOT NULL , 
     MONTHLY_RENT_TENANT BIGINT DEFAULT 0 NOT NULL , 
     ALV BIGINT DEFAULT 0 NOT NULL , 
     RESD_ALV BIGINT DEFAULT 0 NOT NULL , 
     NONRESD_ALV BIGINT DEFAULT 0 NOT NULL , 
     WATERTAX_ALV BIGINT DEFAULT 0 NOT NULL , 
     BIGBLDNG_ALV BIGINT DEFAULT 0 NOT NULL , 
     TAX_PAYABLE BIGINT DEFAULT 0 NOT NULL , 
     TAXDAYS BIGINT DEFAULT 0 NOT NULL , 
     FROM_DATE TIMESTAMP without time zone, 
     GENERAL_TAX BIGINT DEFAULT 0 NOT NULL , 
     GEN_TAX_FROMDATE TIMESTAMP without time zone, 
     SEWERAGE_TAX BIGINT DEFAULT 0 NOT NULL , 
     SEWERAGETAX_FROMDATE TIMESTAMP without time zone, 
     FIRE_TAX BIGINT DEFAULT 0 NOT NULL , 
     FIRETAX_FROMDATE TIMESTAMP without time zone, 
     LIGHT_TAX BIGINT DEFAULT 0 NOT NULL , 
     LIGHTTAX_FROMDATE TIMESTAMP without time zone, 
     WATER_TAX BIGINT DEFAULT 0 NOT NULL , 
     WATERTAX_FROMDATE TIMESTAMP without time zone, 
     EDUCESS_RESD BIGINT DEFAULT 0 NOT NULL , 
     EDURESD_FROMDATE TIMESTAMP without time zone, 
     EDUCESS_NONRESD BIGINT DEFAULT 0 NOT NULL , 
     EDUNONRESD_FROMDATE TIMESTAMP without time zone, 
     EGC BIGINT DEFAULT 0 NOT NULL , 
     EGC_FROMDATE TIMESTAMP without time zone, 
     BIGBLDNG_TAX BIGINT DEFAULT 0 NOT NULL , 
     BIGBLDNGTAX_FROMDATE TIMESTAMP without time zone, 
     CHQ_BOUNCE_PENALTY BIGINT DEFAULT 0 NOT NULL , 
     PENALTY_FINES BIGINT DEFAULT 0 NOT NULL , 
     CREATED_TIMESTAMP TIMESTAMP without time zone NOT NULL , 
     LASTUPDATED_TIMESTAMP TIMESTAMP without time zone NOT NULL , 
     SERVICE_CHARGE BIGINT DEFAULT 0 NOT NULL , 
     BUILDING_COST BIGINT DEFAULT 0 NOT NULL 
);

COMMENT ON TABLE EGPT_UNITCALC_DETAIL IS 'This table contains a row which gives the consolidated info of ALV and Annual Taxes';

create sequence SEQ_EGPT_UNITCALC_DETAIL;
