CREATE UNIQUE INDEX IDX_UNQ_PROPERTY_ID ON EGPT_BASIC_PROPERTY USING BTREE (PROPERTYID ASC);

ALTER TABLE ONLY EGPT_BASIC_PROPERTY 
    ADD CONSTRAINT PK_EGPT_BASIC_PROPERTY PRIMARY KEY (id);


CREATE INDEX IDX_CITIZENADDRESS_ADDRESSID ON EGPT_CITIZEN_ADDRESS USING BTREE (ID_ADDRESS ASC);

CREATE INDEX IDX_CITIZENADDRESS_CITIZENID ON EGPT_CITIZEN_ADDRESS USING BTREE (ID_CITIZEN ASC);


CREATE INDEX IDX_DMDCALC_IDDMD ON EGPT_DEMANDCALCULATIONS USING BTREE (ID_DEMAND ASC);

ALTER TABLE ONLY EGPT_DEMANDCALCULATIONS 
    ADD CONSTRAINT PK_EGPT_DEMANDCALCULATIONS PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_FLOORDEMANDCALC 
    ADD CONSTRAINT PK_EGPT_FLOORDEMANDCALC PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_FLOOR_DETAIL 
    ADD CONSTRAINT PK_EGPT_FLOOR_DETAIL_PK PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_HEARING
    ADD CONSTRAINT PK_EGPT_HEARING PRIMARY KEY (ID);

ALTER TABLE ONLY EGPT_HEARING 
    ADD CONSTRAINT UNQ_HEARINGNUMBER UNIQUE ( HEARINGNUMBER );


ALTER TABLE ONLY EGPT_INSPECTION 
    ADD CONSTRAINT PK_EGPT_INSPECTION PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_MSTR_BNDRY_CATEGORY 
    ADD CONSTRAINT PK_EGPT_MSTR_BNDRY_CATEGORY PRIMARY KEY (ID);


CREATE UNIQUE INDEX IDX_UNQ_EGPT_CAT_CATNAME ON EGPT_MSTR_CATEGORY USING BTREE (CATEGORY_NAME ASC);

ALTER TABLE ONLY EGPT_MSTR_CATEGORY 
    ADD CONSTRAINT PK_EGPT_CATEGORY PRIMARY KEY ( ID );


CREATE UNIQUE INDEX IDX_UNQ_MUTATION_CODE ON EGPT_MUTATION_MASTER USING BTREE (CODE ASC);
CREATE UNIQUE INDEX IDX_UNQ_MUTATION_ORDER_TYPE ON EGPT_MUTATION_MASTER USING BTREE (ORDER_ID ASC , TYPE ASC );

ALTER TABLE ONLY EGPT_MUTATION_MASTER 
    ADD CONSTRAINT PK_EGPT_MUTATION_MASTER PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_MUTATION_OWNER 
    ADD CONSTRAINT PK_EGPT_MUTATION_OWNER PRIMARY KEY ( ID );

ALTER TABLE ONLY EGPT_NOTICE 
    ADD CONSTRAINT PK_EGPT_NOTICE PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_NOTICE 
    ADD CONSTRAINT UNQ_NOTICENO UNIQUE ( NOTICENO );


CREATE UNIQUE INDEX IDX_UNQ_OBJECTIONNUMBER ON EGPT_OBJECTION USING BTREE ( OBJECTION_NUMBER ASC );

ALTER TABLE ONLY EGPT_OBJECTION 
    ADD CONSTRAINT PK_EGPT_OBJECTION PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_OCCUPATION_TYPE_MASTER 
    ADD CONSTRAINT PK_EGPT_OCCUPATION_TYPE_MASTER PRIMARY KEY ( ID );


CREATE INDEX IDX_PROP_INST ON EGPT_PROPERTY using BTREE ( 
     ID_BASIC_PROPERTY ASC , 
     ID_INSTALLMENT ASC , 
     STATUS ASC , 
     ID_SOURCE ASC 
);

ALTER TABLE ONLY EGPT_PROPERTY 
    ADD CONSTRAINT PK_EGPT_PROPERTY PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_PROPERTYID 
    ADD CONSTRAINT PK_EGPT_PROPERTYID PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_PROPERTY_ARREARS 
    ADD CONSTRAINT PK_EGPT_PROPERTY_ARREARS PRIMARY KEY ( ID );


CREATE INDEX IDX_PROPDET_PROPID ON EGPT_PROPERTY_DETAIL USING BTREE (ID_PROPERTY ASC);

ALTER TABLE ONLY EGPT_PROPERTY_DETAIL 
    ADD CONSTRAINT PK_EGPT_PROPERTY_DETAIL PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_PROPERTY_DOCS 
    ADD CONSTRAINT PK_EGPT_PROPERTY_DOCS PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_PROPERTY_MUTATION 
    ADD CONSTRAINT EGPT_PROPERTY_MUTATION_PK PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_PROPERTY_RECEIPTS 
    ADD CONSTRAINT PK_ID_PROP_RCPTS PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_PROPERTY_STATUS_VALUES 
    ADD CONSTRAINT PK_EGPT_PROPERTY_STATUS_VALUES PRIMARY KEY ( ID );


ALTER TABLE EGPT_PROPERTY_TYPE_MASTER 
    ADD CONSTRAINT PK_EGPT_PROPERTYTYPE_MASTER PRIMARY KEY ( ID );


CREATE UNIQUE INDEX IDX_UNIQUE_KEY_USAGENAME ON EGPT_PROPERTY_USAGE_MASTER USING BTREE (USG_NAME ASC);

ALTER TABLE ONLY EGPT_PROPERTY_USAGE_MASTER 
    ADD CONSTRAINT PK_EGPT_PROPERTY_USAGE_MASTER PRIMARY KEY ( ID );


CREATE UNIQUE INDEX IDX_UNQ_PTDEMAND ON EGPT_PTDEMAND USING BTREE (ID_DEMAND ASC , ID_PROPERTY ASC );

ALTER TABLE ONLY EGPT_RECOVERY 
    ADD CONSTRAINT PK_EGPT_RECOVERY PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_RECOVERY_CEASE_NOTICE 
    ADD CONSTRAINT PK_EGPT_SEIZURE_NOTICE PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_RECOVERY_INTMATION 
    ADD CONSTRAINT PK_EGPT_NOTICE_INT PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_RECOVERY_WARRANT 
    ADD CONSTRAINT PK_EGPT_WARRANT PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_RECOVERY_WARRANTFEE 
    ADD CONSTRAINT PK_EGPT_WARRANTFEE PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_RECOVERY_WARRANT_NOTICE 
    ADD CONSTRAINT PK_EGPT_WARRANT_NOTICE PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_SRC_OF_INFO 
    ADD CONSTRAINT PK_EGPT_SRC_OF_INFO PRIMARY KEY (ID);


CREATE UNIQUE INDEX IDX_UNIQUE_KEY_STATUS_NAME ON EGPT_STATUS USING BTREE (STATUS_NAME ASC);

ALTER TABLE ONLY EGPT_STATUS 
    ADD CONSTRAINT EGPT_STATUS_PK PRIMARY KEY ( ID );


CREATE UNIQUE INDEX IDX_UNQ_FLOOR_CODE ON EGPT_STRUC_CL USING BTREE (CODE ASC , FLOOR_NUM ASC );

ALTER TABLE ONLY EGPT_STRUC_CL 
    ADD CONSTRAINT PK_EGPT_STRUC_CL PRIMARY KEY ( ID );


CREATE INDEX IDX_PT_UACD_ID_UNTAX ON EGPT_UNITAREACALC_DETAIL USING BTREE (ID_UNITTAX ASC );

ALTER TABLE ONLY EGPT_UNITAREACALC_DETAIL 
    ADD CONSTRAINT PK_UNITAREATAXCALC_ID PRIMARY KEY ( ID );


CREATE INDEX IDX_PT_UCD_ID_PROP ON EGPT_UNITCALC_DETAIL USING BTREE (ID_PROPERTY ASC );

ALTER TABLE ONLY EGPT_UNITCALC_DETAIL 
    ADD CONSTRAINT PK_UNITTAXCALC_ID PRIMARY KEY ( ID );


ALTER TABLE ONLY EGPT_PROPERTY_DETAIL 
    ADD CONSTRAINT FK_EGPT_PROP_USG_PROP_DET FOREIGN KEY (ID_USG_MSTR) 
    REFERENCES EGPT_PROPERTY_USAGE_MASTER (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_STATUS_VALUES
    ADD CONSTRAINT FK_BASICPROP FOREIGN KEY (ID_BASIC_PROPERTY) 
    REFERENCES EGPT_BASIC_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_MUTATION 
    ADD CONSTRAINT FK_BASICPROPFORMUT FOREIGN KEY (ID_BASIC_PROPERTY) 
    REFERENCES EGPT_BASIC_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_BASIC_PROPERTY 
    ADD CONSTRAINT FK_BASIC_STATUS_ID FOREIGN KEY (STATUS) 
    REFERENCES EGPT_STATUS (ID) NOT DEFERRABLE;

ALTER TABLE ONLY EGPT_PROPERTY 
    ADD CONSTRAINT FK_BAS_PROP FOREIGN KEY (ID_BASIC_PROPERTY) 
    REFERENCES EGPT_BASIC_PROPERTY (ID) NOT DEFERRABLE;

ALTER TABLE ONLY EGPT_MSTR_BNDRY_CATEGORY 
    ADD CONSTRAINT FK_CATEGORY_BNDRY_CATEGORY FOREIGN KEY (ID_CATEGORY) 
    REFERENCES EGPT_MSTR_CATEGORY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_MSTR_CATEGORY 
    ADD CONSTRAINT FK_CATEGORY_STRUCT_CL FOREIGN KEY (ID_STRUCT_CL) 
    REFERENCES EGPT_STRUC_CL (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_FLOORDEMANDCALC 
    ADD CONSTRAINT FK_DMDCALC FOREIGN KEY (ID_DMDCALC) 
    REFERENCES EGPT_DEMANDCALCULATIONS (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PTDEMAND 
    ADD CONSTRAINT FK_EGPT_PROPERTY_ID FOREIGN KEY (ID_PROPERTY) 
    REFERENCES EGPT_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_FLOORDEMANDCALC 
    ADD CONSTRAINT FK_FLOORDET FOREIGN KEY (ID_FLOORDET) 
    REFERENCES EGPT_FLOOR_DETAIL (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_ARREARS 
    ADD CONSTRAINT FK_ID_BASIC_PROP FOREIGN KEY (ID_BASIC_PROPERTY) 
    REFERENCES EGPT_BASIC_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_RECEIPTS 
    ADD CONSTRAINT FK_ID_BASIC_RCPTS FOREIGN KEY (ID_BASIC_PROPERTY) 
    REFERENCES EGPT_BASIC_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_MUTATION_OWNER 
    ADD CONSTRAINT FK_ID FOREIGN KEY (ID_PROP_MUTATION) 
    REFERENCES EGPT_PROPERTY_MUTATION (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_STATUS_VALUES 
    ADD CONSTRAINT FK_ID_STSTUS FOREIGN KEY (ID_STATUS) 
    REFERENCES EGPT_STATUS (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_MSTR_CATEGORY 
    ADD CONSTRAINT FK_ID_USAGE FOREIGN KEY (ID_USAGE) 
    REFERENCES EGPT_PROPERTY_USAGE_MASTER (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_DETAIL 
    ADD CONSTRAINT FK_MUTAION_MASTER FOREIGN KEY (ID) 
    REFERENCES EGPT_MUTATION_MASTER (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_NOTICE 
    ADD CONSTRAINT FK_NOTICE_BASICPROPERTY FOREIGN KEY (ID_BASICPROPERTY) 
    REFERENCES EGPT_BASIC_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_RECOVERY_INTMATION 
    ADD CONSTRAINT FK_NOTICE_INT_NOTICE FOREIGN KEY (ID_NOTICE) 
    REFERENCES EGPT_NOTICE (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_RECOVERY_INTMATION 
    ADD CONSTRAINT FK_NOTICE_INT_RECOVERY FOREIGN KEY (ID_RECOVERY) 
    REFERENCES EGPT_RECOVERY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_RECOVERY_CEASE_NOTICE 
    ADD CONSTRAINT FK_NOTICE_SEIZURE_NOTICE FOREIGN KEY (ID_NOTICE) 
    REFERENCES EGPT_NOTICE (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_RECOVERY_WARRANT_NOTICE 
    ADD CONSTRAINT FK_NOTICE_WARRANT_NOTICE FOREIGN KEY (ID_NOTICE) 
    REFERENCES EGPT_NOTICE (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_OBJECTION 
    ADD CONSTRAINT FK_OBJECTION_BASICPROPERTY FOREIGN KEY (ID_BASICPROPERTY) 
    REFERENCES EGPT_BASIC_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_HEARING 
    ADD CONSTRAINT FK_OBJECTION_HEARING FOREIGN KEY (ID_OBJECTION) 
    REFERENCES EGPT_OBJECTION (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_INSPECTION 
    ADD CONSTRAINT FK_OBJECTION_INSPECTION FOREIGN KEY (ID_OBJECTION) 
    REFERENCES EGPT_OBJECTION (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_BASIC_PROPERTY 
    ADD CONSTRAINT FK_PROPERTYID_BASICPROP FOREIGN KEY (ID_PROPERTYID) 
    REFERENCES EGPT_PROPERTYID (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_OWNER 
    ADD CONSTRAINT FK_PROP_OWNER_PROPID FOREIGN KEY (ID_PROPERTY) 
    REFERENCES EGPT_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_OWNER 
    ADD CONSTRAINT FK_PROP_OWNER_SRC FOREIGN KEY (ID_SOURCE) 
    REFERENCES EGPT_SRC_OF_INFO (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_OCCUPATION_TYPE_MASTER 
    ADD CONSTRAINT FK_PROP_USG_MSTR FOREIGN KEY (ID_USG_MSTR) 
    REFERENCES EGPT_PROPERTY_USAGE_MASTER (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_RECOVERY 
    ADD CONSTRAINT FK_RECOVERY_BASICPROPERTY FOREIGN KEY (ID_BASIC_PROPERTY) 
    REFERENCES EGPT_BASIC_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_RECOVERY_CEASE_NOTICE 
    ADD CONSTRAINT FK_RECOVERY_SEIZURE_NOTICE FOREIGN KEY (ID_RECOVERY) 
    REFERENCES EGPT_RECOVERY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_RECOVERY_WARRANT_NOTICE 
    ADD CONSTRAINT FK_RECOVERY_WARRANT_NOTICE FOREIGN KEY (ID_RECOVERY) 
    REFERENCES EGPT_RECOVERY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_STATUS_VALUES 
    ADD CONSTRAINT FK_STATUS_REF_BASIC_IDR FOREIGN KEY (REF_ID_BASIC) 
    REFERENCES EGPT_BASIC_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_UNITAREACALC_DETAIL 
    ADD CONSTRAINT FK_UNITAREATAXCALC_ID_UNITTAX FOREIGN KEY (ID_UNITTAX) 
    REFERENCES EGPT_UNITCALC_DETAIL (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_UNITCALC_DETAIL 
    ADD CONSTRAINT FK_UNITTAXCALC_IDPROP FOREIGN KEY (ID_PROPERTY) 
    REFERENCES EGPT_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_FLOOR_DETAIL 
    ADD CONSTRAINT FK_UNIT_TYPE FOREIGN KEY (UNIT_TYPE) 
    REFERENCES EGPT_PROPERTY_TYPE_MASTER (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_RECOVERY_WARRANTFEE 
    ADD CONSTRAINT FK_WARRANTFEE_WARRANT FOREIGN KEY (ID_WARRANT) 
    REFERENCES EGPT_RECOVERY_WARRANT (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_RECOVERY_WARRANT 
    ADD CONSTRAINT FK_WARRANT_NOTICE FOREIGN KEY (ID_NOTICE) 
    REFERENCES EGPT_NOTICE (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_RECOVERY_WARRANT 
    ADD CONSTRAINT FK_WARRANT_RECOVERY FOREIGN KEY (ID_RECOVERY) 
    REFERENCES EGPT_RECOVERY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_DOCS 
    ADD CONSTRAINT FK_ID_BASIC_PROPERTY FOREIGN KEY (ID_BASIC_PROPERTY) 
    REFERENCES EGPT_BASIC_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_DETAIL 
    ADD CONSTRAINT FK_ID_OCCPN_MSTR FOREIGN KEY (ID_OCCPN_MSTR) 
    REFERENCES EGPT_OCCUPATION_TYPE_MASTER (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_DETAIL 
    ADD CONSTRAINT FK_ID_PROPERTYTYPEMASTER FOREIGN KEY (ID_PROPERTYTYPEMASTER) 
    REFERENCES EGPT_PROPERTY_TYPE_MASTER (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_MUTATION 
    ADD CONSTRAINT FK_MUTN_MSTR_PROP_MUTN FOREIGN KEY (ID) 
    REFERENCES EGPT_MUTATION_MASTER (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_FLOOR_DETAIL 
    ADD CONSTRAINT FK_OCC_TYP_MST_FLR_DET FOREIGN KEY (ID_OCCPN_MSTR) 
    REFERENCES EGPT_OCCUPATION_TYPE_MASTER (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY_DETAIL 
    ADD CONSTRAINT FK_PROPERTY_PROPERTY_DETAIL FOREIGN KEY (ID_PROPERTY) 
    REFERENCES EGPT_PROPERTY (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_FLOOR_DETAIL 
    ADD CONSTRAINT FK_PROP_FLR_DET FOREIGN KEY (ID_PROPERTY_DETAIL) 
    REFERENCES EGPT_PROPERTY_DETAIL (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_FLOOR_DETAIL 
    ADD CONSTRAINT FK_PRP_USG_MST_FLR_DET FOREIGN KEY (ID_USG_MSTR) 
    REFERENCES EGPT_PROPERTY_USAGE_MASTER (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_PROPERTY 
    ADD CONSTRAINT FK_SRC_OF_INFO_PROPERTY FOREIGN KEY ( ID_SOURCE) 
    REFERENCES EGPT_SRC_OF_INFO (ID) NOT DEFERRABLE;


ALTER TABLE ONLY EGPT_FLOOR_DETAIL 
    ADD CONSTRAINT FK_STR_CL_FLR_DET FOREIGN KEY (ID_STRUC_CL) 
    REFERENCES EGPT_STRUC_CL (ID) NOT DEFERRABLE;

