Insert into eg_action (ID,NAME,ENTITYID,TASKID,UPDATEDTIME,URL,QUERYPARAMS,URLORDERID,MODULE_ID,ORDER_NUMBER,DISPLAY_NAME,IS_ENABLED,ACTION_HELP_URL,CONTEXT_ROOT) values (nextval('seq_eg_action'),'CollectionIndexPage',null,null,current_timestamp,'/index.jsp',null,null,(select ID_MODULE from eg_module where MODULE_NAME ='Collection'),1,'Collection Index','0',null,'collection');
Insert into eg_action (ID,NAME,ENTITYID,TASKID,UPDATEDTIME,URL,QUERYPARAMS,URLORDERID,MODULE_ID,ORDER_NUMBER,DISPLAY_NAME,IS_ENABLED,ACTION_HELP_URL,CONTEXT_ROOT) values (nextval('seq_eg_action'),'ServiceCategory',null,null,current_timestamp,'/service/serviceCategory-newform.action',null,null,(select ID_MODULE from eg_module where MODULE_NAME ='Collection Master'),1,'Service Category','1',null,'collection');
Insert into eg_action (ID,NAME,ENTITYID,TASKID,UPDATEDTIME,URL,QUERYPARAMS,URLORDERID,MODULE_ID,ORDER_NUMBER,DISPLAY_NAME,IS_ENABLED,ACTION_HELP_URL,CONTEXT_ROOT) values (nextval('seq_eg_action'),'ServiceCategoryEdit',null,null,current_timestamp,'/service/serviceCategory-edit.action',null,null,(select ID_MODULE from eg_module where MODULE_NAME ='Collection Master'),1,'Edit Service Category','0',null,'collection');
Insert into eg_action (ID,NAME,ENTITYID,TASKID,UPDATEDTIME,URL,QUERYPARAMS,URLORDERID,MODULE_ID,ORDER_NUMBER,DISPLAY_NAME,IS_ENABLED,ACTION_HELP_URL,CONTEXT_ROOT) values (nextval('seq_eg_action'),'ServiceCategorySave',null,null,current_timestamp,'/service/serviceCategory-save.action',null,null,(select ID_MODULE from eg_module where MODULE_NAME ='Collection Master'),1,'Save Service Category','0',null,'collection');
Insert into eg_action (ID,NAME,ENTITYID,TASKID,UPDATEDTIME,URL,QUERYPARAMS,URLORDERID,MODULE_ID,ORDER_NUMBER,DISPLAY_NAME,IS_ENABLED,ACTION_HELP_URL,CONTEXT_ROOT) values (nextval('seq_eg_action'),'ServiceCategoryCreate',null,null,current_timestamp,'/service/serviceCategory-create.action',null,null,(select ID_MODULE from eg_module where MODULE_NAME ='Collection Master'),1,'Create Service Category','0',null,'collection');
Insert into eg_action (ID,NAME,ENTITYID,TASKID,UPDATEDTIME,URL,QUERYPARAMS,URLORDERID,MODULE_ID,ORDER_NUMBER,DISPLAY_NAME,IS_ENABLED,ACTION_HELP_URL,CONTEXT_ROOT) values (nextval('seq_eg_action'),'ServiceCategoryList',null,null,current_timestamp,'/service/serviceCategory-list.action',null,null,(select ID_MODULE from eg_module where MODULE_NAME ='Collection Master'),1,'List Service Category','0',null,'collection');
Insert into eg_action (ID,NAME,ENTITYID,TASKID,UPDATEDTIME,URL,QUERYPARAMS,URLORDERID,MODULE_ID,ORDER_NUMBER,DISPLAY_NAME,IS_ENABLED,ACTION_HELP_URL,CONTEXT_ROOT) values (nextval('seq_eg_action'),'ServiceDetails',null,null,current_timestamp,'/service/serviceDetails-newform.action',null,null,(select ID_MODULE from eg_module where MODULE_NAME ='Collection Master'),1,'ServiceDetails','1',null,'collection');
Insert into eg_action (ID,NAME,ENTITYID,TASKID,UPDATEDTIME,URL,QUERYPARAMS,URLORDERID,MODULE_ID,ORDER_NUMBER,DISPLAY_NAME,IS_ENABLED,ACTION_HELP_URL,CONTEXT_ROOT) values (nextval('seq_eg_action'),'ServiceDetailsList',null,null,current_timestamp,'/service/serviceDetails-listServices.action',null,null,(select ID_MODULE from eg_module where MODULE_NAME ='Collection Master'),1,'ServiceDetailsList','0',null,'collection');
Insert into eg_action (ID,NAME,ENTITYID,TASKID,UPDATEDTIME,URL,QUERYPARAMS,URLORDERID,MODULE_ID,ORDER_NUMBER,DISPLAY_NAME,IS_ENABLED,ACTION_HELP_URL,CONTEXT_ROOT) values (nextval('seq_eg_action'),'ServiceDetailsBeforeCreate',null,null,current_timestamp,'/service/serviceDetails-beforeCreate.action',null,null,(select ID_MODULE from eg_module where MODULE_NAME ='Collection Master'),1,'ServiceDetailsBeforeCreate','0',null,'collection');
Insert into eg_action (ID,NAME,ENTITYID,TASKID,UPDATEDTIME,URL,QUERYPARAMS,URLORDERID,MODULE_ID,ORDER_NUMBER,DISPLAY_NAME,IS_ENABLED,ACTION_HELP_URL,CONTEXT_ROOT) values (nextval('seq_eg_action'),'AjaxServiceCodeUniqueCheck',null,null,current_timestamp,'/service/serviceDetails-codeUniqueCheck.action',null,null,(select ID_MODULE from eg_module where MODULE_NAME ='Collection Master'),1,'AjaxServiceCodeUniqueCheck','0',null,'collection');




