
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Applicant Signature updated',now(),'Applicant Signature updated',1);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Application Forwarded to LS',to_date('19-06-14','DD-MM-RR'),'Application Forwarded to LS',2);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Application Registered',now(),'Registered',3);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Application Registered By Citizen',to_date('19-06-14','DD-MM-RR'),'CitizenRegisteredApplication',4);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Approved',now(),'Approved',5);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Cancelled',to_date('23-06-14','DD-MM-RR'),'CANCELLED',6);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Challan Amout is Collected',now(),'Challan Amout is Collected',7);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Challan Notice Sent to Citizen',now(),'Challan Notice Sent to Citizen',8);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Challan receipt created',now(),'Challan receipt created',9);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Considered',now(),'Considered',10);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','File Consideration Checked',now(),'File Consideration Checked',11);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Forwarded To EE',to_date('30-06-14','DD-MM-RR'),'FORWARDED_TO_EE',12);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','LP Reply received',now(),'LPREPLYRECEIVED',13);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','LP Reply received for LS',to_date('19-06-14','DD-MM-RR'),'LP Reply received for LS',14);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','LP Sent to Applicant',now(),'LP Sent to Applicant',15);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Letter To CMDA Created',to_date('27-03-15','DD-MM-RR'),'Letter To CMDA Created',16);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Letter To CMDA Created',to_date('27-03-15','DD-MM-RR'),'Letter To CMDA Created',17);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Letter To CMDA Sent',to_date('27-03-15','DD-MM-RR'),'Letter To CMDA Sent',18);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Letter To Party Created',now(),'Letter To Party Created',19);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Letter To Party Raised By LS',to_date('19-06-14','DD-MM-RR'),'Letter To Party Raised By LS',20);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Letter to CMDA Reply Received',to_date('27-03-15','DD-MM-RR'),'Letter to CMDA Reply Received',21);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Order Issued to Applicant',now(),'Order Issued to Applicant',22);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Order Prepared',now(),'Order Prepared',23);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','RevisedFeeInitiated',to_date('19-09-13','DD-MM-RR'),'RevisedFeeInitiated',24);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Site Inspected By LS',to_date('15-07-14','DD-MM-RR'),'Site Inspected By LS',25);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Site Inspected By LS',to_date('16-07-14','DD-MM-RR'),'Site Inspected By LS',26);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Site Inspection Scheduled',now(),'Site Inspection Scheduled',27);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Site Inspection Scheduled By LS',to_date('19-06-14','DD-MM-RR'),'Site Insp Scheduled By LS',28);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Unconsideration Approved',now(),'Unconsideration Approved',29);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Unconsidered Order Issued',now(),'Unconsidered Order Issued',30);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Unconsidered Order Prepared',now(),'Unconsidered Order Prepared',31);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'NEWBPAREGISTRATION','Under Unconsideration',now(),'Under Unconsideration',32);


--- building category

Insert into EGBPAEXTND_MSTR_BLDGCATEGORY   (ID, CODE, DESCRIPTION, CREATEDBY, MODIFIEDBY, MODIFIEDDATE, ISACTIVE)
 Values   (nextval('SEQ_EGBPAEXTND_MSTR_BUILDGCAT'), 'Residential', 'Residential', 1, 1, now(), '1');

Insert into EGBPAEXTND_MSTR_BLDGCATEGORY   (ID, CODE, DESCRIPTION, CREATEDBY, MODIFIEDBY, MODIFIEDDATE, ISACTIVE)
 Values   (nextval('SEQ_EGBPAEXTND_MSTR_BUILDGCAT'), 'Non Residential', 'Non Residential', 1, 1, now(), '1');




-------------- Building Usage

Insert into EGBPAEXTND_MSTR_BUILDINGUSAGE
   (ID, CODE, DESCRIPTION, CREATEDBY, MODIFIEDBY, MODIFIEDDATE, ISACTIVE)
 Values
   (nextval('SEQ_EGBPAEXTND_MSTR_BLGUSAGE'), 'RESD', 'Residential', 1, 1, now(), '1');
Insert into EGBPAEXTND_MSTR_BUILDINGUSAGE
   (ID, CODE, DESCRIPTION, CREATEDBY, MODIFIEDBY, MODIFIEDDATE, ISACTIVE)
 Values
   (nextval('SEQ_EGBPAEXTND_MSTR_BLGUSAGE'), 'COMMERCIAL', 'Commercial', 1, 1, now(), '1');
Insert into EGBPAEXTND_MSTR_BUILDINGUSAGE
   (ID, CODE, DESCRIPTION, CREATEDBY, MODIFIEDBY, MODIFIEDDATE, ISACTIVE)
 Values
   (nextval('SEQ_EGBPAEXTND_MSTR_BLGUSAGE'), 'INDUSTRIAL', 'Industrial', 1, 1, now(), '1');
Insert into EGBPAEXTND_MSTR_BUILDINGUSAGE
   (ID, CODE, DESCRIPTION, CREATEDBY, MODIFIEDBY, MODIFIEDDATE, ISACTIVE)
 Values
   (nextval('SEQ_EGBPAEXTND_MSTR_BLGUSAGE'), 'MULTIPLE', 'Multiple', 1, 1, now(), '1');
Insert into EGBPAEXTND_MSTR_BUILDINGUSAGE
   (ID, CODE, DESCRIPTION, CREATEDBY, MODIFIEDBY, MODIFIEDDATE, ISACTIVE)
 Values
   (nextval('SEQ_EGBPAEXTND_MSTR_BLGUSAGE'), 'INSTITUTIONAL', 'Institutional', 1, 1, now(), '1');
Insert into EGBPAEXTND_MSTR_BUILDINGUSAGE
   (ID, CODE, DESCRIPTION, CREATEDBY, MODIFIEDBY, MODIFIEDDATE, ISACTIVE)
 Values
   (nextval('SEQ_EGBPAEXTND_MSTR_BLGUSAGE'), 'NONRESD', 'Non - Residential',1, 1,now(), '1');


------------- Change of usage

Insert into EGBPAEXTND_MSTR_CHANGEOFUSAGE (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_CHANGEOFUSAGE'),'Agriculture',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_CHANGEOFUSAGE (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_CHANGEOFUSAGE'),'Industrial',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_CHANGEOFUSAGE (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_CHANGEOFUSAGE'),'Mixed Residential',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_CHANGEOFUSAGE (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_CHANGEOFUSAGE'),'Primary Residential',1, 1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_CHANGEOFUSAGE (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_CHANGEOFUSAGE'),'Institutional',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_CHANGEOFUSAGE (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_CHANGEOFUSAGE'),'Commercial',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_CHANGEOFUSAGE (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_CHANGEOFUSAGE'),'Open space Reservation',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_CHANGEOFUSAGE (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_CHANGEOFUSAGE'),'Others',1,1, now(), now(),'1');

---- construction stages

Insert into EGBPAEXTND_MSTR_CONST_STAGES
   (ID, CONST_STAGE, DESCRIPTION, CREATEDBY, MODIFIEDBY, MODIFIEDDATE)
 Values
   (nextval('SEQ_EGBPAEXTND_MSTR_CONST_STG'), 'NotStarted', 'NotStarted',1 , 1, now());

Insert into EGBPAEXTND_MSTR_CONST_STAGES
   (ID, CONST_STAGE, DESCRIPTION, CREATEDBY, MODIFIEDBY, MODIFIEDDATE)
 Values
   (nextval('SEQ_EGBPAEXTND_MSTR_CONST_STG'), 'Started', 'Started', 1, 1, now());


------- SurrouningBuilding Details ---------------

Insert into EGBPAEXTND_MSTR_SURNBLDGDTLS (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_SURDBLDGDTLS'),'Residential',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_SURNBLDGDTLS (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_SURDBLDGDTLS'),'Office',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_SURNBLDGDTLS (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_SURDBLDGDTLS'),'Shops',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_SURNBLDGDTLS (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_SURDBLDGDTLS'),'Commercial Establishment',1, 1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_SURNBLDGDTLS (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_SURDBLDGDTLS'),'Industries',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_SURNBLDGDTLS (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_SURDBLDGDTLS'),'Institution Activities',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_SURNBLDGDTLS (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_SURDBLDGDTLS'),'Agricultural',1,1, now(), now(),'1');

Insert into EGBPAEXTND_MSTR_SURNBLDGDTLS (ID,NAME,CREATEDBY,MODIFIEDBY,CREATEDDATE,MODIFIEDDATE,ISACTIVE)
values (nextval('SEQ_EGBPAEXTND_SURDBLDGDTLS'),'Others',1,1, now(), now(),'1');

-----appconfig values

INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'BPA_DEPARTMENT_CODE','BPA Department code ForVoucher','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'BPA_FUND_CODE','BPA Fund Code','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'BPA_FUNCTION_CODE','BPA Function code','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'SMS_NOTIFICATION_ALLOWED_BPA','Sending SMS and eMail Register BPA Applicant','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'EMAIL_NOTIFICATION_ALLOWED_BPA','Sending SMS and eMail Register BPA Applicant','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'DueCheckForProperty','Check dues for property before registration','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'OFFICIALS_DESIGLIST_SMS_BPA','Designations of the officials to whom SMS should be sent','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'IS_SATURDAY_HOLIDAY','Saturday is considered as holiday or no','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'IS_SECONDSATURDAY_HOLIDAY','Second Saturday is considered as holiday or no','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'IS_SUNDAY_HOLIDAY','Sunday is considered as holiday or no','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'HOLIDAYLIST_INCLUDED','Other Govt holidays in Holiday List are considered or no','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'AUTO_GENERATION_INSPCTIONDATES','Site Inspection dates are auto Generated','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'ROLELIST_BPA','List of roles for bpa','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'DocUPloadForSurveyor','List Of Servicetype code','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'BPA_FILE_UPLOAD_LOCATION','File upload location for bpa module','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'AUTODCR_FETCH_TYPE','Auto DCR Details Fetching type','BPA');
INSERT INTO eg_appconfig ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( nextval('SEQ_EG_APPCONFIG'), 'INSPECTION_DWELLUNIT_DATE','Show DwellingUnit in Inspection based on date','BPA');

INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='SENDEMAILFORESCALATION'),CURRENT_DATE, 'YES');


INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='BPA_DEPARTMENT_CODE' ),  CURRENT_DATE, 'W');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='BPA_FUND_CODE' ),  CURRENT_DATE, '1');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='BPA_FUNCTION_CODE' ),  CURRENT_DATE, '101200');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='SMS_NOTIFICATION_ALLOWED_BPA' ),  CURRENT_DATE, 'YES');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='EMAIL_NOTIFICATION_ALLOWED_BPA' ),  CURRENT_DATE, 'YES');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='DueCheckForProperty' ),  CURRENT_DATE, '0');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='OFFICIALS_DESIGLIST_SMS_BPA' ),  CURRENT_DATE, 'ASSISTANT EXECUTIVE ENGINEER');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='IS_SATURDAY_HOLIDAY' ),  CURRENT_DATE, 'YES');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='IS_SECONDSATURDAY_HOLIDAY' ),  CURRENT_DATE, 'YES');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='IS_SUNDAY_HOLIDAY' ),  CURRENT_DATE, 'YES');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='HOLIDAYLIST_INCLUDED' ),  CURRENT_DATE, 'YES');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='AUTO_GENERATION_INSPCTIONDATES' ),  CURRENT_DATE, 'YES');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='ROLELIST_BPA' ),  CURRENT_DATE, 'BPA AE,BPA EE,BPA AEE,BPA Assistant,BPA SE,BPA RDC');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='DocUPloadForSurveyor' ),  CURRENT_DATE, '10306');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='BPA_FILE_UPLOAD_LOCATION' ),  CURRENT_DATE, 'BPA/');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='AUTODCR_FETCH_TYPE' ),  CURRENT_DATE, 'REMOTESYSTEM');
INSERT INTO eg_appconfig_values ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES (nextval('SEQ_EG_APPCONFIG_VALUES'), (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='INSPECTION_DWELLUNIT_DATE' ),  CURRENT_DATE, '41921');

--Modules 
Insert into eg_module (ID_MODULE,MODULE_NAME,LASTUPDATEDTIMESTAMP,ISENABLED,MODULE_NAMELOCAL,BASEURL,PARENTID,MODULE_DESC,ORDER_NUM)
 values (nextval('SEQ_MODULEMASTER'),'BPA',current_date,1,null,'bpa',null,'Building Plan Approval',1);

Insert into eg_module (ID_MODULE,MODULE_NAME,LASTUPDATEDTIMESTAMP,ISENABLED,MODULE_NAMELOCAL,BASEURL,PARENTID,MODULE_DESC,ORDER_NUM)
 values (nextval('SEQ_MODULEMASTER'),'BpaRegistration',current_date,1,'Register BPA','bpa',
 (select ID_MODULE from eg_module where MODULE_DESC = 'Building Plan Approval'),'Registration',1);

 Insert into eg_module (ID_MODULE,MODULE_NAME,LASTUPDATEDTIMESTAMP,ISENABLED,MODULE_NAMELOCAL,BASEURL,PARENTID,MODULE_DESC,ORDER_NUM)
 values (nextval('SEQ_MODULEMASTER'),'BpaSearch',current_date,1,'BpaSearch','bpa',
 (select ID_MODULE from eg_module where MODULE_DESC = 'Building Plan Approval'),'Search',1);

 Insert into eg_module (ID_MODULE,MODULE_NAME,LASTUPDATEDTIMESTAMP,ISENABLED,MODULE_NAMELOCAL,BASEURL,PARENTID,MODULE_DESC,ORDER_NUM)
 values (nextval('SEQ_MODULEMASTER'),'BpaMasters',current_date,1,'BpaMasters','bpa',
 (select ID_MODULE from eg_module where MODULE_DESC = 'Building Plan Approval'),'Masters',1);

Insert into eg_module (ID_MODULE,MODULE_NAME,LASTUPDATEDTIMESTAMP,ISENABLED,MODULE_NAMELOCAL,BASEURL,PARENTID,MODULE_DESC,ORDER_NUM)
 values (nextval('SEQ_MODULEMASTER'),'BpaReports',current_date,1,'BpaReports','bpa',
 (select ID_MODULE from eg_module where MODULE_DESC = 'Building Plan Approval'),'Reports',1);
 
  Insert into eg_module (ID_MODULE,MODULE_NAME,LASTUPDATEDTIMESTAMP,ISENABLED,MODULE_NAMELOCAL,BASEURL,PARENTID,MODULE_DESC,ORDER_NUM)
 values (nextval('SEQ_MODULEMASTER'),'Bpa Fees Type Mapping',current_date,1,'Fees',null,
 (select ID_MODULE from eg_module where MODULE_NAME = 'BpaMasters'),'Fees',1);
 
Insert into eg_module (ID_MODULE,MODULE_NAME,LASTUPDATEDTIMESTAMP,ISENABLED,MODULE_NAMELOCAL,BASEURL,PARENTID,MODULE_DESC,ORDER_NUM)
 values (nextval('SEQ_MODULEMASTER'),'BpaCitizenPortal',current_date,0,'Building Plan Approval','bpa',
 null,'Bpa Citizen Portal',1);

 Insert into eg_module (ID_MODULE,MODULE_NAME,LASTUPDATEDTIMESTAMP,ISENABLED,MODULE_NAMELOCAL,BASEURL,PARENTID,MODULE_DESC,ORDER_NUM)
 values (nextval('SEQ_MODULEMASTER'),'Surveyor Master',current_date,1,'Surveyor Master','bpa',
 (select ID_MODULE from eg_module where  MODULE_NAME = 'BpaMasters'),'Surveyor Master',1);

 Insert into eg_module (ID_MODULE,MODULE_NAME,LASTUPDATEDTIMESTAMP,ISENABLED,MODULE_NAMELOCAL,BASEURL,PARENTID,MODULE_DESC,ORDER_NUM)
 values (nextval('SEQ_MODULEMASTER'),'BpaReportsCitizen',current_date,1,'BpaReportsCitizen','bpa',
 (select ID_MODULE from eg_module where  MODULE_NAME = 'BpaReports'),'Citizen',1);
