update eg_user set "type"='0' where "type"='SYSTEM';
update eg_user set "type"='1' where "type"='CITIZEN';
update eg_user set "type"='2' where "type"='EMPLOYEE';
alter table eg_user alter column "type" type numeric USING ("type"::numeric);
--alter table eg_user alter column "type" type varchar(50) USING ("type"::varchar);
--update eg_user set "type"='SYSTEM' where "type"='0';
--update eg_user set "type"='CITIZEN' where "type"='1';
--update eg_user set "type"='EMPLOYEE' where "type"='2';

alter table eg_citizen add column version bigint;
alter table eg_citizen add column lastModifiedDate timestamp;
alter table eg_citizen add column lastModifiedby bigint;
alter table eg_citizen add column createdDate timestamp;
alter table eg_citizen add column createdBy bigint;
update eg_citizen set version=1;
update eg_citizen set lastModifiedDate=now();
update eg_citizen set lastModifiedby=1;
update eg_citizen set createdDate=now();
update eg_citizen set createdBy=1;
--alter table eg_citizen drop column version;
--alter table eg_citizen drop column lastModifiedDate;
--alter table eg_citizen drop column lastModifiedby;
--alter table eg_citizen drop column createdDate;
--alter table eg_citizen drop column createdBy;

alter table egeis_employee add column version bigint;
alter table egeis_employee add column lastModifiedDate timestamp;
alter table egeis_employee add column lastModifiedby bigint;
alter table egeis_employee add column createdDate timestamp;
alter table egeis_employee add column createdBy bigint;
update egeis_employee set version=1;
update egeis_employee set lastModifiedDate=now();
update egeis_employee set lastModifiedby=1;
update egeis_employee set createdDate=now();
update egeis_employee set createdBy=1;
--alter table egeis_employee drop column version;
--alter table egeis_employee drop column lastModifiedDate;
--alter table egeis_employee drop column lastModifiedby;
--alter table egeis_employee drop column createdDate;
--alter table egeis_employee drop column createdBy;