ALTER TABLE egeis_employee ADD CONSTRAINT PK_EGEIS_EMPLOYEE_ID PRIMARY KEY(id);
UPDATE egeis_assignment SET employee=(SELECT id FROM eg_user WHERE username='narasappa') WHERE employee=1;
ALTER TABLE egeis_assignment ADD CONSTRAINT FK_EGEIS_ASSIGNMENT_EMPLOYEE FOREIGN KEY(employee) REFERENCES egeis_employee(id);
DROP TABLE egeis_service_history;
ALTER TABLE egasset_asset DROP CONSTRAINT fk_asset_preparedby;
ALTER TABLE egasset_asset ADD CONSTRAINT FK_ASSET_PREPAREDBY FOREIGN KEY(preparedby) REFERENCES egeis_employee(id);
ALTER TABLE egw_abstractestimate DROP CONSTRAINT fk_estimate_preparedby;
ALTER TABLE egw_abstractestimate ADD CONSTRAINT FK_ESTIMATE_PREPAREDBY FOREIGN KEY(preparedby) REFERENCES egeis_employee(id);
ALTER TABLE egw_workspackage DROP CONSTRAINT fk_workspackage_employee;
ALTER TABLE egw_workspackage ADD CONSTRAINT FK_WORKSPACKAGE_EMPLOYEE FOREIGN KEY(preparedby) REFERENCES egeis_employee(id);
ALTER TABLE egw_tender_response DROP CONSTRAINT fk_tenderresponse_employee;
ALTER TABLE egw_tender_response ADD CONSTRAINT FK_TENDERRESPONSE_EMPLOYEE FOREIGN KEY(prepared_by) REFERENCES egeis_employee(id);
ALTER TABLE egw_workorder DROP CONSTRAINT fk_wo_preparedby;
ALTER TABLE egw_workorder ADD CONSTRAINT FK_WO_PREPAREDBY FOREIGN KEY(preparedby) REFERENCES egeis_employee(id);
ALTER TABLE egw_workorder DROP CONSTRAINT fk_wo_eng_incharge1;
ALTER TABLE egw_workorder ADD CONSTRAINT FK_WO_ENG_INCHARGE1 FOREIGN KEY(engineer_incharge1) REFERENCES egeis_employee(id);
ALTER TABLE egw_workorder DROP CONSTRAINT fk_wo_eng_incharge2;
ALTER TABLE egw_workorder ADD CONSTRAINT FK_WO_ENG_INCHARGE2 FOREIGN KEY(engineer_incharge2) REFERENCES egeis_employee(id);
ALTER TABLE egw_mb_header DROP CONSTRAINT fk_mbh_preparedby;
ALTER TABLE egw_mb_header ADD CONSTRAINT FK_MBH_PREPAREDBY FOREIGN KEY(prepared_by) REFERENCES egeis_employee(id);
DROP TABLE eg_emp_assignment_prd;
DROP VIEW v_egeis_empdetails;
DROP VIEW eg_eis_employeeinfo;
