INSERT INTO EG_CITIZEN VALUES((select ID from eg_user where username='999999999'),'XXX',0);
ALTER TABLE EG_CITIZEN ALTER ID TYPE BIGINT;
ALTER TABLE EG_CITIZEN ADD PRIMARY KEY (ID);
ALTER TABLE EG_CITIZEN ADD CONSTRAINT FK_CITIZEN_USER FOREIGN KEY (ID) REFERENCES EG_USER (ID) MATCH FULL;