CREATE SEQUENCE seq_unit_rent_agreement_detail;
CREATE SEQUENCE seq_property_status_values;
ALTER table egpt_property ALTER column created_date type timestamp without time zone;
ALTER table egpt_property ALTER column modified_date type timestamp without time zone;
ALTER TABLE egpt_property ALTER COLUMN is_default_property type varchar;
ALTER TABLE egpt_property ALTER COLUMN status type varchar;
ALTER TABLE egpt_property ALTER COLUMN ischecked type varchar;
ALTER TABLE egpt_property ALTER COLUMN isexemptedfromtax type varchar;
ALTER TABLE egpt_basic_property ALTER COLUMN is_taxxml_migrated type varchar;
ALTER TABLE egpt_basic_property ALTER COLUMN is_bill_created type varchar;
ALTER TABLE egpt_basic_property ALTER COLUMN ismigrated type varchar;
ALTER TABLE egpt_basic_property ALTER COLUMN regd_doc_no type varchar(25);

ALTER TABLE egpt_property_detail DROP constraint fk_mutaion_master;
ALTER TABLE egpt_property_detail ADD constraint fk_mutation_master FOREIGN KEY (id_mutation)  REFERENCES egpt_mutation_master (id);

--rollback DROP SEQUENCE seq_unit_rent_agreement_detail;
--rollback DROP SEQUENCE seq_property_status_values;
--rollback ALTER TABLE egpt_property ALTER COLUMN created_date type date;
--rollback ALTER TABLE egpt_property ALTER COLUMN modified_date type date;
--rollback ALTER TABLE egpt_property ALTER COLUMN is_default_property type character(1);
--rollback ALTER TABLE egpt_property ALTER COLUMN status type character(1);
--rollback ALTER TABLE egpt_property ALTER COLUMN ischecked type character(1);
--rollback ALTER TABLE egpt_property ALTER COLUMN isexemptedfromtax type character(1);
--rollback ALTER TABLE egpt_basic_property ALTER COLUMN is_taxxml_migrated type character(1);
--rollback ALTER TABLE egpt_basic_property ALTER COLUMN is_bill_created type character(1);
--rollback ALTER TABLE egpt_basic_property ALTER COLUMN ismigrated type character(1);
--rollback ALTER TABLE egpt_basic_property ALTER COLUMN regd_doc_no type character(1);
--rollback ALTER TABLE egpt_property_detail ADD constraint fk_mutaion_master FOREIGN KEY(id_mutation) REFERENCES egpt_mutation_master (id);
--rollback ALTER TABLE egpt_property_detail DROP constraint fk_mutation_master;
