ALTER TABLE Scheme ALTER COLUMN isactive DROP DEFAULT;
ALTER TABLE Scheme ALTER isactive TYPE bool USING CASE WHEN isactive='0' THEN FALSE ELSE TRUE END;
ALTER TABLE Scheme ALTER COLUMN isactive SET DEFAULT FALSE;
