
Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate") values (nextval('seq_eg_action'),'CollectionBillingStub','/billingstub/collection.action','/collection/receipts/receipt-newform.action',(select ID from eg_module where NAME ='CreateCollectionBillBasedServices'),1,'Call Billing Stub','1','collection',0,1,current_timestamp,1,current_timestamp);

Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate") values (nextval('seq_eg_action'),'SaveReceipt','/receipts/receipt-save.action',null,(select ID from eg_module where NAME ='Collection Master'),1,'SaveReceipt','0','collection',0,1,current_timestamp,1,current_timestamp);

Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate") values (nextval('seq_eg_action'),'CreateReceipt','/receipts/receipt-newform.action',null,(select ID from eg_module where NAME ='Collection Master'),1,'CreateReceipt','0','collection',0,1,current_timestamp,1,current_timestamp);

Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate") values (nextval('seq_eg_action'),'ServiceDetailsSchemeList','/receipts/ajaxReceiptCreate-schemeList.jsp',null,(select ID from eg_module where NAME ='Collection Master'),1,'ServiceDetailsSchemeList','0','collection',0,1,current_timestamp,1,current_timestamp);

Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate") values (nextval('seq_eg_action'),'ServiceDetailsCreate','/service/serviceDetails-create.action',null,(select ID from eg_module where NAME ='Collection Master'),1,'ServiceDetailsCreate','0','collection',0,1,current_timestamp,1,current_timestamp);

