ALTER TABLE EG_SCRIPT RENAME SCRIPT_TYPE TO "type";
ALTER TABLE EG_SCRIPT RENAME CREATED_DATE to createddate;
ALTER TABLE EG_SCRIPT RENAME CREATED_BY to createdby;
ALTER TABLE EG_SCRIPT RENAME MODIFIED_DATE to lastmodifieddate;
ALTER TABLE EG_SCRIPT RENAME MODIFIED_BY to lastmodifiedby;
ALTER TABLE EG_SCRIPT RENAME START_DATE to startdate;
ALTER TABLE EG_SCRIPT RENAME end_date to enddate;
ALTER SEQUENCE EG_SCRIPT_SEQ RENAME TO  SEQ_EG_SCRIPT;