DROP SEQUENCE SEQ_EGPT_MSTR_CATEGORY;
DROP SEQUENCE SEQ_EGPT_MSTR_BNDRY_CATEGORY;

CREATE SEQUENCE SEQ_EGPT_MSTR_CATEGORY;
CREATE SEQUENCE SEQ_EGPT_MSTR_BNDRY_CATEGORY;



--rollback DROP SEQUENCE SEQ_EGPT_MSTR_CATEGORY;
--rollback DROP SEQUENCE SEQ_EGPT_MSTR_BNDRY_CATEGORY;
