--cleaning existing demand data
delete from egdm_depreciationmaster;
delete from eg_demand_reason_details where id_demand_reason in (select id from eg_demand_reason where id_demand_reason_master in (select id from eg_demand_reason_master where module=(select id from eg_module where name='Property Tax')));
delete from eg_demand_reason where id_demand_reason_master in (select id from eg_demand_reason_master where module=(select id from eg_module where name='Property Tax'));
delete from eg_demand_reason_master where module=(select id from eg_module where name='Property Tax');
delete from eg_installment_master where id_module=(select id from eg_module where name='Property Tax');
delete from egpt_mstr_bndry_category;
delete from egpt_mstr_category;

--eg_installment_master
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2004 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'I/04-05',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/10/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/10/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('31/03/2005 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'II/04-05',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2005 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2005 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2005 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'I/05-06',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/10/2005 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/10/2005 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('31/03/2006 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'II/05-06',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2006 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2006 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2006 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'I/06-07',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/10/2006 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/10/2006 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('31/03/2007 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'II/06-07',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2007 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2007 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2007 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'I/07-08',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/10/2007 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/10/2007 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('31/03/2008 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'II/07-08',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2008 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2008 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2008 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'I/08-09',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/10/2008 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/10/2008 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('31/03/2009 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'II/08-09',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2009 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2009 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2009 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'I/09-10',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/10/2009 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/10/2009 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('31/03/2010 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'II/09-10',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2010 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2010 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2010 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),to_date('31/03/2010 20:17:50','dd/MM/yyyy HH24:MI:SS'),'I/10-11',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/10/2010 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/10/2010 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('31/03/2011 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'II/10-11',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2011 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2011 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2011 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'I/11-12',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/10/2011 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/10/2011 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('31/03/2012 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'II/11-12',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2012 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2012 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2012 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'I/12-13',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/10/2012 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/10/2012 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('31/03/2013 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'II/12-13',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2013 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2013 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2013 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'I/13-14',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/10/2013 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/10/2013 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('31/03/2014 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'II/13-14',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2014 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2014 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2014 00:00:00','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'I/14-15',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/10/2014 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/10/2014 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('31/03/2015 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'II/14-15',null);
Insert into eg_installment_master (id,INSTALLMENT_NUM,INSTALLMENT_YEAR,START_DATE,END_DATE,ID_MODULE,LASTUPDATEDTIMESTAMP,DESCRIPTION,INSTALLMENT_TYPE) values (nextval('SEQ_EG_INSTALLMENT_MASTER'),1,to_date('01/04/2015 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2015 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('30/09/2015 23:59:59','dd/MM/yyyy HH24:MI:SS'),(select id from eg_module where name='Property Tax'),current_timestamp,'I/15-16',null);

--eg_demand_reason_master
INSERT INTO EG_DEMAND_REASON_MASTER ( ID, REASONMASTER, "category", ISDEBIT, module, CODE, "order", create_date, modified_date) VALUES(nextval('seq_eg_demand_reason_master'), 'General Tax', (select id from eg_reason_category where code='TAX'), 'N', (select id from eg_module where name='Property Tax'), 'GEN_TAX', 1, current_timestamp, current_timestamp);
INSERT INTO EG_DEMAND_REASON_MASTER ( ID, REASONMASTER, "category", ISDEBIT, module, CODE, "order", create_date, modified_date) VALUES(nextval('seq_eg_demand_reason_master'), 'Library Cess', (select id from eg_reason_category where code='TAX'), 'N', (select id from eg_module where name='Property Tax'), 'LIB_CESS', 2, current_timestamp, current_timestamp);
INSERT INTO EG_DEMAND_REASON_MASTER ( ID, REASONMASTER, "category", ISDEBIT, module, CODE, "order", create_date, modified_date) VALUES(nextval('seq_eg_demand_reason_master'), 'Education Cess', (select id from eg_reason_category where code='TAX'), 'N', (select id from eg_module where name='Property Tax'), 'EDU_CESS', 3, current_timestamp, current_timestamp);
INSERT INTO EG_DEMAND_REASON_MASTER ( ID, REASONMASTER, "category", ISDEBIT, module, CODE, "order", create_date, modified_date) VALUES(nextval('seq_eg_demand_reason_master'), 'Unauthorized Penalty', (select id from eg_reason_category where code='FINES'), 'N', (select id from eg_module where name='Property Tax'), 'UNAUTH_PENALTY', 4, current_timestamp, current_timestamp);

--eg_demand_reason
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) 
select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='General Tax' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, null from eg_installment_master inst where inst.id_module=(select id_module from eg_module where name='Property Tax');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) 
select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Library Cess' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, null from eg_installment_master inst where inst.id_module=(select id_module from eg_module where name='Property Tax');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) 
select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Education Cess' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, null from eg_installment_master inst where inst.id_module=(select id_module from eg_module where name='Property Tax');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) 
select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Unauthorized Penalty' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, null from eg_installment_master inst where inst.id_module=(select id_module from eg_module where name='Property Tax');


--eg_demand_reason_detail
Insert into eg_demand_reason_details (ID,ID_DEMAND_REASON,PERCENTAGE,FROM_DATE,TO_DATE,LOW_LIMIT,HIGH_LIMIT,CREATE_DATE,MODIFIED_DATE,FLAT_AMOUNT,IS_FLATAMNT_MAX) values (NEXTVAL('seq_eg_demand_reason_details'),(select id from eg_demand_reason where id_demand_reason_master = (select id from EG_DEMAND_REASON_MASTER where REASONMASTER = 'General Tax') and id_installment = (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Property Tax') and start_date = to_date('01/04/2015 00:00:00','dd/MM/yyyy HH24:MI:SS'))),20,to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2015 23:59:59','dd/MM/yyyy HH24:MI:SS'),1,9999999999,current_timestamp, current_timestamp,0,0);
Insert into eg_demand_reason_details (ID,ID_DEMAND_REASON,PERCENTAGE,FROM_DATE,TO_DATE,LOW_LIMIT,HIGH_LIMIT,CREATE_DATE,MODIFIED_DATE,FLAT_AMOUNT,IS_FLATAMNT_MAX) values (NEXTVAL('seq_eg_demand_reason_details'),(select id from eg_demand_reason where id_demand_reason_master = (select id from EG_DEMAND_REASON_MASTER where REASONMASTER = 'Library Cess') and id_installment = (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Property Tax') and start_date = to_date('01/04/2015 00:00:00','dd/MM/yyyy HH24:MI:SS'))),5,to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2015 23:59:59','dd/MM/yyyy HH24:MI:SS'),1,9999999999,current_timestamp, current_timestamp,0,0);
Insert into eg_demand_reason_details (ID,ID_DEMAND_REASON,PERCENTAGE,FROM_DATE,TO_DATE,LOW_LIMIT,HIGH_LIMIT,CREATE_DATE,MODIFIED_DATE,FLAT_AMOUNT,IS_FLATAMNT_MAX) values (NEXTVAL('seq_eg_demand_reason_details'),(select id from eg_demand_reason where id_demand_reason_master = (select id from EG_DEMAND_REASON_MASTER where REASONMASTER = 'Education Cess') and id_installment = (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Property Tax') and start_date = to_date('01/04/2015 00:00:00','dd/MM/yyyy HH24:MI:SS'))),5,to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2015 23:59:59','dd/MM/yyyy HH24:MI:SS'),1,9999999999,current_timestamp, current_timestamp,0,0);
Insert into eg_demand_reason_details (ID,ID_DEMAND_REASON,PERCENTAGE,FROM_DATE,TO_DATE,LOW_LIMIT,HIGH_LIMIT,CREATE_DATE,MODIFIED_DATE,FLAT_AMOUNT,IS_FLATAMNT_MAX) values (NEXTVAL('seq_eg_demand_reason_details'),(select id from eg_demand_reason where id_demand_reason_master = (select id from EG_DEMAND_REASON_MASTER where REASONMASTER = 'Unauthorized Penalty') and id_installment = (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Property Tax') and start_date = to_date('01/04/2015 00:00:00','dd/MM/yyyy HH24:MI:SS'))),50,to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2015 23:59:59','dd/MM/yyyy HH24:MI:SS'),1,9999999999,current_timestamp, current_timestamp,0,0);

--category
insert into egpt_mstr_category (id,category_name,category_amnt,id_installment,is_history,created_by,id_usage,from_date,to_date,modified_by,created_date,id_struct_cl) select NEXTVAL('SEQ_EGPT_MSTR_CATEGORY'), 'RESD',2, NULL, 'N', 1, id, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),  to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'),  1, current_timestamp, null from egpt_property_usage_master where usg_name='Residence';
insert into egpt_mstr_category (id,category_name,category_amnt,id_installment,is_history,created_by,id_usage,from_date,to_date,modified_by,created_date,id_struct_cl) select NEXTVAL('SEQ_EGPT_MSTR_CATEGORY'), 'NR-'||code,4, NULL, 'N', 1, id, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),  to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'),  1, current_timestamp, null from egpt_property_usage_master where usg_name!='Residence';
--boundary category
insert into egpt_mstr_bndry_category (id, id_bndry, id_category, modified_date, from_date, to_date, created_by, modified_by, created_date) select NEXTVAL('SEQ_EGPT_MSTR_BNDRY_CATEGORY'), (select id from eg_boundary where name = 'Zone-1' and boundarytype = (select id from eg_boundary_type where name = 'Zone')), id, current_timestamp, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'), to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'), 1, 1, current_timestamp from egpt_mstr_category where CATEGORY_NAME = 'RESD';
insert into egpt_mstr_bndry_category (id, id_bndry, id_category, modified_date, from_date, to_date, created_by, modified_by, created_date) select NEXTVAL('SEQ_EGPT_MSTR_BNDRY_CATEGORY'), (select id from eg_boundary where name = 'Zone-1' and boundarytype = (select id from eg_boundary_type where name = 'Zone')), id, current_timestamp, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'), to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'), 1, 1, current_timestamp from egpt_mstr_category where CATEGORY_NAME in (select 'NR-'||code from egpt_property_usage_master where usg_name!='Residence');
insert into egpt_mstr_bndry_category (id, id_bndry, id_category, modified_date, from_date, to_date, created_by, modified_by, created_date) select NEXTVAL('SEQ_EGPT_MSTR_BNDRY_CATEGORY'), (select id from eg_boundary where name = 'Zone-2' and boundarytype = (select id from eg_boundary_type where name = 'Zone')), id, current_timestamp, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'), to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'), 1, 1, current_timestamp from egpt_mstr_category where CATEGORY_NAME = 'RESD';
insert into egpt_mstr_bndry_category (id, id_bndry, id_category, modified_date, from_date, to_date, created_by, modified_by, created_date) select NEXTVAL('SEQ_EGPT_MSTR_BNDRY_CATEGORY'), (select id from eg_boundary where name = 'Zone-2' and boundarytype = (select id from eg_boundary_type where name = 'Zone')), id, current_timestamp, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'), to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'), 1, 1, current_timestamp from egpt_mstr_category where CATEGORY_NAME in (select 'NR-'||code from egpt_property_usage_master where usg_name!='Residence');
insert into egpt_mstr_bndry_category (id, id_bndry, id_category, modified_date, from_date, to_date, created_by, modified_by, created_date) select NEXTVAL('SEQ_EGPT_MSTR_BNDRY_CATEGORY'), (select id from eg_boundary where name = 'Zone-3' and boundarytype = (select id from eg_boundary_type where name = 'Zone')), id, current_timestamp, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'), to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'), 1, 1, current_timestamp from egpt_mstr_category where CATEGORY_NAME = 'RESD';
insert into egpt_mstr_bndry_category (id, id_bndry, id_category, modified_date, from_date, to_date, created_by, modified_by, created_date) select NEXTVAL('SEQ_EGPT_MSTR_BNDRY_CATEGORY'), (select id from eg_boundary where name = 'Zone-3' and boundarytype = (select id from eg_boundary_type where name = 'Zone')), id, current_timestamp, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'), to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'), 1, 1, current_timestamp from egpt_mstr_category where CATEGORY_NAME in (select 'NR-'||code from egpt_property_usage_master where usg_name!='Residence');
insert into egpt_mstr_bndry_category (id, id_bndry, id_category, modified_date, from_date, to_date, created_by, modified_by, created_date) select NEXTVAL('SEQ_EGPT_MSTR_BNDRY_CATEGORY'), (select id from eg_boundary where name = 'Zone-4' and boundarytype = (select id from eg_boundary_type where name = 'Zone')), id, current_timestamp, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'), to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'), 1, 1, current_timestamp from egpt_mstr_category where CATEGORY_NAME = 'RESD';
insert into egpt_mstr_bndry_category (id, id_bndry, id_category, modified_date, from_date, to_date, created_by, modified_by, created_date) select NEXTVAL('SEQ_EGPT_MSTR_BNDRY_CATEGORY'), (select id from eg_boundary where name = 'Zone-4' and boundarytype = (select id from eg_boundary_type where name = 'Zone')), id, current_timestamp, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'), to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'), 1, 1, current_timestamp from egpt_mstr_category where CATEGORY_NAME in (select 'NR-'||code from egpt_property_usage_master where usg_name!='Residence');

--depreciation
INSERT INTO egdm_depreciationmaster (ID, YEAR, DEPRECIATION_PCT, MODULE, lastmodifieddate, INSTALLMENT, IS_HISTORY, USERID, depreciation_name, depreciation_type, from_date, to_date) VALUES (NEXTVAL('SEQ_EGDM_DEPRECIATIONMASTER'),25,10, (select ID from EG_MODULE where name = 'Property Tax'),current_timestamp,(SELECT id FROM eg_installment_master WHERE start_date <= current_timestamp AND end_date  >= current_timestamp AND id_module = (SELECT id FROM eg_module WHERE name='Property Tax')),'N',1, '0-25', null, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'), to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'));

INSERT INTO egdm_depreciationmaster (ID, YEAR, DEPRECIATION_PCT, MODULE, lastmodifieddate, INSTALLMENT, IS_HISTORY, USERID, depreciation_name, depreciation_type, from_date, to_date) VALUES (NEXTVAL('SEQ_EGDM_DEPRECIATIONMASTER'),25,20, (select ID from EG_MODULE where name = 'Property Tax'),current_timestamp,(SELECT id FROM eg_installment_master WHERE start_date <= current_timestamp AND end_date  >= current_timestamp AND id_module = (SELECT id FROM eg_module WHERE name='Property Tax')),'N',1, '26-40', null, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'), to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'));

INSERT INTO egdm_depreciationmaster (ID, YEAR, DEPRECIATION_PCT, MODULE, lastmodifieddate, INSTALLMENT, IS_HISTORY, USERID, depreciation_name, depreciation_type, from_date, to_date) VALUES (NEXTVAL('SEQ_EGDM_DEPRECIATIONMASTER'),25,30, (select ID from EG_MODULE where name = 'Property Tax'),current_timestamp,(SELECT id FROM eg_installment_master WHERE start_date <= current_timestamp AND end_date  >= current_timestamp AND id_module = (SELECT id FROM eg_module WHERE name='Property Tax')),'N',1, 'Above 40', null, to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'), to_date('31/03/2099 23:59:59','dd/MM/yyyy HH24:MI:SS'));
