ALTER TABLE EGPT_MUTATION_OWNER RENAME TO EGPT_MUTATION_TRANSFEROR;

CREATE TABLE EGPT_MUTATION_TRANSFEREE (
MUTATION numeric,
TRANSFEREE numeric
);

CREATE TABLE egpt_document_files(
document numeric,
filestore numeric
);

ALTER TABLE EGPT_PROPERTY_MUTATION RENAME CREATEBY TO CREATEDBY;
ALTER TABLE EGPT_PROPERTY_MUTATION ADD COLUMN STATE_ID numeric;
ALTER TABLE EGPT_PROPERTY_MUTATION DROP COLUMN feepayable;
ALTER TABLE EGPT_PROPERTY_MUTATION ADD COLUMN feepayable boolean;
ALTER TABLE egpt_property_mutation DROP CONSTRAINT fk_mutn_mstr_prop_mutn;
ALTER TABLE eg_filestoremap ALTER COLUMN contenttype TYPE varchar(100);
ALTER TABLE EGPT_PROPERTY_OWNER_INFO ALTER basicproperty DROP NOT NULL;