--demand reason master
INSERT INTO EG_DEMAND_REASON_MASTER ( ID, REASONMASTER, "category", ISDEBIT, module, CODE, "order", create_date, modified_date) VALUES(nextval('seq_eg_demand_reason_master'), 'Sewerage Tax', (select id from eg_reason_category where code='TAX'), 'N', (select id from eg_module where name='Property Tax'), 'SEW_TAX', 3, current_timestamp, current_timestamp);
INSERT INTO EG_DEMAND_REASON_MASTER ( ID, REASONMASTER, "category", ISDEBIT, module, CODE, "order", create_date, modified_date) VALUES(nextval('seq_eg_demand_reason_master'), 'Vacant Land Tax', (select id from eg_reason_category where code='FINES'), 'N', (select id from eg_module where name='Property Tax'), 'VAC_LAND_TAX', 4, current_timestamp, current_timestamp);
INSERT INTO EG_DEMAND_REASON_MASTER ( ID, REASONMASTER, "category", ISDEBIT, module, CODE, "order", create_date, modified_date) VALUES(nextval('seq_eg_demand_reason_master'), 'Public Service Charges', (select id from eg_reason_category where code='FINES'), 'N', (select id from eg_module where name='Property Tax'), 'PUB_SER_CHRG', 4, current_timestamp, current_timestamp);

--demand reason
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) 
select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Sewerage Tax' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where name='Receivables for Property Taxes- Arrears') from eg_installment_master inst where inst.id_module=(select id_module from eg_module where name='Property Tax');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) 
select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Vacant Land Tax' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where name='Receivables for Property Taxes- Arrears') from eg_installment_master inst where inst.id_module=(select id_module from eg_module where name='Property Tax');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) 
select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Public Service Charges' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where name='Receivables for Property Taxes- Arrears') from eg_installment_master inst where inst.id_module=(select id_module from eg_module where name='Property Tax');

--reason details
Insert into eg_demand_reason_details (ID,ID_DEMAND_REASON,PERCENTAGE,FROM_DATE,TO_DATE,LOW_LIMIT,HIGH_LIMIT,CREATE_DATE,MODIFIED_DATE,FLAT_AMOUNT,IS_FLATAMNT_MAX) values (NEXTVAL('seq_eg_demand_reason_details'),(select id from eg_demand_reason where id_demand_reason_master = (select id from EG_DEMAND_REASON_MASTER where REASONMASTER = 'Vacant Land Tax') and id_installment = (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Property Tax') and start_date = to_date('01/04/2015 00:00:00','dd/MM/yyyy HH24:MI:SS'))),0.5,to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2015 23:59:59','dd/MM/yyyy HH24:MI:SS'),1,9999999999,current_timestamp, current_timestamp,0,0);

Insert into eg_demand_reason_details (ID,ID_DEMAND_REASON,PERCENTAGE,FROM_DATE,TO_DATE,LOW_LIMIT,HIGH_LIMIT,CREATE_DATE,MODIFIED_DATE,FLAT_AMOUNT,IS_FLATAMNT_MAX) values (NEXTVAL('seq_eg_demand_reason_details'),(select id from eg_demand_reason where id_demand_reason_master = (select id from EG_DEMAND_REASON_MASTER where REASONMASTER = 'Sewerage Tax') and id_installment = (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Property Tax') and start_date = to_date('01/04/2015 00:00:00','dd/MM/yyyy HH24:MI:SS'))),0.5,to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2015 23:59:59','dd/MM/yyyy HH24:MI:SS'),1,9999999999,current_timestamp, current_timestamp,0,0);

Insert into eg_demand_reason_details (ID,ID_DEMAND_REASON,PERCENTAGE,FROM_DATE,TO_DATE,LOW_LIMIT,HIGH_LIMIT,CREATE_DATE,MODIFIED_DATE,FLAT_AMOUNT,IS_FLATAMNT_MAX) values (NEXTVAL('seq_eg_demand_reason_details'),(select id from eg_demand_reason where id_demand_reason_master = (select id from EG_DEMAND_REASON_MASTER where REASONMASTER = 'Public Service Charges') and id_installment = (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Property Tax') and start_date = to_date('01/04/2015 00:00:00','dd/MM/yyyy HH24:MI:SS'))),0,to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2015 23:59:59','dd/MM/yyyy HH24:MI:SS'),1,1000,current_timestamp, current_timestamp,30,0);

Insert into eg_demand_reason_details (ID,ID_DEMAND_REASON,PERCENTAGE,FROM_DATE,TO_DATE,LOW_LIMIT,HIGH_LIMIT,CREATE_DATE,MODIFIED_DATE,FLAT_AMOUNT,IS_FLATAMNT_MAX) values (NEXTVAL('seq_eg_demand_reason_details'),(select id from eg_demand_reason where id_demand_reason_master = (select id from EG_DEMAND_REASON_MASTER where REASONMASTER = 'Public Service Charges') and id_installment = (select id from EG_INSTALLMENT_MASTER where ID_MODULE = (select id from EG_MODULE where name = 'Property Tax') and start_date = to_date('01/04/2015 00:00:00','dd/MM/yyyy HH24:MI:SS'))),0,to_date('01/04/2004 00:00:00','dd/MM/yyyy HH24:MI:SS'),to_date('01/04/2015 23:59:59','dd/MM/yyyy HH24:MI:SS'),1000,9999999999,current_timestamp, current_timestamp,60,0);

--property types
update EGPT_PROPERTY_TYPE_MASTER set property_type='Vacant Land', code='VAC_LAND' where code='OPEN_PLOT';
update EGPT_PROPERTY_TYPE_MASTER set property_type='Private', code='PRIVATE' where code='RESIDENTIAL';
update EGPT_PROPERTY_TYPE_MASTER set property_type='State Government', code='STATE_GOVT' where code='NON_RESD';
update EGPT_PROPERTY_TYPE_MASTER set property_type='Central Government 33.5%', code='CENTRAL_GOVT_33.5' where code='STATE_GOVT';
update EGPT_PROPERTY_TYPE_MASTER set property_type='Central Government 50%', code='CENTRAL_GOVT_50' where code='CENTRAL_GOVT';
update EGPT_PROPERTY_TYPE_MASTER set property_type='Central Government 70%', code='CENTRAL_GOVT_70' where code='OP-RESD-NONRESD';

--actions and role mapping
INSERT INTO EG_ACTION(ID, NAME, URL, QUERYPARAMS, PARENTMODULE, ORDERNUMBER,DISPLAYNAME, ENABLED, CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE) Values (nextval('SEQ_EG_ACTION'), 'Populate Categories by Property Type','/common/ajaxCommon-propTypeCategoryByPropType.action', NULL, (SELECT ID FROM EG_MODULE WHERE NAME = 'Ptis Revision Petition'),NULL, 'Populate Categories by Property Type',false,'ptis',0,1,now(),1,now());

INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) values ((select id from eg_role where name LIKE 'ULB Operator'),(select id FROM eg_action WHERE NAME = 'Populate Categories by Property Type' and CONTEXTROOT='ptis'));

--delete from eg_demand_reason_details where id_demand_reason in (select id from eg_demand_reason where id_demand_reason_master in (select id from eg_demand_reason_master where reasonmaster in ('Sewerage Tax','Vacant Land Tax') and id_module=(select id_module from eg_module where name='Property Tax')));
--delete from eg_demand_reason where id_demand_reason_master in (select id from eg_demand_reason_master where reasonmaster in ('Sewerage Tax','Vacant Land Tax') and id_module=(select id_module from eg_module where name='Property Tax'));
--delete from eg_demand_reason where id_demand_reason_master in (select id from eg_demand_reason_master where reasonmaster in ('Sewerage Tax','Vacant Land Tax') and id_module=(select id_module from eg_module where name='Property Tax'));
