Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Rent, Rates And Taxes','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Electricity Charges','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Water Charges','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Security Expenses','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Communication Expenses','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Books And Periodicals','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Printing And Stationery','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Postage And Telegrams','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Traveling And Conveyance','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Insurance','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Audit Fees','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Legal Expenses','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Professional And Other Fees','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'E-Governance','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Advertisement And publicity','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Hospitality Expenses','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Membership And Subscription','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Others','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Power And Fuel','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Education Expenses','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Garden Expenses','Expense');
Insert into EG_BILL_SUBTYPE (ID,NAME,EXPENDITURE_TYPE) values (nextval('SEQ_EG_BILL_SUBTYPE'),'Privatization','Expense');
