ALTER TABLE EGWTR_CONNECTION DROP COLUMN EMAIL;
ALTER TABLE EGWTR_CONNECTION DROP COLUMN MOBILENUMBER;

--rollback ALTER TABLE EGWTR_CONNECTION ADD COLUMN MOBILENUMBER CHARACTER VARYING(15);
--rollback ALTER TABLE EGWTR_CONNECTION ADD COLUMN EMAIL CHARACTER VARYING(100);