INSERT INTO EGF_INSTRUMENTACCOUNTCODES (ID, TYPEID, GLCODEID, CREATEDBY, LASTMODIFIEDBY, CREATEDDATE, LASTMODIFIEDDATE) VALUES (nextval('SEQ_EGF_INSTRUMENTACCOUNTCODES'),(SELECT ID FROM EGF_INSTRUMENTTYPE WHERE TYPE='cash'),
(SELECT ID FROM CHARTOFACCOUNTS WHERE GLCODE='4501001'),
(select id from eg_user where username='egovernments'),(select id from eg_user where username='egovernments'),
current_timestamp,current_timestamp);

INSERT INTO EGF_INSTRUMENTACCOUNTCODES (ID, TYPEID, GLCODEID, CREATEDBY, LASTMODIFIEDBY, CREATEDDATE, LASTMODIFIEDDATE) VALUES (nextval('SEQ_EGF_INSTRUMENTACCOUNTCODES'),(SELECT ID FROM EGF_INSTRUMENTTYPE WHERE TYPE='cheque'),
(SELECT ID FROM CHARTOFACCOUNTS WHERE GLCODE='4501051'),
(select id from eg_user where username='egovernments'),(select id from eg_user where username='egovernments'),
current_timestamp,current_timestamp);

INSERT INTO EGF_INSTRUMENTACCOUNTCODES (ID, TYPEID, GLCODEID, CREATEDBY, LASTMODIFIEDBY, CREATEDDATE, LASTMODIFIEDDATE) VALUES (nextval('SEQ_EGF_INSTRUMENTACCOUNTCODES'),(SELECT ID FROM EGF_INSTRUMENTTYPE WHERE TYPE='dd'),
(SELECT ID FROM CHARTOFACCOUNTS WHERE GLCODE='4501051'),
(select id from eg_user where username='egovernments'),(select id from eg_user where username='egovernments'),
current_timestamp,current_timestamp);

INSERT INTO EGF_INSTRUMENTACCOUNTCODES (ID, TYPEID, GLCODEID, CREATEDBY, LASTMODIFIEDBY, CREATEDDATE, LASTMODIFIEDDATE) VALUES (nextval('SEQ_EGF_INSTRUMENTACCOUNTCODES'),(SELECT ID FROM EGF_INSTRUMENTTYPE WHERE TYPE='online'),
(SELECT ID FROM CHARTOFACCOUNTS WHERE GLCODE='4501002'),
(select id from eg_user where username='egovernments'),(select id from eg_user where username='egovernments'),
current_timestamp,current_timestamp);
