DELETE from EGF_INSTRUMENTTYPE;
INSERT INTO EGF_INSTRUMENTTYPE (ID,TYPE,ISACTIVE,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE) values (nextval('SEQ_EGF_INSTRUMENTTYPE'),'cash','1',1,1, current_timestamp, current_timestamp);

INSERT INTO EGF_INSTRUMENTTYPE (ID,TYPE,ISACTIVE,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE) values (nextval('SEQ_EGF_INSTRUMENTTYPE'),'cheque','1',1,1, current_timestamp, current_timestamp);

INSERT INTO EGF_INSTRUMENTTYPE (ID,TYPE,ISACTIVE,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE) values (nextval('SEQ_EGF_INSTRUMENTTYPE'),'dd','1',1,1, current_timestamp, current_timestamp);

INSERT INTO EGF_INSTRUMENTTYPE (ID,TYPE,ISACTIVE,CREATEDBY,LASTMODIFIEDBY,CREATEDDATE,LASTMODIFIEDDATE) values (nextval('SEQ_EGF_INSTRUMENTTYPE'),'online','1',1,1, current_timestamp, current_timestamp);


