Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'OnlinePayment','Pending',to_date('28-03-10','DD-MM-RR'),'ONLINE_STATUS_PENDING',1);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'OnlinePayment','Success',to_date('28-03-10','DD-MM-RR'),'ONLINE_STATUS_SUCCESS',2);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'OnlinePayment','Failure',to_date('28-03-10','DD-MM-RR'),'ONLINE_STATUS_FAILURE',3);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'OnlinePayment','To Be Refunded',to_date('28-03-10','DD-MM-RR'),'TO_BE_REFUNDED',4);
Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'OnlinePayment','Refunded',to_date('14-07-10','DD-MM-RR'),'ONLINE_STATUS_REFUNDED',4);



Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID) values (nextval('SEQ_EGW_STATUS'),'ReceiptHeader','Pending',to_date('23-01-10','DD-MM-RR'),'PENDING',5);

