
Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate","application") values (nextval('seq_eg_action'),'CashCollectionReport','/reports/cashCollectionReport-criteria.action',null,(select ID from eg_module where NAME ='Collection Reports'),1,'Cash Collection','1','collection',0,1,current_timestamp,1,current_timestamp,(select id from eg_module where name='Collection' and parentmodule is null));

Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate","application") values (nextval('seq_eg_action'),'CashCollectionReportResult','/reports/cashCollectionReport-report.action',null,(select ID from eg_module where NAME ='Collection Reports'),1,'Cash Collection Report Result','0','collection',0,1,current_timestamp,1,current_timestamp,(select id from eg_module where name='Collection' and parentmodule is null));

Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate","application") values (nextval('seq_eg_action'),'ChequeCollectionReport','/reports/chequeCollectionReport-criteria.action',null,(select ID from eg_module where NAME ='Collection Reports'),1,'Cheque Collection','1','collection',0,1,current_timestamp,1,current_timestamp,(select id from eg_module where name='Collection' and parentmodule is null));

Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate","application") values (nextval('seq_eg_action'),'ChequeCollectionReportResult','/reports/chequeCollectionReport-report.action',null,(select ID from eg_module where NAME ='Collection Reports'),1,'Cheque Collection Report Result','0','collection',0,1,current_timestamp,1,current_timestamp,(select id from eg_module where name='Collection' and parentmodule is null));

Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate","application") values (nextval('seq_eg_action'),'ReceiptRegisterReport','/reports/receiptRegisterReport-criteria.action',null,(select ID from eg_module where NAME ='Collection Reports'),1,'Receipt Register Report','1','collection',0,1,current_timestamp,1,current_timestamp,(select id from eg_module where name='Collection' and parentmodule is null));

Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate","application") values (nextval('seq_eg_action'),'ReceiptRegisterReportResult','/reports/receiptRegisterReport-report.action',null,(select ID from eg_module where NAME ='Collection Reports'),1,'Receipt Register Report Result','0','collection',0,1,current_timestamp,1,current_timestamp,(select id from eg_module where name='Collection' and parentmodule is null));

Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate","application") values (nextval('seq_eg_action'),'ReceiptRegisterReport','/reports/receiptRegisterReport-criteria.action',null,(select ID from eg_module where NAME ='Collection Reports'),1,'Receipt Register Report','1','collection',0,1,current_timestamp,1,current_timestamp,(select id from eg_module where name='Collection' and parentmodule is null));

Insert into EG_ACTION ("id","name","url","queryparams","parentmodule","ordernumber","displayname","enabled","contextroot","version","createdby","createddate","lastmodifiedby","lastmodifieddate","application") values (nextval('seq_eg_action'),'ReceiptRegisterReportResult','/reports/receiptRegisterReport-report.action',null,(select ID from eg_module where NAME ='Collection Reports'),1,'Receipt Register Report Result','0','collection',0,1,current_timestamp,1,current_timestamp,(select id from eg_module where name='Collection' and parentmodule is null));

update eg_action  set enabled=true,displayname='Search Receipts' where contextroot='collection' and name='SearchReceipts';


