
delete from EGW_STATUS where MODULETYPE='WATERTAXAPPLICATION';

Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID)
 values (nextval('SEQ_EGW_STATUS'),'WATERTAXAPPLICATION','CREATED',now(),
 'Created',1);


 Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID)
 values (nextval('SEQ_EGW_STATUS'),'WATERTAXAPPLICATION','VERIFIED',now(),
 'Verified',1);

 Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID)
 values (nextval('SEQ_EGW_STATUS'),'WATERTAXAPPLICATION','ESTIMATIONNOTICEGENERATED',now(),
 'Estimation Notice Generated',1);

Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID)
 values (nextval('SEQ_EGW_STATUS'),'WATERTAXAPPLICATION','ESTIMATIONNOTICEGENERATED',now(),
 'Estimation Amount Paid',1);

 Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID)
 values (nextval('SEQ_EGW_STATUS'),'WATERTAXAPPLICATION','APPROVED',now(),
 'Approved',1);

 Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID)
 values (nextval('SEQ_EGW_STATUS'),'WATERTAXAPPLICATION','WORKORDERGENERATED',now(),
 'Work Order Generated',1);

  Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID)
 values (nextval('SEQ_EGW_STATUS'),'WATERTAXAPPLICATION','SANCTIONED',now(),
 'Sanctioned',1);

 
  Insert into EGW_STATUS (ID,MODULETYPE,DESCRIPTION,LASTMODIFIEDDATE,CODE,ORDER_ID)
 values (nextval('SEQ_EGW_STATUS'),'WATERTAXAPPLICATION','CANCELLED',now(),
 'Cancelled',1);