
UPDATE EGW_STATUS SET CODE='CREATED',DESCRIPTION='Created'  WHERE CODE='Created' AND MODULETYPE='WATERTAXAPPLICATION';
UPDATE EGW_STATUS SET CODE='VERIFIED' ,DESCRIPTION='Verified' WHERE CODE='Verified' AND MODULETYPE='WATERTAXAPPLICATION';
UPDATE EGW_STATUS SET CODE='ESTIMATIONNOTICEGENERATED' ,DESCRIPTION='Estimation Notice Generated' WHERE CODE='Estimation Notice Generated' AND MODULETYPE='WATERTAXAPPLICATION';
UPDATE EGW_STATUS SET CODE='ESTIMATIONAMOUNTPAID' ,DESCRIPTION='Estimation Amount Paid' WHERE CODE='Estimation Amount Paid' AND MODULETYPE='WATERTAXAPPLICATION';
UPDATE EGW_STATUS SET CODE='APPROVED' ,DESCRIPTION='Approved' WHERE CODE='Approved'  AND MODULETYPE='WATERTAXAPPLICATION';
UPDATE EGW_STATUS SET CODE='WORKORDERGENERATED',DESCRIPTION='Work Order Generated' WHERE CODE='Work Order Generated' AND MODULETYPE='WATERTAXAPPLICATION';
UPDATE EGW_STATUS SET CODE='SANCTIONED',DESCRIPTION='Sanctioned' WHERE CODE='Sanctioned' AND MODULETYPE='WATERTAXAPPLICATION';
UPDATE EGW_STATUS SET CODE='CANCELLED',DESCRIPTION='Cancelled' WHERE CODE='Cancelled' AND MODULETYPE='WATERTAXAPPLICATION';
