
insert into chartofaccountdetail values(nextval('seq_chartofaccountdetail'),(select id from chartofaccounts where glcode='4601001'),
(select id from accountdetailtype where name='Employee'),1,current_date,1,current_date);

insert into chartofaccountdetail values(nextval('seq_chartofaccountdetail'),(select id from chartofaccounts where glcode='4605001'),
(select id from accountdetailtype where name='Employee'),1,current_date,1,current_date);

insert into chartofaccountdetail values(nextval('seq_chartofaccountdetail'),(select id from chartofaccounts where glcode='4601004'),
(select id from accountdetailtype where name='DrawingOfficer'),1,current_date,1,current_date);

insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E006'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E007'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E008'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E017'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E018'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E019'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E020'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E021'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E022'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E023'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E024'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E025'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E026'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E027'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E028'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E029'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E030'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E031'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E032'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E033'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E034'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E036'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E037'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E001'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E005'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E002'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E003'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E004'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E009'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E010'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E011'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E012'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E013'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E014'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E015'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E039'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E040'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E041'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E042'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E043'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E044'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E045'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E046'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E047'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E048'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E049'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E050'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E051'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E052'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E053'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E054'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E055'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E056'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E057'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E058'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E059'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E060'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E061'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E062'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E063'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E064'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E065'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E066'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E067'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E099'),1,'employee_id');
insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='Employee'),(select id from egeis_employee where code='E000'),1,'employee_id');

insert into eg_drawingofficer(id,code,name,createddate,lastmodifieddate,createdby, lastmodifiedby) values(nextval('seq_eg_drawingofficer'),'DO01','ASST EXT HEALTH',current_date,current_date,1,1);

insert into accountdetailkey(id,detailtypeid,detailkey,groupid,detailname) values (nextval('seq_accountdetailkey'),(select id from accountdetailtype where name='DrawingOfficer'),(select id from eg_drawingofficer where code='DO01'),1,'drawingofficer_id');


