ALTER TABLE EGWTR_FIELDINSPECTION_DETAILS DROP COLUMN DIGGINGCHARGES;
ALTER TABLE EGWTR_FIELDINSPECTION_DETAILS DROP COLUMN SUPERVISIONCHARGES;
ALTER TABLE EGWTR_FIELDINSPECTION_DETAILS DROP COLUMN MATERIALCHARGES;

--rollback ALTER TABLE EGWTR_ESTIMATION_DETAILS ADD COLUMN MATERIALCHARGES double precision;
--rollback ALTER TABLE EGWTR_ESTIMATION_DETAILS ADD COLUMN SUPERVISIONCHARGES double precision;
--rollback ALTER TABLE EGWTR_ESTIMATION_DETAILS ADD COLUMN DIGGINGCHARGES double precision;