--module names
insert into EG_MODULE (ID,NAME,ENABLED,CONTEXTROOT,PARENTMODULE,DISPLAYNAME,ORDERNUMBER) VALUES (NEXTVAL('SEQ_EG_MODULE'),'Trade License','t','tl',null,'Trade License', null);
insert into EG_MODULE (ID,NAME,ENABLED,CONTEXTROOT,PARENTMODULE,DISPLAYNAME,ORDERNUMBER) VALUES (NEXTVAL('SEQ_EG_MODULE'),'Trade License Reports','t','tl',(select id from eg_module where name = 'Trade License'),'Trade License Reports', null);
insert into EG_MODULE (ID,NAME,ENABLED,CONTEXTROOT,PARENTMODULE,DISPLAYNAME,ORDERNUMBER) VALUES (NEXTVAL('SEQ_EG_MODULE'),'Trade License Transactions','t','tl',(select id from eg_module where name = 'Trade License'),'Trade License Transactions', null);
insert into EG_MODULE (ID,NAME,ENABLED,CONTEXTROOT,PARENTMODULE,DISPLAYNAME,ORDERNUMBER) VALUES (NEXTVAL('SEQ_EG_MODULE'),'Search Trade','t','tl',(select id from eg_module where name = 'Trade License'),'Search Trade', null);

--action urls
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'tradeLicenseLateRenewalsReport','/reports/web/Trade License Reports!showLateRenewalsReport.action',null,(select id from EG_MODULE where name = 'Trade License Reports'),4,'Late Renewals','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Enter Trade License','/entertradelicense/web/enterTradeLicense!enterExistingForm.action',null,(select id from EG_MODULE where name = 'Trade License Transactions'),2,'Enter License','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'tradelicense index page','/eGov_TRADELICENSE.jsp',null,(select id from EG_MODULE where name = 'Trade License'),1,'Index page','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Create New License','/newtradelicense/web/newTradeLicense!newForm.action',null,(select id from EG_MODULE where name = 'Trade License Transactions'),2,'Create New License','t','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'View Trade License','/viewtradelicense/web/viewTradeLicense!view.action',null,(select id from EG_MODULE where name = 'Trade License Transactions'),1,'View Trade','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'SearchTradeLicense','/search/web/searchTrade!newForm.action',null,(select id from EG_MODULE where name = 'Search Trade'),1,'Search Trade License','t','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'tradeLicenseZoneWiseReport','/reports/web/Trade License Reports!showZoneWiseReport.action',null,(select id from EG_MODULE where name = 'Trade License Reports'),1,'Zonewise Licenses','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'tradeLicenseWardWiseReport','/reports/web/Trade License Reports!showWardWiseReport.action',null,(select id from EG_MODULE where name = 'Trade License Reports'),2,'Wardwise Licenses','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'tradeLicenseTradeWiseReport','/reports/web/Trade License Reports!showTradeWiseReport.action',null,(select id from EG_MODULE where name = 'Trade License Reports'),3,'Tradewise Licenses','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'New Trade License Action','/newtradelicense/web/newTradeLicense.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'New Trade License','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Enter Trade License Action','/entertradelicense/web/enterTradeLicense.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Enter Trade License','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'View Trade License View Action','/viewtradelicense/web/viewTradeLicense!view.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'View Trade License','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Search Trade License Action','/search/web/searchTrade.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Search Trade License','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Trade License Bill Collect','/web/integration/licenseBillCollect.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Trade License Collection','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Cancel Trade License New Form','/cancellation/web/cancelLicense!newForm.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Cancel Trade License','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Cancel Trade License Action','/cancellation/web/cancelLicense.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Cancel Trade Action','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'View Trade License Duplicate Certificate','/viewtradelicense/web/viewTradeLicense!duplicateCertificate.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Duplicate Certificate','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'View Trade License Generate Certificate','/viewtradelicense/web/viewTradeLicense!generateCertificate.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Generate Certificate','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Transfer Trade License New Form','/transfer/web/transferTradeLicense!newForm.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Transfer Trade License','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Transfer Trade License Action','/transfer/web/transferTradeLicense.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Transfer Trade Action','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Transfer Trade License Show for Approval','/transfer/web/transferTradeLicense!showForApproval.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Transfer Show for Approval','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'New Trade License Before Edit','/newtradelicense/web/editTradeLicense!beforeEdit.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'New Trade License Edit','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Edit Trade License Action','/newtradelicense/web/editTradeLicense.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Edit Trade License','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'View Trade License Show for Approval','/viewtradelicense/web/viewTradeLicense!showForApproval.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Show for Approval','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'View Trade License Action','/viewtradelicense/web/viewTradeLicense.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'View Trade License','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'View Trade License Generate Rejection Certificate','/viewtradelicense/web/viewTradeLicense!generateRejCertificate.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Generate Rejection Certificate','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Trade License Objection New Form','/web/objection/objection!newForm.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Trade License Objection','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Trade License Objection Action','/web/objection/objection.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Trade Objection Action','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Trade License Objection Show for Approval','/web/objection/objection!showForApproval.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Objection Show for Approval','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Trade Revoke Suspension New Form','/revokesuspension/web/revokeSuspension!newForm.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Revoke Suspension','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Trade Revoke Suspension Action','/revokesuspension/web/revokeSuspension.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Revoke Suspension','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Trade License Renewal Notice','/renew/web/tradeRenewalNotice!renewalNotice.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Renewal Notice','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'New Trade License Before Renew','/newtradelicense/web/newTradeLicense!beforeRenew.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Trade Before Renew','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Trade Objection Preliminary Notice','/web/objection/objection!preNotice.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Preliminary Notice','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Trade Objection Show Cause Notice','/web/objection/objection!scNotice.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Show Cause Notice','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Trade Objection Print Preliminary Notice','/web/objection/objection!preliminaryNotice.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Preliminary Notice','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Trade Objection Print Show Cause Notice','/web/objection/objection!showCauseNotice.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Show Cause Notice','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Transfer Trade License Before Edit','/transfer/web/transferTradeLicense!beforeEdit.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Transfer License Edit','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'View Trade License Certificate for Rejection','/viewtradelicense/web/viewTradeLicense!certificateForRej.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Certificate for Rejection','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Populate Divisions for Trade License','/web/commonAjax!populateDivisions.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Populate Divisions','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Populate Designation for Trade License','/web/commonAjax!ajaxPopulateDesignationsByDept.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Populate Designation','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Populate Users for Trade License','/web/commonAjax!ajaxPopulateUsersByDesignation.action',null,(select id from EG_MODULE where name = 'Trade License'),1,'Populate Users','f','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'TLAuditTrailReport','/viewtradelicense/web/viewTradeLicense!auditReport.action','moduleName=TL',(select id from EG_MODULE where name = 'Trade License Reports'),1,'Audit Trail Report','t','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'Search Trade Portal Licenses','/search/web/searchTrade!searchPortal.action',null,(select id from EG_MODULE where name = 'Search Trade'),2,'Search Portal Licenses','t','egtradelicense',0,1,now(),1,now(),(select id from eg_module  where name = 'Trade License'));

--Updating url
update eg_action set url = replace(url, '!', '-') where contextroot = 'egtradelicense' and url like '%!%';

--Updating context root
update eg_action set contextroot = 'tl' where contextroot = 'egtradelicense';

--roleaciton mappings for super user
insert into eg_roleaction (roleid, actionid) select (select id from eg_role where name = 'Super User'), id from eg_action where contextroot = 'tl';


--rollback delete from eg_roleaction  where actionid in (select id from eg_action where contextroot = 'tl') and roleid in (select id from eg_role where name = 'Super User');
--rollback update eg_action set contextroot = 'egtradelicense' where contextroot = 'tl';
--rollback update eg_action set url = replace(url, '-', '!') where contextroot = 'egtradelicense' and url like '%-%';
--rollback delete from eg_action where contextroot = 'egtradelicense';
--rollback delete from eg_module where name in ('Search Trade', 'Trade License Transactions', 'Trade License Reports', 'Trade License');
