
Insert into  EGTL_MSTR_LICENSE_TYPE (ID,NAME,ID_MODULE) values (nextval('SEQ_EGTL_MSTR_LICENSE_TYPE'),'TradeLicense',(select id from eg_module where name='Trade License' and parentmodule is null));



Insert into  EGTL_MSTR_BUSINESS_NATURE (ID,NAME,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY) values (nextval('SEQ_EGTL_MSTR_BUSINESS_NATURE'),'Permanent',Current_date,Current_date,1,1);
Insert into  EGTL_MSTR_BUSINESS_NATURE (ID,NAME,CREATEDDATE,LASTMODIFIEDDATE,CREATEDBY,LASTMODIFIEDBY) values (nextval('SEQ_EGTL_MSTR_BUSINESS_NATURE'),'Temporary',Current_date,Current_date,1,1);



Insert into  EGTL_MSTR_STATUS (ID,STATUS_NAME,LASTUPDATEDTIMESTAMP,IS_ACTIVE,CODE,ORDER_ID) values (nextval('SEQ_EGTL_MSTR_STATUS'),'Acknowledged',Current_date,'1','ACK',1);
Insert into  EGTL_MSTR_STATUS (ID,STATUS_NAME,LASTUPDATEDTIMESTAMP,IS_ACTIVE,CODE,ORDER_ID) values (nextval('SEQ_EGTL_MSTR_STATUS'),'Active',Current_date,'1','ACT',2);
Insert into  EGTL_MSTR_STATUS (ID,STATUS_NAME,LASTUPDATEDTIMESTAMP,IS_ACTIVE,CODE,ORDER_ID) values (nextval('SEQ_EGTL_MSTR_STATUS'),'Rejected',Current_date,'1','REJ',3);
Insert into  EGTL_MSTR_STATUS (ID,STATUS_NAME,LASTUPDATEDTIMESTAMP,IS_ACTIVE,CODE,ORDER_ID) values (nextval('SEQ_EGTL_MSTR_STATUS'),'Objected',Current_date,'1','OBJ',4);
Insert into  EGTL_MSTR_STATUS (ID,STATUS_NAME,LASTUPDATEDTIMESTAMP,IS_ACTIVE,CODE,ORDER_ID) values (nextval('SEQ_EGTL_MSTR_STATUS'),'Suspended',Current_date,'1','SUS',5);
Insert into  EGTL_MSTR_STATUS (ID,STATUS_NAME,LASTUPDATEDTIMESTAMP,IS_ACTIVE,CODE,ORDER_ID) values (nextval('SEQ_EGTL_MSTR_STATUS'),'Cancelled',Current_date,'1','CAN',6);
Insert into  EGTL_MSTR_STATUS (ID,STATUS_NAME,LASTUPDATEDTIMESTAMP,IS_ACTIVE,CODE,ORDER_ID) values (nextval('SEQ_EGTL_MSTR_STATUS'),'Expired',Current_date,'1','EXP',7);
Insert into  EGTL_MSTR_STATUS (ID,STATUS_NAME,LASTUPDATEDTIMESTAMP,IS_ACTIVE,CODE,ORDER_ID) values (8,'UnderWorkflow',Current_date,'1','UWF',8);

