-- Contractor Grade Search --
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksContractorGradeSearch','/masters/contractorGrade-search.action',null,(select id from EG_MODULE where name = 'WorksContractorGradeMaster'),2,'View/Edit Contractor Grade','true','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksContractorGradeSearch' and contextroot = 'egworks'));

-- Milestone Template Search --
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksMilestoneTemplateSearch','/masters/milestoneTemplate-search.action',null,(select id from EG_MODULE where name = 'WorksMilestoneTemplateMaster'),2,'Search Milestone Template','true','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksMilestoneTemplateSearch' and contextroot = 'egworks'));

-- Estimate Template Search --
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksEstimateTemplateSearch','/estimate/estimateTemplate-search.action',null,(select id from EG_MODULE where name = 'WorksEstimateTemplateMaster'),2,'Search Estimate Template','true','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksEstimateTemplateSearch' and contextroot = 'egworks'));

-- Schedule Of Rate Search --
Insert into EG_ACTION (ID,NAME,URL,QUERYPARAMS,PARENTMODULE,ORDERNUMBER,DISPLAYNAME,ENABLED,CONTEXTROOT,VERSION,CREATEDBY,CREATEDDATE,LASTMODIFIEDBY,LASTMODIFIEDDATE,APPLICATION) values (NEXTVAL('SEQ_EG_ACTION'),'WorksScheduleOfRateSearch','/masters/scheduleOfRate-search.action',null,(select id from EG_MODULE where name = 'WorksScheduleOfRateMaster'),2,'View/Edit Schedule Of Rate','true','egworks',0,1,now(),1,now(),(select id from eg_module  where name = 'Works Management'));
Insert into eg_roleaction (roleid, actionid) values ((select id from eg_role where name = 'Super User'),(select id from eg_action where name ='WorksScheduleOfRateSearch' and contextroot = 'egworks'));