INSERT INTO EG_ACTION(ID, NAME, URL, QUERYPARAMS, PARENTMODULE, ORDERNUMBER, DISPLAYNAME, ENABLED, CONTEXTROOT, VERSION, CREATEDBY, CREATEDDATE, LASTMODIFIEDBY, LASTMODIFIEDDATE, APPLICATION)
VALUES (nextval('SEQ_EG_ACTION'), 'Usage Master', '/usage/create', NULL, (SELECT ID FROM EG_MODULE WHERE NAME = 'PTIS-Administration'), 3, 'Usage Master', true, 'ptis', 0, 1, now(), 1, now(), (SELECT id FROM eg_module WHERE name='Property Tax' AND parentmodule IS NULL));

INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) 
VALUES ((SELECT id FROM eg_role WHERE name LIKE 'Property Administrator'), (SELECT id FROM eg_action WHERE NAME = 'Usage Master' AND CONTEXTROOT = 'ptis'));

INSERT INTO EG_ACTION(ID, NAME, URL, QUERYPARAMS, PARENTMODULE, ORDERNUMBER,DISPLAYNAME, ENABLED, CONTEXTROOT, VERSION, CREATEDBY, CREATEDDATE, LASTMODIFIEDBY, LASTMODIFIEDDATE, APPLICATION)
VALUES (nextval('SEQ_EG_ACTION'), 'Usage Master List', '/usage/list', NULL, (SELECT ID FROM EG_MODULE WHERE NAME = 'PTIS-Administration'), 3, 'Usage Master List', false, 'ptis', 0, 1, now(), 1, now(), (SELECT id FROM eg_module WHERE name='Property Tax' AND parentmodule IS NULL));

INSERT INTO EG_ROLEACTION (ROLEID, ACTIONID) 
VALUES ((SELECT id FROM eg_role WHERE name LIKE 'Property Administrator'),(SELECT id FROM eg_action WHERE NAME = 'Usage Master List' AND CONTEXTROOT = 'ptis'));

ALTER TABLE egpt_property_usage_master ADD COLUMN RESD_OR_NONRESD CHARACTER VARYING(50);