
Insert into FUNDSOURCE (ID,CODE,NAME,TYPE,PARENTID,ISACTIVE,CREATED,LLEVEL,ISNOTLEAF,CREATEDBY,LASTMODIFIEDDATE,LASTMODIFIEDBY) values (1,'01','Own Sources',null,null,true,now(),0,0,null,now(),1);
Insert into FUNDSOURCE (ID,CODE,NAME,TYPE,PARENTID,ISACTIVE,CREATED,LLEVEL,ISNOTLEAF,CREATEDBY,LASTMODIFIEDDATE,LASTMODIFIEDBY) values (10,'02','Loans',null,null,true,now(),0,0,null,now(),1);
Insert into FUNDSOURCE (ID,CODE,NAME,TYPE,PARENTID,ISACTIVE,CREATED,LLEVEL,ISNOTLEAF,CREATEDBY,LASTMODIFIEDDATE,LASTMODIFIEDBY) values (11,'03','Grants',null,null,true,now(),0,0,null,now(),1);
Insert into FUNDSOURCE (ID,CODE,NAME,TYPE,PARENTID,ISACTIVE,CREATED,LLEVEL,ISNOTLEAF,CREATEDBY,LASTMODIFIEDDATE,LASTMODIFIEDBY) values (14,'04','MLACDS',null,null,true,now(),0,0,null,now(),1);
Insert into FUNDSOURCE (ID,CODE,NAME,TYPE,PARENTID,ISACTIVE,CREATED,LLEVEL,ISNOTLEAF,CREATEDBY,LASTMODIFIEDDATE,LASTMODIFIEDBY) values (15,'05','MPLADS',null,null,true,now(),0,0,null,now(),1);
Insert into FUNDSOURCE (ID,CODE,NAME,TYPE,PARENTID,ISACTIVE,CREATED,LLEVEL,ISNOTLEAF,CREATEDBY,LASTMODIFIEDDATE,LASTMODIFIEDBY) values (17,'06','JNNURM',null,null,true,now(),0,0,null,now(),1);
Insert into FUNDSOURCE (ID,CODE,NAME,TYPE,PARENTID,ISACTIVE,CREATED,LLEVEL,ISNOTLEAF,CREATEDBY,LASTMODIFIEDDATE,LASTMODIFIEDBY) values (21,'07','Deposit Works',null,null,true,now(),0,0,null,now(),1);

--rollback delete from FUNDSOURCE;