update eg_installment_master set end_date='2015-09-30 23:59:59' where id_module=359 and description='2015-2016-1';
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 1, '2015-10-01 00:00:00', '2015-10-01 00:00:00', '2016-03-31 23:59:59', 359, current_timestamp, '2015-2016-2', NULL);
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 1, '2016-04-01 00:00:00', '2016-04-01 00:00:00', '2016-09-30 23:59:59', 359, current_timestamp, '2016-2017-1', NULL);
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 1, '2016-10-01 00:00:00', '2016-10-01 00:00:00', '2017-03-31 23:59:59', 359, current_timestamp, '2016-2017-2', NULL);
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 1, '2017-04-01 00:00:00', '2017-04-01 00:00:00', '2017-09-30 23:59:59', 359, current_timestamp, '2017-2018-1', NULL);
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 1, '2017-10-01 00:00:00', '2017-10-01 00:00:00', '2018-03-31 23:59:59', 359, current_timestamp, '2017-2018-2', NULL);
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 1, '2018-04-01 00:00:00', '2018-04-01 00:00:00', '2018-09-30 23:59:59', 359, current_timestamp, '2018-2019-1', NULL);
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 1, '2018-10-01 00:00:00', '2018-10-01 00:00:00', '2019-03-31 23:59:59', 359, current_timestamp, '2018-2019-2', NULL);
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 1, '2019-04-01 00:00:00', '2019-04-01 00:00:00', '2019-09-30 23:59:59', 359, current_timestamp, '2019-2020-1', NULL);
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type) VALUES (nextval('seq_eg_installment_master'), 1, '2019-10-01 00:00:00', '2019-10-01 00:00:00', '2020-03-31 23:59:59', 359, current_timestamp, '2019-2020-2', NULL);

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='General Tax' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where name='Receivables for Property Taxes- Arrears') from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Property Tax') and INSTALLMENT_YEAR > to_date('01-04-15','DD-MM-YY');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Vacant Land Tax' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where name='Receivables for Property Taxes- Arrears') from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Property Tax') and INSTALLMENT_YEAR > to_date('01-04-15','DD-MM-YY');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Library Cess' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where name='Receivables for Property Taxes- Arrears') from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Property Tax') and INSTALLMENT_YEAR > to_date('01-04-15','DD-MM-YY');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Library Cess' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where name='Government Dues payable-Library Cess') from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Property Tax') and INSTALLMENT_YEAR > to_date('01-04-15','DD-MM-YY');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Education Cess' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where name='Receivables for Property Taxes- Arrears') from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Property Tax') and INSTALLMENT_YEAR > to_date('01-04-15','DD-MM-YY');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Primary Service Charges' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where name='Receivables for Property Taxes- Arrears') from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Property Tax') and INSTALLMENT_YEAR > to_date('01-04-15','DD-MM-YY');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Unauthorized Penalty' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where name='Receivables for Property Taxes- Arrears') from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Property Tax') and INSTALLMENT_YEAR > to_date('01-04-15','DD-MM-YY');
Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='PENALTY_FINES' and module=(select id from eg_module where name='Property Tax')), inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where name='Penalties and Fines-Contractors') from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Property Tax') and INSTALLMENT_YEAR > to_date('01-04-15','DD-MM-YY');