-- Adding ADDRESS column to EGTL_LICENSEE
ALTER TABLE EGTL_LICENSEE ADD COLUMN ADDRESS character varying(250) NOT NULL;

-- Dropping id_address from EGTL_LICENSEE
ALTER TABLE EGTL_LICENSEE drop COLUMN id_address;

-- Dropping columns from EGTL_LICENSE

ALTER TABLE EGTL_LICENSE drop COLUMN id_address;

ALTER TABLE EGTL_LICENSE drop COLUMN doc_number;

ALTER TABLE EGTL_LICENSE drop COLUMN bio_medical_waste_reg;

ALTER TABLE EGTL_LICENSE drop COLUMN type_of_firm;

ALTER TABLE EGTL_LICENSE drop COLUMN name_sole_proprietor;

ALTER TABLE EGTL_LICENSE drop COLUMN banker_name;

ALTER TABLE EGTL_LICENSE drop COLUMN execute_works_worth;

ALTER TABLE EGTL_LICENSE drop COLUMN cost_of_works_hand;

ALTER TABLE EGTL_LICENSE drop COLUMN parent_id;

ALTER TABLE EGTL_LICENSE drop COLUMN is_upgrade;

ALTER TABLE EGTL_LICENSE drop COLUMN bank_address;

ALTER TABLE EGTL_LICENSE drop COLUMN place_of_business;

ALTER TABLE EGTL_LICENSE drop COLUMN id_license_sub_type;

ALTER TABLE EGTL_LICENSE drop COLUMN contractor_code;

ALTER TABLE EGTL_LICENSE DROP COLUMN BUILDINGTYPE;

-- Adding columns to EGTL_LICENSE

ALTER TABLE EGTL_LICENSE ADD COLUMN BUILDINGTYPE  bigint;

ALTER TABLE EGTL_LICENSE ADD COLUMN PROPERTY_NO character varying(64);

ALTER TABLE EGTL_LICENSE ADD COLUMN ADDRESS character varying(250) NOT NULL;

ALTER TABLE EGTL_LICENSE ADD COLUMN OWNERSHIP_TYPE  character varying(120) NOT NULL;

ALTER TABLE EGTL_LICENSE ADD COLUMN ID_CATEGORY  bigint NOT NULL;

ALTER TABLE EGTL_LICENSE ADD COLUMN WORKERS_CAPACITY bigint NOT NULL;

ALTER TABLE EGTL_LICENSE ADD COLUMN TRADE_AREA_WEIGHT  bigint NOT NULL;

ALTER TABLE EGTL_LICENSE ADD COLUMN ID_UOM bigint NOT NULL;

-- Adding FK relation for category / uom / buildingtype columns

ALTER TABLE EGTL_LICENSE ADD CONSTRAINT egtl_license_category FOREIGN KEY (ID_CATEGORY) REFERENCES EGTL_MSTR_CATEGORY(id);

ALTER TABLE EGTL_LICENSE ADD CONSTRAINT egtl_license_UOM FOREIGN KEY (ID_UOM) REFERENCES EGTL_MSTR_UNITOFMEASURE(id);

ALTER TABLE EGTL_LICENSE ADD CONSTRAINT egtl_license_buildingType FOREIGN KEY (BUILDINGTYPE) REFERENCES egtl_mstr_business_nature(id);


