
INSERT INTO EGEIS_BLOODGROUP (ID, VALUE, START_DATE, END_DATE) 
VALUES ( EGEIS_BLOOD_SEQ.nextval,'A+' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_BLOODGROUP (ID, VALUE, START_DATE, END_DATE) 
VALUES ( EGEIS_BLOOD_SEQ.nextval,'A-' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_BLOODGROUP (ID, VALUE, START_DATE, END_DATE) 
VALUES ( EGEIS_BLOOD_SEQ.nextval,'B+' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_BLOODGROUP (ID, VALUE, START_DATE, END_DATE) 
VALUES ( EGEIS_BLOOD_SEQ.nextval,'A-' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_BLOODGROUP (ID, VALUE, START_DATE, END_DATE) 
VALUES ( EGEIS_BLOOD_SEQ.nextval,'AB+' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_BLOODGROUP (ID, VALUE, START_DATE, END_DATE) 
VALUES ( EGEIS_BLOOD_SEQ.nextval,'AB-' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_BLOODGROUP (ID, VALUE, START_DATE, END_DATE) 
VALUES ( EGEIS_BLOOD_SEQ.nextval,'O+' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_BLOODGROUP (ID, VALUE, START_DATE, END_DATE) 
VALUES ( EGEIS_BLOOD_SEQ.nextval,'O-' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));

/***Languages Known Master ****/


INSERT INTO EGEIS_LANGUAGES_KNOWN_MSTR (LANGUAGES_KNOWN_ID, LANGUAGES_KNOWN_VALUE, START_DATE, END_DATE) 
VALUES (EGPIMS_LANGUAGES_KNOWN_SEQ.nextval ,'English' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_LANGUAGES_KNOWN_MSTR (LANGUAGES_KNOWN_ID, LANGUAGES_KNOWN_VALUE, START_DATE, END_DATE) 
VALUES (EGPIMS_LANGUAGES_KNOWN_SEQ.nextval ,'Hindi' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));

/***Mode of Recruitment ****/

INSERT INTO EGEIS_MODE_OF_RECRUIMENT_MSTR ( MODE_OF_RECRUIMENT_ID, MODE_OF_RECRUIMENT_NAME,START_DATE, END_DATE ) 
VALUES (EGPIMS_RECRUITMENT_TYPE_SEQ.nextval, 'Direct',  TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_MODE_OF_RECRUIMENT_MSTR ( MODE_OF_RECRUIMENT_ID, MODE_OF_RECRUIMENT_NAME,START_DATE, END_DATE ) 
VALUES (EGPIMS_RECRUITMENT_TYPE_SEQ.nextval, 'Transfer',  TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_MODE_OF_RECRUIMENT_MSTR ( MODE_OF_RECRUIMENT_ID, MODE_OF_RECRUIMENT_NAME,START_DATE, END_DATE ) 
VALUES (EGPIMS_RECRUITMENT_TYPE_SEQ.nextval, 'Compensatory Appointment',  TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));

/***Recruitment type ****/
INSERT INTO EGEIS_RECRUITMENT_TYPE_MSTR (RECRUITMENT_TYPE_ID, RECRUITMENT_TYPE_NAME, START_DATE,  END_DATE) 
VALUES ( EGPIMS_RECRUITMENT_TYPE_SEQ.nextval,'Appointment' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_RECRUITMENT_TYPE_MSTR (RECRUITMENT_TYPE_ID, RECRUITMENT_TYPE_NAME, START_DATE,  END_DATE) 
VALUES ( EGPIMS_RECRUITMENT_TYPE_SEQ.nextval,'UPSC' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_RECRUITMENT_TYPE_MSTR (RECRUITMENT_TYPE_ID, RECRUITMENT_TYPE_NAME, START_DATE,  END_DATE) 
VALUES ( EGPIMS_RECRUITMENT_TYPE_SEQ.nextval,'Clerical Exam' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_RECRUITMENT_TYPE_MSTR (RECRUITMENT_TYPE_ID, RECRUITMENT_TYPE_NAME, START_DATE,  END_DATE) 
VALUES ( EGPIMS_RECRUITMENT_TYPE_SEQ.nextval,'Direct Appointment' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));

/***Employee user entered Status ****/
INSERT INTO EGEIS_STATUS_MASTER (STATUS_ID, NAME, END_DATE, START_DATE) 
VALUES (SEQ_EGEIS_STATUS.nextval ,'Permanent' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_STATUS_MASTER (STATUS_ID, NAME, END_DATE, START_DATE) 
VALUES (SEQ_EGEIS_STATUS.nextval ,'Temporary' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));

/***Category ****/
INSERT INTO EGEIS_CATEGORY_MSTR (CATEGORY_ID, CATEGORY_NAME, START_DATE,END_DATE) 
VALUES (EGPIMS_CAT_SEQ.nextval ,'CNT' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_CATEGORY_MSTR (CATEGORY_ID, CATEGORY_NAME, START_DATE,END_DATE) 
VALUES (EGPIMS_CAT_SEQ.nextval ,'NON-CNT' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));

/***Property How Acquired ****/

INSERT INTO EGEIS_HOW_ACQUIRED_MSTR ( HOW_ACQUIRED_ID, HOW_ACQUIRED_VALUE, END_DATE,START_DATE ) 
VALUES (EGPIMS_HOW_ACQUIRED_SEQ.nextval, 'Gift',  TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_HOW_ACQUIRED_MSTR ( HOW_ACQUIRED_ID, HOW_ACQUIRED_VALUE, END_DATE,START_DATE ) 
VALUES (EGPIMS_HOW_ACQUIRED_SEQ.nextval, 'Lease',  TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_HOW_ACQUIRED_MSTR ( HOW_ACQUIRED_ID, HOW_ACQUIRED_VALUE, END_DATE,START_DATE ) 
VALUES (EGPIMS_HOW_ACQUIRED_SEQ.nextval, 'Mortgage',  TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));

/***Technical Skill and Grades ****/

INSERT INTO EGEIS_SKILL_MSTR (SKILL_ID, SKILL_VALUE, END_DATE,START_DATE) 
VALUES (EGPIMS_SKILL_MSTR_SEQ1.nextval,'Typewriting' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));


INSERT INTO EGEIS_TECHNICAL_GRADES_MSTR (TECK_GRADES_ID, TECK_GRADES_VALUE, SKILL_ID,END_DATE, START_DATE) 
VALUES (EGPIMS_TECK_GRADES_SEQ1.nextval ,'Junior' ,(select SKILL_ID FROM EGEIS_SKILL_MSTR where SKILL_VALUE = 'Typewriting') ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_TECHNICAL_GRADES_MSTR (TECK_GRADES_ID, TECK_GRADES_VALUE, SKILL_ID,END_DATE, START_DATE) 
VALUES (EGPIMS_TECK_GRADES_SEQ1.nextval ,'Senior' , (select SKILL_ID FROM EGEIS_SKILL_MSTR where SKILL_VALUE = 'Typewriting'),TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));


/***Leave types ****/
INSERT INTO EGEIS_TYPE_OF_LEAVE_MSTR (TYPE_OF_LEAVE_ID, TYPE_OF_LEAVE_VALUE, ACCUMULATE,PAY_ELIGIBLE, IS_HALF_DAY) VALUES (EGPIMS_TYPE_OF_LEAVE_SEQ.nextval ,'Casual' ,0 ,1 ,0 );
INSERT INTO EGEIS_TYPE_OF_LEAVE_MSTR (TYPE_OF_LEAVE_ID, TYPE_OF_LEAVE_VALUE, ACCUMULATE,PAY_ELIGIBLE, IS_HALF_DAY) VALUES (EGPIMS_TYPE_OF_LEAVE_SEQ.nextval ,'Restricted' ,0 ,1 ,0 );
INSERT INTO EGEIS_TYPE_OF_LEAVE_MSTR (TYPE_OF_LEAVE_ID, TYPE_OF_LEAVE_VALUE, ACCUMULATE,PAY_ELIGIBLE, IS_HALF_DAY) VALUES (EGPIMS_TYPE_OF_LEAVE_SEQ.nextval ,'EL' ,1 ,1 ,0 );
INSERT INTO EGEIS_TYPE_OF_LEAVE_MSTR (TYPE_OF_LEAVE_ID, TYPE_OF_LEAVE_VALUE, ACCUMULATE,PAY_ELIGIBLE, IS_HALF_DAY) VALUES (EGPIMS_TYPE_OF_LEAVE_SEQ.nextval ,'Maternity' ,0 ,1 ,0 );
INSERT INTO EGEIS_TYPE_OF_LEAVE_MSTR (TYPE_OF_LEAVE_ID, TYPE_OF_LEAVE_VALUE, ACCUMULATE,PAY_ELIGIBLE, IS_HALF_DAY) VALUES (EGPIMS_TYPE_OF_LEAVE_SEQ.nextval ,'Medical' ,0 ,1 ,0 );

delete from EGEIS_GRADE_MSTR;

INSERT INTO EGEIS_GRADE_MSTR ( GRADE_ID, GRADE_VALUE, START_DATE, END_DATE,AGE ) VALUES ( 
EGPIMS_GRADE_MSTR_SEQ.nextval, 'A', TO_DATE('01-04-2000', 'DD-MM-YYYY'), TO_DATE('01-04-2099','DD-MM-YYYY'), 60); 
INSERT INTO EGEIS_GRADE_MSTR ( GRADE_ID, GRADE_VALUE, START_DATE, END_DATE,AGE ) VALUES ( 
EGPIMS_GRADE_MSTR_SEQ.nextval, 'B',  TO_DATE('01-04-2000', 'DD-MM-YYYY'), TO_DATE('01-04-2099','DD-MM-YYYY'), 60); 
INSERT INTO EGEIS_GRADE_MSTR ( GRADE_ID, GRADE_VALUE, START_DATE, END_DATE,AGE ) VALUES ( 
EGPIMS_GRADE_MSTR_SEQ.nextval, 'C', TO_DATE('01-04-2000', 'DD-MM-YYYY'), TO_DATE('01-04-2099','DD-MM-YYYY'), 60); 
INSERT INTO EGEIS_GRADE_MSTR ( GRADE_ID, GRADE_VALUE, START_DATE, END_DATE,AGE ) VALUES ( 
EGPIMS_GRADE_MSTR_SEQ.nextval, 'D',  TO_DATE('01-04-2000', 'DD-MM-YYYY'), TO_DATE('01-04-2099','DD-MM-YYYY'), 60); 


INSERT INTO EGEIS_RELIGION_MSTR (RELIGION_ID, RELIGION_VALUE, START_DATE, END_DATE) 
VALUES (EGPIMS_RELIGION_SEQ.nextval ,'Hindu' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_RELIGION_MSTR (RELIGION_ID, RELIGION_VALUE, START_DATE, END_DATE) 
VALUES (EGPIMS_RELIGION_SEQ.nextval ,'Sikh' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_RELIGION_MSTR (RELIGION_ID, RELIGION_VALUE, START_DATE, END_DATE) 
VALUES (EGPIMS_RELIGION_SEQ.nextval ,'Muslim' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_RELIGION_MSTR (RELIGION_ID, RELIGION_VALUE, START_DATE, END_DATE) 
VALUES (EGPIMS_RELIGION_SEQ.nextval ,'Jain' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_RELIGION_MSTR (RELIGION_ID, RELIGION_VALUE, START_DATE, END_DATE) 
VALUES (EGPIMS_RELIGION_SEQ.nextval ,'Buddhist' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_RELIGION_MSTR (RELIGION_ID, RELIGION_VALUE, START_DATE, END_DATE) 
VALUES (EGPIMS_RELIGION_SEQ.nextval ,'Sindhi' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));
INSERT INTO EGEIS_RELIGION_MSTR (RELIGION_ID, RELIGION_VALUE, START_DATE, END_DATE) 
VALUES (EGPIMS_RELIGION_SEQ.nextval ,'Christian' ,TO_DATE('01-01-2000', 'DD-MM-YYYY') , TO_DATE('01-01-2999','DD-MM-YYYY'));

/***Leave Designation mapping ****/
INSERT INTO EGEIS_LEAVE_MSTR (ID, DESIG_ID, LEAVE_TYPE_ID, NO_OF_DAYS) 
SELECT EGEIS_LEAVE_MSTR_SEQ.nextval, DESIGNATIONID, (SELECT (TYPE_OF_LEAVE_ID) FROM EGEIS_TYPE_OF_LEAVE_MSTR WHERE TYPE_OF_LEAVE_VALUE='Casual'), 14
FROM EG_DESIGNATION;
INSERT INTO EGEIS_LEAVE_MSTR (ID, DESIG_ID, LEAVE_TYPE_ID, NO_OF_DAYS) 
SELECT EGEIS_LEAVE_MSTR_SEQ.nextval, DESIGNATIONID, (SELECT (TYPE_OF_LEAVE_ID) FROM EGEIS_TYPE_OF_LEAVE_MSTR WHERE TYPE_OF_LEAVE_VALUE='Restricted'), 2
FROM EG_DESIGNATION;
INSERT INTO EGEIS_LEAVE_MSTR (ID, DESIG_ID, LEAVE_TYPE_ID, NO_OF_DAYS) 
SELECT EGEIS_LEAVE_MSTR_SEQ.nextval, DESIGNATIONID, (SELECT (TYPE_OF_LEAVE_ID) FROM EGEIS_TYPE_OF_LEAVE_MSTR WHERE TYPE_OF_LEAVE_VALUE='EL'), 31
FROM EG_DESIGNATION;


/***CREATE OPENING BALANCE ****/



INSERT INTO FINANCIALYEAR ( ID, FINANCIALYEAR, STARTINGDATE, ENDINGDATE, ISACTIVE, CREATED,
LASTMODIFIED, MODIFIEDBY, ISACTIVEFORPOSTING, ISCLOSED,
TRANSFERCLOSINGBALANCE ) VALUES ( 
SEQ_FINANCIALYEAR.nextval, '2009-2010',  TO_Date( '04/01/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '03/31/2010 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 1,  SYSDATE,  SYSDATE, 1, 0, 0, 0); 
COMMIT;
