#UP

/******** Table for rules set up ******************/
CREATE TABLE EGPAY_PAYGENRULESSETUP_MSTR
(
  ID NUMBER(12) NOT NULL,
  SALARYCODE_ID NUMBER(12),
  PERCENTAGE NUMBER(12,2),
  MONTHLYFLAT_AMOUNT NUMBER(12,2),
  MONTH NUMBER(12),
  ID_FINANCIALYEAR NUMBER(12),
  CONSTRAINT PK_EGPAY_PAYGENRULESSETUP_MSTR PRIMARY KEY (ID )
);

/*************  References *****************/

ALTER TABLE EGPAY_PAYGENRULESSETUP_MSTR ADD 
CONSTRAINT FK_PAYGENRULESSETUP_SALARY_ID
 FOREIGN KEY (SALARYCODE_ID)
 REFERENCES EGPAY_SALARYCODES (ID) ENABLE
 VALIDATE;

 ALTER TABLE EGPAY_PAYGENRULESSETUP_MSTR ADD 
CONSTRAINT FK_PAYGENRULES_FIN_ID
 FOREIGN KEY (ID_FINANCIALYEAR)
 REFERENCES FINANCIALYEAR (ID) ENABLE
 VALIDATE;


/************** sequence ********************/
CREATE SEQUENCE EISPAYROLL_PAYGENRULES_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
MAXVALUE 999999999999999999999999999
NOCACHE 
NOCYCLE 
NOORDER; 

/************* Unique combination of salary code,month,fin year*******************/

ALTER TABLE EGPAY_PAYGENRULESSETUP_MSTR ADD 
CONSTRAINT UNIQUE_RULESETUP
 UNIQUE (SALARYCODE_ID, MONTH, ID_FINANCIALYEAR)
 ENABLE
 VALIDATE;

#DOWN




