#UP

CREATE SEQUENCE SEQ_BANK START WITH 1 MAXVALUE 999999999999999999999999999 
MINVALUE 0 NOCYCLE NOCACHE NOORDER;

CREATE SEQUENCE SEQ_BANKBRANCH START WITH 1 MAXVALUE 999999999999999999999999999 
MINVALUE 0 NOCYCLE NOCACHE NOORDER;

INSERT INTO EGW_STATUS ( ID, MODULETYPE, DESCRIPTION,
LASTMODIFIEDDATE ) VALUES ( 
SEQ_EGW_STATUS.nextval, 'CBILL', 'CREATED',  SYSDATE); 

ALTER TABLE EG_OBJECT_TYPE ADD (
   CONSTRAINT UNQ_OBJECT_TYPE UNIQUE (TYPE));

alter table eg_billdetails add NARRATION  VARCHAR2(250);  


INSERT INTO EGW_STATUS
   (ID, MODULETYPE, DESCRIPTION, LASTMODIFIEDDATE)
 VALUES
   (SEQ_EGW_STATUS.NEXTVAL, 'SALBILL', 'Paid', TO_DATE('07/10/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
INSERT INTO EGW_STATUS
   (ID, MODULETYPE, DESCRIPTION, LASTMODIFIEDDATE)
 VALUES
   (SEQ_EGW_STATUS.NEXTVAL, 'SALBILL', 'Passed', TO_DATE('07/10/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
INSERT INTO EGW_STATUS
   (ID, MODULETYPE, DESCRIPTION, LASTMODIFIEDDATE)
 VALUES
   (SEQ_EGW_STATUS.NEXTVAL, 'SALBILL', 'Approved', TO_DATE('07/10/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
INSERT INTO EGW_STATUS
   (ID, MODULETYPE, DESCRIPTION, LASTMODIFIEDDATE)
 VALUES
   (SEQ_EGW_STATUS.NEXTVAL, 'SALBILL', 'Created', TO_DATE('07/10/2007 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
INSERT INTO EGW_STATUS
   (ID, MODULETYPE, DESCRIPTION, LASTMODIFIEDDATE)
 VALUES
   (SEQ_EGW_STATUS.NEXTVAL, 'SALBILL', 'Cancelled', TO_DATE('02/01/2008 07:28:02', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;



#DOWN