#UP
CREATE TABLE EGPAY_PAYHEAD_RULE
(
  ID              NUMBER(12)                        NULL,
  ID_SALARYCODE   NUMBER(12)                        NULL,
  EFFECTIVE_FROM  DATE                              NULL,
  DESCRIPTION     VARCHAR2(64 BYTE)                 NULL,
  RULE_FILE_PATH  VARCHAR2(64 BYTE)                 NULL
);


ALTER TABLE EGPAY_PAYHEAD_RULE ADD (
  CONSTRAINT PK_EGPAY_PAYHEAD_RULE PRIMARY KEY (ID));

ALTER TABLE EGPAY_PAYHEAD_RULE ADD (
  CONSTRAINT FK_ID_SALARYCODE FOREIGN KEY (ID_SALARYCODE) 
    REFERENCES EGPAY_SALARYCODES (ID));


CREATE SEQUENCE EISPAYROLL_PAYHEAD_RULE_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

#DOWN