#UP
/**** AFTER TAG 11 ****************/
        
       
/****changes for batch generation of payslips 23/12/2008****************/



ALTER TABLE EGPAY_BATCHGENDETAILS
ADD ID_FUNCTIONARY NUMBER;

ALTER TABLE EGPAY_BATCHGENDETAILS ADD (
CONSTRAINT FK_ID_FUNCTIONARY FOREIGN KEY (ID_FUNCTIONARY) 
REFERENCES FUNCTIONARY (ID));

ALTER TABLE  EGPAY_BATCHFAILUREDETAILS
ADD ID_FUNCTIONARY NUMBER;

ALTER TABLE EGPAY_BATCHFAILUREDETAILS ADD (
CONSTRAINT FK_ID_FUNCTIONARY_FAIL FOREIGN KEY (ID_FUNCTIONARY) 
REFERENCES FUNCTIONARY (ID));


#DOWN