#UP

/**06/01/2009 advance schedule table********/

CREATE TABLE EGPAY_ADVANCE_SCHEDULE
(
  ID NUMBER(12) NOT NULL,
  INST_AMT NUMBER(15,2),
  MONTH NUMBER(15),
  ID_FINYEAR NUMBER(12),
  ID_SALADVANCE NUMBER(12),
  CONSTRAINT PK_EGPAY_ADVANCE_SCHEDULE PRIMARY KEY (ID )
);


ALTER TABLE EGPAY_ADVANCE_SCHEDULE ADD 
CONSTRAINT FK_IDSALADVANCE
 FOREIGN KEY (ID_SALADVANCE)
 REFERENCES EGPAY_SALADVANCES (ID) ENABLE
 VALIDATE;

ALTER TABLE EGPAY_ADVANCE_SCHEDULE ADD 
CONSTRAINT FK_IDFINANCIALYEAR
 FOREIGN KEY (ID_FINYEAR)
 REFERENCES FINANCIALYEAR (ID) ENABLE
 VALIDATE;

CREATE SEQUENCE EISPAYROLL_ADV_SCHEDULE_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

/**added timestamp in egpay_emppayroll ******/

ALTER TABLE EGPAY_EMPPAYROLL
  ADD LASTMODIFIEDDATE DATE;

UPDATE EGPAY_EMPPAYROLL SET lastmodifieddate = SYSDATE where lastmodifieddate is null;

/**added grade and type in paysclae ******/

ALTER TABLE EGPAY_PAYSCALE_HEADER
  ADD GRADE_ID NUMBER(32)
  ADD TYPE VARCHAR2(512);
  
  ALTER TABLE EGPAY_PAYSCALE_HEADER ADD 
  CONSTRAINT GRADE_PAYSCALE_FK
   FOREIGN KEY (GRADE_ID)
   REFERENCES EGEIS_GRADE_MSTR (GRADE_ID) ENABLE
 VALIDATE;
 
 #DOWN