package org.egov.billsaccounting.model;

// Generated Mar 6, 2008 11:33:35 AM by Hibernate Tools 3.2.0.b9

import org.egov.commons.CVoucherHeader;
import org.egov.model.bills.EgBillregister;

/**
 * Otherbilldetail generated by hbm2java
 */
public class OtherBillDetail implements java.io.Serializable
{

	private Integer id;

	private CVoucherHeader voucherheaderByPayvhid;

	private CVoucherHeader voucherheaderByVoucherheaderid;

	private EgBillregister egBillregister;

	public OtherBillDetail()
	{
	}

	public OtherBillDetail(Integer id,
			CVoucherHeader voucherheaderByVoucherheaderid,
			EgBillregister egBillregister)
	{
		this.id = id;
		this.voucherheaderByVoucherheaderid = voucherheaderByVoucherheaderid;
		this.egBillregister = egBillregister;
	}

	public OtherBillDetail(Integer id, CVoucherHeader voucherheaderByPayvhid,
			CVoucherHeader voucherheaderByVoucherheaderid,
			EgBillregister egBillregister)
	{
		this.id = id;
		this.voucherheaderByPayvhid = voucherheaderByPayvhid;
		this.voucherheaderByVoucherheaderid = voucherheaderByVoucherheaderid;
		this.egBillregister = egBillregister;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public CVoucherHeader getVoucherheaderByPayvhid()
	{
		return this.voucherheaderByPayvhid;
	}

	public void setVoucherheaderByPayvhid(CVoucherHeader voucherheaderByPayvhid)
	{
		this.voucherheaderByPayvhid = voucherheaderByPayvhid;
	}

	public CVoucherHeader getVoucherheaderByVoucherheaderid()
	{
		return this.voucherheaderByVoucherheaderid;
	}

	public void setVoucherheaderByVoucherheaderid(
			CVoucherHeader voucherheaderByVoucherheaderid)
	{
		this.voucherheaderByVoucherheaderid = voucherheaderByVoucherheaderid;
	}

	public EgBillregister getEgBillregister()
	{
		return this.egBillregister;
	}

	public void setEgBillregister(EgBillregister egBillregister)
	{
		this.egBillregister = egBillregister;
	}

}
