#UP

INSERT INTO EGLC_ADVOCATE_MASTER ( ID, ADVOCATE_NAME, ADVOCATE_ADDR, CONTACT_PHONE,
ADVOCATE_SPECIALTY, MOBILE_NUMBER, EMAIL, MONTHLY_RENUMERATION, IS_RETAINERADVOCATE, FIRMNAME,
PANNUMBER, IS_ACTIVE, IS_SENIORADVOCATE, CREATEDDATE, LASTMODIFIEDDATE, CREATEDBY, LASTMODIFIEDBY,
SALUTATION ) VALUES ( 
SEQ_EGLC_ADVOCATE_MASTER.NEXTVAL, 'Paranthaman', NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 1, 1,  TO_Date( '06/26/2009 01:32:50 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '06/26/2009 01:32:50 PM', 'MM/DD/YYYY HH:MI:SS AM'), 436, 436, 'Mr.'); 


commit;
#DOWN
