#UP
INSERT INTO EG_APPCONFIG ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES ( 
SEQ_EG_APPCONFIG.NEXTVAL, 'DEFAULT_SEARCH_MISATTRRIBUTES', 'default search mis attributes', 'EGF'); 

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE key_name='DEFAULT_SEARCH_MISATTRRIBUTES'),  TO_DATE( '10/07/2009 04:21:15 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'department|N'); 
INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE key_name='DEFAULT_SEARCH_MISATTRRIBUTES'),  TO_DATE( '10/07/2009 04:21:15 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'fund|M'); 

#DOWn