#UP

INSERT INTO EG_BILL_TYPE(ID,NAME,CODE,CREATE_TIME_STAMP,UPDATED_TIME_STAMP) VALUES(SEQ_EG_BILL_TYPE.NEXTVAL,'AUTO','AUTO',SYSDATE,SYSDATE);


INSERT INTO EG_BILL(ID, ID_DEMAND, CITIZEN_NAME, CITIZEN_ADDRESS, BILL_NO, ID_BILL_TYPE, ISSUE_DATE, LAST_DATE, MODULE_ID, USER_ID, CREATE_TIME_STAMP,LAST_UPDATED_TIMESTAMP, IS_HISTORY, IS_CANCELLED, FUNDCODE, FUNDSOURCE_CODE,DEPARTMENT_CODE, COLL_MODES_NOT_ALLOWED, BOUNDARY_NUM,BOUNDARY_TYPE, TOTAL_AMOUNT, TOTAL_COLLECTED_AMOUNT,SERVICE_CODE, PART_PAYMENT_ALLOWED, OVERRIDE_ACCOUNTHEADS_ALLOWED, DESCRIPTION) 
VALUES(SEQ_EG_BILL.nextval,  ( select min(id) FROM eg_demand ), 'citizen name', 'citizen address', 'billNo', (select id from eg_bill_type where name='AUTO'),sysdate, sysdate, (select id_module from eg_module where module_name='Property Tax'), 1, sysdate, sysdate, 'N', 'N', 'fundCode','fundSourceCode', 'departmentCode', 'cheque',1,'boundaryType', 200, 0, 'serviceCode', 'N', 'N', 'bill description');



INSERT INTO EG_BILL_DETAILS(ID, ID_DEMAND_REASON, CREATE_TIME_STAMP, LAST_UPDATED_TIMESTAMP, ID_BILL, GLCODE, COLLECTED_AMOUNT, 
ORDER_NO, FUNCTION_CODE, CR_AMOUNT, DR_AMOUNT) 
VALUES(SEQ_EG_BILL_DETAILS.nextval, null, sysdate, sysdate, SEQ_EG_BILL.currval, '431100100', 0, 1, 'functionCode', 100, 0);

INSERT INTO EG_BILL_DETAILS(ID, ID_DEMAND_REASON, CREATE_TIME_STAMP, LAST_UPDATED_TIMESTAMP, ID_BILL, GLCODE, COLLECTED_AMOUNT, 
ORDER_NO, FUNCTION_CODE, CR_AMOUNT, DR_AMOUNT) 
VALUES(SEQ_EG_BILL_DETAILS.nextval, null, sysdate, sysdate, SEQ_EG_BILL.currval, '431101300', 0, 2, 'functionCode', 100, 0);




#DOWN
