#UP

INSERT INTO EGPT_PROPERTY_TYPE_MASTER 
   (ID_PROPERTYTYPEMASTER, PROPERTY_TYPE, MODIFIED_DATE,TYPE_FACTOR, PROPERTY_TYPE_LOCAL, CODE) 
VALUES 
   (SEQ_PROP_TYPE_MASTER.NEXTVAL, 'Cell Phone Tower',  SYSDATE, 1, NULL, 'CELL_TOWER');

insert into EG_APPCONFIG (ID, KEY_NAME, DESCRIPTION, MODULE) values (SEQ_EG_APPCONFIG.nextval,'CELL_PHONE_TOWER_TAX','Cell Phone Tower Tax','Property Tax');
insert into EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) values (SEQ_EG_APPCONFIG_VALUES.nextval,(select id from EG_APPCONFIG where KEY_NAME = 'CELL_PHONE_TOWER_TAX'),to_date('01/04/2009','dd/MM/yyyy'),'15000');

#DOWN
delete from EGPT_PROPERTY_TYPE_MASTER where code = 'CELL_TOWER';

delete from EG_APPCONFIG_VALUES where key_id = (select id from EG_APPCONFIG where KEY_NAME = 'CELL_PHONE_TOWER_TAX');
delete from EG_APPCONFIG where KEY_NAME = 'CELL_PHONE_TOWER_TAX' and module = 'Property Tax';
