#UP

/** Bank details for emp id=1 or name=vimal kishore **/
INSERT INTO BANKBRANCH ( ID, BRANCHCODE, BRANCHNAME, BRANCHADDRESS1, BRANCHADDRESS2, BRANCHCITY,
BRANCHSTATE, BRANCHPIN, BRANCHPHONE, BRANCHFAX, BANKID, CONTACTPERSON, ISACTIVE, CREATED,
LASTMODIFIED, MODIFIEDBY, NARRATION ) VALUES ( 
SEQ_BANKBRANCH.NEXTVAL, 'IFSC0001', 'Indiranagar', 'Indiranagar', '38', 'Banglaore', NULL, NULL, NULL, NULL
, (SELECT id from bank where code='ICICI'), NULL, 1,  TO_Date( '12/01/2010 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/01/2010 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 1, NULL);

INSERT INTO EGEIS_BANK_DET ( ID_BANK, ID, SALARY_BANK, BANK, ACCOUNT_NUMBER,
BRANCH ) VALUES ( 
EGPIMS_BANK_DET_SEQ.nextval, 1, 1, (SELECT id from bank where code='ICICI'), '016901234512', (SELECT id from BANKBRANCH where branchcode='IFSC0001')); 


#DOWN

