#UP

/** Sample dummy data for rulescript in nomination head master **/

INSERT INTO EG_WF_ACTIONS ( ID, TYPE, NAME, DESCRIPTION, CREATED_BY, CREATED_DATE, MODIFIED_BY,
MODIFIED_DATE ) VALUES ( 
EG_WF_ACTIONS_SEQ.nextVal, 'NominationHeader', 'DummyPF', 'Dummy Pct Of PF', NULL,  TO_Date( '02/08/2010 10:44:47 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL,  TO_Date( '02/08/2010 10:44:47 AM', 'MM/DD/YYYY HH:MI:SS AM')); 

INSERT INTO EGPAY_NOMINATION_HEADER ( ID, CODE, DESCRIPTION, ID_GLCODE, ID_SALARYCODES,
ID_WF_ACTION, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE ) VALUES ( 
SEQ_EGPAY_NOMINATION_HEADER.nextval, 'NOMPF', 'Nomination for PF', NULL, (select id from EGPAY_SALARYCODES where head='PF'), NULL, 1,  TO_Date( '02/12/2010 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 1,  TO_Date( '02/12/2010 08:10:34 AM', 'MM/DD/YYYY HH:MI:SS AM')); 


#DOWN

