/* Formatted on 2009/12/17 02:12 (Formatter Plus v4.8.5) */
#UP


/* INSERT INTO CHARTOFACCOUNTS ( ID, GLCODE, NAME, DESCRIPTION, ISACTIVEFORPOSTING, PARENTID,
LASTMODIFIED, MODIFIEDBY, CREATED, PURPOSEID, OPERATION, TYPE, CLASS, CLASSIFICATION, FUNCTIONREQD,
BUDGETCHECKREQ, SCHEDULEID, RECEIPTSCHEDULEID, RECEIPTOPERATION, PAYMENTSCHEDULEID,
PAYMENTOPERATION, MAJORCODE, CREATEDBY ) VALUES ( 
SEQ_CHARTOFACCOUNTS.NEXTVAL, '2205101', 'LEGAL EXPENSES-LEGAL FEES-CORPORATION STANDING COUNCILS', NULL
, 1, 627,  TO_Date( '10/14/2009 06:51:03 AM', 'MM/DD/YYYY HH:MI:SS AM'), 1,  TO_Date( '10/14/2009 06:51:03 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 40, NULL, 'E', NULL, 4, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
INSERT INTO CHARTOFACCOUNTS ( ID, GLCODE, NAME, DESCRIPTION, ISACTIVEFORPOSTING, PARENTID,
LASTMODIFIED, MODIFIEDBY, CREATED, PURPOSEID, OPERATION, TYPE, CLASS, CLASSIFICATION, FUNCTIONREQD,
BUDGETCHECKREQ, SCHEDULEID, RECEIPTSCHEDULEID, RECEIPTOPERATION, PAYMENTSCHEDULEID,
PAYMENTOPERATION, MAJORCODE, CREATEDBY ) VALUES ( 
SEQ_CHARTOFACCOUNTS.NEXTVAL, '2205102', 'LEGAL EXPENSES-EXPENSES FOR FILING CASES', NULL, 1, 628,  TO_Date( '10/14/2009 06:51:03 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 1,  TO_Date( '10/14/2009 06:51:03 AM', 'MM/DD/YYYY HH:MI:SS AM'), 40, NULL, 'E'
, NULL, 4, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 
*/

INSERT INTO CHARTOFACCOUNTS ( ID, GLCODE, NAME, DESCRIPTION, ISACTIVEFORPOSTING, PARENTID,
LASTMODIFIED, MODIFIEDBY, CREATED, PURPOSEID, OPERATION, TYPE, CLASS, CLASSIFICATION, FUNCTIONREQD,
BUDGETCHECKREQ, SCHEDULEID, RECEIPTSCHEDULEID, RECEIPTOPERATION, PAYMENTSCHEDULEID,
PAYMENTOPERATION, MAJORCODE, CREATEDBY ) VALUES ( 
SEQ_CHARTOFACCOUNTS.NEXTVAL, '2205105', 'LEGAL EXPENSES-EXPENSES FOR FILING CASES', NULL, 1, 123, sysdate
, 1, sysdate, 59, NULL, 'E'
, NULL, 4, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 

UPDATE CHARTOFACCOUNTS SET PURPOSEID=59 WHERE GLCODE='2205101';

INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='E R K MOORTHY'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='R K KALPANA'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='T MATHI'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='MD GHOUSE'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='G T SUBRAMANIAM'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='L N PRAGHASHAM'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='V BHARATHIDASAN'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='P UDAYAKUMAR'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='J S MAHALINGAM'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='D SURESH'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='B VENUGOPAL'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='V MURALI'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='N SUBRAMANI'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='P GANESAN'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='G JAGANATHAN'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='K SURENDRAN'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='S EZHILAN'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='V NANMARAN GOPIKRISHNAN'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='K VELAYUDHAM'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='G SRIRAM'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='R JAISHANKARAN'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='T BABU'));
INSERT INTO ACCOUNTDETAILKEY ( ID, GROUPID, GLCODEID, DETAILTYPEID, DETAILNAME,DETAILKEY ) VALUES (SEQ_ACCOUNTDETAILKEY.nextval,1, NULL,(select id from ACCOUNTDETAILTYPE where name='lawyer'),'eglc_legalcase_advocate_id',(select id from EGLC_ADVOCATE_MASTER where ADVOCATE_NAME='Paranthaman'));

INSERT INTO CHARTOFACCOUNTDETAIL ( ID, GLCODEID, DETAILTYPEID, MODIFIEDBY, MODIFIEDDATE, CREATEDBY,
CREATEDDATE ) VALUES ( 
SEQ_CHARTOFACCOUNTDETAIL.nextval, (select id from chartofaccounts where glcode='2205101'), (select id from ACCOUNTDETAILTYPE where name='lawyer'), NULL, NULL, NULL, NULL); 

INSERT INTO CHARTOFACCOUNTDETAIL ( ID, GLCODEID, DETAILTYPEID, MODIFIEDBY, MODIFIEDDATE, CREATEDBY,
CREATEDDATE ) VALUES ( 
SEQ_CHARTOFACCOUNTDETAIL.nextval, (select id from chartofaccounts where glcode='2205105'), (select id from ACCOUNTDETAILTYPE where name='lawyer'), NULL, NULL, NULL, NULL); 


#DOWN