#UP
INSERT INTO CHARTOFACCOUNTS ( ID, GLCODE, NAME, DESCRIPTION, ISACTIVEFORPOSTING, PARENTID,
LASTMODIFIED, MODIFIEDBY, CREATED, PURPOSEID, OPERATION, TYPE, CLASS, CLASSIFICATION, FUNCTIONREQD,
BUDGETCHECKREQ, SCHEDULEID, RECEIPTSCHEDULEID, RECEIPTOPERATION, PAYMENTSCHEDULEID,
PAYMENTOPERATION, MAJORCODE, CREATEDBY ) VALUES ( 
SEQ_CHARTOFACCOUNTS.NEXTVAL, '2205106', 'LEGAL EXPENSES-RETAINER FEES', NULL
, 1, 123,  TO_Date( '10/14/2009 06:51:03 AM', 'MM/DD/YYYY HH:MI:SS AM'), 1,  TO_Date( '10/14/2009 06:51:03 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL, 'E', NULL, 4, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 

INSERT INTO CHARTOFACCOUNTDETAIL ( ID, GLCODEID, DETAILTYPEID, MODIFIEDBY, MODIFIEDDATE, CREATEDBY,
CREATEDDATE ) VALUES ( 
SEQ_CHARTOFACCOUNTDETAIL.nextval, (select id from chartofaccounts where glcode='2205106'), (select id from ACCOUNTDETAILTYPE where name='lawyer'), NULL, NULL, NULL, NULL); 

INSERT INTO EG_APPCONFIG_VALUES (ID, KEY_ID, EFFECTIVE_FROM, VALUE) VALUES (SEQ_EG_APPCONFIG_VALUES.nextval, (select ID from EG_APPCONFIG where KEY_NAME='LEGALCASE_COA_DEBITCODE_FOR_RSF'),  TO_Date( '04/08/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), '2205106');

INSERT INTO EG_ROLEACTION_MAP ( ROLEID, ACTIONID ) VALUES ( 
(select ID_ROLE from eg_roles where ROLE_NAME like 'LAW OFFICER'),
(select ID from EG_ACTION where NAME like 'RetainerShip Fees')); 
update eglc_advocate_master set monthly_renumeration=1000, paymentmode='Cash';

UPDATE EG_APPCONFIG_VALUES SET VALUE = '0101'
WHERE KEY_ID = (select ID from EG_APPCONFIG where KEY_NAME='LEGALCASE_FUND_CODE');

#DOWN