#UP
INSERT INTO EG_APPCONFIG_VALUES
  (
    ID,
    KEY_ID,
    EFFECTIVE_FROM,
    VALUE
  )
  VALUES
  (
    SEQ_EG_APPCONFIG_VALUES.nextval,
    (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='WORKS_NETPAYABLE_CODE'
    ),
    TO_Date( '04/08/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'),
    '26'
  );

#DOWN
DELETE FROM EG_APPCONFIG_VALUES where key_id = (select id from EG_APPCONFIG where KEY_NAME = 'WORKS_NETPAYABLE_CODE');

