#UP
INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='STANDARD_DEDUCTION'),  SYSDATE, 
'Tender Deposit-Revenue:2205102|Tender Deposit-Capital:46040|Security Deposit-Revenue:1801001|Security Deposit-Capital:3402002|Retention Money-Revenue:3401002|Retention Money-Capital:3401002|Forms-Publications-Tenders:1501101');

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='CUSTOM_DEDUCTION'),  SYSDATE, 'I,L'); 


#DOWN
DELETE FROM EG_APPCONFIG_VALUES WHERE KEY_ID IN (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='CUSTOM_DEDUCTION')
AND VALUE = 'I,L';

DELETE FROM EG_APPCONFIG_VALUES WHERE KEY_ID IN (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='STANDARD_DEDUCTION')
AND VALUE = 'Tender Deposit-Revenue:2205102|Tender Deposit-Capital:46040|Security Deposit-Revenue:1801001|Security Deposit-Capital:3402002|Retention Money-Revenue:3401002|Retention Money-Capital:3401002|Forms-Publications-Tenders:1501101';

