#UP


INSERT INTO EG_WF_STATES ( ID, TYPE, VALUE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE,
OWNER, DATE1, DATE2, TEXT1, TEXT2, PREVIOUS, NEXT ) VALUES ( 
EG_WF_STATES_SEQ.NEXTVAL, 'Budget', (SELECT value FROM EG_APPCONFIG_VALUES WHERE key_id IN(SELECT id FROM EG_APPCONFIG WHERE key_name='budget_final_approval_status')), NULL,  TO_DATE( '08/27/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL,  TO_DATE( '08/27/2009 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL, NULL, NULL, 'workflow.start', NULL, NULL, NULL); 




---- This is for Budget detail

INSERT INTO EGF_BUDGETDETAIL
   (ID, BUDGETGROUP, BUDGET, ORIGINALAMOUNT, APPROVEDAMOUNT, BUDGETAVAILABLE, FUNCTION, STATE_ID, MODIFIEDDATE, SCHEME, SUBSCHEME,EXECUTING_DEPARTMENT,BOUNDARY, FUND)
 VALUES
   (seq_egf_budgetdetail.NEXTVAL,(SELECT id FROM EGF_BUDGETGROUP WHERE name='41120-BUILDING WORKS'),
   (SELECT id FROM EGF_BUDGET WHERE name='2010-2011-BE'), 20000000, 20000000, 20000000, (SELECT id FROM FUNCTION WHERE code='0201')
   , NULL, TO_DATE('11/16/2008 22:15:19', 'MM/DD/YYYY HH24:MI:SS'),NULL, NULL,(SELECT id_dept FROM EG_DEPARTMENT WHERE dept_name='BR-Bus Route Roads'),null, (SELECT id FROM FUND WHERE code='0102'));
   

INSERT INTO EGF_BUDGETDETAIL
   (ID, BUDGETGROUP, BUDGET, ORIGINALAMOUNT, APPROVEDAMOUNT, BUDGETAVAILABLE, FUNCTION, STATE_ID, MODIFIEDDATE, SCHEME, SUBSCHEME,EXECUTING_DEPARTMENT,BOUNDARY, FUND)
 VALUES
   (seq_egf_budgetdetail.NEXTVAL,(SELECT id FROM EGF_BUDGETGROUP WHERE name='41120-BUILDING WORKS'),
   (SELECT id FROM EGF_BUDGET WHERE name='2010-2011-BE'), 10000000, 10000000, 10000000, (SELECT id FROM FUNCTION WHERE code='0101')
   , NULL, TO_DATE('11/16/2008 22:15:19', 'MM/DD/YYYY HH24:MI:SS'),NULL, NULL,(SELECT id_dept FROM EG_DEPARTMENT WHERE dept_name='BR-Bus Route Roads'),null, (SELECT id FROM FUND WHERE code='0102'));

	UPDATE eg_wf_states SET owner=(SELECT id FROM eg_position WHERE position_name='EGFCOMMISSIONER') WHERE id=(SELECT id FROM eg_wf_states WHERE id =(SELECT state_id FROM egf_budget WHERE name='2010-2011-BE'));




#DOWN
