
#UP

INSERT INTO EGF_OPENINGBALANCE_JOBDETAIL   (
SELECT  SEQ_STORESOPENBALANCEJOBDETAIL.NEXTVAL, (SELECT id FROM FINANCIALYEAR WHERE FINANCIALYEAR='2009-10')  AS FINANCIALYEARid,id AS storeid ,SYSDATE,
(SELECT id FROM EGW_STATUS WHERE moduletype='STORES_OB' AND description='Approved') AS statusid
 FROM EG_STORES  );
 
#DOWN
 DELETE FROM EGF_OPENINGBALANCE_JOBDETAIL;