#UP
INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES
(SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='add_less_codes_for_ie_report'),  SYSDATE, '280-Add,290-Less'); 

#DOWN
delete from EG_APPCONFIG_VALUES where  KEY_ID in (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='add_less_codes_for_ie_report');