#UP
INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='WORK_ORDER_CREATEDBY'),SYSDATE, 'no'); 
INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='WORK_ORDER_PASTDATE'),SYSDATE, 'yes');
#DOWN
delete from EG_APPCONFIG_VALUES where key_id in (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='WORK_ORDER_CREATEDBY') ;
delete from EG_APPCONFIG_VALUES where key_id in (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='WORK_ORDER_PASTDATE') ;
