#UP
INSERT INTO EG_APPCONFIG ( ID, KEY_NAME, DESCRIPTION, MODULE ) VALUES 
(SEQ_EG_APPCONFIG.NEXTVAL, 'NATUREOFWORKFORASSETCAPITALISATION', 'NATURE OF WORK FOR ASSET CAPITALISATION', 'Works'); 

INSERT INTO EG_APPCONFIG_VALUES
   (ID, KEY_ID, EFFECTIVE_FROM, VALUE)
 VALUES
(SEQ_EG_APPCONFIG_VALUES.nextval,(SELECT ID FROM  eg_appconfig WHERE key_name='NATUREOFWORKFORASSETCAPITALISATION'), SYSDATE, 'Capital Works - New Asset,Deposit Works - Own Asset');


#DOWN

DELETE FROM EG_APPCONFIG_VALUES WHERE KEY_ID IN (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='NATUREOFWORKFORASSETCAPITALISATION');
DELETE FROM EG_APPCONFIG WHERE KEY_NAME='NATUREOFWORKFORASSETCAPITALISATION';


