#UP

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='SLDEPOSITCODE_SHOW_FUNDS'),SYSDATE, 'DEP,MP,MLA'); 


#DOWN

DELETE FROM EG_APPCONFIG_VALUES where KEY_ID in (select id from EG_APPCONFIG where KEY_NAME='SLDEPOSITCODE_SHOW_FUNDS');


