#UP

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='BILL_STATUTORYDEDUCTIONS_EDITABLE'),SYSDATE, 'yes'); 

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='BILL_STATUTORYDEDUCTIONS_SHOW_PARTYSUBTYPE'),SYSDATE, 'yes'); 

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES ( 
SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT id FROM EG_APPCONFIG WHERE KEY_NAME='BILL_STATUTORYDEDUCTIONS_SHOW_SERVICETYPE'),SYSDATE, 'yes'); 


#DOWN

DELETE FROM EG_APPCONFIG_VALUES where KEY_ID in (select id from EG_APPCONFIG where KEY_NAME='BILL_STATUTORYDEDUCTIONS_EDITABLE');

DELETE FROM EG_APPCONFIG_VALUES where KEY_ID in (select id from EG_APPCONFIG where KEY_NAME='BILL_STATUTORYDEDUCTIONS_SHOW_PARTYSUBTYPE');

DELETE FROM EG_APPCONFIG_VALUES where KEY_ID in (select id from EG_APPCONFIG where KEY_NAME='BILL_STATUTORYDEDUCTIONS_SHOW_SERVICETYPE');


