#UP

INSERT INTO EG_NUMBER_GENERIC (ID,OBJECTTYPE,"VALUE") VALUES (SEQ_EG_NUMBER_GENERIC.NEXTVAL,'PROJECTCODE-2011-12',0);

#DOWN

DELETE FROM EG_NUMBER_GENERIC WHERE OBJECTTYPE='PROJECTCODE-2011-12';
