#UP

INSERT INTO EG_APPCONFIG_VALUES ( ID, KEY_ID, EFFECTIVE_FROM, VALUE ) VALUES
(SEQ_EG_APPCONFIG_VALUES.NEXTVAL, (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='GJV_FOR_RCPT_CHQ_DISHON'),  SYSDATE, 'N');


#DOWN

DELETE FROM EG_APPCONFIG_VALUES WHERE KEY_ID = (SELECT ID FROM EG_APPCONFIG WHERE KEY_NAME='GJV_FOR_RCPT_CHQ_DISHON');

