#UP

INSERT INTO EGLEMS_DEMANDREASONTYPE(ID,TYPE,REASONNAME,GLCODE, ISACTIVE,DESCRIPTION,PURPOSEID)
VALUES(SEQ_EGLEMS_DEMANDREASONTYPE.NEXTVAL,'LAND','ADVANCE','3504103',1,'Advance','LandEstate_Advance_purpose');

INSERT INTO EGLEMS_DEMANDREASONTYPE(ID,TYPE,REASONNAME,GLCODE, ISACTIVE,DESCRIPTION,PURPOSEID)
VALUES(SEQ_EGLEMS_DEMANDREASONTYPE.NEXTVAL,'HOARDINGS','ADVANCE','3504103',1,'Advance','LandEstate_Advance_purpose');



#DOWN

DELETE FROM EGLEMS_DEMANDREASONTYPE WHERE TYPE = 'LAND' and description='ADVANCE';

DELETE FROM EGLEMS_DEMANDREASONTYPE WHERE TYPE = 'HOARDINGS' and description='ADVANCE';
