#UP

-- script for  EG_WF_MATRIX 

-- Abstract Estimate 

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','budgetApp','CREATED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','TECH_SANCTIONED',null,'Pending Budgetary Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','budgetApp','FINANCIALLY_SANCTIONED','Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','FINANCIALLY_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','budgetApp','FINANCIALLY_SANCTIONED','Pending Admin Sanction','Municipal Commissioner','FINANCIALLY_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Admin Sanction','Municipal Commissioner','budgetApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','budgetApp','RESUBMITTED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','budgetApp','CREATED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','TECH_SANCTIONED',null,'Pending Budgetary Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','budgetApp','FINANCIALLY_SANCTIONED','Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','FINANCIALLY_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','budgetApp','FINANCIALLY_SANCTIONED','Pending Admin Sanction','Municipal Commissioner','FINANCIALLY_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Admin Sanction','Municipal Commissioner','budgetApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','budgetApp','RESUBMITTED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','budgetApp','CREATED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','TECH_SANCTIONED',null,'Pending Budgetary Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','budgetApp','FINANCIALLY_SANCTIONED','Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','FINANCIALLY_SANCTIONED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','budgetApp','FINANCIALLY_SANCTIONED','Pending Admin Check','Municipal Commissioner','FINANCIALLY_SANCTIONED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Admin Check','Municipal Commissioner','budgetApp','ADMIN_CHECKED','Pending Admin Sanction','Municipal Commissioner','ADMIN_CHECKED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','ADMIN_CHECKED',null,'Pending Admin Sanction','Municipal Commissioner','budgetApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','budgetApp','RESUBMITTED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','budgetApp','TECH_SANCTIONED','Pending Budgetary Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','depositCodeApp','CREATED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Deposit Code Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','TECH_SANCTIONED',null,'Pending Deposit Code Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','depositCodeApp','FINANCIALLY_SANCTIONED','Pending Deposit Code Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','FINANCIALLY_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Deposit Code Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','depositCodeApp','FINANCIALLY_SANCTIONED','Pending Admin Sanction','Municipal Commissioner','FINANCIALLY_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Admin Sanction','Municipal Commissioner','depositCodeApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','depositCodeApp','RESUBMITTED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Deposit Code Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',0,500000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','depositCodeApp','CREATED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Deposit Code Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','TECH_SANCTIONED',null,'Pending Deposit Code Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','depositCodeApp','FINANCIALLY_SANCTIONED','Pending Deposit Code Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','FINANCIALLY_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Deposit Code Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','depositCodeApp','FINANCIALLY_SANCTIONED','Pending Admin Sanction','Municipal Commissioner','FINANCIALLY_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Admin Sanction','Municipal Commissioner','depositCodeApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','depositCodeApp','RESUBMITTED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Deposit Code Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',500000.1,1000000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','depositCodeApp','CREATED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','CREATED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Deposit Code Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','TECH_SANCTIONED',null,'Pending Deposit Code Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','depositCodeApp','FINANCIALLY_SANCTIONED','Pending Deposit Code Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','FINANCIALLY_SANCTIONED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Deposit Code Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','depositCodeApp','FINANCIALLY_SANCTIONED','Pending Admin Check','Municipal Commissioner','FINANCIALLY_SANCTIONED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Admin Check','Municipal Commissioner','depositCodeApp','ADMIN_CHECKED','Pending Admin Sanction','Municipal Commissioner','ADMIN_CHECKED','Forward,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','ADMIN_CHECKED',null,'Pending Admin Sanction','Municipal Commissioner','depositCodeApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','depositCodeApp','RESUBMITTED','Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',1000000.1,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','RESUBMITTED',null,'Pending Approval for Technical Sanction','EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Deposit Code Appropriation By ASSISTANT SUPERINTENDENT/SUPERINTENDENT','ASSISTANT SUPERINTENDENT,SUPERINTENDENT','TECH_SANCTIONED','Forward,Reject',1000000.1,null);


--ContractorBillRegister

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','CREATED',null,'Pending for Check','EXECUTIVE ENGINEER',null,'CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','NEW',null,null,'JUNIOR ENGINEER',null,'CREATED','Pending for Check','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','REJECTED',null,null,'JUNIOR ENGINEER',null,'RESUBMITTED','Pending for Check','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','ContractorBillRegister','RESUBMITTED',null,'Pending for Check','EXECUTIVE ENGINEER',null,'CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);



-- Indent 

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','Indent','CREATED',null,'Pending for Approval','EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','Indent','NEW',null,null,'EXECUTIVE ENGINEER',null,'CREATED','Pending for Approval','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','Indent','REJECTED',null,null,'EXECUTIVE ENGINEER',null,'RESUBMITTED','Pending for Approval','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','Indent','RESUBMITTED',null,'Pending for Approval','EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);


--MBHeader

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','CHECKED',null,'Pending for Approval','EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','CREATED',null,'Pending for check','EXECUTIVE ENGINEER',null,'CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','NEW',null,null,'JUNIOR ENGINEER',null,'CREATED','Pending for check','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','REJECTED',null,null,'JUNIOR ENGINEER',null,'RESUBMITTED','Pending for check','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','MBHeader','RESUBMITTED',null,'Pending for check','EXECUTIVE ENGINEER',null,'CHECKED','Pending for Approval','EXECUTIVE ENGINEER','CHECKED','Forward,Reject',null,null);


-- indent rate contract

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RateContract','CREATED',null,'Pending for Approval','EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RateContract','NEW',null,null,'EXECUTIVE ENGINEER',null,'CREATED','Pending for Approval','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RateContract','REJECTED',null,null,'EXECUTIVE ENGINEER',null,'RESUBMITTED','Pending for Approval','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RateContract','RESUBMITTED',null,'Pending for Approval','EXECUTIVE ENGINEER',null,'APPROVED','END',null,'APPROVED','Approve,Reject',null,null);


-- RevisionAbstractEstimate

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','moreExtraItemCost','CREATED','Pending for Technical Sanction','EXECUTIVE ENGINEER','CREATED','Forward',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','CREATED',null,'Pending for Technical Sanction','EXECUTIVE ENGINEER','moreExtraItemCost','TECH_SANCTIONED','Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','TECH_SANCTIONED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','TECH_SANCTIONED',null,'Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','moreExtraItemCost','FINANCIALLY_SANCTIONED','Pending Admin Sanction','EXECUTIVE ENGINEER','ADMIN_SANCTIONED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Admin Sanction','EXECUTIVE ENGINEER','moreExtraItemCost','ADMIN_SANCTIONED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','moreExtraItemCost','RESUBMITTED','Pending for Technical Sanction','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','RESUBMITTED',null,'Pending for Technical Sanction','EXECUTIVE ENGINEER','moreExtraItemCost','TECH_SANCTIONED','Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','TECH_SANCTIONED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','lessExtraItemCost','CREATED','Pending for Technical Sanction','EXECUTIVE ENGINEER','CREATED','Forward',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','CREATED',null,'Pending for Technical Sanction','EXECUTIVE ENGINEER','lessExtraItemCost','TECH_SANCTIONED','END','null','APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','lessExtraItemCost','RESUBMITTED','Pending for Technical Sanction','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','RESUBMITTED',null,'Pending for Technical Sanction','EXECUTIVE ENGINEER','lessExtraItemCost','TECH_SANCTIONED','END','NULL','APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','moreAdditionalItemCost','CREATED','Pending for Technical Sanction','EXECUTIVE ENGINEER','CREATED','Forward',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','CREATED',null,'Pending for Technical Sanction','EXECUTIVE ENGINEER','moreAdditionalItemCost','TECH_SANCTIONED','Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','TECH_SANCTIONED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','TECH_SANCTIONED',null,'Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','moreAdditionalItemCost','FINANCIALLY_SANCTIONED','Pending Admin Sanction','EXECUTIVE ENGINEER','ADMIN_SANCTIONED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','FINANCIALLY_SANCTIONED',null,'Pending Admin Sanction','EXECUTIVE ENGINEER','moreAdditionalItemCost','ADMIN_SANCTIONED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','moreAdditionalItemCost','RESUBMITTED','Pending for Technical Sanction','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','RESUBMITTED',null,'Pending for Technical Sanction','EXECUTIVE ENGINEER','moreAdditionalItemCost','TECH_SANCTIONED','Pending Budgetary Appropriation By Chief Accounts and Finance Officer','Chief Accounts and Finance Officer','TECH_SANCTIONED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','lessAdditionalItemCost','CREATED','Pending for Technical Sanction','EXECUTIVE ENGINEER','CREATED','Forward',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','CREATED',null,'Pending for Technical Sanction','EXECUTIVE ENGINEER','lessAdditionalItemCost','TECH_SANCTIONED','END','null','APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','lessAdditionalItemCost','RESUBMITTED','Pending for Technical Sanction','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','RevisionAbstractEstimate','RESUBMITTED',null,'Pending for Technical Sanction','EXECUTIVE ENGINEER','lessAdditionalItemCost','TECH_SANCTIONED','END','NULL','APPROVED','Approve,Reject',null,null);


--TenderFile

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CHECKED',null,'Pending for Approval','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','quotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CREATED',null,'Pending for Approval','EXECUTIVE ENGINEER','noQuotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','CREATED',null,'Pending for Check','EXECUTIVE ENGINEER','quotation','CHECKED','Pending for Approval','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','CHECKED','Forward,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','NEW',null,null,'EXECUTIVE ENGINEER','noQuotation','CREATED','Pending for Approval','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','NEW',null,null,'JUNIOR ENGINEER','quotation','CREATED','Pending for Check','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','REJECTED',null,null,'EXECUTIVE ENGINEER','noQuotation','RESUBMITTED','Pending for Approval','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','REJECTED',null,null,'JUNIOR ENGINEER','quotation','RESUBMITTED','Pending for Check','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','RESUBMITTED',null,'Pending for Approval','EXECUTIVE ENGINEER','noQuotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','TenderFile','RESUBMITTED',null,'Pending for Check','EXECUTIVE ENGINEER','quotation','CHECKED','Pending for Approval','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','CHECKED','Forward,Reject',null,null);


--Work Order

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','NEW',null,null,'EXECUTIVE ENGINEER','noQuotation','CREATED','Pending for Approval','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending for Approval','EXECUTIVE ENGINEER','noQuotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending for Approval','EXECUTIVE ENGINEER','noQuotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','REJECTED',null,null,'EXECUTIVE ENGINEER','noQuotation','RESUBMITTED','Pending for Approval','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','NEW',null,null,'EXECUTIVE ENGINEER','quotation','CREATED','Pending for Approval','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending for Approval','EXECUTIVE ENGINEER','quotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending for Approval','EXECUTIVE ENGINEER','quotation','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','REJECTED',null,null,'EXECUTIVE ENGINEER','quotation','RESUBMITTED','Pending for Approval','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','NEW',null,null,'EXECUTIVE ENGINEER','rateContract','CREATED','Pending for Approval','EXECUTIVE ENGINEER','CREATED','Forward,Cancel',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','RESUBMITTED',null,'Pending for Approval','EXECUTIVE ENGINEER','rateContract','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','CREATED',null,'Pending for Approval','EXECUTIVE ENGINEER','rateContract','APPROVED','END',null,'APPROVED','Approve,Reject',null,null);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','WorkOrder','REJECTED',null,null,'EXECUTIVE ENGINEER','rateContract','RESUBMITTED','Pending for Approval','EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',null,null);

#DOWN

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='AbstractEstimate';

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='ContractorBillRegister';

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='Indent';

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='MBHeader';

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='RateContract';

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='RevisionAbstractEstimate';

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='TenderFile';

delete from EG_WF_MATRIX where DEPARTMENT='Public Work' and OBJECTTYPE='WorkOrder';
