#UP

-- Estimate Quotation wf matrix script

--Electrical   (budget App)

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','budgetApp','CREATED','Pending checking for Technical Sanction','ASSISTANT ENGINEER','CREATED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','CREATED',null,'Pending checking for Technical Sanction','ASSISTANT ENGINEER','budgetApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','EXECUTIVE ENGINEER,ASST. COMMISSIONER / WARD OFFICER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','TECH_SANCTION_CHECKED',null,'Pending Admin Sanction','EXECUTIVE ENGINEER,ASST. COMMISSIONER / WARD OFFICER','budgetApp','TECH_SANCTIONED','Pending Admin Sanction','EXECUTIVE ENGINEER,ASST. COMMISSIONER / WARD OFFICER','TECH_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','TECH_SANCTIONED',null,'Pending Admin Sanction','EXECUTIVE ENGINEER,ASST. COMMISSIONER / WARD OFFICER','budgetApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','budgetApp','RESUBMITTED','Pending checking for Technical Sanction','ASSISTANT ENGINEER','RESUBMITTED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','RESUBMITTED',null,'Pending checking for Technical Sanction','ASSISTANT ENGINEER','budgetApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','EXECUTIVE ENGINEER,ASST. COMMISSIONER / WARD OFFICER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);

--Electrical   (Deposit Code App)

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','depositCodeApp','CREATED','Pending checking for Technical Sanction','ASSISTANT ENGINEER','CREATED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','CREATED',null,'Pending checking for Technical Sanction','ASSISTANT ENGINEER','depositCodeApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','EXECUTIVE ENGINEER,ASST. COMMISSIONER / WARD OFFICER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','TECH_SANCTION_CHECKED',null,'Pending Admin Sanction','EXECUTIVE ENGINEER,ASST. COMMISSIONER / WARD OFFICER','depositCodeApp','TECH_SANCTIONED','Pending Admin Sanction','EXECUTIVE ENGINEER,ASST. COMMISSIONER / WARD OFFICER','TECH_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','TECH_SANCTIONED',null,'Pending Admin Sanction','EXECUTIVE ENGINEER,ASST. COMMISSIONER / WARD OFFICER','depositCodeApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','depositCodeApp','RESUBMITTED','Pending checking for Technical Sanction','ASSISTANT ENGINEER','RESUBMITTED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Electrical','AbstractEstimate','RESUBMITTED',null,'Pending checking for Technical Sanction','ASSISTANT ENGINEER','depositCodeApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','EXECUTIVE ENGINEER,ASST. COMMISSIONER / WARD OFFICER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);



--Public Work (budget App)

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','budgetApp','CREATED','Pending checking for Technical Sanction','DEPUTY ENGINEER','CREATED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','CREATED',null,'Pending checking for Technical Sanction','DEPUTY ENGINEER','budgetApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','TECH_SANCTION_CHECKED',null,'Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','budgetApp','TECH_SANCTIONED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','TECH_SANCTIONED',null,'Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','budgetApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','budgetApp','RESUBMITTED','Pending checking for Technical Sanction','DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','RESUBMITTED',null,'Pending checking for Technical Sanction','DEPUTY ENGINEER','budgetApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);

--Public Work (Deposit Code App)

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER','depositCodeApp','CREATED','Pending checking for Technical Sanction','DEPUTY ENGINEER','CREATED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','CREATED',null,'Pending checking for Technical Sanction','DEPUTY ENGINEER','depositCodeApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','TECH_SANCTION_CHECKED',null,'Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','depositCodeApp','TECH_SANCTIONED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','TECH_SANCTIONED',null,'Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','depositCodeApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER','depositCodeApp','RESUBMITTED','Pending checking for Technical Sanction','DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Public Work','AbstractEstimate','RESUBMITTED',null,'Pending checking for Technical Sanction','DEPUTY ENGINEER','depositCodeApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);




--Water Works (Budget App)

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER,ASSISTANT ENGINEER','budgetApp','CREATED','Pending checking for Technical Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','CREATED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','CREATED',null,'Pending checking for Technical Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','budgetApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','TECH_SANCTION_CHECKED',null,'Pending Admin Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','budgetApp','TECH_SANCTIONED','Pending Admin Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','TECH_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','TECH_SANCTIONED',null,'Pending Admin Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','budgetApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER,ASSISTANT ENGINEER','budgetApp','RESUBMITTED','Pending checking for Technical Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','RESUBMITTED',null,'Pending checking for Technical Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','budgetApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);


--Water Works (Deposit Code App)

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','NEW',null,null,'JUNIOR ENGINEER,ASSISTANT ENGINEER','depositCodeApp','CREATED','Pending checking for Technical Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','CREATED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','CREATED',null,'Pending checking for Technical Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','TECH_SANCTION_CHECKED',null,'Pending Admin Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTIONED','Pending Admin Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','TECH_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','TECH_SANCTIONED',null,'Pending Admin Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','depositCodeApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','REJECTED',null,null,'JUNIOR ENGINEER,ASSISTANT ENGINEER','depositCodeApp','RESUBMITTED','Pending checking for Technical Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','RESUBMITTED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Water Works','AbstractEstimate','RESUBMITTED',null,'Pending checking for Technical Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','depositCodeApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','ASSISTANT ENGINEER,SPECIAL DESK OFFICER,EXECUTIVE ENGINEER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);




--Garden (Budget App)

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','NEW',null,null,'Garden Inspector,JUNIOR ENGINEER','budgetApp','CREATED','Pending checking for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','CREATED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','CREATED',null,'Pending checking for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','budgetApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','TECH_SANCTION_CHECKED',null,'Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','budgetApp','TECH_SANCTIONED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','TECH_SANCTIONED',null,'Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','budgetApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','REJECTED',null,null,'Garden Inspector,JUNIOR ENGINEER','budgetApp','RESUBMITTED','Pending checking for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','RESUBMITTED',null,'Pending checking for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','budgetApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);


--Garden (Deposit Code App)

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','NEW',null,null,'Garden Inspector,JUNIOR ENGINEER','depositCodeApp','CREATED','Pending checking for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','CREATED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','CREATED',null,'Pending checking for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','depositCodeApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','TECH_SANCTION_CHECKED',null,'Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','depositCodeApp','TECH_SANCTIONED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','TECH_SANCTIONED',null,'Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','depositCodeApp','ADMIN_SANCTIONED','END',null,'ADMIN_SANCTIONED','Approve,Reject',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','REJECTED',null,null,'Garden Inspector,JUNIOR ENGINEER','depositCodeApp','RESUBMITTED','Pending checking for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','RESUBMITTED','Forward,Cancel',0,50000);

Insert into EG_WF_MATRIX (ID,DEPARTMENT,OBJECTTYPE,CURRENTSTATE,CURRENTSTATUS,PENDINGACTIONS,CURRENTDESIGNATION,ADDITIONALRULE,NEXTSTATE,NEXTACTION,NEXTDESIGNATION,NEXTSTATUS,VALIDACTIONS,FROMQTY,TOQTY) values (EG_WF_MATRIX_SEQ.nextVal,'Garden','AbstractEstimate','RESUBMITTED',null,'Pending checking for Technical Sanction','Garden Superintendent,DEPUTY ENGINEER','depositCodeApp','TECH_SANCTION_CHECKED','Pending Admin Sanction','Addl. Dy. Municipal Commissioner,DEPUTY MUNICIPAL COMMISSIONER','TECH_SANCTION_CHECKED','Forward,Reject',0,50000);

#DOWN

delete from  EG_WF_MATRIX  where  DEPARTMENT in ('Public Work','Water Works','Electrical','Garden')  and  FROMQTY=0 and OBJECTTYPE='AbstractEstimate';
