#UP

Insert into EG_WF_MATRIX
   (ID,  OBJECTTYPE, CURRENTSTATE,PENDINGACTIONS,CURRENTDESIGNATION, NEXTSTATE, NEXTACTION, NEXTDESIGNATION, NEXTSTATUS, VALIDACTIONS)
 Values
   (EG_WF_MATRIX_SEQ.nextVal,  'WorkCompletionDetail', 'NEW',null, 'JUNIOR ENGINEER,Garden Inspector', 'CREATED', 'Pending for Check', 'DEPUTY ENGINEER,ASSISTANT ENGINEER', 'CHECKED', 'Forward');

Insert into EG_WF_MATRIX
   (ID,  OBJECTTYPE, CURRENTSTATE,PENDINGACTIONS,CURRENTDESIGNATION, NEXTSTATE, NEXTACTION, NEXTDESIGNATION, NEXTSTATUS, VALIDACTIONS)
 Values
   (EG_WF_MATRIX_SEQ.nextVal,  'WorkCompletionDetail', 'CREATED','Pending for Check', 'DEPUTY ENGINEER,ASSISTANT ENGINEER', 'CHECKED', 'Pending for Approval', 'EXECUTIVE ENGINEER', 'APPROVED', 'Forward,Reject');

Insert into EG_WF_MATRIX
   (ID,  OBJECTTYPE, CURRENTSTATE,PENDINGACTIONS,CURRENTDESIGNATION, NEXTSTATE, NEXTACTION, NEXTDESIGNATION, NEXTSTATUS, VALIDACTIONS)
 Values
   (EG_WF_MATRIX_SEQ.nextVal,  'WorkCompletionDetail', 'CHECKED','Pending for Approval', 'EXECUTIVE ENGINEER', 'APPROVED', 'END', null, 'APPROVED', 'Approve,Reject');

Insert into EG_WF_MATRIX
   (ID,  OBJECTTYPE, CURRENTSTATE,PENDINGACTIONS,CURRENTDESIGNATION, NEXTSTATE, NEXTACTION, NEXTDESIGNATION, NEXTSTATUS, VALIDACTIONS)
 Values
   (EG_WF_MATRIX_SEQ.nextVal, 'WorkCompletionDetail', 'REJECTED',null, 'JUNIOR ENGINEER,Garden Inspector', 'RESUBMITTED', 'Pending for Check', 'DEPUTY ENGINEER,ASSISTANT ENGINEER', 'RESUBMITTED', 'Forward,Cancel');

Insert into EG_WF_MATRIX
   (ID, OBJECTTYPE, CURRENTSTATE,PENDINGACTIONS,CURRENTDESIGNATION, NEXTSTATE, NEXTACTION, NEXTDESIGNATION, NEXTSTATUS, VALIDACTIONS)
 Values
   (EG_WF_MATRIX_SEQ.nextVal,  'WorkCompletionDetail', 'RESUBMITTED','Pending for Check', 'DEPUTY ENGINEER,ASSISTANT ENGINEER', 'CHECKED', 'Pending for Approval', 'EXECUTIVE ENGINEER', 'APPROVED', 'Forward,Reject');

#DOWN
delete from EG_WF_MATRIX where  OBJECTTYPE='WorkCompletionDetail';




















