#UP
insert into eg_script
   (ID, NAME, SCRIPT_TYPE, SCRIPT, START_DATE, END_DATE)
 Values
   (eg_script_seq.nextVal, 'Pension.ComputeGratuity', 'python', 'from java.math import BigDecimal
from org.egov.pension.common import PensionConstants
from java.lang import Double
ret_grat=None
if(type==PensionConstants.RETIREMENT):    
    ret_grat=(head1Amt+head2Amt+head3Amt+head4Amt+head5Amt)*(noOfHalfYear/Double.valueOf(''4''))
if(type==PensionConstants.DEATH):    
    ret_grat=2*((head1Amt+head2Amt+head3Amt+head4Amt+head5Amt)*(noOfHalfYear/Double.valueOf(''4'')))
print ret_grat 
result=ret_grat',TO_DATE('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('01/01/2100 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
/* 
-- Already exists in database scripts
INSERT INTO EGW_STATUS
	(ID, MODULETYPE, DESCRIPTION, LASTMODIFIEDDATE, CODE, ORDER_ID) 
VALUES 
	(SEQ_EGW_STATUS.NEXTVAL,'Gratuity','Initiated',SYSDATE,'Initiated',1);

INSERT INTO EGW_STATUS
	(ID, MODULETYPE, DESCRIPTION, LASTMODIFIEDDATE, CODE, ORDER_ID) 
VALUES 
	(SEQ_EGW_STATUS.NEXTVAL,'Gratuity','Approved',SYSDATE,'Approved',2);

INSERT INTO EGW_STATUS
   (ID, MODULETYPE, DESCRIPTION, LASTMODIFIEDDATE, CODE, ORDER_ID)
 VALUES
   (SEQ_EGW_STATUS.NEXTVAL, 'Gratuity','Rejected', SYSDATE, 'Rejected',3);

INSERT INTO EGW_STATUS
   (ID, MODULETYPE,CODE , DESCRIPTION, LASTMODIFIEDDATE,ORDER_ID)
 VALUES
   (SEQ_EGW_STATUS.NEXTVAL,'PENSION', 'Created','Created', SYSDATE,1);

INSERT INTO EGW_STATUS
   (ID, MODULETYPE,CODE , DESCRIPTION, LASTMODIFIEDDATE,ORDER_ID)
 VALUES
   (SEQ_EGW_STATUS.NEXTVAL, 'PENSION', 'Approved', 'Approved', SYSDATE,2);

INSERT INTO EGW_STATUS
   (ID, MODULETYPE,CODE , DESCRIPTION, LASTMODIFIEDDATE,ORDER_ID)
 VALUES
   (SEQ_EGW_STATUS.NEXTVAL, 'PENSION', 'Rejected', 'Rejected', SYSDATE,3);

-- Added under database
insert into EG_DISBURSEMENT_MODE(id,type) values(SEQ_EG_DISBURSEMENT_MODE.nextval, 'cash');
insert into EG_DISBURSEMENT_MODE(id,type) values(SEQ_EG_DISBURSEMENT_MODE.nextval, 'cheque');
insert into EG_DISBURSEMENT_MODE(id,type) values(SEQ_EG_DISBURSEMENT_MODE.nextval, 'directbank');
*/
insert into EGPEN_BASIC_COMPONENTS(ID, HEAD1_AMT, HEAD2_AMT, HEAD3_AMT, HEAD4_AMT, HEAD5_AMT) values (SEQ_EGPEN_BASIC_COMPONENTS.nextval,3000,200,500,100,100);

INSERT INTO EGPEN_PENSIONER_CATEGORY(ID,NAME)
VALUES(SEQ_EGPEN_PENSIONER_CATEGORY.NEXTVAL,'Teacher');

INSERT INTO EGPEN_PENSIONER_CATEGORY(ID,NAME)
VALUES(SEQ_EGPEN_PENSIONER_CATEGORY.NEXTVAL,'Other');

INSERT INTO EGPEN_PAY_COMMISSION(ID,NAME,CODE,EFFECTIVE_FROM)
VALUES(SEQ_EGPEN_PAY_COMMISSION.NEXTVAL,'5th Pay Commission','5th PC','01-Jan-2001');

INSERT INTO EGPEN_PAY_COMMISSION(ID,NAME,CODE,EFFECTIVE_FROM)
VALUES(SEQ_EGPEN_PAY_COMMISSION.NEXTVAL,'6th Pay Commission','6th PC','01-Jan-2012');


INSERT INTO EGPEN_PENSIONER_HEADER (ID, EMP_ID, EMP_CODE, PENSIONER_NUMBER, PENSIONER_NAME, DATE_OF_BIRTH, 
DATE_OF_APPOINTMENT, DATE_OF_RETIREMENT, NET_QUALIFYING_SERVICE, DEPARTMENT_ID, DESIGNATION_ID, 
PAYSCALE_ID, GRADE_ID, STATUS_ID, COMMUTATION_OPTED, DISBURSEMENT_TYPE_ID, PEN_BANK_DETAILS_ID, COMPONENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE,
PAYMENT_ORDERNO,REGISTER_SLNO,ISWORKING,PENSIONER_CATEGORY_ID,PAY_COMMISSION_ID,ISPENSION_STOPPED)
VALUES (SEQ_EGPEN_PENSIONER_HEADER.NEXTVAL,1,'100','P-01','VIMAL KISHORE','01-Oct-1964',
'19-Nov-1985','31-Mar-2012',27,10,1,NULL,NULL,(Select id from EGW_STATUS where moduletype='Pension' and code='CREATED'),'Y',
(select id from EG_DISBURSEMENT_MODE where type='cheque'),null,(select id from EGPEN_BASIC_COMPONENTS where HEAD1_AMT='3000'),1,1,sysdate,sysdate,
'P1234','R1234','N',
(select id from EGPEN_PENSIONER_CATEGORY where name ='Teacher' ),(select id from EGPEN_PAY_COMMISSION where name ='5th Pay Commission' ),'N');

#DOWN

delete from eg_script where name='Pension.ComputeGratuity';
delete from EGW_STATUS where moduletype in ('Gratuity','PENSION') and code in ('Initiated','Approved','Created','Rejected');
delete from EG_DISBURSEMENT_MODE;
delete from EGPEN_BASIC_COMPONENTS;
delete from EGPEN_PENSIONER_HEADER ;
DELETE FROM EGPEN_PENSIONER_CATEGORY WHERE NAME IN ('Teacher','Other');
DELETE FROM EGPEN_PAY_COMMISSION WHERE NAME IN ('5th Pay Commission','6th Pay Commission');
