insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Create-AssetCategory'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Update-AssetCategory'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='View-AssetCategory'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Edit-AssetCategory'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Result-AssetCategory'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Search and View Result-AssetCategory'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Search and Edit Result-AssetCategory'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Search and View-AssetCategory'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='New-Asset'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Search and Edit-AssetCategory'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Get-Parent-Accounts'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Get-Master-Records'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Delete-Category-Property'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Get-Category-Properties'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Search and Edit Result-Asset'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Get-Boundaries'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Search and Edit-Asset'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='New-AssetCategory'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Create-Asset'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Update-Asset'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='View-Asset'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Edit-Asset'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Result-Asset'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Search and View-Asset'));
insert into eg_roleaction(roleid,actionid) values ((select id from eg_role where name='Asset Administrator'),(select id from eg_action where name='Search and View Result-Asset'));
