--------------------------- START ------------------------------
insert into EG_APPCONFIG (ID,KEY_NAME,DESCRIPTION,VERSION,MODULE) 
values (nextval('seq_eg_appconfig'),'Asset_category_code_creation_mode','Asset category code to be autogenerated',0,(select id from eg_module where name='Asset Management'));
--------------------------- END --------------------------------

--------------------------- START ------------------------------
insert into EG_APPCONFIG_VALUES (ID,KEY_ID,EFFECTIVE_FROM,VALUE,VERSION) 
values (nextval('seq_eg_appconfig_values'),
(select id from EG_APPCONFIG where KEY_NAME ='Asset_category_code_creation_mode'),current_date,'Auto',0);
--------------------------- END --------------------------------

--Rollback DELETE FROM EG_APPCONFIG_VALUES where KEY_ID = (select id from EG_APPCONFIG where KEY_NAME ='Asset_category_code_creation_mode');
--Rollback DELETE FROM EG_APPCONFIG where KEY_NAME = 'Asset_category_code_creation_mode';
